### ISSUE TITLE
Add a README.md file

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1]

**Comment by kevinchalet** [comment]
Assigned to you, @Bartmax :smile:

**Comment by Bartmax** [comment]
Here is a draft https://github.com/openiddict/core/pull/12. How can I link the PR to this issue ?

**Comment by kevinchalet** [comment]
Done: https://github.com/openiddict/core/commit/ae38ba119360ae2d30f34f15bb952d55793a9a49 :tada:
