### ISSUE TITLE
Implement client_secret hashing/key derivation

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#10]
Currently, `client_secret` is stored as-is in the database. Implementing key derivation + hashing would help mitigating the risks of a database leakage and make brute force attacks harder.

aspnet/Identity has a password hasher that could be used for this exact purpose: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/PasswordHasher.cs. Sadly, it requires a `TUser` parameter, which doesn't seem really appropriate.

@henkmollema created a `Crypto` package for that, but it's for ASP.NET 5 beta6 and uses deprecated CoreFX crypto packages: https://github.com/henkmollema/CryptoHelper

/cc @Bartmax

**Comment by Bartmax** [comment]
Does the aspnet/identity `PasswordHasher` even use the `user` ? can't see any reference on code.

**Comment by henkmollema** [comment]
@PinpointTownes you could have just asked :smile: 

~~What do you mean by deprecated CoreFX packages?~~
I'll update the package.

**Comment by henkmollema** [comment]
@Bartmax the Identity implementation is indeed somewhat strange. The reason behind it is to provide access to the user when implementing your own password hasher. See https://github.com/aspnet/Home/issues/765#issuecomment-124702657.

**Comment by henkmollema** [comment]
@PinpointTownes I've updated [CryptoHelper](https://www.nuget.org/packages/CryptoHelper) in case you still need it.

**Comment by kevinchalet** [comment]
@henkmollema fantastic, thanks! :+1:

**Comment by kevinchalet** [comment]
Re-assigned.

@henkmollema surprisingly, the following snippet crashes on DNX CLR when using the latest version (but it used to work with the first version):

``` csharp
var hash = Crypto.HashPassword("secret");
Debug.Assert(Crypto.VerifyHashedPassword(hash, "secret"));
```

FYI, `PasswordHasher` works as expected:

``` csharp
var hasher = new PasswordHasher<object>();
var hash = hasher.HashPassword(null, "secret");
Debug.Assert(hasher.VerifyHashedPassword(null, hash, "secret") == PasswordVerificationResult.Success);
```

**Comment by henkmollema** [comment]
Oops, I introduced a bug in reading some copying of byte arrays. I'll fix it ASAP.

**Comment by henkmollema** [comment]
@PinpointTownes fixed: https://www.nuget.org/packages/CryptoHelper/1.0.0-rc1-build03 :sparkles:

**Comment by kevinchalet** [comment]
Woot, thanks, it now works like a charm! :+1:

**Comment by kevinchalet** [comment]
Done: https://github.com/openiddict/core/commit/4a318920caa3ab7a2bdb6f634148bf2a5db461b6.
