### ISSUE TITLE
ArgumentNullException when null email

### ISSUE THREAD

**Issue by smbecker** [openiddict/openiddict-core#101]
When the 'email' scope is requested and the user does not have an email address on file, then a ArgumentNullException is thrown. Perhaps just add a string.IsNullOrEmpty check [here](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/OpenIddictManager.cs#L90)?

**Comment by kevinchalet** [comment]
Thanks for reporting this bug :smile: 

It should be fixed by https://github.com/openiddict/openiddict-core/commit/5c09b2ef8ec373c6d5fd19ea46b77b6a27abe49a.
