### ISSUE TITLE
Automatically disable the incompatible options when enabling the degraded mode

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1022]
When enabling the degraded mode, the following options should be automatically set:
  - `OpenIddictServerOptions.DisableAuthorizationStorage = true`
  - `OpenIddictServerOptions.DisableTokenStorage = true`
  - `OpenIddictServerOptions.IgnoreEndpointPermissions = true`
  - `OpenIddictServerOptions.IgnoreGrantTypePermissions = true`
  - `OpenIddictServerOptions.IgnoreScopePermissions = true`
  - `OpenIddictServerOptions.UseReferenceAccessTokens = false`
  - `OpenIddictServerOptions.UseReferenceRefreshTokens = false`
  - `OpenIddictServerOptions.UseRollingRefreshTokens = true`

**Comment by askalione** [comment]
@kevinchalet, and `OpenIddictServerOptions.UseSlidingExpiration = false`, because DisableTokenStorage requires this

**Comment by kevinchalet** [comment]
Actually, when token storage is disabled, you can either disable sliding expiration or use rolling refresh tokens. With the degraded mode enabled, the best option is likely to use rolling tokens and keep sliding expiration enabled.

**Comment by askalione** [comment]
Got it, thanks.
