### ISSUE TITLE
Should additional languages be supported?

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1051]
OpenIddict 3.0 currently supports the following locales:

  - Arabic
  - Chinese (simplified and traditional)
  - Deutsch
  - Dutch
  - English (default culture)
  - French
  - Gujarati
  - Hindi
  - Italian
  - Spanish
  - Turkish

Additional cultures will be added in a future release:
  - Russian
  - Ukrainian

**Comment by kevinchalet** [comment]
Spanish support will be added by @Bartmax as part of this PR: https://github.com/openiddict/openiddict-core/pull/1054.

**Comment by kevinchalet** [comment]
@kinosang is providing simplified/traditional Chinese translations something that you could be interested in?

At the time of writing, there are ~120 strings to translate. Translations that are already supported can be found here: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.Abstractions/Resources/xlf

Please let me know if you're interested 😃 

(note: XLF files can be easily opened in tools like Poedit if you prefer a GUI-only approach)

**Comment by kinosang** [comment]
@kevinchalet yep. I'll create a PR for that today.

**Comment by serkanz** [comment]
I could provide Turkish translations if it's appropriate

**Comment by kevinchalet** [comment]
I added the [OpenIddictResources.tr.xlf file](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf). To contribute to the Turkish translation, please fork the repo and send a PR 😃

**Comment by serkanz** [comment]
> I added the [OpenIddictResources.tr.xlf file](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Resources/xlf/OpenIddictResources.tr.xlf). To contribute to the Turkish translation, please fork the repo and send a PR 😃 

It's coming in a few hours 👍😀
