### ISSUE TITLE
Mark the OpenIddict.Quartz package as shipping

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1053]
`OpenIddict.Quartz` currently depends on packages that are not available on NuGet.org yet (which may take quite some time, as the [`Quartz.Extensions.Hosting`](https://www.nuget.org/packages/Quartz.Extensions.Hosting) package's ownership needs to be transferred first to the Quartz org). Once they are available, we should mark the package as shipping and remove the Quartz.NET nightly builds feed from `NuGet.config`.

**Comment by lahma** [comment]
Just to update the status, yesterday 2020-09-18 I sent an email to NuGet support as 30 days had passed which is a requirement for package dispute. I'm waiting for their reply and actions.

**Comment by kevinchalet** [comment]
Thanks for the update! Let's hope they'll make the right decision 😄

**Comment by kevinchalet** [comment]
@lahma did you hear back from the NuGet folks? If not, I know a few people in the NuGet team that could help speed up the process 😄

**Comment by lahma** [comment]
This morning got the following status update:

> We’re working internally on the best course of action in this case. We’ll get back to you within a couple of days regarding next steps.
 
> Thank you for your patience.

**Comment by lahma** [comment]
And this morning the following status update arrived:

> We have sent an email to the owners of the package.
> If they do not respond within 7 days, we will add you as a co-owner of the package.

**Comment by kevinchalet** [comment]
Today's the day 🤞

**Comment by lahma** [comment]
We'll see. If I don't hear anything this night I'll send a follow-up tomorrow morning 🙂 

**UPDATE**: I sent them a reminder...

**Comment by kevinchalet** [comment]
![image](https://user-images.githubusercontent.com/6998306/94849778-39356100-0426-11eb-8a50-892246fe139f.png)

![](https://media.giphy.com/media/4xZmzEuuQ8wnK/giphy.gif)

**Comment by lahma** [comment]
And the 3.2 release is now live! 🎉 🚀
