### ISSUE TITLE
Access to the path error, but doesnt exist?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#106]
If i run `dotnet publish` and upload this to my server, and then try to run this code via IIS, i get the error below, however, if i run the .exe file using command line window, it works, and the file is wrote to a completely different location?

Here is the location when running the exe via command prompt

> info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
>       User profile is available. Using 'C:\Users\Administrator\AppData\Local\ASP
> .NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at
>  rest.
> info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
>       A new RSA key was automatically generated, added to the signing credential
> s list and persisted on the disk: C:\Users\Administrator\AppData\Local\ASP.NET\a
> spnet-contrib\oidc-server\ffde9cd9-724d-4844-b8fc-74f68c5c0ca7.key.

Any ideas?  Running on Windows Server 2012, using runtime win8-x64

> :(  Oops.
> 500 Internal Server Error
> System.UnauthorizedAccessException
> Access to the path 'C:\Windows\TEMP\ASP.NET\aspnet-contrib\oidc-server\038a06fc-bc2c-4761-8f84-955418b8a16d.key' is denied.
> at System.IO.__Error.WinIOError(int errorCode, string maybeFullPath) 
> at System.IO.FileStream.Init(string path, FileMode mode, FileAccess access, int rights, bool useRights, FileShare share, int bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)
> at System.IO.FileStream..ctor(string path, FileMode mode, FileAccess access, FileShare share) 
> at System.IO.FileInfo.Open(FileMode mode, FileAccess access, FileShare share) 
> at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware..ctor(RequestDelegate next, IOptions<OpenIdConnectServerOptions> options, IHostingEnvironment environment, ILoggerFactory loggerFactory, IDistributedCache cache, HtmlEncoder htmlEncoder, UrlEncoder urlEncoder, IDataProtectionProvider dataProtectionProvider)
> --- exception rethrown --- 
> at Microsoft.Extensions.Internal.ConstructorMatcher.CreateInstance(IServiceProvider provider) 
> at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters) 
> at Microsoft.AspNetCore.Builder.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next) 
> at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build() 
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> Show raw exception details
> .NET Framework CLR version 4.0.30319.42000   |   DNX x64 version 4.0.0.0   |   Microsoft.AspNetCore.Hosting version 1.0.0-rc3-20681   |   Windows 6.3.9600   |   Need help?

**Comment by kevinchalet** [comment]
Same root cause as https://github.com/openiddict/openiddict-core/issues/90#issuecomment-213442540.

I'm considering removing the automatic key generation feature from ASOS/OpenIddict as it seems impossible to find an appropriate keys folder that works everywhere. This feature is quite useful as you don't have to manually create a X509 certificate, but it's causing too much pain when going to production.

**Comment by Gillardo** [comment]
THANKS @PinpointTownes

**Comment by kevinchalet** [comment]
Moved to https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/269.

**Comment by Bartmax** [comment]
Maybe we should make that an explcit call and provide the folder? Or we can make it optional, catch the exception and tell how to fix it.

Like: OpenIddict failed to create the RSA Key on "{path}", most likely written permission. You can give writting permissions to folder or use .UseKeyGeneratorPath(path) and provide a path that has writting permissions. On production servers we recommend that you ... {insert recommendation here}

what do you think @PinpointTownes ?

**Comment by kevinchalet** [comment]
> Maybe we should make that an explcit call and provide the folder? Or we can make it optional, catch the exception and tell how to fix it.

The cool thing about this feature is that it was fully automatic: you didn't have to configure anything. Having to configure this feature seems to defeat its entire purpose. And in this case, it's probably "as complicated" as configuring an embedded X509 certificate, which is what we recommend when going live.

Do you strongly feel X509 certificates are too hard to configure?
Here's the syntax I'd like to use:

``` csharp
app.UseOpenIddict(builder => {
    // Register the embedded X509 certificate used to sign the JWT tokens.
    // Note: this certificate is a TEST certificate: NEVER USE IT ON PRODUCTION.
    // Instead, generate a self-signed certificate using Pluralsight's self-cert utility:
    // https://s3.amazonaws.com/pluralsight-free/keith-brown/samples/SelfCert.zip
    builder.UseCertificate(
        assembly: typeof(Startup).GetTypeInfo().Assembly,
        resource: "Mvc.Server.Certificate.pfx",
        password: "OpenIddict");

    builder.Options.AllowInsecureHttp = true;
});
```

**Comment by Bartmax** [comment]
the certificate problem is that you must create and add to your server, those are steps I really don't want to do when developing, i like the automatic, but if people have a problem right now is hard for them to understand what's wrong. I guess a proper error message will be enough. I agree that configuring the folder has no sense, because is not what we want on production.

**Comment by kevinchalet** [comment]
> the certificate problem is that you must create and add to your server, those are steps I really don't want to do when developing

Ideally:
- When testing OpenIddict, you don't have to configure anything as the default samples use an embedded test certificate, that doesn't have to be persisted in the machine store.
- When creating your own project based on OpenIddict, you can generate your own certificate using a tool like [`self-cert`](https://s3.amazonaws.com/pluralsight-free/keith-brown/samples/SelfCert.zip) (please give it a try and tell me what you think) and embed it in the assembly. Nothing to persist in the certificate store in this scenario.
- When going live, the certificate should be stored in the machine store, but storing it as an embedded resource should also be supported for convenience.

Isn't that a good compromise?

**Comment by joel00** [comment]
I'm trying to use the suggested configuration for AddSigningCertificate():

`app.UseOpenIddict(builder => {
    builder.UseCertificate(
        assembly: typeof(Startup).GetTypeInfo().Assembly,
        resource: "Mvc.Server.Certificate.pfx",
        password: "OpenIddict");

```
builder.Options.AllowInsecureHttp = true;
```

});`

as follows:

`services.AddOpenIddict<ApplicationDbContext>()
                .AddMvcBinders()
                .EnableAuthorizationEndpoint("/connect/authorize")
                .EnableLogoutEndpoint("/connect/logout")
                .EnableTokenEndpoint("/connect/token")
                .EnableUserinfoEndpoint("/connect/userinfo")

```
            .AllowAuthorizationCodeFlow()
            .AllowPasswordFlow()
            .AllowRefreshTokenFlow()

            // .RequireClientIdentification()
            // .DisableHttpsRequirement()    

            .AddSigningCertificate(
                assembly: typeof(Startup).GetTypeInfo().Assembly,
                resource: "tokenCert.pfx",
                password: "test password"
            );`
```

but I'm getting:

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --
-> System.InvalidOperationException: The certificate was not found in the given assembly. 

Where should I have the pfx file?

**Comment by kevinchalet** [comment]
Make sure your `project.json` has an `embed` section: https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/project.json#L8

Your resource name must also be prefixed by the project name. E.g `[name].tokenCert.pfx`

**Comment by joel00** [comment]
Thanks for answering so fast.... 

I added the "embed" section in my project.json; double check my assembly name and prefixed MyProject.tokenCert.pfx and I'm getting the same error.

I've also downloaded your Certificate.pfx but nothing.

Anything else that I'm missing?

**Comment by joel00** [comment]
Sorry, I misplaced the embed section x( now i't working  :)
