### ISSUE TITLE
Use both reference tokens and JWT in same application

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [openiddict/openiddict-core#1070]
Hello!
I’m wondering if it is possible to use both reference tokens and JWT tokens in the same project. I need to be able to revoke a reference token once it has been validated and exchange it for a JWT token. This step is crucial in ensuring my project’s adherence to the [cmi5 standard](http://aicc.github.io/CMI-5_Spec_Current/). Thank you!!!

**Comment by kevinchalet** [comment]
Hey,

This [blog post](https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/) and its "Enabling reference tokens is no longer required to use immediate access token revocation" chapter should answer your question 😃

**Comment by ssimo3lsuhsc** [comment]
I do not need revocation on all API calls. As a matter of fact, if the revocation is done on all API calls, my application is not cmi5-compliant. need to revoke the token if and only if a method is called, and I haven't yet found documentation of a method `revoke()` or anything similar in the documentation.

I also apparently have to use the `Basic ` (not `Bearer`) authentication scheme.

**Comment by kevinchalet** [comment]
You probably misread the post: it’s the validation that is per-request (if you explicitly enable authorization and/or token entry validation) not the revocation.
