### ISSUE TITLE
Azure BLOB storage for persisting keys

### ISSUE THREAD

**Issue by BaumTom** [openiddict/openiddict-core#1076]
Hi,

I've started a trial to migrate to version 3. So far everything the migration went smoothly. The problem I have is that I want to share the encryption key with other micro services. 

I've used opaque tokens and with version 3 I think the default are JWTs.

With the opaque tokens I've just need to add following snippet so that the keys were share via Azure:

```c#
            //If tokens need to be validated in a separate resource server, configure a shared ASP.NET Core DataProtection with shared key store and application name
            //See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.1&tabs=aspnetcore2x#setapplicationname
            var storageAccount = CloudStorageAccount.Parse(
                "DefaultEndpointsProtocol=https;AccountName=aaa;AccountKey=...;EndpointSuffix=core.windows.net");
            var container = storageAccount.CreateCloudBlobClient().GetContainerReference("default");

            services.AddDataProtection()
                .PersistKeysToAzureBlobStorage(container, "aaa")
                .SetApplicationName("XYZ");
```

Is this approach still valid with v3 and JWTs?  
How do I need to pass they keys to the options? In the examples I only found the development keys.

```c#
...
                    // Register the signing and encryption credentials.
                    options.AddSigningKey(???)
	                    .AddEncryptionKey(???)
...
```

Thanks in advance,
Thomas

**Comment by kevinchalet** [comment]
Hey,

> Is this approach still valid with v3 and JWTs?

By default, it has no effect as OpenIddict 3.0 doesn't use Data Protection tokens by default. Read https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/ for more information on how to enable Data Protection in 3.0.

> How do I need to pass they keys to the options? In the examples I only found the development keys.

https://github.com/openiddict/openiddict-core/issues/976#issuecomment-643305644

**Comment by BaumTom** [comment]
Thanks, that already helps a lot.

As my app is still in development, I can switch to JWTs at any time. Would you prefer the JWTs over the Data Protection tokens?

**Comment by kevinchalet** [comment]
Data Protection tokens are the best option. If you need JWT access tokens, you can use DP for the other token types and JWT only for access tokens using `options.UseDataProtection().PreferDefaultAccessTokenFormat();`.

**Comment by BaumTom** [comment]
Thanks, then I'll continue to use DP tokens.

In my other micro services, where the validation happens, I followed this description (in v2): [Resource server shared ASP.NET Core DataProtection](https://openiddict.github.io/openiddict-documentation/configuration/token-setup-and-validation.html#resource-server-shared-aspnet-core-dataprotection)

```c#
			services.AddOpenIddict()
				//This adds a "Bearer" authentication scheme
				.AddValidation(options =>
				{
					options.UseDataProtection();
				});

			//Optionally set Bearer token authentication as default
			services.AddAuthentication(options =>
			{
				options.DefaultAuthenticateScheme = "Bearer";
				options.DefaultChallengeScheme = "Bearer";
			});
```

Do you also have some guidance what needs to be changed so that this works with v3? I've already investigated but couldn't find any solution. At the moment I get:

```
System.InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Bearer",...)?
```

**Comment by kevinchalet** [comment]
Your configuration is invalid. Take a look at https://github.com/openiddict/openiddict-samples/commit/d0802061c087c3ba1e9a6854450a9af38a45991a for a sample using local token validation.
