### ISSUE TITLE
How to server multiple sites from same resource server site?

### ISSUE THREAD

**Issue by DreamingDevs** [openiddict/openiddict-core#108]
I have TWO sites, `http://localhost:5000/` (MVC + WebAPI + Resource Server) and `http:localhost:63845/` (MVC Site). I have all the OpenIddict code in 5000 site which was enabled for CORS. I wanted to get token and validate all the requests from 63485 site as well. So I want to authenticate users from both sites, how to do that?

I have following code in startup.cs - 

```
            app.UseOpenIddictCore(builder =>
                {
                    builder.Options.UseJwtTokens();
                    builder.Options.AllowInsecureHttp = true;
                    builder.Options.ApplicationCanDisplayErrors = true;
                });

                var Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = context => Task.FromResult(0)
                };

                // use jwt bearer authentication
                app.UseJwtBearerAuthentication(new JwtBearerOptions
                {
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                    Audience = Configuration["BearerAuthentication:Audience"],
                    Authority = Configuration["BearerAuthentication:Authority"],
                    Events = Events
                });
```

And I have following in appsettings.json - 

>   "BearerAuthentication": {
>     "Audience": "http://localhost:5000/",
>     "Authority": "http://localhost:5000/"
>   }

Now I do overridden OpenIddictManager - 

```
  public class CustomOpenIddictManager : OpenIddict.OpenIddictManager<UserModel, Application>
    {
        public CustomOpenIddictManager(OpenIddictServices<UserModel, Application> services)
            : base(services)
        {
        }

        public override async Task<ClaimsIdentity> CreateIdentityAsync(UserModel user, IEnumerable<string> scopes)
        {
            var identity = await base.CreateIdentityAsync(user, scopes);

            var nameClaim = new Claim("givenName", user.FirstName + ' ' + user.LastName)
                .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
                                 OpenIdConnectConstants.Destinations.IdentityToken);

            identity.AddClaim(nameClaim);

            var emailClaim = new Claim("email", user.Email)
               .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
                                OpenIdConnectConstants.Destinations.IdentityToken);

            identity.AddClaim(emailClaim);
            return identity;
        }
    }
```

**Comment by kevinchalet** [comment]
Not sure to fully understand your question. Are you trying to add a new OAuth2/OpenID Connect client? Or a new API (= resource server)?

**Comment by DreamingDevs** [comment]
I have two sites hosted on 5000 and 63845, Both sites got AngularJS pages which will be interacting with WebAPI (which is also hosted in 5000). Now my Web API is protected by Authorize attribute through OpenIddict. And I have `/connect/token` endpoint in 5000.  I was able to get token in below way and use the same in 5000 hosted pages and everything is working fine.

![image](https://cloud.githubusercontent.com/assets/5579127/15222545/e2169476-188d-11e6-9939-f7ccb0886f6f.png)

Now pages in 63845 were able to browse anonymous endpoints in 5000, but not authorized ones, they are getting 401 response.

So what should I do in this scenario?

**Comment by kevinchalet** [comment]
Can you please share the token requests you're sending and the tokens you get?
You should also enable logging to determine why the token is rejected.

**Comment by DreamingDevs** [comment]
I updated my previous answer with a screenshot. Now I tried to get different tokens using different `resource` (one for 5000 and other for 63845). I was able to get 5000 token working, but not 63845 token from that site. I mean 5000 hosted pages working with token got from resource - 5000. But 63845 pages were not able to access secured endpoints using token got from resource - 63845.

**Comment by kevinchalet** [comment]
> I was able to get 5000 token working, but not 63845 token from that site. I mean 5000 hosted pages working with token got from resource - 5000.

That's totally expected, `resource` identifies the resource server (= the API), not the client that makes the request. Use `resource=http://localhost:5000/` in both apps and it should work.

**Comment by DreamingDevs** [comment]
Thanks @PinpointTownes , it works.
