### ISSUE TITLE
Authenticating remote API/resource server using client credential flow not authenticating.

### ISSUE THREAD

**Issue by davidvr2** [openiddict/openiddict-core#1080]
I have searched high and low and tried many different things and so far I cannot get an authorized response if my Authorization server and Resource server isn't the same application. So my latest attempt is using the Aridka sample client and server as is. That works perfectly together.
Then from what I learnt [here](https://github.com/openiddict/openiddict-core/issues/901) I added AddJwtBearer to my startup.
My startup can be found [here](https://ragingriver-my.sharepoint.com/:u:/g/personal/davidvr_ragingriver_co_za/EVuskSchs49JkuZVYKuyVtsBPZqXdZHPnZqZ79pggHF4gA?e=ThBrwc)
Then I added the Authorize annotation to my Get in my WeatherForecastController which can be found [here](https://ragingriver-my.sharepoint.com/:u:/g/personal/davidvr_ragingriver_co_za/EYK_sqsaG6JFta6dCtJt2ucB_ClHkZMV_MkYQQItAJhQxA?e=EWzOwi)

I updated my Program.cs [here](https://ragingriver-my.sharepoint.com/:u:/g/personal/davidvr_ragingriver_co_za/Eax2jpE7fDNFsD7T7c_DP-YBTKmti14EKskfJ6VHn3yafA?e=AfmMnP) in the Aridka.Client to first call the Aridka.Server like it usually does, and then call my new API. First call works perfectly, second one returns unauthorized.

Logs from Aridka.Server can be found [here](https://ragingriver-my.sharepoint.com/:t:/g/personal/davidvr_ragingriver_co_za/EXoQaHdHsedFkQpRKrS23FoBSXAIzhzYjmJdJWXgprBfGw?e=HgGbNA)

**Comment by kevinchalet** [comment]
Without seeing your OIDC server config, hard to say what's going on.

**Comment by kevinchalet** [comment]
I updated the Zirku.Api2 sample to show how to configure local validation in a separate project: https://github.com/openiddict/openiddict-samples/commit/d0802061c087c3ba1e9a6854450a9af38a45991a

**Comment by davidvr2** [comment]
Sorry for the delay in getting back to you. Has been a crazy couple of days. Like I said the server is the Aridka.Server sample as is. I didn't make any changes there except adding AddDevelopmentSigningCredentials
`services.AddOpenIddict()
...
                .AddServer(options =>
                {
...
                    options.AddDevelopmentSigningCertificate();
...
                })`

The whole server can be found [here](https://ragingriver-my.sharepoint.com/:f:/g/personal/davidvr_ragingriver_co_za/EqniCndUZyZGk8WiRDfPanYBmishru4hRmPY0SY06EyKRw?e=bpyYFq)

Thanks a lot for the update on the Zirku.Api2 project. I will look into it and I am sure I will be able to figure it out
