### ISSUE TITLE
Renaming Tables

### ISSUE THREAD

**Issue by DaljitBhail** [openiddict/openiddict-core#1082]
struggling to rename the new tables in Ver 3. If I reference models namespace I can only change the old table names. How do I change the new table names to conform with naming standards:

`
     protected override void OnModelCreating(ModelBuilder modelBuilder)
        { 
  modelBuilder.Entity<OpenIddictApplications>().ToTable(string.Format("{0}_{1}", IDENTITY_PREFIX, OPENIDDICT_APPLICATION));
            modelBuilder.Entity<OpenIddictAuthorizations>().ToTable(string.Format("{0}_{1}", IDENTITY_PREFIX, OPENIDDICT_AUTHORIZATION));
            modelBuilder.Entity<OpenIddictScopes>().ToTable(string.Format("{0}_{1}", IDENTITY_PREFIX, OPENIDDICT_SCOPE));
            modelBuilder.Entity<OpenIddictTokens>().ToTable(string.Format("{0}_{1}", IDENTITY_PREFIX, OPENIDDICT_TOKEN));`

**Comment by kevinchalet** [comment]
Table names haven't changed, only the models have, and it shouldn't have any impact on the names used for the SQL tables.

**Comment by DaljitBhail** [comment]
The entity OpenIddictApplications creates a table called OpenIddictApplications. I want to call it CLIENTXXX_123_OpenIdDictApplications. But in ApplicationDbContext the entity OpenIddictApplications  does not exist. Is there a specific namespace or nuget package I need to install?  I note that package OpenIdDict.Models nuget is still in ver.2 and refers to OpenIddictApplication and not OpenIddictApplications

**Comment by kevinchalet** [comment]
Did you read https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/ ?

**Comment by DaljitBhail** [comment]
I have gone through it and excuse me as I cannot see the answer. 

In the old version I had a reference to OpenIddict.EntityFrameworkCore.Models and could change the table name of each of the models. 

I have installed every package there is and I still cannot find a reference to these models. If I reference the old models, it creates two sets of tables.

All I want to do is change the name of the database tables for these models.

**Comment by kevinchalet** [comment]
![image](https://user-images.githubusercontent.com/6998306/92271707-93570b00-eee8-11ea-8cc0-def386712a4e.png)

**Comment by DaljitBhail** [comment]
Don't worry about it...I give up !  

You made an incredible solution with 2.0.0-rc3-final. Worked so well with Angular and Nativescript. Hat off to you. I even wrote a whole load of blogs at Nativescript on how to use tokens. 

But this new version is painful.  Takes forever to work out how to use int as the primary key and now trying to change the database tables names. Following you logic I would have expected to see the models in OpenIddict.EntityFrameworkCore.Models. But I just get "CS0246 C# The type or namespace name could not be found (are you missing a using directive or an assembly reference?)"

Thank you for your time.

**Comment by kevinchalet** [comment]
> Following you logic I would have expected to see the models in OpenIddict.EntityFrameworkCore.Models.

They are definitely part of this package: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.EntityFrameworkCore.Models

> I note that package OpenIdDict.Models nuget is still in ver.2 and refers to OpenIddictApplication and not OpenIddictApplications

OpenIddict has never used the plural form for the entity names, so either you had custom entities named this way or you were doing something weird. In both cases, you can't blame 3.0 for that.

Regarding `OpenIddict.Models`, it was removed in 2.0 RC3: https://github.com/openiddict/openiddict-core/issues/608
