### ISSUE TITLE
How to configure UseJwtBearerAuthentication on multiple application to use same token for authentication?

### ISSUE THREAD

**Issue by DreamingDevs** [openiddict/openiddict-core#109]
I am following this example - [http://capesean.co.za/blog/asp-net-5-jwt-tokens/](http://capesean.co.za/blog/asp-net-5-jwt-tokens/).

Now I have App1 which is giving token through `/Connect/Token/` endpoint (in App1). I will call this App1 endpoint and get token from App2 (i enabled CORS on App1). Now I want to use the same token to authenticate the call for Web API which is present in App2.

So basically I want to use Token (which I get from App1) in App2 Web Api through Authorize attribute. Please guide me on how to do that?

**Comment by kevinchalet** [comment]
The `resource` parameter supports multiple endpoints, just separate them with spaces and you'll get an access token targeting multiple audiences (= APIs)

e.g `resource=http://app1.domain.com/ http://app2.domain.com/`

**Comment by DreamingDevs** [comment]
In that case, having following code in App2 Startup would be enough? Audience and Authority pointing to App1 base url (because that is my authorization server).

My understanding is that there is no need to add OpenIddict in App2, is that right? Having App2 configured for JWT Bearer Authentication (with code below) should be fine.

```
  app.UseJwtBearerAuthentication(options =>
      {
           options.AutomaticAuthenticate = true;
           options.AutomaticChallenge = true;
           options.RequireHttpsMetadata = false;
           options.Audience = "http://localhost:58292/";
           options.Authority = "http://localhost:58292/";
       });
```

**Comment by kevinchalet** [comment]
Yep. Except the Authority property must point to your authorization server (that uses the port 5000 IIRC).

**Comment by DreamingDevs** [comment]
Yes, 5000 is my Auth Server, 58292 is my App2. So I am going to use following in App2 Startup.cs. 

```
app.UseJwtBearerAuthentication(options =>
      {
           options.AutomaticAuthenticate = true;
           options.AutomaticChallenge = true;
           options.RequireHttpsMetadata = false;
           options.Audience = "http://localhost:58292/";
           options.Authority = "http://localhost:5000/";
       });
```

I will try this suggestion and will keep you this thread posted with update. Thanks for the info.

**Comment by DreamingDevs** [comment]
Thanks @PinpointTownes, it worked. Thanks for your help and support.

**Comment by a-a-k** [comment]
> Thanks @PinpointTownes, it worked. Thanks for your help and support.

Could you provide your whole startup? I'm stuck on this
