### ISSUE TITLE
Client Secret decoding incorrectly

### ISSUE THREAD

**Issue by aviatoredb** [openiddict/openiddict-core#1093]
Building an OpenIdDict auth server using .Net Core 3.1 and OpenIdDict 3.0.0-beta3.20403.69
Testing with Postman

The request.ClientSecret is incorrect when evaluating in debugger.
[OpenIddictServerHandler.txt](https://github.com/openiddict/openiddict-core/files/5246954/OpenIddictServerHandler.txt)

I have implemented a server in degraded mode and have implements a custom IOpenIddictServerHandler<ValidateTokenRequestContext> to handle the client id
[Startup.txt](https://github.com/openiddict/openiddict-core/files/5246955/Startup.txt)
/secret validations.

The client secret is showing up with any '+' characters replaced with spaces.
Testing is pretty simple. I replaced my secret in postman with 'A+A' and is appears in my handler as 'A A'

I have attached my startup.cs and server handler code files.
thanks

**Comment by kevinchalet** [comment]
It's not an OpenIddict issue: Postman doesn't properly encode the `+` sign, which is sent as-is when using formurl encoding. Yet, it's the standard form of the "space" character, hence the behavior you're seeing.

See https://github.com/postmanlabs/postman-app-support/issues/8626 for more information.

**Comment by aviatoredb** [comment]
HUGE FACEPALM!  Thanks Kevin. I've bene banging my head on the wall looking for what I was doing wrong. Cheers

**Comment by kevinchalet** [comment]
You're welcome :smile:

If you found OpenIddict useful, please consider sponsoring me (or encouraging your company to do it) so I can dedicate more time to it: https://github.com/sponsors/kevinchalet

Cheers.
