### ISSUE TITLE
Incorrect DateTimeOffset values when using the Oracle MySQL provider

### ISSUE THREAD

**Issue by GDreyV** [openiddict/openiddict-core#1097]
Everything worked perfectly when I was in UTC-05 time zone. But when I moved to UTC+03 time zone I'm constantly getting an error:

> OpenIddict.Server.Internal.OpenIddictServerHandler: Error: The token request was rejected because the authorization code or the refresh token was expired.

exactly on the same code. The error occurs when I call token exchange endpoint. I checked database and all values there seems to be correct UTC values.

I found that the error was fired at AspNet.Security.OpenIdConnect.Server\src\AspNet.Security.OpenIdConnect.Server\OpenIdConnectServerHandler.Exchange.cs. But I'm not sure how to debug it.

**Comment by kevinchalet** [comment]
The check responsible of validating the expiration date is here: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/398c2ea282d671c4b160440f6c059248cf5cee0d/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Exchange.cs#L311-L324

Does it impact authorization codes created after changing the timezone or just the previously issued codes?

**Comment by GDreyV** [comment]
Yeah, I saw that code but didn't find a good way to debug it. I reproduce the problem performing clean login. I mean I remove all cookies and all tokens stored on the client side and start authorization from the very beginning. Also to be sure that it's not a cache I rebooted laptop.
I'm not sure if it's related but I'm using mysql database as a storage.

**Comment by kevinchalet** [comment]
Have you tried with 3.0's latest beta to see if you can reproduce it?

**Comment by GDreyV** [comment]
Sorry, it will take some time to migrate to the version 3.0... I'm in progress, will share update as it's ready. Do you have any migration guide?

**Comment by kevinchalet** [comment]
> Do you have any migration guide?

Sadly nope. If it's important for you or your company, consider [sponsoring me](https://github.com/sponsors/kevinchalet) so I can spend more time on things that could help the community.

**Comment by GDreyV** [comment]
Sorry, my company is pretty small but I'll try to setup sponsoring out of the pocket because you are doing a really great job!

Ok, I migrated to the version 3.0, thanks a lot for descriptive errors messages. And I still see the same error. I checked authorization code flow using samples and didn't face such issue. So it's something specific for my configuration. I will try to check sample with mysql database. Also I'm using angular client but not sure if it might be the reason.

**Comment by kevinchalet** [comment]
> Sorry, my company is pretty small but I'll try to setup sponsoring out of the pocket because you are doing a really great job!

Thanks! ❤️ 

> So it's something specific for my configuration. I will try to check sample with mysql database.

Do you use EF/EF Core or custom stores? If you use EF Core, do you use the Oracle provider or the Pomelo provider?

**Comment by GDreyV** [comment]
I'm using MySql.Data.EntityFrameworkCore by Oracle.

**Comment by kevinchalet** [comment]
Thanks (and thanks a lot for your sponsorship!).

I'll give it a try and see if I can reproduce it with the Oracle provider. FWIW, I've always had way better results with the Pomelo provider, so it may be interesting to see if it's also impacted or not.

**Comment by kevinchalet** [comment]
I'm able to reproduce the issue locally, and as you suspected, this is indeed caused by an issue with the dates retrieved from the database:

Before the token is persisted in the database:

![image](https://user-images.githubusercontent.com/6998306/94157198-3dd7a380-fe81-11ea-8d2a-5b3b8590ee8c.png)

When it's retrieved from the database:

![image](https://user-images.githubusercontent.com/6998306/94157232-492acf00-fe81-11ea-862a-7d25ea3ab1f3.png)

I will try with Pomelo.

**Comment by kevinchalet** [comment]
It works just fine with the Pomelo provider. Would using it be an option for you?

If we want to make it work with the official provider, we'll need to either:
  - Fix the underlying issue directly in the Oracle MySQL connector. It's the best option, but not something we have much control over.
  - Use `DateTime` in the EF models (and `DateTime.SpecifyKind()` in the EF stores to enforce `DateTimeKind.Utc` dates). Sadly, changing the type of the `CreationDate`/`ExpirationDate` is a massive breaking change, so it's not something we can introduce without evaluating how painful migrating will be. Also, it should workaround the issue for the OpenIddict models, but it will still be present elsewhere (e.g in the ASP.NET Core Identity models, that also use `DateTimeOffset`).

**Comment by GDreyV** [comment]
Wow, it was fast. Great you found the reason.
For sure I will try Pomelo provider. The question us should I stay with openiddict version 3.0 for production (it looks like in includes all pdbs and consumes much more memory) or rollback to the version 2.0.1? Do you have any thoughts about possible release date? For sure I'd love to stay with v.3 :)

**Comment by GDreyV** [comment]
One more question, do you have Issue number for the Date format? Is it this one: https://bugs.mysql.com/bug.php?id=92367 ?

**Comment by kevinchalet** [comment]
> Wow, it was fast. Great you found the reason.

That's the "sponsors treatment" 😄 

> The question us should I stay with openiddict version 3.0 for production (it looks like in includes all pdbs and consumes much more memory) or rollback to the version 2.0.1? Do you have any thoughts about possible release date?

OpenIddict 3.0 (beta3 and later) is now stable enough to be used in production.

Beta4 will be released soon (it's currently blocked by https://github.com/openiddict/openiddict-core/issues/1053) and we'll have another beta to use new APIs from IdentityModel and react to bug fixes in the Roslyn compiler/VS. I don't know yet whether a RC1 version will be useful or not, but for RTM, I'd say November or December, assuming we're not blocked by upstream bugs in VS or in the few libs we depend on.

> One more question, do you have Issue number for the Date format? Is it this one: https://bugs.mysql.com/bug.php?id=92367 ?

Yeah, it sounds very similar. Hard to believe it was opened 2 years ago and it's still not fixed 😭 

> For sure I'd love to stay with v.3 :)

Haha! It's definitely not a bad thing to start using 3.0 as early as possible, as 2.x won't be supported once 3.0 ships later this year (for more information, don't miss https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/) 😃

**Comment by GDreyV** [comment]
Thanks for the update. I'm switching to the Pomelo driver (have to fix some issues with charset and collation as that driver doesn't have such extensions and attributes) will post update here as it's ready just for history :)

**Comment by kevinchalet** [comment]
> it looks like in includes all pdbs and consumes much more memory

It's a change that occurred when we migrated to .NET Arcade. I'll check with @martincostello whether we still want to use embedded PDBs in the aspnet-contrib projects or if we can use `<DebugType>portable</DebugType>` instead.

**Comment by kevinchalet** [comment]
@GDreyV FYI, we just switched to `<DebugType>portable</DebugType>` + `.snupkg`, which should reduce the size of both assemblies and packages. If you're interested in giving the nightly builds a try, the `3.0.0-beta4.20474.78` version includes these changes.

Regarding the memory footprint, I'd expect OpenIddict 3.0 to take a bit more RAM as there are more assemblies to load, but I'm interested in taking a look at your 2.x vs 3.0 numbers if you're willing to share them 😃

**Comment by GDreyV** [comment]
@kevinchalet thanks a lot for your help and fast replies. I suppose we can close the issue now. Just for the history here's the answer and possible workaround for the problem: https://github.com/openiddict/openiddict-core/issues/1097#issuecomment-698374105
