### ISSUE TITLE
Single Login for Server and Client application

### ISSUE THREAD

**Issue by JohnCorner78** [openiddict/openiddict-core#1109]
My scenario based on “Velusia” sample provided with OpenIddict framework. In my scenario server running under [https://domain/server](https://domain/server)   address. ASP.Core client application added under [https://domain/client](https://domain/client) . Both applications share the same domain, but different subdomains and each application uses its own application pool process.  

It is all working fine. if I open server page I enter credentials and can access my profile, if I open client application I have to enter credentials again and can access client application.

Also in my scenario server main page contains all links of all registered client applications and once User logged on the server He can open any client application from the main page by clicking on client application link. Unfortunately every time User opens new client application User has to enter the same credentials again!

The question is - Is it possible that I authenticate the User based on this same token? I mean User logs on the server, enters valid credentials just once and after that he can open any client application and doesn’t need to enter the same credentials again? The application can still go through authorization process, and get valid token from the server, but can share the same User ?

All I need is a single login. I know it is possible to achieve this with ASP form authentication application by sharing the same system.web/machineKey values. But how to achieve this with OpenIddict?

**Comment by kevinchalet** [comment]
I'd say you didn't correctly configure your server app to use persistent ASP.NET Core Data Protection keys, that are used to protect the authentication cookies created by ASP.NET Core Identity (and needed to keep the user logged in at the authorization server level).

See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1 for more information.

**Comment by JohnCorner78** [comment]
thank you for the advise, I'll try to review server configuration.
