### ISSUE TITLE
Investigate why transitive dependencies are leaking

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1113]
For reasons I ignore, something regressed in beta4/5 that caused transitive dependencies to leak across packages.
It shouldn't cause any technical issue, but it adds unnecessary/unwanted noise in the package dependencies:

https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.AspNetCore/OpenIddict.AspNetCore.csproj
https://www.nuget.org/packages/OpenIddict.AspNetCore/3.0.0-beta5.20503.76

Beta4:

![image](https://user-images.githubusercontent.com/6998306/94999712-90b90580-05bb-11eb-9f0f-c7075815a713.png)

Beta3:

![image](https://user-images.githubusercontent.com/6998306/94999731-a75f5c80-05bb-11eb-9e02-78bbc4a4a6e8.png)

**Comment by kevinchalet** [comment]
Potential culprits:
  - .NET SDK 5.0 RC1.
  - `snupkg`s, that we enabled recently.
  - CPVM.

**Comment by kevinchalet** [comment]
The NuGet team confirmed this is caused by CPVM: https://github.com/NuGet/Home/issues/10115.

**Comment by kevinchalet** [comment]
The NuGet team doesn't plan to change this behavior in 5.0 RTM and it's not clear when they'll be able to introduce a switch to opt out this unwanted behavior. As such, we'll need to remove CPVM.

@martincostello I'm afraid we'll also have to do that in the aspnet-contrib repos... 😭

**Comment by martincostello** [comment]
How much of an issue is this in the other repos with minimum dependencies? For example, MyGet only shows this for the Apple provider for 5.0 RC2:

![image](https://user-images.githubusercontent.com/1439341/96018530-4c432a80-0e43-11eb-8d43-d5b528e357e5.png)

**Comment by kevinchalet** [comment]
Hum yeah, good point. It looks like we don't have `<PackageVersion>`s for the transitive dependencies referenced by the IM packages we depend on, so it's much less visible in the OAuth/OpenID 2.0 repos than here (in another project, we now have up to 44 direct references compared to 7 before this change 🤣).

**Comment by kevinchalet** [comment]
@martincostello we can get a similar centralized management experience by using `<PackageReference Update />`: https://github.com/openiddict/openiddict-core/pull/1130. Thoughts?
