### ISSUE TITLE
[Q] ASP.NET Core 3.1 / .NET Core 3.1 / EF Core 5 and OpenIddict v. 3

### ISSUE THREAD

**Issue by marcellorutter** [openiddict/openiddict-core#1117]
Hello.

I have a simple question. I would kindly ask if I can use OpenIddict v. 3.x in a ASP.NET Core 3.1 project that is using EF Core 5.0 (not EF Core 3.1).

Thank you very much.
-m

**Comment by kevinchalet** [comment]
Hey,

Yep, it should work. If it doesn't, let me know.

Cheers.

**Comment by marcellorutter** [comment]
Thank you  very much for your quick answer.
I'm setting up the project in these hours.
I will let you know about the result.

Thanks.
Best regards.

**Comment by kevinchalet** [comment]
Closing, as I guess it went smoothly 😃
