### ISSUE TITLE
Separating client_id and Application primary key

### ISSUE THREAD

**Issue by Ciantic** [openiddict/openiddict-core#112]
I'm using a Integer as a keys for User, Role etc. Currently this also forces an application client_id to be a integer. This is not necessarily wanted, and they could be decoupled.

Right now I'm registering my official apps with e.g. with client_id 10000 and increment the number with another 10000 to make room for the possiblity of thirdparty apps (if there ever is any).

Ideally I would like to use string as a client_id, so I could register official apps with clear names such as "official-spa", "mobile-app" etc. so I could find them from logs if I need to.

**Comment by kevinchalet** [comment]
Sounds like a good idea (as long as we can define the client_id column as an index for maximal performance).

/cc @Bartmax @ilmax thoughts? :smile:

**Comment by Bartmax** [comment]
> Ideally I would like to use string as a client_id, so I could register official apps with clear names such as "official-spa", "mobile-app" etc. so I could find them from logs if I need to.

Agree, client_id type shouldn't be forced to be the same as user_id.

**Comment by ilmax** [comment]
Ideally we could use a genircs here, so int or string can be used based on Dev needs

**Comment by kevinchalet** [comment]
@ilmax the `Application` type supports custom key types thanks to its `TKey` generic argument (as requested by @khellang), but `TKey` is shared by all the OpenIddict/Identity models, so you can't use `string` for `Application` and `long` or `Guid` for the other models. We could of course use a key type per entity, but it would quickly become a real nightmare, as it would end up having an insane number of generic arguments (Identity doesn't support that for this exact reason).

I think having a separate indexed string property for `client_id` and a primary key whose type is chosen via `TKey` is a good compromise.

**Comment by ilmax** [comment]
@PinpointTownes yes, that makes sense

**Comment by kevinchalet** [comment]
Fixed, thanks to @xperiandri :clap:
