### ISSUE TITLE
Configuration without .AddIdentity?

### ISSUE THREAD

**Issue by NoahStahl** [openiddict/openiddict-core#1132]
In my project, I'm not using `AspNetCore.Identity` for user storage. Therefore, I haven't added this line in my configuration, which is present in all the samples:

https://github.com/openiddict/openiddict-core/blob/923c53f67230b1af0d70d5e98a4c45adf71a2d56/samples/Mvc.Server/Startup.cs#L36

Because this has the side-effect of registering `IdentityConstants.ApplicationScheme` as the default authentication scheme, the example controller actions don't work using that scheme unless this is called. I haven't been able to find any documentation or code comments about whether AspNetCore.Identity is required or optional, and what the consequences are of omitting `.AddIdentity()`. Is there a recommended alternative configuration for projects not using the Identity integration for user data? Thanks!

**Comment by kevinchalet** [comment]
It's a quite general question you should ask to the ASP.NET team, as it's not really specific to OpenIddict 😄 

If you don't use Identity, you'll likely want to register at least a cookie handler. The ASP.NET Core docs should help for that (e.g https://docs.microsoft.com/fr-fr/aspnet/core/security/authentication/?view=aspnetcore-3.1).

**Comment by NoahStahl** [comment]
Thanks Kevin. I was thinking it specific to OpenIddict because presumably the inclusion of it  in the samples was on purpose. If it is indeed optional, that would raise the question as to how to understand its use and implications of omission. The sample just has the comment `// Register the Identity services` without any "because..." whereas there are lots of other (excellent) detailed comments with reasoning elsewhere in the code. Hence my curiosity. :)

That said, this appears to get the sample code working without (in place of) `AddIdentity`:

```
services.AddAuthentication(IdentityConstants.ApplicationScheme)
        .AddIdentityCookies();

services.AddOpenIddict()
// Etc
```

**Comment by kevinchalet** [comment]
> "because..."

... it's pretty much the only membership stack available on .NET Core, which makes it hard to replace by something else 😅 

You can also take a look at this blog post, that uses a single cookie handler (with the default scheme): https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

**Comment by NoahStahl** [comment]
Yes, I think the degraded mode helps show how a slimmer setup can be achieved. Using the standard Cookies scheme seems to be working for me with my custom user management. I did get scared off by "degraded" and implemented all the stores for Cosmos DB to keep using the provided managers and validation, but that seems to be working too. Thanks again for your insight.
