### ISSUE TITLE
Use OpenIddict within Azure Functions

### ISSUE THREAD

**Issue by fmExcense** [openiddict/openiddict-core#1133]
Hi guys, thanks a lot for your hard work! We have tried (unsuccessfully) to build an Azure Function that would act as an OpenIddict authentication server. Did you ever think about such a scenario? Right now it seems that it is not possible.

Any clues from your side are more than welcomed !

Thanks,

**Comment by kevinchalet** [comment]
Hi,

> Did you ever think about such a scenario?

I did, but Azure Functions has severe limitations. The most annoying one is that they prevent ASP.NET Core authentication handlers from being registered in the DI container. Yet, both the OpenIddict server and validation ASP.NET Core hosts need to register a handler... so this simply doesn't work.

I tweeted about that in May and I was told they were considering fixing it... almost 5 months later, it's still a broken scenario: https://twitter.com/ChristosMatskas/status/1266496297302806528.

**Comment by fmExcense** [comment]
Thanks for your quick reply @kevinchalet . Tant pis, we won't go serverless this time...

**Comment by kevinchalet** [comment]
@fmExcense avec plaisir. If you're interested in having a little chat to explain your scenario, feel free to ping me at contact [at] kevinchalet.com

**Comment by espray** [comment]
I was able to get a OpenIddict server hosted in Az Func 3.1 using AspNet.Security.OpenIdConnect.Server v2. I used what I posted here https://github.com/Azure/azure-functions-host/issues/4485 to register a dynamic auth schema then I call the OpenIdConnectServerHandler in my http trigger. There is a nuget now to register a dynamic auth schema https://www.nuget.org/packages/DarkLoop.Azure.Functions.Authorize so I wont need to use my hacky way. There is also a good chance it will work out-of-box with an isolated Az Func, but I have not tried yet.

**Comment by kevinchalet** [comment]
> I was able to get a OpenIddict server hosted in Az Func 3.1 using AspNet.Security.OpenIdConnect.Server v2.

ASOS was merged into OpenIddict as part of the 3.x effort and thus is no longer supported.

> There is also a good chance it will work out-of-box with an isolated Az Func, but I have not tried yet.

I don't think it will work, as the out-of-process mode used in >= 5.x doesn't expose ASP.NET Core at all (there are equivalent types like `HttpRequestData` in `Microsoft.Azure.Functions.Worker.Core`, but it's a very limited subset of what you have in ASP.NET Core: none of the authentication stuff is there, AFAIK).

The best way to implement Azure Functions would be via a native OpenIddict host integration. If a company is interested in sponsoring this work, I'm all ears. Otherwise, it's something that could be released as a paid plugin if there was enough interest.

**Comment by espray** [comment]
> I don't think it will work, as the out-of-process mode used in >= 5.x doesn't expose ASP.NET Core at all (there are equivalents types like HttpRequestData in Microsoft.Azure.Functions.Worker.Core, but it's a very limited subset of what you have in ASP.NET Core: none of the authentication stuff is there, AFAIK).

Thanks for the heads-up on isolated AzFunc!

> The best way to implement Azure Functions would be via a native OpenIddict host integration.

I agree something native would be the way to go. I am going to try to put something together my self for now.

@kevinchalet ASOS had `OpenIdConnectServerProvider` is there something equivalent in 3.x?

**Comment by artmasa** [comment]
> > I was able to get a OpenIddict server hosted in Az Func 3.1 using AspNet.Security.OpenIdConnect.Server v2.
> 
> ASOS was merged into OpenIddict as part of the 3.x effort and thus is no longer supported.
> 
> > There is also a good chance it will work out-of-box with an isolated Az Func, but I have not tried yet.
> 
> I don't think it will work, as the out-of-process mode used in >= 5.x doesn't expose ASP.NET Core at all (there are equivalent types like `HttpRequestData` in `Microsoft.Azure.Functions.Worker.Core`, but it's a very limited subset of what you have in ASP.NET Core: none of the authentication stuff is there, AFAIK).
> 
> The best way to implement Azure Functions would be via a native OpenIddict host integration. If a company is interested in sponsoring this work, I'm all ears. Otherwise, it's something that could be released as a paid plugin if there was enough interest.

Isolated mode is supported with ASP.NET Core integration
