### ISSUE TITLE
Allowing database-generated values into created models

### ISSUE THREAD

**Issue by NoahStahl** [openiddict/openiddict-core#1134]
I notice that that when `CreateAsync` is called in the code, it doesn't assign a value returned from the store. For example:

https://github.com/openiddict/openiddict-core/blob/45fcfbedaa319727df49c9d916087c1bb11f1a6b/src/OpenIddict.Core/Managers/OpenIddictTokenManager.cs#L153

Here, the value used to create the token is assumed to be the actual result of the creation.

As a result, any custom model values that are database-generated don't make it back into the app state. An example is the ETag concurrency value in CosmosDB which only comes from the database. On subsequent updates, the ETag is missing from the model passed to the store's `UpdateAsync` method.

Is there a recommended way to allow data to flow back from the creation into the model? Thanks!

**Comment by kevinchalet** [comment]
> Here, the value used to create the token is assumed to be the actual result of the creation.

That's exact: stores are expected to mutate the `token` instance to attach database-generated values (i.e instead of returning a different one).

**Comment by NoahStahl** [comment]
Ah! I was trying to replace the token. Setting the required property does work. Sorry for the hassle, thanks for setting me straight. :)
