### ISSUE TITLE
Windows authentication with Correlation Error

### ISSUE THREAD

**Issue by mfarkan** [openiddict/openiddict-core#1141]
Hi,
I'm making a web application with windows authentication. But I'm getting error windows authentication and classic username-password login. I couldn't understand this exception. Is this related to any kind of exception that you're throwing for not using https?

![image](https://user-images.githubusercontent.com/20838613/96724997-18bf4d80-13b9-11eb-8279-9da57d4fd9bc.png)

Is this about misconfiguration? 

Thank you for your help.

**Comment by kevinchalet** [comment]
Hi,

It's likely a same-site issue. You can confirm it by trying a different browser (e.g Firefox).
Consider enabling SSL/TLS to work around it.
