### ISSUE TITLE
Cannot create a DbSet for 'OpenIddictEntityFrameworkCoreApplication' because this type is not included in the model for the context

### ISSUE THREAD

**Issue by mdmoura** [openiddict/openiddict-core#1145]
I am using Openiddict with NetCore 5.0 RC2 and Entity Framework 5.0 RC2 and I created custom Entities:

    public class Application : OpenIddictEntityFrameworkCoreApplication<Int32, Authorization, Token> { }

    public class Authorization : OpenIddictEntityFrameworkCoreAuthorization<Int32, Application, Token> { } 

    public class Token : OpenIddictEntityFrameworkCoreToken<Int32, Application, Authorization> { }

    public class Scope : OpenIddictEntityFrameworkCoreScope<Int32> { }

And I added these entities to my EntityFramework's DbContext (which is in a Class Library):

    public class DatabaseContext : IdentityUserContext<User, Int32, UserClaim, UserLogin, UserToken> {
       
        public DbSet<Application> Applications { get; set; }
        public DbSet<Authorization> Authorizations { get; set; }
        public DbSet<Scope> Scopes { get; set; }
        public DbSet<Token> Tokens { get; set; }
    
        public DatabaseContext(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder) {

          base.OnModelCreating(builder);

          builder..Entity<Application>().ToTable("Applications");
          builder..Entity<Authorization>().ToTable("Authorizations");
          builder..Entity<Scope>().ToTable("Scopes");
          builder..Entity<Token>().ToTable("Tokens");
  
      }

    }

And I have a  ContextFactory defined for configuration

```
  public class ContextFactory : IDesignTimeDbContextFactory<DatabaseContext> {

    public Context CreateDbContext(String[] args) {

      DbContextOptionsBuilder<DatabaseContext> builder = new DbContextOptionsBuilder<DatabaseContext>();

      builder
        .UseSqlServer(connectionString)
        .UseOpenIddict<Application, Authorization, Scope, Token, Int32>();

      return new Context(builder.Options);

    } 

  }

```

I am able to create the migrations and add the tables to the database.

On my Openiddic I have the following Startup configuration:

    public void ConfigureServices(IServiceCollection services) {

      services.AddDbContext<DatabaseContext>(x => {
        x.UseSqlServer(connectionString);
        x.UseOpenIddict<Application, Authorization, Scope, Token, Int32>();
      });

      services.AddOpenIddict()
      
        .AddCore(x => {
          x.UseEntityFrameworkCore().UseDbContext<DatabaseContext>();
        })

        .AddServer(x => {

          x.SetAuthorizationEndpointUris("/connect/authorize")
           .SetLogoutEndpointUris("/connect/logout")
           .SetTokenEndpointUris("/connect/token")
           .SetUserinfoEndpointUris("/connect/userinfo");

          x.RegisterScopes(OpenIddictConstants.Scopes.Email, OpenIddictConstants.Scopes.Profile, OpenIddictConstants.Scopes.OfflineAccess);

          x.AllowAuthorizationCodeFlow();

          x.AddDevelopmentEncryptionCertificate().AddDevelopmentSigningCertificate();

          x.UseAspNetCore()
           .EnableAuthorizationEndpointPassthrough()
           .EnableLogoutEndpointPassthrough()
           .EnableTokenEndpointPassthrough()
           .EnableUserinfoEndpointPassthrough()
           .EnableStatusCodePagesIntegration();

        })

        .AddValidation(x => {
          x.UseLocalServer();
          x.UseAspNetCore();
        });

    }

When the client calls the Openiddic to start the login process I get the following exception:

```
InvalidOperationException: Cannot create a DbSet for 'OpenIddictEntityFrameworkCoreApplication' because this type is not included in the model for the context.
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.get_EntityType()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.CheckState()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.get_EntityQueryable()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.System.Linq.IQueryable.get_Provider()
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsTracking<TEntity>(IQueryable<TEntity> source)
OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreApplicationStore<TApplication, TAuthorization, TToken, TContext, TKey>.FindByClientIdAsync(string identifier, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
OpenIddict.Core.OpenIddictApplicationCache<TApplication>+<>c__DisplayClass6_0+<<FindByClientIdAsync>g__ExecuteAsync|0>d.MoveNext()
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
OpenIddict.Core.OpenIddictApplicationManager<TApplication>.FindByClientIdAsync(string identifier, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
OpenIddict.Core.OpenIddictApplicationManager<TApplication>.OpenIddict.Abstractions.IOpenIddictApplicationManager.FindByClientIdAsync(string identifier, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
OpenIddict.Server.OpenIddictServerHandlers+Authentication+ValidateClientId.HandleAsync(ValidateAuthorizationRequestContext context)
OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync<TContext>(TContext context)
OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync<TContext>(TContext context)
System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
OpenIddict.Server.OpenIddictServerHandlers+Authentication+ValidateAuthorizationRequest.HandleAsync(ProcessRequestContext context)
OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync<TContext>(TContext context)
OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync<TContext>(TContext context)
System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

Am I missing something here or this might be a bug?

**Comment by kevinchalet** [comment]
> Am I missing something here

https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Startup.cs#L68 😃

**Comment by mdmoura** [comment]
> https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Startup.cs#L68 😃

Than you! That solved it ...
