### ISSUE TITLE
Quartz needs reference to Quartz.Extensions.Hosting

### ISSUE THREAD

**Issue by 1619digital** [openiddict/openiddict-core#1146]
Hi, great job on the new version.

I believe `OpenIddict.Quartz` is missing a reference to `Quartz.Extensions.Hosting` . Currently, without referencing this package separately, then

`services.AddQuartzHostedService(options => options.WaitForJobsToComplete = true);`

won't work. (Right now, `OpenIddict.Quartz` depends on `Quartz.Extensions.DependincyInjection` which in turn depends on the core  `Quartz` package, but the `Quartz.Extensions.Hosting` package is not present.)

Thanks.

**Comment by kevinchalet** [comment]
Hey,

> Hi, great job on the new version.

Thanks for the kind words 😃 

> I believe OpenIddict.Quartz is missing a reference to Quartz.Extensions.Hosting.

Technically, the OpenIddict Quartz.NET integration doesn't need this reference (and it doesn't call `services.AddQuartzHostedService()` for you, which is not an idempotent method, BTW).

For convenience, we could probably reference `Quartz.Extensions.Hosting`, but I'm not sure calling `services.AddQuartzHostedService()` would be the right thing to do, as some people may not want to use the Quartz.NET generic host support.

**Comment by 1619digital** [comment]
Ah ok, I was (rather robotically) following the steps in your blog post

https://kevinchalet.com/2020/10/02/introducing-quartz-net-support-and-new-languages-in-openiddict-3-0-beta4/

So to be clear, `AddQuartzHostedService()` is unnecessary for the OpenIddict Quartz.NET to do its cleanup?

**Comment by kevinchalet** [comment]
> So to be clear, AddQuartzHostedService() is unnecessary for the OpenIddict Quartz.NET to do its cleanup?

The Quartz.NET hosted service is just one way to register the scheduler (the most convenient one to be honest), but you could also create and manage the scheduler yourself (e.g https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/using-quartz.html).

@lahma hey! Do you think Quartz.NET/third-party integrations should register the `IHostedService` exposed by `Quartz.Extensions.Hosting` or should it be "left as an exercise" for the end user?

**Comment by lahma** [comment]
I don't know if I have any right answer to this... For example MassTransit has [infrastructure to listen to service bus start and hosts the running scheduler](https://github.com/MassTransit/MassTransit/blob/develop/src/Scheduling/MassTransit.QuartzIntegration/Configuration/SchedulerBusObserver.cs) until service bus is stopped. 

One option could be to have hidden/internal hosted service that is meant only for OpenIddict use and use that, keeping scheduling internal this way.  So you could build the scheduler with/without the Quartz DI extensions (there's `SchedulerBuilder` too when no DI libs) and then start your own private hosted service. When Quartz is configured with `DefaultThreadPool` it runs tasks in system task queue anyway so it's really lightweight, there's only one thread running to trigger the tasks into pool.

So that was just a idea I wanted to throw. Anyway, configuring the token cleanup might cause an expectation that it will automatically start doing things, with extra libs/service calls. The fun case usually is when library consumer also wants to host own jobs and triggers, who owns the scheduler/schedules then - but there can be always two (or more) schedulers running with different instance names.

**Comment by 1619digital** [comment]
Thank you. For what it's worth, I think everything that OpenIddict does should be targetted at "OpenID Connect server and token validation in any ASP.NET Core". So, while it's nice to introduce people to a new and useful library (Quartz) then the OpenIddict.Quartz package should be _solely_ focussed on doing any background jobs that OpenIddict needs. 

What I'd suggest is that `options => options.UseQuartz()` is the only thing you need to do to get it running; if there really is a need for more granular options then they could be raised in the Issues.

Anyway, it's a bit of a niche issue, as long as it works! I've come back to this project after a few years away, very impressed by the amount of work and professionalism that's gone into it. Thank you.

**Comment by lahma** [comment]
One option could be to just copy the current [Quartz's HostedService](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Extensions.Hosting/QuartzHostedService.cs) to internal use into OpenIddict and via options decide whether OpenIddict should start it for you (`options.StartScheduler`?), basically registering the hosted service, might default to true then.

With setting set to false the option would allow people to configure additional jobs if they wish and use the Quartz hosted service and share the scheduler.

**Comment by kevinchalet** [comment]
@lahma thanks for chiming in, much appreciated!

As you said, there's likely no right answer here. As such, I'm going to leave things as-is for now. If we ever decide to make Quartz.NET a first-class citizen by adding `OpenIddict.Quartz` to the `OpenIddict` metapackage, we'll still be able to revisit that.

Thanks!

**Comment by Camuvingian** [comment]
I am slightly confused here. I have followed the examples and looked at the configuration class in the source code. I am adding the Quartz support 
	
```C#
public static IServiceCollection AddQuartzServices(this IServiceCollection services)
{
	// Quartz here is used to automatically prune/remove authorization and token entries that
	// are no longer valid from the database.
	return services
		.AddQuartz(options =>
		{
			options.UseMicrosoftDependencyInjectionJobFactory();
			options.UseSimpleTypeLoader();
			options.UseInMemoryStore();
		})
		// Register the Quartz.NET service and configure it to block shutdown until jobs are complete.
		.AddQuartzHostedService(options => options.WaitForJobsToComplete = true);
}
```
	
I then add the Core service and initialize with `UseQuartz`

```C#
services
	.AddOpenIddict()
	.AddCore(options =>
	{
		options.UseMongoDb()
			   .UseDatabase(new MongoClient(_mongoDbSettings.ConnectionString).GetDatabase(_mongoDbSettings.DatabaseName))
			   .SetApplicationsCollectionName("applications")
			   .SetAuthorizationsCollectionName("authorizations")
			   .SetTokensCollectionName("tokens")
			   .SetScopesCollectionName("scopes");

		options.UseQuartz(builder => 
		{ 
			builder.Configure(o => { o.MaximumRefireCount = 3; }); 
		});
	})
```
		
This gives the following output,

> [12:39:12.720 INF] [] [Quartz.Core.SchedulerSignalerImpl] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
> [12:39:12.721 INF] [] [Quartz.Core.QuartzScheduler] Quartz Scheduler created
> [12:39:12.721 INF] [] [Quartz.Core.QuartzScheduler] JobFactory set to: Quartz.Simpl.MicrosoftDependencyInjectionJobFactory
> [12:39:12.721 INF] [] [Quartz.Simpl.RAMJobStore] RAMJobStore initialized.
> [12:39:12.723 INF] [] [Quartz.Core.QuartzScheduler] Scheduler meta-data: Quartz Scheduler (v3.4.0.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
>   Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
>   Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.
> 
> [12:39:12.723 INF] [] [Quartz.Impl.StdSchedulerFactory] Quartz scheduler 'QuartzScheduler' initialized
> [12:39:12.723 INF] [] [Quartz.Impl.StdSchedulerFactory] Quartz scheduler version: 3.4.0.0
> [12:39:12.738 INF] [] [Quartz.ContainerConfigurationProcessor] Adding 1 jobs, 1 triggers.
> [12:39:12.739 INF] [] [Quartz.ContainerConfigurationProcessor] Adding job: OpenIddict.Quartz.OpenIddictQuartzJob
> // ... Other logging ...
> [12:39:13.316 WRN] [] [Microsoft.AspNetCore.Server.Kestrel] Overriding address(es) '"https://localhost:6699"'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
> [12:39:13.337 INF] [] [Microsoft.Hosting.Lifetime] Now listening on: "https://[::]:6699"
> [12:39:13.337 INF] [] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
> [12:39:13.337 INF] [] [Microsoft.Hosting.Lifetime] Hosting environment: "Localhost"
> [12:39:13.338 INF] [] [Microsoft.Hosting.Lifetime] Content root path: "C:\VRPM\Repos\authentication-server\src\Services\Migr8.AuthenticationServer\bin\Debug\net6.0"
> [12:39:13.343 INF] [] [Quartz.Core.QuartzScheduler] Scheduler QuartzScheduler_$_NON_CLUSTERED started.

but the cleanup never fires and the code that is supposed to be triggered between 1 to 10 min after initialization in `OpenIddictQuartzConfiguration`

```C#
options.AddTrigger(builder =>
	{
		// Note: this trigger uses a quite long interval (1 hour), which means it may be potentially never
		// reached if the application is shut down or recycled. As such, this trigger is set up to fire
		// between 1 and 10 minutes after the application starts to ensure the job is executed at least once.
		builder.ForJob(OpenIddictQuartzJob.Identity)
			   .WithSimpleSchedule(options => options.WithIntervalInHours(1).RepeatForever())
			   .WithDescription(SR.GetResourceString(SR.ID8002))
			   .StartAt(DateBuilder.FutureDate(new Random().Next(1, 10), IntervalUnit.Minute));
	});
```
		
never runs. What am I doing wrong here? I image something stupid...
