### ISSUE TITLE
UpdateAsync from OpenIddictApplicationDescriptor

### ISSUE THREAD

**Issue by rudiv** [openiddict/openiddict-core#1148]
We've been toying around with creating a management interface for OpenIddict's applications or Clients, however the Manager is completely generic (to the point of returning `object`).

This is fine, as we know the underlying type is `OpenIddictEntityFrameworkCoreApplication`, we can then call  [`PopulateAsync(OpenIddictApplicationDescriptor descriptor, TApplication application, ..)`](https://github.com/openiddict/openiddict-core/blob/84facf0895b09b61f960aeb40aa284e7a92e37c5/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L934) to get back to the `OpenIddictApplicationDescriptor`.

Unlike [`CreateAsync(OpenIddictApplicationDescriptor descriptor, ..)`](https://github.com/openiddict/openiddict-core/blob/84facf0895b09b61f960aeb40aa284e7a92e37c5/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L218) however, there is no `UpdateAsync(OpenIddictApplicationDescriptor descriptor, ..)` method to make the update process easier.

This may be fine if the implementation was something like this (calling the inverse `PopulateAsync(app, desc)`):
```
var application = new OpenIddictEntityFrameworkCoreApplication();
await manager.PopulateAsync(application, appDescriptor);
await manager.UpdateAsync(application);
```

However with this, `UpdateAsync` will give us a Validation Exception of: `An application with the same client identifier already exists.` Instead we have to re-pull the item from the database (assuming the original is not available, which it may not be by default for example on an interface postback).

```
var application = await manager.FindByClientIdAsync(appDescriptor.ClientId);
await manager.PopulateAsync(application, appDescriptor);
await manager.UpdateAsync(application);
```

This is something that seems like a lot of overhead, and I'm wondering if there's any plans (or perhaps more accurately, desire - so that this can be an issue to be implemented (easier CRUD using Descriptors)) for a simpler API to be implemented.

It feels a little awkward that the signature of `PopulateAsync` takes both the `application` and the `description`, when actually depending on what it's called with `object` vs `OpenIddictDescriptor`, it could simply return a task with the type, not requiring a new one to be created in advance.

A simpler API may well be:
```
var application = await PopulateAsync(appDescriptor); // Returning out an OpenIddictEntityFrameworkCoreApplication
await manager.UpdateAsync(application);
```

**Comment by kevinchalet** [comment]
> We've been toying around with creating a management interface for OpenIddict's applications or Clients, however the Manager is completely generic (to the point of returning object).

That's not exact: only the _non-generic_ `IOpenIddictApplicationManager` interface returns and takes `object` parameters.

It's clearly mentioned in the XML docs that "it is primarily intended to be used by services that cannot easily depend on the generic application manager. The actual application entity type is automatically determined at runtime based on the OpenIddict core options".

If your management interface is only designed to work with the EF Core stores, use `OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>` instead.

> This is something that seems like a lot of overhead.

It's the [standard EF Core update pattern](https://docs.microsoft.com/fr-fr/ef/core/saving/basic#updating-data): you retrieve the entity, mutate its properties and persist the changes.

If I understood your post correctly, you're looking for a more complicated option where the entity wasn't loaded in the `DbContext` and where you'd like to attach an untracked entity that would be used to update the application?

**Comment by rudiv** [comment]
That's true, we were simply taking `IOpenIddictApplicationManager` rather than the hard type (we did first look for a generic interface) and so now using the generic implementation directly we're getting back the `OpenIddictEntityFrameworkCoreApplication`, it doesn't actually change the code though.

Usually with EF Core we can simply `Attach` (as you rightly said) and based on the ID, EF Core would essentially do the same pattern albeit internally.

My main gripe though is the work with the descriptors, obviously it's not just a case of the underlying entity type, but working with the translation of the descriptors back to an underlying entity.

We've basically implemented the simpler `PopulateAsync(Descriptor)` (which will either new up or load from DB if found by ClientId) and `PopulateAsync(Application)` (which news up a Descriptor) methods at our side and was just wondering if there were any plans primarily for a simpler API for the CRUD side, when Descriptors are used as primary interaction method.

If not, obviously no problem as we can work around it all 😊

**Comment by kevinchalet** [comment]
> We've basically implemented the simpler PopulateAsync(Descriptor) (which will either new up or load from DB if found by ClientId) and PopulateAsync(Application) (which news up a Descriptor) methods at our side and was just wondering if there were any plans primarily for a simpler API for the CRUD side, when Descriptors are used as primary interaction method.

Interesting. Would you mind sharing the code?

**Comment by rudiv** [comment]
Sure, it's hugely primitive and just inherits from the Manager directly, but the relevant methods are:
 ```
        public virtual async ValueTask<OpenIddictApplicationDescriptor> PopulateAsync(
            OpenIddictEntityFrameworkCoreApplication application,
            CancellationToken cancellationToken = default)
        {
            if (application is null)
            {
                throw new ArgumentNullException(nameof(application));
            }
            
            var descriptor = new OpenIddictApplicationDescriptor();
            await PopulateAsync(descriptor, application, cancellationToken);
            return descriptor;
        }

        public virtual async ValueTask<OpenIddictEntityFrameworkCoreApplication> PopulateAsync(
            OpenIddictApplicationDescriptor descriptor,
            CancellationToken cancellationToken = default)
        {
            if (descriptor is null)
            {
                throw new ArgumentNullException(nameof(descriptor));
            }

            var application = default(OpenIddictEntityFrameworkCoreApplication);
            
            if (descriptor.ClientId is not null)
            {
                application = await FindByClientIdAsync(descriptor.ClientId, cancellationToken);
            }

            application ??= new OpenIddictEntityFrameworkCoreApplication();

            await PopulateAsync(application, descriptor, cancellationToken);

            return application;
        }
```

That's actually allowing us to have the simpler API of:
```
var application = await manager.PopulateAsync(appDescriptor); // Returning out an OpenIddictEntityFrameworkCoreApplication
await manager.UpdateAsync(application);
```

For future reference, if we can make this a generic "admin" (that's ever requested to be similar to IS' AdminUI) but lighter than Orchard, it's something we'll likely put out in the open.

**Comment by kevinchalet** [comment]
> Sure, it's hugely primitive and just inherits from the Manager directly, but the relevant methods are:

AFAICT, your method also needs to retrieve the application from the DB prior to mutating it, so it works pretty much the same way as the built-in methods, but in a bit more condensed way?

We have an `UpdateAsync` overload that directly takes an application and a descriptor used to mutate it. Wouldn't that fit your needs? It's the one we use in OrchardCore:

https://github.com/openiddict/openiddict-core/blob/84facf0895b09b61f960aeb40aa284e7a92e37c5/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L1094-L1095

```csharp
var application = await manager.FindByClientIdAsync("mvc");
if (application is null)
{
    throw new InvalidOperationException("The client application couldn't be found.");
}

await manager.UpdateAsync(application, descriptor);
```

> For future reference, if we can make this a generic "admin" (that's ever requested to be similar to IS' AdminUI) but lighter than Orchard, it's something we'll likely put out in the open.

👍

**Comment by rudiv** [comment]
Correct, it's simply condensing down the process to a couple of helpers, as I say extremely primitive.

I didn't spot the `UpdateAsync(application, descriptor)`, and actually removes the need for the second PopulateAsync prior to the update (which is effectively a one-use discard to pass to `UpdateAsync`).

With that, I'll likely replace those helpers out with a `ListAsync` that returns Descriptors directly, and a simple shim/abstraction around the `UpdateAsync` to pull by clientId so that once again, the API is straight forward and working with Descriptors directly.

**Comment by kevinchalet** [comment]
> and a simple shim/abstraction around the UpdateAsync to pull by clientId so that once again

There's a downside to that method, tho': you won't be able to change the client identifier.

I'm not fundamentally opposed to introducing the APIs you suggested, but this would require adding new properties in the 4 descriptors (typically, an `Id` property).

If `Populate` is not your thing, we could hide it completely with a new overload taking a `Func`:

```csharp
var application = await manager.FindByClientIdAsync("mvc") ??
    throw new InvalidOperationException("The client application couldn't be found.");

await manager.UpdateAsync(application, descriptor =>
{
    descriptor.ClientId = "New client identifier";
    descriptor.DisplayName = "New display name";

    return default;
});
```

```csharp
/// <summary>
/// Updates an existing application.
/// </summary>
/// <param name="application">The application to update.</param>
/// <param name="function">The method delegate used to mutate the application descriptor.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
/// <returns>
/// A <see cref="ValueTask"/> that can be used to monitor the asynchronous operation.
/// </returns>
ValueTask UpdateAsync(object application, Func<OpenIddictApplicationDescriptor, ValueTask> function, CancellationToken cancellationToken = default);
```

**Comment by rudiv** [comment]
To be fair that API probably ends up being a bit more confusing, though I do agree with you that obviously we wouldn't be able to use the `FindByClientIdAsync` had it changed on the frontend.

With that said I'm actually treating the `ClientId` as the unique identifier here, and probably wouldn't allow change. The best way around that at least from an interface perspective would be to allow a clone of what's already there in to a new ClientId.

Again if you're thinking from an interface perspective (and specifically a typical form post of what would map to a descriptor), we wouldn't reasonably have the old client ID to do some form of mapping against that. Of course we could introduce an `OriginalClientId` at all times to handle the change, but feels a bit clunky. I think with the Permissions system you have, we would just then block the previous application through a removal of all permissions.

I think it's `ListAsync` that actually bothers me most (off the back of knowing there's `UpdateAsync(application, descriptor)`) as we're always having to loop the conversion:
```
await foreach (var application in manager.ListAsync())
{
    var descriptor = await manager.PopulateAsync(application);
    Applications.Add(descriptor);
}
```

It's a pretty minor thing though, so I'm not sure if there's much mass benefit to introducing an API that effectively does the same. From your perspective, it's whether it would add value to the wider users of OpenIddict.

**Comment by kevinchalet** [comment]
Looks like the demand for a new API is fairly low. Closing for now, but we'll still be able to revisit that post-RTM if necessary.
