### ISSUE TITLE
.AddValidation() doesn't call a registered IConfigureOptions<OpenIddictValidationBuilder>

### ISSUE THREAD

**Issue by JohnGalt1717** [openiddict/openiddict-core#1154]
If you use the standard practice of:

```
services.AddTransient<IConfigureOptions<OpenIddictValidationBuilder>, ConfigureOpenIddictValidation>(); 

			services.AddOpenIddict()
				.AddValidation();


```
So that you can use DI on your options configuration without having to get a ServiceProvider in Startup.cs which is verboten now, the Configure method in ConfigureOpenIddictValidation (or whatever you call your class) isn't called.

I would assume this is true about all of the rest of the configuration methods. It would be highly desirable for this to work so that we can get config settings etc. that are from DI instead of having to generation stuff manually.

**Comment by kevinchalet** [comment]
> It would be highly desirable for this to work so that we can get config settings etc. that are from DI instead of having to generation stuff manually.

Oh, it already works, but you have to use the right type: `IConfigureOptions<OpenIddictValidationOptions>`.

**Comment by JohnGalt1717** [comment]
Cool! Thanks!

**Comment by JohnGalt1717** [comment]
Sorry, one question, what's the equivalent to: AddEncryptionCertificate(509cert) in this syntax? (or UseAspNetCore() or UseSystemNetHttp()?

**Comment by kevinchalet** [comment]
All these methods are open source, I'm sure you can find the answer yourself 😃
