### ISSUE TITLE
Beta6: authorization_code token request doesn't return refresh or id tokens even with openid and offline_access scopes specified.

### ISSUE THREAD

**Issue by JohnGalt1717** [openiddict/openiddict-core#1156]
So with the latest beta, I'm getting different results than with beta 5:

The token request was successfully extracted: {
"client_id": "Admin",
"grant_type": "authorization_code",
"redirect_uri": "https://admin.dev.staccat.io/callback.html",
"client_secret": "[redacted]",
"code": "[redacted]",
"code_verifier": "rX3b_iSY2vKf-IKqJ4psG2pfXaNMuK6b4.8jBm4Am6V46zGEUBYlvjVqWxm_Ne5B6VPfKezLxA3D4mNnub5HWyKb3X6At8u.nNolRdt4o36bIAn6DJBI6dY2XfFMTaJA",
"scopes": "openid profile email offline_access api accounts"
}

It's my understanding that that should return both a refresh token and because of openid should also return the id token, but it doesn't. I only get the authorization token.

here's what it returns:

The response was successfully returned as a JSON document: {
"access_token": "[redacted]",
"token_type": "Bearer",
"expires_in": 3599
}

I can't see anything in the samples that is different. Is there some new setting that would induce the refresh and id token in this case? Is there something else I'm supposed to send? I would expect that with openid and offline_access specified these would be automatically created and returned wouldn't they?

**Comment by kevinchalet** [comment]
According to our new policy, questions asked by non-sponsors must now be posted on StackOverflow, where they will be answered by the community. If you need immediate support, please consider sponsoring the project.

Thanks!
