### ISSUE TITLE
App Gets Directed to /signin-oidc

### ISSUE THREAD

**Issue by stap123** [openiddict/openiddict-core#117]
I suspect there is a really simple answer to this that I just don't know but i'll ask the stupid question anyway :).

We are using IdentityServer3 to authenticate our applications when using AspNetCore I have one application that authenticates with the server using the UseOpenIdConnectAuthentication() Middleware. But when we added the same middleware to another application (With a different client id etc) that application just gets redirected to http://localhost:50026/signin-oidc.

It seems to me that this second applications middleware (for whatever reason) isn't catching the callback url and dealing with it. The startup classes configure methods are IDENTICAL (They are both very simple at this stage, early test projects etc)

Is there a common problem that you know of that I am missing? (I have searched around but can't find an answer/am not searching the correct thing)

Many Thanks

**Comment by kevinchalet** [comment]
> We are using IdentityServer3 to authenticate our applications

Then, this is obviously the wrong repository :smile: 
Here's the one you're looking for: https://github.com/IdentityServer/IdentityServer3.

**Comment by stap123** [comment]
Not sure I explained that very well. 

The Identity Server functionality is working correctly, I think the issue is with the Open Id Authentication OWIN Middleware. It is not catching the callback when it comes in to {Appurl}/signin-oidc

The Identity Server issue is probably irrelevant (Because it is working perfectly well with other applications including another on aspnet core) and I have mislead you by mentioning it but thought I should provide as much information as possible.

**Comment by kevinchalet** [comment]
> The Identity Server functionality is working correctly, I think the issue is with the Open Id Authentication OWIN Middleware. It is not catching the callback when it comes in to {Appurl}/signin-oidc

I'm not sure to understand how it's related to OpenIddict. The OIDC client middleware is developed by the ASP.NET team. Issues related to this middleware should be filed via https://github.com/aspnet/Security
