### ISSUE TITLE
Allow specifying per-user and/or per-application token lifetime

### ISSUE THREAD

**Issue by DreamingDevs** [openiddict/openiddict-core#119]
Currently I have following configuration in `Startup.cs` - 

```
 app.UseOpenIddictCore(builder =>
                {
                    // tell openiddict you're wanting to use jwt tokens
                    builder.Options.UseJwtTokens();
                    // NOTE: for dev consumption only! for live, this is not encouraged!
                    builder.Options.AllowInsecureHttp = true;
                    builder.Options.ApplicationCanDisplayErrors = true;
                });

                var Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = context => Task.FromResult(0)
                };

                // use jwt bearer authentication
                app.UseJwtBearerAuthentication(new JwtBearerOptions
                {
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true,
                    RequireHttpsMetadata = false,
                    Audience = Configuration["BearerAuthentication:Audience"],
                    Authority = Configuration["BearerAuthentication:Authority"],
                    Events = Events
                });

```

And this is my Custom OpenIddictManager - 

```
        public override async Task<ClaimsIdentity> CreateIdentityAsync(UserModel user, IEnumerable<string> scopes)
        {            
            if (String.IsNullOrWhiteSpace(instanceId))
                throw new AuthenticationException("InstanceId is missing in request.");

            var identity = await base.CreateIdentityAsync(user, scopes);

            var nameClaim = new Claim("givenName", user.FirstName + ' ' + user.LastName)
                .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
                                 OpenIdConnectConstants.Destinations.IdentityToken);

            identity.AddClaim(nameClaim);

            var emailClaim = new Claim("email", user.Email)
               .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
                                OpenIdConnectConstants.Destinations.IdentityToken);

            identity.AddClaim(emailClaim);

            return identity;
        }
```

One request to `/connect/token`, I get following token response.
![image](https://cloud.githubusercontent.com/assets/5579127/15352705/13afd5fa-1d03-11e6-8995-2be89729104a.png)

Now I want to set the token's `expires_in` property (basically AccessTokenLifetime) based on user (from my database, every user will have different value). How to do that?

**Comment by DreamingDevs** [comment]
Update - I used below code by handling `OnSerializeAccessToken`. With this approach I am only able to get the "expires_in" set after first request.

What I mean is that when ever I change value in DB, the immediate request to TokenEndpoint uses the OLD value, but from second request (to TokenEndpoint) uses NEW value. Can some one point me what I am doing wrong here.

```
app.UseOpenIddictCore(builder =>
{
     // tell openiddict you're wanting to use jwt tokens
     builder.Options.UseJwtTokens();
     // NOTE: for dev consumption only! for live, this is not encouraged!
      builder.Options.AllowInsecureHttp = true;
      builder.Options.ApplicationCanDisplayErrors = true;
      builder.Options.Provider = new OpenIddict.OpenIddictProvider<UserModel, Application>
       {
            OnSerializeAccessToken = context =>
              {
                 var sessionTimeout = DB.SessionDurationTimeout; //Get data from DB, here value us coming correctly.
                 Console.WriteLine(sessionTimeout);
                  builder.Options.AccessTokenLifetime = new TimeSpan(0, (int)sessionTimeout, 0);

                  return Task.FromResult<object>(null);
              }
         };

});
```

**Comment by kevinchalet** [comment]
> What I mean is that when ever I change value in DB, the immediate request to TokenEndpoint uses the OLD value, but from second request (to TokenEndpoint) uses NEW value. Can some one point me what I am doing wrong here.

Not surprising, since you're updating the global options by replacing `builder.Options.AccessTokenLifetime`, which is terribad as it's not thread-safe.

Instead, you can replace `context.Ticket.Properties.ExpiresUtc` with the expiration date you want. It will only impact the access token lifetime and won't affect the other tokens or the other requests.

That said, this kind of extensibility is not officially supported by OpenIddict (at least, not yet). Not sure what will be the final story for these scenarios :smile:

**Comment by DreamingDevs** [comment]
Thanks @PinpointTownes Setting `ExpiresUtc` is working fine.

**Comment by kevinchalet** [comment]
Reopening, to make sure we track this scenario.

**Comment by ilmax** [comment]
Interesting one, can we implement an abstraction around token lifetime? I think of something like this one

```
public interface ITokenLifetimeProvider
{
   Task SetTokenLifetimeAsync<TUser>(TUser user, AuthenticationProperties properties);
}
```

Maybe the application can also be passed in to have more granularity?

The default implementations can simply return the default values e.g. `Options.AccessTokenLifetime`

Should we provide similar method for 
- RefreshTokens
- AuthorizationCode
- IdentityToken

In that case we can pass additional info to the method to make explicit what kind of token we are generating

/cc @Bartmax

**Comment by kevinchalet** [comment]
Generating an `AuthenticationTicket` is something the dev' must do in his own controller, as of beta1 so it's now possible to use a per-user/per-application token lifetime by implementing your own logic.

**Comment by andrzejmartyna** [comment]
Just a note that might helps others. I was searching for a way to customize expiration time for a token.

Found this conversation with "Instead, you can replace context.Ticket.Properties.ExpiresUtc with the expiration date you want." which made mu stuck in thinking I'm doing something wrong.

Finally I've found that it is an obsolete advice and I should instead use this:

**ticket.SetAccessTokenLifetime(TimeSpan.FromHours(3));**
