### ISSUE TITLE
one time donate button

### ISSUE THREAD

**Issue by dzmitry-lahoda** [openiddict/openiddict-core#1193]
until i use this stuff, i cannot do monthly. so one time donation button option would be good.

**Comment by kevinchalet** [comment]
Thanks a lot for your interest!

I'm not sure GitHub sponsors supports one-time donations but you can certainly use PayPal for that: https://paypal.me/kevinchalet.
If you have another service in mind, please don't hesitate.

Merry Christmas! 🎄
