### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by djechelon** [openiddict/openiddict-core#1203]
### Describe the bug
The URLs generated automatically by authorization errors point to missing pages.

Example: 

```
Bearer error="insufficient_access", error_description="The user represented by the token is not allowed to perform the requested action.", error_uri="https://documentation.openiddict.com/errors/ID2095"
```

https://documentation.openiddict.com/errors/ID2095 reports 404

The scope of this issue is the bare absence of the related documentation page. I am not asking for help about the cause of the problem, which _could be investigated_ with help from documentation.

For the scope of my access problem, I'll start poking around the code.

### Further technical details
Openiddict v 3.0

**Comment by kevinchalet** [comment]
It's not a bug, the errors documentation is just not there yet: https://github.com/openiddict/openiddict-documentation/issues/30.

To help make that happen sooner, please consider sponsoring the project.
