### ISSUE TITLE
Problem with migration to OpenIdDict 3.0 / AuthenticationSchemes

### ISSUE THREAD

**Issue by Dinatte** [openiddict/openiddict-core#1204]
Hello,
I am in the process of migrating .net core 2.2 -> .net 5.0
I also update all libraries, including OpenIdDict to version 3.0

I have 3 applications: AuthApp, AppA and AppB.
AuthApp is responsible for issuing tokens and verifying access.

So far I have used in AuthApp:
```
<ItemGroup>
<PackageReference Include = "AspNet.Security.OAuth.Introspection" Version = "2.0.0" />
<PackageReference Include = "FirebaseAdmin" Version = "1.8.0" />
<PackageReference Include = "MailKit" Version = "2.1.3" />
<PackageReference Include = "Microsoft.AspNetCore.App" />
<PackageReference Include = "Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version = "2.2.0" />
<PackageReference Include = "Microsoft.AspNetCore.Razor.Design" Version = "2.2.0" PrivateAssets = "All" />
<PackageReference Include = "Microsoft.EntityFrameworkCore.Sqlite" Version = "2.2.2" />
<PackageReference Include = "Microsoft.VisualStudio.Web.CodeGeneration.Design" Version = "2.2.3" />
<PackageReference Include = "MimeKit" Version = "2.1.3" />
<PackageReference Include = "Novell.Directory.Ldap.NETStandard2_0" Version = "3.1.0" />
<PackageReference Include = "Npgsql.EntityFrameworkCore.PostgreSQL" Version = "2.2.0" />
<PackageReference Include = "OpenIddict" Version = "2.0.0" />
<PackageReference Include = "OpenIddict.EntityFrameworkCore" Version = "2.0.0" />
</ItemGroup>
```

So far, each method has the following authorization attribute:
`[Authorize (AuthenticationSchemes = OAuthIntrospectionDefaults.AuthenticationScheme)]`

Package `AspNet.Security.OAuth.Introspection` is deprecated, I need to find another solution.
I don't know what my new attribute should look like.

Using the available knowledge, I used:
`[Authorize (AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]`

I changed my AuthorizationController and in the Startup.cs file I added the following code:
```
.AddValidation (options =>
{
// Import the configuration from the local OpenIddict server instance.
options.UseLocalServer ();

// Register the ASP.NET Core host.
options.UseAspNetCore ();
});
```

As a result, within the AuthApp application:
- /connect/token/ zwraca mi prawidłowe tokeny, których może uzyć
- /api/userinfo zwraca mi informacje o zalogowanym użytkowniku na podstawie tokenu
- /api/user/:id pozwala czytać informacje o wskazanym użytkowniku (wymagany poprawny token)

Everything seems to be working fine.
However, I have doubts whether the `OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme` scheme can be treated as an equivalent for `OAuthIntrospectionDefaults.AuthenticationScheme`?
Is my solution really good?

I am wondering about this because my AppA and AppB apps are now having a problem with user authorization and returning error 500. AuthApp seems to be working 100% correctly.

I don't know if the configuration of the A / B application is to blame. Maybe I made a mistake with the configuration of AuthApp. In particular, I'm not convinced of the AuthenticationSchemes value set.

For now, I am asking only for confirmation if I changed the authorization method in AuthApp correctly.

Sorry for silly questions. I'm not an advanced person with OpendIdDict. It is really simple solution and doesn't require a lot of knowledge.

**Comment by kevinchalet** [comment]
Hi and thanks for sponsoring the project!

> Is my solution really good?

The aspnet-contrib introspection handler has been merged into the OpenIddict validation handler, that now supports local validation and remote validation (introspection). So yeah, it's fine.

> For now, I am asking only for confirmation if I changed the authorization method in AuthApp correctly.

What you have in AuthApp is fine: when the API is in the same project as the authorization server, using `options.UseLocalServer()` is the simplest and best option.

For your other projects, you'll want to use introspection. Take a look at https://github.com/openiddict/openiddict-samples/blob/dev/samples/Zirku/Zirku.Api1/Startup.cs#L16-L36 for a concrete example.

**Comment by kevinchalet** [comment]
@Dinatte let me know if you still need help 😃

**Comment by Dinatte** [comment]
Hello,
Thanks for quick reply and the example. I was browsing this repository but had not seen this code before ;) 

I have a problem with one app, but the other app is working fine, so I think we can close this issue. 
Perhaps I will open another one with a specific description of the error, if I cannot solve it myself.


Thank you! :)
