### ISSUE TITLE
Determine whether the log level of request errors should be lowered

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1205]
Currently, request errors are logged as `Error`s. While semantically correct, this can result in a bit too much noise.

We should determine if there's a consensus in the community, what's the norm in ASP.NET Core itself and whether we should update these logs to use the `Warning` or `Information` levels.

/cc @schmitch

**Comment by NoahStahl** [comment]
I can't speak to a consensus, but I think it would be great if there were a configurable `LogLevel` offered so the application could set a default level for errors and warnings, or perhaps an optional error handler delegate for those wanting more dynamic control.

Operationally, my rule of thumb is to log errors that are "my fault", and not flag those at fault of public requests that will always be hitting with something or other deliberately malformed.

**Comment by deanmarcussen** [comment]
If we're voting here, I'd vote for a drop to `Warning` or `Information`.

When they're `Error`, you can't really use the ASP.NET logging filters to filter what're you're seeing. But when they are a lower log level, if you need to you can bump them up, as and when required.

It's a slightly different scenario, but we just reduced the ImageSharp logging for `File Not Found`, to match that of the ASP.NET `StaticFileMiddleware`, as it was on Error, which was just a bit of a recipe for over logging.

**Comment by kevinchalet** [comment]
Sold, let's do that as part of the next update: most `Errors` logs will be replaced by `Informations` but we'll likely want to use the `Warning` level for a few select errors that may indicate potential attacks (e.g when an authorization code or refresh token is used by a different client application)
