### ISSUE TITLE
Using introspection validation with public applications

### ISSUE THREAD

**Issue by miegir** [openiddict/openiddict-core#1206]

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As specified, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.

**Comment by miegir** [comment]
I deleted original text because of understanding that using introspection validation with public client is unlikely to be supported. GitHub community will be unable to recommend more elegant solution than my workaround anyway.
