### ISSUE TITLE
Problem with handling introspection errors

### ISSUE THREAD

**Issue by miegir** [openiddict/openiddict-core#1207]
In my web project I use introspection validation. I need to implement additional validation after the one provided by OpenIddict (i.e. I need to lookup user in our employee database with the value of the sub claim). I do so by adding event handler for HandleIntrospectionResponseContext. Such approach works in principle. But when I did not find entity in the database, I call HandleIntrospectionResponseContext.Reject. And the problem is that arguments passed to the Reject method are ignored and standard www-authenticate header is returned which does not describe the error exactly:
`www-authenticate: Bearer error="invalid_token", error_description="The specified token is invalid.", error_uri="https://documentation.openiddict.com/errors/ID2004"`.

As I digged out, the cause is as follows. My handler is invoked by the code:
https://github.com/openiddict/openiddict-core/blob/5a6417f756ca3421a90827dbab9011ca6015ef7a/src/OpenIddict.Validation/OpenIddictValidationService.cs#L454-L459
When context is rejected, it throws GenericException. It saves Error, ErrorMessage and ErrorUri for possible use.

But then this exception is  catched here:
https://github.com/openiddict/openiddict-core/blob/5a6417f756ca3421a90827dbab9011ca6015ef7a/src/OpenIddict.Validation/OpenIddictValidationHandlers.cs#L358-L368
There is no special handling for GenericException and therefore standard error is generated instead.

Is this an error? Should there be specialized catch clause for GenericException?

**Comment by kevinchalet** [comment]
It's deliberate: errors can contain potentially very sensitive stuff and are not returned as-is. Instead they are logged and a generic error is returned.

Anyway, even if we changed that, "invalid token" errors returned by the introspection endpoint typically only include `active: false` and no message indicating why that failed, as asked by the introspection specification.
