### ISSUE TITLE
Bug: Unexpected behavior occurs with audience verification

### ISSUE THREAD

**Issue by robertkhou** [openiddict/openiddict-core#1208]
Expected behavior: Each resource server is to be configured with it's own audience and not configured to add audience of all resource servers.

---
The following error message should not occur, when you only add specific audience and not the full list of audience to the resource server

www-authenticate: Bearer error="invalid_token"error_description="The specified token cannot be used with this resource server."error_uri="https://documentation.openiddict.com/errors/ID2094" 
---

**How to reproduce this error**
(Assume you have 3 resource servers, account, order, payment)
Open ID Connect server
1. Client Credentials: add the full set of resources, for example "account, order, payment" 
Payment Web API (client)
2. Since this is the payment resource server, you only add "payment" audience (you leave out "order" and "payment")
3. Use the access token returned from the open id connect server to make a web api call to any payment api endpoint.
4. An error occurs via open id connect server "The specified token cannot be used with this resource server."

**Work around**
Add the full set of resources "account, order, payment" etc to all resource servers. now everything will work, but it shouldn't work like this.

**Comment by kevinchalet** [comment]
I cannot reproduce that locally. Please consider sending a repro that exhibits the problem.

**Comment by NecatiKaya** [comment]
I am using openIdDict also. I have one Auth Server and Api host project. All with C#.NET Core 9. Api project uses introspection to introspect token from auth server. My configs are also as below.

Problem: Token is not introspected when you are using introspection (not local validation in resource server) if your audience does not contain your inspector client name.

Solution: When you are using auth server introspector, both resource client and introspector client must be provided to AddAudiences method inside resource configuration

**Api**

  services.AddOpenIddict()
            .AddValidation(validationBuilder =>
            {
                validationBuilder.AddAudiences(authServerConfiguration.Audience!, _"customer-introspector"_);
                validationBuilder.SetIssuer(authServerConfiguration.IssuerUrl);
                validationBuilder.AddEncryptionKey(new SymmetricSecurityKey(
                    Convert.FromBase64String(authServerConfiguration.EncryptionKey)));
                validationBuilder.UseAspNetCore();
                validationBuilder.UseSystemNetHttp();
                validationBuilder.UseIntrospection()
                    .SetClientId(authServerConfiguration.Introspection!.ClientId)
                    .SetClientSecret(authServerConfiguration.Introspection.ClientSecret);
            });

**Auth Server**
await manager.CreateAsync(new OpenIddictScopeDescriptor
        {
            DisplayName = "Customer API Access",
            DisplayNames =
            {
                [SupportedCultures.English] = "Customer API Access",
                [SupportedCultures.Turkish] = "Customer API Erişimi"
            },
            Name = "Customer.Api",
            Resources =
            {
                "customer-resource",
                _"customer-introspector"_
            }
        });


**Api.Host. csproj**

 
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0-rc.2" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.0.0-preview4.24563.42" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.0.0-preview4.24563.42" /> 
 

**Auth.Host csproj**

 
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
        <PackageReference Include="OpenIddict.Abstractions" Version="6.0.0-preview4.24563.42" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.0.0-preview4.24563.42" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.0.0-preview4.24563.42" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0-rc.2" />
    </ItemGroup>
