### ISSUE TITLE
How / where to set the full user name in the id token?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1212]
I added a Fullname property to the ApplicationUser class. It is being saved as expected.

However when the user is authenticated and the id token is returned, it's the email that's included in the name property. How and where do I need to set the full name so the id token gets created correctly?

**Comment by kinosang** [comment]
https://github.com/openiddict/openiddict-core/blob/bf828b8dfe64be014f87d09e62fbe59c1c46f60a/samples/Mvc.Server/Controllers/UserinfoController.cs#L40-L65

see comment below.

I have misunderstood your problem.

**Comment by cryo75** [comment]
Thanks

**Comment by kinosang** [comment]
sorry I gave the wrong link.

https://github.com/openiddict/openiddict-core/blob/b6766e480ef82c7e150c6deef794ecb2682c3419/test/OpenIddict.Abstractions.Tests/Primitives/OpenIddictExtensionsTests.cs#L1514

set the claims before set the destinations.

https://github.com/openiddict/openiddict-core/blob/bf828b8dfe64be014f87d09e62fbe59c1c46f60a/samples/Mvc.Server/Controllers/AuthorizationController.cs#L510-L513

https://github.com/openiddict/openiddict-core/blob/bf828b8dfe64be014f87d09e62fbe59c1c46f60a/samples/Mvc.Server/Controllers/AuthorizationController.cs#L534-L535

**Comment by kevinchalet** [comment]
FYI, I added some documentation for the claim destinations feature: https://documentation.openiddict.com/configuration/claim-destinations.html

Let me know if there's anything unclear.

**Comment by cryo75** [comment]
Thanks. Very well documented!
