### ISSUE TITLE
How to add an additional authentication scheme with OpenIddict along with Windows Authentication?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1214]
My resource server has windows authentication out-of-the-box. And now I want to add additional authentication schemes. So I added the following to the resource server:

```c#
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            });

            services.AddOpenIddict()
                .AddValidation(options =>
                {
                    options.SetIssuer(Configuration["Settigns:Issuer"]);

                    if (Convert.ToBoolean(Configuration["Settings:UseIntrospection"]))
                    {
                        options.UseIntrospection()
                               .SetClientId(Configuration["Settings:ClientId"])
                               .SetClientSecret(Configuration["Settings:ClientSecret"]);
                    }
                    else
                    {
                        options.AddEncryptionKey(new SymmetricSecurityKey(Convert.FromBase64String(Configuration["Settings:EncryptionKey"])));
                    }

                    options.UseSystemNetHttp();
                    options.UseAspNetCore();
                });
````

Is this enough to handle both windows and  bearer authentication schemes on the resource server?

**Comment by kevinchalet** [comment]
As I said in another thread, using Integrated Windows Authentication directly at the API/resource server layer is a bad idea and a good way to make your app vulnerable to CSRF. If possible, you should consider moving that IWA support to the authorization server and update the callers to use OIDC (in this case, most likely the code flow).

> Is this enough to handle both windows and bearer authentication schemes on the resource server?

Impossible to say without seeing how you handle the WIA part, but in this case, I'd tempted to say it will only work with tokens.

**Comment by cryo75** [comment]
Moving WIA to the auth server would be optimal. However, if the auth server is in a different domain, then WIA will not work. And if I move the WIA to the auth server, do I need to implement the same code as in the Window Auth sample? 

I'm not handling any WIA. It's all done out-of-the-box. WIA is enabled for the resource server.

I also see that requests now have 3 WWW Authentication headers (NTLM; Negotiate, Bearer). Is this correct?

**Comment by kevinchalet** [comment]
> However, if the auth server is in a different domain, then WIA will not work.

As long as the machine and the account running the ASP.NET Core host are correctly configured to use IWA, I don't see why this wouldn't work: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0

> And if I move the WIA to the auth server, do I need to implement the same code as in the Window Auth sample?

That sample is great, so yeah, you can follow it. In case you'd be looking for a sample that doesn't use the degraded mode, I just added one for you: https://github.com/openiddict/openiddict-samples/commit/15c17c17fde47986b3ab3cd892b45ca15ab1d78c

> I also see that requests now have 3 WWW Authentication headers (NTLM; Negotiate, Bearer). Is this correct?

It is: while not recommended, the OpenIddict validation handler should play nice with other headers-based authentication handlers, so having a double OpenIddict/IAW challenge is fine. Now, you'll want to check whether `HttpContext.User` is correctly populated with your IWA claims or not, if you absolutely want to handle IAW at the resource server level.

**Comment by cryo75** [comment]
Thanks for the info. I thought about it and I will do as you suggest. WIA at the auth server and Oidc at the resource level. Any other solution is a mess.
