### ISSUE TITLE
Bug in PruneAsync execution?

### ISSUE THREAD

**Issue by filippomoretto** [openiddict/openiddict-core#1216]
Hello,
I'm trying using PruneAsync method of TokenStorage. It doesn't delete all the tokens as I expected, so I looked at the code in OpenIddictEntityFrameworkCoreTokenStore.cs and noticed that for each cycle the transaction is created, 1000 tokens are deleted and the save is performed. In this way 1000 tokens are deleted, then due to the offset it skips 1000 to delete another 1000, then it skips 2000 and so on.
Am I wrong something?

Sorry for my bad English.

**Comment by kevinchalet** [comment]
Hey,

Thanks for your report, it makes total sense. Would you be interested in sending a PR to fix that?
