### ISSUE TITLE
code flow with polling

### ISSUE THREAD

**Issue by GDreyV** [openiddict/openiddict-core#1218]
Hello, I'm looking for a proper way to perform kind of mixture of code flow and device flow. I have a plugin for an app which can open browser but can't interact with it and can't handle return url. So I suppose it must be kind of polling from device flow to obtain all the tokens. What flow/settings should be used in that case?

**Comment by kinosang** [comment]
use `device flow` as you say.

**Comment by GDreyV** [comment]
Good point :) I missed that `verify` endpoint might apply device code as parameter, so user do not really need to input anything.

**Comment by GDreyV** [comment]
Just in case if anybody is looking for a proper way how to implement device flow with OpenIDDict here are several links I found useful for myself:
https://auth0.com/docs/flows/device-authorization-flow
https://github.com/openiddict/openiddict-core/pull/842/commits/f536e56b116c996af4ce4bf58c80469351c9ffac
https://gitter.im/openiddict/openiddict-core?at=5df76db22cc1b31e342a35a7
https://tools.ietf.org/html/rfc8628#section-3.5

**Comment by GDreyV** [comment]
Just realized that authorization doesn't work with the tokens but requires cookie value. I found pretty long topic https://github.com/openiddict/openiddict-core/issues/578 which seems to be pretty old. So what's the right configuration to avoid cookies usage?

**Comment by kevinchalet** [comment]
@GDreyV you mean the API endpoints? If so, it should work like with any other flow: `[Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]`.

**Comment by GDreyV** [comment]
@kevinchalet , sorry, it looks like I was a bit lost in configurations and help articles how it supposed to work. I finally found that proper configuration should include:
```
services.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            });
```
Not sure though if it's the same as Authorize attribute. Really I thought `token` authorization is a most common case of API usage. Not sure why it's cookie by default.

**Comment by kevinchalet** [comment]
> Not sure why it's cookie by default.

I'd recommend leaving cookies as the default scheme in mixed cookies+tokens scenarios, as things like the antiforgery token validation middleware are known to only work with the default authentication scheme (yet, if you use tokens as the default scheme, it won't work correctly).

**Comment by GDreyV** [comment]
@kevinchalet , sorry, could you please add some details. So what is the right combination of magic spells? Using example I provided device verification doesn't work at all as it requires cookies. Who will set the cookies? Should I roll back to `services.AddIdentity<ApplicationUser, IdentityRole<Guid>>()` instead of `.AddIdentityCore`?
```
services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultScheme = OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            });
```

**Comment by kevinchalet** [comment]
It's not clear to me what's not working correctly.

If you're referring to the token authentication process, decorating your API controllers with `[Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]` is what I'd recommend.
If you're referring to the ASP.NET Core Identity authentication/verification dance, then yes, it depends on cookies being enabled: if you use `.AddIdentityCore()` instead of `AddIdentity()`, then things get more complicated as you have to add the cookies handlers yourself.

I'd recommend using `AddIdentity()` and removing the snippet you posted to keep the default ASP.NET Core Identity schemes as the default schemes.

**Comment by GDreyV** [comment]
I thought that it must be just single spell to rule them all :) I mean I can set something like "always use bearer token except authorization". But I checked and your suggestions work well so far. Thanks!
