### ISSUE TITLE
How to turn off case-sensitive redirect uris?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1223]
I have added redirect and logout redirect uri's for an application using pascal casing. When I use all lowercase to access the website, the following is logged:

[WRN] Client validation failed because 'https://xxx/yyy/signin-oidc' was not a valid redirect_uri for MyApp.
[ERR] The authorization request was rejected because the redirect_uri was invalid: 'https://xxx/yyy/signin-oidc'.

When I use the exact same casing, everything works fine?

Is there a setting that I might set to turn off case-sensitivity for the redirect uri's?

**Comment by kevinchalet** [comment]
> Is there a setting that I might set to turn off case-sensitivity for the redirect uri's?

No. The OIDC specification requires doing simple string comparison, which is essentially byte-for-byte comparison. As such, there's no flag to change the way the `redirect_uri` validation routine works.

Potential options:
  - Fixing the client to always use the same `redirect_uri`.
  - Adding multiple `redirect_uri`s to deal with uppercased URLs.
  - Overriding the OpenIddict application manager to override the default validation logic (bad idea).

**Comment by cryo75** [comment]
I tried to go with the first option so I did:

Added the following in `Startup.cs`:

```c#    
    options.Events = new OpenIdConnectEvents
    {
        OnRedirectToIdentityProvider = async context =>
        {
            context.ProtocolMessage.RedirectUri = Configuration["RedirectUri"];
            await Task.CompletedTask;
        }
    };
```

And then in `appsettings.json`:

    "RedirectUri": "https://host/AppName/signin-oidc"

and in `appsettings.Development.json`:

    "RedirectUri": "https://localhost:44311/signin-oidc"

When I run the app locally, everything is working fine. The redirection works as expected. Running the app once deployed, the redirection works only if the url typed in the browser is also case-senstive. When it's not, it tries to redirect to the case-sensitive url, but I get a 400 error. The redirect uri passed to `connect/authorize` is correct but it doesn't want to work.

So now I don't know what the problem is.

**Comment by kevinchalet** [comment]
Well, the 2 URLs you shared (production and development) point to completely different hosts (`host` vs `localhost`). Are you 100% sure it's just a case-sensitivity issue?

**Comment by cryo75** [comment]
Yes I'm sure. Both URLs are registered for the application. `localhost` works always (it's also all in lowercase). In production, `AppName` as the host works, but `appname` doesn't as it returns with 400. So what I tried to achieve with the above was to enforce the correct casing but it didn't solve the problem.

What is weird is that the parameters passed to `connect/authorize` are the same (apart from code_challenge, nonce, etc)

**Comment by kevinchalet** [comment]
And have you tried to register both `https://host/AppName/signin-oidc` and `https://host/appname/signin-oidc`?

If it still doesn't work, it's likely not an OI-related issue (most likely an IIS issue, as I suppose /AppName is just a IIS virtual directory)

**Comment by cryo75** [comment]
Both are now registered without any further changes to the above code. The lowercase version still doesn't work. Furthermore, IIS should be case-insensitive.

**Comment by kevinchalet** [comment]
I'm out of ideas. Consider posting a minimalist repro on a private GitHub repository and I'll take a look to confirm it's not an OI issue.

**Comment by kevinchalet** [comment]
Closing for now, but feel free to reopen if needed.
