### ISSUE TITLE
Error message not clear, documentation missing

### ISSUE THREAD

**Issue by danielleiszen** [openiddict/openiddict-core#1225]
I try to use AuthCode + PKCE from SPA client.
After I get the Code, I would call the token endpoint for the access token.

The relevant part of the logs are:

```
[15:12:56 INF] The token request was successfully extracted: {
  "grant_type": "authorization_code",
  "code": "[redacted]",
  "redirect_uri": "http://localhost:6200/",
  "client_id": "dashboard",
  "code_verifier": "XRkc42OkRXmhiOCNNQqMDk0TjGQDn3SBDvLuLWIPpcDNZts5T9"
}.
```

Then I get an error message:

```
[15:12:56 ERR] The token request was rejected because the 'code_verifier' parameter didn't correspond to the expected value.
[15:12:56 INF] The response was successfully returned as a JSON document: {
  "error": "invalid_grant",
  "error_description": "The specified 'code_verifier' is invalid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2052"
}.
```

1. The given documentation url is not working.
2. The [source code](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs) includes 2052 at three segments:
- Prompt.None with Promt.OTHERS: not in my case
- Missing ClientId: the client id is present as seen in request
- Unrecognized scope: I would vote for this, but the error states invalid grant, and I really cannot see the way to get closer to the problem by this error message.

Thanks for clarifying this.

**Comment by kevinchalet** [comment]
> The given documentation url is not working.

https://github.com/openiddict/openiddict-documentation/issues/30

> Thanks for clarifying this.

The error sounds clear to me: you sent a wrong `code_verifier`.

**Comment by kevinchalet** [comment]
Closing for now, as this doesn't seem to be a bug in OI (questions are reserved to sponsors as a way to thank them).

**Comment by ghost** [comment]
I am facing exactly the same issue.   I am unable to find the exact reason. Any help will be really appreciated. 

**Request**

Address 	= "https://localhost:44373/connect/token"
ClientId 	= "My.Sample.Application"
ClientSecrent 	= "901564A5-E7FE-XXXXXXXX"
Code		= "5YyWmExZmnMEGMnBaoPN1WLh9DOQmHslO_ip3Lhvh8U"
CodeVerifier	= "_NZ9wKVx0oYtHhehs_D49g"
GrantType	= "authorization_code"
RedirectUri	= "https://localhost:44340/signin-oidc"
Parameters
   code		 = "5YyWmExZmnMEGMnBaoPN1WLh9DOQmHslO_ip3Lhvh8U"
   code_verifier = "_NZ9wKVx0oYtHhehs_D49g"
   grant_type	 = "authorization_code"

**Response**

{
  "error": "invalid_grant",
  "error_description": "The specified 'code_verifier' is invalid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2052"
}

**Client Side Code** 

[clientside_code.txt](https://github.com/openiddict/openiddict-core/files/6722266/clientside_code.txt)

**Server Side Code**

[serverside_code.txt](https://github.com/openiddict/openiddict-core/files/6722265/serverside_code.txt)

Error Message

> 
info: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The request address matched a server endpoint: Token.
info: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The token request was successfully extracted: {
        "code": "[redacted]",
        "code_verifier": "_NZ9wKVx0oYtHhehs_D49g",
        "redirect_uri": "https://localhost:44340/signin-oidc",
        "grant_type": "authorization_code",
        "client_id": "My.Sample.Application",
        "client_secret": "[redacted]"
      }.
fail: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The token request was rejected because the 'code_verifier' parameter didn't correspond to the expected value.
info: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The response was successfully returned as a JSON document: {
        "error": "invalid_grant",
        "error_description": "The specified 'code_verifier' is invalid.",
        "error_uri": "https://documentation.openiddict.com/errors/ID2052"
      }.
