### ISSUE TITLE
Client side introspection issue

### ISSUE THREAD

**Issue by DuncancMartin** [openiddict/openiddict-core#1227]
Hi Kevin
I have Introspection set up on my identity server, and I have added the resource name into my ticket like so:
`            ticket.Principal.SetResources("publicApi");`

I can create a ticket in postman, and when I hit the introspection endpoint, I can see it working like so (this token has been revoked):
![image](https://user-images.githubusercontent.com/33480994/111199970-23bd8900-85b9-11eb-9a87-54a66ddc19b6.png)

However, when I use this token to access an endpoint in my client application, it is working as if the token is valid. When I look at my server logs I see that the introspection endpoint is being hit, but that it is querying the OpenIddictApplications table and returning an error saying: 
"The introspection request was rejected because the client application was not found: '{ClientId}'."

It is not some sort of connection issue, because I can achieve the same result as in Postman if I call /introspect direct from inside my client application. I'm assuming that it is erroring through the client but not through Postman because the client is providing more data and in that case it checks the database - to make this work do I need to put data into the OpenIddictApplications table or can I solve this in the client configuration?

My client config looks like this (I'm not sure what the difference between an Audience and a ClientId is):
```
            services.AddOpenIddict()
                .AddValidation(options =>
                {

                    options.SetIssuer(_config["IdentityMicroServiceUrl"]);
                    options.AddAudiences("publicApi");

                    options.UseIntrospection()
                       .SetClientId("publicApi")
                       .SetClientSecret("846B62D0-DEF9-4215-A99D-86E6B8DAB342");

                    // Register the System.Net.Http integration.
                    options.UseSystemNetHttp();

                    // Register the ASP.NET Core host.
                    options.UseAspNetCore();
                });
```

Adding this into the server side code made no difference:
```
                    options.IgnoreEndpointPermissions()
                      .IgnoreGrantTypePermissions()
                      .IgnoreScopePermissions();
```

I've been plugging away at this for a while now, but each step is taking longer and longer, so I would be grateful if you can offer me some pointers to finally getting this working!

Thanks
Duncan

**Comment by DuncancMartin** [comment]
I have made 2 steps forward, but also one back. I did some digging in the source code and found where it was checking the database, which meant I was able to find a demo (for RC2, but it seems to work for RC3) of how to add the Application to the DB. This is working well, and now when my application hits the introspection endpoint, the server is able to go through the normal flow, and check that the token is OK. The problem is that when the token is not valid, the server logs this (extra json bit snipped):

> "The token '{Identifier}' was no longer valid."
> "The response was successfully returned as a JSON document: {Response}.","Response":"{\n  \"active\": false\n}"

and then the client logs the following message and just carries on with executing the method. 

> {"@t":"2021-03-16T12:58:30.9282219Z","@mt":"{AuthenticationScheme} was not authenticated. Failure message: {FailureMessage}","AuthenticationScheme":"OpenIddict.Validation.AspNetCore","FailureMessage":"An error occurred while authenticating the current request.","EventId":{"Id":7,"Name":"AuthenticationSchemeNotAuthenticatedWithFailure"},"SourceContext":"OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler","RequestId":"0HM78EBN23523:00000004","RequestPath":"/api/v1.0/Clerks","ConnectionId":"0HM78EBN23523","IM-Dockerbuild":"any.build.number","IM-TenantId":null}

I don't understand why the client is ignoring what is coming back from the introspection endpoint (it definitely does some auth, because if execution fails if I give the client a bad token).

FWIW, my server side change looks like this (it's called at the end of the Configure method on startup):

```
   private async Task InitializeAsync(IServiceProvider services, CancellationToken cancellationToken)
        {
            // Create a new service scope to ensure the database context is correctly disposed when this methods returns.
            using (var scope = services.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                var manager = scope.ServiceProvider.GetRequiredService<IOpenIddictApplicationManager>();

                if (await manager.FindByClientIdAsync("publicApi", cancellationToken) == null)
                {
                    var descriptor = new OpenIddictApplicationDescriptor
                    {
                        ClientId = "publicApi",
                        DisplayName = "Public API",
                        PostLogoutRedirectUris = { new Uri("https://oidcdebugger.com/debug") },
                        RedirectUris = { new Uri("https://oidcdebugger.com/debug") },
                        ClientSecret = "846B62D0-DEF9-4215-A99D-86E6B8DAB342"
                    };

                    await manager.CreateAsync(descriptor, cancellationToken);
                }
            }
        }

```

Is this the correct way to register a client application, and do you have any pointers as to why when introspection fails, it carries on as if it had succeeded?

**Comment by DuncancMartin** [comment]
Is the reference to AuthenticationScheme related to this line in the client?

```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            }).AddOAuthValidation();
```
I've been searching in Gitter, and it seems like maybe I'm using both the regular authentication and the validation flows - I understand I should only do the second one, but if I remove the above then I get the following error:

>   "error": "No authentication handler is registered for the scheme 'Bearer'. The registered schemes are: OpenIddict.Validation.AspNetCore. Did you forget to call AddAuthentication().Add[SomeAuthHandler](\"Bearer\",...)?"

Do you think that my diagnosis is correct, and if so, how can I avoid using the regular authentication?
Thanks
Duncan

**Comment by kevinchalet** [comment]
Hey,

> However, when I use this token to access an endpoint in my client application, it is working as if the token is valid.

Like any other ASP.NET Core authentication handler, the OpenIddict validation handler is not responsible of "blocking" unauthenticated requests (that may be unauthenticated because the token was missing or invalid). This is an authorization concern that is exclusively handled by the authorization middleware in ASP.NET Core.

This is typically done by decorating your API controllers with `[Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]`, that simply creates a "require an authenticated user using tokens" policy under the hood.

> Is this the correct way to register a client application

Yes, what you have is fine.

> I've been searching in Gitter, and it seems like maybe I'm using both the regular authentication and the validation flows - I understand I should only do the second one, but if I remove the above then I get the following error:

I suggest keeping the cookies handlers registered by ASP.NET Core Identity as the default schemes. Instead, consider using `[Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]`.

**Comment by DuncancMartin** [comment]
Making this change for the client endpoint:
```
    [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]
    //[Authorize(AuthenticationSchemes ="Bearer")]
```
results in this error (no matter what data/parameters I pass):

> System.InvalidOperationException: An unknown error occurred while retrieving the OpenIddict validation context.
>    at OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
>    at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at PublicApiGatewayV2Api.Middleware.ExceptionHandlingMiddleware.Invoke(HttpContext context, ISessionService _sessionService, IOptions`1 settings) in C:\GitHub\K3\K3Imagine\PublicApiGatewayV2\PublicApiGatewayV2Api\Middleware\ExceptionHandlingMiddleware.cs:line 39}
>     Data: {System.Collections.ListDictionaryInternal}
>     HResult: -2146233079
>     HelpLink: null
>     InnerException: null
>     Message: "An unknown error occurred while retrieving the OpenIddict validation context."

This looks to me like I'm missing some plumbing that allows the middleware to connect it up to a validator, but it could also be because my request is incorrectly formatted - is it still OK to include the word "Bearer" in the Authorization header in front of the token? The token_type is "Bearer", even though the scheme that I've used to create the token is OpenIddictServerAspNetCoreDefaults.AuthenticationScheme. If that's fine, how do I determine what I'm missing in terms of the validation context?

**Comment by kevinchalet** [comment]
Are you sure the authentication/authorization middleware are registered in the correct order? Can you please share your Startup config?

**Comment by DuncancMartin** [comment]
This is the startup for the client:
```
        public void ConfigureServices(IServiceCollection services)
        {

            var redisHost = _config.GetValue<string>("RedisHost");
            var redisPort = _config.GetValue<int>("RedisPort");
            var redis = ConnectionMultiplexer.Connect($"{redisHost}:{redisPort}");

            services.AddDataProtection()
                .SetApplicationName("Imagine")
                .PersistKeysToStackExchangeRedis(redis, "DataProtection-Keys");

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
                options.DefaultForbidScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
            });

            //services.AddAuthorization(options =>
            //{
            //    options.AddPolicy("ModuleAccess",
            //        policy => policy.RequireClaim(ClaimType.Name, "PublicApi"));
            //});

            services.AddMvc()
                .AddControllersAsServices()
                .AddMetrics()
                .AddNewtonsoftJson();

            services.AddOpenIddict()
                .AddValidation(options =>
                {

                    options.SetIssuer(_config["IdentityMicroServiceUrl"]);
                    options.AddAudiences("publicApi");

                    options.UseIntrospection()
                       .SetClientId("publicApi")
                       .SetClientSecret("846B62D0-DEF9-4215-A99D-86E6B8DAB342");

                    // Register the System.Net.Http integration.
                    options.UseSystemNetHttp();

                    // Register the ASP.NET Core host.
                    options.UseAspNetCore();
                });

            services.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VV");
            services.AddApiVersioning(o =>
            {
                o.ReportApiVersions = true;
                o.DefaultApiVersion = new ApiVersion(1, 0);
                o.AssumeDefaultVersionWhenUnspecified = true;
            });

            services.AddCors();
            services.AddAutoMapper(typeof(MapperConfig));
            services.AddSharedFunctionalityInjection();

            services.ConfigureSwagger(options =>
            {
                options.Title = "Public API Gateway V2";
                options.SetVersionInPaths = true;
                options.AddBearerTokenAuth = true;
                options.AddAuthorizationHeader = true;
            });


                services.Configure<Config>(_config);
            services.AddTypedHttpClients(_config);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IApiVersionDescriptionProvider provider)
        {

            app.ConfigureSwaggerAndBasePath(provider, _config.GetValue<string>("BasePath"));

            app.UseRouting();
            app.UseCors(_corsAllowAll);

            app.UseDeveloperExceptionPage();

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint($"./v1.0/swagger.json", "v1.0");
            });

            app.UseMiddleware<ExceptionHandlingMiddleware>();

            app.UseStaticFiles();

            app.UseAuthorization();
            app.UseAuthentication();

            app.UseEndpoints(i => i.MapControllers());
        }
```

**Comment by kevinchalet** [comment]
Your ASP.NET Core configuration is invalid: you must register the authentication middleware before the authorization middleware.

**Comment by DuncancMartin** [comment]
That fixed it, and now this whole process works.  Thanks Kevin - it would have taken me forever to find that!

**Comment by kevinchalet** [comment]
Glad I could help!
