### ISSUE TITLE
How can you change the UI?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#123]
Is it possible to use a custom view for openiddict-core?  I want to change the buttons on this screen, if so, how do you go about it, cos cant find anything on there?

![image](https://cloud.githubusercontent.com/assets/7406381/15510495/760908c2-21cf-11e6-8a53-741e6025301e.png)

**Comment by kevinchalet** [comment]
Yep, it's possible: create an `OpenIddict` folder under `Views` and add an `Authorize.cshtml` view.

You can reuse the default view and customize it the way you want:

```
@using AspNet.Security.OpenIdConnect.Extensions
@using Microsoft.IdentityModel.Protocols.OpenIdConnect

@model Tuple<OpenIdConnectMessage, string>

<div class="jumbotron">
    <h1>Authorization</h1>

    <p class="lead text-left">Do you wanna grant <strong>@Model.Item2</strong> access to your resources? (scopes requested: @Model.Item1.Scope)</p>
    <p class="lead text-left"><strong>@Model.Item2</strong> will be able to access the following endpoints: @string.Join(" ; ", Model.Item1.GetResources())</p>

    <form enctype="application/x-www-form-urlencoded" method="post">
        @Html.AntiForgeryToken()

        @foreach (var parameter in Model.Item1.Parameters) {
            <input type="hidden" name="@parameter.Key" value="@parameter.Value" />
        }

        <input formaction="@Url.Action("Accept")" class="btn btn-lg btn-success" name="Authorize" type="submit" value="Yeah, sure" />
        <input formaction="@Url.Action("Deny")" class="btn btn-lg btn-danger" name="Deny" type="submit" value="Hell, no" />
    </form>
</div>
```

**Comment by Gillardo** [comment]
@PinpointTownes thanks for this, it seems nice and easy.  On a similar note, you will notice that on my screen shot, the available endpoints seem to be empty??  Why?  What should i of done in order to populate them?

**Comment by Gillardo** [comment]
Also, if i have created a login and accepted everything, why upon logging in everytime should i have to Confirm authorization?  Is it possible to drop this screen altogether?

**Comment by kevinchalet** [comment]
> @PinpointTownes thanks for this, it seems nice and easy. On a similar note, you will notice that on my screen shot, the available endpoints seem to be empty?? Why? What should i of done in order to populate them?

The `resources` list is determined by the `resource` space-separated parameter. It's useful when using JWT access tokens, as the JWT bearer middleware requires a non-empty audience by default. If you use our validation middleware, it's not needed.

I sent a PR to improve this view a bit: https://github.com/openiddict/openiddict-core/pull/124.

> Also, if i have created a login and accepted everything, why upon logging in everytime should i have to Confirm authorization? Is it possible to drop this screen altogether?

For security reasons, you can't skip the authorization consent. We'll likely merge the login and consent screens in the future, but we'll unlikely allow skipping it completely (maybe except for confidential clients).

**Comment by xperiandri** [comment]
I agree with @Gillardo that if I am an owner of a Server App and a Client App my user must not be prompted for authorization.

**Comment by xperiandri** [comment]
With regard to the discussion above I want to ask if Mobile App developed by the Server App owner can be treated as `Confidential`?

**Comment by rpicone** [comment]
Hi, 

about "...but we'll unlikely allow skipping it completely (maybe except for confidential clients).", how can I help with this? 

This feature would be very cool. In many cases, the developers creates an openid server just for one application/service, and a user who doesn´t whant use that application, doesn´t want to register anyway. Today, after be registered, they are asked to authorize the client, so it´s kind of redundant.

**Comment by kevinchalet** [comment]
> This feature would be very cool.

If you want to implement that, I'd recommend creating your own authorization controller instead of using the optional MVC module (that might be removed if we decide to use a template-only approach: https://github.com/openiddict/openiddict-core/issues/46).

Here's an example: https://github.com/Ciantic/AspNetApiMonolithSample/blob/master/src/Api/Controllers/OpenIdController.cs#L114

When using your own authorization controller, you have almost total flexibility, but it's also a risk. Avoid doing crazy things :smile:
