### ISSUE TITLE
Iddictoptions still require encryptioncertificate when dataprotection package is added?

### ISSUE THREAD

**Issue by gustavdw** [openiddict/openiddict-core#1231]
Hello!
Using Iddict 3.0.2

I was under the impression the Dataprotection package would replace the encryption certificate and that one wouldn't need to be registered, what am I missing? I'm registering DP with:
```
o.UseDataProtection(dp =>
{
    dp.PreferDefaultAccessTokenFormat();
});
```

And I'm getting the following error.

At least one encryption key must be registered in the OpenIddict server options. Consider registering a certificate using 'services.AddOpenIddict().AddServer().AddEncryptionCertificate()' or 'services.AddOpenIddict().AddServer().AddDevelopmentEncryptionCertificate()' or call 'services.AddOpenIddict().AddServer().AddEphemeralEncryptionKey()' to use an ephemeral key.

If the encryption certificate does need to be added, what is it used for when DP has been added?

**Comment by kevinchalet** [comment]
Hi,

> If the encryption certificate does need to be added, what is it used for when DP has been added?

In your case, it will be used for access tokens.

If you use DP for all token types, then it's currently not strictly required. In the future, it will be used to support things like authorization requests encryption, which is why I didn't add any "hack" to make it optional when DP is used (which is a bit difficult due to how things are layered).

**Comment by gustavdw** [comment]
Thanks!

Im assuming what you meant was this, correct me if Im wrong

SigningCertificate = Used for access tokens in my case since I specify PreferDefaultAccessTokenFormat, as well as id tokens since they are always JWT
EncryptionCertificate = Not used at the moment but iddict still requires it to be set
Dataprotection = Used for auth codes and refresh tokens in my case

**Comment by giometrix** [comment]
> Thanks!
> Im assuming what you meant was this, correct me if Im wrong
> SigningCertificate = Used for access tokens in my case since I specify PreferDefaultAccessTokenFormat, as well as id tokens since they are always JWT
EncryptionCertificate = Not used at the moment but iddict still requires it to be set
Dataprotection = Used for auth codes and refresh tokens in my case

I have the same question.  Can I get some clarity here?  Thank you!

**Comment by erwan-joly** [comment]
@kevinchalet does this means we can just have

```
     services
            .AddOpenIddict()
            .AddServer(options =>
            {
            ...
                options.AddEphemeralEncryptionKey()
                    .AddEphemeralSigningKey()
                    .UseDataProtection();
            })
            .AddValidation(options =>
            {
                options.UseAspNetCore();
                options.UseLocalServer();
                options.UseDataProtection();
            });
```

on a multi node production environment and the ephemeral keys are just going to be bypassed to used DataProtection instead ?

**Comment by elit0451** [comment]
@erwan-joly seems so, according to https://github.com/openiddict/openiddict-core/issues/1892#issuecomment-1737308506
