### ISSUE TITLE
How to use external logins with OpenIddict?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1232]
I need to implement external logins (eg. Google) within my OpenIddict server. First, the should the google client id and secret be those of my server or each application configured within my server should have a unique google client id and secret?

And when the user selects to sign in with google instead of local account when are the ExternalLogin and ExternalLoginCallback endpoints called? How is the user returned back to the application?

**Comment by sfsharapov** [comment]
I would recommend to start by reading [this post](https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/) in order to get to know with external login process.

**Comment by kevinchalet** [comment]
> First, the should the google client id and secret be those of my server or each application configured within my server should have a unique google client id and secret?

In the typical case, your server will act as a unique OAuth 2.0 client with the external providers, so you won't need to create an external OAuth 2.0 client per "OpenIddict client".

> And when the user selects to sign in with google instead of local account when are the ExternalLogin and ExternalLoginCallback endpoints called? How is the user returned back to the application?

Assuming you're going to use the Identity UI pages, this part will be handled for you transparently: the authorization endpoint will redirect your users to the external provider if they are not already logged in (thanks to `[Authorize]`), and the users will be redirected back to the authorization endpoint where they will be able to finalize the first OAuth 2.0/OpenID Connect dance. In this regard, it works exactly the same way as with password/form authentication.

**Comment by cryo75** [comment]
That makes sense. 

So when the user clicks on, for example, Google, a challenge with Google will be done through the ExternalLogin action. And the ExternalLoginCallback action is what Google redirects to after authentication.

Is this correct?

And what is the purpost of the ExternalLoginCallbackConfirmation?

**Comment by kevinchalet** [comment]
> Is this correct?

Absolutely.

> And what is the purpost of the ExternalLoginCallbackConfirmation?

This action is used to create the user profile in the Identity database and attach the external provider to it.
In the default Identity UI, this step is handled by a similar method in the `ExternalLogin` Razor page: https://github.com/dotnet/aspnetcore/blob/5b3ba86121c6afc27ac3851308e0f00b8c809600/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L171-L228.
