### ISSUE TITLE
Combine MongoDB store with InMemory Store.

### ISSUE THREAD

**Issue by SebastianStehle** [openiddict/openiddict-core#1242]
### Is your feature request related to a problem?
I would like to use an in-memory store because I only have one application and one scope and I do not see that much value of persisting it to MongoDB. It also makes migration harder, when the URL changes.

It is very straight forward to implement such a store, but it is hard to combine it with the MongoDB implementation. The reason is that the TokenStore uses BsonId for references to the application and scope.

### Describe the solution you'd like
Just change the properties to String.

**Comment by kevinchalet** [comment]
Using mixed stores is not really a supported scenario (and for in-memory scenarios, my recommendation is to use EF Core + the in-memory integration, or Sqlite with an in-memory database).

Changing the Id properties would be a breaking change so it's not an option at this point. That said, I don't think there's anything preventing you from using `ObjectId` in your custom implementation, is there?

**Comment by SebastianStehle** [comment]
It could be implemented as non-breaking change with a custom serializer or so, but I see that this is an issue.

I am about to migrate 2 services from identity server to openiddict-core. 

In the first case it is very simple because I only have one client and one scope and I created in-memory implementations where I create ObjectId-compliant Ids.

But in another use case the applications are dependent on other services.

This is the current implementation wit: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex/Areas/IdentityServer/Config/LazyClientStore.cs

So my hope was that I am able to port this store to openid-dict and when I want to support multiple databases like Mongo or EF it becomes very likely impossible.

Of course I can also write code where I hook into all the places where I create clients and apps and users in my system and then create applications in openid-dict but it is more complicated and because of the redirect URIs I also have to run a migration when a backup is restored into another machine.

**Comment by kevinchalet** [comment]
> It could be implemented as non-breaking change with a custom serializer or so, but I see that this is an issue.

I don't think a custom serializer would be required as `[BsonId, BsonRepresentation(BsonType.ObjectId)]` could likely be used. But custom serializer or not, changing the type of a CLR property is a binary and source breaking change and not something we can easily do in a non-major version.

> So my hope was that I am able to port this store to openid-dict and when I want to support multiple databases like Mongo or EF it becomes very likely impossible.

While it's still not completely clear why you can't have "`ObjectId`-compliant IDs" in your case (it's just the DB identifier, not a public identifier like the `client_id` that is a completely different property in OpenIddict), you can still create your own stores and your own models. It's a bit more code than just inheriting from the "official" MongoDB stores, but at least, you have full control over what happens.

**Comment by SebastianStehle** [comment]
> While it's still not completely clear why you can't have "ObjectId-compliant IDs"

What I meant is that I cannot create Ids that would work with Entity Framework and MongoDB. In EF I would have the problem that the IDs are references and with MongoDB that the ID need to be in a specific format. Combining different storages is kind of possible with MongoDB with a few hacks and very likely impossible with EF in general.

Right now I think that everything is possible, but it is just more work than with IdentityServer, so it is more a question of "developer UX".

**Comment by kevinchalet** [comment]
> What I meant is that I cannot create Ids that would work with Entity Framework and MongoDB. In EF I would have the problem that the IDs are references and with MongoDB that the ID need to be in a specific format. Combining different storages is kind of possible with MongoDB with a few hacks and very likely impossible with EF in general.

Oh, I thought you had your own in-memory stores. Yeah, with EF, it may be a bit more complicated.

> Right now I think that everything is possible, but it is just more work than with IdentityServer, so it is more a question of "developer UX".

Not denying that. OpenIddict's stores are heavily inspired by ASP.NET Core Identity (which is quite different from what you have in IdSrv) and neither OI nor Identity have been designed with the ability to mix different types of stores.
