### ISSUE TITLE
Custom flow - delegation

### ISSUE THREAD

**Issue by pfaustinopt** [openiddict/openiddict-core#1246]
I was wondering if it is possible to implement with `openiddict` a delegation grant type similar to the one implemented [here](https://identityserver4.readthedocs.io/en/latest/topics/extension_grants.html) with `Identity Server`.

```
var result = await _validator.ValidateAccessTokenAsync(userToken);
if (result.IsError)
{
    context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
    return;
}
``` 

Is there any equivalent method to `ValidateAccessTokenAsync` in `openiddict` in order to validate the token and access some of its properties?

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.

**Comment by pfaustinopt** [comment]
My bad. 

I had both StackOverflow and Github open and posted this question on the wrong website.
