### ISSUE TITLE
Absolute Uris in options seem not to work

### ISSUE THREAD

**Issue by Alex-111** [openiddict/openiddict-core#1255]
### Describe the bug

If I use absolute Uris in the options to specify my endpoints in the authorization server then the following check is always true, because HostString.FromUriComponent(address); always returns the host with the portnumber included. But the request is always without port number...

OpenIddictServerAspNetCoreHandlers:
line 126:       if (host != request.Host) <------ always true!!!

![image](https://user-images.githubusercontent.com/18511703/117112418-50a44600-ad89-11eb-8965-82f68b2e1c51.png)

my absolute uris from the options are always with port:
![image](https://user-images.githubusercontent.com/18511703/117112829-edff7a00-ad89-11eb-8ef1-e1a7a4a4d97a.png)

incoming request is always without port:
![image](https://user-images.githubusercontent.com/18511703/117113068-43d42200-ad8a-11eb-8d33-72c5881e36e1.png)

### Exceptions (if any)
error 500

### Further technical details
- latest version of all tools

**Comment by kevinchalet** [comment]
> HostString.FromUriComponent(address); always returns the host with the portnumber included. But the request is always without port number...

@Tratcher do you confirm this is the intended behavior? If so, should `HostString.Equals` be avoided in this case and replaced by a dual `HostString.Host` and `HostString.Port` check with the request port potentially inferred from the request scheme (80 for HTTP, 443 for HTTPS)?

**Comment by Tratcher** [comment]
HostString.Equals is a literal string.Equals, including the port if it was in the original input (or FromUriComponet?). HostString is separated from the uri so it can't infer a port for the equality check. If you need inference they yes you should check the host and port seperately.

**Comment by kevinchalet** [comment]
@Tratcher great, thanks! 👍🏻

**Comment by kevinchalet** [comment]
@Alex-111 could you please give the nightly builds a try to see if it fixed your issue?

**Comment by kevinchalet** [comment]
@Alex-111 let me know when you have a chance to test the nightly builds.

**Comment by Alex-111** [comment]
Thanks for the quick hotfix. Is it possible to test it with the nuget beta channel, or do I need to integrate complete sources into my solution, which will take some time for the complete setup?

**Comment by kevinchalet** [comment]
The nightly builds are hosted on MyGet (you can find the feed address in the README).

**Comment by Alex-111** [comment]
After a quick test, the latest version works as expected! Thanks!

Background why I need this, is that I have several domains. I want to have indivual login pages for each domain, so I defined several  dynamic URIs for all endpoints by implementing a domain dependant IConfigureNamedOptions \<OpenIddictServerOptions>

The question is, if it is ok to have the same issuer for each domain or should I also build the issuer dynamically per domain.

I would prefer a static issuer, because then the implementation is much easier on the ressource server side. Any drawbacks with this?

I tested both and both seem to work with the latest version. Before the fix, the issuer was always necessary to have URIs working correctly, because it was not possible to specify absolute URIs....and relative URIs were concatenated with the issuer Uri

**Comment by kevinchalet** [comment]
@Alex-111 thanks for giving it a try!

Regarding your scenario, I'd probably opt for a separate issuer per domain (specially if they are owned by different parties). You can opt for per-path options resolution like in https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login/49682427#49682427 or do it a-la-Orchard-Core with a DI container per tenant.
