### ISSUE TITLE
How to use OidcClient to logout?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1256]
Is it possible to use OidcClient to logout or do I need to explicitly call /Account/Logoff?

**Comment by kevinchalet** [comment]
There are many projects called OidClient, which one are you referring to?

**Comment by cryo75** [comment]
The one from the IdentityServer authors.

**Comment by kevinchalet** [comment]
Both the .NET flavor (https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/src/OidcClient/OidcClient.cs#L140) and the JS flavor (https://github.com/IdentityModel/oidc-client-js/blob/dev/src/UserManager.js#L433) should support logout.

**Comment by cryo75** [comment]
Was doing it the wrong way. I just call SignOut with the appropriate scheme and options and it works fine.

**Comment by kevinchalet** [comment]
Glad you sorted it out! 👍🏻
