### ISSUE TITLE
Need help to merge client and server in single project

### ISSUE THREAD

**Issue by devilsuraj** [openiddict/openiddict-core#126]
Hi i am trying to merge client and server in single project for learning exercise but getting error on invalid redirect_uri or postlogout_uri.
check my copy here https://github.com/devilsuraj/openiddict-core/tree/dev/samples/Mvc.Server

**Comment by xperiandri** [comment]
What is your intent of doing this?

**Comment by devilsuraj** [comment]
actually its my personal preference dont want to manage so many files from different projects .. anyways i am almost there , i am following this project https://github.com/capesean/openiddict-test but with angular2 . now i am stuck at a point please help if you can. 

the problem is that
when i have this inlcuded 

```
  app.UseOpenIddict(options =>
            {
               options.Options.UseJwtTokens();

```

angular2-jwt decodes my token but on server [authorize] tag sends me login url

and when i am not using `options.Options.UseJwtTokens();` my server will send me api data (i.e. authorization works) but jwt wont decode my token.
but in the project above it works with angular1 and normal JS
if you want to see the whole code let me know i will create a new repo
