### ISSUE TITLE
Allow replace JsonWebTokenHandler with custom Token handler.

### ISSUE THREAD

**Issue by kinosang** [openiddict/openiddict-core#1262]
### Is your feature request related to a problem?
I'm trying to use a custom self-encoded token for access_token instead of JWT, for e.g. CWT (CBOR Web Token) or others.

*JWT wastes bandwidth, CPU and other server resources.*

### Describe the solution you'd like
We may add `TokenFormatter` for access token, refresh token, id token, etc.
Also, reference tokens and DataProtection tokens can be unified with this changes.

*We may merge `IOpenIddictServerDataProtectionFormatter` and `IOpenIddictValidationDataProtectionFormatter`, and move it into `OpenIddict.Core` project.*

### Additional context
I'm working on it, will submit PR if this idea accepted.

**Comment by kevinchalet** [comment]
Having a single formatter/token handler per token type is not an option as multiple formats should be supported for a given token type (in 3.0, you can switch between JWTs and Data Protection: old and new tokens can still be validated, which was not true in 2.0).

That said, your scenario is already supported in the current bits, using the events model (you can take a look at the Data Protection integration for a concrete example)

**Comment by kinosang** [comment]
Oh, I got it.

I just found the default handler will skip the token generation and validation if there others handled them.

https://github.com/openiddict/openiddict-core/blob/1af24ef8884d92c493cd7fc265e38b2d3b7aaba1/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L403-L407

https://github.com/openiddict/openiddict-core/blob/1af24ef8884d92c493cd7fc265e38b2d3b7aaba1/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L2637-L2641

So I can use any token handler to generate and validate tokens by registering handlers with different ordering.

https://github.com/openiddict/openiddict-core/blob/1af24ef8884d92c493cd7fc265e38b2d3b7aaba1/src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs#L61-L66

https://github.com/openiddict/openiddict-core/blob/1af24ef8884d92c493cd7fc265e38b2d3b7aaba1/src/OpenIddict.Server.DataProtection/OpenIddictServerDataProtectionHandlers.cs#L179-L186

Thanks for your reply.
