### ISSUE TITLE
Owin EnableLogoutEndpointPassthrough exception always throwing

### ISSUE THREAD

**Issue by friit** [openiddict/openiddict-core#1263]
I'm using the Owin versions of Openiddict, when I try to setup Logout I always receive the exception 

To handle logout requests in a controller, create a custom controller action with the same route as the logout endpoint and enable the pass-through mode in the server ASP.NET Core or OWIN options using 'services.AddOpenIddict().AddServer().UseAspNetCore().EnableLogoutEndpointPassthrough()'.
Alternatively, create a class implementing 'IOpenIddictServerHandler&lt;HandleLogoutRequestContext&gt;' and register it using 'services.AddOpenIddict().AddServer().AddEventHandler()

In my startup I have 
   options.UseOwin()
                        .EnableAuthorizationEndpointPassthrough()
                        .EnableLogoutEndpointPassthrough()
                         ....

Enabled as well as the endpoint setup and method on the authorization controller. All other passthroughs are working correctly

I've pulled the source code in to debug and I can see from the OpeniddictServerHanlder.session.cs what is happening

Dispatch async is failing to find a handler and then falling through to where the exception is thrown in line 254.

Looking at what the OpeniddictServerDispatcher does I can see that it's failing to find any handlers that match the logout request context. 

I wasn't sure if I was doing the correct thing, so I took a look at the MVC samples which are in .netcore and followed them through with the debugger.
It looks to have no problem finding the correct handler and doing the pass through there, I can't see any extra configuration around logout setup there, and the two apis should work the same if i recall correctly from your blog post?

I can't seem to find the piece of code that adds the handlers to the options in either core or owin so I'm a little stuck where to go from here.

Any info you have on this would be appreciated. Am I missing some extra configuration option or is this an owin related bug?

**Comment by kevinchalet** [comment]
It's a legit bug, caused by this invalid event handler registration:

https://github.com/openiddict/openiddict-core/blob/1af24ef8884d92c493cd7fc265e38b2d3b7aaba1/src/OpenIddict.Server.Owin/OpenIddictServerOwinHandlers.Session.cs#L48

To work around it, you can remove this event handler using the server builder event APIs and re-register it with the right context generic type (i.e `HandleLogoutRequestContext` instead of `HandleUserinfoRequestContext`).

**Comment by ghost** [comment]
Great thank you. 

In case someone else has the same issue, this is what fixed it for me

options.AddEventHandler<OpenIddictServerEvents.HandleLogoutRequestContext>(b =>
                        b.UseSingletonHandler<IOpenIddictServerHandler<OpenIddictServerEvents.HandleLogoutRequestContext>>(
                            provider => new OpenIddictServerOwinHandlers.EnablePassthroughMode
                                <OpenIddictServerEvents.HandleLogoutRequestContext, 
                                    OpenIddictServerOwinHandlerFilters.RequireLogoutEndpointPassthroughEnabled>()));
