### ISSUE TITLE
redirect_uri is not valid for client application

### ISSUE THREAD

**Issue by Msrdevadiga** [openiddict/openiddict-core#1264]
Removing the question as it is not relevant here

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
