### ISSUE TITLE
RequireAuthenticatedUser prevents access to token endpoint

### ISSUE THREAD

**Issue by mlhDevelopment** [openiddict/openiddict-core#1270]
### Description
A common method [[1](https://stackoverflow.com/q/36432340/295686)] [[2](https://scottsauber.com/2020/01/20/globally-require-authenticated-users-by-default-using-fallback-policies-in-asp-net-core/)] to provide opt-out authentication is to set the option during AddControllers of the startup file. The pass through methods (`EnableTokenEndpointPassthrough`) are insufficient to allow anonymous access and a redemption attempt isn't fielded by OpenIdDict but is redirected to the login page with the ReturnUrl set to the token endpoint. The OpenID client isn't expecting this and throws an error when it receives the HTML page.

### To reproduce
See https://github.com/mlhDevelopment/openiddict-samples/commit/17e62eeacdcbe580bea99cb1f6af4e0752b500c2#diff-780c52f62da49a2b1c7849d7ee64c244ac6f9f91236025d75dbfe9012f95473fR24 for a demo but the offending code is:

    services.AddControllersWithViews(
        options =>
        {
            var policy = new Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .Build();
            options.Filters.Add(new Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter(policy));
        });

If that is added to `ConfigureServices` of startup (either before `services.AddOpenIddict` or after, I tested both and both fail) then the server will redirect back to the client after login, the client will make a backchannel request and that request errors out.

### Exceptions (if any)
From the client (e.g. Velusia.Client in the sample branch https://github.com/mlhDevelopment/openiddict-samples/tree/Velusia/RequireAuthenticatedUser):
`Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Failed to parse token response body as JSON. Status Code: 200. Content-Type: text/html; charset=utf-8`

### Further technical details
Running .net 5 via Visual Studio 2019 (v16.9.5) on Windows 10 (v2004)

**Comment by kevinchalet** [comment]
It's not an OpenIddict bug: you forgot to decorate your token endpoint action with `[AllowAnonymous]`.

Also, using `AuthorizeFilter` is no longer recommended: these things are now supposed to be configured using endpoint routing or by configuring a fallback policy in the authorization options.
