### ISSUE TITLE
Implement reference tokens but only for refresh tokens

### ISSUE THREAD

**Issue by Evengard** [openiddict/openiddict-core#1271]
### Is your feature request related to a problem?
The cookies storage only allows cookies to up to 4096 bytes. Refresh tokens are usually a lot bigger than that, including a lot of information in them (usually bigger than access tokens). But the application doesn't really needs the information from them, as it is just exchanging it for a new access token and is actually using access tokens instead. There is literally no need for them to be this huge.
Now, there is reference tokens... But when enabling it it also makes access tokens reference ones. Which means I need to make separate requests to the auth server to retrieve information about them. Which is not really practical.

### Describe the solution you'd like
Now, if we could allow to only refresh tokens to be reference tokens, making them small and economizing the storage, that would solve the problem.

### Additional context
This feature could be extended by allowing defining which tokens should be reference ones, and which not. There may be people who for some reason needs reference access tokens, but full size refresh tokens... (although I kinda doubt it)

**Comment by kevinchalet** [comment]
> Now, there is reference tokens... But when enabling it it also makes access tokens reference ones.

Not in 3.0: https://documentation.openiddict.com/configuration/token-storage.html

**Comment by Evengard** [comment]
Oh sorry, I was mislead by the old examples. Thanks.

**Comment by kevinchalet** [comment]
No problem 😄
