### ISSUE TITLE
return SignIn in not registered as token/auth endpoint

### ISSUE THREAD

**Issue by Moskvinr** [openiddict/openiddict-core#1272]
I need to implement a feature where admin can sign in as any other user in the system. How can I implement this using OpenIddict without info about user password? Or how can I turn off content type validation if I register one more endpoint in "SetTokenEndpointUris"?

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
