### ISSUE TITLE
Refresh token is still valid after exchange multiple times

### ISSUE THREAD

**Issue by quantranepiserver** [openiddict/openiddict-core#1274]
### Question

I'm implementing my authorization server with OpenIddict. Everything is working perfectly except the following issue:
- Get a new access token using Password flow with offline_access. A access token is returned along with a refresh token (let's say REF_TOKEN_1)
- Use REF_TOKEN_1 to exchange new access token (Call exchange endpoint the first time it works well).
- Then I check the database I see that the REF_TOKEN_1 is marked as `redeemed` (good until now)
- Instantly, I use REF_TOKEN_1 (which is already marked as `redeemed`) to exchange few more times, it still works (new access token and refresh token are returned). 
- After 1 or 2 minutes (since the first request to exchange token using REF_TOKEN_1), I got a HTTP 400 Bad request saying that `The specified refresh token has already been redeemed`. This message should be returned when I use the same refresh token for the second time and next subsequent requests.

Requests are not concurrent, the request is sent one by one.

Is this a intended behavior or a known issue or am I misunderstanding something ? How I can prevent this behavior ?

I already checked with the Mvc.Server project in the source code https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server and got the same problem even when I disable the entity cache.

Please help me to answer this question. Thanks a lot :)

**Comment by kevinchalet** [comment]
> Is this a intended behavior

It is: in 3.0, the rolling refresh token mechanism has a leeway (30 seconds by default) that allows you to "replay" already used refresh tokens during a short period of time to account for connection issues and concurrent requests. You can change the default value using `options.SetRefreshTokenReuseLeeway()`.

**Comment by quantranepiserver** [comment]
Thank you very much. You saved my day !

**Comment by kevinchalet** [comment]
Haha, you're welcome 😄 

If you use OpenIddict for a professional project, please consider encouraging your employer/client to sponsor it! 😃

**Comment by quantranepiserver** [comment]
Yes sure I'll do it :)

**Comment by hungpv1988** [comment]
@kevinchalet : really sorry for missing this. I am Quan's manager. I guess that there's one guy in our company contacting you for sponsor, but if not, then, please, reach out to me. I would bring this to leadership group.

Really thank for your support old days (and the days tomorrow as well). Fast, furious, and effective

**Comment by andrewlansdowne** [comment]
Hi, I came across this after noticing the same thing. I think leeway must be disabled if refresh tokens are being used in a SPA which is getting more common due to browser restrictions of 3rd party cookies etc. Otherwise only a single refresh token needs to be stolen and then the malicious party can reuse it indefinitely without detection. There is a good explaination of how disabling reuse avoids this here - https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation

**Comment by kevinchalet** [comment]
As always, there's necessarily a balance to find between security and usability and the reuse leeway - 30 seconds by default - is a reasonable compromise.

You're free to disable the leeway, but it may degrade the user experience as users will need to re-authenticate if the refresh token request didn't succeed the first time (as you can't replay it if there's no leeway).
