### ISSUE TITLE
Unable to integration test with web api

### ISSUE THREAD

**Issue by jingliancui** [openiddict/openiddict-core#1275]
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#mock-authentication

Please take a look at above link.
If I use below code,will throw exception said duplicate scheme.
var scheme=＂OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme＂;

services.AddAuthentication(scheme)
                    .AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(
                        scheme, options => {});

So I don't know how to add the mock handler to the scheme which was add by openiddict or remove the openiddict service when running the test.

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
