### ISSUE TITLE
Request is empty when using EventHandler

### ISSUE THREAD

**Issue by dotdiego** [openiddict/openiddict-core#1284]
I'm trying to use the **EventHandler** with **ExtractConfigurationRequestContext** to create multiple Discovery / Configuration files because of specific needs (I have one authorization endpoint for smart card / client credentials authentication so i can't access discovery on it) but the Request is always empty.

To achieve that purpose i'm using the ```options.AddEventHandler<OpenIddictServerEvents.ExtractConfigurationRequestContext>();``` method. However i'm having an issue as the Request object is not containing anything and i can't use it to dispatch the request to the right configuration.
I would like to get at least the RequestUri to determine if i'm on my main ConfigurationEndpoint or on the one that targets the Certificate Configuration (which in turn returns a different AuthorizationEndpoint/TokenEndpoint)

```csharp
options.AddEventHandler<OpenIddictServerEvents.ExtractConfigurationRequestContext>(builder => 
{
    builder.UseInlineHandler(context =>
    {
        if (string.IsNullOrEmpty(context.Request.RequestUri)
            Console.WriteLine("Not working");
        return default;
    })
});
```

It would be a great help to have this filled with the request.

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

> I would like to get at least the RequestUri to determine if i'm on my main ConfigurationEndpoint or on the one that targets the Certificate Configuration (which in turn returns a different AuthorizationEndpoint/TokenEndpoint)

It's not a bug: `RequestUri` is a parameter (typically used in authorization requests), not something that contains the "requested URI". To access the requested URI, retrieve the HTTP context and get the request path from there.

Thanks.
