### ISSUE TITLE
How do I get a custom field to be included in the application manager query? 

### ISSUE THREAD

**Issue by ntimmerman** [openiddict/openiddict-core#1285]
I am new to this so please forgive if this is an easy question. I need to join the Application entity to an existing database schema. We're thinking to link Application to our users table. How do I then get the Application Manager to query for my custom fields from the database? 

These are my customized entities. We're using integers instead of the default GUID's. 

          public class CustomApplication : OpenIddictEntityFrameworkCoreApplication<int, CustomAuthorization, CustomToken>
          { 
                 public User User { get; set; } 
          }
          public class CustomAuthorization : OpenIddictEntityFrameworkCoreAuthorization<int, CustomApplication, CustomToken> { }
          public class CustomScope : OpenIddictEntityFrameworkCoreScope<int> { }
          public class CustomToken : OpenIddictEntityFrameworkCoreToken<int, CustomApplication, CustomAuthorization> { }`

And then in a controller action, can the application manager pull in my UserKey? 

            var clientId = User.Claims.Where(x => x.Type == "client_id").SingleOrDefault();
            var application = await _applicationManager.FindByClientIdAsync(clientId.Value);
            var userKey = ((CustomApplication)application).User.UserKey;

            var persistedFacilities = _dbContext.Facilities.Where(x => x.UserKey == userKey).ToList();

**Comment by kevinchalet** [comment]
Hi,

I'm not sure how your scenario works (it's not super clear to me why a client would be linked to a user), but querying based on an extended property should definitely be possible. If you use the EF Core, EF 6 or MongoDB stores, you can call the `GetAsync()` overload (or `ListAsync()` if you want to get multiple items) that takes a delegate. E.g:

```csharp
var application = await _applicationManager.GetAsync(applications => applications.Where(application => application.User.Id == "abc"));
```

Or if you prefer the query syntax:

```csharp
var application = await _applicationManager.GetAsync(applications =>
    from application in applications
    where application.User.Id == "abc"
    select application);
```

For that, you'll want to resolve the strongly typed version of the application manager (i.e `OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>` instead of `IOpenIddictApplicationManager`).

**Comment by ntimmerman** [comment]
So I would need to specify my type, right? But the where predicate doesn't infer its type properly. The compiler tells me User is not a property of type object. 

            var application = await _applicationManager.GetAsync<CustomApplication>(applications => applications.Where(application => application.User.UserKey == clientId));

**Comment by ntimmerman** [comment]
I switched to the strongly typed application manager and the User is still null. I'm guessing it has to do with the fact that my entity type is in this case a view with a key instead of a table. 

```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
            base.OnModelCreating(builder);

            builder.Entity<User>(u =>
            {
                u.HasKey(u => u.UserKey);
                u.ToView("vwAPIUsers");
            });
}
```

**Comment by kevinchalet** [comment]
> I switched to the strongly typed application manager and the User is still null.

Do you mean the `User` property of the returned `application` object is null? Doesn't adding `.Include(application => application.User)` help (or you can turn on lazy loading)?
