### ISSUE TITLE
Using a custom TokenStore and extending TokenStoreResolver to deliver it to TokenManager

### ISSUE THREAD

**Issue by DuncancMartin** [openiddict/openiddict-core#1287]
Hi Kevin
Thanks to your assistance, I have an extended Token object containing a new field. To insert data into this field, I believe I need to over-ride the PopulateAsync method in the TokenManager, and add the ability to set this value in the TokenStore. 
I have a working ExtendedTokenManager, and I am able to use it to set the Properties data in the Token using the built in TokenStore, but I am having issues creating an ExtendedTokenStore inside my ExtendedTokenStoreResolver.  I've been attempting to replicate the source here:
https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFrameworkCore/Resolvers/OpenIddictEntityFrameworkCoreTokenStoreResolver.cs
and implement this interface so that I can use the extended TokenStore
```
    public interface IExtendedOpenIddictTokenStoreResolver : IOpenIddictTokenStoreResolver
    {
        IExtendedOpenIddictTokenStore<TToken> GetExtended<TToken>() where TToken : class;
    }
```
but no matter what I do, it makes the OpenIddict generic type, not my extended version. I suspect there may be some config somewhere in startup that would ensure it returns my ExtendedTokenStore, but I can't find it. Is there an example that shows me how to do this? 
Thanks again for any pointers you can offer.
Duncan

**Comment by kevinchalet** [comment]
Hey,

FYI the sponsor tier you selected is limited to 2 support tickets per year. For more recurrent help, please consider choosing a higher tier.

Thanks!

**Comment by DuncancMartin** [comment]
Hi Kevin
I updated my sponsorship to the next tier.
If there are no examples of this sort of thing, then I'll try to summarise the problem and my code tomorrow.
Thanks
Duncan

**Comment by kevinchalet** [comment]
Thanks!

So: creating your own resolver interface/implementation shouldn't be necessary at all: the default one can be used even with subclassed stores (which is exactly the approach OrchardCore uses). Instead, you can use casts in your custom manager to expose the methods defined in your own subclassed stores. Here's a concrete example from OrchardCore:

```csharp
public virtual async ValueTask<ImmutableArray<string>> GetRolesAsync(
    TApplication application, CancellationToken cancellationToken = default)
{
    if (application == null)
    {
        throw new ArgumentNullException(nameof(application));
    }

    if (Store is IOpenIdApplicationStore<TApplication> store)
    {
        return await store.GetRolesAsync(application, cancellationToken);
    }
    else
    {
        var properties = await Store.GetPropertiesAsync(application, cancellationToken);
        if (properties.TryGetValue(OpenIdConstants.Properties.Roles, out JsonElement value))
        {
            var builder = ImmutableArray.CreateBuilder<string>();

            foreach (var item in value.EnumerateArray())
            {
                builder.Add(item.GetString());
            }

            return builder.ToImmutable();
        }

        return ImmutableArray.Create<string>();
    }
}
```

https://github.com/OrchardCMS/OrchardCore/blob/e2a1b00142fa7703de35ed57ab504cf0ff658952/src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs#L74-L103

That method - like the rest of the manager - works with both customized Orchard stores, that implement the `IOpenIdApplicationStore` interface - and with the official OpenIddict stores that are not Orchard-aware (in that case, it uses an untyped property to store the roles).

Of course, you don't have to do that: if you only want to support your derived stores in your manager, you can instead tweak the `Store` property (or use another one) to expose your derived interface type:

```csharp
protected new IExtendedOpenIddictTokenStore<TToken> Store => (IExtendedOpenIddictTokenStore<TToken>) base.Store;
```

Let me know if it's not clear 😄
