### ISSUE TITLE
Consider backporting the log level changes to OpenIddict 3.x

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1290]
In the dev branch, the log level of most errors was lowered to avoid overlogging: https://github.com/openiddict/openiddict-core/issues/1205.

We should consider backporting these changes to OpenIddict 3.x, most likely as part of a 3.1 release.

**Comment by kevinchalet** [comment]
FYI @deanmarcussen the log level change was backported to 3.x, in case you'd be interested for Orchard 😃

**Comment by deanmarcussen** [comment]
Ideal, defintely, thanks @kevinchalet
