### ISSUE TITLE
Missing token error

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1295]
I have a server app that validates tokens from clients. I see following logs constantly:

2021-08-05 08:18:09.666 +02:00 [INF] The response was successfully returned as a challenge response: {
  "error": "missing_token",
  "error_description": "The security token is missing.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2000"
}.

What does it actually mean and how do I solve it?

**Comment by kevinchalet** [comment]
This error means ASP.NET asked OpenIddict to authenticate a request for which no access token was provided (in the headers, in the query string or in the form body). This may indicate that some of your callers are trying to call your API endpoints without being authenticated (and in this case, all they'll get is a 401 response).

**Comment by kevinchalet** [comment]
Closing for now. Please let me know if you need additional details 😃
