### ISSUE TITLE
State generated too long by OpenId connect for Azure AD  external login

### ISSUE THREAD

**Issue by makilas** [openiddict/openiddict-core#1301]
I have implemented a login flow using OpenID, that redirects more than one server (**My Application-> Identity Server-> Azure AD**) to authenticate users. **My Application** and **Identity server** both are using OpenId for login.
In My login flow, the user will be redirected from **My Application** to the **Identity Server** with redirect URI, then **Identity Server** redirects to **Azure AD**. In this request, the `state `property is so large, so Azure AD can't accept and shows the request query too long.

I have to reduce the length of the `state `property on the Azure AD login request. Can you suggest how to customize the state generation in my application with OpenId. Is this possible to generate and validate the state manually?

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
