### ISSUE TITLE
how to deal with multiple domain on a single application

### ISSUE THREAD

**Issue by nako-ruru** [openiddict/openiddict-core#1311]
I am looking for an appropriate solution for multiple domain on a single legacy asp.net core application.

one of solutions i thought is that adding sso support for one of domains, and then all other domains check whether users have logged in on that domain

i followed steps of sample Velusia, i succeeded in integrating openiddict. however, there should be serveral extra tasks to do.
1. skip authorization page
2. automatically add external provider for openiddict

i didn't find any sample for the two tasks metioned above, can someone give me some advice

or are there any other better solutions for my issue

**Comment by kinosang** [comment]
> 1. skip authorization page

set your application as implicit

What do you means by "2. automatically add external provider for openiddict"? do you have a look at docs.microsoft.com ?

**Comment by nako-ruru** [comment]
> > 1. skip authorization page
> 
> set your application as implicit
> 
> What do you means by "2. automatically add external provider for openiddict"? do you have a look at docs.microsoft.com ?

thanks for your reply, 

as for "automatically add external provider for openiddict", i mean that i have to add external provider key for every user, otherwise, the default identity pages will ask users to register after users do external login. i'm not sure what is the best way to solve this

**Comment by kinosang** [comment]
That's about the Asp.Net Identity, do your own bussiness logic after scaffolding.

**Comment by nako-ruru** [comment]
Oh, I see. I'll have a look at that. Thank you very much

**Comment by nako-ruru** [comment]
> > 1. skip authorization page
> 
> set your application as implicit
>
as for "implicit", i tried implicit-flow the day before yesterday, i remembered openiddict show me a message "i have to login directly", i forgot the exact original words.

i'm not sure whether openiddict show me the message by design or i'm missing something

**Comment by kinosang** [comment]
RTFC

https://github.com/openiddict/openiddict-core/blob/49dc526476241b5dc31f204ca5c3508c99ed4242/samples/Mvc.Server/Controllers/AuthorizationController.cs#L168-L199

or

https://github.com/openiddict/openiddict-samples/blob/0a8c81b7f9aa1b3f0e1c133a37e8d56da73cb4c9/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs#L141-L172

**Comment by kevinchalet** [comment]
Closing as I believe @kinosang answered your question. Also, it's worth noting GitHub questions are reserved to sponsors, as indicated when creating a ticket:

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)
