### ISSUE TITLE
How to manual handle OpeniddictApplication, OpeniddictScope in database context?

### ISSUE THREAD

**Issue by phungxuanvuong** [openiddict/openiddict-core#1323]
I created a CustomApplication class and inheriting it with the OpenIddictEntityFrameworkCoreApplication class. Then I put this class in the Database Context:

public DbSet<CustomApplication> OpenIdApplicationExtension { get; set; }
When I use Database Context to insert records, the field ClientSecret is not encrypted, the format of the Permissions field is not the same as when creating an Application with OpenIddictApplicationDescriptor.

I need to be able to insert and get data from tables such as OpenIddictScopes, OpenIddictScopes. How can I do that?

Sorry, I also posted on Stackoverflow.

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.

**Comment by phungxuanvuong** [comment]
> Hi,
> 
> ![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)
> 
> As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.
> 
> Thanks.

I did

**Comment by phungxuanvuong** [comment]
https://github.com/openiddict/openiddict-core/actions/runs/1224528808

**Comment by kevinchalet** [comment]
https://gitter.im/openiddict/openiddict-core?at=613e026ed9a141754de81c71
