### ISSUE TITLE
How I can register with google authorize  account ? 

### ISSUE THREAD

**Issue by Hu238n** [openiddict/openiddict-core#1326]
when I register in my account to Openidict project I get this error 

 An unhandled exception occurred while processing the request.
InvalidOperationException: A sign-in response cannot be returned from this endpoint.
OpenIddict.Server.OpenIddictServerHandlers+ValidateSignInDemand.HandleAsync(ProcessSignInContext context) in OpenIddictServerHandlers.cs, line 1139

how I can resolve it?

**Comment by kinosang** [comment]
RTFM

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-5.0

That's not issue about openiddict. you'd better read some asp.net core documents before using it.

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
