### ISSUE TITLE
Claim scope names not matching

### ISSUE THREAD

**Issue by ianleeder** [openiddict/openiddict-core#1328]
### Describe the bug
If this is user error (as I suspect) I apologise in advance.  But for the life of me, I can't get OpenIddict to attach scopes to tokens, and have them authorised.

I have set up an auth server, and an API server.  These are communicating fine via introspection (based on Zirku sample code).  I can restrict API endpoints by roles, and everything so far works fine.  I am using the `password` grant type (legacy code I have to integrate with).

I am trying to set up a scope for one particular endpoint.  I have registered the scope in the auth server `startup.cs`:

    options.RegisterScopes("user.create");

When creating my application, I have allowed the scope:

    Permissions =
    {
        Permissions.Endpoints.Introspection,
        Permissions.Endpoints.Token,
        Permissions.GrantTypes.Password,
        Permissions.GrantTypes.RefreshToken,
        Permissions.Prefixes.Scope + "user.create",
    },

I have created the scope:

    var manager = scope.ServiceProvider.GetRequiredService<IOpenIddictScopeManager>();

    if (await manager.FindByNameAsync("user.create") == null)
    {
        var descriptor = new OpenIddictScopeDescriptor
        {
            Name = "user.create",
            Resources =
            {
                "api_server"
            }
        };
        await manager.CreateAsync(descriptor);
    }
    }

When creating my token, I have hard-coded the scope:

    principal.SetScopes(Scopes.OfflineAccess, "user.create");

I can generate a token, and when I introspect it, it includes the scope I want:

    {
        "active": true,
        "iss": "http://auth.myproject.local/",
        "username": "my_username",
        "sub": "def66e3b-35ee-4a4d-99b8-e8bef29a1fc1",
        "scope": "offline_access user.create",
        "token_type": "Bearer",
        "token_usage": "access_token",
        "client_id": "api_server",
        "iat": 1631797123,
        "nbf": 1631797123,
        "exp": 1631800723,
        "aud": "api_server",
        "name": "my_username",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "my_email_address",
        "role": "Superuser"
    }

*BUT* when I try to authenticate based on this scope (either `[RequiredScope("user.create")]` or `HttpContext.VerifyUserHasAnyAcceptedScope("user.create")`, I get the following exception:

	2021-09-16 23:11:49.7300|Error|An unhandled exception has occurred while executing the request. |EventId_Id=1, EventId_Name=UnhandledException, EventId=UnhandledException System.UnauthorizedAccessException: IDW10203: The 'scope' or 'scp' claim does not contain scopes 'user.create' or was not found. 
	   at Microsoft.Identity.Web.Resource.ScopesRequiredHttpContextExtensions.VerifyUserHasAnyAcceptedScope(HttpContext context, String[] acceptedScopes)

I tracked down the extension method [`VerifyUserHasAnyAcceptedScope`](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs#L36), and as far as I can see it's looking for claims with the following keywords:

1. `public const string Scp = "scp";`
2. `public const string Scope = "http://schemas.microsoft.com/identity/claims/scope";`

My `User.Claims` contains:

	username: my_username
	sub: def66e3b-35ee-4a4d-99b8-e8bef29a1fc1
	scope: offline_access user.create
	client_id: api_server
	iat: 1631797123
	exp: 1631800723
	aud: api_server
	name: my_username
	http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress: my_email
	role: Superuser
	oi_tkn_typ: access_token
	oi_crt_dt: Thu, 16 Sep 2021 12:58:43 GMT
	oi_exp_dt: Thu, 16 Sep 2021 13:58:43 GMT
	oi_aud: api_server
	oi_prst: api_server
	oi_scp: offline_access
	oi_scp: user.create

So my question is.... why are scopes stored as `scope` and `oi_scp` when the Identity verification code looks for `scp` or `http://schemas.microsoft.com/identity/claims/scope`?

**Comment by kinosang** [comment]
`scp` and `http://schemas.microsoft.com/identity/claims/scope` are not included in JWT registry.

see https://www.iana.org/assignments/jwt/jwt.xhtml

Use custom authorize policy to do so.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies

e.g. 

```csharp
services.AddAuthorization(options =>
          options.AddPolicy("user.create",
          policy => policy.RequireClaim("scope", "user.create")));
```

**Comment by ianleeder** [comment]
Thanks @kinosang, I got your solution to work.  But it feels like a hack.  From my perspective:

- I already have scopes defined and applied to tokens, scope-based restrictions exist (`[RequiredScope("user.create")]`), I don't understand why I can't use them.
- I have to create a policy that detects scopes, and then restrict based on the policy, instead of scopes directly.  [That just sounds like scope-based restrictions with extra steps](https://i.redd.it/300sbgrfr2741.png).
- The policy needs to be defined on every resource server, not on the central auth server.
- The command `policy.RequireClaim("scope", "user.create")));` matches the complete scope string, not `.Contains`.  So if my `scope` claim contains multiple scopes (eg `"offline_access user.create"`), the policy fails.  I either need to update the policy to match the entire string (not robust) or write a more complicated [policy handler](https://stackoverflow.com/questions/54852094/asp-net-core-requireclaim-scope-with-multiple-scopes).

This really feels like the wrong solution to my problem.

Also I would like to request/suggest that an example using scopes is added to the Samples code.

**Comment by kinosang** [comment]
The asp.net core JWT/OpenIdConnect handler can handle `scope` claims correctly, read the https://github.com/openiddict/openiddict-samples codes for how to use scopes.

If you'd like the microsoft-identity-web extensions, please consider submit request to the azure ad Wilson team for standard JWT `scope` claim support.

**Comment by ianleeder** [comment]
I'm sorry @kinosang, I don't understand.  Are you saying there are two different ways of doing scopes, and I simply can't use the `RequiredScope` attribute with OpenIddict scopes?

I have looked through the samples a number of times.  The word "scope" doesn't appear on the samples README page, and as far as I can see, none of the examples restrict resource access by scope.  Can you point me at a specific example?

**Comment by kinosang** [comment]
you should read more about the asp.net security. claims can have same name and different values.

RTFM & RTFC

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-5.0

https://github.com/openiddict/openiddict-core/blob/44fe717204be6d94fa114e64e79970b09564a4f4/src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs#L1372-L1385

or just print all claims after signed in to see how JWT scopes stored in asp.net claims.

just have a try with `RequireClaim` policy when you have multi scopes, you'll find it works.

asp.net core JWT authentication handlers will split JWT scope into multi claims with same name (`scope`) and different values. just use `RequireClaim` will match the name and specified value.

**Comment by ianleeder** [comment]
Thanks for the persistence @kinosang.  I've got it working well enough.  And you're right, I'm in over my head and have been reading as much as I can, but with no background in authorisation, it's a steep learning curve.

I'm happy to take your word for it that this is intended behaviour, even if I don't fully understand it.

Lastly though, 

> just have a try with RequireClaim policy when you have multi scopes, you'll find it works.

For the record, my claims contain:

    scope: offline_access user.create
    oi_scp: offline_access
    oi_scp: user.create

`scope` is not split into multiples.  This does not work:

    policy.RequireClaim("scope", "user.create");

This does (but too rigid):

    policy.RequireClaim("scope", "offline_access user.create");

This does (but I'm not sure if it's good practice to inspect third-party scopes):

    policy.RequireClaim("oi_scp", "user.create");

But this is the [best solution](https://stackoverflow.com/a/57577319/5329728) I've seen:

    options.AddPolicy("TestPolicy2", policy =>
    {
        policy.RequireAssertion(context =>
        {
            var claim = context.User.FindFirst("scope");
            if (claim == null)
            {
                return false;
            }

            return claim.Value.Split(' ')
                .Any(s => string.Equals(s, "user.create", StringComparison.InvariantCultureIgnoreCase));
        });
    });

**Comment by kinosang** [comment]
If I remember correctly, `AddAuthentication(...).AddJwtBearer(...)`, `AddAuthentication(...).Add OpenIdConnect(...)`, and `Add OpenIddict(...).AddValidation(...)` can deal with the `scope` claims, are you using one of them?

**Comment by ianleeder** [comment]
@kinosang I have `services.AddOpenIddict().AddValidation()` and then I have `services.AddAuthentication();`.  Is the order tripping me up?  I'll try rearranging them.

Update: Rearranging did not make a difference.

**Comment by ianleeder** [comment]
And to reiterate.  My issue isn't with the `scope` claim, I have that.  My issue is that the `RequiredScope` attribute spits out this error message:

> IDW10203: The 'scope' or 'scp' claim does not contain scopes 'user.admin' or was not found. 

But only checks for the following claims:

- `scp`
- `http://schemas.microsoft.com/identity/claims/scope`

It does ***not*** check for the `scope` claim, as far as I can tell.   
At least, the [VerifyUserHasAnyAcceptedScope](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Resource/ScopesRequiredHttpContextExtensions.cs#L36) extension method does not.  Which is why I was asking whether OpenIddict is setting the correct claim values.  The mismatch is very confusing.

**Comment by kevinchalet** [comment]
OpenIddict 3.0 implements the JWT access token specification, that requires that scopes be formatted a single space-separated claim: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-access-token-jwt-13.

The method you mentioned is not part of OpenIddict and doesn't comply with that spec.

@ianleeder as mentioned when you opened the ticket, only sponsors can open questions on GitHub. Please consider sponsoring the project.

**Comment by ianleeder** [comment]
Ok thanks Kévin.  So it *is* a bug, just on the MS side not yours.  This is why I lodged it as a bug, not a question. However I appreciate the code and the support, so I've just done a donation.  Thanks.

**Comment by kinosang** [comment]
@ianleeder I don't think it's a bug. It seems is as-design, microsoft-identity-web `RequiredScope` method does not follow the OpenID Connect standard.

**Comment by ianleeder** [comment]
Again, I would like to suggest that an example using scopes is added to the Samples code.  I think it would be beneficial.

Either use RequiredScope if you can work out how, or write some documentation why it can't be done, and show how to work around using Policies.  As it is, the code shows how to attach scopes to tokens, but doesn't explain that you can't use them with Identity authorisation.

All of this authorisation stuff has been a steep enough learning curve, but manageable.  This was a nasty surprise that has cost me many unexpected days.

**Comment by kinosang** [comment]
`RequiredScope` is not a part of asp.net core, openid connect authentication middleware, jwt bearer authentication middleware, nor openiddict. It is belongs to Azure (the Microsoft Identity Platform). There's no any relationship between it and OpenID Connect. Do Not Presuppose It Will Work With Any OpenID Connect Provider.

Just use policy-based solution or create a OpenID Connect complicated `RequiredScope` filter (attribute).
