### ISSUE TITLE
Separate setting/handling base uri and issuer

### ISSUE THREAD

**Issue by balazsmeszegeto** [openiddict/openiddict-core#1329]
### Issue
I have an OpenIddict Server running on a host and configured to listen both on public address and the internal (private) network of the host. Other application servers on the host are also accessible outside, but servers are using the internal network communicating each other. For example a server should use internal network when fetching jwk and/or requesting tokens through TokenEndpoint.

I want to keep the issuer ("iss") inside tokens the same regardless which network interface was it requested from. I can achieve this by setting `OpenIddictServerOptions.Issuer`. However, Discovery/Configuration endpoint will also use this as a base uri when returning JSON for /.well-known/openid-configuration

This will then mean that servers reading the configuration, even though they requested from the internal network, the public endpoint addresses will be shown

To be fair, head comment of the setting is somewhat indicating this behaviour:
> optional base address used to uniquely identify the authorization server.

### Suggested solution
My suggestion would be separate handling of base uri and issuer. So it is possible to setting issuer, while keeping the base uri for Configuration endpoint "default" (as in infer base uri from request host).

This might be easily achieved by adding a new setting: `OpenIddictServerOptions.BaseUri` or similar. Similarly, if not set, BaseUri would be inferred from request

**Comment by balazsmeszegeto** [comment]
Remark: my current workaround was to replace builtin handler `Discovery.AttachEndpoints` with my own implementation, which infers base uri from host

**Comment by kevinchalet** [comment]
This really sounds like an advanced scenario (it's way more frequent to see it implemented at the DNS/IP routing level so that all "public" addresses remain the same). As such, having to use the events model doesn't seem to be unreasonable.

That said, if there's a strong demand, I'm fine reconsidering it.

**Comment by balazsmeszegeto** [comment]
I don't have broad overview and cannot estimate how advanced scenario is this, the reason I'd think might be demand, since this is a feature of Identity Server (I've just finished migration to OpenIdDict)

**Comment by kevinchalet** [comment]
> since this is a feature of Identity Server (I've just finished migration to OpenIdDict)

As mentioned in https://kevinchalet.com/2020/10/03/using-the-orchardcore-openid-management-feature-with-an-existing-openiddict-deployment/, OpenIddict uses a very different approach and is not meant to be a free clone of IdentityServer (which is, I guess, the reason you decided to migrate? 😄). While IdentityServer offers many first-class options, OpenIddict encourages you to use its powerful events model as soon as you need something that is not provided OOTB: what you described as a workaround is the right way to do things in OI.

**Comment by balazsmeszegeto** [comment]
Yes, I'm aware of that and I actually prefer OI-way (for example it is much more convenient and much rather write whole authorization/token endpoint, than having to add many extensions, hooks and whatnot), so I'm happy with the migration.

Regarding "free clone" from the article, after having used Identity for 7 years, I see that OI has way more to offer (features) , is more robust and flexible. 

But I still think my suggestion would be useful and will easily fit in the OI model. The argument regarding Identity was just for the demand.

If so, I'd happy to contribute 😊

**Comment by kevinchalet** [comment]
> But I still think my suggestion would be useful and will easily fit in the OI model. The argument regarding Identity was just for the demand.

I'll leave the thread open to see if there's a strong interest that would justify implementing this feature directly in OpenIddict instead of relying on the events model.

**Comment by aldari** [comment]
Hello, how proper is to use ValidIssuers for a such case ? This settings allow to keep public issuer uri unchanged and pass internal address calls to identity from internal api services. From my point it works.

```
services.AddOpenIddict()
    ....
    .AddServer(options =>
    {
        options.Configure(options =>
        {
            options.TokenValidationParameters.ValidIssuers = new List<string>
            {
                // internal idp address
                "http://localhost:44395/",
            };
        });
```
