### ISSUE TITLE
Consider using last available version of AspNet.Security.OpenIdConnect.Server in dev branch.

### ISSUE THREAD

**Issue by ORuban** [openiddict/openiddict-core#133]
Current dev branch contains 1.0.0-beta5-final version of AspNet.Security.OpenIdConnect.Server. It could be more useful to have reference to last available version of package. 

`"AspNet.Security.OpenIdConnect.Server": "1.0.0-*",`
instead of
`"AspNet.Security.OpenIdConnect.Server": "1.0.0-beta5-final",`

There is the same approach in ASP.NET Core projects - for specific versions the release branch with commit labels is used.

**Comment by kevinchalet** [comment]
> There is the same approach in ASP.NET Core projects - for specific versions the release branch with commit labels is used.

OpenIddict is still in alpha and there's no official release yet. We will move to ASOS beta6 and ASP.NET Core RTM when they are released, but in the meantime, we'll keep using ASOS beta5-final and RC2.

**Comment by ilmax** [comment]
Move to ASP.NET Core RTM and ASOS beta 6 was adressed by #147.

Closing.
