### ISSUE TITLE
Extract AccessToken from Cookie / Allow custom access token extractors

### ISSUE THREAD

**Issue by ccvca** [openiddict/openiddict-core#1331]
### Is your feature request related to a problem?
In my Single Page App (react) images require authentication. But as they are  included by `<image src="" />` there is no way to pass any Authentication header. Furthermore passing the Tokens to all components doesn't look right. Stroring the token in a (http-only) Cookie would solve this issue, as the browser would automatically send the token in all requests and authentication needs to be done only in one place in the SPA.

At the moment, the three possible sources for extracting the AccessToken (AuthorizationHeader, BodyForm, QueryString) which are added her:
https://github.com/openiddict/openiddict-core/blob/511e52eb061d380510c72c8b88907d070c71f615/src/OpenIddict.Validation.AspNetCore/OpenIddictValidationAspNetCoreHandlers.cs#L46-L48

There is no way of adding a (custom ) extractor for Cookies.

### Describe the solution you'd like
I see two possible solutions:

1. Add `ExtractAccessTokenFromCookie`
2. Offer an API to add a custom extractor e.g. like described [here](https://spin.atomicobject.com/2020/07/25/net-core-jwt-cookie-authentication/) for `AddJwtBearer`:
```CS
options.Events = new JwtBearerEvents
{
  OnMessageReceived = context =>
  {
    context.Token = context.Request.Cookies["your-cookie"];
    return Task.CompletedTask;
  },
};
```

**Comment by kevinchalet** [comment]
The RFC6750 specification discourages using cookies to convey access tokens due to the CSRF risk:

> Don't store bearer tokens in cookies:  Implementations MUST NOT store bearer tokens within cookies that can be sent in the clear (which is the default transmission mode for cookies).  Implementations that do store bearer tokens in cookies MUST take precautions against cross-site request forgery.

https://datatracker.ietf.org/doc/html/rfc6750#section-5.3

While absolutely not recommended, you can implement this scenario yourself using the events model.

**Comment by a-a-k** [comment]
> While absolutely not recommended, you can implement this scenario yourself using the events model.

Could you share an example, please? Is this possible for encrypted cookie, anyway?

@ccvca could you comment in a couple words, how did you solve that?
