### ISSUE TITLE
Allow logs to contain obfuscated/hashes values rather than redacted values

### ISSUE THREAD

**Issue by MatthewSteeples** [openiddict/openiddict-core#1332]
### Is your feature request related to a problem?
We're currently trying to debug an issue where we're unexpectedly getting `invalid_grant` exceptions. Looking at the logs we get the plain text `client_id`, `grant_type` and `redirect_url`, and for `client_secret` and `code` we just get the text `[redacted]`

### Describe the solution you'd like
I understand why these values are not output in the logs, but it may be useful to have a configurable option to output hash of the values in Base64 format so that _if you already know the values_ you can compare that what you expect to be passed in was actually passed in

### Additional context
If this sounds like an acceptable idea then we're happy to contribute the code towards getting it working. We'd suggest leaving the default as is and making this behaviour "opt-in"

**Comment by kevinchalet** [comment]
Actual tokens can be logged if you lower the log level to `Trace`. For the other "protected" parameters, I don't think it would be a good idea to log them even with an opt-in switch: things like `password` (that convey the user password in the password grant type) are ultra sensitive and should never be logged.

That said, you can implement custom logging using the events model, if that's really what you want.

Closing.

**Comment by MatthewSteeples** [comment]
Thanks for the response. We came up with a way of diagnosing our issue without resorting to sniffing the data but we'll bear the Trace level in mind should we encounter it again
