### ISSUE TITLE
Return custom message from policy based authorization handler

### ISSUE THREAD

**Issue by levitatejay** [openiddict/openiddict-core#134]
I've written some requirements and handlers to handle authorization for my controller actions. In my handler if the requirement fails I write a custom response with a message. Like so:

```
//if we don't have permission
var message = new { Message = "You don't have permission" };
mvcContext.Result = new JsonErrorResult(403, message);
```

It seems like all the middleware I can find is overwriting this response and only returning a 403 status code with no body.

I've tried:
app.UseIdentity()
app.UseOAuthValidation()
app.UseJwtBearerAuthentication()

Am I going about this wrong? I don't want to write lots of authorization logic in my controllers... I want to be able to add the relevant policy attribute to a controller action and my clients can receive a message about why they got a 403 response.

**Comment by kevinchalet** [comment]
Moved to https://github.com/aspnet/Security/issues/872.
