### ISSUE TITLE
Dapper Stores

### ISSUE THREAD

**Issue by Modest-as** [openiddict/openiddict-core#1344]
### Is your feature request related to a problem?

Not a problem.

### Additional context

Hey, I've wanted to ask if I've created a PR to add dapper stores to the project would you be willing to marge it upstream, or it is not a functionality that is generally requested?

**Comment by kevinchalet** [comment]
Thanks for your offer!

Sadly, my answer will be the same [as for the Marten stores](https://github.com/openiddict/openiddict-core/issues/1343#issuecomment-946128992): the demand is too low to justify maintaining such things in the core stack.

That said, I plan to create a dedicated thread new week to discuss OpenIddict's future - the sponsoring model simply doesn't work - and it's typically the kind of things that could be available as part of a pro/paid offer. Is that something you could be interested in?

**Comment by Modest-as** [comment]
Perfectly understandable, with more features it gets more difficult to maintain the project. I could OSS the dapper stores from my repo. Just wanted to offer to pull this upstream in case this was highly requested. 

I am afraid I can not comment on the sponsorship model. I am not using openiddict in any commercial setting. If you decide to commercialize that is totally reasonable, I just feel like with the recent identity server licensing changes they community will look for a good alternative that they can contribute to.

**Comment by iAlexanderMoon** [comment]
What would your feelings be on an openiddict-contrib for community based extensions as mentioned dapper,  marten etc.

**Comment by kevinchalet** [comment]
> What would your feelings be on an openiddict-contrib for community based extensions as mentioned dapper, marten etc.

Someone would still need to maintain that repo and the corresponding packages. And if these packages used the official "OpenIddict.*", that someone would likely be me 🤣 

I encourage the community members to provide support for additional stores and release them under their own name. The OpenIddict documentation already lists such community packages.
