### ISSUE TITLE
I have an error when implementing openiddict with envoy

### ISSUE THREAD

**Issue by dinhan92** [openiddict/openiddict-core#1352]
### Describe the bug

Here is my envoy.yaml:

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/a"
                route:
                  prefix_rewrite: "/api"
                  cluster: api_service
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: api_service
    connect_timeout: 15s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: api_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: api
                port_value: 80

Here is my Api Startup.cs:

public void ConfigureServices(IServiceCollection services)
    {
      services.AddRouting(o => o.LowercaseUrls = true);

      services.AddAuthentication(options =>
      {
        options.DefaultScheme
          = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
        options.DefaultForbidScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
      });

      // Register the OpenIddict validation components.
      services.AddOpenIddict()
        .AddValidation(options =>
        {
          // Note: the validation handler uses OpenID Connect discovery
          // to retrieve the address of the introspection endpoint.
          options.SetIssuer("https://localhost:5000/");
          options.AddAudiences("api_service");

          // Configure the validation handler to use introspection and register the client
          // credentials used when communicating with the remote introspection endpoint.
          options.UseIntrospection()
                 .SetClientId("api_service")
                 .SetClientSecret("my-api-secret");

          // Register the System.Net.Http integration.
          options.UseSystemNetHttp();

          // Register the ASP.NET Core host.
          options.UseAspNetCore();
        });

      services.AddControllers();
      services.AddSwaggerGen(c =>
      {
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "Api", Version = "v1" });
      });
    }

    public void Configure(
      IApplicationBuilder app,
      IWebHostEnvironment env
    )
    {
      if (env.IsDevelopment())
      {
        app.UseCors(builder =>
        {
          builder.WithOrigins("http://localhost:4200", "https://localhost:5000");
          builder.WithMethods("GET");
          builder.WithHeaders("Authorization");
        });

        app.UseDeveloperExceptionPage();
        app.UseSwagger();
        app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Api v1"));
      }

      // app.UseHttpsRedirection();

      app.UseRouting();

      app.UseAuthentication();
      app.UseAuthorization();

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapControllers();
      });
    }

Here is my Openiddict Server Startup.cs:

public void ConfigureServices(IServiceCollection services)
    {
      services.AddDbContext<ApplicationDbContext>(options =>
      {
        // Configure the context to use Microsoft SQL Server.
        options.UseSqlite(Configuration.GetConnectionString("DefaultConnection"));
      });

      // Register the Identity services.
      services.AddIdentity<ApplicationUser, IdentityRole>(options =>
      {
        options.User.RequireUniqueEmail = true;
      })
      .AddEntityFrameworkStores<ApplicationDbContext>()
      .AddDefaultTokenProviders();

      // Configure Identity to use the same JWT claims as OpenIddict instead
      // of the legacy WS-Federation claims it uses by default (ClaimTypes),
      // which saves you from doing the mapping in your authorization controller.
      services.Configure<IdentityOptions>(options =>
      {
        options.Password.RequireDigit = false;
        options.Password.RequiredLength = 5;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequireUppercase = false;
        options.Password.RequireLowercase = false;

        options.ClaimsIdentity.UserNameClaimType = Claims.Name;
        options.ClaimsIdentity.UserIdClaimType = Claims.Subject;
        options.ClaimsIdentity.RoleClaimType = Claims.Role;
      });

      if (!Helpers.Constants.IsTestingEnvironment(Environment.EnvironmentName))
      {
        // OpenIddict offers native integration with Quartz.NET to perform scheduled tasks
        // (like pruning orphaned authorizations/tokens from the database) at regular intervals.
        services.AddQuartz(options =>
        {
          options.UseMicrosoftDependencyInjectionJobFactory();
          options.UseSimpleTypeLoader();
          options.UseInMemoryStore();
        });

        // Register the Quartz.NET service and configure it to block shutdown until jobs are complete.
        services.AddQuartzHostedService(options => options.WaitForJobsToComplete = true);
      }

      services.AddOpenIddict()
        // Register the OpenIddict core components.
        .AddCore(options =>
        {
          options.UseEntityFrameworkCore();
          if (!Helpers.Constants.IsTestingEnvironment(Environment.EnvironmentName))
          {
            options.UseQuartz();
          }
        })
        // Register the OpenIddict server components.
        .AddServer(options =>
        {
          options.SetIssuer(new Uri("https://localhost:5000/"));

          // Enable the authorization, device, logout, token, userinfo and verification endpoints.
          options.SetAuthorizationEndpointUris("/connect/authorize")
                 .SetLogoutEndpointUris("/connect/logout")
                 .SetTokenEndpointUris("/connect/token")
                 .SetIntrospectionEndpointUris("/connect/introspect")
                 .SetUserinfoEndpointUris("/connect/userinfo");

          // Note: this sample uses the code, device, password and refresh token flows, but you
          // can enable the other flows if you need to support implicit or client credentials.
          options.AllowAuthorizationCodeFlow()
                 .AllowRefreshTokenFlow();

          // Mark the "email", "profile", "roles" and "demo_api" scopes as supported scopes.
          options.RegisterScopes(
            Scopes.OpenId,
            Scopes.Email,
            Scopes.Profile,
            Scopes.Roles
            // "server_scope",
            // "api_scope"
            // "some_scope"
          );

          if (!Helpers.Constants.IsTestingEnvironment(Environment.EnvironmentName))
          {
            // Register the signing and encryption credentials.
            options.AddDevelopmentEncryptionCertificate()
                   .AddDevelopmentSigningCertificate()
                   .DisableAccessTokenEncryption();
          }
          else
          {
            options.AddEphemeralEncryptionKey()
                   .AddEphemeralSigningKey()
                   .DisableAccessTokenEncryption();
          }

          // Force client applications to use Proof Key for Code Exchange (PKCE).
          options.RequireProofKeyForCodeExchange();

          // Register the ASP.NET Core host and configure the ASP.NET Core-specific options.
          options.UseAspNetCore()
                 .EnableStatusCodePagesIntegration()
                 .EnableAuthorizationEndpointPassthrough()
                 .EnableLogoutEndpointPassthrough()
                 .EnableTokenEndpointPassthrough()
                 .EnableUserinfoEndpointPassthrough();
          // .DisableTransportSecurityRequirement(); // During development, you can disable the HTTPS requirement.
        })
        // Register the OpenIddict validation components.
        .AddValidation(options =>
        {
          // Import the configuration from the local OpenIddict server instance.
          options.UseLocalServer();

          // Register the ASP.NET Core host.
          options.UseAspNetCore();
        })
        // Register the EF based UI Store for OpenIddict related entities.
        .AddUIStore(options =>
        {
          options.OpenIddictUIContext = builder =>
           builder.UseSqlite(Configuration.GetConnectionString("DefaultConnection"),
             sql => sql.MigrationsAssembly(typeof(Startup)
                       .GetTypeInfo()
                       .Assembly
                       .GetName()
                       .Name));
        })
        // Register the APIs for the EF based UI Store based on OpenIddict.
        .AddUIApis(options =>
        {
          // Tell the system about the allowed Permissions it is built/configured for.
          options.Permissions = new List<string>
          {
            Permissions.Endpoints.Authorization,
            Permissions.Endpoints.Logout,
            Permissions.Endpoints.Token,
            Permissions.Endpoints.Introspection,
            Permissions.GrantTypes.AuthorizationCode,
            Permissions.GrantTypes.DeviceCode,
            Permissions.GrantTypes.RefreshToken,
            Permissions.ResponseTypes.Code,
            Permissions.Scopes.Email,
            Permissions.Scopes.Profile,
            Permissions.Scopes.Roles,
            Permissions.Prefixes.Scope + "server_scope"
            // Permissions.Prefixes.Scope + "api_scope"
            // Permissions.Prefixes.Scope + "some_scope"
          };
        })
        // Register the EF based UI Store for the ASP.NET Identity related entities.
        .AddUIIdentityStore(options =>
        {
          options.OpenIddictUIIdentityContext = builder =>
           builder.UseSqlite(Configuration.GetConnectionString("DefaultConnection"),
             sql => sql.MigrationsAssembly(typeof(Startup)
                       .GetTypeInfo()
                       .Assembly
                       .GetName()
                       .Name));
        })
        // Register the APIs for the EF based UI Store based on ASP.NET Identity.
        .AddUIIdentityApis<ApplicationUser>();

      if (!Helpers.Constants.IsTestingEnvironment(Environment.EnvironmentName))
      {
        services.AddSwaggerGen(c =>
        {
          c.SwaggerDoc("v1", new OpenApiInfo
          {
            Version = "v1",
            Title = "API Server Documentation",
            Description = "API Server Documentation"
          });

          c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
          {
            In = ParameterLocation.Header,
            Name = "Authorization",
            Description = "Example: \"Bearer {token}\"",
            Type = SecuritySchemeType.ApiKey
          });
          c.DocInclusionPredicate((name, api) => true);
          c.TagActionsBy(api =>
          {
            if (api.GroupName != null)
            {
              return new[] { api.GroupName };
            }

            if (api.ActionDescriptor is ControllerActionDescriptor controllerActionDescriptor)
            {
              return new[] { controllerActionDescriptor.ControllerName };
            }

            throw new InvalidOperationException("Unable to determine tag for endpoint.");
          });
          c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
        });
      }

      services.AddScoped<IMigrationService, MigrationService>();

      services.AddMvc();
    }

    public void Configure(IApplicationBuilder app)
    {
      app.UseCors(builder =>
      {
        builder
          .WithOrigins("http://localhost:4200")
          .AllowAnyHeader()
          .AllowAnyMethod()
          .AllowCredentials();
      });

      if (!Helpers.Constants.IsTestingEnvironment(Environment.EnvironmentName))
      {
        app.UseSwagger();
        app.UseSwaggerUI(c =>
        {
          c.SwaggerEndpoint("/swagger/v1/swagger.json", "Server API V1");
          c.DocExpansion(DocExpansion.None);
        });
      }

      app.UseDeveloperExceptionPage();

      app.UseDefaultFiles();
      app.UseStaticFiles();

      app.UseStatusCodePagesWithReExecute("/error");

      app.UseRouting();

      app.UseAuthentication();
      app.UseAuthorization();

      app.UseEndpoints(builder =>
      {
        builder.MapControllers();
        builder.MapRazorPages();
        builder.MapDefaultControllerRoute();
      });
    }

When I run docker compose up, I can still get the token, but when I paste the token to Postman and run, I meet 504 Gateway Error, sometimes, it may change to 500 Internal Server Error: An unknown error occurred while retrieving the OpenIddict validation context.

I have no idea how to solve this. It took me 2 days! Please help !

**Comment by kevinchalet** [comment]
Hi,

If you're sure the bug is caused by OpenIddict, please provide a **minimal** repro - ideally hosted in a GitHub repository - and I'll take a look.

**Comment by dinhan92** [comment]
https://github.com/dinhan92/DemoOpeniddictDocker 
Here is my Demo, the actual error is: 
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
demomicroservice-api-1        |       An unhandled exception has occurred while executing the request.
demomicroservice-api-1        |       System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
demomicroservice-api-1        |        ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5000)
demomicroservice-api-1        |        ---> System.Net.Sockets.SocketException (99): Cannot assign requested address

In case I use docker, when I use [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)], it get this error. If I remove it, the  identity.Name in private function in Resource Controller of the Api return nothing.

So can you give some advice?

**Comment by kevinchalet** [comment]
It's very likely not an OpenIddict issue but a network problem specific to your implementation. If you search for the exception message on Google, I'm sure you'll find a few hints to point you in the right direction.
