### ISSUE TITLE
make Properties of xxxDescriptor virtual

### ISSUE THREAD

**Issue by tai-yi** [openiddict/openiddict-core#1355]
I just want add  `JsonExtensionDataAttribute`  for Properties, that will simplify json body map to  OpenIddict...Descriptor.

**Comment by kevinchalet** [comment]
While I agree it could be useful, these types contain properties that are not meant to be serialized or can't be serialized to JSON easily (e.g `OpenIddictTokenDescriptor.Principal` of type `ClaimsPrincipal`). Adding such an attribute would encourage users to do something not supported.

Closing.
