### ISSUE TITLE
Nonce cookie not being returned, .AspNetCore.Identity.Application cookie returned instead

### ISSUE THREAD

**Issue by mitchellgarner** [openiddict/openiddict-core#1358]
We have upgraded both our application running openiddict and the client application in question to .net core 3.1 and .net framework 4.8 respectively.  Openiddict is also updated to 3.1.0

Since this update, and the resulting changes in both projects, our .net framework asp.net mvc 5 application began hitting exception
IDX21323: RequireNonce is 'System.Boolean'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.

Upon inspection of the redirect request from our connect/authorize endpoint back to the client application's signin callback (called signin-sevanidentity) we see that instead of receiving a cookie of OpenIdConnect.nonce like we see on our production instance we see .AspNetCore.Identity.Application
Callback in updated version
![image](https://user-images.githubusercontent.com/31454269/144307852-1b06a4d2-8ee4-4cd2-babc-39c0eca67d2e.png)

Callback in working production instance
![image](https://user-images.githubusercontent.com/31454269/144307811-f3d69010-5bbb-4772-9f5c-33adb35efe74.png)

Not certain if I've messed up config in openiddict, the client or both.

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.

**Comment by mitchellgarner** [comment]
@kevinchalet I previously sponsored this project (granted I couldn't do too much) and submitted an issue see -> https://github.com/openiddict/openiddict-core/issues/1338 so thought I could submit another as still facing issues

I will put on the community, thx

**Comment by kevinchalet** [comment]
@mitchellgarner I hate to be that guy, but your sponsorship was bellow the $2/month ($24/year) tier, so it wasn't even eligible to support. Since I think every contribution counts and it's not always easy for individuals to select a higher tier, I answered your question but you didn't reply back.

Assuming it's for a professional project, I'd recommend encouraging your company to sponsor the project 😄
