### ISSUE TITLE
How to manually login or generate a token from a controller?

### ISSUE THREAD

**Issue by levitatejay** [openiddict/openiddict-core#136]
I'd like to do something like the following in a controller:

```
var token = openiddict.login(username, password, grant_type);
HttpContext.Response.Cookies.Append("CookieBearer", token);
```

Then I will write some middleware to shift incoming cookies with the name "CookieBearer" to an Authorization bearer header.

Is there a way to do this?

**Comment by kevinchalet** [comment]
> Is there a way to do this?

No, there's **deliberately** no way to generate a token outside an OAuth2/OIDC request, just like the cookies middleware doesn't allow you to manually generate an authentication cookie.

> Then I will write some middleware to shift incoming cookies with the name "CookieBearer" to an Authorization bearer header.

That sounds like a crazy idea and in this case, why not just using cookies authentication?

**Comment by levitatejay** [comment]
I'm using bearer auth currently to secure my API for native running applications and its working well.

There are a couple of reasons I want to use a cookie instead for my angular website:
1. Storing the token in session/local storage is vulnerable to XSS attacks
2. I can redirect unauthenticated users attempting to load the web application before having to load and run any javascript

This link recommends storing JWT in a cookie and using an antiforgery token as a claim to prevent CSRF attacks: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

> No, there's deliberately no way to generate a token outside an OAuth2/OIDC request, just like the cookies middleware doesn't allow you to manually generate an authentication cookie.

You can manually login with cookie authentication by passing user credentials directly to  SignInManager in a controller. Is there not something similar for bearer authentication?

**Comment by kevinchalet** [comment]
> Storing the token in session/local storage is vulnerable to XSS attacks

Contrary to popular belief, cookies are also vulnerable to XSS, even if they are marked with HttpOnly, since nothing prevents me from sending an API request on behalf of a victim if I find a XSS vulnerability in your app (no need to steal the token in this case, since it is automatically sent by the victim's browser)

> This link recommends storing JWT in a cookie and using a antiforgery token as a claim to prevent CSRF attacks: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

I had a brief discussion with Nathanael Barbettini (from Stormpath) about one of his recent blog post. I totally disagree with the approach this post recommends, as it makes you think putting a JWT token in a cookie is a form of "token authentication", which is totally wrong: it's plain old cookie authentication, with all the XSRF risks it involves.

If you want to use cookies, use the cookie middleware, implement XSRF countermeasures and don't even use tokens. No need for OpenIddict in this case.

> You can manually login with cookie authentication by passing user credentials directly to SignInManager in a controller. Is there not something similar for bearer authentication?

Sure, but Identity's `SignInManager` doesn't allow to "just generate a cookie ticket" or retrieve it before it is sent to the browser. OpenIddict exactly works the same way.

**Comment by levitatejay** [comment]
Okay thank you for the suggestions. I'll use both the bearer and identity cookie middleware together for now.

What about signing out? I'd like to make a controller action for admins to invalidate any tokens/cookies linked to a certain user. That way we can force a user to enter his credentials again.

**Comment by kevinchalet** [comment]
> What about signing out? I'd like to make a controller action for admins to invalidate any tokens/cookies linked to a certain user. That way we can force a user to enter his credentials again.

The latest OpenIddict bits support refresh token invalidation/revocation: take a look at `OpenIddictUserManager.GetTokensAsync()` and `OpenIddictTokenManager.RevokeAsync()`.

You can also use the built-in revocation endpoint. You can learn more about revocation by reading the RFC: https://tools.ietf.org/html/rfc7009#section-2.1

Access token revocation is not supported and will likely never be for performance reasons. To mitigate the risks of an access token leakage, the default access token lifetime was recently lowered to 30 minutes, which matches the default security stamp check interval used by Identity for the authentication cookies it issues.

**Comment by levitatejay** [comment]
Thank you for your help so far... I've written the following in my admin user service:

```
public async Task<bool> RevokeTokenAsync(string userId)
        {
            var user = await _repo.Get()
                .Where(u => u.Id == userId)
                .SingleOrDefaultAsync();

            var tokens = await _userManager.GetTokensAsync(user);

            foreach(var token in tokens)
            {
                await _tokenManager.RevokeAsync(token);
            }
            return true;
        }
```

But the RevokeAsync method takes an `OpenIddictToken`and not a `string`(which is what GetTokensAsync returns)... How can I convert the strings returned my the user manager to tokens so I can revoke them? Is there a better way that involves less round trips to the DB?

**Comment by kevinchalet** [comment]
Making `GetTokensAsync` return a list of `TToken` was unfortunately not an option, so we had to return token identifiers instead.

You can retrieve the token entity using `var token = await _tokenManager.FindByIdAsync(id);`.
