### ISSUE TITLE
Access token getting expired before the time span. Server time is in Arabic Standard Time and Server UTC time is proper. Please suggest us with the change.

### ISSUE THREAD

**Issue by anilvebilisetty** [openiddict/openiddict-core#1360]
### Further technical details
- ASP.NET Core version.
- Include the output of `dotnet --info`.
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version.

**Comment by kevinchalet** [comment]
I tried with the Riyadh TZ and I was unable to reproduce that issue.

![image](https://user-images.githubusercontent.com/6998306/145070775-d2818425-edb8-4e91-951d-331c98f8a32b.png)
