### ISSUE TITLE
The mandatory 'code_challenge' parameter is missing

### ISSUE THREAD

**Issue by vishnu4** [openiddict/openiddict-core#1361]
Hi there.  I'm trying to build an identity server that i can use as a provider for an existing Azure B2C tenant.  I'm writing the server in .net 5 using OpenIddict 3.1.1.  What I've written is a combination of your MVC.Server sample ( https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server ) and your Contruum sample ( https://github.com/openiddict/openiddict-samples/tree/dev/samples/Contruum ) for the razor pages.  I have everything working when i connect directly from another .net 5 test app to this identity server, authorization works fine, i get the claims back and everything, but when i try to put my link in https://oidcdebugger.com/ or through Azure B2C's user flow, i get the error that 'The mandatory 'code_challenge' parameter is missing'.   

most of my startup code and examples are this stackoverflow post: https://stackoverflow.com/questions/70140416/the-mandatory-code-challenge-parameter-is-missing-with-openiddict .

Please let me know what i might be missing, or what i can try to fix this up.  I feel like I'm 90% there just missing something stupid.  Let me know if i should upload my app here instead.

**Comment by kevinchalet** [comment]
Hi @vishnu4,

Thanks for sponsoring the project, much appreciated!

The error you're seeing indicates that one of the PKCE parameters (`code_challenge` or `code_challenge_method`) was not sent, yet was considered required [for one of these 2 reasons](https://documentation.openiddict.com/configuration/proof-key-for-code-exchange.html):
  - The server is globally configured to require PKCE using `options.RequireProofKeyForCodeExchange()`.
  - The client was created with the `Requirements.Features.ProofKeyForCodeExchange` requirement enforced. The snippet you posted on SO indicates this policy is enforced for your demo client.

Regarding https://oidcdebugger.com/, getting this error is expected: it doesn't support PKCE at all. Its support is tracked by https://github.com/nbarbettini/oidc-debugger/issues/39 but I wouldn't expect it to appear anytime soon without a contribution.

Regarding Azure B2C, I believe it supports PKCE so it's more surprising. Please post your logs to determine what's going on.

**Comment by vishnu4** [comment]
yeah, i thought the oidcdebugger was a stretch.  Thank you for helping!  Here are my app insights web server logs:

> Connecting...
> 2021-12-03T15:35:35  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
> #Software: Microsoft Internet Information Services 8.0#Fields: date time s-sitename cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Cookie) cs(Referer) cs-host sc-status sc-substatus sc-win32-status sc-bytes cs-bytes time-taken
> 2021-12-03 15:34:55 ~1COBRAID GET /api/vfs/site/wwwroot/ _=1638544727307&X-ARR-LOG-ID=23710c4c-9308-4dc1-aa01-f224bfa4562b 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 - - <SCMsitename>.net 200 0 0 8253 1533 234
> 2021-12-03 15:34:55 ~1COBRAID GET /api/siteextensions/ api-version=2018-11-01&X-ARR-LOG-ID=188bbc0f-a1d2-43b1-80ca-3c00cbff3002 443 - 40.71.13.64 - - https://management.azure.com/subscriptions/fa2b7108-47f0-46ae-bde8-0b3f0a3f717c/resourceGroups/COBRA5-Develop/providers/Microsoft.Web/sites/<sitename>/siteextensions?api-version=2018-11-01 <SCMsitename>.net 200 0 0 1464 2889 1643
> 2021-12-03 15:35:52 ~1COBRAID GET /api/logstream/ X-ARR-LOG-ID=95a90ef9-102f-473b-b72c-ebaedf9c25e6 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 - - <SCMsitename>.net 200 0 64 1658 1401 25444
> 2021-12-03 15:36:05 COBRAID GET /.well-known/openid-configuration X-ARR-LOG-ID=9b2a1d44-b442-40e0-83fb-043ca399983c 443 - 104.42.32.20 - - - <sitename>.net 200 0 0 2075 819 14035
> 2021-12-03 15:36:05 COBRAID GET /.well-known/jwks X-ARR-LOG-ID=837f658b-dfc5-4280-98eb-886c8bc5ad79 443 - 104.42.32.20 - - - <sitename>.net 200 0 0 1022 771 93
> 2021-12-03 15:36:07 COBRAID GET /connect/authorize client_id=XXXXXX&redirect_uri=https%3a%2f%2f<b2csitename>.b2clogin.com%2f<b2csitename>.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid&response_mode=form_post&nonce=jkaT1xuyyFWf3zA5gyWN1w%3d%3d&prompt=login&ui_locales=en-US&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6MzkyYWZiZWUtOWVkYy00ZDM2LTgxN2EtMTFhYTdmODIzZGU2IiwiVElEIjoiZDc4ZGE0NWMtMjJlMi00NTM1LThiMWQtN2I3OTAzZmYwODViIiwiVE9JRCI6IjZkNDQ5NWUyLWFhM2ItNGIxMy04NTk3LTNmMTU4NzVlYWI3ZSJ9&X-ARR-LOG-ID=3ad682e9-558d-47e4-960c-5d91ed80882b 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 ARRAffinity=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17;+ARRAffinitySameSite=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17 https://portal.azure.com/ <sitename>.net 302 0 0 576 2998 389
> 2021-12-03 15:36:07 COBRAID GET /connect/authorize request_id=E_X01RVisQoEp7rWC2mpIDKQKTWYbZh1Z7iDrVyWz90&X-ARR-LOG-ID=3945d57f-f3fd-4eac-af0e-c1153f2c6b34 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 ARRAffinity=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17;+ARRAffinitySameSite=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17 https://portal.azure.com/ <sitename>.net 400 0 0 732 1771 218
> 2021-12-03 15:36:17 COBRAID GET /.well-known/openid-configuration X-ARR-LOG-ID=36fcf293-2b3f-4087-80fb-cd74a41fc839 443 - 104.42.32.20 - - - <sitename>.net 200 0 0 2118 821 15
> 2021-12-03 15:36:17 COBRAID GET /.well-known/jwks X-ARR-LOG-ID=c70008f1-46cb-4a32-9489-8445b6f350c6 443 - 104.42.32.20 - - - <sitename>.net 200 0 0 1022 773 31
> 2021-12-03 15:36:17 COBRAID GET /connect/authorize client_id=XXXXXX&redirect_uri=https%3a%2f%2f<b2csitename>.b2clogin.com%2f<b2csitename>.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid&response_mode=form_post&nonce=u3YPeeHltW4MpqWv0%2bBFyQ%3d%3d&prompt=login&ui_locales=en-US&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6OTI5ZWQzMmItMzdhNy00MmRjLTlhZWMtY2M3MTMxY2FkYWQ2IiwiVElEIjoiZDc4ZGE0NWMtMjJlMi00NTM1LThiMWQtN2I3OTAzZmYwODViIiwiVE9JRCI6IjZkNDQ5NWUyLWFhM2ItNGIxMy04NTk3LTNmMTU4NzVlYWI3ZSJ9&X-ARR-LOG-ID=6cfd30c7-5efb-4e4c-bf67-418023181e40 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 ARRAffinity=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17;+ARRAffinitySameSite=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17 https://portal.azure.com/ <sitename>.net 302 0 0 576 3004 15
> 2021-12-03 15:36:17 COBRAID GET /connect/authorize request_id=-ruj6aGl23710T4BLEQ-8pQhsKWE6jmVbyP87D6Klac&X-ARR-LOG-ID=1d6dfd04-c71f-4d65-bc57-95be5eff5f03 443 - 67.160.96.42 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/96.0.4664.45+Safari/537.36 ARRAffinity=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17;+ARRAffinitySameSite=22a7daa836b64a8ce56c907737553d08297ff2e76cd06a1f52c29956b9a85c17 https://portal.azure.com/ <sitename>.net 400 0 0 732 1771 31

and here are my application logs (not much here):

> Connecting...
> 2021-12-03T15:33:14  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
> 2021-12-03T15:33:30 sandboxproc.exe D:\DWASFiles\Sites\cobraid\Temp\applicationhost.config True True
> 2021-12-03T15:33:30 env XPROC_TYPENAME=Microsoft.Web.Hosting.Transformers.ApplicationHost.SiteExtensionHelper, Microsoft.Web.Hosting, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> 2021-12-03T15:33:30 env XPROC_METHODNAME=Transform
> 2021-12-03T15:33:30 Start 'Microsoft.AspNetCore.AzureAppServices.SiteExtension' site extension transform
> 2021-12-03T15:33:30 StartSection Executing InsertIfMissing (transform line 7, 23)
> 2021-12-03T15:33:30 on /configuration/system.webServer
> 2021-12-03T15:33:30 Applying to 'configuration' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertIfMissing
> 2021-12-03T15:33:30 StartSection Executing InsertIfMissing (transform line 8, 16)
> 2021-12-03T15:33:30 on /configuration/system.webServer/runtime
> 2021-12-03T15:33:30 Applying to 'system.webServer' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertIfMissing
> 2021-12-03T15:33:30 StartSection Executing InsertIfMissing (transform line 9, 31)
> 2021-12-03T15:33:30 on /configuration/system.webServer/runtime/environmentVariables
> 2021-12-03T15:33:30 Applying to 'runtime' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertIfMissing
> 2021-12-03T15:33:30 StartSection Executing InsertOrAppendAttribute (transform line 10, 406)
> 2021-12-03T15:33:30 on /configuration/system.webServer/runtime/environmentVariables/add[@name='DOTNET_ADDITIONAL_DEPS']
> 2021-12-03T15:33:30 Applying to 'environmentVariables' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertOrAppendAttribute
> 2021-12-03T15:33:30 StartSection Executing InsertOrAppendAttribute (transform line 11, 158)
> 2021-12-03T15:33:30 on /configuration/system.webServer/runtime/environmentVariables/add[@name='DOTNET_SHARED_STORE']
> 2021-12-03T15:33:30 Applying to 'environmentVariables' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertOrAppendAttribute
> 2021-12-03T15:33:30 StartSection Executing InsertOrAppendAttribute (transform line 12, 146)
> 2021-12-03T15:33:30 on /configuration/system.webServer/runtime/environmentVariables/add[@name='ASPNETCORE_HOSTINGSTARTUPASSEMBLIES']
> 2021-12-03T15:33:30 Applying to 'environmentVariables' element (no source line info)
> 2021-12-03T15:33:30 EndSection Done executing InsertOrAppendAttribute
> 2021-12-03T15:33:30 Successful 'C:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\applicationHost.xdt' site extension transform
> 2021-12-03T15:33:30 sandboxproc.exe complete successfully. Elapsed = 694.00 ms
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 400.0 - Bad Request</title><style type="text/css"></style>
> </head><body><div id="content">
> <div class="content-container"><h3>HTTP Error 400.0 - Bad Request</h3><h4>Bad Request</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li></li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
> <div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr>
> </table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://cobraid:80/connect/authorize?request_id=qo6NFUG2kRsN-mSgkmE9RZZY_uNv0rtzStAtXl-4XFc</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\connect\authorize</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
> </table><div class="clear"></div></div></fieldset></div>
> <div class="content-container"><fieldset><h4>More Information:</h4>The request could not be understood by the server due to malformed syntax.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=400,0,0x00000000,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>
> </fieldset></div></div></body></html>

**Comment by kevinchalet** [comment]
The AI logs confirm that no `code_challenge`/`code_challenge_method` parameter is specified in the authorization request: since they are missing and the application is configured to require PKCE, OpenIddict does the right thing by rejecting the request.

Can you please double check your B2C settings?

**Comment by vishnu4** [comment]
These are my identity provider settings, and my user flow settings.  are there other ones you're interested in that i'm not aware of
![1](https://user-images.githubusercontent.com/1782150/144635508-3811739a-9fa4-4964-ae5f-f7849ed171cb.PNG)
?
![2](https://user-images.githubusercontent.com/1782150/144635541-825769ac-ea29-41b8-8b80-43457e8d39f3.PNG)

**Comment by kevinchalet** [comment]
I tried to reproduce that and B2C doesn't even show me the PKCE configuration panel when running the user flow (not sure why it's even a thing, it's typically not something that is user-set...). I'll try with a different external provider to see if it helps, but I suspect you'll need to ping the Azure support as it's likely not something I'll be able to help you with, unfortunately.

**Comment by kevinchalet** [comment]
In the meantime, you'll probably want to remove the PKCE requirement from the OpenIddict client application registration, so you're not blocked by that error.

**Comment by vishnu4** [comment]
understood, will try that and thank you.  Also some extra images that might help you follow are the app registration pages, see the line about my app being 'eligible for PKC
![4](https://user-images.githubusercontent.com/1782150/144639729-ae8508db-cede-4f99-9c6d-2bbc37514634.PNG)
![3](https://user-images.githubusercontent.com/1782150/144639732-4c708a51-de86-4539-9eb8-cc3eaa6fc315.PNG)
E'

**Comment by kevinchalet** [comment]
Alright, you only get this panel when creating a SPA client (which makes no sense at all, since PKCE was originally designed for native mobile apps and can now be used by any type of app, public or confidential).

What happens is that they have a bug: if you select "plain" (not allowed by default by OpenIddict for security reasons), the code challenge/code challenge method are correctly attached to the request. If you keep S256, no code challenge at all is attached 🤣 

At this point, the best I can do is wish you good luck with the support so that it's fixed this year rather than the next one 😄

**Comment by vishnu4** [comment]
Thank you for finding that out!  I'll work w/out PKCE for now and at least get stuff started.  Hopefully i can get a B2C fix soon!  I'll leave comments here for others in case anything comes up

**Comment by kevinchalet** [comment]
In case you'd prefer keeping PKCE enforced, you can also configure OpenIddict to allow the less secure `plain` method: https://documentation.openiddict.com/configuration/proof-key-for-code-exchange.html#enabling-codechallengemethodplain-support

**Comment by vishnu4** [comment]
BTW, i couldn't get the plain method to work.  
if i leave 'RequireProofKeyForCodeExchange'  and add
`options.Configure(options => options.CodeChallengeMethods.Add(CodeChallengeMethods.Plain));`
then i still get the 'The mandatory 'code_challenge' parameter is missing.' error, even changing the B2C code challenge method in the User Flow test from 256 to plain (same error for both)

Removing RequireProofKeyForCodeExchange does seem to allow me to move forward though, although i had to remove
`Requirements.Features.ProofKeyForCodeExchange` from my worker as well (forgot i had that in there)

**Comment by kevinchalet** [comment]
Interesting. When I tested earlier today, the plain method worked if you manually replaced the code verifier with a custom value. But maybe I was just lucky? 🤣

**Comment by vishnu4** [comment]
maybe, but no big right now.  Thank you!

**Comment by vishnu4** [comment]
heads up @kevinchalet , apparently this is by design right now?  The answer I recieved was this link so far: https://docs.microsoft.com/en-us/answers/questions/294423/external-identity-providers-how-to-configure-code.html

**Comment by kevinchalet** [comment]
Thanks for the heads-up! Not exactly the kind of reply you'd want to get for such a critical service, but sadly, I'm not really surprised 😕
