### ISSUE TITLE
Claims are merged when they get to the client side

### ISSUE THREAD

**Issue by 3x0dv5** [openiddict/openiddict-core#1365]
When we have multiple Claims with the same Type what is sent to a client side is a single Claim with its value being a serialized representation of an array.

**table asp_net_role_claims**
![image](https://user-images.githubusercontent.com/250271/146846470-894473fc-6ab8-4c61-901b-fe4a929cd589.png)

** The claims that get to the client side**
![image](https://user-images.githubusercontent.com/250271/146846836-6c578c1d-f89b-4c56-bd18-1d3e6a8a9af6.png)

For single
![image](https://user-images.githubusercontent.com/250271/146847162-3370f408-07f2-4f43-9814-fb57adaac485.png)

For multiple fails because the Claim Value is a string '[]'
![image](https://user-images.githubusercontent.com/250271/146847233-e0d78fed-01cd-4801-a83a-5afa7d75a571.png)
![image](https://user-images.githubusercontent.com/250271/146847531-950a8463-606d-46de-9f76-ab2a09272ee8.png)

On the server side I have not problem. 
![image](https://user-images.githubusercontent.com/250271/146847642-1ac787ab-69f4-4849-9208-31009c7d2d8b.png)
![image](https://user-images.githubusercontent.com/250271/146847727-3eec0835-0d5a-4e58-bd76-b176c4af946a.png)

**Comment by kevinchalet** [comment]
I'm not able to reproduce it locally. Please attach a minimal repro demonstrating the issue.

**Comment by 3x0dv5** [comment]
Hi, I changed the blazor sample https://github.com/openiddict/openiddict-samples/pull/174

Repo: https://github.com/3x0dv5/openiddict-samples/tree/bug_1365

You just need to:
1. execute the Balosar sample
2. create an user
3. click on the add sample claims button

You'll see that the result reported by server and client is different and the client side is wrong.
![image](https://user-images.githubusercontent.com/250271/146941978-4d166388-e51d-4a56-9101-fa66b143bb90.png)

Hope this helps

**Comment by kevinchalet** [comment]
Thanks for the repro, I'll take a look.

Were you able to reproduce this issue with a more "traditional" OIDC client (like a regular ASP.NET Core app with the OIDC middleware) to exclude a potential bug in the Blazor authentication stack?

**Comment by 3x0dv5** [comment]
Tried the aspnet default template, that one doesn't even seem to load the claims from the Db. I need to figure out how that Duende thingie works I guess 😞 to see if it has the same behaviour.

**Comment by kevinchalet** [comment]
The id_token generated by OpenIddict is correctly formatted so it's not a server bug. It's very likely because the Blazor authentication stack doesn't materialize array claims in `ClaimsPrincipal` the same way the MSFT JWT or OpenIddict validation handlers do. Unfortunately, it's not something OpenIddict has any influence on so you'll need to report this bug/inconsistency to the ASP.NET folks. Please open a ticket here with a link to this thread: https://github.com/dotnet/aspnetcore/issues.

```json
{
  "sub": "9e415cd6-d544-4377-a837-e7a6a74b498e",
  "name": "demo@demo.com",
  "ENTITY_TYPE_1": [
    "VIEW",
    "ADD"
  ],
  "ENTITY_TYPE_2": "VIEW",
  "oi_au_id": "f8d8edc0-a17e-4e30-9c9c-e2660471741c",
  "azp": "balosar-blazor-client",
  "at_hash": "WyZOPSgAfGBGasF7Jowqrg",
  "oi_tkn_id": "ddb96c80-d75c-4692-8cf7-b46eab3fe909",
  "aud": "balosar-blazor-client",
  "exp": 1640101910,
  "iss": "https://localhost:44310/",
  "iat": 1640100710
}
```

**Comment by kevinchalet** [comment]
BTW, you'll want to fix that:

```csharp
// [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]
// using the above Authorize will break the server side CLAIMS.
```

Currently, your "API" controller reads claims from the authentication cookie and not from the access token. Make sure your custom claims have the "access_token" destination allowed, uncomment that attribute and things should work flawlessly (well, for the server-side check, at least 🤣)

**Comment by 3x0dv5** [comment]
Thanks for that tip, adding the access_token made it work server side with that decorator Authorize indeed. 
The client side, the more I look around the more it seems to be related with the actual framework implementation. Seems to be one of those things that just keeps missing the target 😞 

Some links: 
https://github.com/IdentityServer/IdentityServer4/issues/2999
https://github.com/IdentityServer/IdentityServer4/issues/1452
https://stackoverflow.com/questions/60623201/asp-net-core-3-0-merged-roles

Anyways I have a work around 
![image](https://user-images.githubusercontent.com/250271/146988967-1679c361-2899-463d-9d7b-413b09618b5e.png)

repo with sample:
https://github.com/3x0dv5/openiddict-samples/tree/bug_1365

```csharp
/******
the hack
******/

static class ClaimsPrincipalExtensions
{
    public static bool HasClaimValue(this ClaimsPrincipal user,string claimType, string claimValue)
    {
        var c = user.Claims.SingleOrDefault(m => m.Type == claimType);
        if (c == null)
            return false;
        try
        {
            var cValues = JsonSerializer.Deserialize<List<string>>(c.Value);
            return cValues != null && cValues.Contains(claimValue);
        }
        catch (Exception)
        {
            // ignored
        }
        return c.Value == claimValue;
    }
}
```

**Comment by kevinchalet** [comment]
> Thanks for that tip, adding the access_token made it work server side with that decorator Authorize indeed.

Glad it helped. If you like the project, please consider sponsoring it (or encouraging your employer/clients to do so) 😃 

> The client side, the more I look around the more it seems to be related with the actual framework implementation. Seems to be one of those things that just keeps missing the target 😞

You may still want to report this issue: both the JWT and OIDC handlers developed by MSFT - backed by the same Azure AD IdentityModel libs, also used by OpenIddict - correctly handle access/identity tokens by materializing JSON arrays as multiple claims. It's Blazor that is clearly inconsistent in this case, and since it's quite new, they may change this behavior or introduce a configuration option to fix that.

**Comment by 3x0dv5** [comment]
Thanks for your help. Sent you a pint (beer)! Enjoy 

Sorry, I can't sponsor more, unfortunately I only work with .NET as a hobbie, I don't make any money out of .NET.

**Comment by kevinchalet** [comment]
> Sorry, I can't sponsor more, unfortunately I only work with .NET as a hobbie, I don't make any money out of .NET.

Haha, no worries. Every contribution counts so thanks for that! 😃
