### ISSUE TITLE
OpenIddict.Validation.AspNetCore was not authenticated. Failure message: An error occurred while authenticating the current request.

### ISSUE THREAD

**Issue by Appdevcount** [openiddict/openiddict-core#1371]
Hi Kevin

I have setup a separate authorization server and is working fine and a separate resource/api server. I got the access token and tried to communicate api with token but got the subject message in console and below response from api

info: OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler[7]
      OpenIddict.Validation.AspNetCore was not authenticated. Failure message: An error occurred while authenticating the current request.
info: OpenIddict.Validation.OpenIddictValidationDispatcher[0]
      The response was successfully returned as a JSON document: {
        "error": "server_error",
        "error_description": "This resource server is currently unavailable.",
        "error_uri": "https://documentation.openiddict.com/errors/ID2092"
      }.
info: OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler[12]
      AuthenticationScheme: OpenIddict.Validation.AspNetCore was challenged.

Please help me understand the rootcause as i verified the config at auth server and api side validations, things look fine but no clue of exact reason

application details:
await manager.CreateAsync(new OpenIddictApplicationDescriptor
                {
                    ClientId = "mvc",
                    ClientSecret = "901564A5-E7FE-42CB-B10D-61EF6A8F3654",
                    ConsentType = ConsentTypes.Explicit,
                    DisplayName = "MVC client application",
                    PostLogoutRedirectUris =
                {
                    new Uri("https://localhost:7286/signout-callback-oidc")
                },
                    RedirectUris =
                {
                    new Uri("https://localhost:7286/signin-oidc")
                },
                    Permissions =
                {
                    Permissions.Endpoints.Authorization,
                    Permissions.Endpoints.Logout,
                    Permissions.Endpoints.Token,
                    Permissions.GrantTypes.AuthorizationCode,
                    Permissions.GrantTypes.RefreshToken,
                    //Permissions.Endpoints.Introspection,//added
                    Permissions.ResponseTypes.Code,
                    Permissions.Scopes.Email,
                    Permissions.Scopes.Profile,
                    Permissions.Scopes.Roles,
                    Permissions.Prefixes.Scope + "demo_api"//"api_service"// "demo_api"
                    ,Permissions.Prefixes.Scope + "api_scope"
                },
                    Requirements =
                {
                    Requirements.Features.ProofKeyForCodeExchange
                }
                });

  var descriptor = new OpenIddictApplicationDescriptor
                {
                    ClientId = "api_service",
                    DisplayName = "API Service",
                    ClientSecret = "my-api-secret",
                            Permissions =
                    {
                      Permissions.Endpoints.Introspection
                    }
                };

scope details:

 var descriptor = new OpenIddictScopeDescriptor
                {
                    Name = "api_scope",
                    DisplayName = "API Scope access",
                    Resources =
                    {
                      "api_service"
                    }
                };

auth server:

    // Register the OpenIddict server components.
    .AddServer(options =>
    {
                // Enable the authorization, logout, token and userinfo endpoints.
                options.SetAuthorizationEndpointUris("/connect/authorize")
               .SetLogoutEndpointUris("/connect/logout")
               .SetTokenEndpointUris("/connect/token")
               .SetUserinfoEndpointUris("/connect/userinfo");

                // Mark the "email", "profile" and "roles" scopes as supported scopes.
                options.RegisterScopes(Scopes.Email, Scopes.Profile, Scopes.Roles);

                // Note: this sample only uses the authorization code flow but you can enable
                // the other flows if you need to support implicit, password or client credentials.
                options.AllowAuthorizationCodeFlow();

        //added
        options.AllowClientCredentialsFlow();
        options.AllowImplicitFlow();    
        options.AllowRefreshTokenFlow();
        //added

        // Register the signing and encryption credentials.
        options.AddDevelopmentEncryptionCertificate()
               .AddDevelopmentSigningCertificate();

        //The JWT access tokens produced by the latest OpenIddict 3.0 nightly builds are now encrypted, to match the behavior we had in 1.x and 2.x. JWE is not something jwt.io supports, so it's not surprising if you get an invalid error there.
        //https://documentation.openiddict.com/configuration/token-formats.html
        options.DisableAccessTokenEncryption();

        // Register the ASP.NET Core host and configure the ASP.NET Core-specific options.
        options.UseAspNetCore()
               .EnableAuthorizationEndpointPassthrough()
               .EnableLogoutEndpointPassthrough()
               .EnableTokenEndpointPassthrough()
               .EnableUserinfoEndpointPassthrough()
               .EnableStatusCodePagesIntegration();
    })

    // Register the OpenIddict validation components.
    .AddValidation(options =>
    {
                // Import the configuration from the local OpenIddict server instance.
                options.UseLocalServer();

                // Register the ASP.NET Core host.
                options.UseAspNetCore();
    });

api server:

services.AddAuthentication(options =>
{
    options.DefaultScheme
      = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
    //options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    //options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
});

// Register the OpenIddict validation components.
services.AddOpenIddict()
  .AddValidation(options =>
  {
            // Note: the validation handler uses OpenID Connect discovery
            // to retrieve the address of the introspection endpoint.
            options.SetIssuer("https://localhost:7236/");
  options.AddAudiences("api_service");//"mvc");// 

      // Configure the validation handler to use introspection and register the client
      // credentials used when communicating with the remote introspection endpoint.
      options.UseIntrospection()
                   .SetClientId("api_service")
                   .SetClientSecret("my-api-secret");

            // Register the System.Net.Http integration.
            options.UseSystemNetHttp();

            // Register the ASP.NET Core host.
            options.UseAspNetCore();
  });

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
