### ISSUE TITLE
Using the Encryption Key for access token decryption

### ISSUE THREAD

**Issue by tmccal2** [openiddict/openiddict-core#1372]
So, it does seem that OIDC access tokens will be encrypted by default unless I add `DisableAccessTokenEncryption()`.

How would a client be able to verify or decrypt the access token? Would they need to send the token to the OIDC server or how would they be able to obtain the decryption key?

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
