### ISSUE TITLE
Couldn't install OpenIddict.AspNetCore nuget package

### ISSUE THREAD

**Issue by dsuryd** [openiddict/openiddict-core#1375]
I was trying to follow the "Getting started" steps but couldn't do the first step to add the nuget package.
The IDE has this error:
```
Cycle detected. 
OpenIddict -> OpenIddict.AspNetCore 3.1.1 -> OpenIddict (>= 3.1.1).
```

**Comment by dsuryd** [comment]
Never mind, the fault's at my end.

**Comment by kevinchalet** [comment]
Don’t hesitate to share additional details. It may help people impacted by a similar issue in the future.

**Comment by dsuryd** [comment]
It's a silly thing.  I happened to name my test project "OpenIddict" which apparently Nuget didn't like as the name clashed with the other package this one depends on.
