### ISSUE TITLE
How do you setup and retrieve encryption and signing certificates in IIS?

### ISSUE THREAD

**Issue by TomTomDam** [openiddict/openiddict-core#1377]
Hello, I am new to OpenIddict and authorization in general, I am having trouble storing and retrieving the encryption and signing certificates that will be used by OpenIddict. I will be deploying this as a production-ready app to IIS.

I would like to know how I would go about storing the certificates in IIS and then retrieving them in my app startup?
Here are the two methods I need to use in Startup.ConfigureServices:
```
options.AddEncryptionCertificate();
options.AddSigningCertificate();
```
I created both of these certificates manually using the code you have provided in [this link](https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-certificate-recommended-for-production-ready-scenarios), then writing them to .pfx files.

I then used the certificate import wizard to import the certificates to my host computer which is also running IIS. But right now I am confused on how to retrieve these certificates from IIS storage when calling options.Add_Certificate(). Right now I can retrieve the certificate directly from the project folder but this seems quite unsafe to have the certificates sitting in the folder.

Thank you

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

Thanks.
