### ISSUE TITLE
SSO with openiddict

### ISSUE THREAD

**Issue by feededit** [openiddict/openiddict-core#1378]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

When a user logs in from site https://www.siteA.com, an authentication cookie is recorded.

I want to read this authentication cookie from site https://www.siteB.com using User.Identity.Name.

How should I configure Program.cs(ASP.NET CORE 6.0) of Site https://www.siteA.com and Site https://www.siteB.com ?

<h3>
Program.cs
</h3>

```
using AuthorizationServer.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<DbContext>(options =>
{
    options.UseInMemoryDatabase(nameof(DbContext));
    options.UseOpenIddict();
});

builder.Services.AddOpenIddict()

    .AddCore(options =>
    {
            options.UseEntityFrameworkCore()
            .UseDbContext<DbContext>();
    })

    .AddServer(options =>
    {
        options
            .AllowClientCredentialsFlow();

        options
            .SetTokenEndpointUris("/connect/token");

            options
            .AddEphemeralEncryptionKey()
            .AddEphemeralSigningKey();

            options.RegisterScopes("api");

           options
            .UseAspNetCore()
            .EnableTokenEndpointPassthrough();
    });

builder.Services.AddHostedService<TestData>();
builder.Services.AddControllersWithViews();

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
    {
        options.LoginPath = "/account/login";
    });

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();

app.UseEndpoints(endpoints =>
{
    endpoints.MapDefaultControllerRoute();
});


app.Run();


```

**Comment by kevinchalet** [comment]
Hey @feededit,

Thanks for sponsoring the project!

> I want to read this authentication cookie from site https://www.siteB.com using User.Identity.Name.

As you probably figured out, reading authentication cookies across domains is impossible as-is and that's why cross-domain protocols like OpenID Connect exist, so that each domain can create its own local cookie, based on authentication exchanged with the identity provider.

Assuming both web applications are based on ASP.NET Core, you'll want to take a look at [the Velusia sample in the samples repository](https://github.com/openiddict/openiddict-samples/tree/dev/samples/Velusia):
  - The identity provider (that would correspond to your siteA.com app) uses ASP.NET Core with Identity as the membership stack and the default Identity UI that manages its own authentication cookies under the hood.
  - The client (that would correspond to your siteB.com app) uses ASP.NET Core and the OIDC handler to communicate with the identity provider, using the classical authorization code flow.

Let me know if you need additional details! 😃

**Comment by feededit** [comment]
thank you.
 
I reviewed the example you provided.
I didn't have time, so I wanted to finish SSO quickly and move on to something else. 
But after reviewing the examples, I had fun and changed my mind. 
I discovered an exciting new world. 
Please wait a few days. 
I'm going to do some tests with examples. 
I'll review and then ask a question. 
 
Is there any paid or open [ openiddict identity ID scaffolding ]? 
 
 
 
-----Original Message-----

**Comment by kevinchalet** [comment]
> Is there any paid or open [ openiddict identity ID scaffolding ]?

No (at least, not yet, but it's a popular demand, so it may happen at some point 😃).
The best approach is to simply copy the authorization controller from the sample that matches your scenario (Velusia in your case) and tweak it if you need something specific.

Cheers.

**Comment by feededit** [comment]
Velusia.Server works fine on https://localhost:44313/ but not on https://www/siteA.com.


The error screen is shown below.

```
HTTP Error 500.30 - ASP.NET Core app failed to start
Common solutions to this issue:
The app failed to start
The app started but then stopped
The app started but threw an exception during startup
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=202826

```


<h3>The environment of https://www/siteA.com is as follows.</h3>

1. Server: 2012
2. IIS: 8

3. appsettings.json:

```
"DefaultConnection": "Data Source=115.68.108.76;Initial Catalog=Openidtest;USER ID=forum;PASSWORD=XXXXXXXXXX;trustServerCertificate=true;"   
```


<h3>Specific symptoms are as follows.</h3>

1. It works fine for https://localhost:44313/ but
2. It does not work on https://www/siteA.com
3. If Startup.cs is deleted as shown below, the main screen is executed in the browser.
 ```
  .AddServer(options => { .... } //delete
  services.AddHostedService<Worker>(); //delete

```


Do you have any guesses as to the cause of this problem?

What does the sentence below mean?

```
        // Register the worker responsible of seeding the database.
        // Note: in a real world application, this step should be part of a setup script.

```

**Comment by feededit** [comment]
Velusia.Server works fine on https://localhost:44313/ but not on https://www/siteA.com.
The error screen is shown below.
HTTP Error 500.30 - ASP.NET Core app failed to start Common solutions to this issue: The app failed to start The app started but then stopped The app started but threw an exception during startup Troubleshooting steps: Check the system event log for error messages Enable logging the application process' stdout messages Attach a debugger to the application process and inspect For more information visit: https://go.microsoft.com/fwlink/?LinkID=202826
The environment of https://www/siteA.com is as follows.

Server: 2012

IIS: 8

appsettings.json:


"DefaultConnection": "Data Source=115.68.108.76;Initial Catalog=Openidtest;USER ID=forum;PASSWORD=XXXXXXXXXX;trustServerCertificate=true;"
Specific symptoms are as follows.

It works fine for https://localhost:44313/ but
It does not work on https://www/siteA.com
If Startup.cs is deleted as shown below, the main screen is executed in the browser.

.AddServer(options => { .... } //delete services.AddHostedService<Worker>(); //delete
{ .... } //delete services.AddHostedService(); //delete " tabindex="0" role="button" style="box-sizing: border-box; position: relative; display: inline-block; line-height: 20px; white-space: nowrap; vertical-align: middle; cursor: pointer; user-select: none; border-width: 1px; border-style: solid; border-color: var(--color-btn-border); border-image: initial; border-radius: 6px; appearance: none; color: var(--color-btn-text); background-color: var(--color-btn-bg); box-shadow: var(--color-btn-shadow),var(--color-btn-inset-shadow); transition: color 0.2s cubic-bezier(0.3, 0, 0.5, 1) 0s, background-color 0s ease 0s, border-color 0s ease 0s; padding: 0px !important; margin: 8px !important;">
Do you have any guesses as to the cause of this problem?
What does the sentence below mean?
// Register the worker responsible of seeding the database. // Note: in a real world application, this step should be part of a setup script.

 
 
 
-----Original Message-----

**Comment by kevinchalet** [comment]
> What does the sentence below mean?

The samples all use a worker to initialize the database. This is a bit crude and something you wouldn't want in a production app, where the database would be already populated.

> Do you have any guesses as to the cause of this problem?

Hard to say as the error you shared is a very generic error returned by the ASP.NET Core module when something wrong happens when booting the app.

Can you please take a look at the Windows Events if you see anything interesting? (in the Applications tab IIRC)

If I had to guess, I'd say that's caused by the calls to `AddDevelopment*Certificate()`, that are not expected to work in production and will typically throw an exception on Azure and on-premise IIS deployments. You can temporarily replace by `AddEphemeral*Key()` or generate real certificates: https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-certificate-recommended-for-production-ready-scenarios

**Comment by feededit** [comment]
Thanks for your kind guidance, authentication sharing between the two sites works well.
 
I am trying to use Openiddiict for sharing authentication between htts://www.siteA.com and htts://www.siteB.com.
 
 
Before starting Openiddiict, there was no problem in sharing authentication between subdomains.
 
From now on, the authentication sharing method between subdomains will not work.
 
Below is what I have modified Startup.cs, it is not working.
 
```
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddCookie(options =>
{
    options.LoginPath = "/login";
    options.ExpireTimeSpan = TimeSpan.FromMinutes(50);
    options.SlidingExpiration = false;
    options.Cookie.Domain = ".feededit.com";
    options.Cookie.Name = ".ASPXAUTH";
 
})
 
 
```
 
 
 
How can htts://www.siteA.com share authentication with subdomains?
-----Original Message-----

**Comment by feededit** [comment]
Thanks for your kind guidance, authentication sharing between the two sites works well.

I am trying to use Openiddict for sharing authentication between htts://www.siteA.com and htts://www.siteB.com.


Before starting Openiddict, there was no problem in sharing authentication between subdomains.

From now on, the authentication sharing method between subdomains will not work.

Below is what I have modified Startup.cs, it is not working.

```
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddCookie(options =>
{
    options.LoginPath = "/login";
    options.ExpireTimeSpan = TimeSpan.FromMinutes(50);
    options.SlidingExpiration = false;
    options.Cookie.Domain = ".siteA.com";
    options.Cookie.Name = ".ASPXAUTH";

})


```



How can htts://www.siteA.com share authentication with subdomains?

**Comment by kevinchalet** [comment]
> Before starting Openiddict, there was no problem in sharing authentication between subdomains.

OpenIddict itself doesn't manage cookies, so it's likely unrelated. The Velusia sample uses ASP.NET Core Identity, that manages its own cookies so if you use it, make sure you configure the cookie options using `services.Services.ConfigureApplicationCookie(...)`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.configureapplicationcookie?view=aspnetcore-6.0

**Comment by feededit** [comment]
You can see that the authentication cookie is written from subdomain.site.com to site.com.




But User.Identity.Name is not readable.

I have one incomprehensible question about authentication cookies.
For subdomain.site.com, the authentication cookie is written to site.com, but why can't User.Identity.Name read it?

**Comment by kevinchalet** [comment]
First, we'll need to determine whether the authentication cookie is correctly read. It's possible that the name property is null because the claim was not returned by your authorization server or because it was not persisted by the OIDC middleware when the cookie was created.

Could you please share your ASP.NET Core logs?

**Comment by feededit** [comment]
I can't find the  ASP.NET Core logs.

Please link to help on how to create ASP.NET Core logs.

**Comment by kevinchalet** [comment]
> Please link to help on how to create ASP.NET Core logs.

Sure. Here's the documentation for the logging stack: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0

**Comment by feededit** [comment]
<h3> 
HomeController.cs
</h3>

```
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace coky.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var claims = new List<Claim> { new Claim(ClaimTypes.Name, "Username") };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));
            return RedirectToAction(nameof(HomeController.about), "Home");      //refresh
        }

        public IActionResult about()
        {
            ViewBag.username = User?.Identity?.Name;
            return View();
        }
    }
}

```

Why can't I set Program.cs like below?

```
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
    {
        options.LoginPath = "/";
        options.Cookie.Domain = ".site.com";
    });

```

**Comment by kevinchalet** [comment]
> Why can't I set Program.cs like below?

You can definitely do that and it should be enough to share your authentication cookie between your main site - acting as the OIDC client in the scenario we discussed - and the subdomain.

If it doesn't work, then there are many possible root causes:
  - The authentication cookie can be read by both your client.com and subdomain.client.com apps but the name claim is lost in the process so `User.Identity.Name` returns null.

  - The authentication cookie can't be read by the subdomain.client.com app. You didn't say what kind of app your third app was, but assuming it's an ASP.NET Core application, you must also configure ASP.NET Core Data Protection to share the same key ring and the same application name as your client.com. This process is described here: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#persistkeystofilesystem and https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0#setapplicationname. If your subdomain.client.com application is hosted on the same IIS machine and uses the same worker account, you can keep using the default registry store. More info at https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-6.0.

That said, if you're looking for a different approach that doesn't involve sharing cookies between your client.com and subdomain.client.com apps, you can also treat subdomain.client.com as another OIDC client, with its own authentication cookie that won't be shared with the main domain.

If you're still blocked, consider posting minimal projects matching your solution on GitHub (possibly on a private repo) and I'll happily take a look 😃

**Comment by feededit** [comment]
Thank you for your kindness.
I will peruse and study your answer.

Your answer is the answer to my final problem, but this time the above question is all.
For the my question above, the question and the code required for the question are very simple.

above source  is the all source.

Just create a new project and copy-paste only the code above.

But there is a problem.
In order for you to do a review, you need a server and a domain name URL.
You must publish on your server.
And you need to create a new subdomain site in your domain in IIS.
Then the browser reads the cookie from the subdomain.sate.com site to see if .site.com is visible in the cookie.

I thought this process was very simple, but looking back, it seems to be very cumbersome for you.
 
sorry!

However, in the case of the above question, I was only curious about basic knowledge,
You can only explain "why not".

**Comment by feededit** [comment]
I solved the problem.
I didn't read the answer carefully.
This topic ends.
I'll be working on SSO for a while and I'll ask another question.
thank you.

**Comment by kevinchalet** [comment]
> Thank you for your kindness.

Thanks for your kind words and for sponsoring the project! 🎉 

I'm glad you got things working. Don't hesitate if you still have any question!

**Comment by feededit** [comment]
Is Hollastin a working sample?
 
I'll use one question if it works

**Comment by kevinchalet** [comment]
> Is Hollastin a working sample?

It is. Feel free to open a bug report if you find anything that doesn't work as it should 😃

**Comment by feededit** [comment]
It may be an bug report, but you should guide me on how to authenticate an asp.net 4.x client to an asp.net core host.

Here are the conditions I tested:

<h3>1. asp.net 4.x</h3>


<h5>HomeController.cs</h5>

```
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var client = new HttpClient();
            const string email = "bob@le-magnifique.com", password = "}s>EWG@f4g;_v7nB";
            await CreateAccountAsync(client, email, password);
            var token = await GetTokenAsync(client, email, password);
            var resource = await GetResourceAsync(client, token);
            ViewBag.resource = resource;
            return View();
        }

        static async Task CreateAccountAsync(HttpClient client, string email, string password)
        {
            var response = await client.PostAsJsonAsync("https://localhost:44360/Account/Register", new { email, password });

            if (response.StatusCode == HttpStatusCode.Conflict)
            {
                return;
            }

            response.EnsureSuccessStatusCode();
        }

        static async Task<string> GetTokenAsync(HttpClient client, string email, string password)
        {
            var configuration = await client.GetDiscoveryDocumentAsync("https://localhost:44360/");
            if (configuration.IsError)
            {
                throw new Exception($"An error occurred while retrieving the configuration document: {configuration.Error}");
            }

            var response = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = configuration.TokenEndpoint,
                UserName = email,
                Password = password
            });

            if (response.IsError)
            {
                throw new Exception($"An error occurred while retrieving an access token: {response.Error}");
            }

            return response.AccessToken;
        }

        static async Task<string> GetResourceAsync(HttpClient client, string token)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, "https://localhost:44360/api/message");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await client.SendAsync(request);
            response.EnsureSuccessStatusCode();

            return await response.Content.ReadAsStringAsync();
        }
    }


```






<h3>2. Modify Hollastin.Server</h3>

<h5>worker</h5>

```
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        await using var scope = _serviceProvider.CreateAsyncScope();

        var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        await context.Database.EnsureCreatedAsync();


        var manager = scope.ServiceProvider.GetRequiredService<IOpenIddictApplicationManager>();

        if (await manager.FindByClientIdAsync("datnet4x") == null)
        {
            await manager.CreateAsync(new OpenIddictApplicationDescriptor
            {
                ClientId = "datnet4x",
                ClientSecret = "901564A5-E7FE-42CB-B10D-61EF3e4656654",
                ConsentType = ConsentTypes.Explicit,
                DisplayName = "client application",
                PostLogoutRedirectUris =
                {
                    new Uri("https://localhost:44362/signout-callback-oidc")
                },
                RedirectUris =
                {
                    new Uri("https://localhost:44362/signin-oidc")
                },
                Permissions =
                {
                    Permissions.Endpoints.Authorization,
                    Permissions.Endpoints.Logout,
                    Permissions.Endpoints.Token,
                    Permissions.GrantTypes.AuthorizationCode,
                    Permissions.GrantTypes.RefreshToken,
                    Permissions.ResponseTypes.Code,
                    Permissions.Scopes.Email,
                    Permissions.Scopes.Profile,
                    Permissions.Scopes.Roles,
                    Permissions.Prefixes.Scope + "demo_api"
                },
                Requirements =
                {
                    Requirements.Features.ProofKeyForCodeExchange
                }
            });
        }


    }

```



<h5>HomeController.cs</h5>

```
        public IActionResult Index()
        {

            ViewBag.Title = User.Identity.Name;

            return View();
        }

```


I have created a new asp.net 4.x project.
And I changed it by pasting the code I copied from Hollastin.Client into it.

No authentication cookie is created on the host and asp.net 4.x.

**Comment by kevinchalet** [comment]
Your configuration is inconsistent: your client uses the resource owner password credentials grant (ROPC) while the server is configured to only allow the authorization code and refresh token grants for the `datnet4x` application.

To fix that, you'll need to either:
  1. Update your client to use the authorization code flow. You can use Katana's OIDC middleware for that: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-asp-webapp (the tutorial mentions response_type=code id_token, but native support for response_type=code was added in recent versions). It's the option I'd recommend.

  2. Update the client registration to allow the ROPC flow (i.e add `Permissions.GrantTypes.Password`). It works but the ROPC flow is not recommended these days as it requires passing the user password to the client.

**Comment by feededit** [comment]
**_To fix that, you'll need to either:_**


If asp.net4.x is fixed, can the fixed asp.net4.x connect with Hollastin.Server?


I'll make a new post for the next question that follows.

My writing is translated by google, so please be generous with the unnaturalness of my writing.
