### ISSUE TITLE
Fix the introspection/userinfo endpoints to support client application tokens 

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#138]
This check currently prevents validating access tokens issued during a `grant_type=client_credentials` token request (i.e access tokens representing a client app):

``` csharp
var user = await services.Users.GetUserAsync(context.Ticket.Principal);
if (user == null) {
    services.Logger.LogInformation("The token {Identifier} was declared as inactive because the " +
                                   "corresponding user ({Username}) was not found in the database.",
                                   context.Ticket.GetTicketId(), services.Users.GetUserName(context.Ticket.Principal));

    context.Active = false;

    return;
}
```

We could simply remove this check, but I wonder if we shouldn't adopt a more general approach distinguishing tokens representing apps and tokens representing users.

/cc @ilmax

**Comment by kevinchalet** [comment]
Title updated, as it also impacts the userinfo endpoint. We should decide if we allow using "app access tokens" with the userinfo endpoint. If we think we shouldn't, we'll have to return a better error message.

**Comment by ilmax** [comment]
I like the second option to distinguish between apps and user tokens, and make this check smarter. 

About allowing "app access tokens" in the userinfo endpoint I cannot find nothing preventing this from the specs, but shouldn't be that useful. No strong opinion.

**Comment by kevinchalet** [comment]
Closing, as the userinfo endpoint is no longer provided by OpenIddict itself.
