### ISSUE TITLE
Startup.cs configuration for authorization code flow

### ISSUE THREAD

**Issue by feededit** [openiddict/openiddict-core#1380]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

```
To fix that, you'll need to either:

Update your client to use the authorization code flow. You can use Katana's OIDC middleware for that: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-asp-webapp (the tutorial mentions response_type=code id_token, but native support for response_type=code was added in recent versions). It's the option I'd recommend.

Update the client registration to allow the ROPC flow (i.e add Permissions.GrantTypes.Password). It works but the ROPC flow is not recommended these days as it requires passing the user password to the client.
```

How should i write Startup.cs of asp.net4.x to configure the client to use the authorization code flow?

**Comment by kevinchalet** [comment]
As mentioned in the other thread, you'll need to reference the OWIN OIDC middleware, similarly to what you'd do for an ASP.NET Core application. Then, you'll need to configure it use your authorization server. Something like that should work:

```csharp
app.SetDefaultSignInAsAuthenticationType("ClientCookie");

// Insert a new cookies middleware in the pipeline to store the user
// identity after he has been redirected from the identity provider.
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationMode = AuthenticationMode.Active,
    AuthenticationType = "ClientCookie",
    CookieName = CookieAuthenticationDefaults.CookiePrefix + "ClientCookie",
    ExpireTimeSpan = TimeSpan.FromMinutes(5)
});

// Insert a new OIDC client middleware in the pipeline.
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
    AuthenticationMode = AuthenticationMode.Active,

    // Note: setting the Authority allows the OIDC client middleware to automatically
    // retrieve the identity provider's configuration and spare you from setting
    // the different endpoints URIs or the token validation parameters explicitly.
    Authority = "https://localhost:44313/",
    RequireHttpsMetadata = false,

    // Note: these settings must match the application details inserted in
    // the database at the server level (see ApplicationContextInitializer.cs).
    ClientId = "mvc",
    ClientSecret = "901564A5-E7FE-42CB-B10D-61EF6A8F3654",
    RedirectUri = "https://localhost:44338/signin-oidc",
    PostLogoutRedirectUri = "https://localhost:44338/signout-callback-oidc",

    ResponseType = "code",
    Scope = "openid email roles",

    SecurityTokenValidator = new JwtSecurityTokenHandler
    {
        // Disable the built-in JWT claims mapping feature.
        InboundClaimTypeMap = new Dictionary<string, string>()
    },

    TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    },

    // Note: by default, the OIDC client throws an OpenIdConnectProtocolException
    // when an error occurred during the authentication/authorization process.
    // To prevent a YSOD from being displayed, the response is declared as handled.
    Notifications = new OpenIdConnectAuthenticationNotifications
    {
        AuthenticationFailed = notification =>
        {
            if (string.Equals(notification.ProtocolMessage.Error, "access_denied", StringComparison.Ordinal))
            {
                notification.HandleResponse();

                notification.Response.Redirect("/");
            }

            return Task.CompletedTask;
        },

        // Attach the id_token stored in the authentication cookie to the logout request.
        RedirectToIdentityProvider = notification =>
        {
            if (notification.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
            {
                var token = notification.OwinContext.Authentication.User?.FindFirst(OpenIdConnectParameterNames.IdToken);
                if (token != null)
                {
                    notification.ProtocolMessage.IdTokenHint = token.Value;
                }
            }

            return Task.CompletedTask;
        }
    }
});
```

Let me know how it goes 😄

**Comment by feededit** [comment]
thank you.
The login was successful.
I used the examples from the microsoft identity help.


Now I have two problems.

<h3>1. RedirectUri</h3>

Always only the RedirectUri recorded in the server's DB is returned.


I would like to do something like below.

```
 string reurl = "/home/about";
 HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = reurl }, OpenIdConnectAuthenticationDefaults.AuthenticationType);

```


<h3>2. Problems with authentication cookies.</h3>

I'd like to use the User.Identity.Name() written on my old site without having to modify it.
How to put [System.Security.Claims.ClaimsPrincipal.Current.FindFirst("name").Value] into [User.Identity.Name()]?

**Comment by kevinchalet** [comment]
> Always only the RedirectUri recorded in the server's DB is returned.
> I would like to do something like below.

That should work: despite having the same as the OIDC authorization request parameter, the `AuthentiationProperties.RedirectUri` is not related to the `redirect_uri` registered with your authorization server: you can set any value and the MSFT OIDC middleware should handle the redirection for you 😃 

> How to put [System.Security.Claims.ClaimsPrincipal.Current.FindFirst("name").Value] into [User.Identity.Name()]?

You'll first need to ensure the `name` claim is present in the identity tokens returned by the authorization server (so it must have the "id_token" destination: https://documentation.openiddict.com/configuration/claim-destinations.html).

**Comment by feededit** [comment]
> Update the client registration to allow the ROPC flow (i.e add Permissions.GrantTypes.Password). It works but the ROPC flow is not recommended these days as it requires passing the user password to the client.


Is it possible  after the client passes the name (email) and password to the host, the host passes an AspNetUsers ID to the client instead of the password?

**Comment by kevinchalet** [comment]
Technically, OpenIddict doesn't have any restriction on what represents the "password" parameter in the ROPC flow. That said, passwords should be hard to guess and I don't think a user ID meets this requirement.

**Comment by feededit** [comment]
> You'll first need to ensure the name claim is present in the identity tokens returned by the authorization server (so it must have the "id_token" destination: https://documentation.openiddict.com/configuration/claim-destinations.html).


In the Velusia example, Velusia.Client connected to Velusia.Server and authenticated successfully, so **Welcome, @User.Identity.Name** appeared in /home/index at Velusia.Client 

My aspnet4x client set **authorization code flow** in Startup.cs to connect to the Velusia.Server host and successfully authenticated.

Why do my aspnet4x and Velusia.Server need to set [Claim destinations](https://documentation.openiddict.com/configuration/claim-destinations.html)?

**Comment by kevinchalet** [comment]
> Why do my aspnet4x and Velusia.Server need to set Claim destinations?

It's not specific to the Velusia sample: all servers based OpenIddict need to use claim destinations, for security reasons.
In the Velusia server sample (that uses ASP.NET Core Identity), it's done here: https://github.com/openiddict/openiddict-samples/blob/dev/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs#L353-L359

**Comment by feededit** [comment]
The code below should be modified to aspnet 4X version.

![6](https://user-images.githubusercontent.com/97811439/152562567-392f218a-e659-4353-a2a6-6b75956c949d.png)


```

        public void SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        public void SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut( OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
        }



```





Is it possible to write **[AuthenticationController.cs]** in aspnet 4X version?

**Comment by kevinchalet** [comment]
> Is it possible to write [AuthenticationController.cs] in aspnet 4X version?

Yes. What you have should just work fine. Are you seeing any issue?

**Comment by feededit** [comment]
I found that my old site is impossible to migrate to core 6.
So I need openiddict for aspnet 4x.
Please make  [AuthenticationController.cs]  below for aspnet4x.

```

public class AuthenticationController : Controller
{
    [HttpGet("~/login")]
    public ActionResult LogIn()
    {
        return Challenge(new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectDefaults.AuthenticationScheme);
    }

    [HttpGet("~/logout"), HttpPost("~/logout")]
    public ActionResult LogOut()
    {
        // is redirected from the identity provider after a successful authorization flow and
        // to redirect the user agent to the identity provider to sign out.
        return SignOut(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
    }
}


```

**Comment by kevinchalet** [comment]
> So I need openiddict for aspnet 4x.

"ASP.NET 4.x" is fairly vague: do you mean ASP.NET 4.x Web Forms (with the .aspx pages), ASP.NET MVC 4.x or something else?

Here's an example for ASP.NET MVC 4.x:

```csharp
public class AuthenticationController : Controller
{
    [HttpGet, Route("~/login")]
    public ActionResult LogIn()
    {
        var properties = new AuthenticationProperties
        {
            RedirectUri = "/"
        };

        HttpContext.GetOwinContext().Authentication.Challenge(properties,
            OpenIdConnectAuthenticationDefaults.AuthenticationType);

        return new EmptyResult();
    }

    [AcceptVerbs("GET", "POST"), Route("~/logout")]
    public ActionResult LogOut()
    {
        HttpContext.GetOwinContext().Authentication.SignOut(
            CookieAuthenticationDefaults.AuthenticationType,
            OpenIdConnectAuthenticationDefaults.AuthenticationType);

        return new EmptyResult();
    }
}
```

For ASP.NET 4.x Web Forms, it's also very similar. Here's how you could do with 2 buttons triggering a challenge/sign-out:

```asp
<%@ Page Title="Authenticate" Async="true" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Authenticate.aspx.cs" Inherits="DemoApp.Authenticate" %>

<asp:Content runat="server" ID="Content1" ContentPlaceHolderID="MainContent">
    <asp:Button runat="server" OnClick="LogIn" Text="Log in" CssClass="btn btn-lg btn-success" />
    <asp:Button runat="server" OnClick="LogOut" Text="Log out" CssClass="btn btn-lg btn-danger" />
</asp:Content>
```

```csharp
public partial class Authenticate : Page
{
    protected void LogIn(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            return;
        }

        var properties = new AuthenticationProperties
        {
            RedirectUri = "/"
        };

        var context = Context.GetOwinContext();
        context.Authentication.Challenge(properties, OpenIdConnectAuthenticationDefaults.AuthenticationType);
        Visible = false;
    }

    protected void LogOut(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            return;
        }

        var context = Context.GetOwinContext();
        context.Authentication.SignOut(
            CookieAuthenticationDefaults.AuthenticationType,
            OpenIdConnectAuthenticationDefaults.AuthenticationType);
        Visible = false;
    }
}
```

**Comment by feededit** [comment]
In the next question I will ask about data passing in [Challenge].
However, in this question, I will only ask about the authentication cookie that [Challenge] automatically creates.


My problem is not with the 4.x version.
It's a matter of how to write the authentication cookie so that **all subdomains can read it**.

4.x version Startup.cs 


>            app.UseCookieAuthentication(new CookieAuthenticationOptions
>             {
>                 AuthenticationType = CookieAuthenticationDefaults.AuthenticationType,
>                 CookieDomain = ".site.com"
>              }
> 
> _All subdomains can authenticate._






I'm re-posting the  Core6  code I introduced earlier below.

<h5>HomeController.cs</h5>

```
public class HomeController : Controller
    {
        
        public async Task<IActionResult> Index()
        {
            var claims = new List<Claim> { new Claim(ClaimTypes.Name, "See this at Privacy View !") };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));
            return RedirectToAction(nameof(HomeController.Privacy), "Home");      //refresh
        }
        public IActionResult Privacy()
        {
            ViewBag.SeeThisAtView = User?.Identity?.Name;
            return View();
        }

    }

```





<h5>Program.cs</h5>

```
using Microsoft.AspNetCore.Authentication.Cookies;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();

builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
    {
        options.LoginPath = "/";
        options.Cookie.Name = "YouNamedThisCooke";
    });

var app = builder.Build();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
```

At Core6,
[SignInAsync] creates an authentication cookie using [CookieAuthenticationDefaults.AuthenticationScheme] .

but at Aspnet 4.x , 
[UseCookieAuthentication] of Aspnet4.x cannot use [CookieAuthenticationDefaults.AuthenticationScheme].

So subdomain.siteA.com (Aspnet 4.x) cannot SSO with siteB.com (core 6).

**(If you tell me how Aspnet4.x can use [CookieAuthenticationDefaults.AuthenticationScheme] , you don't need to read below.)**



I tried to work around this problem using Aspnet 4.x as the client.
But your code uses [UseCookieAuthentication] like below.


<h3>aspnet 4.x </h3>

```

   app.SetDefaultSignInAsAuthenticationType("ClientCookie");

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationMode = AuthenticationMode.Active,
                AuthenticationType = "ClientCookie",
                CookieName = CookieAuthenticationDefaults.CookiePrefix + "ClientCookie",
                ExpireTimeSpan = TimeSpan.FromMinutes(5),
            });


```





How does it SSO with other subdomains?

**Comment by kevinchalet** [comment]
If I understood you correctly, one of the cookie-based apps uses ASP.NET Core and the other is an ASP.NET 4.x app that relies on the OWIN/Katana cookie authentication middleware?

If so, it won't work natively: ASP.NET Core uses a different data encryption mechanism called ASP.NET Core Data Protection, that replaces the MachineKey stuff you had in ASP.NET 4.x. Also, the ticket data format that is used to format authentication cookies has changed in ASP.NET Core.

If you absolutely want to share cookies between those apps, see https://github.com/dotnet/AspNetCore.Docs/issues/21987#issuecomment-821132315.

https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-6.0#share-authentication-cookies-between-aspnet-4x-and-aspnet-core-apps

Otherwise, consider avoiding sharing cookies and treating them as two separate apps with their own OIDC registration as I suggested earlier.

**Comment by feededit** [comment]
> Otherwise, consider avoiding sharing cookies and treating them as two separate apps with their own OIDC registration as I suggested earlier.


Since Core6 is still based on cookie sharing, it seems that cookie sharing cannot be avoided. Please take the time to study the method in the future.


For treating ASPNET 4x as separate apps with their own OIDC registration,
Please provide a full source sample of Velusia.Client for ASPNET 4x Client version.

**Comment by feededit** [comment]
```

        public void Configuration(IAppBuilder app)
        {

            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());
            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    Authority = "https://login.microsoftonline.com/xxx~xxxxxxxxx~xxxxxxx/v2.0",
                    ClientId = "35306352-030b-41f2-8e7b-e0122e392ffa",
                    RedirectUri = "https://localhost:44378/",
                    PostLogoutRedirectUri = "https://localhost:44378/",
                    Scope = OpenIdConnectScope.OpenIdProfile,
                    ResponseType = OpenIdConnectResponseType.CodeIdToken,
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidateIssuer = false // This is a simplification
                    },
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthenticationFailed = OnAuthenticationFailed
                    }
                }
            );

            app.UseMicrosoftAccountAuthentication(
                clientId: "35306352-030b-41f2-8e7b-e0122e392ffa",
                clientSecret: "xxx~xxxxxxxxx~xxxxxxx");

        }


```





In aspnet 4x, [UseOpenIdConnectAuthentication] and [UseMicrosoftAccountAuthentication] have the same authentication function.


 [UseOpenIdConnectAuthentication] has many features, such as using a profile picture.
But Programmers may want to conserve resources.


```
services.AddAuthentication()
.AddOpenIdConnect("Azure AD / Microsoft", "Azure AD / Microsoft", options =>
{
    options.Authority = "https://login.microsoftonline.com/common/v2.0/";
    options.ClientId = "86c71d32-17e0-4246-9539-827798669ca6";
    options.ClientSecret = "xxx~xxxxxxxxx~xxxxxxx";
    options.SignInScheme = "Identity.External";
    options.RemoteAuthenticationTimeout = TimeSpan.FromSeconds(300);
    options.ResponseType = "code";
    options.UsePkce = false; // live does not support this yet
    options.Scope.Add("profile");
    options.Scope.Add("email");
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = false,
        NameClaimType = "email",
    };
    options.CallbackPath = "/signin-microsoft";
    options.Prompt = "login"; // login, consent
});


```


You recommended [UseOpenIdConnectAuthentication], but I think the programmer should be able to choose.
Even in Core6, there is [Nuget Package].


```
services.AddAuthentication()
    .AddMicrosoftAccount(microsoftOptions =>
{
    microsoftOptions.ClientId = "86c71d32-17e0-4246-9539-827798669ca6";
    microsoftOptions.ClientSecret = "xxx~xxxxxxxxx~xxxxxxx";
});



// Install-Package Microsoft.AspNetCore.Authentication.MicrosoftAccount -Version 6.0.2
//Install-Package Microsoft.AspNetCore.Authentication.Google -Version 6.0.2
//https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-6.0

```




I would like to use it in OPeniddict as well.
how can I get this Nuget Package  ?

**Comment by kevinchalet** [comment]
> In aspnet 4x, [UseOpenIdConnectAuthentication] and [UseMicrosoftAccountAuthentication] have the same authentication function.

No, they don't: the Microsoft Account authentication middleware doesn't implement OIDC and is a simpler OAuth 2.0 middleware, with less security checks than what you have in the OIDC middleware.

If you want to have something equivalent, you'll have to create your own middleware. The code can be found here: https://github.com/aspnet/AspNetKatana/tree/dev/src/Microsoft.Owin.Security.MicrosoftAccount. Of course, it's not something I'd recommend: the OIDC client middleware is much better option.

**Comment by feededit** [comment]
I will use Velusia.Server host .

While all client sites connect to Velusia.Server host with OIDC security authentication,
Is there a way for oldsite.com to connect with Velusia.Server host in less security checks way?

I don't want to know the knowledge to connect OldSite.com to Velusia.Server host.

Anyway, as soon as I finish linking oldsite.com with Velusia.Server host.

and I would like to talk  about OIDC certified connection.

**Comment by feededit** [comment]
> Yes. What you have should just work fine. Are you seeing any issue?


In core6,

After going to [HomeController index] from [AuthenticationController login()], there was code in [HomeController index].


<h3>AuthenticationController</h3>

```
   public ActionResult LogIn()
    {
        return Challenge(new AuthenticationProperties { RedirectUri = "/Id" }, OpenIdConnectDefaults.AuthenticationScheme);
    }
```




<h3>HomeController</h3>

```
public async Task<ActionResult> Index(CancellationToken cancellationToken)
    {
        var token = await HttpContext.GetTokenAsync(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectParameterNames.AccessToken);
        if (string.IsNullOrEmpty(token))
        {
            throw new InvalidOperationException("The access token cannot be found in the authentication ticket. " +
                                                "Make sure that SaveTokens is set to true in the OIDC options.");
        }

        using var client = _httpClientFactory.CreateClient();

        using var request = new HttpRequestMessage(HttpMethod.Get, "https://localhost:44313/api/message");
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

        using var response = await client.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();

        return View("Home", model: await response.Content.ReadAsStringAsync());
    }

```


I had asked you for the complete full source for AspNet4x.
But you haven't given it to me yet.

For AspNet4x,
Please let me know which code should proceed after [AuthenticationController] below .

```
    [HttpGet, Route("~/login")]
    public ActionResult LogIn()
    {
        var properties = new AuthenticationProperties
        {
            RedirectUri = "/"
        };

        HttpContext.GetOwinContext().Authentication.Challenge(properties,
            OpenIdConnectAuthenticationDefaults.AuthenticationType);

        return new EmptyResult();
    }
```

**Comment by feededit** [comment]
Should I wait for your answer?

**Comment by kevinchalet** [comment]
I'm sorry, it's not clear to me what you're asking: it seems like your requirements change all the time.

> I had asked you for the complete full source for AspNet4x.
But you haven't given it to me yet.

As I already said, "AspNet4x" is too vague and can apply to multiple technologies. If you don't define more precisely what you mean, I won't be able to create a sample client matching your needs.

> "ASP.NET 4.x" is fairly vague: do you mean ASP.NET 4.x Web Forms (with the .aspx pages), ASP.NET MVC 4.x or something else?

> I don't want to know the knowledge to connect OldSite.com to Velusia.Server host.

I'm not sure I understand. What's the point of asking questions if you're not interested in the answers?

**Comment by feededit** [comment]
My plan was to migrate my old site to Core6.
But I found that it was impossible.
 
Since then, confusion has arisen for me.
The cause of all my incomprehensible questions that you have felt at online is the confusion that has arisen with me.

My confusion is:

First I want to use openiddick .
Second, to use openiddick, my old site is not compatible with openiddick.
Thirdly, I'm trying to somehow fix the problem with my old site as quickly as possible.

I wondered if I should do this or that, and I asked you many question.
This is where I think you may not have understood my actions.


> I don't want to know the knowledge to connect OldSite.com to Velusia.Server host

It means owin.

sorry.

now, I will explain to you the current progress.

I am concerned that an unknown error will occur when Velusia.Server is modified.
When you first told me this, I was very worried about modifying even a single line of Velusia.Server's code.

```

foreach (var claim in principal.Claims)
{
    claim.SetDestinations(claim.Type switch
    {
        // If the "profile" scope was granted, allow the "name" claim to be
        // added to the access and identity tokens derived from the principal.
        Claims.Name when principal.HasScope(Scopes.Profile) => new[]
        {
            OpenIddictConstants.Destinations.AccessToken,
            OpenIddictConstants.Destinations.IdentityToken
        },

        // Never add the "secret_value" claim to access or identity tokens.
        // In this case, it will only be added to authorization codes,
        // refresh tokens and user/device codes, that are always encrypted.
        "secret_value" => Array.Empty<string>(),

        // Otherwise, add the claim to the access tokens only.
        _ => new[]
        {
            OpenIddictConstants.Destinations.AccessToken
        }
    });
}


```

now, All three places of Velusia.Server AuthorizationController.cs  have been corrected. 
there is no problem.


From now on I will not try to finish quickly.
If you tell me what to do next, I will proceed as you tell me.

I'm sorry if you offended me.

**Comment by kevinchalet** [comment]
> Second, to use openiddick, my old site is not compatible with openiddick.

FYI the OpenIddict server feature can be used in any ASP.NET 4.x application via OWIN/Katana. The Fornax sample demonstrates how to implement that in WebForms: https://github.com/openiddict/openiddict-samples/tree/dev/samples/Fornax

Your case is different: you want your "old site" to act as a client, and in this case, OpenIddict is not used: it's the OWIN OIDC client middleware developed by MSFT that you should use.

> I am concerned that an unknown error will occur when Velusia.Server is modified.
When you first told me this, I was very worried about modifying even a single line of Velusia.Server's code.

Don't be worried about that: OpenIddict is a framework meant to be used to build custom OIDC servers that exactly match your needs. The sample code used in Velusia is just a tiny bit of the authorization processing handling and all validation steps are actually performed by OpenIddict before the code you have in the authorization controller is even invoked.

The chances of introducing a security issue are extremely low.

> I'm sorry if you offended me.

Haha, no worries at all. What matters is that you end up building something that works for you. And for that, I needed to know exactly what was blocking you 😃 

Feel free to keep asking questions if you need help.

**Comment by feededit** [comment]
I want you Please provide Fornax's client application.
The application should be .NET Framework 4.8 MVC.
This code is in feededit/FornaxClient.

**Comment by kevinchalet** [comment]
> This code is in feededit/FornaxClient.

Well, there's no code in that .7zip file: the solution is an empty ASP.NET MVC project... not sure why you put that on a private repository 😅

I opened https://github.com/openiddict/openiddict-samples/issues/188 to add a legacy ASP.NET MVC 5.2 client+server sample. It's going to take some time, so I can't promise it'll be available soon.

**Comment by feededit** [comment]
I haven't figured out how to upload a project yet.
github doesn't allow me to upload more than 26mb.

I finally uploaded the empty project after many tries.
You can ignore the project I uploaded and choose whether it is convenient for you to create a new project or use it.

Please complete the project and hand it over to me.
All I need is a fully functional tested source.

I've told you in a previous post that I have successfully completed a task.
But that's not true.

It was a lack of success.
My problem is that I cannot solve the incompleteness on my own.

There is something I regret about the way I've been asking you questions in the meantime.
To complete the imperfect part, I had to constantly ask you questions.

Not only did it make you tired, but it didn't even solve the problem in the end.
So you should hand over a fully tested project.
Only then will you be comfortable.

**Comment by kevinchalet** [comment]
> I haven't figured out how to upload a project yet.
github doesn't allow me to upload more than 26mb.

When using GitHub (or any other git platform), storing your source code in a zip file is not a common practice. Instead, you're expected to add the individual files to the git structure and in this case, the max size limits are typically not blocking.

> Please complete the project and hand it over to me.
All I need is a fully functional tested source.
I've told you in a previous post that I have successfully completed a task.
But that's not true.
It was a lack of success.
My problem is that I cannot solve the incompleteness on my own.
Not only did it make you tired, but it didn't even solve the problem in the end.

I'm certainly not tired, but to help you the best I can, I need to have a clear view of what's working for you and what's not working. If you're not accurate about that, it's extremely hard to help you 😃 

Anyway, keep an eye on https://github.com/openiddict/openiddict-samples/issues/188. I hope I'll be able to do that later this week.

**Comment by kevinchalet** [comment]
The MVC 5.2 sample can be found here: https://github.com/openiddict/openiddict-samples/blob/dev/samples/Mortis

Closing.
