### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Owin.OwinMiddleware'

### ISSUE THREAD

**Issue by dbakker-uab-online** [openiddict/openiddict-core#1382]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Describe the bug

Trying to use this library with OWIN & Microsoft.Extensions.DependencyInjection (rather than Autofac), throws an exception on application startup:

```
Unable to resolve service for type 'Microsoft.Owin.OwinMiddleware' while attempting to activate 'OpenIddict.Server.Owin.OpenIddictServerOwinMiddleware'.
```

Because `OpenIddictServerOwinMiddleware` and `OpenIddictValidationOwinMiddleware` are registered as Scoped services [here](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Validation.Owin/OpenIddictValidationOwinExtensions.cs#L35) and [here](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server.Owin/OpenIddictServerOwinExtensions.cs#L37).

However, they are never actually resolved through the DI container, as can be seen [here](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server.Owin/OpenIddictServerOwinMiddlewareFactory.cs#L53) and [here](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Validation.Owin/OpenIddictValidationOwinMiddlewareFactory.cs#L53)

---

I currently work around this issue by manually removing those service registrations from the IServiceCollection, after the `AddOpenIddict` call. 

```cs
services.AddOpenIddict(...);
services.RemoveWhere(descriptor => descriptor.ServiceType == typeof(OpenIddictServerOwinMiddleware));
services.RemoveWhere(descriptor => descriptor.ServiceType == typeof(OpenIddictValidationOwinMiddleware));
```

### To reproduce

Register library services in an .NET Framework application with OWIN and using Microsoft.Extensions.DependencyInjection (rather than Autofac.)

### Exceptions (if any)

```shell
Unable to resolve service for type 'Microsoft.Owin.OwinMiddleware' while attempting to activate 'OpenIddict.Server.Owin.OpenIddictServerOwinMiddleware'.
```

**Comment by kevinchalet** [comment]
The bot didn't recognize you as a sponsor. Did you sponsor the project using a different GitHub account?
