### ISSUE TITLE
Access token validation fails for GRPC-Web service: missing_token

### ISSUE THREAD

**Issue by danielleiszen** [openiddict/openiddict-core#1385]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Describe the bug

I have a modified version of the Zirku sample. The modifications are:
- I use the password flow with bearer tokens
- I replaced the /authorization endpoint with the /token endpoint but the basic logic is the same
- I use a Grpc service as a resource with EnableGrpcWeb since I am calling it from a Flutter WebApp.
- I have only one resource which is the Api2 in the sample with shared encryption key.

I have a working scenario from a C# client and a non working scenario from Flutter, however they used to work in previous versions.

The scenario: 
1. client gets the token from the /token endpoint (success)
2. client calls the /api endpoint on the same server, that requires authorization (success)
3. client calls the Greeter Grpc service on the resource server, requires authorization (success)

The same scenario works for the C# client - all 3 steps, but does not work for the Flutter client: the 3. step fails.
So both clients get the token and succeeds to call an authorized resource endpoint. However the flutter client cannot call the Grpc endpoint because its bearer token is not picked up by the infrastructure. I could not debug it further.

With the C# client the headers sent are visible from the grpc call context:

```
user-agent grpc-dotnet/2.42.0 (.NET 6.0.1; CLR 6.0.1; net6.0; windows; x64)
authorization Bearer eyJhb .. .haBU
traceparent 00-72844bcf9a07ee977bc6d7e848f3a789-19a5d689ab2345ce-00
```

If the authorization requirement is removed from the Grpc service, both clients can call the endpoint. Then the Flutter client sends the following headers:

```
accept */*
user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
accept-language en-GB,en-US;q=0.9,en;q=0.8
authorization Bearer eyJh ... aZCY
origin http://localhost:61056
referer http://localhost:61056/
content-length 11
sec-ch-ua " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
x-user-agent grpc-web-dart/0.1
sec-ch-ua-mobile ?0
x-grpc-web 1
sec-ch-ua-platform "Windows"
sec-fetch-site cross-site
sec-fetch-mode cors
sec-fetch-dest empty
```
So, in both cases the headers are there and the Grpc infrastructure is capable of picking them up. However the authorization logic does not recognize the bearer token sent from the Flutter client.

### To reproduce

Please see the following repo

https://github.com/danielleiszen/MissingTokenIssue

### Exceptions (if any)

```shell
OpenIddict.Validation.OpenIddictValidationDispatcher: Information: The response was successfully returned as a challenge response: {
  "error": "missing_token",
  "error_description": "The security token is missing.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2000"
}.

Thank you.
```

**Comment by kevinchalet** [comment]
The Flutter SDK is a huge mess (2GB to unzip, WTF?) so before I spend time on that, can you first try to move `app.UseGrpcWeb()` before `app.UseAuthentication()` and see if it makes any difference?

**Comment by danielleiszen** [comment]
Sure thing. It's also fine by me to try other combinations or dig deeper if I can.

**Comment by danielleiszen** [comment]
That was the problem.  I cannot believe this. Thank you.
However maybe that would be worth to mention something in the documentation about it. Because it is not obvious that the order of these commands matter. Had I knew it, I would have played with the order.

Furthermore it is not clear for me why does this work with the C# client and does not with the Flutter client.
Is it possible to debug the actual logic that handles token extraction? Because it seems that the token itself is in the request header.

**Comment by kevinchalet** [comment]
> However maybe that would be worth to mention something in the documentation about it. Because it is not obvious that the order of these commands matter. Had I knew it, I would have played with the order.

Even if the ASP.NET folks try their best to hide that in the new minimal host, the order of middleware is very important and it has a noticeable impact on how things are handled. E.g for all ASP.NET Core apps, `app.UseAuthorization()` must come after `app.UseAuthentication()`. When using the OpenIddict server feature, it's recommended to have things like CORS or HSTS before `app.UseAuthentication()`, etc.

In this particular case, I suspect the gRPC-web stuff has special code to convert requests sent by browsers (that can't use things like trailing headers natively) to something the classical gRPC layer can handle. It's possible headers are impacted by that.

If you have a minute, please trying adding the following event handler to your resource API config to see if the authorization handler can be extracted from the `HttpRequest` instance:

```csharp
services.AddOpenIddict()
    .AddValidation(options =>
    {
        // ... your existing validation configuration

        options.AddEventHandler<OpenIddictValidationEvents.ProcessAuthenticationContext>(builder =>
        {
            builder.UseInlineHandler(context =>
            {
                var request = context.Transaction.GetHttpRequest();
                Debug.WriteLine("Authorization header: " + request.Headers.Authorization.ToString());

                return default;
            });

            builder.SetOrder(ExtractAccessTokenFromAuthorizationHeader.Descriptor.Order + 1);
        });
    });
```

**Comment by danielleiszen** [comment]
This is the full log. I removed the symbol loading stuff and segmented for readability.

--- WORKING SCENARIO FROM C# CLIENT -----------

--- ANONYMOUS CALL TO C# LOGIC -------

Request OPTIONS:/greet.Auth/Login, Authorization header: 
Request POST:/greet.Auth/Login, Authorization header: 

--- CALLING TOKEN ENDPOINT FROM C# CLIENT ----

OpenIddict.Server.OpenIddictServerDispatcher: Information: The request address matched a server endpoint: Token.

OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was successfully extracted: {
  "grant_type": "password",
  "client_id": "client",
  "client_secret": "[redacted]",
  "username": "user",
  "password": "[redacted]",
  "scope": "openid profile email custom roles"
}.

SELECT [o].[Id], [o].[ConcurrencyToken], [o].[Description], [o].[Descriptions], [o].[DisplayName], [o].[DisplayNames], [o].[Name], [o].[Properties], [o].[Resources]
FROM [OpenIddictScopes] AS [o]
WHERE [o].[Name] = N'custom'

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[ClientId] = @__identifier_0
OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was successfully validated.

SELECT [o].[Id], [o].[ConcurrencyToken], [o].[Description], [o].[Descriptions], [o].[DisplayName], [o].[DisplayNames], [o].[Name], [o].[Properties], [o].[Resources]
FROM [OpenIddictScopes] AS [o]
WHERE [o].[Name] IN (N'openid', N'profile', N'email', N'custom', N'roles')

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[Id] = @__key_0

SET NOCOUNT ON;
INSERT INTO [OpenIddictTokens] ([Id], [ApplicationId], [AuthorizationId], [ConcurrencyToken], [CreationDate], [ExpirationDate], [Payload], [Properties], [RedemptionDate], [ReferenceId], [Status], [Subject], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[Id] = @__key_0

SET NOCOUNT ON;
INSERT INTO [OpenIddictTokens] ([Id], [ApplicationId], [AuthorizationId], [ConcurrencyToken], [CreationDate], [ExpirationDate], [Payload], [Properties], [RedemptionDate], [ReferenceId], [Status], [Subject], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);

OpenIddict.Server.OpenIddictServerDispatcher: Information: The response was successfully returned as a JSON document: {
  "access_token": "[redacted]",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "[redacted]"
}.

--- CALLING API ENDPOINT FROM C# CLIENT ----
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request GET https://localhost/api
System.Net.Http.HttpClient.Default.ClientHandler: Information: Sending HTTP request GET https://localhost/api

--- AUTHORIZED API CALLED BY BOB --- 

--- CALLING GRPC ENDPOINT FROM C# CLIENT ----

Request POST:/greet.Greeter/SayHello, Authorization header: Bearer eyJh ... SDGJB-k

System.Net.Http.HttpClient.OpenIddict.Validation.SystemNetHttp.LogicalHandler: Information: Start processing HTTP request GET https://localhost/.well-known/openid-configuration
System.Net.Http.HttpClient.OpenIddict.Validation.SystemNetHttp.ClientHandler: Information: Sending HTTP request GET https://localhost/.well-known/openid-configuration
OpenIddict.Server.OpenIddictServerDispatcher: Information: The request address matched a server endpoint: Configuration.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The configuration request was successfully extracted: {}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The configuration request was successfully validated.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The response was successfully returned as a JSON document: {
  "issuer": "https://localhost/",
  "authorization_endpoint": "https://localhost/authorize",
  "token_endpoint": "https://localhost/token",
  "introspection_endpoint": "https://localhost/introspect",
  "jwks_uri": "https://localhost/.well-known/jwks",
  "grant_types_supported": [
    "password"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "profile",
    "offline_access",
    "roles",
    "address",
    "phone"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "claims_parameter_supported": false,
  "request_parameter_supported": false,
  "request_uri_parameter_supported": false
}.

System.Net.Http.HttpClient.OpenIddict.Validation.SystemNetHttp.LogicalHandler: Information: Start processing HTTP request GET https://localhost/.well-known/jwks
System.Net.Http.HttpClient.OpenIddict.Validation.SystemNetHttp.ClientHandler: Information: Sending HTTP request GET https://localhost/.well-known/jwks
OpenIddict.Server.OpenIddictServerDispatcher: Information: The request address matched a server endpoint: Cryptography.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The cryptography request was successfully extracted: {}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The cryptography request was successfully validated.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The response was successfully returned as a JSON document: {
  "keys": [
    {
      "kid": "0746E3E9F2F754722E106664F5B5C84F7DBFB08B",
      "use": "sig",
      "kty": "RSA",
      "alg": "RS256",
      "e": "AQAB",
      "n": "wC_DtBm ... Q1Q",
      "x5t": "B0bj6fL3VHIuEGZk9bXIT32_sIs",
      "x5c": [
        "MIIC9 ... kxWY="
      ]
    }
  ]
}.

--- START GRPC METHOD ----
HEADER: user-agent = grpc-dotnet/2.42.0 (.NET 6.0.1; CLR 6.0.1; net6.0; windows; x64)
HEADER: authorization = Bearer eyJh ... GJB-k
HEADER: traceparent = 00-9fcfb1c6675b7c86dd959592d28c0b99-9a15560dffb25fb7-00
--- END GRPC METHOD ----


--- END OF WORKING SCENARIO ----

--- NON WORKING SCENARIO FROM FLUTTER CLIENT ----
 
--- CALLING TOKEN ENDPOINT FROM FLUTTER CLIENT ---- 

OpenIddict.Server.OpenIddictServerDispatcher: Information: The request address matched a server endpoint: Token.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was successfully extracted: {
  "grant_type": "password",
  "client_id": "client",
  "client_secret": "[redacted]",
  "username": "user",
  "password": "[redacted]",
  "scope": "openid profile email custom roles"
}.

SELECT [o].[Id], [o].[ConcurrencyToken], [o].[Description], [o].[Descriptions], [o].[DisplayName], [o].[DisplayNames], [o].[Name], [o].[Properties], [o].[Resources]
FROM [OpenIddictScopes] AS [o]
WHERE [o].[Name] = N'custom'

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[ClientId] = @__identifier_0

OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was successfully validated.

SELECT [o].[Id], [o].[ConcurrencyToken], [o].[Description], [o].[Descriptions], [o].[DisplayName], [o].[DisplayNames], [o].[Name], [o].[Properties], [o].[Resources]
FROM [OpenIddictScopes] AS [o]
WHERE [o].[Name] IN (N'openid', N'profile', N'email', N'custom', N'roles')

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[Id] = @__key_0

SET NOCOUNT ON;
INSERT INTO [OpenIddictTokens] ([Id], [ApplicationId], [AuthorizationId], [ConcurrencyToken], [CreationDate], [ExpirationDate], [Payload], [Properties], [RedemptionDate], [ReferenceId], [Status], [Subject], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);

SELECT TOP(1) [o].[Id], [o].[ClientId], [o].[ClientSecret], [o].[ConcurrencyToken], [o].[ConsentType], [o].[DisplayName], [o].[DisplayNames], [o].[Permissions], [o].[PostLogoutRedirectUris], [o].[Properties], [o].[RedirectUris], [o].[Requirements], [o].[Type]
FROM [OpenIddictApplications] AS [o]
WHERE [o].[Id] = @__key_0

SET NOCOUNT ON;
INSERT INTO [OpenIddictTokens] ([Id], [ApplicationId], [AuthorizationId], [ConcurrencyToken], [CreationDate], [ExpirationDate], [Payload], [Properties], [RedemptionDate], [ReferenceId], [Status], [Subject], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);

OpenIddict.Server.OpenIddictServerDispatcher: Information: The response was successfully returned as a JSON document: {
  "access_token": "[redacted]",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "[redacted]"
}.

--- CALLING API ENDPOINT FROM FLUTTER CLIENT ----
--- Local handler stuff is not logged here ----
--- AUTHORIZED API CALLED BY BOB --- 

--- CALLING GRPC ENDPOINT FROM FLUTTER CLIENT ----

Request OPTIONS:/greet.Greeter/SayHello, Authorization header: 
OpenIddict.Validation.OpenIddictValidationDispatcher: Information: The response was successfully returned as a challenge response: {
  "error": "missing_token",
  "error_description": "The security token is missing.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2000"
}.

OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler: Information: AuthenticationScheme: OpenIddict.Validation.AspNetCore was challenged.

**Comment by danielleiszen** [comment]
The interesting part for me:
the Flutter HTTP API call does not have the local handler log lines, and the GRPC call fails at the preflight request before the actual POST, so it seems that the preflight request does not have the token, and the infrastructure is not prepared for it.

It actually makes sense now, since the C# client is not calling from a browser it does not have a preflight request.

And sorry but you were right to reopen the issue. I was too happy to notice that I removed the [Authorize] attribute and tried reordering the middlewares that way. So it worked only because there were no authorization set on the Grpc service. 

Now I tried with different ordering and the result is the same (above) so it is not affected by the order of middlewares, at least not in this case.

All in all I think it is some kind of bug, maybe not on your side, I am not sure whose side it is. However I would be really thankful if you helped me altering the middleware so, it could skip the preflight request that does not have the token and wait for the POST to extract the token from it.

**Comment by kevinchalet** [comment]
> Now I tried with different ordering and the result is the same (above) so it is not affected by the order of middlewares, at least not in this case.

Did you try calling `app.UseCors()` earlier so it's the first middleware invoked (ideally, even before `app.UseGrpcWeb()`)?

> All in all I think it is some kind of bug, maybe not on your side, I am not sure whose side it is. However I would be really thankful if you helped me altering the middleware so, it could skip the preflight request that does not have the token and wait for the POST to extract the token from it.

Since you called `builder.Services.AddAuthentication(OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)`, your application is configured to try to authenticate all requests (at least the ones that reach the `app.UseAuthentication()` middleware). Like all standard ASP.NET Core authentication handlers, OpenIddict returns `AuthenticateResult.NoResult()` to inform the authentication stack it is unable to locate a token to validate: at this stage, the request should never be rejected and for that, a challenge has to be triggered.

What's not 100% clear to me (yet) is why a challenge pointing to OpenIddict's validation handler is triggered for `OPTIONS:/greet.Greeter/SayHello` requests with the configuration you have in the MissingTokenIssue repo. These requests should be handled by the CORS middleware, that typically doesn't do that 😃 

Can you try lowering the log level and see if you find anything that may indicate what's the component triggering the challenge operation?

**Comment by danielleiszen** [comment]
It seems I hadn't played enough with the ordering. With calling `app.UseCors()` right after `app.UseRouting()` and before `app.UseGrpcWeb() `everything magically started to work.

So, thank you for figuring this out. If you still need me to create the debug logs for the wrong middleware order, please let me know, will do.

Otherwise, this issue can be closed. Thank you.

**Comment by kevinchalet** [comment]
> If you still need me to create the debug logs for the wrong middleware order, please let me know, will do.

Yeah, that would be nice! It would be interesting to know what was causing the challenge. 

> So, thank you for figuring this out.

Glad I could help! If you like the project, don't hesitate to sponsor it regularly so it stays free. Cheers.
