### ISSUE TITLE
Consider supporting multiple instances of the same issuer

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1392]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Currently, client registrations must be unique per issuer/authorization server. We should determine whether it would make sense to support multiple registrations per server so you can have 2 or more client registrations for the same identity provider.

**Comment by yedidyas** [comment]
@kevinchalet 
Hello
I'm new with the openiddict library, thanks for the work there.

Correct me if I'm wrong, but I think that what you are trying to achieve in the task already can be achieved with the current functions.
I'm creating a new descriptor in an async middleware, to support multi-tenancy clients functionality
`await _openIddictApplicationManager.CreateAsync(descriptor);`
(the descriptor details are being read few lines before from an external database)
This is actually "supporting multiple instances of the same issuer".
Please correct me if you are talking about something else, and provide a code example if you can.
thanks!

**Comment by kevinchalet** [comment]
@yedidyas wooops, I should have been more specific: this ticket is about allowing multiple client registrations pointing to the same issuer **in the new OpenIddict client that will ship as part of the next major release**. More information here: https://kevinchalet.com/2022/02/25/introducing-the-openiddict-client/ 😃

**Comment by kevinchalet** [comment]
After thinking about it, supporting multiple client registrations for the same issuer would be incompatible with webfinger-based discovery, should OpenIddict implement it in the future. Closing as _wontfix_.
