### ISSUE TITLE
Extract `TargetFrameworks` property to `Directory.Build.props`

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1400]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Now in order to build OpenIddict I have to install all `<TargetFrameworks>net461;netcoreapp3.1;net5.0;net6.0;netstandard2.0;netstandard2.1</TargetFrameworks>` frameworks.
I have only `net48` and `net6.0` on my machine.
I would like to be able to override `TargetFrameworks` property once to be able to build the project

**Comment by kevinchalet** [comment]
> I would like to be able to override `TargetFrameworks` property once to be able to build the project

Sadly it's not possible: not all the projects specify the same set of TFMs (they are careful chosen per-package to avoid having useless TFMs and optimize the dependencies graph when possible).

Consider installing the missing SDKs or doing a find and replace to remove the TFMs you don't want.
