### ISSUE TITLE
Add token refresh support in the OpenIddict client

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1401]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Token refresh is an important part and should be directly supported by OpenIddict instead of requiring users to use a separate client like IdentityModel. Such support will need to be added as part of the `ProcessAuthentication` event.

### Additional context

As a bonus, check with the ASP.NET folks whether they'd be okay to introduce an overload of `AuthenticateAsync()` taking an `AuthenticationProperties` instance, so that users could directly do something like this:

```csharp
var properties = new AuthenticationProperties(new Dictionary<string, string>
{
    // Note: when only one client is registered in the client options,
    // setting the issuer property is not required and can be omitted.
    [OpenIddictClientAspNetCoreConstants.Properties.Issuer] = issuer,

    [OpenIddictClientAspNetCoreConstants.Properties.RefreshToken] = "the refresh token retrieved from the authentication cookie, the Identity database or anywhere else"
});

// Ask the OpenIddict client to do the token refresh dance and get back the result.
var result = await HttpContext.AuthenticateAsync(properties, OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
```

**Comment by a-a-k** [comment]
Did I understand that correctly, I have to implement refreshing myself if I use MS OIDC client? I was thinking it's going silently, but when checked this I got that refresh token flow never initiates.

**Comment by ProgramGeek02** [comment]
any news on how to implement refresh token directly inside Openiddict?
I see there is support for refresh token flow but there is no way the client app try to refresh token it self using openiddict

**Comment by kevinchalet** [comment]
> any news on how to implement refresh token directly inside Openiddict?

https://github.com/openiddict/openiddict-samples/blob/dev/samples/Imynusoph/Imynusoph.Client/Program.cs
