### ISSUE TITLE
Problem with implementing custom stores

### ISSUE THREAD

**Issue by Huppiflu** [openiddict/openiddict-core#1405]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I have a problem implementing custom stores.
I inject them as follows:

```
services
        .AddOpenIddict()
        .AddCore(options =>
        {
               options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
                options.SetDefaultScopeEntity<BitsScope>();
                options.AddScopeStore<BitsScopeStore>();
                options.SetDefaultTokenEntity<BitsToken>();
                options.AddTokenStore<BitsTokenStore>();
                options.SetDefaultAuthorizationEntity<BitsAuthorization>();
                options.AddAuthorizationStore<BitsAuthorizationStore>();
        })
```

I also tried injecting them one by one, but none of them works as expected. I also have custom classes for storage, like this:

```
public class BitsAuthorization
{
        public Guid Key { get; set; }
        public string Status { get; internal set; } = string.Empty;
        public string Subject { get; internal set; } = string.Empty;
        public string Type { get; internal set; } = string.Empty;
        public string ApplicationID { get; internal set; } = string.Empty;
        public DateTimeOffset? CreationDate { get; internal set; } = DateTimeOffset.Now;
        public ImmutableDictionary<string, JsonElement> Properties = null;
        public ImmutableArray<string> Scopes = new ImmutableArray<string>();

        internal BitsAuthorization(Guid key)
        {
           this.Key = key;
        }
}
```

I get errors like:
![OpenIDDict01](https://user-images.githubusercontent.com/68861443/160634108-cf8245c0-b096-464b-81a1-63347626b995.jpg)

 

Do have any idea what I am doing wrong?

**Comment by kevinchalet** [comment]
> Do have any idea what I am doing wrong?

You're mixing different types of stores:
  - The built-in EF Core stores for applications.
  - Custom stores for the authorizations, scopes and tokens entities that don't derive from the built-in EF Core stores.

It's possible but it's an advanced scenario that requires writing custom `IOpenIddict*StoreResolver` implementations. Otherwise, the store resolvers registered by `options.UseEntityFrameworkCore()` will ignore your custom non-EF Core stores.
