### ISSUE TITLE
Change `DateTime` to `DateTimeOffset` in EF storage

### ISSUE THREAD

**Issue by kinosang** [openiddict/openiddict-core#1414]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Most of EFCore providers now deal with `DateTimeOffset, offset 0` correctly, for e.g., Npgsql.EntityFrameworkCore.PostgreSQL, Pomelo.EntityFrameworkCore.MySql, etc.

**Comment by kevinchalet** [comment]
Doing so would require making another breaking change and wouldn't work with all providers (it's likely the Oracle MySQL provider still doesn't support that properly 😆). Do you see any advantage moving back to `DateTimeOffset`?

**Comment by kinosang** [comment]
@kevinchalet oops, I forgot to check the Oracle MySQL provider...

by moving back to `DateTimeOffset`, we can omit the conversion between `DateTimeOffset` and `DateTime` and keep the stored timestamps timezone-independant.

**Comment by kevinchalet** [comment]
> by moving back to `DateTimeOffset`, we can omit the conversion between `DateTimeOffset`

Well, it's a very cheap operation so not sure there's anything visible to gain 😃

> and keep the stored timestamps timezone-independant.

All the stores use UTC dates so they are not really timezone-dependent (and while the rest of OpenIddict does use `DateTimeOffset`, we actually only care about UTC dates, so it's not really important to keep the timezone offset).
