### ISSUE TITLE
How to login with a particular identity provider?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#143]
How and where to specify which identity provider I want to use?
Is this possible in a request?
Do I have to create my own authorization controller?
How to tell ASP.NET infrastructure that I want to use particular identity provider and navigate directly to it's page but not my login page?

**Comment by kevinchalet** [comment]
@xperiandri you can tweak your `Authorize` action to call `Challenge("the name of the external provider")` to trigger a challenge pointing to the external provider you want.

E.g:

```
var provider = (string) request["identity_provider"];
if (!string.IsNullOrEmpty(provider)) {
    return Challenge(provider);
}
```

Note that you won't be able to use `[Authorize]` in this case, as it would prevent your `Challenge` call to be invoked before redirecting the user to the login endpoint.

**Comment by xperiandri** [comment]
So I just add a URL parameter to my request and look for it at `authorize` endpoint, right?
Could you explain where I can't use `[Authorize]` attribute? 
Do you mean that I need to use `[HttpGet, Route("~/connect/authorize")]` instead of `[Authorize, HttpGet, Route("~/connect/authorize")]`
Or do something like `[HttpGet, Route("~/connect/authorize/{provider}")]` ?

**Comment by kevinchalet** [comment]
> So I just add a URL parameter to my request and look for it at authorize endpoint, right?

Right.

> Could you explain where I can't use [Authorize] attribute? 

Before your action wouldn't be executed, so `Challenge` would never be invoked.

> Do you mean that I need to use [HttpGet, Route("~/connect/authorize")]

Yes. And make the `IsAuthenticated` check inside the action:

```
if (!User.Identity.IsAuthenticated) {
    var provider = (string) request["identity_provider"];
    if (!string.IsNullOrEmpty(provider)) {
        return Challenge(provider);
    }

    return Challenge();
}
```
