### ISSUE TITLE
[Azure Functions] Viewless auth on mobile and SPA

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1436]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I want to implement a viewless (only native views) authentication on Azure Function.

How should it work?
Imagine the I authenticate on iOS with Apple ID natively. Then Apple gives me a token. Same stuff I can achieve with MS Account on Windows. How much of OpenIddict do I need in that case to implement the authentication?

And if I need to execute a provider view, how should that work? Just not returning MVC views but redirect to a scheme?

**Comment by kevinchalet** [comment]
Your question has actually two aspects:
  - A non-interactive flow allowing to exchange tokens issued by other servers: https://stackoverflow.com/questions/40257981/exchanging-a-google-idtoken-for-local-openid-token-c-sharp/40260960#40260960 should put you on the right track.

  - Azure Functions support: see https://github.com/openiddict/openiddict-core/issues/1133 for more information. If it's important for your company, native support in OpenIddict is certainly something we can discuss, but in any case, it will be a sponsors-only or paid feature as the demand is too low to justify having that in the core stuff.

**Comment by xperiandri** [comment]
But can't I make interactive login on mobile/SPA for any provider and exchange the token then? In that case, I only need an exchange endpoint on Azure Function, right?

**Comment by kevinchalet** [comment]
> In that case, I only need an exchange endpoint on Azure Function, right?

Having an exchange endpoint is just a tiny part of the story: before your endpoint is even called, the OpenIddict ASP.NET Core host does a lot of things, like extracting the request or validating it. There's no such thing on Azure Functions, so you'll just get an exception when calling `SignIn`.
