### ISSUE TITLE
Creating a authorization code from a custom endpoint

### ISSUE THREAD

**Issue by BlackSyc** [openiddict/openiddict-core#1438]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I'd like to create an authorization code from a custom endpoint (not in the OAuth2.0 spec) for an authorized user and a specific client with the implicit consent type.
However, I'm unable to find how I should do this, as I got lost in the OpenIddictServerHandler architecture a little. 
Could you point me to where this logic is located in OpenIddictCore so I can see if I can invoke that logic from my custom endpoint?

**Comment by kevinchalet** [comment]
There are 2 ways to achieve that, basically:

  - The easy way: authorization codes are encrypted JWT tokens (unless you use the Data Protection integration) so nothing prevents you from directly using `JsonWebTokenHandler` to produce your own authorization codes. It's not strictly required, but you'll want to also use `IOpenIddictTokenManager` to create token entries for your authorization codes, so they can be marked as redeemed when used and revoked if a replay attack is detected.

  - The more complicated way: integrating your custom endpoint into OpenIddict's request processing pipeline so you can natively call things like `SignIn`, as you'd do from the authorization endpoint. For that, you'll need:

    - A custom `ProcessRequestContext` event handler to tell OpenIddict when your custom endpoint is called (`context.EndpointType` is an enum so you use casts to support custom values that are not part of the `OpenIddictServerEndpointType` enum: `context.EndpointType = (OpenIddictServerEndpointType) 42`. You can get some inspiration from the built-in handler: https://github.com/openiddict/openiddict-core/blob/128eaf24bacb001c39f18de90b43b9ee3ab69254/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs#L60-L161

    - Another custom `ProcessRequestContext` handler that will execute the logic needed to make your endpoint work: you can create sub-events like the `ExtractAuthorizationRequestContext`/ `ValidateAuthorizationRequestContext`/`HandleAuthorizationRequestContext` events offered by OpenIddict, or you can use a simpler approach, e.g by directly calling `context.SkipRequest()` to invoke the rest of the request processing pipeline so that you can eventually call `SignIn()` from a MVC action or a minimal API action.

    - A custom `ProcessSignInContext` handler that replaces the built-in one to allow triggering sign-in operations from your custom endpoint: https://github.com/openiddict/openiddict-core/blob/128eaf24bacb001c39f18de90b43b9ee3ab69254/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L1109-L1177

    - Another custom `ProcessSignInContext` handler invoked after `EvaluateGeneratedTokens` to allow OpenIddict to generate authorization codes for sign-in operations triggered from your custom endpoint. Take a look at the built-in handler for some inspiration: https://github.com/openiddict/openiddict-core/blob/128eaf24bacb001c39f18de90b43b9ee3ab69254/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L1379-L1476

    - A last `ProcessSignInContext` handler invoked late in the pipeline to take care of returning the response to the caller (e.g as as 302 redirect). OpenIddict has a dedicated `ApplyAuthorizationResponseContext` sub-event triggered from `ProcessSignInContext` but nothing prevents you from applying the response directly from `ProcessSignInContext`. You can get some inspiration from the built-in handlers: https://github.com/openiddict/openiddict-core/blob/128eaf24bacb001c39f18de90b43b9ee3ab69254/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Authentication.cs#L408-L477

Note: for the second option, I'd recommend using the 4.0 nightly builds as it comes with many improvements for these scenarios.

**Comment by BlackSyc** [comment]
Thank you for the fast and detailed answer. 
I think for my use case the simple approach would suffice because I know the user performing the request is authorized (and therefore doesn't need to go through the SignIn flow), but I'll definitely look into integrating it with OpenIddict's request processing pipeline in a bit more detail too. 

When I'm creating a authorization code with the JsonWebTokenHandler however, how would I go about applying the code challenge/code verifier to it?

**Comment by kevinchalet** [comment]
> Thank you for the fast and detailed answer.

You're welcome 😄 

> When I'm creating a authorization code with the JsonWebTokenHandler however, how would I go about applying the code challenge/code verifier to it?

Everything is stored as claims, code challenge/code challenge method included (these claims are prefixed with `oi_` to indicate they are OpenIddict-specific/private claims):

https://github.com/openiddict/openiddict-core/blob/128eaf24bacb001c39f18de90b43b9ee3ab69254/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L1693-L1780

**Comment by BlackSyc** [comment]
That makes sense, I'll give it a go!

**Comment by kevinchalet** [comment]
Out of curiosity, may I ask what's the scenario you have in mind? Are you trying to implementing something similar to the OIDC App2app flow?

**Comment by BlackSyc** [comment]
Sure!

I'm building a game that consists of 4 components:
- Game client (desktop application)
- Game server (multiple, the user can choose which one they want to connect to)
- Web API Resource server
- Identity provider

On startup, the game client will obtain an access token through the regular auth_code flow by opening a browser window with the identity provider authorize url. This access token is used every time the game client needs to retrieve resources directly from the resource web API.

Then, after this, the user can choose to connect to one of the game servers (through a socket connection). This game server needs to be able to request the user's resources from the same web API. For this, I'd want to use a second access token scoped to the game server application. In order to retrieve this token for the game server, I figured I'd send the game servers client_id and code_challenge to the game client, which would then in turn invoke another auth_code flow through a browser window and send the auth_code back to the game server.

However, I would prefer if this last auth_code for the server could be requested without opening another browser from within the game. Since I know that in this case the user is already authenticated (and authorized) to request this authorization code, I figured I could create a custom endpoint that requires authorization and would return an auth_code.

The reason I'm not going for the client credentials flow is because I would prefer if the identity information in the request context going to the resource server contains information about the user so I can scope it's permissions to only affect the user's resources.

As a useful side-effect this could also make it possible for me to revoke authorizations to other game servers when a new one is authorized.

I figured this would be a good way to go about this, but maybe I'm missing a more obvious solution to this problem. If that's the case, please don't hesitate to challenge :)
