### ISSUE TITLE
Client credentials flow fails with 401 Not Authorized from the resource server 

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1445]
### Confirm you've already contributed to this project or that you sponsor it

- [x] I confirm I'm a sponsor or a contributor

### Version

3.x

### Describe the bug

I have a separate authorization server and a resource server. The resource server runs in IIS and have Windows Integrated Security activated too. This means that the resource server should work for both NTLM and bearer tokens (client credentials and authorization code flow).

I am successfully connecting to the auth server, getting an access token and passing it along to the resource server.

However the request is failing with 401 Unauthorized. The request only contains an `Authorization` header and there is no `Negotiate` header (as it should be) as this request must be done with the bearer token and not with network credentials.

### To reproduce

The  authorization server is setup as follows:

```csharp
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddDbContext<ApplicationDbContext>(options =>
        {
            options.UseSqlServer(Configuration.GetConnectionString("Identity"));
            options.UseOpenIddict();
        });

        services.Configure<IdentityOptions>(options =>
        {
            options.ClaimsIdentity.UserNameClaimType = Claims.Name;
            options.ClaimsIdentity.UserIdClaimType = Claims.Subject;
            options.ClaimsIdentity.RoleClaimType = Claims.Role;
        });

        services.AddQuartz(options =>
        {
            options.UseMicrosoftDependencyInjectionJobFactory();
            options.UseSimpleTypeLoader();
            options.UseInMemoryStore();
        });

        services.AddQuartzHostedService(options => options.WaitForJobsToComplete = true);

        services.AddOpenIddict()
            .AddCore(options =>
            {
                options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
                options.UseQuartz();
            })

            .AddServer(options =>
            {
                options.SetAuthorizationEndpointUris("/connect/authorize")
                        .SetLogoutEndpointUris("/connect/logout")
                        .SetIntrospectionEndpointUris("/connect/introspect")
                        .SetTokenEndpointUris("/connect/token")
                        .SetUserinfoEndpointUris("/connect/userinfo")
                        .SetVerificationEndpointUris("/connect/verify");

                options.AllowAuthorizationCodeFlow() //.RequireProofKeyForCodeExchange()
                        .AllowPasswordFlow()
                        .AllowClientCredentialsFlow()
                        .AllowImplicitFlow()
                        .AllowHybridFlow()
                        .AllowRefreshTokenFlow();

                options.RegisterScopes(
                    Scopes.OpenId, 
                    Scopes.Email, 
                    Scopes.Profile, 
                    Scopes.Roles,
                    Scopes.OfflineAccess);

                options.AddEncryptionKey(new SymmetricSecurityKey(Convert.FromBase64String(Configuration["Identity:EncryptionKey"])));

                options.AddDevelopmentSigningCertificate();

                options.UseAspNetCore()
                        .EnableStatusCodePagesIntegration()
                        .EnableAuthorizationEndpointPassthrough()
                        .EnableLogoutEndpointPassthrough()
                        .EnableTokenEndpointPassthrough()
                        .EnableUserinfoEndpointPassthrough()
                        .EnableVerificationEndpointPassthrough();

                options.DisableAccessTokenEncryption();
            })

            .AddValidation(options =>
            {
                options.UseLocalServer();
                options.UseAspNetCore();
            });
        });
    }
```

The resource server is configured as follows:

```csharp
    services.AddAuthentication(options =>
    {
        options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
    });

    services.AddOpenIddict()
        .AddValidation(options =>
        {
            options.SetIssuer(Configuration["Issuer"]);
            options.AddAudiences(Configuration["Audiences"]);

                options.UseIntrospection()
                    .SetClientId(Configuration["ClientId"])
                    .SetClientSecret(Configuration["ClientSecret"]);

            options.UseSystemNetHttp();
            options.UseAspNetCore();
        });
```

I'm using `Flurl` to get an access token and then connect to a resource endpoint protected with the `[Authorize]` attribute.  The code is:

```csharp

    //Get access tokens
    var tokens = await authServerUrl
        .AppendPathSegment("connect/token")
        .WithHeader("content-type", "application/x-www-form-urlencoded")
        .PostUrlEncodedAsync(new {
            grant_type = "client_credentials",
            client_id = clientId,
            client_secret = clientSecret,
            audience = audience,
        })
        .ReceiveJson<ClientCredentialsResponse>();

    //Access protected endpoint
    var response= await serverUrl
        .AppendPathSegment("api/Protected/Endpoint")
        .WithOAuthBearerToken(tokens.AccessToken)
        .ReceiveString();
```

The `ClientCredentialsResponse` class is a simple POCO containing `access_token`, `token_type` and `expires_in`.

**Comment by kevinchalet** [comment]
Thanks for (re)-sponsoring the project.

> I have a separate authorization server and a resource server. The resource server runs in IIS and have Windows Integrated Security activated too. This means that the resource server should work for both NTLM and bearer tokens (client credentials and authorization code flow).

This is not a scenario I'd recommend supporting, as Integrated Windows Authentication is, like cookies, an automatic authentication mode. Using it for APIs requires using antiforgery to prevent CSRF attacks.
If removing IWA at the API level is an option, you may want to consider using the authorization code flow and implementing IWA at the authorization endpoint level.

That said, what you have should work. To investigate, I'll need the ASP.NET Core logs (make sure to lower the default log level to Trace so we don't miss any detail).

**Comment by cryo75** [comment]
Removing IWA is not possible at this stage. It will be implemented in the near future.

I would like to add that I also have 3 Blazor server-side projects that use Authorization Code Flow with the same authorization and resource servers, and there I have no problem accessing protected endpoints.

Here are the log files for the auth and resource servers
[AuthServer.Log-20220518.txt](https://github.com/openiddict/openiddict-core/files/8718235/AuthServer.Log-20220518.txt)
[ResourceServer.Log-20220518.txt](https://github.com/openiddict/openiddict-core/files/8718236/ResourceServer.Log-20220518.txt)
.

**Comment by cryo75** [comment]
These are the correct log files:
[ResourceServer.Log-20220518.txt](https://github.com/openiddict/openiddict-core/files/8718370/ResourceServer.Log-20220518.txt)
[AuthServer.Log-20220518.txt](https://github.com/openiddict/openiddict-core/files/8718371/AuthServer.Log-20220518.txt)

**Comment by cryo75** [comment]
I found the following in the resource server log file:

2022-05-18 18:59:17.044 +02:00 [INF] The authentication demand was rejected because the token had no audience attached.

2022-05-18 18:59:17.044 +02:00 [DBG] The event OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Validation.OpenIddictValidationHandlers+ValidateAudience.

2022-05-18 18:59:17.044 +02:00 [DBG] The event OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext was marked as rejected by OpenIddict.Validation.OpenIddictValidationHandlers+ValidateAudience.

2022-05-18 18:59:17.046 +02:00 [INF] OpenIddict.Validation.AspNetCore was not authenticated. Failure message: An error occurred while authenticating the current request.

2022-05-18 18:59:17.048 +02:00 [INF] The response was successfully returned as a challenge response: {
  "error": "invalid_token",
  "error_description": "The specified token doesn't contain any audience.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2093"
}.

Could this be the problem why I'm getting 401?

Also, in the above example, I'm adding the audience to the request sent to the token endpoint.

**Comment by cryo75** [comment]
This is the code that creates the token:

```csharp
    var request = HttpContext.GetOpenIddictServerRequest() ??
        throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");

    if (request.IsClientCredentialsGrantType())
    {
        var application = await applicationManager.FindByClientIdAsync(request.ClientId);
        if (application == null)
        {
            throw new InvalidOperationException("The application details cannot be found in the database.");
        }
        var identity = new ClaimsIdentity(
            TokenValidationParameters.DefaultAuthenticationType,
            Claims.Name, Claims.Role);
        identity.AddClaim(Claims.Subject, await applicationManager.GetClientIdAsync(application),
            Destinations.AccessToken, Destinations.IdentityToken);

        identity.AddClaim(Claims.Name, await applicationManager.GetDisplayNameAsync(application),
            Destinations.AccessToken, Destinations.IdentityToken);

        return SignIn(new ClaimsPrincipal(identity), OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
    }
```

**Comment by cryo75** [comment]
I added the following code:

```csharp
    // Set the list of scopes granted to the client application in access_token.
    var principal = new ClaimsPrincipal(identity);
    principal.SetScopes(request.GetScopes());
    principal.SetResources(await scopeManager.ListResourcesAsync(principal.GetScopes()).ToListAsync());

    foreach (var claim in principal.Claims)
    {
        claim.SetDestinations(GetDestinations(claim, principal));
    }

    return SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
```

But the audience is still not included in the access token.

**Comment by kevinchalet** [comment]
> But the audience is still not included in the access token.

https://github.com/openiddict/openiddict-core/issues/1440#issuecomment-1126723677 should put you on the right track (TL;DR, create a scope with one or multiple resources corresponding to your API audiences).

**Comment by cryo75** [comment]
I already have a scope with the api resource. And this scope is also included in the openiddict application.

**Comment by kevinchalet** [comment]
Then don't forget to request it:

```csharp
var tokens = await authServerUrl
    .AppendPathSegment("connect/token")
    .WithHeader("content-type", "application/x-www-form-urlencoded")
    .PostUrlEncodedAsync(new {
        grant_type = "client_credentials",
        client_id = clientId,
        client_secret = clientSecret,
        // 👇
        scope = "your_custom_scope"
    })
    .ReceiveJson<ClientCredentialsResponse>();
```

**Comment by cryo75** [comment]
Oh wow I was using `audience` instead from the Auth0 specification. I do get the audience in the token now!!
