### ISSUE TITLE
[Samples] Use ASP.NET Core 6 scaffoldable template as a base of Server and Client samples

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1446]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

I propose:
1. Remove your custom AccountController and ManageController, all related views and view models, and rely on Identity Razor pages
2. Make template scaffoldable, so that consumers can scaffold any built-in Identity Razor Page
3. Remove all legacy stuff like gulp, package.json, etc., and use everything from .NET 6 template. Leaving only regular `Program.cs` and `Startup.cs`

My company can prepare a PR if you approve

### Additional context

As a preparation to project template creation

**Comment by kevinchalet** [comment]
It's important to note that the "samples" contained in this repo are not really "public samples", unlike the projects you can find in the dedicated repo: https://github.com/openiddict/openiddict-samples.

These projects are actually engineering samples I use when developing/testing new features. Think of them as functional/integration tests projects (that's also the reason why I recently moved them from `samples` to `sandbox` and renamed them).

As such, I'm not sure it's worth spending time on 1/2: there's no real ROI to expect here 😄 
Regarding 3, I'm not opposed to remove these artifacts, so 👍🏻
