### ISSUE TITLE
[Templates] Create a `dotnet new` project template of authentication server

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1447]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

With some simple configurability reusing server sample as a source of the template.

My company can prepare a PR if you approve.

### Additional context

Related #1446

**Comment by kevinchalet** [comment]
When I started working on OpenIddict, there was a strong demand for templates. I've never been completely opposed to that, but it's extremely important to note that maintaining templates in the long term is **extremely** expensive given all the combinations folks would like to see supported:
  - With and without consent pages.
  - With and without authorization code flow support.
  - With and without implicit flow support.
  - With and without hybrid flow support.
  - With and without resource owner password credentials grant support.
  - With and without client credentials grant support.
  - With and without device authorization grant support.
  - With and without refresh token grant support.
  - With and without ASP.NET Core Identity.
  - With and without delegated OIDC/OAuth 2.0 authentication/pseudo-authentication.
  - With and without Integrated Windows Authentication.
  - With and without Entity Framework Core.
  - With and without local validation.
  - With and without introspection.

So not a strong "no" but a "let's wait to see how we can fund this work item to make it viable in the long term" (e.g should that be a sponsors-only or paid feature?)
