### ISSUE TITLE
Decrypt access tokens

### ISSUE THREAD

**Issue by GDreyV** [openiddict/openiddict-core#1458]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I was using code shared on [OpenIddict: How to manually check access token and get identity](https://stackoverflow.com/questions/46764492/openiddict-how-to-manually-check-access-token-and-get-identity). The idea why I need is that token was sent not through regular .net mvc but through some plugin interfaces so I don't have access to the context. How can I do the same in Openiddict 3 (and 4 as it's already in preview)?

Old code for version 2:
```C#
var provider = this.services.GetRequiredService<IDataProtectionProvider>();
var protector = provider.CreateProtector(
    nameof(OpenIdConnectServerHandler),
    nameof(OpenIdConnectServerOptions.AccessTokenFormat),
    OpenIdConnectServerDefaults.AuthenticationScheme);

var format = new TicketDataFormat(protector);

// If the access token is not malformed, a non-null value
// is returned. Note that you'll have to manually validate
// the expiration date and the audience of the ticket.
AuthenticationTicket ticket = format.Unprotect(token);
```

**Comment by kevinchalet** [comment]
Hey 👋🏻 

It should be simpler in OpenIddict 3.0 thanks to the dedicated `OpenIddictValidationService` that can be used outside of a request:

```csharp
var service = this.services.GetRequiredService<OpenIddictValidationService>();
var principal = await service.ValidateAccessTokenAsync(token); // If the token is not valid, an exception will be thrown.
```

**Comment by GDreyV** [comment]
Awesome, thank you!
Did I get it right to get `AuthenticationTicket` I just need to do something like
```C#
var ticket = new AuthenticationTicket(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
```
?

**Comment by kevinchalet** [comment]
OpenIddict's server and validation features have been decoupled from ASP.NET Core as part of the 3.0 effort so the ASP.NET Core `AuthenticationTicket` type is no longer used: in 3.0, everything is stored as claims in the `ClaimsPrincipal`.

If you absolutely need `AuthenticationTicket` for some reasons, you can indeed create it as in your snippet. If it's not required, consider directly using `ClaimsPrincipal` 😃

**Comment by GDreyV** [comment]
Got it, switched to `ClaimsPrincipal`. Thanks for fast help!

**Comment by kevinchalet** [comment]
You're welcome 😃 

Thanks for sponsoring the project! (you're one of the very first sponsors so it means a lot to me 😉)
