### ISSUE TITLE
IDX20803: Unable to obtain configuration 

### ISSUE THREAD

**Issue by eddiekimdev** [openiddict/openiddict-core#1459]
### Confirm you've already contributed to this project or that you sponsor it

- [ ] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I have an authorization server running on different port and I can access the configuration url from browser.
However, when I configure the auth issuer in .net core webapi, I get below errors.
IDX20803: Unable to obtain configuration from: 'http://localhost:5001/auth/.well-known/openid-configuration

It only happens after I changed the auth server base path from http://localhost:5001 to http://localhost:5001/auth

services.AddOpenIddict()
                .AddValidation(options =>
                {
                    options.SetIssuer("http://localhost:5001/auth");
                    options.AddAudiences("resource_server");
                    options.AddEncryptionKey(new SymmetricSecurityKey(
                        Convert.FromBase64String("DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=")));
                    options.UseSystemNetHttp();
                    options.UseAspNetCore();
                });

Is there any reason or solution to this issue?

**Comment by kevinchalet** [comment]
The bot didn't recognize you as a sponsor. Did you sponsor the project using a corporate account?

**Comment by eddiekimdev** [comment]
No, just using my personal account.

**Comment by kevinchalet** [comment]
But did you sponsor the project? 😕

**Comment by eddiekimdev** [comment]
Nope, but we plan to use this on our project, it is currently under evaluation.

**Comment by kevinchalet** [comment]
As mentioned in the issue template, support is reserved to sponsors. Closing.
