### ISSUE TITLE
Update CryptoHelper to v2.0

### ISSUE THREAD

**Issue by henkmollema** [openiddict/openiddict-core#146]
I released [CryptoHelper v2.0](https://www.nuget.org/packages/CryptoHelper/2.0.0) which targets .NET Core RTM. Either I'll send a pull request when you are updating to RTM or you can update yourself. :smile:

**Comment by kevinchalet** [comment]
Ha great, thanks, I'll include that in my local branch! :tada: 

Curious: is the <net451 TFM deprecation the only breaking change?

**Comment by henkmollema** [comment]
Yeah, I removed the `net40` and `net45` targets and the associated API's which were `ifdef`'d. The API for `net451` and `.netstandard1.3` stays the same.

**Comment by kevinchalet** [comment]
Fixed as part of https://github.com/openiddict/openiddict-core/commit/dced1cd8fee9aa3c8ef9ff9a4271f204bb15f66c.

@henkmollema thanks! :clap:
