### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#148]
How can we achieve two factor authentication with ROPC workflow?

**Comment by kevinchalet** [comment]
You can't. This flow doesn't offer a standard way to support 2FA authentication and OpenIddict will systematically reject `grant_type=password` requests when 2FA is enforced for an account. 

Instead, consider using an interactive flow like the authorization code flow or implicit.

**Comment by jayrulez** [comment]
Thanks for your feedback. I will look into this.

**Comment by asadsahi** [comment]
@PinpointTownes I am also at a stage where I am trying to implement 2FA in [project](https://github.com/asadsahi/AspNetCoreSpa).

This project has password flow for internal logins and implicit flow (for external logins). How do I incorporate 2FA using openidconnect-core.

e.g in my two schenarios.

1) after username/password verification, is there a way to hold on until user verifies through 2nd factor before sending the ticket. What mechanism do you reckon can be used here?

2) after social logins verification, how to ask for second factor? Is it ok to ask 2nd factor after social logins?

**Comment by kinosang** [comment]
@asadsahi as @PinpointTownes said, password flow doesn't offer a standard way to support 2FA authentication, but I've implemented 2FA in my way.

1. for password flow, ask users append the 6-digit code after their password, and spilt it in token endpoint before calling `CheckPasswordSignInAsync` if user has 2FA enabled.
1. for social logins, check `result.RequiresTwoFactor` after do `ExternalLoginSignInAsync`, and redirect users to the action for 2FA.

**Comment by kinosang** [comment]
BTW, I return a `BadRequest` response with `OpenIdConnectConstants.Errors.ConsentRequired` error and a user-friendly message such as `Two-Factor authentication required, append the 6-digit code to password.` to users if they didn't pass the 2FA.

**Comment by asadsahi** [comment]
@kinosang do you mean to enter 6 digits in same field as password or in a seperate input field? 

I was thinking, instead of passing the whole thing in one reqeust, somehow send username/password in one request and get an intermediary token if two factor enabled, otherwise signin completely.

**Comment by kinosang** [comment]
@asadsahi I mean, ask user to input password+token in password field.

**Comment by kinosang** [comment]
You can have a look at Yahoo’s implementation.

**Comment by asadsahi** [comment]
@kinosang can you please send me a link where this is implemented, can't find it [here](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Yahoo)

**Comment by kinosang** [comment]
@asadsahi not the `AspNet.Security.OAuth.Yahoo`, it required you to use `password`+`6 digits` as password on macOS's `Internet Accounts` (and maybe somewhere) when you try to sign in your Yahoo account.

the way I chose is just splitting the last 6 digits from user's input, and use it to make a 2FA challenge.

**Comment by asadsahi** [comment]
Ahh ok, I thought when you said:

> You can have a look at Yahoo’s implementation.

I thought you mean there is an example of your implementation of 2FA.
