### ISSUE TITLE
Implement impersonation/delegation behavior

### ISSUE THREAD

**Issue by a-a-k** [openiddict/openiddict-core#1489]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I was inspired by [this](https://github.com/openiddict/openiddict-samples/issues/75#issuecomment-531502199) comment (I'm still not sure if I need to ask this question there) when was starting to implement something. If I understood correctly, I need to implement a call to `token` endpoint with specific grant type and custom request parameter.

The **main question** I have: how to trigger that request, should I do that using http client or initialize a challenge or somehow else? if I do that using http client, how can I preserve related principal? If I can't pass principal with the request, then how should I validate the request? I believe, this is something a quite simple, but I can't grope the answer.

**Comment by kinosang** [comment]
OAuth requires a "flow" to do so. so a Relying Party or a "Gateway" should do HTTP request for token exchange.

**Comment by a-a-k** [comment]
@kinosang I know about that OAuth specification, but we don't have to follow this. All the more so, OpenIddict itself has not `token_exchange` flow implementation yet. Well, we're trying to make something to get push off.

**Comment by kevinchalet** [comment]
> I was inspired by https://github.com/openiddict/openiddict-samples/issues/75#issuecomment-531502199 comment (I'm still not sure if I need to ask this question there) when was starting to implement something. If I understood correctly, I need to implement a call to token endpoint with specific grant type and custom request parameter.

While terms are similar, the impersonation model discussed in that thread has nothing to do with RFC8693: it's just a custom parameter used by a regular code flow client to tell the authorization server that a specific user (the impersonated user) - different from the logged in user (the impersonator) - should be used to create the `ClaimsPrincipal` that OpenIddict will need to create the tokens (which typically requires a special role/permission). It's very easy to implement as the only thing you need to do is tweak your `Authorize` action to use the impersonated identity after checking the impersonator is allowed to do so.

Delegation/impersonation as defined in RFC8693 is a **much more complex beast** that is actually a flow in itself: it uses the regular token endpoint with a specific `grant_type` with parameters and semantics that are unique to RFC8693. The main use case for delegation/impersonation as defined in RFC8693 is when API A need to communicate with API B on behalf of the first user while preserving the identity of API A so that API B can make appropriate security decisions based on the identity of each party involved.

As I mentioned in one of my emails, implementing RFC8693 is not an easy task: the current OpenIddict bits will only help you with the token request/response handling part but that's pretty much all. All the token validation and generation part will be completely up to you. If you decide to implement that yourself, I'd recommend using OpenIddict 4.0 as [the revamped token generation/validation pipeline](https://kevinchalet.com/2022/06/22/openiddict-4-0-preview1-is-out/) should make things a bit easier.

**Comment by a-a-k** [comment]
Sure, I don't mean implementation of protocol, that's why I named the issue '_implementing behavior_'. We have no required skills for that and have no time too.

> It's just a custom parameter used by a regular code flow client to tell the authorization server that a specific user (the impersonated user) - different from the logged in user (the impersonator) - should be used to create the ClaimsPrincipal that OpenIddict will need to create the tokens (which typically requires a special role/permission). It's very easy to implement as the only thing you need to do is tweak your Authorize action to use the impersonated identity after checking the impersonator is allowed to do so.

Okay, I shouldn't use `token` endpoint, but `authorize`. Anyway, I still don't understand, how can I achieve that? The `Authorize` action fires only twice and both of them at the login process, so how it should be reached within logged user's activity? As I realize, authorization happens on a client side until a user's authentication is valid. Also, how it is supposed to add some '_impersonation_' parameter to request properties?

I understand, that may seem too trivial, but that's we stuck on now.

**Comment by kevinchalet** [comment]
IMHO, before discussing implementation details, you should start by describing your scenario.

**Comment by a-a-k** [comment]
Our scenario is pretty simple: web client with cookie authentication, user clicks some `impersonate` button. We have had this implemented using `OAuthAuthorizationServerProvider` via `GrantCustomExtension` method before migrated to netcore and OpenIddict. After a user was clicking the button, we were appending a 'target' user id to the request and validated this request. We were preserving impersonator info to be able to make a reverse operation.

<details>
   <summary>Would be better to illustrate this with code.</summary>

   ```
public override async Task GrantCustomExtension(OAuthGrantCustomExtensionContext context)
        {
            switch (context.GrantType)
            {
                case AuthConstants.ImpersonationGrant:
                    await ImpersonateAsync().ConfigureAwait(false);
                    return;
                case AuthConstants.RevertImpersonationGrant:
                    await RevertAsync().ConfigureAwait(false);
                    return;
                default:
                    context.SetError($"Unknown grant_type '{context.GrantType}'!");
                    return;
            }

            async Task ImpersonateAsync()
            {
                var auth = context.Request.Context.Authentication;
                var token = context.Request.Cookies.FirstOrDefault(c => c.Key == AuthConstants.AccessTokenCookie).Value
                            ?? context.Request.Headers.Get(AuthConstants.AuthorizationHeader).Substring(7);

                var oldTicket = context.Options.AccessTokenFormat.Unprotect(token);
                if (!oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Administration_Companies}/{Permissions.All}")
                    && !oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Administration_Users}/{Permissions.All}")
                    && !oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Superuser}/{Permissions.All}"))
                {
                    context.SetError("Impersonation is not allowed!");
                    return;
                }

                var repo = new AuthRepository(context.OwinContext.Get<ApplicationDbContext>(), context.OwinContext.Get<ApplicationUserManager>());
                var user = await repo.FindUserByIdAsync(context.Parameters["userId"]).ConfigureAwait(false);
                if (user == null)
                {
                    context.SetError("invalid_grant", "User with specified ID not found!");
                    return;
                }

                var permissions = repo.GetUserPermissions(user.Id).ToList();
                if (!oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Administration_Companies}/{Permissions.All}")
                    && !oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Superuser}/{Permissions.All}")
                    && permissions.Contains((ModuleConstants.Modules.Administration_Companies, Permissions.All)))
                {
                    context.SetError("You can't impersonate a user with EA role!");
                    return;
                }

                if (!oldTicket.Identity.HasClaim(AuthConstants.ModulePermissionClaim, $"{ModuleConstants.Modules.Superuser}/{Permissions.All}")
                    && permissions.Contains((ModuleConstants.Modules.Superuser, Permissions.All)))
                {
                    context.SetError("You can't impersonate a Superuser!");
                    return;
                }

                if (oldTicket.Identity.HasClaim(AuthConstants.ImpersonationClaim, "true"))
                {
                    context.SetError("You are already impersonated! Please, revert current impersonation before.");
                    return;
                }

                var userName = context.Parameters["username"];
                var origUserId = oldTicket.Identity.GetUserId();

                var allowedOrigins = context.OwinContext.Get<string>("clientAllowedOrigin");
                context.OwinContext.Response.Headers.Add("Access-Control-Allow-Origin", allowedOrigins.Split(','));

                var identity = new ClaimsIdentity(DefaultAuthenticationTypes.ExternalCookie);

                identity.AddClaim(new Claim(ClaimTypes.Name, userName));
                identity.AddClaim(new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "OWIN Provider", ClaimValueTypes.String));
                identity.AddClaim(new Claim(AuthConstants.ImpersonationClaim, "true"));
                identity.AddClaim(new Claim(AuthConstants.OriginalUserIdClaim, origUserId));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, user.Id));

                foreach (var (module, permission) in permissions)
                {
                    identity.AddClaim(new Claim(AuthConstants.ModulePermissionClaim, $"{module}/{permission}"));
                }

                var tokenLifetime = int.Parse(ConfigurationManager.AppSettings[AuthConstants.AccessTokenLifetime]);
                var now = DateTime.UtcNow;
                var expires = now.AddMinutes(tokenLifetime);
                var props = new AuthenticationProperties(new Dictionary<string, string>
                {
                    { AuthConstants.ClientIdOAuth, context.ClientId ?? string.Empty },
                    { "username", userName },
                    { "userId", user.Id },
                })
                {
                    AllowRefresh = true,
                    IssuedUtc = now,
                    ExpiresUtc = expires,
                };

                var ticket = new AuthenticationTicket(identity, props);
                var options = new CookieOptions { Expires = expires };
                auth.SignIn(props, identity);
                context.Response.Cookies.Append(AuthConstants.AccessTokenCookie, context.Options.AccessTokenFormat.Protect(ticket), options);
                context.Validated(ticket);
            }

            async Task RevertAsync()
            {
                var auth = context.Request.Context.Authentication;
                var token = context.Request.Cookies.FirstOrDefault(c => c.Key == AuthConstants.AccessTokenCookie).Value
                            ?? context.Request.Headers.Get(AuthConstants.AuthorizationHeader).Substring(7);

                var oldTicket = context.Options.AccessTokenFormat.Unprotect(token);
                if (!oldTicket.Identity.HasClaim(AuthConstants.ImpersonationClaim, "true"))
                {
                    context.SetError("There no any impersonation existed!");
                    return;
                }

                var origUserId = oldTicket.Identity.Claims.FirstOrDefault(c => c.Type == AuthConstants.OriginalUserIdClaim)?.Value;

                var allowedOrigins = context.OwinContext.Get<string>("clientAllowedOrigin");
                context.OwinContext.Response.Headers.Add("Access-Control-Allow-Origin", allowedOrigins.Split(','));

                var identity = new ClaimsIdentity(DefaultAuthenticationTypes.ExternalCookie);
                identity.AddClaim(new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "OWIN Provider", ClaimValueTypes.String));

                var repo = new AuthRepository(context.OwinContext.Get<ApplicationDbContext>(), context.OwinContext.Get<ApplicationUserManager>());
                var user = await repo.FindUserByIdAsync(origUserId).ConfigureAwait(false);
                if (user == null)
                {
                    context.SetError("invalid_grant", "User with specified ID not found!");
                    return;
                }

                var userName = user.UserName;
                identity.AddClaim(new Claim(ClaimTypes.Name, userName));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, user.Id));

                var permissions = repo.GetUserPermissions(user.Id);
                foreach (var (module, permission) in permissions)
                {
                    identity.AddClaim(new Claim(AuthConstants.ModulePermissionClaim, $"{module}/{permission}"));
                }

                var tokenLifetime = int.Parse(ConfigurationManager.AppSettings[AuthConstants.AccessTokenLifetime]);
                var now = DateTime.UtcNow;
                var expires = now.AddMinutes(tokenLifetime);
                var props = new AuthenticationProperties(new Dictionary<string, string>
                {
                    { AuthConstants.ClientIdOAuth, context.ClientId ?? string.Empty },
                    { "username", userName },
                    { "userId", user.Id },
                })
                {
                    AllowRefresh = true,
                    IssuedUtc = now,
                    ExpiresUtc = expires,
                };

                var ticket = new AuthenticationTicket(identity, props);
                var options = new CookieOptions { Expires = expires };
                auth.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                auth.SignIn(props, identity);
                context.Response.Cookies.Append(AuthConstants.AccessTokenCookie, context.Options.AccessTokenFormat.Protect(ticket), options);
                context.Validated(ticket);
            }
        }
```
</details>

**Comment by kevinchalet** [comment]
Good thing I asked about your scenario (which has indeed not much to do with RFC8693 🤣)

You could implement [a similar thing in OpenIddict using a custom grant](https://stackoverflow.com/questions/40257981/exchanging-a-google-idtoken-for-local-openid-token-c-sharp) but I wouldn't recommend it at all as your implementation - based on cookies - was sadly flawed and prone to CSRF/session fixation attacks.

Since you're using cookie authentication for that, the approach I mentioned in https://github.com/openiddict/openiddict-samples/issues/75#issuecomment-531502199 is the best option.

> The Authorize action fires only twice and both of them at the login process, so how it should be reached within logged user's activity?

An OIDC client can start an authorization code flow at any time. Should the client need to start an authorization code flow with impersonation enforced for a specific user, it could redirect the user agent to the authorization server with the impersonated username in the parameters and if the impersonator was already logged in, it would be a transparent operation.

If you decide to opt for this approach, [the implementation will be very similar to what you have in the Velusia sample](https://github.com/openiddict/openiddict-samples/blob/master/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs), with just a tweak when creating the `ClaimsIdentity` to use the impersonated user claims when impersonation is used. If you use a custom `impersonated_username` parameter sent from the client, it can be resolved server-side this way:

```csharp
var impersonatedUsername = (string?) request["impersonated_username"];
```

> As I realize, authorization happens on a client side until a user's authentication is valid.

I'm not sure I'm following. What do you mean exactly?

> Also, how it is supposed to add some 'impersonation' parameter to request properties?

It depends on the OIDC client stack you're using. With the new OpenIddict client stack introduced in 4.0, it's as easy as adding a value in `AuthenticationProperties.Parameters`. Here's an example that sends an `identity_provider` parameter whose value is set by the client:

https://github.com/openiddict/openiddict-core/blob/00c657340a69d35baba602214f2a173ba014a144/sandbox/OpenIddict.Sandbox.AspNetCore.Client/Controllers/AuthenticationController.cs#L12-L53

**Comment by a-a-k** [comment]
> An OIDC client can start an authorization code flow at any time. Should the client need to start an authorization code flow with impersonation enforced for a specific user, it could redirect the user agent to the authorization server with the impersonated username in the parameters and if the impersonator was already logged in, it would be a transparent operation.

Well, this is the thing I'm mainly asking for. How are we able to enforce client to start authorization?

> The main question I have: how to trigger that request, should I do that using http client or initialize a challenge or somehow else?

**Comment by kevinchalet** [comment]
It's sadly impossible to give you an answer without having more information on the "web client" you're mentioning: is it an ASP.NET Core application? Do you use the MSFT OIDC handler?

**Comment by a-a-k** [comment]
Correct - ASP.NET Core 6, MSFT OIDC handler.

**Comment by kevinchalet** [comment]
You'll need a custom event handler to be able to attach the custom parameter to the authorization request:

```csharp
services.AddAuthentication().AddOpenIdConnect(options =>
{
    // ...

    options.Events.OnRedirectToIdentityProvider = context =>
    {
        if (context.ProtocolMessage.RequestType is OpenIdConnectRequestType.Authentication)
        {
            // Attach the impersonated username resolved from the authentication
            // properties to the request, if one was specified during the challenge.
            var username = context.Properties.GetParameter<string>("impersonated_username");
            if (!string.IsNullOrEmpty(username))
            {
                context.ProtocolMessage.SetParameter("impersonated_username", username);
            }
        }

        return Task.CompletedTask;
    };
});
```

Once it's in place, you can easily attach an `impersonated_username` to the authentication properties to trigger a challenge operation with impersonation:

```csharp
[HttpGet("~/login")]
public ActionResult LogInWithImpersonation(string username)
{
    var properties = new AuthenticationProperties
    {
        RedirectUri = "/"
    };

    if (!string.IsNullOrEmpty(username))
    {
        properties.SetParameter("impersonated_username", username);
    }

    return Challenge(properties, OpenIdConnectDefaults.AuthenticationScheme);
}
```

**Comment by a-a-k** [comment]
Okay, seems I got the answer and become much closer to a completion. I've done with your tips, but by some reason the request can't get authenticated at this [point](https://github.com/openiddict/openiddict-samples/blob/f41688184e383f95dfd9d2774e112dc207111551/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs#L83). What does that mean?

**Comment by kevinchalet** [comment]
Do you use ASP.NET Core Identity to handle the cookie authentication process? If not, you'll need to change the constant to use your custom cookie authentication scheme.

**Comment by a-a-k** [comment]
I've tried to use `CookieAuthenticationDefaults.AuthenticationScheme` instead of `OpenIdConnectDefaults.AuthenticationScheme`, but unfortunately with the same result.

**Comment by kevinchalet** [comment]
Please post your `Startup`/`Program` class.

**Comment by a-a-k** [comment]
<details>
   <summary>Here it goes</summary>

   ```
public class Startup
{
    private readonly IWebHostEnvironment _env;
    private readonly IConfiguration _configuration;

    public Startup(IConfiguration configuration, IWebHostEnvironment env)
    {
        _env = env;
        _configuration = configuration;
    }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllersWithViews()
            .AddHttpExceptions();

        services.AddCors(options =>
            options.AddDefaultPolicy(policy =>
                policy.WithOrigins(_configuration.GetRequiredSection("AllowedHosts").Get<string[]>())
                    .AllowAnyHeader()
                    .AllowAnyMethod()));

        services.AddDbContext<AuthDbContext>(options =>
        {
            if (_env.IsDevelopment())
            {
                options.UseInMemoryDatabase(nameof(AuthDbContext));
            }
            else
            {
                options.UseNpgsql(_configuration.GetConnectionString("AuthDbConnection"));
            }

            options.UseOpenIddict();
        });

        services.AddDbContext<FmsDbContext>(options => options.UseNpgsql(_configuration.GetConnectionString("FmsDbConnection")));

        services.AddIdentity<AspNetUser, AspNetRole>()
            .AddEntityFrameworkStores<FmsDbContext>()
            .AddDefaultTokenProviders();

        services.Configure<IdentityOptions>(options =>
        {
            // Configure Identity to use the same JWT claims as OpenIddict instead
            // of the legacy WS-Federation claims it uses by default (ClaimTypes),
            // which saves you from doing the mapping in your authorization controller.
            options.ClaimsIdentity.UserNameClaimType = OpenIddictConstants.Claims.Name;
            options.ClaimsIdentity.UserIdClaimType = OpenIddictConstants.Claims.Subject;
            options.ClaimsIdentity.RoleClaimType = OpenIddictConstants.Claims.Role;
            options.ClaimsIdentity.EmailClaimType = OpenIddictConstants.Claims.Email;

            options.SignIn.RequireConfirmedAccount = false;
        });

        services.AddScoped<IUserClaimsPrincipalFactory<AspNetUser>, CustomClaimsPrincipalFactory>();
        services.AddTransient<IMessageToSendService, MessageToSendService>();

        services.AddOpenIddict()
            .AddCore(options =>
            {
                options.UseEntityFrameworkCore()
                    .UseDbContext<AuthDbContext>();
            })
            .AddServer(options =>
            {
                options.SetAccessTokenLifetime(TimeSpan.FromDays(7));

                options.AllowClientCredentialsFlow();
                options.UseReferenceAccessTokens();
                options.AllowAuthorizationCodeFlow()
                    .AllowRefreshTokenFlow()
                    .RequireProofKeyForCodeExchange();

                options
                    .SetAuthorizationEndpointUris("/connect/authorize")
                    .SetLogoutEndpointUris("/connect/logout")
                    .SetTokenEndpointUris("/connect/token")
                    .SetIntrospectionEndpointUris("/introspect");

                options
                    .AddEphemeralEncryptionKey()
                    .AddEphemeralSigningKey();

                options.RegisterScopes("openid", "api", "offline_access", "impersonation", "sync_api");

                options
                    .UseAspNetCore()
                    .DisableTransportSecurityRequirement()
                    .EnableTokenEndpointPassthrough()
                    .EnableAuthorizationEndpointPassthrough()
                    .EnableLogoutEndpointPassthrough();
            })
            .AddValidation(options =>
            {
                options.UseLocalServer();
                options.UseAspNetCore();
            });

        services.AddAuthorization();

        services.Configure<List<OpenIddictApplicationDescriptor>>(_configuration.GetRequiredSection("Clients"));
        services.AddHostedService<ClientDefinitionService>();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseHttpExceptions();

        app.UseCors();

        app.UseForwardedHeaders(new ForwardedHeadersOptions
        {
            ForwardedHeaders = ForwardedHeaders.XForwardedProto,
        });

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseStaticFiles();
        app.UseRouting();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapDefaultControllerRoute();
        });
    }
}
```
</details>

**Comment by kevinchalet** [comment]
I meant the server `Startup`, where your `AuthorizationController` is localed 😄

**Comment by a-a-k** [comment]
Oops, sorry ) I've updated previous comment

**Comment by kevinchalet** [comment]
I don't see anything suspicious in the `Startup` configuration. Can you also please share your authorization controller?

**Comment by a-a-k** [comment]
It's just a copy of mentioned Velusia example AuthorizationController with minimal minor adoptions. Need I post it here anyway?

**Comment by kevinchalet** [comment]
Yes please. The devil is always in the details so if things don't work as you expect, there's something wrong somewhere.

**Comment by a-a-k** [comment]
wouldn't be better to give you access to the git repo where the code lies?

**Comment by kevinchalet** [comment]
Yep, that would work too (assuming your company is fine with that 😅)

**Comment by a-a-k** [comment]
There no any sensitive information and business logic. Just sent you invitation (Bitbucket repo). Take a look at `dev` branch, it is most actual.

**Comment by kevinchalet** [comment]
I see an `AccountController` in the `dev` branch. Is it used?

```csharp
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Login(LoginViewModel model)
{
    ViewData["ReturnUrl"] = model.ReturnUrl;

    if (!ModelState.IsValid)
    {
        return View(model);
    }

    var user = await _userManager.FindByNameAsync(model.Username);
    if (user == null)
    {
        return View(model);
    }

    var res = await _signInManager.PasswordSignInAsync(user, model.Password, false, false);
    if (!res.Succeeded)
    {
        return View(model);
    }

    var claims = new List<Claim>
    {
        new(ClaimTypes.Name, user.UserName),
        new(ClaimTypes.NameIdentifier, user.Id),
    };

    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

    await HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));

    if (Url.IsLocalUrl(model.ReturnUrl))
    {
        return Redirect(model.ReturnUrl);
    }

    return Redirect("/");
}
```

There are 2 issues with it:
  - It points to an instance of the cookie authentication handler (`CookieAuthenticationDefaults.AuthenticationScheme`) that doesn't seem to be registered in the `Startup` config.
  - Identity's `PasswordSignInAsync()` already creates and returns a cookie for you, so you're essentially trying to return 2 different authentication cookies as part of the same call, which may hit cookie size limits depending on the browser you're using.

If this controller is used, try to remove the `HttpContext.SignInAsync` call to see if it helps.

**Comment by a-a-k** [comment]
Fixed, but that didn't help :(

**Comment by kevinchalet** [comment]
I tested it locally with IIS Express - after removing all the references to `EyeRide.FMS.Model`, adding a new client entry and a fake Identity user - and it worked flawlessly using Postman with PKCE. So either there's an issue with your machine or there's a problem with how you host that application that causes issues with ASP.NET Core Identity.

![image](https://user-images.githubusercontent.com/6998306/180487204-6cc7c819-6b06-442e-bfe6-0eaba505256d.png)

**Comment by a-a-k** [comment]
Just for sure, are you talking about 'impesonation' or regular authentication?

**Comment by kevinchalet** [comment]
AFAICT, your controller in your `dev` branch doesn't contain any logic for impersonation, so it's just "regular authentication". That said, since it's just a simple request parameter, it's unrelated to the cookie problem you described earlier: you should get an authenticated identity [here](https://github.com/openiddict/openiddict-samples/blob/f41688184e383f95dfd9d2774e112dc207111551/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs#L83) whether you're using impersonation or not.

**Comment by a-a-k** [comment]
If we are talking about regular authentication, then it undoubtedly works. But the issue is, as I said before, that the request doesn't authenticate at this point when user initiates 'impersonation'. So, I'm a bit confused about the subject of discussion.

**Comment by kevinchalet** [comment]
> But the issue is, as I said before, that the request doesn't authenticate at this point when user initiates 'impersonation'. So, I'm a bit confused about the subject of discussion.

As I said, there's no trace of any impersonation logic in your repo and the client app you're mentioning is not even part of that repo. I can't test code that doesn't exist or help you determine whether the logic is good or not if I can't even see it.

**Comment by a-a-k** [comment]
I didn't implement any impersonation logic at the server side yet, just because of the mentioned issue. I just can do nothing with an empty authentication result, regardless there exists some logic after or not.

This is how it looks at the client side - a user clicks the button and 'impersonation' request reaches MVC controller action, where challenge performs. After that, OIDC handler handles redirection request and adds the parameter. Right? Next, authorization endpoint hits at the server side, and it is expected that request should be authenticated, but somehow this not happens. Implementations of the handler and MVC controller action are absolutely the same as you posted before. Can share if needed. Did you have a chance to see client's Startup configuration before I replaced it?

**Comment by kevinchalet** [comment]
> This is how it looks at the client side - a user clicks the button and 'impersonation' request reaches MVC controller action, where challenge performs. After that, OIDC handler handles redirection request and adds the parameter. Right? Next, authorization endpoint hits at the server side, and it is expected that request should be authenticated, but somehow this not happens.

Yes, that's how it should work (and it did work when I tested the snippet I shared earlier so 🤷🏻‍♂️)

> Can share if needed.

If you need additional assistance, yes. This time, please make sure the solution includes all the needed dependencies so I don't have to remove tons of references on my end 😄 

> Did you have a chance to see client's Startup configuration before I replaced it?

It looked fine.

**Comment by a-a-k** [comment]
Well, I definitely need an assistance since I absolutely have no idea what's going wrong. Let me share additional info tomorrow.
BTW, here is how it looks now at the break

![image](https://user-images.githubusercontent.com/5455861/180497854-c0554f3c-cbf5-4f75-b61d-c7b96447c8c4.png)
![image](https://user-images.githubusercontent.com/5455861/180498027-d2ea5426-646f-4039-99bc-062449e21ea5.png)

**Comment by kevinchalet** [comment]
An `AuthenticateResult` with `None` to `true` indicates that no cookie was found in the request headers, so you'll also want to try capturing a Fiddler trace to see if it's sent by the browser or not.

**Comment by a-a-k** [comment]
Uhh! Brilliant, I see that there is no cookie in the request to MVC controller and I know why. Digging into this to fix....

**Comment by a-a-k** [comment]
Is it ok that an `OPTIONS` request sends to `authorize` endpoint before `GET`? This looks weird.

**Comment by kevinchalet** [comment]
Not really. Is that `OPTIONS` request a pre-flight CORS request? (the authorization endpoint should NEVER be used with an API client: it's an interactive endpoint meant to be used with 302 redirects).

**Comment by a-a-k** [comment]
Yeah, exactly pre-flight CORS request. But I have no idea why it appears. Have you? It is definitely not an API client. 

UPD
Okay, I found the cause.

**Comment by kevinchalet** [comment]
> Okay, I found the cause.

Care to share more details? 😄

**Comment by a-a-k** [comment]
Later, I'm full in the process :)

**Comment by a-a-k** [comment]
I figured that out finally. In short - the issue was in the request, it was incorrectly doing via JS service. After getting that fixed, it was really simple to get impersonation to work. Warmest thanks to you for your support! :upside_down_face:

**Comment by kevinchalet** [comment]
As I said...

> The devil is always in the details so if things don't work as you expect, there's something wrong somewhere.

Glad you figured it out 😄

**Comment by jwillmer** [comment]
@kevinchalet I'm looking at a similar use case and have one question regarding your example in this task:

You propose to add a new parameter to the authentication cookie if the parameter value was defined/transferred by the request. That means each app that supports the impersonation of a user has to implement a check if this parameter exists and then use this information to display the (impersonated) username / validate that this user in fact can execute the requested action?

```
context.ProtocolMessage.SetParameter("impersonated_username", username);
```
