### ISSUE TITLE
How get token?

### ISSUE THREAD

**Issue by Alados** [openiddict/openiddict-core#149]
I try connect on server used postman, but can't get access_token.
May be I do not understand what a few parameters means.
Why in scope required openid, if not add him, displays it: 
"error: invalid_request
error_description: openid scope missing"

What is nonce?
I dont now what is it, and get this:
"error: invalid_request
error_description: nonce parameter missing"

Pls, help me understanding how to use you technology=)

**Comment by kevinchalet** [comment]
> Why in scope required openid, if not add him, displays it: 
> "error: invalid_request
> error_description: openid scope missing"

You're likely trying to use a `response_type` that includes `id_token`. In this case, you must request the `openid` scope.

> What is nonce?
> I dont now what is it, and get this:
> "error: invalid_request
> error_description: nonce parameter missing"
> 
> REQUIRED. String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. Sufficient entropy MUST be present in the nonce values used to prevent attackers from guessing values. One method to achieve this is to store a cryptographically random value in HTML5 local storage and use a cryptographic hash of the value as the nonce parameter. In that case, the nonce in the returned ID Token is compared to the hash of the value in local storage to detect ID Token replay by third parties.

http://openid.net/specs/openid-connect-implicit-1_0.html#RequestParameters

**Comment by Alados** [comment]
Thank, this problem resolved. But i meet new problem. Was not found my redirect_uri. May be may get token without that? I have mobile application and for authorization need have token.

**Comment by kevinchalet** [comment]
Are you still facing this issue? If so, please post more details.

**Comment by petedavis** [comment]
Hey @PinpointTownes, I found a way to invoke this behaviour. Using Postman to request a token, if you add openid to the list of scopes then you will get this error. Is this expected behaviour?

![image](https://user-images.githubusercontent.com/164331/49058430-e8fe7e00-f253-11e8-92d6-a773a5dc9329.png)

**Comment by kevinchalet** [comment]
@petedavis hey.

Yep, it's completely expected: in OpenID Connect, implicit flow requests must include a nonce, which is unfortunately not sent by Postman (which is a pure OAuth2 client).

To avoid that, simply don't send the `openid` scope: OpenIddict will fall back to a "legacy" mode and accept your `response_type=token` request, even if it doesn't include `nonce`, which would be required for an OpenID Connect request.
