### ISSUE TITLE
Single-Sign-Off does not work after upgrade 

### ISSUE THREAD

**Issue by feededit** [openiddict/openiddict-core#1492]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x (in preview)

### Describe the bug

upgraded Velusia.Client to 4.0.
everything works fine.

But when Velusia.Client logs off,
Velusia.Server is not logged off.

### To reproduce

Original unmodified Velusia.Client sample

**Comment by kevinchalet** [comment]
It's not a bug: the OpenIddict client doesn't support logout yet.

**Comment by feededit** [comment]
And what certificate does Velusia.Client use?

1. Using the certificate from the Velusia.Client sample as is

2. Jointly use the already installed certificate with Velusia.Server.

3. Do I need to create a new client certificate?

**Comment by kevinchalet** [comment]
> Do I need to create a new client certificate?

Yep, it's the right option: generate a new pair of signing and encryption certificates just like you did for the server certificates.

I opened https://github.com/openiddict/openiddict-core/issues/1496 to track adding logout support in the client.

**Comment by kevinchalet** [comment]
@feededit FYI, logout support was added in 4.0.0-preview3, that was released today: https://github.com/openiddict/openiddict-core/releases/tag/4.0.0-preview3

Both the Velusia and Mortis client samples were updated to target preview3:
  - https://github.com/openiddict/openiddict-samples/tree/dev/samples/Velusia/Velusia.Client
  - https://github.com/openiddict/openiddict-samples/tree/dev/samples/Mortis/Mortis.Client

**Comment by feededit** [comment]
> Note: when only one client is registered in the client options, setting the issuer property is not required and can be omitted.


Ask about [client options].



### LogIn


    public ActionResult LogIn(string returnUrl)
    {
        var properties = new AuthenticationProperties(new Dictionary<string, string>
        {
            // [OpenIddictClientAspNetCoreConstants.Properties.Issuer] = "https://localhost:44313/"
        })

         ~~~~~~

    }



### LogOut

    public async Task<ActionResult> LogOut(string returnUrl)
    {
        var properties = new AuthenticationProperties(new Dictionary<string, string>
        {
            //[OpenIddictClientAspNetCoreConstants.Properties.Issuer] = "https://localhost:44313/",
            //[OpenIddictClientAspNetCoreConstants.Properties.IdentityTokenHint] = result.Properties.GetTokenValue(OpenIddictClientAspNetCoreConstants.Tokens.BackchannelIdentityToken)
         }

         ~~~~~~~
    }









login works.  

but why doesn't logout work?

**Comment by feededit** [comment]
[HttpPost("~/logout"), ValidateAntiForgeryToken]
    public async Task<ActionResult> LogOut(string returnUrl)
    {


It's not an error, but I fixed it like this:

    [HttpGet("~/logout"), HttpPost("~/logout"), ValidateAntiForgeryToken]
    public async Task<ActionResult> LogOut(string returnUrl)
    {
