### ISSUE TITLE
Implement RP-initiated logout in the client stack

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1496]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

**Comment by feededit** [comment]
Velusia.Server is the old version and  Velusia.Client is the new version.


```
return SignOut(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
```

How does signout() work?

**Comment by feededit** [comment]
When will you complete  adding logout support in the client?

**Comment by kevinchalet** [comment]
@feededit support will be available in the next preview.
