### ISSUE TITLE
Client secrets must always be hashed according to ValidateClientSecretAsync

### ISSUE THREAD

**Issue by Thodor12** [openiddict/openiddict-core#1501]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

I've been getting errors in my logs saying that my introspection requests are failing because the client_secret is not a base64 string, this is because I just put a GUID in there for testing purposes.

If you create applications through the OpenIddict manager instance it will automatically hash your client_secret, but even the examples tell you to (preferably) do this via setup scripts, unless you hash these to the exact specification that OpenIddict wants them, these will always fail which is not that nice.

I see two ways this could be remedied:
- Provide some short documentation on how to create a viable hashed client secret manually, in case you want to setup using SQL scripts or some other form.
- Make the [ObfuscateClientSecretAsync](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L1339) a public (static) method so we could use it elsewhere (for example in EF Core HasData())

Also as a sidenote, some documentation regarding the different fields of the application would be nice, there's a lot of conditions for creating an application which are not documented if you want to create them manually (for example the type of the application must not be public if you want to use a client secret)

**Comment by kevinchalet** [comment]
> If you create applications through the OpenIddict manager instance it will automatically hash your client_secret, but even the examples tell you to (preferably) do this via setup scripts

By scripts, I didn't exactly have "SQL scripts" in mind, but more like minimal setup helper applications that help bootstrap the initial database and use the managers to populate it if necessary.

Bypassing the managers and directly populating the database is not a supported scenario and definitely not something I want to encourage: as you said, the managers (not just the app' one) enforce a lot of validation rules that are not checked if you manually populate the database.

I'll update the samples to clarify what I meant by "scripts" 😃

**Comment by Thodor12** [comment]
In that case I just interpreted the meaning of scripts wrong, thanks for the clarification.
I'll just use the manager classes if that is the intended way, thanks!
