### ISSUE TITLE
OpenIddict Refresh-Token for native Xamarin.Forms app

### ISSUE THREAD

**Issue by flyfear** [openiddict/openiddict-core#1502]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

Hello, we are using the OpenIddict server to authorize on the site, and we are also trying to connect the authorization of the Xamarin.Forms application, which should receive Access-token and Refresh-Token.

When setting scope = 'openid' , getting the Identity-token works fine, however when expanding to scope = "openid offline_access" we immediately get the following message:

_error:invalid_request
error_description:The client application is not allowed to use the 'offline_access' scope.
error_uri:https://documentation.openiddict.com/errors/ID2065_

This issue affects the Android app, it has not been tested on iOS/iPhone.
In Xamarin, we use the IdentityModel.OidcClient v 4.0+ library.
In general, the OidcClient settings are taken from the article:
https://mallibone.com/post/xamarin-oidc
In which direction to look for the key to the problem?

**Comment by kevinchalet** [comment]
Hi,

You likely forgot to add `OpenIddictConstants.Permissions.GrantTypes.RefreshToken` to the list of permissions granted to that specific client: https://documentation.openiddict.com/configuration/application-permissions.html#grant-type-permissions.

**Comment by a-a-k** [comment]
wouldn't be enough just add it as a plain string `offline_access`?

**Comment by a-a-k** [comment]
`["ept:authorization","ept:token","gt:authorization_code","gt:client_credentials","scp:openid","scp:sync_api","scp:offline_access","rst:code"]`

I took out that permissions from OpenIddict db, so that client has that grant type

**Comment by kevinchalet** [comment]
> I took out that permissions from OpenIddict db, so that client has that grant type

No, it doesn't 😄

**Comment by a-a-k** [comment]
the scope `offline_access` does not grant this permission?

**Comment by a-a-k** [comment]
arrgghh, I compared with other clients and now I see
