### ISSUE TITLE
Database store support for LinqToDB

### ISSUE THREAD

**Issue by timbze** [openiddict/openiddict-core#1503]
### Confirm you've already contributed to this project or that you sponsor it

- [ ] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

I'm working on adding LinqToDB support by using EntityFrameworkCore and MongoDb as references. Is this something you'd be interested to add to this repo? Would you be happy for a PR?

**Comment by kevinchalet** [comment]
Thanks for your offer! Unfortunately, maintaining many stores on the long term has a very high cost and the demand for LinqToDB is sadly way too low to justify having "official" support (you're the first one mentioning it here).

That said, I'd encourage you to open source them and release them under your own name on NuGet. If you're fine with that, I can add a link in the docs to mention your work 😃 

Cheers.

**Comment by timbze** [comment]
Ok no worries! 😄 

What is good and acceptable practice regarding the namespace? Should I use OpenIddict.LinqToDB, or should I rather use something else instead of OpenIddict?

I'll let you know when it's done so you can link to it if you wish.

**Comment by kevinchalet** [comment]
> Should I use OpenIddict.LinqToDB, or should I rather use something else instead of OpenIddict?

The `OpenIddict` prefix is reserved so you'd get an error if you tried to upload a package named `OpenIddict.LinqToDB`.
The recommended approach is to name it `[name of your company].OpenIddict.LinqToDB` or `[your name].OpenIddict.LinqToDB`.

Let me know if you need any additional information 😃

**Comment by timbze** [comment]
Great, thanks!

**Comment by timbze** [comment]
Hey Kevin, I'm about done with [the library](https://github.com/TecMeet/tecmeet-openiddict-linq2db) (without actual testing yet)... I'm wondering about tests for Stores, e.g. `OpenIddictEntityFrameworkCoreApplicationStore`, I don't find any tests for that class, and the other 3 Stores. Have they just not been created or am I not finding them?

Do you think unit tests would be beneficial or should it rather be integration tests so that db functionality is properly tested?

**Comment by kevinchalet** [comment]
Hey,

> Have they just not been created

Yep. It was on my radar at some point but I never had enough time to work on that. As you said, such tests would need to be integration tests to be truly useful. The code in the stores is fairly boring as they are basically simple wrappers around the underlying provider methods: all the interesting parts (persistence and queries) are actually evaluated by the provider itself.

Setting the infrastructure needed to configure disposable databases (SQL Server, MongoDB) and adding the integration tests for the 3 supported providers is likely not going to be a trivial task and there's likely quite some time to spend on that, but would you be interested in contributing? 😃

**Comment by timbze** [comment]
Hmm it does seem like a huge job that I won't have enough time for at this point. I realized that the stores have a quite a few methods that don't use the database and can be perfectly tested with unit tests. I started with ApplicationStore and already spent a few hours to get it mostly covered, but whew! Will have to see when I can take more time to continue with the other 3 stores.
