### ISSUE TITLE
Keycloak

### ISSUE THREAD

**Issue by Bazaillion** [openiddict/openiddict-core#1534]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be implemented in the near future without my contribution.

### Provider name

Keycloak

### Provider address

keycloak.org

### Documentation page

https://www.keycloak.org/documentation

### OpenID Connect discovery/OAuth 2.0 authorization server metadata support

- [ ] The provider doesn't support OpenID Connect discovery or OAuth 2.0 authorization server metadata and requires using static configuration.

### Additional context

https://www.keycloak.org/getting-started/getting-started-docker

http://localhost:8080/realms/<your realm>/.well-known/openid-configuration

**Comment by kevinchalet** [comment]
Hum, looks like my message wasn't sent correctly when I posted it.

Thanks for your suggestion.
I went ahead and added support for Keycloak as part of the 4.0.0-preview4 release: https://www.nuget.org/packages/OpenIddict.Client.WebIntegration/4.0.0-preview4.22517.68. Don't hesitate to test it and share your feedback.

Cheers.
