### ISSUE TITLE
scopes format in access token

### ISSUE THREAD

**Issue by salimz1** [openiddict/openiddict-core#1541]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

Hi Kevin,
We would like to have scopes format in access token as an array. However whenever request include standard scopes "openid offline_access" it always shows a string in the access token using JWT.io. When there is no standard scopes (openid offline_access included) with custom scopes , the format in access token is coming properly that is an array of scopes.  
e.g  **"scope": [
    "attributes",
    "audittrails" ]**
The moment i includes standard scopes in the request, we get the following response from access token( from jwt.io).
**scope": "openid offline_access attributes boxes.**
i tried with this code in connect/token endpoint, still behaviour is same as mentioned above.
  
claimsPrincipal.SetScopes(request.GetScopes());
Also tried this
--------------------------
  var scopes = new[]
                        {
                            /* openid: */ 
                            OpenIdConnectConstants.Scopes.OpenId,
                            OpenIdConnectConstants.Scopes.OfflineAccess
                              }.intersect(scopeArray);
                        claimsPrincipal.SetScopes(scopes);

Please assist to get the scopes in access token in array format not as string

**Comment by salimz1** [comment]
Sponsored.

**Comment by salimz1** [comment]
[github-salimz1-receipt-2022-10-19.pdf](https://github.com/openiddict/openiddict-core/files/9820225/github-salimz1-receipt-2022-10-19.pdf)

**Comment by kevinchalet** [comment]
Hi,

In OpenIddict 3.x, the public `scope` claim is always represented as a space-separated string in access tokens, as required by the specification: https://datatracker.ietf.org/doc/html/rfc9068#section-2.2.3 (https://datatracker.ietf.org/doc/html/rfc9068#section-3).

OpenIddict's `GetScopes()`/`SetScopes()` use private `oi_scp` claims that are mapped from/to `scope` at runtime, so you can do `principal.GetScopes()` or `principal.FindAll("oi_scp")` to get all the values as individual claims.

Cheers.

**Comment by shao200** [comment]
var token = await HttpContext.GetTokenAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                OpenIdConnectParameterNames.AccessToken);
                var t = await blogClient.GetBlogsAsync(token, ct);
I got the token, but I can't access the API using the method below:
 public async Task<Blog[]> GetBlogsAsync(string token, CancellationToken ct)
        {
            _client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);
            var responseMessage = await _client.GetAsync("api/v2/blog/list", ct);
            responseMessage.EnsureSuccessStatusCode();
            var stream = await responseMessage.Content.ReadAsStreamAsync(ct);
            return await JsonSerializer.DeserializeAsync<Blog[]>(stream, _options, ct);
        }
In the zirku project in sample, too, the API is not accessible, depressed...
