### ISSUE TITLE
Make phone number requestable via scope

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#155]
Hey,

is there a possibility to make the phone requestable via a "phone" scope parameter. The OpenID Connect draft mentions phone as optional scope parameter.

The discovery document also has phone in the response:

`"scopes_supported": [
    "openid",
    "profile",
    "email",
    "phone",
    "roles",
    "offline_access"
  ],`

Thanks in advance

**Comment by kevinchalet** [comment]
Hey.

@nklap would you like to submit a PR to update `OpenIddictUserManager.CreateIdentityAsync`? :smile:

**Comment by kevinchalet** [comment]
Closing, as `OpenIddictUserManager.CreateIdentityAsync` is no longer a thing.
