### ISSUE TITLE
ETA for 4.x

### ISSUE THREAD

**Issue by SebastianStehle** [openiddict/openiddict-core#1567]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

Hi,

do you have an ETA for 4.x or will your provide an update for 3.x and .NET 7. I am not in hurry, I just want to plan it.

**Comment by kevinchalet** [comment]
Hi Sebastian,

OpenIddict 4.0 RTM is expected to ship early December so our friends at Volosoft can use it in ABP 7.0 😃 

In the meantime, OpenIddict 3.1.1 works fine on ASP.NET Core 7 and only requires using an ASP.NET Core compatibility switch when the validation _xor_ server feature is used alone without any other authentication handler (e.g ASP.NET Core Identity). More information here: https://github.com/dotnet/aspnetcore/issues/44661.

If possible, I'd encourage you to start playing with the 4.0.0 preview6 nightly builds on MyGet to see whether you may be affected by the PR that sealed most of the infrastructure classes (in theory no, as the types that were sealed were not supposed to be subclassed 😄) There are also breaking changes in the `AddClaim(s)` extension detailed in this blog post: https://kevinchalet.com/2022/06/22/openiddict-4-0-preview1-is-out/

Cheers.

**Comment by SebastianStehle** [comment]
Btw: This is the switch you have to turn on:

```
AppContext.SetSwitch("Microsoft.AspNetCore.Authentication.SuppressAutoDefaultScheme", true);
```

Also mentioned here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/default-authentication-scheme

**Comment by kevinchalet** [comment]
@SebastianStehle yup, that's the right one. Is Squidex affected?

**Comment by SebastianStehle** [comment]
I have not upgraded Squidex yet, I am working on https://github.com/notifo-io/notifo as a first test. To be honest I have no idea whether I am affected or not, if the flag helps I will just turn it on for now ;)

**Comment by kevinchalet** [comment]
> I have not upgraded Squidex yet, I am working on https://github.com/notifo-io/notifo as a first test.

Nice. Don't hesitate to keep me informed 😃 

> To be honest I have no idea whether I am affected or not, if the flag helps I will just turn it on for now ;)

In practice, applications that are affected are in most cases microservice-oriented authorization servers that only use the OpenIddict server feature without Identity. Not sure if it's your case or not 😄

**Comment by SebastianStehle** [comment]
No, usually you have at least 5 authentication methods I guess:

* Cookie
* Google
* Github
* Microsoft
* OpenIdDict

The migration was incredibly smooth. A few nullable changes, in 3-4 files, but thats it.

**Comment by kevinchalet** [comment]
Closing, as OpenIddict 4.0 RTM was released yesterday. You can read https://kevinchalet.com/2022/12/23/openiddict-4-0-general-availability/ for more information.
