### ISSUE TITLE
How to use existing ClientId/Secret from IdentityServer4

### ISSUE THREAD

**Issue by paluru1** [openiddict/openiddict-core#1578]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x (in preview)

### Question

Hi, 

Currently we are using IdentityServer4 and planning to use OpenIddict, but we would like to keep the existing Auth DB so that there should not be any impact on existing clients to use the same ClientId/Secret.
 
Please let me know the possibility to use the existing ClientId/Secret, the secret was generated by using SHA256 algorithm.

Here is the SQL code to generate and store the secret . 
@Secret - will be shared with client

 DECLARE @Secret varchar(50) = REPLACE(LOWER(NEWID()), '-', '')
		  DECLARE @BinarySecret nvarchar(4000) = CONVERT(nvarchar(4000), CONVERT(VARBINARY(MAX), @secret));  
		  DECLARE @Base64EncodedSecret nvarchar(250) = (SELECT CAST(HASHBYTES('SHA2_256', @BinarySecret) as varbinary(max)) FOR XML PATH(''), BINARY BASE64)

Greatly appreciated for any help and support.

Thanks,
Prasad Aluru

**Comment by kevinchalet** [comment]
Hi @paluru1,

> Greatly appreciated for any help and support.

As indicated in the issue template, support is reserved to sponsors. If you need dedicated assistance, please consider becoming a sponsor 😃 

Cheers.

**Comment by paluru1** [comment]
Hello Kevin & Team

Hope all is well and Thank you for your response.

This is Prasad Aluru(Principal Software engineer) & Kasi Gogula(Sr Development Manager) from BlackBerry .
As I mentioned in the ticket below, we are planning to switch from IdentityServer4 to OpenIddict and we would like to know more details for the items below.

We are planning to sponsor or ready to purchase enterprise license.


  1.  Is OpenIddict will support for  SSO, MFA(multifactor Authentication) and Certificate?
  2.  What is the possibility to use the existing ClientId/Secret which is generate through IdentityServer4, the secret was generated by using SHA256 algorithm.
  3.  What is the support process for functional & implementation help, is there any contact number?
  4.  License Pricing or Sponsor ship amount details.

Greatly appreciated for your help and support.

Thanks & Regards,
Prasad
510-396-4662
