### ISSUE TITLE
RoleManager.SupportsRoleClaims

### ISSUE THREAD

**Issue by brunombsilva** [openiddict/openiddict-core#158]
I'm trying to add claims to roles, and I'm getting them with the user claims.

In OpenIddict.OpenIddictUserManager.CreateIdentityAsync SupportsUserRole is checked, and roles are added as claims, but SupportsRoleClaims is not supported.

In Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory we have something like

``` c#
 if (UserManager.SupportsUserRole)
            {
                var roles = await UserManager.GetRolesAsync(user);
                foreach (var roleName in roles)
                {
                    id.AddClaim(new Claim(Options.ClaimsIdentity.RoleClaimType, roleName));
                    if (RoleManager.SupportsRoleClaims)
                    {
                        var role = await RoleManager.FindByNameAsync(roleName);
                        if (role != null)
                        {
                            id.AddClaims(await RoleManager.GetClaimsAsync(role));
                        }
                    }
                }
            }
```

It this a bug/not implemented feature, or was it a design decision? I'll solve this problem in my app by extending the OpenIddictUserManager, but I can submit a pull request if you wish.

**Comment by brunombsilva** [comment]
Actually, maybe OpenIddict.OpenIddictUserManager.CreateIdentityAsync usage should be replaced by a Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory implementation

**Comment by kevinchalet** [comment]
> It this a bug/not implemented feature, or was it a design decision?

This was indeed a deliberate decision. Keeping access/identity tokens to a reasonable size is one of our most important constraints (a very annoying one, TBH). Yet, people are often tempted to attach tons of custom claims with the roles they create, which can potentially make tokens quite big.

That said, if a majority of people vote to include them, I'm not opposed to implementing this feature.

> Actually, maybe OpenIddict.OpenIddictUserManager.CreateIdentityAsync usage should be replaced by a Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory implementation

Maybe. But it's quite hard to flow the scopes as a parameter using this interface.

**Comment by brunombsilva** [comment]
Fair enough. I'll add these claims just for my use-case. Another issue that I've bumped into is the fact that the connect/userinfo endpoint doesn't use CreateIdentityAsync, so it's kind of cumbersome to add custom claims.

**Comment by kevinchalet** [comment]
Closing as obsolete.

Note: with https://github.com/openiddict/openiddict-core/pull/237 being now merged, you're entirely responsible of choosing the claims you want to include in the tokens.
