### ISSUE TITLE
Using with Blazor BFF, with shared cookies and JWT Authorization 

### ISSUE THREAD

**Issue by devv-guru** [openiddict/openiddict-core#1584]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

Hi Kevin

I need some help with an issue.

I have a OpenIdDict server and a Blazor BFF app.
At the moment the two apps share a cookie using a shared KeyRing, as I have a situation where when a request is sent to my BFF api, it redirects to a protected page on the id server(this page make some change to the users field like a tenantId or if a user has accepted the privacy policy), and once the page has been actioned it would then redirect back to the client app with the new claims in the cookie and openid flow will then get the new tokens from the Idserver.

I'm at a point now where I need to start doing calls from the BFF api to my id server api using the current user token, but every time I hit the endpoint the Id server returns my login page I have tried using the JwtBearerDefaults.AuthenticationScheme and OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme for the endpoint on the id server but both have the same issue.

I'm guessing this would something simple like adjusting the validation on the server but I'm not sure how exactly, any help will be appreciated.

**Comment by kevinchalet** [comment]
Hey @Deon-v,

Did you take a look at the Dantooine sample to see how it implements the BFF pattern? https://github.com/openiddict/openiddict-samples/tree/dev/samples/Dantooine

To help you, I'd need to see some code (at least the logs and the Startup config 😃)

Cheers.

**Comment by devv-guru** [comment]
Hey @kevinchalet 

Yes I used it as my go to, I need to get home now, but I will send you a sample solution tomorrow.

**Comment by devv-guru** [comment]
@kevinchalet [Here](https://github.com/Deon-v/openidditsharedcookie) is an example project.

So basically my OpenIdDict server need to support Cookie and JWT Authorization in it's self.

**Comment by devv-guru** [comment]
Btw, I Love the library!

**Comment by devv-guru** [comment]
@kevinchalet I may have found the issue, I'm using [FastEndpoints](https://github.com/FastEndpoints/FastEndpoints) and i think there is some issue with how they try and use the validation.

Is there a way that i can specify .AddJwtBearer(options => ) at startup to then use JwtBearerDefaults.AuthenticationScheme for the fast endpoints?

**Comment by devv-guru** [comment]
@kevinchalet Turns out I'm just dumb, you can close the issue

**Comment by kevinchalet** [comment]
Thanks for the (great) repro! Sadly, it seems I'm late to the party 😄

I didn't know FastEndpoints so your app was a good opportunity to try it.
In case it could help others, the root cause was actually quite interesting:

To return a response from a "fast endpoint," you need to call `SendAsync()` from `HandleAsync()`: the first parameter is the object to return and the second one is the HTTP status code. The thing is if you use `default` for the second parameter, it ends up returning a `0` HTTP response, which doesn't indicate a successful response (and that's why `HttpClient` throws an exception when calling that endpoint)

```csharp
public override async Task HandleAsync(CancellationToken ct)
{
    await SendAsync(new List<string> { "some data", "more data", "loads of data" }, default, ct);
}
```

Cheers.

**Comment by kevinchalet** [comment]
> Btw, I Love the library!

Thanks for your kind words ❤️

**Comment by devv-guru** [comment]
@kevinchalet If you want I can make a bit of a more usable/practical example of the repo
