### ISSUE TITLE
How to use SetDestinations in 4.0.0preview6?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1585]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x (in preview)

### Question

I upgraded my OpenIddct server from 3.1.1 to the lastest nightly build in order to avoid the workaround with the `AppContext` switch. I have a breaking change when adding claims.

How do I upgrade the following code?

```csharp
identity.AddClaim(Claims.Subject, await applicationManager.GetClientIdAsync(application),
    Destinations.AccessToken, Destinations.IdentityToken);

identity.AddClaim(Claims.Name, await applicationManager.GetDisplayNameAsync(application),
    Destinations.AccessToken, Destinations.IdentityToken);
```

I also have a resource server that uses the following packages to connect to my OpenIddict server:

- OpenIddict.Server.AspNetCore
- OpenIddict.Validation.AspNetCore
- OpenIddict.Validation.SystemNetHttp

All are still on 3.1.1. Do I need to upgrade these to the latest nightly build to match the authorization server or can they stay at this version?

**Comment by kevinchalet** [comment]
Hi,

> I have a breaking change when adding claims.

As mentioned in https://kevinchalet.com/2022/06/22/openiddict-4-0-preview1-is-out/, these extensions have been removed in 4.0. Instead, you're encouraged to use either `Claim.SetDestinations(...)` or the one-shot `ClaimsIdentity.SetDestinations()`/`ClaimsPrincipal.SetDestinations()` extension:

```csharp
identity.SetDestinations(static claim => claim.Type switch
{
    Claims.Name => new[] { Destinations.AccessToken, Destinations.IdentityToken },

    _ => new[] { Destinations.AccessToken }
});
```

Note: canceling monthly sponsorships immediately after your question is answered (as you did for the two previous tickets) is not exactly the spirit of the sponsorship program, that encourages long term support of projects. I can't - of course - prevent you from doing that, but please note your next question may not get an answer.

**Comment by cryo75** [comment]
Thanks. Where there any database changes from 3.1.1 to 4.0? Or will 4.0 work fine with a database created in 3.1.1 and vice-versa?

**Comment by kevinchalet** [comment]
There are no database changes between 3.1.1 and the 4.0 previews and it's likely there won't have any in RTM.

**Comment by cryo75** [comment]
Thanks.
