### ISSUE TITLE
Access/refresh token in OpeniddictClient signin callback with Microsoft provider

### ISSUE THREAD

**Issue by emanuelecastelli** [openiddict/openiddict-core#1588]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x (in preview)

### Question

Hi @kevinchalet , 
i'm using Opeinddict Client to perform external provider login before issue a token with Opeinddict server (the flow is barely the same seen in sandbox Client, with `authorize` endpoint secured by `[Authorize]` decorator).
I use Microsoft AzureAD as authentication and after sign in i would like to save access/refresh token for future validation (handling eventually user disconnection from Azure or user removal from Azure Client).
My problem is that in sign in callback i find only `authentication_code` and `backchannel_token` in Azure response,  that are inconsistent for a refresh token request.

If i try to do an `authorization_token` request to Microsoft (the second half of auth code flow), i got this error `AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE` (it is correct as we use PKCE).

My question is: how can i retrieve an access/refresh token from Azure by using Openiddict Client and Microsoft, or, in alternative, where i can find the `code_verifier` issued by Openiddict Client during first `Challenge()` 

I post an extract from my `AuthorizationCOntroller`

```c#
 [Authorize]
        [HttpGet("~/connect/authorize")]
        [HttpPost("~/connect/authorize")]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> Authorize(CancellationToken cancellationToken = default) {
// do regular flow
}

 [HttpGet("~/login")]
        public ActionResult LogIn([Required][FromQuery(Name = "provider")] string provider, [Required][FromQuery(Name = "ReturnUrl")] string returnUrl)
        {
            var items = new Dictionary<string, string?> { [OpenIddictClientAspNetCoreConstants.Properties.ProviderName] = provider };
            var properties = new AuthenticationProperties(items);
            properties.RedirectUri = returnUrl;

            return Challenge(properties, OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
        }

 [HttpGet("~/signin-{provider}"), HttpPost("~/signin-{provider}")]
        public async Task<IActionResult> LogInCallback(CancellationToken cancellationToken = default){
// Retrieve the authorization data validated by OpenIddict as part of the callback handling.
            var result = await HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);

            if (result.Properties == null)
            {
                throw new Exception("Request properties not found in authentication cookie issuer process.");
            }

// ....

// here i would like to retrieve refresh token, but it is null
 var tokens = result.Properties.GetTokens();

            var authCode = tokens.FirstOrDefault(token => token.Name.Equals(OpenIddictClientAspNetCoreConstants.Tokens.AuthorizationCode));
            var backChannelAccessToken = tokens.FirstOrDefault(token => token.Name.Equals(OpenIddictClientAspNetCoreConstants.Tokens.BackchannelAccessToken));
            var backchannelIdentityToken = tokens.FirstOrDefault(token => token.Name.Equals(OpenIddictClientAspNetCoreConstants.Tokens.BackchannelIdentityToken));
            var refreshToken = tokens.FirstOrDefault(token => token.Name.Equals(OpenIddictClientAspNetCoreConstants.Tokens.RefreshToken));

// alternatively iwould like to issue access/refresh token by myself, but i dont't know to extract code_verifier 
            await RequestAccessToken(authCode!.Value);

// ....  
            return Redirect(properties.RedirectUri!);
}

private async Task RequestAccessToken(string authCode)
        {
            var client = new HttpClient();
            var uri = $"{_configuration.GetValue<string>("AzureAd:Instance")}{_configuration.GetValue<string>("AzureAd:TenantId")}/oauth2/v2.0/token";
            var pairs = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("client_id", $"{_configuration.GetValue<string>("AzureAd:ClientId")}"),
                new KeyValuePair<string, string>("client_secret", $"{_configuration.GetValue<string>("AzureAd:ClientSecret")}"),
                new KeyValuePair<string, string>("grant_type", "authorization_code"),
                new KeyValuePair<string, string>("code", authCode),
                new KeyValuePair<string, string>("redirect_uri", $"{_configuration.GetValue<string>("AzureAd:RedirectUri")}"),
                new KeyValuePair<string, string>("scope", "User.Read profile openid email"),
                new KeyValuePair<string, string>("code_verifier", "missing")
             };

            var content = new FormUrlEncodedContent(pairs);

            var response = await client.PostAsync(uri, content);

            string result = string.Empty;

            if (response.IsSuccessStatusCode)
            {

                result = response.Content.ReadAsStringAsync().Result;
            }

            Console.WriteLine(result);
            Console.ReadLine();
        }
```

**Comment by kevinchalet** [comment]
Hi.

1) redeeming the code yourself is not a supported scenario as it's already done by the OpenIddict client transparently. If the server implements authorization code detection replay, it's likely the authorization would be revoked anyway when doing that.

2) the root cause is likely very simple, like forgetting to request the `offline_access` scope.

**Comment by emanuelecastelli** [comment]
> Hi.
> 
> 1. redeeming the code yourself is not a supported scenario as it's already done by the OpenIddict client transparently. If the server implements authorization code detection replay, it's likely the authorization would be revoked anyway when doing that.
> 2. the root cause is likely very simple, like forgetting to request the `offline_access` scope.

Thanks @kevinchalet ,
i had completely missed the `AddScopes` in WebProvider configuration.
Now `refresh_token` is correctly issued by AzureAD.

Cheers.
