### ISSUE TITLE
Implement automatic scope support

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#16]

**Comment by damccull** [comment]
What IS this? No description provided...pretty vague. :)

**Comment by singlewind** [comment]
fetch scope definition from data store and filter and patch claims, if I understand correctly.

**Comment by kevinchalet** [comment]
Reassigned.

**Comment by ilmax** [comment]
@damccull @singlewind you are correct, we could provide a little infrastructure around scope management because in some scenario the scopes issued in the token can be a subset of the scopes requested by the client RPs

**Comment by kevinchalet** [comment]
Note: we now offer an option to control the exposed scopes. Scopes handling is made in user code and there's no plan to change that.
