### ISSUE TITLE
Postgres exception 42P01: relation "Scopes" does not exist when reading from DB

### ISSUE THREAD

**Issue by a-a-k** [openiddict/openiddict-core#1612]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

I'm getting this exception while trying to construct some wrap around our Auth Server for direct managing data purpose (we don't consider using some out-of-the-box solutions, like OpenIdDictUI, for now). The code I'm using to get this exception is   
```
  [Route("scope")]
  [HttpDelete]
  public async Task<string> DeleteScopeAsync(string scopeId, [FromServices] OpenIddictScopeManager<Scope> scopeManager)
  {
      var scope = await scopeManager.FindByIdAsync(scopeId) ?? throw new BadHttpRequestException("Invalid data.");
      await scopeManager.DeleteAsync(scope);
      return scopeId;
  }
```
This throws on the `FindByIdAsync` execution.
The `Scope` entity inherits as   
```
public class Scope : OpenIddictEntityFrameworkCoreScope<string>
{
}
```
Core services registered as   
```
builder.Services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore()
            .UseDbContext<AuthDbContext>()
            .ReplaceDefaultEntities<Application, Authorization, Scope, Token, string>();
    })
```
Database looks this way (only the expanded table has extended schema)   

![image](https://user-images.githubusercontent.com/5455861/205877233-437ee49a-713f-4a3f-85b2-a1c412dddb3c.png)

Could you say, what is wrong configured?

**Comment by kevinchalet** [comment]
> Could you say, what is wrong configured?

Nope. Do you get a similar issue without the custom entities? And with a different DB provider?

**Comment by a-a-k** [comment]
> Do you get a similar issue without the custom entities? And with a different DB provider?

I did not try yet.

**Comment by kevinchalet** [comment]
Closing for now, but feel free to re-open if necessary 😃
