### ISSUE TITLE
Receive error_description:The specified token is invalid.

### ISSUE THREAD

**Issue by egorXroge** [openiddict/openiddict-core#1639]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x (in preview)

### Question

Hi! Could you please help me with the issue that I'm experiencing? I'm trying to use PKCE mode in my identity server and public client. Sometimes when I try to log in or refresh opened page, client sends the following request:

https://localhost:5001/connect/authorize?client_id=processing_server_js&redirect_uri=https://nps.dev.moto-sandbox.org/silent-login-callback&response_type=code&scope=openid profile&state=70c3aa5a40524b70b31a5d9f16eea577&code_challenge=CoYhToTVvI23FUsBTzldTdKc_oXEfePvkgonD8hBUNg&code_challenge_method=S256&prompt=none&id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2MzY2QjE0NzhFNUYwMkYzRTgyQjdDNzM5QkZCMEJBNzRDNEZGNUEiLCJ4NXQiOiJCalpyRkhqbDhDOC1ncmZIT2Itd3VuVEVfMW8iLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJkNzk2NTU5Ni1lOTIwLTQzOTctODExNS1iYTcyNmQ3NTQ1NzIiLCJvaV9hdV9pZCI6IjEiLCJhenAiOiJwcm9jZXNzaW5nX3NlcnZlcl9qcyIsImF0X2hhc2giOiJWbjkwYzl0VVhkSjU5eXd4clpNbUxBIiwib2lfdGtuX2lkIjoiMTY4MjQiLCJhdWQiOiJwcm9jZXNzaW5nX3NlcnZlcl9qcyIsImV4cCI6MTY2ODA3MzY3NSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5kZXYubW90by1zYW5kYm94Lm9yZy8iLCJpYXQiOjE2NjgwNzI0NzV9.XOldk8r-2oo_vxmJoEzRTYhgbLvXthG1WZab6g-CbpuJqZqNKImYXaF3_CLqyL-2bLS26onH5J6x7V9M1qY2lLwhkq_kRdcPhaynBowfzYuj6o5EWzE0XfswzXf32bFEbG0ZkN2-C8N2zfWKG7aldFJWE6sc3SlJDIh2UEEUsNwpQpG1IvedL3OKvGCGVtjzXyWBU5Sm4zAJObk6x-ou6Q-kiSz-jT1Bv6eskaLrp-eKb-OwfK3MfmTgxdnBDdfcO9PCpdpXCldww4jJMM5tu260R2Gfeg4XGZVsvO6vc7zomkso4yxfJVt30JgHMIalEczmGJpvCvYaFuavvCifssgCy7pCplXXXNlsFR0lCcQv66dMWuDh7qH9Anh-srqmA5pOZQOfO6d5ZzRKw8ElVETVcHz-EFaph78MAgGJHeGoi0GxOl5cnQom9FQwbSypNHpsa7CLZd9hQeuU3J3TGeUwOF1uRB9Ao1xo5UyHFAVz9wntcGXXvLyMBqNj66Sl3U2yjfQuySYaWyGiTMJhmuXwzEHN5EwyGQ_8QMIJhe9u0diqfUf-AEJSG4shBFyANocmbhVT5MFtbtEFpbJWPnD1sa61nymCHIKqmttLkLwxoUDXz1yxUpzlw73j0WacS4wqy9Y2JyLv02U_657xXghu2d7JOQqxusevHpIVU&response_mode=query

And the following error is received:

error:invalid_token
error_description:The specified token is invalid.
error_uri:https://documentation.openiddict.com/errors/ID2004

I usually wait for about 5 minutes as well as refresh the page couple of times and after that the error dissapeears and I'm able to successfully open the page. I think that the reason is in the authorization code. Maybe I incorrectly configured openIdDict server options? 

Would really appreciate your help!

Thanks! Regards,
Egor

**Comment by kevinchalet** [comment]
Hey @egorXroge,

Thanks for sponsoring the project 😄 

> Maybe I incorrectly configured openIdDict server options?

Unfortunately, it's impossible to tell without seeing some code or better, some logs. Configure ASP.NET Core logging and make sure the default log level is set to `Trace` and try to reproduce the issue. Once you do, please post your logs, it will certainly help pinpoint what's wrong.

Cheers.

**Comment by egorXroge** [comment]
Hi @kevinchalet , thanks for the quick response! Will configure logging and I'll get back to you.

Regards,
Egor

**Comment by kevinchalet** [comment]
I'm doing some housecleaning, but feel free to re-open if you have additional information 😃
