### ISSUE TITLE
How do I get a refresh token?

### ISSUE THREAD

**Issue by johnkwaters** [openiddict/openiddict-core#164]
I followed the basic steps, and can get a token, and can use it
However, the call to connect/token does not return a refresh token.

**Comment by kevinchalet** [comment]
You must request the `offline_access` scope. And for that, the refresh token flow must be allowed in the OpenIddict options.

**Comment by johnkwaters** [comment]
I see. So then I get:

A database operation failed while processing the request.
DbUpdateException: An error occurred while updating the entries. See the inner exception for details.SqlException: Invalid object name &#x27;OpenIddictTokens&#x27;

**Comment by kevinchalet** [comment]
Your database is probably a bit old now and doesn't match the new schema. You must either re-create it or migrate it.

**Comment by johnkwaters** [comment]
That did the trick, thanks.
