### ISSUE TITLE
Authorization Code with PKCE requires client_secret?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1643]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

I add the following client in my authorization server as follows:

```csharp
if (await manager.FindByClientIdAsync("MyApp") == null)
{
    await manager.CreateAsync(new OpenIddictApplicationDescriptor
    {
        ClientId = "MyApp",
        ClientSecret = "cliensecrethere",
        DisplayName = "MyApp",
        ConsentType = ConsentTypes.Explicit,
        RedirectUris =
        {
            new Uri("https://localhost:44311/signin-oidc"),
            new Uri("https://oauth.pstmn.io/v1/callback")
        },
        PostLogoutRedirectUris =
        {
            new Uri("https://localhost:44311/signout-callback-oidc")
        },
        Permissions =
        {
            Permissions.Endpoints.Authorization,
            Permissions.Endpoints.Logout,
            Permissions.Endpoints.Token,
            Permissions.Endpoints.Revocation,
            Permissions.GrantTypes.AuthorizationCode,
            Permissions.GrantTypes.RefreshToken,
            Permissions.ResponseTypes.Code,
            Permissions.Scopes.Email,
            Permissions.Scopes.Profile,
            Permissions.Prefixes.Scope + Scopes.OfflineAccess,
            Permissions.Prefixes.Scope + "myserverscope"
        },
        Requirements =
        {
            Requirements.Features.ProofKeyForCodeExchange
        }
    });
}
```

My authorization server does not require PKCE globally but just for specific clients.

When I request the token I get the following error:

2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: POST to https://myauthserver/connect/token
2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: PARAMETER: code : somecodehere
2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: PARAMETER: grant_type : authorization_code
2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: PARAMETER: redirect_uri : someredirecturi
2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: PARAMETER: code_verifier : someverifierhere
2023-01-02 15:50:07.635 24285-24313/net.openid.appauthdemo D/MHR: PARAMETER: client_id : MyApp
2023-01-02 15:50:07.756 24285-24313/net.openid.appauthdemo D/MHR: RESPONSE:
    {
      "error": "invalid_client",
      "error_description": "The 'client_secret' parameter required for this client application is missing.",
      "error_uri": "https://documentation.openiddict.com/errors/ID2054"
    }

Why do I get this error if client_secret is not required for this flow?

**Comment by kevinchalet** [comment]
> Why do I get this error if client_secret is not required for this flow?

Because you specified a `ClientSecret` when creating the client:

```csharp
ClientSecret = "cliensecrethere",
```

**Comment by cryo75** [comment]
Thanks it worked.
