### ISSUE TITLE
How to replace the default Manager and Store with custom ones?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1645]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

I need to add application-specific token lifetimes so I created a custom application class:

```csharp
public class MyApplication : OpenIddictEntityFrameworkCoreApplication<string, MyAuthorization, MyToken>
{
    public int? AccessTokenLifetime { get; set; }
    public int? RefreshTokenLifetime { get; set; }
}

public class MyAuthorization : OpenIddictEntityFrameworkCoreAuthorization<string, MyApplication, MyToken> { }
public class MyScope : OpenIddictEntityFrameworkCoreScope<string> { }
public class MyToken: OpenIddictEntityFrameworkCoreToken<string, MyApplication, MyAuthorization > { }

public class MyApplicationDescriptor : OpenIddictApplicationDescriptor
{
    public int? AccessTokenLifetime { get; set; } = 1;
    public int? RefreshTokenLifetime { get; set; } = 14;
}
```

I set up the above in `Startup.cs` as described in [EF Core integration](https://documentation.openiddict.com/integrations/entity-framework-core.html).

I then created a custom store as follows:

```csharp
public interface IMyApplicationStore : IOpenIddictApplicationStore<MyApplication>
{
    ValueTask<int?> GetAccessTokenLifetimeAsync(MyApplication application, CancellationToken cancellationToken);
    ValueTask<int?> GetRefreshTokenLifetimeAsync(MyApplication application, CancellationToken cancellationToken);
    ValueTask SetAccessTokenLifetimeAsync(MyApplication application, int? lifetime, CancellationToken cancellationToken);
    ValueTask SetRefreshTokenLifetimeAsync(MyApplication application, int? lifetime, CancellationToken cancellationToken);
}

public class MyApplicationStore : OpenIddictEntityFrameworkCoreApplicationStore<
    MyApplication,
    MyAuthorization,
    MyToken,
    ApplicationDbContext,
    string>, IMyApplicationStore
{
    public MyApplicationStore(
        IMemoryCache cache, 
        ApplicationDbContext context, 
        IOptionsMonitor<OpenIddictEntityFrameworkCoreOptions> options) 
        : base(cache, context, options)
    { }

    //Implementation removed for brevity
}
```

And also a custom manager:

```csharp
public interface IMyApplicationManager : IOpenIddictApplicationManager
{
    ValueTask<int?> GetAccessTokenLifetimeAsync(MyApplication application, CancellationToken cancellationToken = default);
    ValueTask<int?> GetRefreshTokenLifetimeAsync(MyApplication application, CancellationToken cancellationToken = default);
    ValueTask PopulateAsync(MyApplication application, MyApplicationDescriptor descriptor, CancellationToken cancellationToken = default);
    ValueTask UpdateAsync(MyApplication application, MyApplicationDescriptor descriptor, CancellationToken cancellationToken = default);
}

public class MyApplicationManager : OpenIddictApplicationManager<MyApplication>, IMyApplicationManager
{
    public MyApplicationManager(
        IOpenIddictApplicationCache<MyApplication> cache,
        ILogger<MyApplicationManager> logger,
        IOptionsMonitor<OpenIddictCoreOptions> options,
        IOpenIddictApplicationStoreResolver resolver,
        IMyApplicationStoreResolver storeResolver)
        : base(cache, logger, options, resolver)
    {
        ApplicationStore = (storeResolver ?? throw new ArgumentNullException(nameof(storeResolver))).Get();
    }

    protected IMyApplicationStore ApplicationStore { get; }

    //Implementation removed for brevity
}
```

And finally a custom resolver:

```csharp
public interface IMyApplicationStoreResolver
{
    IMyApplicationStore Get();
}

public class MyApplicationStoreResolver : IMyApplicationStoreResolver
{
    private readonly IServiceProvider _provider;

    public MyApplicationStoreResolver(IServiceProvider provider)
        => _provider = provider ?? throw new ArgumentNullException(nameof(provider));

    public IMyApplicationStore Get()
        => _provider.GetService<IMyApplicationStore>() ??
            throw new InvalidOperationException(nameof(IMyApplicationStore));
}
```

I didn't create a custom cache because I don't think that it is necessary.

Additionally , in `Startup.cs` I added:

```csharp
services.AddScoped<IMyApplicationStoreResolver, MyApplicationStoreResolver>();
services.AddScoped<IMyApplicationStore, MyApplicationStore>();
services.AddScoped<IMyApplicationManager, MyApplicationManager>();

services.AddOpenIddict()

    // Register the OpenIddict core components.
    .AddCore(options =>
    {
        options.AddApplicationStore<MyApplicationStore>();
        options.ReplaceApplicationManager<MyApplicationManager>();

        //Additional code removed for brevitory
    })
```

And in my controller I am injecting `IMyApplicationManager` in the constructor. Everything seems to be working fine because I can save and load the additional application properties.

Do I need the 2 additional lines above (`AddApplicationStore` and `ReplaceApplicationManager`)? And should I need to add my custom cache class too?

In my AuthorizationController, I'm setting the principal's lifetimes accordingly in the `connect/Authorize` endpoint. Do I need to added the same in the `connect/Token` endpoint because if it is a refresh token grant type I don't have the clientId in the request?

**Comment by kevinchalet** [comment]
> And in my controller I am injecting `IMyApplicationManager` in the constructor. Everything seems to be working fine because I can save and load the additional application properties.
> 
> Do I need the 2 additional lines above (`AddApplicationStore` and `ReplaceApplicationManager`)? And should I need to add my custom cache class too?

1. No, you don't need custom cache classes (it's an ultra advanced hook, you basically never need to change that)
2. These lines can be removed.
3. You don't need a custom store resolver when subclassing the EF stores. Just call `options.AddApplicationStore<MyApplicationStore>()` and it should work. In your custom manager, just cast the `Store` property to access your custom methods.

> In my AuthorizationController, I'm setting the principal's lifetimes accordingly in the `connect/Authorize` endpoint. Do I need to added the same in the `connect/Token` endpoint because if it is a refresh token grant type I don't have the clientId in the request?

No, it's not needed: the lifetimes are stored as special private claims in the refresh tokens and will be preserved and restored so they are persisted in every subsequent refresh token. You can, however, call these methods to override the previously set lifetimes if you needed to change the values at some point.

**Comment by cryo75** [comment]
Ok thanks for the tips. They simplified the code and everything is still working as expected!
