### ISSUE TITLE
Implementing the OnCreateTicket event in v4

### ISSUE THREAD

**Issue by RwnRchrds** [openiddict/openiddict-core#1646]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello, 
I'm currently upgrading a project from OpenIddict 2.0 to 4.0, and am wondering how to migrate the OnCreateTicket event to 4.0

In my project (currently using 2.0) I'm able to define the events in the startup:

```
services.AddOpenIddict(builder =>
            {              
                builder.AddValidation(options =>
                {
                    options.Configure(c =>
                    {
                        var userManager = serviceProvider.GetService<UserManager<ApplicationUser>>();
                        c.Events = new OAuthValidationEvents();
                        c.Events.OnCreateTicket = CustomAuthenticator.OnCreateTicket(userManager);
                    });
                });
            });
```

with the following handler for the OnCreateTicket event:

```
public static Func<CreateTicketContext, Task> OnCreateTicket(UserManager<ApplicationUser> userManager)
    {
        return async delegate(CreateTicketContext context)
        {           
            if (context.Identity.HasClaim("cfd_lvl", "private"))
                return;

            if (!context.Identity.HasClaim("x-application-require-user", "true"))
                return;

            var sub = context.Principal.GetClaim(OpenIddictConstants.Claims.Subject) ??
                      context.Principal.GetClaim(
                          "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier");

            if (sub == null)
            {
                context.Response.Headers.Add("ApplicationUserID", "");
                return;
            }

            using (var connection = new SqlConnection(Startup.ConnectionString))
            {
                var userId = connection.ExecuteScalar<Guid?>(
                    @"
SELECT U.UserId FROM Client c
JOIN AspNetUsers U ON U.ClientId = c.Id
WHERE U.Id = @id AND c.AccessConnectionId is not null",
                    new {id = sub});

                if (userId == null)
                {
                    context.Response.Headers.Add("ApplicationUserID", "");
                    return;
                }

                context.Response.Headers.Add("ApplicationUserID",
                    new StringValues(userId.Value.ToString("N")));
            }
        };
    }
```

I understand that the library that provided the CreateTicketContext (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions) has been merged into OpenIddict, but I'm not able to find the equivalent in OpenIddict - I've tried implementing the Events model IOpenIddictValidationHandler<ValidateTokenContext>, but the ValidationTokenContext doesn't allow me to access the Identity property or modify the response headers.

**Comment by kevinchalet** [comment]
Hi,

> I understand that the library that provided the CreateTicketContext (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions) has been merged into OpenIddict, but I'm not able to find the equivalent in OpenIddict - I've tried implementing the Events model IOpenIddictValidationHandler, but the ValidationTokenContext doesn't allow me to access the Identity property or modify the response headers.

The equivalent in OpenIddict 3.0 and higher is the `ProcessAuthentication(Context)` event.

That said, I'd strongly suggest opting for a different approach: `OnCreateTicket` has never been designed to allow mutating the HTTP response and doing so was not a good idea at all (don't forget that `AuthenticateAsync()` operations are cached by ASP.NET Core so doing things that touch the response is... meh 😄).

You could certainly do the same thing with OpenIddict via `ProcessAuthentication(Context)` (using `context.Transaction.GetHttpRequest()` to access the HTTP context), but a custom ASP.NET Core middleware would be a much better option. Something like this:

```csharp
app.Use(static (context, next) =>
{
    context.Response.OnStarting(static async state =>
    {
        var context = (HttpContext) state;
        var result = await context.AuthenticateAsync(OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme);
        if (result?.Principal is { Identity.IsAuthenticated: true } principal)
        {
            context.Response.Headers["Custom-Header"] = principal.FindFirst(Claims.Subject)!.Value;
        }
    }, context);

    return next(context);
});
```
