### ISSUE TITLE
How to change validation type in runtime?

### ISSUE THREAD

**Issue by MDzyga** [openiddict/openiddict-core#1647]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi @kevinchalet :)
I updated openIdDict to version 4 and I'm trying to use ChangeToken as you said. Unfortunately it doesn't work, change token is executed but OpenIdDict doesn't switch between Introspection and Direct. I tried with ChangeToken registered outside AddValidation, the same efect.

```
services
	.AddOpenIddict()
	.AddCore(options =>
	{
		options.UseEntityFrameworkCore()
			.UseDbContext<ApplicationDbContext>()
			.ReplaceDefaultEntities<Client, Authorization, Scope, Token, int>();
	})
	.AddServer(options =>
	{
		options
			.SetTokenEndpointUris("connect/token")
			.SetRevocationEndpointUris("connect/revocation")
			.SetIntrospectionEndpointUris("connect/introspect");

		options.AddEventHandler<OpenIddictServerEvents.ProcessSignInContext>(builder =>
		{
			builder.UseInlineHandler(context =>
			{
				if (context.Transaction.Request != null)
				{
					context.Response["scope"] = string.Join(" ", context.Transaction.Request.GetScopes().OrderBy(z => z));
				}

				return default;
			});
		});

		options.AddEventHandler<OpenIddictServerEvents.ProcessChallengeContext>(builder =>
		{
			builder.UseInlineHandler(context =>
			{
				var authPropertiesKey = typeof(AuthenticationProperties).ToString();
				if (context.Transaction.Properties.ContainsKey(authPropertiesKey))
				{
					var props = context.Transaction.Properties[authPropertiesKey] as AuthenticationProperties;
					context.Response["message"] = props.Items["message"];
				}

				return default;
			});
		});

		options.AllowClientCredentialsFlow();
		options.AllowPasswordFlow();
		options.AllowRefreshTokenFlow();

		options.UseReferenceRefreshTokens();

		options.RegisterScopes(
			OpenIddictConstants.Permissions.Scopes.Profile.Replace(OpenIddictConstants.Permissions.Prefixes.Scope, string.Empty),
			OpenIddictConstants.Permissions.Scopes.Roles.Replace(OpenIddictConstants.Permissions.Prefixes.Scope, string.Empty),
			CustomScopes.APPLICATION,
			CustomScopes.IDENTITY_SETUP,
			CustomScopes.SUPPORT_PACKAGE);

		options.SetAccessTokenLifetime(TimeSpan.FromHours(1));
		options.SetRefreshTokenLifetime(TimeSpan.FromDays(7));

		options.AddEncryptionCertificate(signingCertificate)
			.AddSigningCertificate(signingCertificate);

		options.DisableAccessTokenEncryption();

		options.UseAspNetCore()
			.EnableTokenEndpointPassthrough();
	})
	.AddValidation(options =>
	{
		SetValidation(options);

		ChangeToken.OnChange(configuration.GetReloadToken, () => SetValidation(options));
	});
```
SetValidation method

```
private static void SetValidation(OpenIddictValidationBuilder builder)
{
	MasterUrlManager masterSettings = MasterUrlManager.Get();
	if (!string.IsNullOrWhiteSpace(masterSettings.Host) && masterSettings.Status == MasterStatus.Healthy)
	{
		string clientId = LocalClientManager.GetId();

		builder.SetIssuer($"https://{masterSettings.Host}:{masterSettings.HttpsPort}/");
		builder.AddAudiences(clientId);

		builder.UseIntrospection()
			.SetClientId(clientId)
			.SetClientSecret(LocalClientManager.GetSecret());

		builder.UseSystemNetHttp();
	}
	else
	{
		builder.UseLocalServer();
	}

	builder.UseAspNetCore();
}
```

**Comment by kevinchalet** [comment]
Hey,

Your approach cannot work: the builders offered by OpenIddict are wrappers around `IServiceCollection` that simply register options initializers in the DI: once the container is built, you can't re-register the options initializers and expect that to work: it just won't have any effect.

Here's a sample of the correct approach:

```csharp
public class OpenIddictValidationOptionsInitializer : IConfigureOptions<OpenIddictValidationOptions>
{
    public void Configure(OpenIddictValidationOptions options)
    {
        if (options is null)
        {
            throw new ArgumentNullException(nameof(options));
        }

        // This initializer is invoked every time the options are (re)-created, which
        // gives you a chance to tweak them on-the-fly based on your configuration.
        options.ValidationType = OpenIddictValidationType.Direct;
    }
}
```

```csharp
public class OpenIddictValidationOptionsReloadManager : IOptionsChangeTokenSource<OpenIddictValidationOptions>, IDisposable
{
    private CancellationTokenSource _source = new();

    public string? Name => Options.DefaultName;

    public IChangeToken GetChangeToken() => new CancellationChangeToken(_source.Token);

    public void Reload() => Interlocked.Exchange(ref _source, new()).Cancel();

    public void Dispose() => _source.Dispose();
}
```

```csharp
builder.Services.AddSingleton<OpenIddictValidationOptionsReloadManager>();
builder.Services.AddSingleton<IConfigureOptions<OpenIddictValidationOptions>, OpenIddictValidationOptionsInitializer>();
builder.Services.AddSingleton<IOptionsChangeTokenSource<OpenIddictValidationOptions>>(provider =>
    provider.GetRequiredService<OpenIddictValidationOptionsReloadManager>());
```

When you need to reload the options, resolve the `OpenIddictValidationOptionsReloadManager` service from DI and call `Reload()` to re-create the options object.

**Comment by kevinchalet** [comment]
Note: it's absolutely not specific to OpenIddict, so you can use the same approach with any other library that uses `Microsoft.Extensions.Options`.

**Comment by MDzyga** [comment]
Hi,
Thank you, I will check it tomorrow :)
Could you tell me if I have to register above servies before OpenIdDict or it doesn't matter?

**Comment by kevinchalet** [comment]
The only service for which you'll see a visible effect is `builder.Services.AddSingleton<IConfigureOptions<OpenIddictValidationOptions>, OpenIddictValidationOptionsInitializer>()`: if you register it before configuring OpenIddict with the regular `services.AddOpenIddict()` stuff, your initializer will be invoked before the initializers added by OpenIddict. If you register it after, it will be invoked after.

Instead of using the builder methods, you'll likely want to configure everything in your custom initializer, anyway.

**Comment by MDzyga** [comment]
Hi,
Could you tell me what should I set to switch validation type?
This is my version:
```
internal class ValidationOptionsInitializer : IConfigureOptions<OpenIddictValidationOptions>
{
	public void Configure(OpenIddictValidationOptions options)
	{
		if (options is null)
		{
			throw new ArgumentNullException(nameof(options));
		}

		MasterUrlManager masterSettings = MasterUrlManager.Get();
		if (!string.IsNullOrWhiteSpace(masterSettings.Host) && masterSettings.Status == MasterStatus.Healthy)
		{
			options.ValidationType = OpenIddictValidationType.Introspection;
			options.Issuer = new Uri($"https://{masterSettings.Host}:{masterSettings.HttpsPort}/");
			options.ClientId = LocalClientManager.GetId();
			options.ClientSecret = LocalClientManager.GetSecret();
			options.Audiences.Clear();
			options.Audiences.Add(options.ClientId);
		}
		else
		{
			options.ValidationType = OpenIddictValidationType.Direct;
		}
	}
}
```
Startup:
```
.AddValidation(options =>
{
  options.UseSystemNetHttp();
  options.UseLocalServer(); <= here is a problem

  options.UseAspNetCore();
});
```
I noticed that to use Direct validation I have to execute `UseLocalServer` but if I do it change validation type on Introspection doesn't work. If I remove `UseLocalServer` then Introspection works but change to Direct throws error with information that I should execute `UseLocalServer`.

If I want to switch on Direct without executing earlier `UseLocalServer` I get this error:
`One or more errors occurred. (An OAuth 2.0/OpenID Connect server configuration or an issuer URI must be registered.\r\nTo use a local OpenIddict server, reference the 'OpenIddict.Validation.ServerIntegration' package and call 'services.AddOpenIddict().AddValidation().UseLocalServer()' to import the server settings.\r\nTo use a remote server, reference the 'OpenIddict.Validation.SystemNetHttp' package and call 'services.AddOpenIddict().AddValidation().UseSystemNetHttp()' and 'services.AddOpenIddict().AddValidation().SetIssuer()' to use server discovery.\r\nAlternatively, you can register a static server configuration by calling 'services.AddOpenIddict().AddValidation().SetConfiguration()'.)\r\nAn OAuth 2.0/OpenID Connect server configuration or an issuer URI must be registered.\r\nTo use a local OpenIddict server, reference the 'OpenIddict.Validation.ServerIntegration' package and call 'services.AddOpenIddict().AddValidation().UseLocalServer()' to import the server settings.\r\nTo use a remote server, reference the 'OpenIddict.Validation.SystemNetHttp' package and call 'services.AddOpenIddict().AddValidation().UseSystemNetHttp()' and 'services.AddOpenIddict().AddValidation().SetIssuer()' to use server discovery.\r\nAlternatively, you can register a static server configuration by calling 'services.AddOpenIddict().AddValidation().SetConfiguration()'.`

If I want to switch on Introspection I get this error:
`One or more errors occurred. (The local server integration can only be used with direct validation.)\r\nThe local server integration can only be used with direct validation.`

**Comment by kevinchalet** [comment]
Ah yeah, I forgot to mention that if you were using `options.UseLocalServer()`, you'll need to remove it. Just add the same logic to your custom initializer to import the server configuration when the remote server is not available:

https://github.com/openiddict/openiddict-core/blob/f954e5c71905379d304dab33f269955f7264d6e1/src/OpenIddict.Validation.ServerIntegration/OpenIddictValidationServerIntegrationConfiguration.cs#L20-L27

https://github.com/openiddict/openiddict-core/blob/f954e5c71905379d304dab33f269955f7264d6e1/src/OpenIddict.Validation.ServerIntegration/OpenIddictValidationServerIntegrationConfiguration.cs#L37-L54

**Comment by MDzyga** [comment]
Hi @kevinchalet,
Thank you very much for your help :) It finally works without any restarts :)

**Comment by kevinchalet** [comment]
Awesome! 👍🏻

Thanks again for sponsoring the project, much appreciated ❤️
