### ISSUE TITLE
Error ID2004 on logout in v4 when id_token has been pruned

### ISSUE THREAD

**Issue by NoahStahl** [openiddict/openiddict-core#1649]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

I just upgraded a project from v3 to v4. Nice work, very smooth! Just noticed one rough edge I was curious about and wanted to flag: after the upgrade, a user who logs out by hitting the logout endpoint sees a plaintext page with this error:

```
error:invalid_token
error_description:The specified token is invalid.
error_uri:https://documentation.openiddict.com/errors/ID2004
```

After a fresh login, logout works fine again for the user. Would be nice if this error could be avoided for the first logout? Also curious if there's a way to have such a scenario fall through to the ASP.NET Core exception handling middleware to be the standard experience for the app, rather than what is rendered by OpenIddict here?

### To reproduce

I've only seen this during upgrade, in both a test and prod environment (same in both cases). Does not repro after a fresh login, so not straightforward to reproduce.

If it helps, here is the logout endpoint:

```
[Route("logout")]
[HttpGet, HttpPost]
public async Task<IActionResult> Logout()
{
    await HttpContext.SignOutAsync();
    var authProps = new AuthenticationProperties { RedirectUri = "/" };

    return SignOut(authProps, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
}
```

**Comment by kevinchalet** [comment]
Hey,

> After a fresh login, logout works fine again for the user. Would be nice if this error could be avoided for the first logout?

4.0's logout endpoint got an overhaul and now automatically validates the `id_token_hint` parameter (in previous versions, there was no automatic validation and your logout action had to call `AuthenticateAsync()` to validate the token), so it's possible this is related. That said, without seeing any logs, it's hard to tell what's going on.

If I get similar reports, I'll try to reproduce it locally.

> Also curious if there's a way to have such a scenario fall through to the ASP.NET Core exception handling middleware to be the standard experience for the app, rather than what is rendered by OpenIddict here?

The ASP.NET Core host natively supports the ASP.NET Core status code pages middleware, but it's opt-in. Take a look at the builder returned by `options.UseAspNetCore()` and the Velusia sample in the dedicated repo.

**Comment by NoahStahl** [comment]
Any particular logs that might be helpful? Would be happy to gather whatever I have.

**Comment by NoahStahl** [comment]
Digging in a little further, I'm seeing the below in logs. It looks like the token is being deleted from the database by pruning, and then during logout it is not found, resulting in the error handling.

If a correct interpretation, does this suggest a problem with the pruning deleting tokens prematurely (our system is configured for a 24 threshold)? Or, if the pruning is correct, can the behavior of logout be changed to ignore the missing DB token and just perform whatever logout action it can without any error, returning user to the login page?

I never saw this prior to v4 upgrade, so that seems to suggest some behavior change in one of these aspects.

```
The request URI matched a server endpoint: "Logout".

The logout request was successfully extracted: {
  "post_logout_redirect_uri": "https://<domain>/signout-callback-oidc",
  "id_token_hint": "[redacted]",
  "state": "CfDJ8O8-fMFilYNJnvaL4M6Bgebs42X4Nqb3eOJoPc1lw010SRbEUFOYD8da_u0nyufUECmbQMxHmjbhKwAB1Dj3IBR2k0GRPb29n9vOMlLJcNTmNigdCxEcQUjsP1C4K20cRGkBVYf5wOaZLFRdBrDB-qwkhc",
  "x-client-SKU": "ID_NETSTANDARD2_0",
  "x-client-ver": "6.15.1.0"
}.

(***Our log***) database read failed for OpenIddictToken with ID <token ID>

The response was successfully returned as a plain-text document: {
  "error": "invalid_token",
  "error_description": "The specified token is invalid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2004"
}.
```

**Comment by kevinchalet** [comment]
> If a correct interpretation, does this suggest a problem with the pruning deleting tokens prematurely (our system is configured for a 24 threshold)?

Assuming "24" means 24 hours, this is indeed way too short.

> Or, if the pruning is correct, can the behavior of logout be changed to ignore the missing DB token

OpenIddict already ignores the expiration date of identity tokens used as hints, so it may make sense to also ignore the token entry. Before changing that, I'll need to determine what's acceptable, tho'. E.g just when the token entry is missing or even when it's marked as revoked?

> I never saw this prior to v4 upgrade, so that seems to suggest some behavior change in one of these aspects.

As I said:

> 4.0's logout endpoint got an overhaul and now automatically validates the `id_token_hint` parameter (in previous versions, there was no automatic validation and your logout action had to call `AuthenticateAsync()` to validate the token), so it's possible this is related. That said, without seeing any logs, it's hard to tell what's going on.

This overhaul was made in relationship with the adoption of the final version of https://openid.net/specs/openid-connect-rpinitiated-1_0.html (which is very recent), that introduced support for the `client_id` parameter and requires executing mandatory security checks (e.g to ensure the `client_id` matches the audience of the identity token).

**Comment by kevinchalet** [comment]
Note: thanks to OpenIddict's event model, you can implement that yourself without needing a change in OpenIddict. The validation is performed by these handlers:

https://github.com/openiddict/openiddict-core/blob/bf366075c288a917b80806ce5d8e5822d963ad4c/src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs#L568-L649

https://github.com/openiddict/openiddict-core/blob/bf366075c288a917b80806ce5d8e5822d963ad4c/src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs#L787-L951

You can remove them from the pipeline and replace them by a custom version that no-ops for identity tokens received by the logout endpoint. Alternatively, you can also create a custom handler that is invoked before `RestoreTokenEntryProperties` and that calls `SetTokenId(null)` to disable all the features that use the token DB entry. Of course, only do that for the identity tokens received by the logout endpoint, or you'll seriously affect the security of your app.

**Comment by NoahStahl** [comment]
Confirming I've now understood this is always reproducible in v4, not specifically related to the upgrade from v3:

1. Log in as a user
2. Delete the `id_token` token state from the database, as pruning would do
3. Attempt the logout flow. Error `ID2004` encountered. 

> Assuming "24" means 24 hours, this is indeed way too short.

Yes, 24 hours. Could you elaborate on "too short"? It seems that pruning and requiring an `id_token` be present on logout are now at odds. Suppose tokens are pruned at 30 days instead -- doesn't the user who logs out on day 31 get the same error? If pruning occurs after time T, error occurs at T + 1. It seems the current treatment implies never pruning?

I defer to your intimate knowledge of the relevant specs -- is there some risk in a logout where the token state is unavailable for whatever reason? It's unclear what this error is meant to accomplish -- not seemingly actionable by the user, so perhaps the audience is really the developer? If so, perhaps this can be refactored into a logged warning about the scenario and why the developer should be worried about it. Then the user wouldn't encounter an error for which they have no control or fault.

Appreciate the ability to override events, but that's pretty heavy and something I like to avoid. Would much rather work with the defaults than override them. 

From the usage point of view, a suggestion if logout without `id_token` state is indeed a problem:

1. Refactor user-visible error to internal logged warning which points to the rationale behind strict logout handling, noting this can occur if token pruning is utilized, and that the warning can be disabled as below
4. Offer a `DisableStrictLogout` option that turns this warning off for situations where it is deemed safe.

**Comment by kevinchalet** [comment]
> Yes, 24 hours. Could you elaborate on "too short"? It seems that pruning and requiring an `id_token` be present on logout are now at odds. Suppose tokens are pruned at 30 days instead -- doesn't the user who logs out on day 31 get the same error? If pruning occurs after time T, error occurs at T + 1. It seems the current treatment implies never pruning?

A more reasonable value - like 14 days (the default) or 30 days - mechanically reduces the chances of seeing a client send an `id_token` that was issued a few weeks ago, which is why you're the first one seeing errors caused by the new behavior.

> I defer to your intimate knowledge of the relevant specs -- is there some risk in a logout where the token state is unavailable for whatever reason?

The `id_token_hint` is often used as a way to bypass the logout confirmation screen. While in most cases an unsolicited logout is not a huge deal, there are scenarios where it can be a real issue (e.g an online game, where being able to trigger an unsolicited logout via a CSRF could be an unfair "tactical" advantage). Checking the status of a token entry is necessary when you need to be able to revoke leaked tokens, for instance.

> It's unclear what this error is meant to accomplish -- not seemingly actionable by the user, so perhaps the audience is really the developer? If so, perhaps this can be refactored into a logged warning about the scenario and why the developer should be worried about it. Then the user wouldn't encounter an error for which they have no control or fault.

Logged warnings are not a perfect solution are they are not visible to third-party developers: only the developer of the authorization server can access them, so it makes finding the root cause of such an error much more complicated 😄 

With that said, I agree the new behavior is not ideal from a UX perspective, so I will change it in 4.1 to bring back roughly the same behavior as in 3.x:
  - An invalid identity token hint (e.g malformed, tampered with, revoked) will not result in an error returned by OpenIddict itself: the invalid hint will be ignored and the request will be considered valid.

  - Calling `AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` from the logout action when the identity token hint is invalid will return a null principal to indicate the hint cannot be used to bypass the logout confirmation. This is consistent with the experience offered in the device authorization flow where an invalid user verification code is specified as a parameter. As in 3.x, the status of the entry will always be taken into account: if it's revoked, a null principal will be returned. I don't plan to add a property to disable this check as I initially mentioned.

  - Security checks that ensure the `id_token_hint` audience is the same as the `client_id` parameter (if specified) will keep returning an error if there's a mismatch.

**Comment by kevinchalet** [comment]
@NoahStahl note: the 4.1.0 nightly builds are available on MyGet.org. Don't hesitate to give them a try to confirm it fixed your issue.

**Comment by NoahStahl** [comment]
Thanks for the detailed reply and changes, Kevin. Very helpful. 👍🏽
