### ISSUE TITLE
IDP claim is missing from access token & idp token

### ISSUE THREAD

**Issue by salimz1** [openiddict/openiddict-core#1650]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x (no longer supported)

### Question

HI Kevin,
Facing an issue with implicit flow where client is SPA with Vue.js using oidc client library. Openiddict is oauth server. Whenever it logins and send both the token with callback url, it throwing an error  ( localstorage  user is null in  ). very similar issue mentioned for (https://github.com/IdentityModel/oidc-client-js/issues/327)  
http://test.com/v2/test-signin/#access_token=xxx&token_type=Bearer&expires_in=3599&id_token=XXYY
When i checked the access token using  jwt.io, the idp claim is not present.  The same thing already included into the token in authorization flow.  The same token used to call  /userinfo endpoint, there also it is showing idp claim as blank.
Not sure at this stage, may be missing of idp claim causing Vue.js client to not able to read the "user" object from token. 

Below is access token results
{
  "sub": "900008",
  "oi_prst": "xxx",
  "client_id": "xxxx",
  "oi_tkn_id": "71a4c473-285f-4ec0-bf6a-5c21df11ace7",
  "scope": "openid customers emails",
  "exp": 1674142467,
  "iss": "https://localhost:5001/",
  "iat": 1674138867
}

part of the snipper which is at openiddict level  /authorize endpoint in authorization controller
 var identity = new ClaimsIdentity(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(identity);
                    var claims = new List<Claim>
                    {
                        // 'subject' claim which is required
                        new Claim(OAuthClaims.Subject, user.Id.ToString()),
                        new Claim(OAuthClaims.Name, string.Join(" ", new string[] { user.FirstName, user.LastName }.Where(name => !String.IsNullOrWhiteSpace(name)))),
                        new Claim(OAuthClaims.SecurityLevel,user.SecurityLevel.ToString()),
                        new Claim(OAuthClaims.GivenName, user.FirstName),
                        new Claim("idp", "local")
                    };

                    long lastLoginSecondsFromEpoch = 0;
                    if (user.LastLogin != null && user.LastLogin.GetType() == typeof(DateTime))
                    {
                        lastLoginSecondsFromEpoch = Convert.ToInt64((user.LastLogin.Value - epochTime).TotalSeconds);
                    }
                   
                    claims.Add(new Claim(OAuthClaims.LastLogin, lastLoginSecondsFromEpoch.ToString(), ClaimValueTypes.Integer64));

                    IList<string> amrlist = new List<string>();
                    amrlist.Add("password");
                    string amrJson = JsonConvert.SerializeObject(amrlist);

                    claims.Add(new Claim(OAuthClaims.AuthenticationMethodReference, amrJson, JsonClaimValueTypes.JsonArray));
                    identity.AddClaims(claims);
                   
                    foreach (var claim in claimsPrincipal.Claims)
                    {
                        claim.SetDestinations(GetDestinations(claim, claimsPrincipal));
                    }
await currController.HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, props);

Any help in this regard would be helpful..

**Comment by kevinchalet** [comment]
Hi @salimz1,

Sponsoring the project to get your question answered and canceling your subscription soon after that as you did last time is not exactly in the spirit of the sponsorship model. Also, a $2/month sponsorship allows you to open 1 ticket/year and you've already opened 3.

Closing.

**Comment by salimz1** [comment]
Hi Kevin, may be every time i took a support , have taken 2$ /month sponsorship. Please let me know which one to be taken to get the support further..  

Thanks.
