### ISSUE TITLE
Add a WinUI client sample

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1654]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

We already have a console, a WPF and a WinForms sample, but nothing for WinUI 3 yet, as there's currently no .NET generic host integration. https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting/pull/37 may change that in the very near future, so we'll be able to create such a sample.

### Additional context

~Note: due to https://github.com/openiddict/openiddict-core/issues/1653, sandboxed applications are not currently supported, so it will need to be a full trust app - the default value in the WinUI 3/WinAppSDK templates - for the time being.~

**Comment by kevinchalet** [comment]
Moving out of 4.2 as https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting/pull/37 hasn't been merged yet.

**Comment by xperiandri** [comment]
Looks like merged

**Comment by kevinchalet** [comment]
The PR was merged but the WinUI integration package wasn't pushed to NuGet due to some issues: https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting/issues/29#issuecomment-1493429977.

**Comment by kevinchalet** [comment]
Closing, as we still miss the WinUI/Dapplo integration (and neither WinUI nor the Dapplo hosting extension get enough love, sadly).
