### ISSUE TITLE
Is it possible to disable issuer fixation attacks attack prevention?

### ISSUE THREAD

**Issue by oh-yeah** [openiddict/openiddict-core#1665]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

As of OpenIddict 4.x, an iss query string value is returned on some OAuth responses.  Is there any way to disable this security feature or the validation of this feature on the server?  I'd really like to upgrade to the latest version of this product, but I'm afraid this functionality will break authentication with some of our third part clients.

https://github.com/openiddict/openiddict-core/blob/8c14d4e3e9cfda95e8b8fab8347545f86ce69638/src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs

**Comment by kevinchalet** [comment]
> [x] I confirm I'm a sponsor or a contributor

GitHub doesn't recognize you as a sponsor. When did you sponsor the project?

**Comment by oh-yeah** [comment]
I'm not a sponsor, I just checked the box so I can post a simple question.  Being forced to sponsor a project to ask questions or submit a bug on an open-source project is strange.

**Comment by kevinchalet** [comment]
> Being forced to sponsor a project to ask questions or submit a bug on an open-source project is strange.

The project is open source but my time is not free. I don't think you work for free, do you?

**Comment by leastprivilege** [comment]
Is there a setting in GitHub to only allow sponsors to open issues? If not - there should be one.

Not cool @oh-yeah
