### ISSUE TITLE
Redirect to client application after sign out

### ISSUE THREAD

**Issue by alexxonline** [openiddict/openiddict-core#167]
Hi! I'm using openiddict-core 1.0 and I added an implicit flow using the AutorizationController in the sample. When I logout the user is not redirected to a client application it stays in blank. Is that a not implemented feature,a bug or I'm doing something wrong?

**Comment by kevinchalet** [comment]
It's fully supported. Do you send the post_logout_redirect_uri parameter?
http://openid.net/specs/openid-connect-session-1_0.html#RedirectionAfterLogout

**Comment by alexxonline** [comment]
I  can confirm the feature is working correctly the parameter was not being sent by the client application. Thanks!

**Comment by kevinchalet** [comment]
Nice :clap:
