### ISSUE TITLE
Introduce support for application types and allow native applications to use relaxed redirect_uri comparisons

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#1690]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

With OpenIddict 4.1 now offering a system integration package with an embedded web server feature, opting for a relaxed URI comparison policy that ignores the port for loopback URIs would be helpful to avoid hardcoding multiple URIs with different ports.

Note: as part of this task, we'll also want to rename `OpenIddictApplicationDescriptor/Model.Type` to `ClientType` to avoid the ambiguity with the `ApplicationType` property that will be introduced. Since it will be a schema change, it will need to be documented.

### Additional context

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

> application_type
OPTIONAL. Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type MUST only register URLs using the https scheme as redirect_uris; they MUST NOT use localhost as the hostname. Native Clients MUST only register redirect_uris using custom URI schemes or URLs using the http: scheme with localhost as the hostname. Authorization Servers MAY place additional constraints on Native Clients. Authorization Servers MAY reject Redirection URI values using the http scheme, other than the localhost case for Native Clients. The Authorization Server MUST verify that all the registered redirect_uris conform to these constraints. This prevents sharing a Client ID across different types of Clients.

https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata

**Comment by kevinchalet** [comment]
@maliming @SebastianStehle I'll start working on that soon, but first, I'd like to ensure it won't be too disruptive for ABP and Squidex/Notifo 😃

As part of this task, I'll need to introduce a new property and rename an existing one: is it something your frameworks will handle transparently for your users? What does your EF Core/MongoDB migration story look like?

Thanks.

**Comment by maliming** [comment]
hi @kevinchalet 

We will update our entities and update the migrations, This is no problem.

**Comment by kevinchalet** [comment]
@maliming awesome, thanks! Out of curiosity, is it transparent for ABP users or do they have to explicit run the migrations?

**Comment by maliming** [comment]
Abp's OpenIddict module defines and configures the EF Core DbContext.

Our customers will use modules in their projects and maintain migrations themselves. 
We can add or rename fields in new versions. They update and create new migrations, of course, we will explain this change in the upgrade document.

**Comment by kevinchalet** [comment]
@maliming great to hear, thanks!

The changes introduced by https://github.com/openiddict/openiddict-core/pull/1877 will be detailed in the future migration docs, but in a nutshell:
  - `OpenIddictApplicationDescriptor.Type` was replaced by `OpenIddictApplicationDescriptor.ClientType` (the `Type` property still exists but is marked as obsolete and will be removed in a future version).
  - `OpenIddictApplicationDescriptor.ApplicationType` was introduced. If it's not explicitly set, the default `web` value is used.
  - `OpenIddict*Application.Type` was renamed to `OpenIddict*Application.ClientType` in the EF 6/EF Core/MongoDB entities.
  - `OpenIddict*Application.ApplicationType` was added to the EF 6/EF Core/MongoDB entities.
  - New `IOpenIddictApplicationStore.GetApplicationTypeAsync()`/`IOpenIddictApplicationStore.SetApplicationTypeAsync()` have been introduced and will need to be implemented by custom stores when targeting OpenIddict 5.0.

**Comment by maliming** [comment]
Thanks @kevinchalet 👍
