### ISSUE TITLE
MethodMissingException Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt

### ISSUE THREAD

**Issue by jignesh-dalal** [openiddict/openiddict-core#1692]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

@kevinchalet, I admit that I'm not yet a contributor or a sponsor but kindly request you to spare a few minutes for the issue. If possible please help.

Tried the very basic degraded mode by following https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/ and using MS OpenIdConnect but facing the following issue:

![image](https://user-images.githubusercontent.com/6212638/221223237-b5b402b8-3a92-4424-9b10-038170164a57.png)

### To reproduce

https://github.com/jignesh-dalal/openiddict-issue

**Comment by kevinchalet** [comment]
> @kevinchalet, I admit that I'm not yet a contributor or a sponsor but kindly request you to spare a few minutes for the issue. If possible please help.

Unfortunately, making exceptions for some people wouldn't be fair for those who contributed or sponsored the project.

That said, if you Google that exception message, I'm sure you'll find what's its root cause.
