### ISSUE TITLE
Implement authorization storage

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#17]
In the current bits, the authorization consent form is always displayed. We should add a new `Authorization` model and offer an option to avoid re-displaying the consent form.

**Comment by singlewind** [comment]
I have completed few features in my fork. However, I have different release roadmap. Need to catch up your guys progress. I still haven't updated since ASP.NET rc1.

**Comment by kevinchalet** [comment]
> I have completed few features in my fork.

Nice!

The current bits use the RC2 packages present on the aspnetvnext feed (stuck for more than a month now).

> Need to catch up your guys progress.

I'm in the process of migrating OpenIddict - and all the aspnet-contrib projects - to .NET CLI and the latest ASP.NET Core 1.0 packages (from the aspnetcidev), which means that existing applications will break (hard). It will likely be done today or tomorrow.

You can take a look at the [related PR](https://github.com/openiddict/openiddict-core/pull/60) for more information :clap:

**Comment by kevinchalet** [comment]
Alright, it's time to implement this (super) important feature (without that, a client application can currently ask more scopes during a prompt=none request, which is terribad).

@singlewind did you make some progress?

**Comment by singlewind** [comment]
The most important thing for you is define an interface :), So we can implement based on different storage. The tricky is that we may extend the default userstore and rolestore compared to the default implementation of Microsoft.AspNet.Identity.EntityFramework. We need store scope information regards a claim. I was thinking the Subject property of Claim (https://msdn.microsoft.com/en-us/library/system.security.claims.claim(v=vs.110).aspx) class can be a candidate of mapping field of scope. However, the subject is not simply a string, it is ClaimsIdentity. We also can use Claim.Properties dictionary to store scope data when the deserialize from storage. What do you think? @PinpointTownes

**Comment by kevinchalet** [comment]
Reassigned.

**Comment by kevinchalet** [comment]
Done as part of https://github.com/openiddict/openiddict-core/issues/339.
