### ISSUE TITLE
User is authorized, but the Identity has an empty Name property

### ISSUE THREAD

**Issue by KerryRitter** [openiddict/openiddict-core#171]
Not sure if I'm missing any steps - everything works well (I can get a token, then use the token in the request to authorize) but the HttpContext.User.Identity.Name property is null and I can't figure out why. 

https://github.com/KerryRitter/CigarBar/tree/51ef659f655f6342e8a5859cf4a865ced56d26fb/CigarBar/CigarBar.Api is the current state of my project.

http://screencast.com/t/j3BZvg6t is what I see in the Identity object.

**Comment by ghost** [comment]
You need to request the Name with the scope, e.g. scope = openid profile name.

Hope that helps

**Comment by KerryRitter** [comment]
This is most likely my problem. Will check back in soon.

**Comment by kevinchalet** [comment]
@nklap is right. You need to request the "profile" scope to get back the username.

**Comment by KerryRitter** [comment]
That was correct. I said "scope" to "email profile" in my request and all is well. Thanks!
