### ISSUE TITLE
Cannot add custom user store

### ISSUE THREAD

**Issue by ppkdo** [openiddict/openiddict-core#172]
OpenIddictBuilder AddUserStore method has wrong validation.

 typeof(**IOpenIddictTokenStore**<>) should be  typeof(**IOpenIddictUserStore**<>)

Otherwise we cannot add a custom user store of type IOpenIddictUserStore

**Comment by kevinchalet** [comment]
Fixed, thanks! https://github.com/openiddict/openiddict-core/commit/aac69a011c64f7f39290705b3aaad26b450e5541

**Comment by armartinez** [comment]
Has this been released already, I seem to be having this problem

**Comment by kevinchalet** [comment]
This fix was included in 1.0.0-alpha2-0393 and is part of all the next versions.
