### ISSUE TITLE
"The "scope" parameter is not valid in this context" when sending authorization code grant

### ISSUE THREAD

**Issue by Thodor12** [openiddict/openiddict-core#1729]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

I upgraded to OpenIddict 4.0 and now my mobile application is unable to login because during the authorization code grant it's passing a "scope", previously this worked just fine but since (I assume) 4.0 this is no longer allowed due to:
https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs#L733

Is there a reason for this change, I don't think this is against the OAuth2 spec?
Didn't this exist so that during the "authorization screen" you could modify what scopes you wanted to allow or not?

### To reproduce

N/A

### Exceptions (if any)

```shell
The response was successfully returned as a JSON document:
{
  "error": "invalid_request",
  "error_description": "The 'scope' parameter is not valid in this context.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2074"
}.
```

**Comment by kevinchalet** [comment]
Hi,

As indicated on the sponsors page (see https://github.com/sponsors/kevinchalet), the benefits of your sponsorship are lost if you cancel it within the first 12 months - as you did - and a one-time $500 sponsorship is required to re-enable it.

Hope you'll understand.

**Comment by Thodor12** [comment]
Hi Kevin,

No worries, my fault, did not read that. I solved the issue anyhow by just taking out the scopes, I'll go ahead and do some research myself to see what the intended way is.

Thanks for all you do anyway.

**Comment by gtbuchanan** [comment]
We also ran into this error when upgrading from an ancient version. We're using this temporary workaround until we can update all of our "misbehaving" apps, since `ValidateScopeParameter` is currently only used for this purpose:

```csharp
.RemoveEventHandler(OpenIddictServerHandlers.Exchange.ValidateScopeParameter.Descriptor)
```
