### ISSUE TITLE
Conceptual question regarding proper configuration and flow

### ISSUE THREAD

**Issue by corentinbst** [openiddict/openiddict-core#1733]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello,

This is related to #1699 to keep matters separate and properly explain my setup. I'll try to keep things conceptually abstract and independent from the specifities of any cloud provider but I would canonically use Google Cloud with this setup.

My initial need was to create an app's backend that would be secure (obviously). Over time I extracted part of this app into its own service. This setup raised the need for a centralized authentication server.

I have a made a [conceptual diagram of my setup here.](https://i.ibb.co/kKDbJy2/setup-drawio-2.png) Dotted lines and boxes indicate possible future components / conceptual relationships.
As you can see services do not know about the gateway or even other services and applications ; they are self-contained. The point I'm trying to make is that I do not want to use `[Authorize]` tags or even check authentication in my apps & services. It should be handled by the gateway as a single entry-point and ideally this gateway would itself act as the authentication server.

Anoter thing of note is that in this context (in my setup) applications refer only to _back-ends_. Front-ends (React apps, that's my preferred JS framework) would be hosted either in VMs or more likely in the Cloud as serverless instances (in Cloud Run in GCP, equivalent to Azure App Engine) and would be more or less independent from the whole walled garden setup for my back-ends and services. Front-ends would be almost entirely pure presentation ; in fact even the login screen would be served by the gateway using Razor Pages.

The authentication server would be multi-tenant, as we discussed in #1699, using the hostname, for example:

- `tenant.auth.domain.com`
- `tenant.app1.domain.com`

Now my question is not architectural nor infrastructure related, although I would welcome opinions if you have any. But since I'm not too experienced with OIDC I'm not sure anymore which flow I should use and what the whole setup would look like. I initially went with authorization code flow but my setup is not exactly a SPA.
The idea is that the user could access apps (not services, at least not directly) in two ways:

1. `app1.domain.com`
2. `tenant.app1.domain.com`

In both scenarios the gateway would check authentication before forwarding the request, and if that fails redirect the user to the login screen with the callback uri the user tried to access. For instance `app1.domain.com` => `auth.domain.com?callback=app1.domain.com`.
The only difference is that in 1. the login screen would include a "tenant" field, where in 2 the redirection would happen at `tenant.auth.domain.com` and the login screen would **not** include a tenant field since we already know it.
But I'm not sure what happens after that and how it all fits together. In #1699 you mentioned two possibilities and I think the second one is what I'm looking for but I'd like confirmation from you with more context, as well as a more detailed explanation of each step in the flow.

As a side note, but this is more architectural and shouldn't be an issue, but the apps need to know the gateway as well to retrieve user information, and even administer users, groups, etc

Thanks for your feedback ; I hope it is clear. If it is not do not hesitate to ask for more information that I will gladly provide.

**Comment by kevinchalet** [comment]
Hey,

> Anoter thing of note is that in this context (in my setup) applications refer only to back-ends. Front-ends (React apps, that's my preferred JS framework) would be hosted either in VMs or more likely in the Cloud as serverless instances (in Cloud Run in GCP, equivalent to Azure App Engine) and would be more or less independent from the whole walled garden setup for my back-ends and services.

So things are clear for me, could you please clarify how the front-ends would communicate with the backends? HTTP API calls pointing to the gateway?

**Comment by corentinbst** [comment]
Basically yes. I haven't laid out the exact routing and DNS, but most likely apps (from the front-end then) would call their apis (back-ends) with `api.xxx.com/app1/`.

**Comment by kevinchalet** [comment]
> In both scenarios the gateway would check authentication before forwarding the request, and if that fails redirect the user to the login screen with the callback uri the user tried to access. For instance app1.domain.com => auth.domain.com?callback=app1.domain.com.

Given that the gateway is only going to accept API calls, using things like 302 redirects at the gateway level "to redirect the user" isn't going to work really well. Instead, here's how I would approach things:

  - The real OIDC clients should be your frontends apps (so you'll want to use a React OIDC integration).
  - The gateway would work as both an authorization server and as one or more resource servers, accepting API requests with access tokens attached and applying authorization rules based on the targeted API (that you call "app" but should rename for clarity). Standard 401 and 403 responses should be used to reject unauthenticated/unauthorized requests.
  - Flowing the identity from the gateway to the APIs could be done by flowing the token itself or by using special headers to flow the user claims extracted by the gateway (in this case, you'll want to triple-check the APIs themselves can NEVER be reached directly).
  - The right flow to use is definitely the code flow in this case.

Regarding multi-tenancy, the easiest option would be to handle that the client level (i.e in your React apps) or at the authorization server level.

**Comment by corentinbst** [comment]
Alright thanks, I think I understand most of it. Multi-tenancy would be handled at the authorization server level. To make things clear I'll redefine some terms:

- Service: API not exposed to the outside world through the gateway and only relevant in my microservice architecture
- Back-end: API specific to an application, exposed to the outside world
- Front-end / app: presentation layer (using React) linked to a back-end

Am I right in thinking that step by step this would look like this:

1. Client tries to access app1.example.com, he is not authorized
2. Gets a 401. **Front-end** redirects the browser to `auth.example.com/login` with `redirectUrl=app1.example.com`
3. Login page is served by auth.example.com. User enters his credentials, successfully logins, gets a 302 response with `Location=app1.example.com` and with the code in the body. _Now it's a bit unclear how do I access the code from app1_?
4. App1's **front-end** gets the code and sends a post request (using Axios or something) with `code`, `client_id=app1`, no client secret, etc directly to `auth.example.com/authorize`
5. Authorization server gives the access token back to be stored by the front-end in the local storage for app1 and only app1, and the front-end takes care of injecting the token in the `Authorization` request for every header. _If this is true, how do I make it so that the user does not have to re-enter the credentials when trying to access another app_?

**Comment by kevinchalet** [comment]
> Client tries to access app1.example.com, he is not authorized
Gets a 401. Front-end redirects the browser to auth.example.com/login with redirectUrl=app1.example.com

Yeah, tho' you generally don't even need to wait for the 401 response to be returned by the API: the client already knows the user hasn't completed an authentication dance yet as it doesn't have any valid tokens (typically stored in `localStorage` for a SPA).

> Login page is served by auth.example.com. User enters his credentials, successfully logins, gets a 302 response with Location=app1.example.com and with the code in the body. Now it's a bit unclear how do I access the code from app1?

For a SPA, the authorization code is ideally returned as part of the fragment part of the callback URI (`response_mode=fragment`) or as part of the query string (`response_mode=query`). Any OIDC client stack will generally handle extracting it from the callback request for you.

> App1's front-end gets the code and sends a post request (using Axios or something) with code, client_id=app1, no client secret, etc directly to auth.example.com/authorize

Yep (except it's sent to the token endpoint, not to the authorization endpoint). I'd strongly recommend using an OIDC JS stack to handle that for you instead of rolling your own one using Axios. You have fairly good options, like https://github.com/AxaGuilDEv/react-oidc, https://github.com/FormidableLabs/react-native-app-auth (for native React apps) or https://github.com/openid/AppAuth-JS (not specific to React).

> Authorization server gives the access token back to be stored by the front-end in the local storage for app1 and only app1, and the front-end takes care of injecting the token in the Authorization request for every header. If this is true, how do I make it so that the user does not have to re-enter the credentials when trying to access another app?

The identity/tokens stored in local storage are indeed specific to each SPA clients, but the authorization server itself persists the user identity in its own authentication cookie: when a second SPA needs to authenticate the user and redirects the browser to the identity provider, the user is already logged in there so the login screen can be avoided 😃 

Hope it was clear.

**Comment by corentinbst** [comment]
> Yeah, tho' you generally don't even need to wait for the 401 response to be returned by the API: the client already knows the user hasn't completed an authentication dance yet as it doesn't have any valid tokens (typically stored in localStorage for a SPA).

Yes that's true

> For a SPA, the authorization code is ideally returned as part of the fragment part of the callback URI (response_mode=fragment) or as part of the query string (response_mode=query). Any OIDC client stack will generally handle extracting it from the callback request for you.
> Yep (except it's sent to the token endpoint, not to the authorization endpoint). I'd strongly recommend using an OIDC JS stack to handle that for you instead of rolling your own one using Axios. You have fairly good options, like https://github.com/AxaGuilDEv/react-oidc, https://github.com/FormidableLabs/react-native-app-auth (for native React apps) or https://github.com/openid/AppAuth-JS (not specific to React).

Yes I'll take a look at those, thanks. Yes it was the token endpoint I mixed them up.

> The identity/tokens stored in local storage are indeed specific to each SPA clients, but the authorization server itself persists the user identity in its own authentication cookie: when a second SPA needs to authenticate the user and redirects the browser to the identity provider, the user is already logged in there so the login screen can be avoided

Yes because `SignIn` with cookie authentication scheme has already been called in the post-login endpoint, I see...

It was very clear thanks! Now the only thing left is implementing it properly.
Thanks a lot!

**Comment by corentinbst** [comment]
Hey @kevinchalet
I got my whole test setup working properly. I have not tried emulating my "production" environment yet with gateway and such but concerns would be more infrastructure-related there.

The actual flow (_localhost_), which is pretty close to a standard flow, looks like this:

- If client tries to access anything at _localhost_ with no tenant hostname, he gets redirected to `/tenant` with _ReturnUrl_ equal to the url he was trying to access, including the query
- `/tenant` is a tenant selection page with only one text input. Once the client enters a valid tenant and proceeds he gets redirected to what he was trying to access, except the domain will now be _tenant.localhost_
- This point can be reached directly by using _tenant.localhost_, thus skipping the whole tenant selection screen
- If client is not authorized, then the standard flow happens at _tenant.localhost_

Using Postman's authentication system (AuthCode + PKCE), this looks like this:

1. Postman tries to access `https://localhost/authorize` with `redirect_uri=https://oauth.pstmn.io/v1/callback`
2. The tenant is missing, so my middleware redirects him to `https://localhost/tenant?ReturnUrl=/authorize?redirect_uri=https://oauth.pstmn.io/v1/callback&...`
3. I enter my valid tenant, in this case _test_
4. I get redirected to `https://test.localhost/authorize` with `redirect_uri=https://oauth.pstmn.io/v1/callback`
5. I am not logged in with cookies so I get redirected (seamlessly from the POV of the client) to `https://localhost/login?ReturnUrl=/authorize?redirect_uri=https://oauth.pstmn.io/v1/callback&...`
6. I log in and finally gets redirect to `/authorize`
7. Token is exchanged by Postman at `https://test.localhost/token`

At any point I could skip 1,2,3 by directly asking for authorization at `test.localhost`

In production of course Postman would be replaced by my front-end which would do an axios get or something for the token. At this point the front-end would be tenant-aware anyway. This setup is not optimal I suppose but it seems neat. The only thing missing is whitelisting the redirect_uris AFAIK.

For reference here is my tenant redirection middleware:
```C#
app.UseWhen(context => context.RequestServices.GetService<TenantInfo>() is null && !context.Request.Path.Value!.EndsWith("/tenant"),
    app => app.Run(context =>
    {
        context.Response.Redirect("/tenant" + QueryString.Create("ReturnUrl", context.Request.PathBase + context.Request.Path + QueryString.Create(context.Request.Query.ToList())));

        return Task.CompletedTask;
    }));
```
and my redirection code in my `TenantController`:
```C#
private IActionResult RedirectToLogin(string? tenantId)
{
    var builder = new StringBuilder("https://");

    if (tenantId is not null)
        builder.Append(tenantId).Append('.');

    builder.Append(Request.Host).Append("/login");
    builder.Append(QueryString.Create(Request.Query.ToList()));

    return Redirect(builder.ToString());
}
```
Technically the above code should not be used with a `null` tenantId.
If this seems good to you then I can call it a day.

**Comment by kevinchalet** [comment]
Hey @InFarAday,

> If this seems good to you then I can call it a day.

It looks good, but note that while it seems "easy" with Postman (as it's a dead simple OAuth 2.0 implementation that doesn't validate anything at all), things will likely be less easy once you add OIDC to your real React clients, as:
  1. You won't be able to use discovery as-is (because your custom middleware only redirects authorization requests: it's not a real OIDC server).
  2. You'll hit validation errors complaining about things like issuer mismatches (as your clients only know your public "facade" server and not the real identity of the tenant-specific server that created the identity token). You'll also need a way to give the OIDC lib the correct signing credentials of the correct tenant-specific OIDC server, which may not be trivial given your clients are not tenant-aware themselves.

Some custom JS/React code will likely be required if you want the full OIDC validation enforced at the client level.

Cheers.

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if you need additional details 😃
