### ISSUE TITLE
"redirect_uri must be included" error

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#174]
Hi,

I've added OpenIddict to an ASP.NET Identity website and now i'm trying to use that to authenticate from another website, when I redirect I get the following error

error: invalid_request
error_description: redirect_uri must be included when making an OpenID Connect request

Does anyone know what is missing, here is the URL that is passed to the OpenIddict website

`https://mysts/connect/authorize?client_id=48BF1BC3-CE01-4787-BBF2-0426EAD21342&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dwcL3Mnqc6NXQp-W83Z67A5grfwsbp5CYxz9mehrrqj7nAnzja6OAFUuDuSlG73FVzrygg-nVFwmQzk45uL-HRwjPTMpwbfKyBICmVj35d5bhHbgR7wZ79jwVK0WgMrPA&nonce=636052981608509668.YzEzMGYyOGQtOGU1Yy00ZWMyLWE2NjYtMWYwODA0MmEyMjE2OWRkZGUyMjgtNTIyZi00YzdmLTkyODYtMmM1ZWVmYmE2OWFh`

**Comment by kevinchalet** [comment]
Hi,

As explained by the error message you're seeing, your authorization request doesn't include the mandatory `redirect_uri` parameter and is rejected.

**Comment by daver77** [comment]
I had redirect Uri set in the OpenIddictApplications table for the client so I didn't think that would be needed. I've added it to the StartUp OpenIdConnectAuthenticationOptions call now and have got past that error, now I get

error: unsupported_response_type
error_description: The specified response_type parameter is not allowed.

**Comment by kevinchalet** [comment]
> I had redirect Uri set in the OpenIddictApplications table for the client so I didn't think that would be needed. 

It is, because it's required by the OIDC specification: http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

For your second error, enable logging and you'll immediately understand what's wrong.

**Comment by daver77** [comment]
I'm getting the following from the logs

2016-07-28 15:24:01.052 +01:00 [Error] The authorization request was rejected because the implicit flow was not enabled.
2016-07-28 15:24:01.055 +01:00 [Error] The authorization request was rejected with the following error: "unsupported_response_type" ; "The specified response_type parameter is not allowed."

I have created the views as described [here](https://github.com/openiddict/openiddict-core#enabling-interactive-flows-support). Do you know what I could be missing?

**Comment by kevinchalet** [comment]
Both the authorization code and implicit flows must be enabled to use the hybrid flow (code + id_token)
