### ISSUE TITLE
Setting up caching with introspection

### ISSUE THREAD

**Issue by Haraldur-Dadi** [openiddict/openiddict-core#1748]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

I'm working on implementing caching for introspection using event handlers in a project using event handlers. The goal is to use caching to prevent calling the introspection endpoint on the auth service for each call in a given time frame.

I've set up an event handler on the PrepareIntrospectionRequestContext that checks if the token is present in the cache and in case it's a hit it should skip the introspection. A second handler is on HandleIntrospectionResponseContext which adds the token to the cache.

The caching works and gets hit when I call my endpoint the second time with the same token. However I'm not able to skip the introspection and the flow still continues. I've tried using context.HandleRequest() and context.SkipRequest() but in both cases I'm met with an exception: "System.InvalidOperationException: The System.Net.Http request cannot be resolved.".

**Registering OpenIddict on startup**
```c#
services.AddOpenIddict()
    .AddValidation(options =>
    {
        options.SetIssuer("issuer");

        options.UseIntrospection()
            .SetClientId("clientId")
            .SetClientSecret("clientSecret");

        // The event handler responsible for checking the cache
        options.AddEventHandler<OpenIddictValidationEvents.PrepareIntrospectionRequestContext>(builder =>
        {
            builder.UseScopedHandler<IntrospectionCheckCache>()
                .SetOrder(int.MinValue);
        });

        // The event handler responsible for adding token to cache
        options.AddEventHandler<OpenIddictValidationEvents.HandleIntrospectionResponseContext>(builder =>
        {
            builder.UseScopedHandler<IntrospectionAddToCache>()
                .SetOrder(int.MaxValue);
        });

        options.UseSystemNetHttp();
        options.UseAspNetCore();
    });
```

**Check cache event handler**
```c#
public ValueTask HandleAsync(OpenIddictValidationEvents.PrepareIntrospectionRequestContext context)
{
    // If the token is alive in the cache we don't need to perform introspection and request can be marked as handled
    if (_memoryCache.TryGetValue(context.Token, out _))
    {
        Debug.WriteLine("Request is handled");
        context.HandleRequest();
    }

    return default;
}
```

**Add to cache event handler**
```c#
public ValueTask HandleAsync(OpenIddictValidationEvents.HandleIntrospectionResponseContext context)
{
    // Cache the token in case it was active to skip introspection on future requests for a period of time
    if (context.Response.TryGetParameter("active", out var active) && active == true)
    {
        _memoryCache.GetOrCreate(context.Token, cacheEntry =>
        {
            cacheEntry.Value = true;
            cacheEntry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(1);
            return true;
        });
    }

    return default;
}
```

**Comment by Haraldur-Dadi** [comment]
After digging deeper into the OpenIddict code I've put together something that at least seems to work. By changing the event handlers to use the ValidateTokenContext I'm able to skip the IntrospectToken in OpenIddictValidationHandlers.Protection by attaching the principle I cache now. Just a good quick sanity check would be much appreciated😁.

**Registering OpenIddict on startup**
```c#
services.AddOpenIddict()
    .AddValidation(options =>
    {
        options.SetIssuer("issuer");

        options.UseIntrospection()
            .SetClientId("clientId")
            .SetClientSecret("clientSecret");

        // Add caching to introspection
        options.AddEventHandler<OpenIddictValidationEvents.ValidateTokenContext>(builder =>
        {
            builder.UseScopedHandler<IntrospectionCheckCache>()
                .SetOrder(int.MinValue);
        });
        options.AddEventHandler<OpenIddictValidationEvents.ValidateTokenContext>(builder =>
        {
            builder.UseScopedHandler<IntrospectionAddToCache>()
                .SetOrder(int.MaxValue);
        });

        options.UseSystemNetHttp();
        options.UseAspNetCore();
    });
```

**Check cache event handler**
```c#
public ValueTask HandleAsync(OpenIddictValidationEvents.ValidateTokenContext context)
{
    // If the token is alive in the cache we retrieve the principal and set the context principal to skip IntrospectToken
    if (_memoryCache.TryGetValue(context.Token, out ClaimsPrincipal principal))
        context.Principal = principal;

    return default;
}
```

**Add to cache event handler**
```c#
public ValueTask HandleAsync(OpenIddictValidationEvents.ValidateTokenContext context)
{
    // Cache token, if we're here it's a valid token
    _memoryCache.GetOrCreate(context.Token, cacheEntry =>
    {
        cacheEntry.Value = context.Principal;
        cacheEntry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(1);
        return cacheEntry.Value;
    });

    return default;
}
```

**Comment by kevinchalet** [comment]
Hey,

> Just a good quick sanity check would be much appreciated😁.

This is exactly how I would have implemented it (and likely how it will be implemented if it's added as a native feature, depending on the demand 😅)

Cheers.

**Comment by Swoorup** [comment]
> After digging deeper into the OpenIddict code I've put together something that at least seems to work. By changing the event handlers to use the ValidateTokenContext I'm able to skip the IntrospectToken in OpenIddictValidationHandlers.Protection by attaching the principle I cache now. Just a good quick sanity check would be much appreciated😁.
> 
> **Registering OpenIddict on startup**
> 
> ```cs
> services.AddOpenIddict()
>     .AddValidation(options =>
>     {
>         options.SetIssuer("issuer");
> 
>         options.UseIntrospection()
>             .SetClientId("clientId")
>             .SetClientSecret("clientSecret");
> 
>         // Add caching to introspection
>         options.AddEventHandler<OpenIddictValidationEvents.ValidateTokenContext>(builder =>
>         {
>             builder.UseScopedHandler<IntrospectionCheckCache>()
>                 .SetOrder(int.MinValue);
>         });
>         options.AddEventHandler<OpenIddictValidationEvents.ValidateTokenContext>(builder =>
>         {
>             builder.UseScopedHandler<IntrospectionAddToCache>()
>                 .SetOrder(int.MaxValue);
>         });
> 
>         options.UseSystemNetHttp();
>         options.UseAspNetCore();
>     });
> ```
> 
> **Check cache event handler**
> 
> ```cs
> public ValueTask HandleAsync(OpenIddictValidationEvents.ValidateTokenContext context)
> {
>     // If the token is alive in the cache we retrieve the principal and set the context principal to skip IntrospectToken
>     if (_memoryCache.TryGetValue(context.Token, out ClaimsPrincipal principal))
>         context.Principal = principal;
> 
>     return default;
> }
> ```
> 
> **Add to cache event handler**
> 
> ```cs
> public ValueTask HandleAsync(OpenIddictValidationEvents.ValidateTokenContext context)
> {
>     // Cache token, if we're here it's a valid token
>     _memoryCache.GetOrCreate(context.Token, cacheEntry =>
>     {
>         cacheEntry.Value = context.Principal;
>         cacheEntry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(1);
>         return cacheEntry.Value;
>     });
> 
>     return default;
> }
> ```

This appears to no longer work. I still get hits to the introspect endpoint. Are there additional steps to this?

**Comment by caxepok** [comment]
> This appears to no longer work. I still get hits to the introspect endpoint. Are there additional steps to this?

Same, did`t work anymore.

**Comment by Swoorup** [comment]
@caxepok  Use this

```fsharp
  type IntrospectionCheckCache(memoryCache: IMemoryCache) =  
    interface IOpenIddictValidationHandler<ProcessAuthenticationContext> with 
      member _.HandleAsync(context: ProcessAuthenticationContext) =
        if String.IsNullOrEmpty(context.AccessToken) then 
          ValueTask()
        else
          match memoryCache.TryGetValue(context.AccessToken) with
          | true, principal ->
            context.AccessTokenPrincipal <- principal :?> ClaimsPrincipal

            // Effectively skip all these handlers in the link below
            // https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Validation/OpenIddictValidationHandlers.cs#L30-L35
            // These handlers has a filter `RequireIntrospectionRequest` which checks upon this flag.
            context.SendIntrospectionRequest <- false
          | _ -> ()
          ValueTask()

    static member Descriptor: OpenIddictValidationHandlerDescriptor 
        = OpenIddictValidationHandlerDescriptor.CreateBuilder<ProcessAuthenticationContext>()
            .UseSingletonHandler<IntrospectionCheckCache>()
             // Ensure the handler is invoked before the introspection handlers.
            .SetOrder(AttachIntrospectionRequestClientCredentials.Descriptor.Order - 1) 
            .SetType(OpenIddictValidationHandlerType.Custom)
            .Build()

  type IntrospectionAddToCache(memoryCache: IMemoryCache) =
    static member Descriptor =
      OpenIddictValidationHandlerDescriptor.CreateBuilder<ProcessAuthenticationContext>()
        .UseSingletonHandler<IntrospectionAddToCache>()
        .SetOrder(Int32.MaxValue)
        .SetType(OpenIddictValidationHandlerType.Custom)
        .Build()

    interface IOpenIddictValidationHandler<ProcessAuthenticationContext> with
      member _.HandleAsync(context: ProcessAuthenticationContext) =
        memoryCache.GetOrCreate(context.AccessToken, fun cacheEntry ->
          cacheEntry.Value <- context.AccessTokenPrincipal
          cacheEntry.AbsoluteExpirationRelativeToNow <- TimeSpan.FromMinutes(1.)
          cacheEntry.Value)
        |> ignore
        ValueTask()
 ```

**Comment by caxepok** [comment]
> @caxepok Use this

I already tried something like this, but CheckCache invoked last

...
[14:38:39 DBG] The event OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Validation.OpenIddictValidationHandlers+ValidateIntrospectedTokenAudiences.
[14:38:39 DBG] The event OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext was successfully processed by **Home.Service.IntrospectionAddToCache.**
[14:38:41 DBG] The event OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext was successfully processed by **Home.Service.IntrospectionCheckCache.**

Here is my code:

```
public class IntrospectionCheckCache(IMemoryCache memoryCache) : IOpenIddictValidationHandler<ProcessAuthenticationContext>
{
    public static OpenIddictValidationHandlerDescriptor Descriptor { get; }
        = OpenIddictValidationHandlerDescriptor.CreateBuilder<ProcessAuthenticationContext>()
            .UseSingletonHandler<IntrospectionCheckCache>()
            .SetOrder(AttachIntrospectionRequestClientCredentials.Descriptor.Order - 1)
            .SetType(OpenIddictValidationHandlerType.Custom)
            .Build();

    public ValueTask HandleAsync(ProcessAuthenticationContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        if (String.IsNullOrEmpty(context.AccessToken))
            return default;

        if (memoryCache.TryGetValue(context.AccessToken, out ClaimsPrincipal? principal))
        {
            context.AccessTokenPrincipal = principal;
            // Effectively skip all these handlers in the link below
            // https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Validation/OpenIddictValidationHandlers.cs#L30-L35
            // These handlers has a filter `RequireIntrospectionRequest` which checks upon this flag.
            context.SendIntrospectionRequest = false;
        }
        return default;
    }
}

public class IntrospectionAddToCache(IMemoryCache memoryCache) : IOpenIddictValidationHandler<ProcessAuthenticationContext>
{
    public static OpenIddictValidationHandlerDescriptor Descriptor { get; }
        = OpenIddictValidationHandlerDescriptor.CreateBuilder<ProcessAuthenticationContext>()
            .UseSingletonHandler<IntrospectionAddToCache>()
            .SetOrder(Int32.MaxValue)
            .SetType(OpenIddictValidationHandlerType.Custom)
            .Build();

    public ValueTask HandleAsync(ProcessAuthenticationContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        if (String.IsNullOrEmpty(context.AccessToken))
            return default;

        memoryCache.GetOrCreate(context.AccessToken, (cacheEntry) =>
        {
            cacheEntry.Value = context.AccessTokenPrincipal;
            cacheEntry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(10);
            return cacheEntry.Value;
        });
        return default;
    }
}
```

and add this handlers like this:

```
options.AddEventHandler<OpenIddictValidationEvents.ProcessAuthenticationContext>(builder =>
{
    builder.UseScopedHandler<IntrospectionCheckCache>();
});

options.AddEventHandler<OpenIddictValidationEvents.ProcessAuthenticationContext>(builder =>
{
    builder.UseScopedHandler<IntrospectionAddToCache>();
});
```

**Comment by caxepok** [comment]
Moved SetOrder to AddEventHandler builder, and it`s working again!

```
options.AddEventHandler<ProcessAuthenticationContext>(builder =>
{
    builder.UseScopedHandler<IntrospectionAddToCache>()
    .SetOrder(Int32.MaxValue);
});

options.AddEventHandler<ProcessAuthenticationContext>(builder =>
{
    builder.UseScopedHandler<IntrospectionCheckCache>()
    .SetOrder(AttachIntrospectionRequestClientCredentials.Descriptor.Order - 1);
});
```

**Comment by Swoorup** [comment]
> Moved SetOrder to AddEventHandler builder, and it`s working again!
> 
> ```
> options.AddEventHandler<ProcessAuthenticationContext>(builder =>
> {
>     builder.UseScopedHandler<IntrospectionAddToCache>()
>     .SetOrder(Int32.MaxValue);
> });
> 
> options.AddEventHandler<ProcessAuthenticationContext>(builder =>
> {
>     builder.UseScopedHandler<IntrospectionCheckCache>()
>     .SetOrder(AttachIntrospectionRequestClientCredentials.Descriptor.Order - 1);
> });
> ```

Yep forget to show that bit of the code.

**Comment by JamesFieldist** [comment]
Anyone have this working with hybridcache or IDistributedCache?  In memory is great but doesn't work in a distributed system.

Doesn't look like you can serialize claims.

**Comment by JamesFieldist** [comment]
[JwtClaimsPrincipalSerializer.zip](https://github.com/user-attachments/files/21354883/JwtClaimsPrincipalSerializer.zip)

My contribution to the cause. This uses hybredcache but you can easily switch it to IDistributedCache.

Here's how to get it linked up:

```
                options.AddEventHandler<OpenIddictValidationEvents.ProcessAuthenticationContext>(
                    b =>
                        b.UseScopedHandler<IntrospectionCheckCache>()
                            .SetOrder(
                                OpenIddictValidationHandlers
                                    .AttachIntrospectionRequestClientCredentials
                                    .Descriptor
                                    .Order - 1
                            )
                );

                options.AddEventHandler<OpenIddictValidationEvents.ProcessAuthenticationContext>(
                    b => b.UseScopedHandler<IntrospectionAddToCache>().SetOrder(int.MaxValue)
                );

```
