### ISSUE TITLE
UseOpenIddict overload that extends DbContextOptionsBuilder<TContext>

### ISSUE THREAD

**Issue by verdie-g** [openiddict/openiddict-core#1749]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

I've noticed that
```cs
DbContextOptions<MyDbContext> options = new DbContextOptionsBuilder<MyDbContext>()
    .UseNpgsql()
    .UseSnakeCaseNamingConvention()
    .Options;
```
would not compile anymore once I add `UseOpenIddict`
```cs
DbContextOptions<MyDbContext> options = new DbContextOptionsBuilder<MyDbContext>()
    .UseOpenIddict()
    .UseNpgsql()
    .UseSnakeCaseNamingConvention()
    .Options;
```
The reason is `UseOpenIddict` doesn't extend `DbContextOptionsBuilder<TContext>()`. Could you a method that does?

**Comment by kevinchalet** [comment]
Hey,

Sounds reasonable. Would you like to send a PR to add these methods? 😃

**Comment by verdie-g** [comment]
Sure will do next week
