### ISSUE TITLE
Add an option to make client identification mandatory for token requests and userinfo requests

### ISSUE THREAD

**Issue by KerryRitter** [openiddict/openiddict-core#175]
Ideally, there would be an option on the configuration to enforce requiring a client credentials' access token to retrieve a token for a user, or to get results from the userinfo endpoint (maybe others that might be suitable?). 

> I guess it should be named OpenIddictOptions.RequireClientAuthentication/OpenIddictBuilder.RequireClientAuthentication() or something like that.

**Comment by kevinchalet** [comment]
@KerryRitter FYI, I'm working on this feature ATM, but I'm facing a dilemma:
- Should this feature only reject token/revocation requests that don't specify a client_id?
- Or should it also reject token/revocation revocation that don't specify a client_secret (i.e prevent public apps from using these endpoints)?

**Comment by KerryRitter** [comment]
I was thinking the latter. We should be able to authorize the client as a registered client.

**Comment by kevinchalet** [comment]
Note that even with the first option, the client_id would have to be valid (i.e a correspond entry would have to be found in the applications table)
