### ISSUE TITLE
 Caching Introspection Results in YARP Gateway with OpenIddict

### ISSUE THREAD

**Issue by shalom-levi** [openiddict/openiddict-core#1759]
### Confirm you've already contributed to this project or that you sponsor it

- [ ] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello OpenIddict team,

I have an architecture of microservices, using OpenIddict 4.x as my identity server (id-server) and YARP 2.0 as my Gateway (GW). 

For token validation, I'm using introspection. However, to prevent constant hits to my id-server, I'm looking to implement a short-term cache. I'm already using Redis, and I would like to use it to cache the results of the introspection.

My current plan is to implement this caching strategy at the GW level, rather than in the id-server. That is, when a request comes in, the GW would check the cache to see if the token is valid, and only if the token is not in the cache, the GW would send an introspection request to the id-server.

I tried to use the following approach with OpenIddict 4:

`options.AddEventHandler<OpenIddictServerEvents.ValidateIntrospectionRequestContext>(builder =>
    builder.UseInlineHandler(async context => ...
`
However, I couldn't figure out how to inject IDistributedCache into the inline handler, so this approach was not successful.

Can you provide some guidance on how to best implement this caching strategy with OpenIddict, YARP, and Redis? Specifically, how can I use the UseIntrospection() function when a token is not in the cache and properly inject IDistributedCache when using an event handler?

Thank you for your time and assistance.

Best regards,
Shalom Levi.

**Comment by kevinchalet** [comment]
Hi @shalom-levi,

GitHub didn't recognize you as a sponsor. Did you sponsor the project using an organization account?

**Comment by shalom-levi** [comment]
I'm not a sponsor, I'll try to get my organization to join, right now I have an open question, can you help?

**Comment by kevinchalet** [comment]
Support is reserved to current sponsors and contributors, I'm afraid.
