### ISSUE TITLE
Cannot set Microsoft tenant

### ISSUE THREAD

**Issue by verdie-g** [openiddict/openiddict-core#1764]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

When trying to set the Microsoft tenant to `consumers` I get a `OpenIddictExceptions+ProtocolException`. The fetched configuration is https://login.microsoftonline.com/consumers/v2.0/.well-known/openid-configuration but the issuer field is https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0 and OpenIddict expects the two to match.

### To reproduce

```cs
options.UseWebProviders().UseMicrosoft(microsoft =>
{
    microsoft.SetClientId(microsoftClientId)
        .SetClientSecret(microsoftClientSecret)
        .SetRedirectUri("connect/callback-microsoft")
        .SetTenant("consumers")
        .Configure(microsoft => microsoft.Scopes.Add("XboxLive.profile"));
});
```

### Exceptions (if any)

```shell
OpenIddict.Abstractions.OpenIddictExceptions+ProtocolException: An error occurred while handling the configuration response.
  Error: server_error
  Error description: The issuer returned in the server configuration doesn't match the value set in the client registration options.
  Error URI: https://documentation.openiddict.com/errors/ID2165
   at OpenIddict.Client.OpenIddictClientService.<>c__DisplayClass15_0.<<GetConfigurationAsync>g__HandleConfigurationResponseAsync|3>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenIddict.Client.OpenIddictClientService.GetConfigurationAsync(OpenIddictClientRegistration registration, Uri uri, CancellationToken cancellationToken)
   at OpenIddict.Client.OpenIddictClientService.GetConfigurationAsync(OpenIddictClientRegistration registration, Uri uri, CancellationToken cancellationToken)
   at OpenIddict.Client.OpenIddictClientRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<OpenIddict.Abstractions.OpenIddictConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
```
```

**Comment by verdie-g** [comment]
Relevant issue: https://github.com/MicrosoftDocs/azure-docs/issues/38427

Workaround:
```diff
options.UseWebProviders().UseMicrosoft(microsoft =>
{
    microsoft.SetClientId(microsoftClientId)
        .SetClientSecret(microsoftClientSecret)
        .SetRedirectUri("connect/callback-microsoft")
-       .SetTenant("consumers")
+       .SetTenant("9188040d-6c67-4c5b-b112-36a304b66dad") // consumers
        .Configure(microsoft => microsoft.Scopes.Add("XboxLive.profile"));
});
```

Would it make sense to skip the issuer validation for Microsoft? Alternatively the `SetTenant` doc should be updated.

**Comment by kevinchalet** [comment]
> Would it make sense to skip the issuer validation for Microsoft? Alternatively the `SetTenant` doc should be updated.

It's already done for the `common` tenant:

https://github.com/openiddict/openiddict-core/blob/8152ac6171dc14219e049d26f04564f46091d944/src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.Discovery.cs#L52-L63

Where did you see `consumers` documented? I'm not opposed to special-casing it too if it's an official value.

**Comment by verdie-g** [comment]
Ok interesting. This is documented here https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#find-your-apps-openid-configuration-document-uri. I'm struggling to find the relevant doc but I should use this tenant for xbox login.

**Comment by kevinchalet** [comment]
Nice, thanks. I'll special-case `consumers` and `organizations` to use the same approach 😃
