### ISSUE TITLE
What should I do if my authorization service is separate from my authorization UI instead of using the Identity default UI?

### ISSUE THREAD

**Issue by 1518648489** [openiddict/openiddict-core#1768]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

What should I do if my authorization service is separate from my authorization UI instead of using the Identity default UI?

**Comment by kevinchalet** [comment]
Support is reserved to sponsors and contributors.
