### ISSUE TITLE
Client secret requirements

### ISSUE THREAD

**Issue by MDzyga** [openiddict/openiddict-core#1769]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi @kevinchalet,
I know that my subscription is off but could you tell me what requirements client's secret should meet (available characters, min lenght)? 
I can't find this information in your repository or website.
Thank you for your answer.

**Comment by kevinchalet** [comment]
> Hi @kevinchalet,
I know that my subscription is off but could you tell me what requirements client's secret should meet (available characters, min lenght)?

Support requires an active sponsorship and sponsors that cancel their subscription shortly after getting support (as you sadly did) unfortunately lose the benefits of the sponsor status.
