### ISSUE TITLE
[Client] How to pass parameters to the token endpoint on authorization code flow

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#1773]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

We need to pass `plarform` parameter to `Exchnage` server method using `client.AuthenticateInteractiveAsync`
But passing `parameters` dictionary to `client.AuthenticateInteractiveAsync` sends them to `Authorize` controller endpoint but not `Exchnage`.
Does the OpenIddict client support our scenario? Or should this happen another way?

What we need is just to have the parameter `platform` resolved in `Exchange` during the authorization code flow.

cc @dim-37

**Comment by kevinchalet** [comment]
Note: free support is reserved to contributors that made a recent contribution.

Please consider becoming a sponsor to get support.

**Comment by kevinchalet** [comment]
Thanks for sponsoring the project!

> Does the OpenIddict client support our scenario? Or should this happen another way?

While it's not officially supported (yet), it's doable using the events model:

```csharp
services.AddOpenIddict()
    .AddClient(options =>
    {
        options.AddEventHandler<ProcessAuthenticationContext>(builder =>
        {
            builder.AddFilter<RequireTokenRequest>();
            builder.SetOrder(AttachTokenRequestParameters.Descriptor.Order + 1);
            builder.UseInlineHandler(context =>
            {
                Debug.Assert(context.TokenRequest is not null);

                if (context.StateTokenPrincipal is ClaimsPrincipal principal &&
                    principal.FindFirst(Claims.Private.HostProperties)?.Value is string value &&
                    JsonSerializer.Deserialize<JsonElement>(value) is JsonElement properties &&
                    properties.TryGetProperty("platform", out JsonElement platform))
                {
                    context.TokenRequest["platform"] = platform.ToString();
                }

                return default;
            });
        });
    });
```

```csharp
// Ask OpenIddict to initiate the authentication flow (typically, by
// starting the system browser) and wait for the user to complete it.
(_, _, var principal) = await _service.AuthenticateInteractivelyAsync(
    provider,
    properties: new()
    {
        ["platform"] = "demo"
    },
    cancellationToken: stoppingToken);
```

Hope it helped.

**Comment by xperiandri** [comment]
Works, thank you, @kevinchalet !
The only issue we got is that we accidentially put duplicate entries into some claims, and on `sub` claim processing in the client we got
![MicrosoftTeams-image](https://github.com/openiddict/openiddict-core/assets/2365592/90d363e1-02cb-4972-bc23-20dddd9d5927)
Must `sub` claim has only one value by specification?

**Comment by kevinchalet** [comment]
> Must `sub` claim has only one value by specification?

Yep, absolutely:

> sub
    REQUIRED. Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII characters in length. **The sub value is a case sensitive string.**

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if necessary 😃
