### ISSUE TITLE
Please Help! The signing key associated to the specified token was not found.

### ISSUE THREAD

**Issue by Broderick890** [openiddict/openiddict-core#1776]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

The signing key associated to the specified token was not found.

server:

builder.Services.AddOpenIddict()

    .AddCore(options =>
    {
        options.UseEntityFrameworkCore()
               .UseDbContext<UserDbContext>();
        options.UseQuartz();
    })

    // 注册OpenIddict服务端
    .AddServer(options =>
    {
        options.SetAuthorizationEndpointUris("authorize")
            .SetIntrospectionEndpointUris("introspect");

        // Enable the token endpoint.
        options.SetTokenEndpointUris("connect/token");
        // Enable the client credentials flow.
        options.AllowPasswordFlow();
        options.AcceptAnonymousClients();
        options.DisableAccessTokenEncryption();

        var encryptionCert = File.ReadAllBytes(Path.Combine(AppContext.BaseDirectory, "Cert/Sign.pfx"));

        options.AddSigningCertificate(new System.Security.Cryptography.X509Certificates.X509Certificate2(encryptionCert));

        options.UseAspNetCore()
               .EnableTokenEndpointPassthrough().DisableTransportSecurityRequirement();

        options.AddEncryptionKey(new SymmetricSecurityKey(
         Convert.FromBase64String("DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=")));

        options.AddSigningKey(new SymmetricSecurityKey(
       Convert.FromBase64String("DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=")));
    })
    .AddValidation(options =>
    {
        options.UseLocalServer();
        options.UseAspNetCore();
        options.Configure((a) =>
        {
            a.TokenValidationParameters.ValidateIssuer = false;
            a.TokenValidationParameters.ValidateIssuerSigningKey = false;
        });

    });

api:

// Register the OpenIddict validation components.
builder.Services.AddOpenIddict()
    .AddValidation(options =>
    {
        // Note: the validation handler uses OpenID Connect discovery
        // to retrieve the address of the introspection endpoint.
        options.SetIssuer(builder.Configuration["IdentityServiceBaseUrl"]);
        options.AddAudiences("api1");

        // Configure the validation handler to use introspection and register the client
        // credentials used when communicating with the remote introspection endpoint.

        options.AddEncryptionKey(new SymmetricSecurityKey(
        Convert.FromBase64String("DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=")));

        // Register the System.Net.Http integration.
        options.UseSystemNetHttp();

        // Register the ASP.NET Core host.
        options.UseAspNetCore();

        options.Configure((a) =>
        {
            a.TokenValidationParameters.ValidateIssuerSigningKey = false;
            a.TokenValidationParameters.ValidateIssuer = false;
        });
    });

**Comment by kevinchalet** [comment]
Support is reserved to sponsors and contributors.
