### ISSUE TITLE
Angular Auth code flow with Yarp and resource microservices

### ISSUE THREAD

**Issue by syedemad** [openiddict/openiddict-core#1777]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hello again,
I already asked a question #1683 and got your kind answer. At that time i was using password grant for my mobile app and then I also got Angular client for which I wanted to use Auth code flow. Now in continuation i am having this issue
Overview:

- My server url is 172.16.1.154
- The services are based on microservice architecture
- proxy is running at localhost:8090
- Issuer set as: localhost:8060 By using the Setissuer #1610 (Just did it now but failing for Angular)
- Issuer is set as localhost:8060 in apis appsettings
- I have added this code for forwarding header  in program.cs for both identity and proxy core apps 
 `var forwardOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
    RequireHeaderSymmetry = false
};

forwardOptions.KnownNetworks.Clear();
forwardOptions.KnownProxies.Clear();

// ref: https://github.com/aspnet/Docs/issues/2384
app.UseForwardedHeaders(forwardOptions);`

1. My android app is getting token via proxy 172.16.1.154:8090 and can call other apis with valid response via proxy (as the apis are using issuer set as localhost:8060 for inter service communication)
2. From angular i have set issuer to 172.16.1.154:8060 (auth server port rather proxy) From here i can get the token and can validate using introspect at 172.16.1.154:8060 but when i call the api its rejected because from api the issuer is set as localhost

So what I want: My existing code from android runs from proxy to call password grant flow
From angular I use the publicly accessible ip (172.16.1.154) to host and serve the login page from Auth server. 
When token is obtained I use the proxy to call other apis by passing the token received and still use the localhost for inter services issuer path

**Comment by kevinchalet** [comment]
Hi,

To prevent abuses and as indicated [here](https://github.com/sponsors/kevinchalet), sponsors who cancel their subscription within the first 12 months - as you sadly did - lose the benefits of their sponsorships, including the dedicated support.
You can re-enable your subscription with a one-time $500 sponsorship.

Regards.
