### ISSUE TITLE
Cannot set audiences with instrospection

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#179]
```
        app.UseOAuthIntrospection(options =>
        {
            options.AutomaticAuthenticate = true;
            options.AutomaticChallenge = true;
            options.Authority = "http://localhost:5000/";
            //options.Audiences = new List<string>();
            options.ClientId = "resource_server";
            options.ClientSecret = "875sqd4s5d748z78z7ds1ff8zz8814ff88ed8ea4z4zzd";
        });
```

options.Audiences is readonly.

It would be cool if we could get a sample where the resource server is not the same as the authorization server.

I'm having a bit of trouble setting this up at the moment.

**Comment by kevinchalet** [comment]
> options.Audiences is readonly.

The property itself is readonly but the collection is mutable. You can add new items by calling `options.Audiences.Add(...)`.

**Comment by jayrulez** [comment]
I see. Thank you for the quick answer.
