### ISSUE TITLE
Dynamic support of external identity providers (Azure AD)

### ISSUE THREAD

**Issue by dxnxk-0** [openiddict/openiddict-core#1791]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi,

I have a multitenant SaaS application, exposing an ASP.NET API. The application SPA, registered as a public client in openiddict, uses an authorization code flow to get user tokens, and then access the API endpoints by provided this token as a bearer token in the Authorization header. The API enpoints are protected by openiddict and users are authenticated internally using their password. Authenticated users have a session managed by a cookie on the `/connect/authorize` endpoint which avoid entering their password if the cookie is still valid.

I have also other kind of applications accessing the API with their own (confidential) openiddict application, with or without users (authorization code, client credentials or device flow).

Now, I want to add the capability for the tenants to register external OIDC identity providers (IDP) - only Azure AD IDPs for now - where they would like their user to authenticate. The application, as an oidc client, will provision the users automatically by reading the Azure AD openid token. 

I have implemented a two stages login process, where the email of the user is first sent to the API which returns a login url: 
- the standard login url if no external idp is configured for this user
- or the one for the external IDPS, which redirect the user to Azure AD authorize endpoint in fine

While redirecting the user to the Azure AD authorize endpoint, I plan to use the state to keep track of the original client request (redirect_uri, client id, pkce code challenge), and after having created/updated the user, set the session cookie and redirect to my `/connect/authorize` to continue the flow as normal.

First, does this approach looks reasonable to you ?

Second, it's unclear to me how I can use the OpenIddict client stack to interact with Azure AD in this scenario. Can I use it in my callback endpoint or do I have to do everything by end ? (from openid-configuration, jwks to id_token verification) 

If yes, how can I register dynamically the external IDP into Openiddict when the users add/delete them ?

Thanks in advance for your help.

**Comment by kevinchalet** [comment]
Hey @pascaldanek,

Thanks for sponsoring the project, much appreciated! ❤️ 

> I have implemented a two stages login process, where the email of the user is first sent to the API which returns a login url:
> 
>     * the standard login url if no external idp is configured for this user
> 
>     * or the one for the external IDPS, which redirect the user to Azure AD authorize endpoint in fine
> 
> 
> While redirecting the user to the Azure AD authorize endpoint, I plan to use the state to keep track of the original client request (redirect_uri, client id, pkce code challenge), and after having created/updated the user, set the session cookie and redirect to my `/connect/authorize` to continue the flow as normal.
> 
> First, does this approach looks reasonable to you ?

This is a common approach that works well.

That said, if the SPA client application is the component that sends the email address to the custom API you mentioned, I'd personally implement differently: instead of having such an endpoint, I'd simply tweak the SPA client to send the email address as part of the standard `login_hint` authorization request parameter: your authorization endpoint action would resolve it from `OpenIddictRequest.LoginHint` and would either redirect the user to the local login page or Azure AD depending on your custom "is it an external user?" logic. It's not only simpler but also more "standard" 😃 

> Second, it's unclear to me how I can use the OpenIddict client stack to interact with Azure AD in this scenario. Can I use it in my callback endpoint or do I have to do everything by end ? (from openid-configuration, jwks to id_token verification)

The OpenIddict client has an Azure AD/Microsoft Account integration shipping as part of the `OpenIddict.Client.WebIntegration` package (more info here: https://kevinchalet.com/2022/12/16/getting-started-with-the-openiddict-web-providers/) that you can definitely use for the scenario you describe. As shown in the blog post, all aspect of the request handling are covered by the OpenIddict client itself (configuration retrieval, request creation, token validation, etc.) but you have to create a custom callback action, that works pretty much like the authorization endpoint you created for the server part.

While it can be a good place to handle things like local account creation, it can also be as simple as:

```csharp
app.MapMethods("callback/login/microsoft", new[] { HttpMethods.Get, HttpMethods.Post }, async (HttpContext context) =>
{
    var result = await context.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);

    var identity = new ClaimsIdentity(Providers.Microsoft);
    // ... copy the claims you want to preserve to your local authentication cookie.

    var properties = new AuthenticationProperties
    {
        RedirectUri = result.Properties.RedirectUri
    };

    // Note: the constant used here will differ if you use ASP.NET Core Identity and treat
    // Azure AD as an Identity external provider (IdentityConstants.ExternalScheme).
    return Results.SignIn(new ClaimsPrincipal(identity), properties, CookieAuthenticationDefaults.AuthenticationScheme);
});
```

It all depends on your specific requirements 😃 

> If yes, how can I register dynamically the external IDP into Openiddict when the users add/delete them ?

To give you a precise answer, I'd need to know how you implemented multitenancy (there are multiple approaches that all have very different requirements/implications).

That said, the OpenIddict client and the web providers companion package both use `Microsoft.Extensions.Options` to manage options initialization, so the most common approach to implement dynamic configuration would consist in implement a custom `IConfigureOptions<OpenIddictClientWebIntegrationOptions.Microsoft>` that populates the `OpenIddictClientWebIntegrationOptions.Microsoft` object with the dynamic settings configured for the tenant.

If you need to enable the Azure AD "selectively" instead of enabling it via `options.UseWebProviders().UseMicrosoft()`, it can be done using a dynamic service resolution. E.g:

```csharp
services.AddSingleton<IConfigureOptions<OpenIddictClientOptions>>(provider =>
{
    var info = provider.GetRequiredService<ICurrentTenantInfo>();
    if (info.IsAzureAdIntegrationConfigured)
    {
        // Allow the OpenIddict client Microsoft integration logic to kick in and add Azure AD
        // to the list of configured providers for you (OpenIddictClientOptions.Registrations).
        return new OpenIddictClientWebIntegrationConfiguration.Microsoft(provider);
    }

    // No-op as the Azure AD details aren't configured.
    return new ConfigureOptions<OpenIddictClientOptions>(action: null);
});
```

Hope it helps 😃

**Comment by dxnxk-0** [comment]
Hi Kevin, and thanks for this quick and rich response :) 

> Thanks for sponsoring the project, much appreciated! ❤️

You're welcome, I am very glad to have the opportunity to sponsor an opensource project like OpenIddict.

> That said, if the SPA client application is the component that sends the email address to the custom API you mentioned, I'd personally implement differently: instead of having such an endpoint, I'd simply tweak the SPA client to send the email address as part of the standard login_hint authorization request parameter: your authorization endpoint action would resolve it from OpenIddictRequest.LoginHint and would either redirect the user to the local login page or Azure AD depending on your custom "is it an external user?" logic. It's not only simpler but also more "standard" 😃

Thanks for the advice, I will do that 👍

> To give you a precise answer, I'd need to know how you implemented multitenancy (there are multiple approaches that all have very different requirements/implications).

Not sure what details you need, here is an overview: it is a b2b multitenant applications. A business is represented as a `company` object. Users can be member of a `company`, but there are also users outside of any companies, like administrators. There is only one authorization server/endpoint for the whole application. The only way tenants can affect the login part is by declaring an external oidc provider which will be used instead of the internal user/password authentication at login time. Tenants do not appear in the url, they are part of the user claim. Does it give you enough details ? 

> That said, the OpenIddict client and the web providers companion package both use Microsoft.Extensions.Options to manage options initialization, so the most common approach to implement dynamic configuration would consist in implement a custom IConfigureOptions<OpenIddictClientWebIntegrationOptions.Microsoft> that populates the OpenIddictClientWebIntegrationOptions.Microsoft object with the dynamic settings configured for the tenant.

Not sure how to implement that, but does it mean I can only declare the external IDP at startup ? Do I have a way to register / unregister the clients when my users create/delete them ? 

> If you need to enable the Azure AD "selectively" instead of enabling it via options.UseWebProviders().UseMicrosoft(), it can be done using a dynamic service resolution.

Can you please explain what you mean by "selectively" ? What I want is that if my callback is called, referring to an issuer that is active on the platform, openiddict handles it and I can then provision the user automatically and redirect him to my authorize endpoint using the state I passed at the beginning of the flow.

When the user will be redirected from AD to my callback, the only things I have in the context will be the code, the issuer and the state right ? Is the issuer enough for openiddict to resolve which client to use ?

Thanks !

**Comment by kevinchalet** [comment]
Hey,

> Does it give you enough details ?

Pretty much, yeah. Assuming I understood you correctly, it sounds like it's a very limited form of multitenancy where there's no per-tenant DI container (which is what OrchardCore does: it dynamically allocates an isolated DI container and a middleware pipeline for each tenant) or even different options instance per tenant (a-la-SaasKit).

Unfortunately, this won't work with the OpenIddict client.

In the current version, client registrations can only be configured by being attached to `OpenIddictClientOptions.Registrations`: it doesn't have to be a startup-only thing - `Microsoft.Extensions.Options` supports reloading options using an `IChangeToken` (tho' it's not the simplest thing to implement) - but this technically means you need to a dynamic `OpenIddictClientOptions` per tenant. I don't have a sample for the client stack, but here's one for the server part that should provide a better view of what I mean: https://stackoverflow.com/a/49682427/542757 😄

"true" dynamic client registrations - created programmatically by the developer and stored in a DB or created automatically by OpenIddict directly via the [OAuth 2.0 Dynamic Client Registration Protocol](https://datatracker.ietf.org/doc/html/rfc7591) if the server supports it - may be added in the future, but it's a massive feature with a very specific threat model and the actual demand is extremely low.

As an alternative, you can take a look at the Microsoft OIDC handler, but it will have the same limitation: the client details must be attached to the `OpenIdConnectOptions` using `IConfigureOptions<OpenIdConnectOptions>`.

**Comment by dxnxk-0** [comment]
Thanks, so you confirm I need to do the token retrieval + validation by hand correct ? I will need to rely on the state parameter to track which AD tenant is in use right ? Do you recommend any library to facilitate that ?

**Comment by kevinchalet** [comment]
> Thanks, so you confirm I need to do the token retrieval + validation by hand correct ?

Sadly yes, if you can't move to a different multitenancy model such as the ones I mentioned - that would allow you to use the OpenIddict client or the MSFT OIDC handler - it's pretty much your only option.

> I will need to rely on the state parameter to track which AD tenant is in use right ?

Yeah, you'd certainly need to store some tenant info in your `state` to be able to resolve it when the authorization response is returned to your callback path.

> Do you recommend any library to facilitate that ?

For JWT validation, you can use https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet, but I'm not aware of a library that will take care of the OIDC protocol details for you. Implementing that is definitely not going to be an easy task (there are tons of sensitive security aspects), but you could get some inspiration from the OpenIddict client or the MSFT OIDC handler.

That said, if it's an important feature for you, I'm open to discussing implementing it for the next major OpenIddict version. Feel free to email me if you're interested 😃

**Comment by dxnxk-0** [comment]
> Implementing that it's definitely not going to be an easy task (there are tons of sensitive security aspects)

In my (limited) use case, what do we have beyond just this ?
- retrieve the openid-configuration of the AD tenant
- retrieve the JWKS (using https)
- validating the `id_token` signature (using one of the jwks public key)
- using the claims to create/update the user and create a session

> That said, if it's an important feature for you, I'm open to discussing implementing it for the next major OpenIddict version. Feel free to email me if you're interested 😃

Thank you I will !

**Comment by kevinchalet** [comment]
> In my (limited) use case, what do we have beyond just this ?

On paper, it always seems fairly easy to implement, but in practice, there are many security checks that must be implemented, including things like anti-forgery to prevent session fixation attacks or nonce replay detection (not to mention additional layers of protection like PKCE).

**Comment by dxnxk-0** [comment]
Ok, thanks for the help. I am closing this and will follow up by email. Best,

**Comment by kevinchalet** [comment]
> If you need to enable the Azure AD "selectively" instead of enabling it via `options.UseWebProviders().UseMicrosoft()`, it can be done using a dynamic service resolution. E.g:
> 
> ```cs
> services.AddSingleton<IConfigureOptions<OpenIddictClientOptions>>(provider =>
> {
>     var info = provider.GetRequiredService<ICurrentTenantInfo>();
>     if (info.IsAzureAdIntegrationConfigured)
>     {
>         // Allow the OpenIddict client Microsoft integration logic to kick in and add Azure AD
>         // to the list of configured providers for you (OpenIddictClientOptions.Registrations).
>         return new OpenIddictClientWebIntegrationConfiguration.Microsoft(provider);
>     }
> 
>     // No-op as the Azure AD details aren't configured.
>     return new ConfigureOptions<OpenIddictClientOptions>(action: null);
> });
> ```

For the record, the web provider registration story was improved in [OpenIddict 4.5](https://github.com/openiddict/openiddict-core/releases/tag/4.5.0) (multiple instances of the same provider are now supported).

Instead of doing what I did in the quoted snippet, you now have to add a registration for each web provider instance. E.g:

```csharp
services.AddOptions<OpenIddictClientOptions>()
    .Configure<ICurrentTenantInfo>(static (options, info) =>
    {
        if (info.IsAzureAdIntegrationConfigured)
        {
            options.Registrations.Add(new OpenIddictClientRegistration
            {
                ProviderType = ProviderTypes.Microsoft,
                ProviderSettings = new OpenIddictClientWebIntegrationSettings.Microsoft
                {
                    Tenant = "common"
                },

                // ... other registration details like client_id/client_secret.

                // The issuer URI will be automatically added by the OpenIddict.Client.WebIntegration package.
            });
        }
    });
```
