### ISSUE TITLE
JWT Claims serialization - multiple VS single value(s)

### ISSUE THREAD

**Issue by dxnxk-0** [openiddict/openiddict-core#1792]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Is seems that the way claims are serialized in json web tokens depends on their arity.

For instance, the `role` claim can contains one to n roles. If it has one, it will be serialized as a string, if multiple, it will be serialized as an array. 

This is quite inconsistent and is not ideal for the clients which need to read the token, often expecting a stable schema.

Is there any way to configure a given claim to always be serialized as an array to allow a consistent reading ot the token ? What do you recommend ? 

Thanks !

**Comment by kevinchalet** [comment]
> Is seems that the way claims are serialized in json web tokens depends on their arity.
> 
> For instance, the `role` claim can contains one to n roles. If it has one, it will be serialized as a string, if multiple, it will be serialized as an array.
> 
> This is quite inconsistent and is not ideal for the clients which need to read the token, often expecting a stable schema.

It's a very frequent scenario in OpenID Connect and clients must be able to support both cases (otherwise, it's a bug in their implementation that should be fixed). Here's an example with the `aud` claim:

> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

https://openid.net/specs/openid-connect-core-1_0.html#IDToken

I wouldn't recommend returning an array for single-element claims, but if you want to do so, you should be able to use `JSON_ARRAY` as the claim value type (`Claim.ValueType`) to force IdentityModel to represent it as a JSON array.

**Comment by kevinchalet** [comment]
In case you'd like to use a constant, it's in `JsonClaimValueTypes`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/0ac187fe1a185c6a412b0b7791be790ee82ed2db/src/Microsoft.IdentityModel.JsonWebTokens/JsonClaimValueTypes.cs#L21

**Comment by dxnxk-0** [comment]
I have seen that in the RFC, but nevertheless I really wonder if I can live with a non stable json schema (at least for custom claims). Thank you !

**Comment by kevinchalet** [comment]
We all have our pet peeves 😄 

Glad it helped.

**Comment by jtanios** [comment]
Why isn't the value type a parameter in any of the `AddClaim()` extension methods provided in `OpenIddictExtensions`?

Background:
I'm implementing an [External Authentication Method for Entra](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-external-method-provider#microsoft-entra-id-processing-of-the-provider-response). It requires the "amr" claim to be returned as an array that contains a single element!
>The amr claims for the authentication method used in authentication. This value should be returned as an array, and only one method claim should be returned. For the list of claims, see [Supported amr claims](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-external-method-provider#supported-amr-claims).
