### ISSUE TITLE
Openiddict - MongoDB Integration 100% CPU issue

### ISSUE THREAD

**Issue by minkminktc** [openiddict/openiddict-core#1799]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

My team is implementing openiddict and it consumes 100% CPU after monitoring it via mongo compass.

![image](https://github.com/openiddict/openiddict-core/assets/72398864/e0337c05-54b8-4923-9102-874685813b47)

 The dashboard shows that the most CPU consumption is authorization as pictures below.

![image](https://github.com/openiddict/openiddict-core/assets/72398864/480e4f60-0344-48c3-9543-ec0c2473155a)

How to fix this and Does it relate to an inappropriate index?

![image](https://github.com/openiddict/openiddict-core/assets/72398864/7a416269-99aa-450d-a72c-8438044520c0)

Thanks in advance

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to contributors and sponsors.

Closing.
