### ISSUE TITLE
Add built-in logging

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#18]
We should update `OpenIddictManager` and/or `OpenIddictProvider` to log important events, like ASP.NET Identity does: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs#L586

**Comment by ilmax** [comment]
Self assigned

**Comment by ilmax** [comment]
Can this be closed or do you plan other changes?

**Comment by kevinchalet** [comment]
Looks like we have a solid logging base now. I think we can indeed close this ticket :+1: 

Thanks :clap:
