### ISSUE TITLE
Openiddict - MongoDB Integration 100% CPU issue

### ISSUE THREAD

**Issue by minkminktc** [openiddict/openiddict-core#1800]
### Personal contribution

- [X] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

identity-app-dmz.thailandpost.com

### Describe the bug

My team is implementing openiddict and it consumes 100% CPU after monitoring it via mongo compass.

![image](https://github.com/openiddict/openiddict-core/assets/72398864/a2cf6d58-2780-43b7-bc43-a7441c6eb65a)

The dashboard shows that the most CPU consumption is authorization as pictures below.

![image](https://github.com/openiddict/openiddict-core/assets/72398864/5380aadc-78a1-4fd7-a94d-c7ea02f6512f)

How to fix this and Does it relate to an inappropriate index?

![image](https://github.com/openiddict/openiddict-core/assets/72398864/c4fe363b-24f8-405d-a36b-98287e10bf56)

Thanks in advance

### To reproduce

It is affecting database

**Comment by kevinchalet** [comment]
Seriously? I already told you support was sponsors-only: trying to resubmit the same support request using the wrong issue template just to avoid sponsoring the project not only makes me waste my time but it's also a clear sign of disrespect.

Do that again and you'll get banned...

**Comment by minkminktc** [comment]
I am sorry mate, I am not good at English, I just want someone to help me
with the issue, Where should I look for someone to help me solve the issue?

**Comment by kevinchalet** [comment]
Your English is excellent and certainly good enough to understand that support here is reserved to sponsors ; as I told you 🤣 

To get help... it's not complicated: ask your employer to sponsor the project (more information here: https://github.com/sponsors/kevinchalet) and I'll happily take a look at your support case.

**Comment by minkminktc** [comment]
My employer ask how much you would like to be sponsored in order to solve
this issue ASAP? how much for one-time payment and how much for monthly?

**Comment by kevinchalet** [comment]
As indicated by https://github.com/sponsors/kevinchalet, sponsorships for companies start at $25/month (or $300/year that you can do as a one-time payment if you prefer).
