### ISSUE TITLE
Owin client and asp.net core server

### ISSUE THREAD

**Issue by ahinin79** [openiddict/openiddict-core#1803]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

I would like to implement an owin ASP.NET Client (net48) and ASP.NET Core openiddict server (net7),
so that the controllers in client can be authorized through openiddict server.

Is it possible?

**Comment by ahinin79** [comment]
I am now testing with Mortis.Client.
When I access /login?provider=local, it returns "The entity type OpenIddictEntityFrameworkToken is not part of the model for the current context."

![Screenshot 2023-06-21 154218](https://github.com/openiddict/openiddict-core/assets/66289357/ecb52fa3-76e4-4857-b13f-13afa10de6e6)

Any idea on this?

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
