### ISSUE TITLE
How to handle CliendId Validation in Refresh Token grant type?

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#1804]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Hello @kevinchalet ,

We have confirgured the app with openiddict and now enabled the refresh token support.

The server validate's the ClientID to provide the access token for refresh_token grant type.

Can we able to get the access token using refresh_token grant type without client_id validation?

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
