### ISSUE TITLE
Save access tokens to database

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#182]
Does openiddict support saving access tokens to the database out of the box?

I see where there is a table for token storage.

If it does, how can I enable it?

When I get a token ropc style, I do not see the record in the database.

My motivation for doing this is to implement two factor auth for ropc flow.

I am thinking of creating a TokenClaim table that stores claims for a token. One of those claims will be a two factor key. If the claim exists in the db then the user is two-factor-authenticated.

So when a user successfully gets a token, if they have two factor enabled then they will have a code sent to them.

I will have a policy to check that the currently logged in token has this token claim on any action that requires 2fa.

Also, is there any way I can subscribe to an event to know when a token is granted and run some custom code (Sending 2fa code if 2fa is enabled).

**Comment by kevinchalet** [comment]
> Does openiddict support saving access tokens to the database out of the box?

No. Mainly for performance reasons. Only refresh tokens are stored and can be revoked.

> My motivation for doing this is to implement two factor auth for ropc flow.

Very bad idea. ROPC has never and will never support 2FA. Of course you could probably hack it and make your own non-standard sauce, but I don't recommend it.

You should **strongly** consider using an interactive flow like code or implicit.

**Comment by jayrulez** [comment]
I do agree with you that it is a bad hack having done it in another project.

There is a native android app consuming the api. 

They would rather not to deal with non-native views... Can I still satisfy them without using ropc?

**Comment by kevinchalet** [comment]
> They would rather not to deal with non-native views... Can I still satisfy them without using ropc?

The recommended approach is to open the native browser and handle everything there (registration, login, 2FA, consent, etc.).

If it's definitely not an option for you, you could consider creating your own non-standard grant... but OpenIddict deliberately doesn't allow that. I'd recommend going with ASOS in this case: http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-introduction/

**Comment by jayrulez** [comment]
@PinpointTownes I'll evaluate this. Thank you.

**Comment by kevinchalet** [comment]
Closing. Feel free to reopen if you still need help.

**Comment by jayrulez** [comment]
So a custom grant type is definitely the way to go based on my considerations over the past few weeks.

I'm at a loss here though as I see openiddict does not support custom grant types.

I would hate to have to implement all the conveniences that openiddict offers which we definitely want to make use of just to implement this.

Is there any chance that openiddict will support custom grant types in the future?

**Comment by kevinchalet** [comment]
> Is there any chance that openiddict will support custom grant types in the future?

There's technically nothing that prevents us from allowing devs to implement custom grants since it's supported by ASOS (see this SO post for [a sample implementing the assertion grant](http://stackoverflow.com/questions/39008642/use-openidconnectserver-and-try-to-connect-to-facebook-through-api-service)).

The biggest concern I have is that doing that is frankly risky. Not everyone is an OAuth2/OIDC expert and unlike ASOS, OpenIddict has been specially designed for newbies, so allowing that might lead to crazy custom grant implementations.

That said, I'm not fundamentally opposed to changing that. I'll see if I can find a reasonable design.

**Comment by jayrulez** [comment]
Sounds great. I'm looking forward to see the design you come up with.

I envision something like this.

Configuring openiddict, I would add a line like:

.EnableCustomFlow("MyCustomGrantType", CustomGrantTypeHandler)

CustomGrantTypeHandler could implement some kind of interface to conform to whatever requirements are needed.

CustomGrantTypeHandler should take care of handling the token request and token validation.

**Comment by kevinchalet** [comment]
@jayrulez the current approach I have in mind is to allow you to handle token requests directly in a custom controller action. You can read https://github.com/openiddict/openiddict-core/issues/194#issuecomment-242507822 for more information.

**Comment by jayrulez** [comment]
This will work for us. Thank you @PinpointTownes .

Do you still intend to look look at supporting custom grant types in openiddict?

I feel bit dirty bastardizing ROPC ;) 

I'm also thinking about implementing our identity system around ASOS as asp.net identity doesn't really fit with our requirements (Multiple email addresses and phone numbers per account and some other stuff) though this is not a priority right now.

**Comment by kevinchalet** [comment]
> Do you still intend to look look at supporting custom grant types in openiddict?

Yep, I'm working on a PR that will remove the "non-standard flows checks" and add a `EnableCustomFlow` method.
