### ISSUE TITLE
Issue with RedirectUri when the application using OpenIddict Client is behind a reverse proxy

### ISSUE THREAD

**Issue by davidepolino** [openiddict/openiddict-core#1820]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

Microsoft

### Describe the bug

Dear Kevin,
we developed an OpenIddict AspNet Core Client to implement the OAuth2 authentication for our server application and we want to use Microsoft as web provider. This is the situation:
- we have a Nginx server which works as a reverse proxy;
- our server application runs on a docker container (with internal urls, behind the reverse proxy) and includes the OpenIddict client.

We are facing the following issue:
1) We call Microsoft authorization service using the following code: 
        // Microsoft web provider configuration:
        ...AddOpenIddict().AddClient(options =>
                ...
                options.UseWebProviders()
                  .UseMicrosoft(microsoftOptions =>
                  {
                    microsoftOptions
                      .SetClientId(provider.ClientId)
                      .SetTenant(provider.Tenant)
                      .SetClientSecret(provider.ClientSecret)
                      .SetRedirectUri("callback/login/microsoft");
                  });
                  ...

        // Challenge
        ...
        properties.SetString(OpenIddictClientAspNetCoreConstants.Properties.ProviderName, 'Microsoft');
        return Challenge(
            authenticationSchemes: OpenIddictClientAspNetCoreDefaults.AuthenticationScheme,
            properties: properties);

2) We expect that, after the Challenge, we are redirect to https://public_url/callback/login/microsoft endpoint, but the redirect_uri parameter passed to the Microsoft authentication page is http://public_url/callback/login/microsoft, and it's refused by Microsoft because it uses the http protocol instead of https. 
We tried to pass an absolute url to the SetRedirectUri method, but we got an ID0309 error: "A grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options." So, it seems that the redirect_uri parameter is managed someway by the OpenIddict library.

Are we missing something in the configuration, or is there something we are doing wrong? Can you help us?
Thank you very much in advance.

### To reproduce

// Microsoft web provider configuration in our Startup
...AddOpenIddict().AddClient(options =>
{
    ...
    options.UseWebProviders()
        .UseMicrosoft(microsoftOptions =>
        {
            microsoftOptions
                .SetClientId(provider.ClientId)
                .SetTenant(provider.Tenant)
                .SetClientSecret(provider.ClientSecret)
                .SetRedirectUri("callback/login/microsoft");
        });
});
...

// Challenge used in our authorize action
 ...
properties.SetString(OpenIddictClientAspNetCoreConstants.Properties.ProviderName, 'Microsoft');

return Challenge(
    authenticationSchemes: OpenIddictClientAspNetCoreDefaults.AuthenticationScheme,
    properties: properties);

**Comment by kevinchalet** [comment]
Hi,

What you describe is not an issue with the Microsoft provider integration itself, but a configuration issue in your app.

If you need help to fix that, please consider asking your employer to sponsor the project. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
