### ISSUE TITLE
Disable user access from custom logic

### ISSUE THREAD

**Issue by paolo8417** [openiddict/openiddict-core#1834]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi,

I need to add some custom logic to disable user access (I need the dbcontext to read the logic from other tables). The user can sign in now with both Authorization Code or Resource owner (maybe in the future also Implicit). Which is the best approach to add this custom logic? On the authorization controller or using events?

**Comment by kevinchalet** [comment]
Hey,

There are multiple approaches to implement such a scenario. These are my 2 favorite ones:
  - At the authorization server level (if you want to block the login process). For that, just update the authorization controller to avoid calling `SignIn(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` if the user has been disabled. You can do that for both interactive flows (in this case, you'll likely want to return an error page) and the refresh token flow (in this case, call `Forbid(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` to reject the request).

  - At the API level (if you want to block calls to the APIs, after the login process). To implement that, your best option is to use ASP.NET Core's authorization stack and create a custom authorization policy. If you're not familiar with the authorization stack, https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-7.0 should put you on the right track.

Hope it helped. Let me know if you need additional details 😃

**Comment by paolo8417** [comment]
Ok,

what about listen to server events?

**Comment by kevinchalet** [comment]
What server events exactly are you referring to?

**Comment by paolo8417** [comment]
I'm reading a lot of server events, for example _OpenIddictServerEvents.ProcessSignInContext_, and I wonder if any of these could be suitable for my problem.

**Comment by kevinchalet** [comment]
The events model is great for advanced stuff. You could certainly implement a bunch of `IOpenIddictServerHandler<HandleAuthorizationRequestContext>` and `IOpenIddictServerHandler<ProcessAuthenticationContext>` handlers that reject authorization requests and token requests for invalid users, but your scenario will really be best implemented using one of the simple approaches I mentioned earlier 😃

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if additional details are needed 😃
