### ISSUE TITLE
ADFS provider doesn't work with OpenIdDict client because of accessing the userinfo endpoint

### ISSUE THREAD

**Issue by eholyat** [openiddict/openiddict-core#1835]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

ADFS 2022

### Describe the bug

When connecting and using ADFS, I am able to get all the id and access tokens.  But, after acquiring the tokens, OpenIdDict client attempts to retrieve extra info from the userinfo endpoint. ADFS doesn't return any useful information from this endpoint and I couldn't find a way to ignore this and think that it should have an option to skip this extra step. e.g. like IdentityModel.OidcClient allows.  LoadProfile = false

I think the right thing to do with ADFS is avoid calling the userinfo endpoint all together, I would say that when using response_type=code where you get both id token and access token, it should be an option with any provider to go back and query the userinfo endpoint.

I was trying to follow the pipeline in the openiddict client to see if I could implement the LoadProfile = false, but I wasn't able to get the right spot.  

Do you think this is something useful?

### To reproduce

Tried adding the event callback to skip by setting HandleRequest or SkipRequest but it just hangs and never returns.  
Added Provider
                       .AddActiveDirectoryFederationServices(options =>
                       {
                           options.SetProviderName("ADFSTest")
                               .SetIssuer("https://xxx.com/adfs")
                               .SetClientId("c8cf672f-xxxxx-eee306376ce3")
                               .SetRedirectUri("http://localhost:7891/callback")
                               .AddScopes(Scopes.OpenId)
                               //.SetResource("urn:microsoft:userinfo");
                           .SetResource("c8cf672f-xxxxx-eee306376ce3");//Required for ADFS with AD Relying Party
                       });
....
                options.AddEventHandler<OpenIddictClientEvents.ApplyUserinfoRequestContext>(builder =>
                {
                    builder.UseInlineHandler(context =>
                    {
                        if (context != null)
                        {
                            AnsiConsole.MarkupLine("[green]ApplyUserinfoRequestContext[/]:{0}", context.Request);
                            //context.HandleRequest();//Don't send to ADFS endpoints
                            //context.SkipRequest();
                        }
                        else
                        {
                            AnsiConsole.MarkupLine("[red]No Token in Context [/]");
                        }
                        return default;
                    });
                    builder.SetOrder(OpenIddictClientHandlers.Protection.ValidateIdentityModelToken.Descriptor.Order - 500);
                });

### Exceptions (if any)

```shell
Error: invalid_token
 Message: An error occurred while authenticating the user.
 Description: The userinfo request was rejected by the remote server.

The ADFS error is UserInfoListener.ValidateAccessToken: The access token in the request doesn't have required audience 'urn:microsoft:userinfo'. Actual audience 'microsoft:identityserver:c8cf672f-xxxx-eee306376ce3'

This is because the access token doesn't audience will no longer match the resource sent as ADFS prefixes microsoft:identityserver: and as in your examples, it expects "urn:microsoft:userinfo" to be in the resource and aud.  so changing the resource to urn:microsoft:userinfo doesn't help.
"aud": "microsoft:identityserver:c8cf672f-xxxxx-eee306376ce3"

Each application will use a different clientid, so setting the client id to urn:microsoft.userinfo is not the right thing to do.  Setting the resource to urn:microsoft.userinfo and using a different client id will deny the request to the access token and id token because they don't match.
```

**Comment by kevinchalet** [comment]
Thanks for the report.

> ADFS doesn't return any useful information from this endpoint and I couldn't find a way to ignore this and think that it should have an option to skip this extra step. e.g. like IdentityModel.OidcClient allows. LoadProfile = false

It's something I considered when designing the OpenIddict client but decided against a "global" switch as it lacks granularity.

Instead, userinfo retrieval can be disabled dynamically via the events model, where you have access to all the request details. Here's how we disable userinfo retrieval for Azure AD/Microsoft Entra ID when we detect a Xbox scope was requested:

https://github.com/openiddict/openiddict-core/blob/9272bbc9a8162352f4cae0ca5597cca9f8a1d8fc/src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationHandlers.cs#L655-L706

I opened https://github.com/openiddict/openiddict-core/pull/1836 to update this event handler to always disable userinfo retrieval for ADFS.

Note: I considered checking the configured `resource` to only disable it when a custom value - different from `urn:microsoft:userinfo` - is set, but as you said, it doesn't return anything interesting anyway, so not worth it 😄
