### ISSUE TITLE
Storing additional data on OpenIddictEntityFrameworkCoreApplication

### ISSUE THREAD

**Issue by paolo8417** [openiddict/openiddict-core#1838]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi,

I need to storing and persist on database two additional data alongside the properties used by OpenIddict Application:

1. _ClientExternalId_ (that is a foreign key)
2. _Description_ (text field)

This is my code:

```
public class IdentityAuthorization : OpenIddictEntityFrameworkCoreAuthorization<string, IdentityApplication, IdentityToken> { }

public class IdentityApplication : OpenIddictEntityFrameworkCoreApplication<string, IdentityAuthorization, IdentityToken> 
{ 
        public string ClientExternalId { get; set; }        
        public ClientExternal ClientExternal { get; set; }

        public string Description { get; set; }
}

public class IdentityToken : OpenIddictEntityFrameworkCoreToken<string, IdentityApplication, IdentityAuthorization> { }

public class IdentityScope : OpenIddictEntityFrameworkCoreScope<string> { }
    
public class IdentityApplicationDescriptor : OpenIddictApplicationDescriptor
{
        public string ClientExternalId { get; set; }        
        public ClientExternal ClientExternal { get; set; }        

        public string Description { get; set; }
}

public class IdentityApplicationManager : OpenIddictApplicationManager<IdentityApplication>
{
        public IdentityApplicationManager(
            IOpenIddictApplicationCache<IdentityApplication> cache,
            ILogger<OpenIddictApplicationManager<IdentityApplication>> logger,
            IOptionsMonitor<OpenIddictCoreOptions> options,
            IOpenIddictApplicationStoreResolver resolver):base(cache,logger,options,resolver)
        {}

     public override async ValueTask PopulateAsync(IdentityApplication application, OpenIddictApplicationDescriptor descriptor, CancellationToken cancellationToken = default)
        {
            await base.PopulateAsync(application,descriptor,cancellationToken);
            var identityDescriptor = (descriptor as IdentityApplicationDescriptor);
            application.ClientExternalId = identityDescriptor.ClientExternalId;
            application.Description = identityDescriptor.Description;
        }
}
```
In the _AddCore_ options I add:

`  .ReplaceApplicationManager<IdentityApplicationManager>()`

Then, when I create or update an application:

```
private readonly IdentityApplicationManager _applicationManager;

....

 var descriptor = new IdentityApplicationDescriptor
    {
        Type = 
        DisplayName =
        ClientExternalId =
        Description = 
    };

....
await _applicationManager.CreateAsync(descriptor);
await _applicationManager.UpdateAsync(application,descriptor);
```

Is it the right way? 

Do I need to extend the _OpenIddictEntityFrameworkCoreApplicationStore_ also?

Do I need to extend the OpenIddictApplicationManager _UpdateAsync_ method also?

Do I have to use some rule in the name of the _IdentityApplication_ properties, to avoid that in the future there may be conflicts (like property _Description_)?

Thanks

**Comment by kevinchalet** [comment]
Hey,

> Is it the right way?

Yes.

> Do I need to extend the _OpenIddictEntityFrameworkCoreApplicationStore_ also?

Technically, it's not 100% required, but if you plan on developing a public package, I'd encourage you to also provide your custom stores and use `Store.Get*Async()`/`Store.Set*Async()` accessors, so that users who want to subclass your stores can do so more easily.

> Do I need to extend the OpenIddictApplicationManager _UpdateAsync_ method also?

No.

> Do I have to use some rule in the name of the _IdentityApplication_ properties, to avoid that in the future there may be conflicts (like property _Description_)?

A common approach is to prefix it with the name of your project or company 😃 

Regards.

**Comment by paolo8417** [comment]
Hi,

> > Do I need to extend the _OpenIddictEntityFrameworkCoreApplicationStore_ also?
> 
> Technically, it's not 100% required, but if you plan on developing a public package, I'd encourage you to also provide your custom stores and use `Store.Get*Async()`/`Store.Set*Async()` accessors, so that users who want to subclass your stores can do so more easily.
> 

So If I don't plan to develop a public package, can I use my code above safely?

**Comment by kevinchalet** [comment]
Hi,

> So If I don't plan to develop a public package, can I use my code above safely?

Yep!

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if additional details are needed 😃
