### ISSUE TITLE
"Token has already been redeemed" error on Velusia Example

### ISSUE THREAD

**Issue by craaash80** [openiddict/openiddict-core#1848]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

Good morning,
 

I'm trying to use your Velusia example.

The development environment is Vs 2022 and I'm compiling with net 6.0.

The only changes I've made are related to the certificates, and are in the code section

The steps I took are the following:

1) new user registration

2) Login of the new user 

In step n.1, after registration, you are not automatically redirected to the user home page.

At step no. 2 the browser stops at this address: 

https://localhost:44338/callback/login/local?code=xHjpgoZiQ9XmMgdwONcO9DF0UGeDxm1KqbYjOLARQwA&state=u5Vmf2P5zVzfVLbsqGpYr6TIyCyMYSTj-70nUs9JSEg&iss=https%3A%2F%2Flocalhost%3A44313%2F 

The page is blank. Viewing the source of the page, the text contained is as follows:

**error:invalid_token

error_description:The specified state token has already been redeemed.

error_uri:https://documentation.openiddict.com/errors/ID2139**

By refreshing the page itself, the error text also appears in the browser. 

In fact, however, the user is logged in, because by trying to access the user's home page after attempting authentication, the page is displayed and the user is therefore authenticated.

### To reproduce

The only changes I've made are related to the certificates, and are as follows:

**For the server part:**

 

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host
                .CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(
                                        webHostBuilder =>
                                        {
                                            X509Certificate2 oX509Certificate2;
                                            oX509Certificate2 =
                                                        new X509Certificate2(
                                                                        @"certificate.pfx",
                                                                        "Password");

                                            webHostBuilder
                                                    .UseUrls()
                                                    .UseKestrel(
                                                        options =>
                                                        {
                                                            options.Listen(
                                                                        IPAddress.Any,
                                                                        44313,
                                                                        listenOptions =>
                                                                        {
                                                                            listenOptions.UseHttps(oX509Certificate2);
                                                                        });
                                                        }); 

                                            webHostBuilder.UseStartup<Startup>();
                                        });
    }

 

**For the client side:** 

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return
            Host
                .CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(
                                        webHostBuilder =>
                                        {
                                            X509Certificate2 oX509Certificate2;
                                            oX509Certificate2 =
                                                        new X509Certificate2(
                                                                        @"certificate.pfx",
                                                                        "Password");

                                            webHostBuilder
                                                    .UseUrls()
                                                    .UseKestrel(
                                                        options =>
                                                        {
                                                            options.Listen(
                                                                        IPAddress.Any,
                                                                        44338,
                                                                        listenOptions =>
                                                                        {
                                                                            listenOptions.UseHttps(oX509Certificate2);
                                                                        });
                                                        }); 

                                            webHostBuilder.UseStartup<Startup>();

                                        });

    }

### Exceptions (if any)

```shell
error:invalid_token

error_description:The specified state token has already been redeemed.

error_uri:https://documentation.openiddict.com/errors/ID2139
```

**Comment by kevinchalet** [comment]
Hey @craaash80,

Thanks for sponsoring the project, much appreciated! ❤️ 

> At step no. 2 the browser stops at this address:

> https://localhost:44338/callback/login/local?code=xHjpgoZiQ9XmMgdwONcO9DF0UGeDxm1KqbYjOLARQwA&state=u5Vmf2P5zVzfVLbsqGpYr6TIyCyMYSTj-70nUs9JSEg&iss=https%3A%2F%2Flocalhost%3A44313%2F

That's because the cookies authentication handler in ASP.NET Core 6 (and older) doesn't honor the `AuthenticationProperties.RedirectUri` when calling `SignIn` from an endpoint whose address doesn't exactly match the value set in `CookieAuthenticationOptions.LoginPath`, which is the case here, since the cookie is created on OpenIddict's callback.

I fixed this problematic issue in ASP.NET Core 7 with this PR: https://github.com/dotnet/aspnetcore/pull/42039.

If you don't want to/can't migrate to ASP.NET Core 7.0, you'll need to make a tiny change to `AuthenticationController`.

Instead of:

```csharp
// Ask the cookie authentication handler to return a new cookie and redirect
// the user agent to the return URL stored in the authentication properties.
return SignIn(new ClaimsPrincipal(identity), properties, CookieAuthenticationDefaults.AuthenticationScheme);
```

You'll need to use:

```csharp
// Note: "return SignIn(...)" cannot be directly used in this case, as the cookies handler doesn't allow
// redirecting from an endpoint that doesn't match the path set in CookieAuthenticationOptions.LoginPath.
// For more information about this restriction, visit https://github.com/dotnet/aspnetcore/issues/36934.
await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), properties);

return Redirect(properties.RedirectUri ?? "/");
```

> The page is blank. Viewing the source of the page, the text contained is as follows:

This is actually the expected behavior: since you're not redirected away due to the limitation I mentioned, viewing the source actually reloads the page, which sends a new callback request. Since the same `state` is reused, OpenIddict detects the state token is replayed - which is considered a security violation - and returns an error indicating it was already redeemed.

Hope it helps 😃

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if you need additional details 😃 

Thanks again for sponsoring the project.
