### ISSUE TITLE
Renew token without Id_token

### ISSUE THREAD

**Issue by apavelm** [openiddict/openiddict-core#1863]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

RefreshToken

### Describe the bug

@kevinchalet Maybe it is just a question, because I cannot find a strong requirement in OAuth specification about the following. If so, could you please point me to the part of document.

Subj:
I noticed that in OpenIdDict it is possible to renew an access token by passing only refresh_token (without providing id_token in the request body). I'm comparing the behavior against IdentityServer where id_token is required, a client (openid-client-ts, also by-default sends id_token). 

Please advise how to enable id_token as requirement or why it is possible to refresh token without id_token
Thanks

Flow: AuthorizationCode + PKCE

### To reproduce

call /connect/token
grant_type: refresh_token
without id_token passed

### Exceptions (if any)

```shell
no exceptions
```

**Comment by kevinchalet** [comment]
Hi,

The issue template you selected is exclusively for reporting issues affecting an OAuth 2.0/OIDC social/enterprise provider supported by the `OpenIddict.Client.WebIntegration` package (but your question has nothing to do with that).

For general support, please consider sponsoring the project. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
