### ISSUE TITLE
The token request was rejected because the public client application 'WayStudy_App' was not allowed to use the client credentials grant.

### ISSUE THREAD

**Issue by jhgg75** [openiddict/openiddict-core#1866]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

![image](https://github.com/openiddict/openiddict-core/assets/60102656/afd947e2-8efd-4c16-8e01-be8332129497)
![image](https://github.com/openiddict/openiddict-core/assets/60102656/0e6b70e8-6026-4431-9f56-7b0af436ddf1)
Is it a problem for me to use it? Can't this default configured application obtain access tokens through customer credentials

### To reproduce

       var consoleAndAngularClientId = configurationSection["WayStudy_App:ClientId"];
        if (!consoleAndAngularClientId.IsNullOrWhiteSpace())
        {
            var consoleAndAngularClientRootUrl = configurationSection["WayStudy_App:RootUrl"]?.TrimEnd('/');
            await CreateApplicationAsync(
                name: consoleAndAngularClientId!,
                type: OpenIddictConstants.ClientTypes.Public,
                consentType: OpenIddictConstants.ConsentTypes.Implicit,
                displayName: "Console Test / Angular Application",
                secret: null,
                grantTypes: new List<string> {
                    OpenIddictConstants.GrantTypes.AuthorizationCode,
                    OpenIddictConstants.GrantTypes.Password,
                    OpenIddictConstants.GrantTypes.ClientCredentials,
                    OpenIddictConstants.GrantTypes.RefreshToken
                },
                scopes: commonScopes,
                redirectUri: consoleAndAngularClientRootUrl,
                clientUri: consoleAndAngularClientRootUrl,
                postLogoutRedirectUri: consoleAndAngularClientRootUrl
            );

**Comment by hisuwh** [comment]
@jhgg75 did you resolve this?
