### ISSUE TITLE
The exception thrown is inconsistent with the exception displayed on the server

### ISSUE THREAD

**Issue by 1764564459** [openiddict/openiddict-core#1867]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

AuthenticateWithRefreshToken

### Describe the bug

1、The exception thrown is inconsistent with the exception displayed on the server。
![image](https://github.com/openiddict/openiddict-core/assets/39048083/11e4dd54-5292-4f89-ba2e-536f23460f4d)
2、How to support internationalized error message prompts? The production environment requires the use of local languages.

**Comment by kevinchalet** [comment]
1. It's a deliberate design choice: I didn't want to flow the error details from the server - that may or may not be an OpenIddict server - as-is (they are often badly formatted or misleading).
2. You can't: `error`, `error_description` and `error_uri` can only contain select US-ASCII characters if you want your implementation to be standard. Catch the exception and return a generic localized error message to the user if necessary.

**Comment by 1764564459** [comment]
Hello, is there any way to customize and handle error prompts ?

**Comment by kevinchalet** [comment]
> Hello, is there any way to customize and handle error prompts ?

```csharp
try
{
    var result = await _service.AuthenticateWithRefreshTokenAsync(new()
    {
        ProviderName = provider,
        RefreshToken = "token"
    });

    // ...
}

catch (OpenIddictExceptions.ProtocolException exception) when (exception.Error is Errors.InvalidGrant)
{
    // Display a custom message telling the user he has to re-authenticate (e.g in the console output)
}
```

**Comment by 1764564459** [comment]
Okay, thank you. I will try to find other solutions.
