### ISSUE TITLE
你好 请问OpenIddict 支持自定义授权码吗 我想通过框架本身的方法去生成授权码 看了很久的源码没找到

### ISSUE THREAD

**Issue by jhgg75** [openiddict/openiddict-core#1868]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Do I provide a corresponding method for generating authorization codes directly and returning them to the front-end without page jumping

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
