### ISSUE TITLE
How to implement a custom OpenIddictClientEvents.HandleTokenResponseContext to handle related server-side prompt information.

### ISSUE THREAD

**Issue by 1764564459** [openiddict/openiddict-core#1870]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

HandleTokenResponseContext

### Describe the bug

1.I can obtain the HandleTokenResponseContext from the source code and also receive server-side prompt information. Can I implement a custom HandleTokenResponseContext to handle server-side related prompt information?
![image](https://github.com/openiddict/openiddict-core/assets/39048083/52e34f75-fc91-4179-a323-a6bf5a765bb0)
2.Can I add localized language files and use error messages related to my localized language?
    .I have also tried the following methods to handle localization, but they have not been effective.
![image](https://github.com/openiddict/openiddict-core/assets/39048083/209dbc59-bf03-41a4-99e7-ffef5d67d22d)

**Comment by kevinchalet** [comment]
Hi,

The issue template you selected is exclusively for reporting issues affecting an OAuth 2.0/OIDC social/enterprise provider integration that is part of the `OpenIddict.Client.WebIntegration` package. Unfortunately, your question is unrelated.

For general support, please consider sponsoring the project. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!

**Comment by 1764564459** [comment]
Okay, thank you. I will study the source code.
