### ISSUE TITLE
Implement automatic expired token delete in db

### ISSUE THREAD

**Issue by PJH-Eric** [openiddict/openiddict-core#1871]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Any way to Delete Token Data in db when expired?

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
