### ISSUE TITLE
I want to make OpeniddictDbContext without inject it for other reasons

### ISSUE THREAD

**Issue by wisamidris7** [openiddict/openiddict-core#1876]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

# I want to make OpeniddictDbContext it new instance but without inject it

Cause There Some Other Issues And Things That Require To Not Inject
I Want To Make Like This Cause This Is Important
```c#
builder.Services.AddOpenIddict()

    // Register the OpenIddict core components.
    .AddCore(options =>
    {
        // Configure OpenIddict to use the Entity Framework Core stores and models.
        // Note: call ReplaceDefaultEntities() to replace the default OpenIddict entities.
        options.UseEntityFrameworkCore()
           .UseDbContext(() => new OpeniddictDbContext()); // Required Design

        // Enable Quartz.NET integration.
        options.UseQuartz();
    })
    ....
```

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
