### ISSUE TITLE
What's the OpenIddict stance for passkeys (WebauthN/FIDO2) support? 

### ISSUE THREAD

**Issue by Bartmax** [openiddict/openiddict-core#1885]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Maybe this is a naive question, but I was just wondering if there's anything that openiddict needs to do (or already did) to support passkeys (and if potentially can I help with some of it).

I understand that Webauthn is mostly client-side but there is still the need to store publickeys and process/validate credentials.

**Comment by kevinchalet** [comment]
> Maybe this is a naive question, but I was just wondering if there's anything that openiddict needs to do (or already did) to support passkeys (and if potentially can I help with some of it).

OpenIddict never handles user authentication, so OpenIddict doesn't need "to do" anything to implement WebAuthn/FIDO2/passkeys.

> I understand that Webauthn is mostly client-side but there is still the need to store publickeys and process/validate credentials.

ASP.NET Core Identity supports TOTP for MFA, but not WebAuthn/FIDO2 for either the secondary or primary (= passwordless) factors. And there's AFAIK, no plan to change that (I suggested that Identity should at least support storing the credentials in its DB, but it was rejected).

To support WebAuthn, your best option is https://github.com/passwordless-lib/fido2-net-lib.

**Comment by kevinchalet** [comment]
@Bartmax did that answer your question? 😄

**Comment by Bartmax** [comment]
Thanks @kevinchalet,
Crystal clear.

**Comment by kevinchalet** [comment]
Maybe that would be nice to have a sample for WebAuthn in the samples repo? Would you be interested in working on that? 😃

**Comment by damienbod** [comment]
Here's an example with it integrated into Identity:

https://github.com/damienbod/AspNetCoreOpeniddict/tree/main/OpeniddictServer

**Comment by kevinchalet** [comment]
Wooops, I had completely forgotten this sample uses fido2-net-lib. Very nice @damienbod! ❤️
