### ISSUE TITLE
Can I pass connect/token parameters via query strings?

### ISSUE THREAD

**Issue by SebastianStehle** [openiddict/openiddict-core#1905]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi,

I have recently deployed a new version of my service and today one of my customers asked me why he cannot get a token with a post request where the parameters like grant_type and client_id are passed in as a query string.

I was not even aware that this is possible, and I told him that it is not the best idea. But nevertheless I would like to know, if ...

1. it is possible.
2. was it possible and has been removed (probably between 4.1. and 4.5)
3. If the error is on my side, where would you check that?

**Comment by kevinchalet** [comment]
Hey @SebastianStehle,

Specifying token request parameters in the query string has never been supported (or even possible), in any OpenIddict version... at least, not without writing a custom event handler to support that. The specification explicitly requires using formURL-encoding to flow the token request parameters and all versions of OpenIddict enforce that 😃 

Could it be possible that your customer uses some sort of proxy that transfers the query string parameters to the request form?

**Comment by SebastianStehle** [comment]
> Could it be possible that your customer uses some sort of proxy that transfers the query string parameters to the request form? 

Probably, but my assumption is that the report does not match to his code. Something is weird here. I also checked your code and could not find any hints that query strings would be accepted.

**Comment by kevinchalet** [comment]
> I also checked your code and could not find any hints that query strings would be accepted.

Yeah, the query string is not used at all for the `ExtractTokenRequest` event:

https://github.com/openiddict/openiddict-core/blob/caebcc3680e899370b9994d1f7f591b69232e1a6/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.Exchange.cs#L16-L21

https://github.com/openiddict/openiddict-core/blob/caebcc3680e899370b9994d1f7f591b69232e1a6/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandlers.cs#L570-L643

ASOS (that was used in OpenIddict 1.x and 2.x) had a very similar logic (that also ignored the query string):

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/15e4cb6264a2222d08c83231fea84dc9dc7458ed/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Exchange.cs#L28-L73

> Something is weird here.

Definitely 😄

**Comment by kevinchalet** [comment]
Did you hear back from your customer, @SebastianStehle? 😃

**Comment by kevinchalet** [comment]
Closing, but feel free to reopen if you need additional information 😃
