### ISSUE TITLE
Token revokation

### ISSUE THREAD

**Issue by maxprilutskiy** [openiddict/openiddict-core#191]
How can I revoke the bearer and refresh token?

**Comment by kevinchalet** [comment]
For performance reasons, access tokens are not stored in the database and thus, are not revocable.

Refresh token can be revoked using the built-in API or the revocation endpoint. See https://github.com/openiddict/openiddict-core/issues/136#issuecomment-225068490 for more information.

**Comment by maxprilutskiy** [comment]
@PinpointTownes so I don't need to revoke the access token on log out, right?

One more question: what are my actions in situation when refresh token expires? Or refresh tokens are being reissued after refreshing the access token?

**Comment by kevinchalet** [comment]
> Or refresh tokens are being reissued after refreshing the access token?

They are. The refresh token used to make a refresh token request is automatically revoked and a new one is issued (unless you disabled sliding expiration in the OpenIddict options: in this case, the refresh token is not revoked and no refresh token is returned).
