### ISSUE TITLE
Audience Validation Issue

### ISSUE THREAD

**Issue by lommez** [openiddict/openiddict-core#1919]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

HI
When obtaining the token through Swagger, the audience value is configured in another property other than "aud", it is configured in "oi_au_id".
When trying to request a protected endpoint I receive the following message: "The audience 'empty' is invalid".

The audience value shouldnt be stored in the "aud" property?

![image](https://github.com/openiddict/openiddict-core/assets/10900667/0119aa01-2e55-47d7-9c47-15f05fc41964)

![image](https://github.com/openiddict/openiddict-core/assets/10900667/183d1895-2221-473e-8eb3-b40a6497bf1d)

But when using Postman to get authenticate using the password flow, the audience is store in the "aud" property and everything works fine.

Am i missing something or is this bug?

### To reproduce

Authenticating using Swagger to get the token, and try to call an endpoint protected

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

That said, I see you're an ABP user and opened a ticket on their repo (https://github.com/abpframework/abp/issues/18331). If you don't hear back from the ABP devs, I'll try to chime in when I have a moment later this week.
