### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by bumblebee333** [openiddict/openiddict-core#192]
Hi there,
        We are using openIddict in our angular web application(asp.net mvc core). It is using the JWT auth flow at the moment. We are using a http interceptor to add the token to the headers for the API calls. We do have a requirement to load one of the views in a new window (something like $window.open). It is calling an MVC controller in that new window. I want to pass the JWT token to that controller and authorize that request. Is there a way to do this? 

Thanks in advance for your help.
Rakesh

**Comment by kevinchalet** [comment]
Cookies is generally better for interactive MVC views (i.e non-API controllers), but I guess you could flow the access token as a query string parameter. You can use the validation middleware events to override the default token resolution logic: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/SignalR/HelloSignalR/Startup.cs#L22-L33

Similar hooks exist for the JWT bearer middleware.

**Comment by bumblebee333** [comment]
Thank you for the timely help. Sorry for my delayed response. I used your suggestion to implement it. I did however wrote an intermediate controller to POST the token instead of using it via GET as querystring.

`public override Task MessageReceived(MessageReceivedContext context)
        {
            //check if the headers doesnt have an authorization  token
            var headers = context.Request.Headers;
            var authHeader = headers["Authorization"];
            if (string.IsNullOrEmpty(authHeader))
            {
                AddTokenFromQueryStringToHeader(context, headers);
            }
            return base.MessageReceived(context);
        }`


`private static void AddTokenFromQueryStringToHeader(MessageReceivedContext context, Microsoft.AspNetCore.Http.IHeaderDictionary headers)
        {
            var token = context.Request.Query["access_token"];
            if (string.IsNullOrEmpty(token) && context.Request.ContentType != null && context.Request.Form != null)
                token = context.Request.Form["authtoken"];
            headers.Add("Authorization", token);           
        }`
