### ISSUE TITLE
BadRequest when calling Userinfo endpoint with POST request

### ISSUE THREAD

**Issue by maeni70** [openiddict/openiddict-core#1922]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

For testing I have used Velusia.Server and registered an own client. All works fine when calling the Userinfo endpoint with a GET request. However, I cannot make it work with POST.

I am using following code:

```
var restClient = new RestClient(baseUrl);

var httpMethod = Method.Post;
if (!String.IsNullOrEmpty(oidcProvider.UserInfoEndpointMethod) && oidcProvider.UserInfoEndpointMethod.ToLower() == "get")
{
	httpMethod = Method.Get;
}

var request = new RestRequest(userInfoEndpoint, httpMethod);
request.AddHeader("accept", "application/json");
request.AddHeader("Authorization", $"Bearer {accessToken}");
if (httpMethod == Method.Post)
{
	// Sometimes needed for POST requests (even if the body is empty)
	// Some APIs expect this header and may return a 400 Bad Request if it's missing.
	request.AddHeader("Content-Type", "application/json");
}

var response = await restClient.ExecuteAsync<Dictionary<string, string>>(request); // returns HttpStatusCode.BadRequest
```

There are no issues with other IdPs using OIDC (e.g. Azure AD or Auth0).

According to the specifications POST requests should be supported for this endpoint, and I can also see in your code base and samples. Unfortunately, I could not find how it works in your own `OpenIddict.Client.AspNetCore` implementation (which HTTP method is the default?).

I would like to know, if posting to the Userinfo endpoint is officially supported, and if so, what might be the reason why it does not work for me when accessing "your" endpoint.

Thanks in advance and best regards,
Roger

**Comment by kevinchalet** [comment]
Hi @maeni70,

> Unfortunately, I could not find how it works in your own `OpenIddict.Client.AspNetCore` implementation (which HTTP method is the default?).

The OpenIddict client stack uses GET, which is the method recommended by the specification:

>  It is RECOMMENDED that the request use the HTTP GET method and the Access Token be sent using the Authorization header field.

(honestly, I don't know why they decided to support POST for this endpoint... it doesn't make much sense to me)

> I would like to know, if posting to the Userinfo endpoint is officially supported, and if so, what might be the reason why it does not work for me when accessing "your" endpoint.

The OpenIddict server stack supports POST requests, but only requests that use `Content-Type: application/x-www-form-urlencoded`. POST requests that don't specify a `Content-Type` or specify a different value (e.g JSON) are currently not supported.

I'm not completely against supporting POST userinfo requests that don't have a `Content-Type` header set, but complete validation is not easy to implement. For instance, you'll want to reject non-empty requests that don't have a `Content-Type` (which is an invalid scenario). And for that, you first need to determine whether some content is attached: recent versions of ASP.NET Core offer `IHttpRequestBodyDetectionFeature` but I'm not aware of anything similar for OWIN.

Hope it'll help.

**Comment by maeni70** [comment]
Thanks for these insights.

I just took it for granted as other providers are supporting corresponding POST requests (as I did). But you are definitely correct with your assumptions!

The new default for my client library will be GET requests, and maybe additional options for the POST.

To be in line with other "major" providers, could it be an idea to allow relaxing the validations for POST requests in OpenIdDict server by a config?

However, I am really happy to know that this issue is mainly concerning my "client" and not the server - I am currently implementing a custom solution using your server library, and my tests failed when calling the Userinfo endpoint.

Thanks for your great work!

**Comment by kevinchalet** [comment]
Wooops, for some reasons my reply wasn't posted when I submitted it, sorry 😓 

___________________

> To be in line with other "major" providers, could it be an idea to allow relaxing the validations for POST requests in OpenIdDict server by a config?

As I mentioned, the problem is when you have a client that doesn't send a `Content-Type` but attaches a body to its request: it's allowed by the HTTP specification, but it's a scenario that doesn't make sense for OIDC and that I wouldn't want to support. So we'd have two choices:
  1. Just ignore the fact a body was attached. It's easy to do but not ideal.
  2. Detect that somehow and reject the request. It's better but harder to do.

I'll keep that in mind and see if there's additional demand for that before choosing 1) or 2).

> Thanks for your great work!

Thanks for your kind words!
