### ISSUE TITLE
OpenIddict + EF6

### ISSUE THREAD

**Issue by ivanmariychuk** [openiddict/openiddict-core#193]
Hello can you give more detailed information how to use Openiddict with EF6?

**Comment by MehdiSaeedifar** [comment]
+1

**Comment by kevinchalet** [comment]
There's no plan to create an "official" OpenIddict package for EF6, but you're free to create your own stores, similarly to what we have for EF Core.

**Comment by MehdiSaeedifar** [comment]
But i think it's more than stores, for example OpenIddictExtensions class is coded specifically for ef core.

**Comment by kevinchalet** [comment]
The extensions you can find in the `OpenIddict` package are only there for convenience. You don't have to use them. `OpenIddict.Core` has all the extensions you need to configure OpenIddict with your own stores.

**Comment by ivanmariychuk** [comment]
Thx for your response!

**Comment by joshgarwood** [comment]
@ivanmariychuk Did you have any luck with this?  I'm in the process of doing the same thing and would be interested in chatting if you were able to get this working with EF6.
