### ISSUE TITLE
I have encountered error: invalid_request The 'iss' parameter cannot be used when 'authorization_response_iss_parameter_supported' is not supported by the authorization server. when adding new web provider based on IdentityServer

### ISSUE THREAD

**Issue by sameerdube9** [openiddict/openiddict-core#1932]
### Personal contribution

- [ ] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

4.x

### Provider name

DuendeIdentityServer

### Describe the bug

![image](https://github.com/openiddict/openiddict-core/assets/4013722/e99a9172-3e87-4436-a05d-fa404e98b147)

when adding new web provider based on IdentityServer

### To reproduce

I have hosted IdentityServer (https://duendesoftware.com/products/identityserver)
trying to add provider for the same it encountered above error
I am just starting out, kindly guide me

**Comment by kevinchalet** [comment]
Hi,

This error is returned when the authorization server specified an `iss` parameter in the authorization response, but doesn't include `"authorization_response_iss_parameter_supported": true` in its configuration document, which is typically a compliance issue.

What version of Duende IdentityServer are you using?

**Comment by sameerdube9** [comment]
v6.0

**Comment by sameerdube9** [comment]
it does have https://[rioid.azurewebsites.net/.well-known/openid-configuration](https://rioid.azurewebsites.net/.well-known/openid-configuration)

https://[rio-content-management-web.azurewebsites.net/.well-known/openid-configuration](https://rio-content-management-web.azurewebsites.net/.well-known/openid-configuration)

**"authorization_response_iss_parameter_supported": true**
but no avail

**Comment by kevinchalet** [comment]
How did you create the provider? By adding it to the .xml file? Care to share it here?

**Comment by sameerdube9** [comment]
[New-Providers.txt](https://github.com/openiddict/openiddict-core/files/13711310/New-Providers.txt)
I have attached txt file as XML is not working good with markdown editor

redirect uri: https://localhost:44381/callback/login/rioid

**Comment by kevinchalet** [comment]
The error occurs because you set a static `<Configuration />` instead of using OIDC discovery. Remove that and it should work.

**Comment by sameerdube9** [comment]
I have removed <Configuration/> block but now got following error:

Ooooops, something went really bad! :(
invalid_client The token request was rejected by the remote server. @kevinchalet

**Comment by kevinchalet** [comment]
Take a look at the logs or intercept the token response using Fiddler to see what's causing the rejection.

**Comment by sameerdube9** [comment]
thank you, will check

**Comment by sameerdube9** [comment]
https://documentation.openiddict.com/errors/ID2147
getting this url for error but does not show anything on the site for the url

**Comment by kevinchalet** [comment]
It's expected: it currently mostly serves as an identifier. Real documentation will come in the future, hopefully: https://github.com/openiddict/openiddict-documentation/issues/30.
