### ISSUE TITLE
Azure B2C web provider integration

### ISSUE THREAD

**Issue by devv-guru** [openiddict/openiddict-core#1934]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.0.0

### Question

Hi Kevin

Is there a way to have a custom OIDC Web provider.
I have an app that uses Google, MS(Personal, school and AD), and Azure B2C.

Setting up the first two was easy, but how can I add support for my B2C users, we are using B2C for "local accounts" but have been having way to many issues so are kind of trying to get an openiddict server running to federate it all.

Thanks in advance.

**Comment by kevinchalet** [comment]
Hi Deon,

> Setting up the first two was easy, but how can I add support for my B2C users, we are using B2C for "local accounts" but have been having way to many issues so are kind of trying to get an openiddict server running to federate it all.

As you likely figured out, there's currently no OpenIddict web integration for Azure B2C. I don't currently have the need for such a provider myself, but if your company was interested in sponsoring the project (sponsorships for companies start at $25/month or $300/year), I could certainly consider adding one.

Happy holidays 🎄

**Comment by devv-guru** [comment]
Would you mind if I grab the code and write one myself and send it over to you to.

**Comment by kevinchalet** [comment]
Sure, feel free to send a PR once you have a working integration. That said, Azure B2C is notoriously known for being quite non-standard (e.g it has "user flows" that impact how the endpoints are resolved, which isn't something standard): it's likely it won't be a trivial task 😄

**Comment by devv-guru** [comment]
Welp, wish me luck in that case.
Thanks

**Comment by kevinchalet** [comment]
Good luck! 😎

**Comment by kevinchalet** [comment]
Did you have a chance to give it a try, @Deon-v? 😃

**Comment by devv-guru** [comment]
@kevinchalet 

Sorry never got around to this, burned out at work and had a baby, I will have a look at this again in the next few weeks.
