### ISSUE TITLE
The specified token is no longer valid

### ISSUE THREAD

**Issue by stasnocap** [openiddict/openiddict-core#1948]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.7.0

### Question

Hi Kevin! First, thank you for this amazing project. I have authorization code flow, with an ASP.NET Core application acting as the client. When i have redirected to authentication server after about 40 minute or 1 hour, i am attempting to login in and get following error:

error:invalid_token
error_description:The specified token is no longer valid.
error_uri:[https://documentation.openiddict.com/e...ors/ID2019](https://documentation.openiddict.com/errors/ID2019)

I found that this is caused by the ValidateExpirationDate handler on my MVC client and removed it
options.RemoveEventHandler(OpenIddictClientHandlers.Protection.ValidateExpirationDate.Descriptor);

Then i fall into the issue about the expiring login correlation cookie and I configured it to live longer
options.UseAspNetCore().Configure(x => x.CookieBuilder.Expiration = TimeSpan.FromDays(1))

So far, i am not sure am i on the right path or there is a better way to make token live longer. Help me please! Thank you!

**Comment by kevinchalet** [comment]
Hey @stasnocap,

> Hi Kevin! First, thank you for this amazing project.

Thanks for your kind words!

> So far, i am not sure am i on the right path or there is a better way to make token live longer. Help me please! Thank you!

The lifetime of the state token - 15 minutes by default - can be changed by calling `options.SetStateTokenLifetime(...)`. By default, OpenIddict uses the same value for the correlation cookie, so you don't need to explicitly call `Configure(options => options.CookieBuilder.Expiration = TimeSpan.FromDays(1))`.

> I found that this is caused by the ValidateExpirationDate handler on my MVC client and removed it
options.RemoveEventHandler(OpenIddictClientHandlers.Protection.ValidateExpirationDate.Descriptor);

I wouldn't recommend removing this event handler. If you want to amend the state token lifetime, just use `options.SetStateTokenLifetime(...)` (you can specify `null` to get state tokens that never expire, but I wouldn't recommend it either).

Keep in mind that if you use a long lifetime for your state tokens/correlation cookies, it increases the chances of hitting a cookie size limit at some point if a user starts multiple authentication flows without completing them (in this case, correlation cookies keep being returned/stored and are not automatically removed by the browser until their expiration date is reached).

Hope it'll help.

**Comment by stasnocap** [comment]
You are a life saver! Thank you for fast detailed answer!

**Comment by kevinchalet** [comment]
Glad I could help 😃

**Comment by stasnocap** [comment]
I have one more question. If I set lifetime of the state token about 10 days. If user have been redirected to authentication server, and he do not login in and closed browser and he has keep tabs feature turn on. Can he login in a few days when he opens up this tab already filled with openid flow parameters? Or how should I handle it? I guess I have encountered it and openiddict showed me

error:invalid_token
error_description:The specified token is no longer valid.
error_uri:[https://documentation.openiddict.com/errors/ID2004](https://documentation.openiddict.com/errors/ID2004)

What if i update my authentication server or my mvc client in this period? Will something break?

**Comment by kevinchalet** [comment]
Technically yes, he can. But 10 days is a crazy value and the sign you're not handling the problem correctly. The state token is expected to be short-lived, giving the user just the time to log in or create an account and get back to the client. That's why the default value is 15 minutes: it's a reasonable value (FWIW, the ASP.NET Core handlers use the same value for correlation cookies).

Consider approaching the problem differently: enable the status code pages integration as in the samples and if you detect an error returned by the OpenIddict client during the callback, ask the user to start a new authorization flow (with a new state token).

**Comment by stasnocap** [comment]
Thank you again. I should check all samples asap.
