### ISSUE TITLE
The security token is missing.   https://documentation.openiddict.com/errors/ID2000 web browser

### ISSUE THREAD

**Issue by emman122** [openiddict/openiddict-core#1960]
### Personal contribution

- [X] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

2.1

### Provider name

autentication

### Describe the bug

the application in net core has as integration this Library, 1 year ago it worked correctly, but again it was launched and does not allow to continue advancing in the testing section of a web app is necessary any change in StartUP.CS?

The response was successfully returned as a challenge response: {
        "error": "missing_token",
        "error_description": "The security token is missing.",
        "error_uri": "https://documentation.openiddict.com/errors/ID2000"
      }.

code STARTUP.CS
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
      
         
            // Display error codes
            app.UseStatusCodePages(context =>
            {
                context.HttpContext.Response.ContentType = "application/json";

                ResError error = new ResError();
                error.Code = context.HttpContext.Response.StatusCode.ToString();

                switch (context.HttpContext.Response.StatusCode)
                {
                    case 401:
                       
                        error.Message = "No tienes permisos x " + error.ToString();
                        break;
                    case 403:
                        context.HttpContext.Response.StatusCode = 401;
                        error.Code = "401";
                        error.Message = "No tienes permisos y "+error.ToString();
                        break;
                }

                return context.HttpContext.Response.WriteAsync(error.ToJson());
            });

            app.UseHttpsRedirection();

            app.UseCors();
          
       
            app.UseRouting();
          app.UseGrpcWeb();
            //se incluye cambios en coors ege
            //TODO: Uncomment this if you need wwwroot folder
            app.UseStaticFiles();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

### To reproduce

error: "invalid_request", error_description: "Multiple client credentials cannot be specified."}
error
: 
"invalid_request"
error_description
: 
"Multiple client credentials cannot be specified."

### Exceptions (if any)

```shell
The token request is successful, but it doesn't take the token on requests after the prefix
```

**Comment by kevinchalet** [comment]
This issue template is reserved to issues affecting web provider integrations. For general support, you need to sponsor the project.
