### ISSUE TITLE
Microsoft Provider: SSO does not work with edge browser

### ISSUE THREAD

**Issue by AGIS-Development** [openiddict/openiddict-core#1961]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.0.1

### Describe the bug

Hi Kevin

Microsoft single sign on does not work with edge browser (version: 120.02210.144) when a working account is connected with the windows. With the google chrome and firefox browser it works successfully.

The microsoft signin-endpoint "signin-microsoft" could not be found after login.
![image](https://github.com/openiddict/openiddict-core/assets/157363207/ff5d99c5-0d36-4fef-9390-8e3acc685b12)

FYI: When i disconnect the working account in windows or the account in the edge profile, login works.

Thanks in advance.

Kind regards
Raphael

### To reproduce

Implementation:

...
// Add microsoft authentication provider.
builder.Services.AddAuthentication().AddMicrosoftAccount("Microsoft", options =>
{
	options.ClientId = appSettings.SingleSignOnProviders.MicrosoftProvider.ClientId;
	options.ClientSecret = appSettings.SingleSignOnProviders.MicrosoftProvider.ClientSecret;
	var scopes = appSettings.SingleSignOnProviders.MicrosoftProvider.Scopes;
	if (scopes != null)
	{
		foreach (string scope in appSettings.SingleSignOnProviders.MicrosoftProvider.Scopes)
		{
			options.Scope.Add(scope);
		}
	}
});
...

### Exceptions (if any)

```shell
https://.../signin-microsoft?code=abc
Status Code 404
Message: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

**Comment by kevinchalet** [comment]
Hi,

Your question is unrelated to this project: `builder.Services.AddAuthentication().AddMicrosoftAccount()` is an extension owned by Microsoft, which has nothing to do with the web providers developed here. If you want to use the OpenIddict/Microsoft integration, it's the `options.UseWebProviders().AddMicrosoft()` extension that you're looking for.

All the best.
