### ISSUE TITLE
Signing Key Store

### ISSUE THREAD

**Issue by KieranFleckney** [openiddict/openiddict-core#1976]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

I understood I am not sponsor, however, I would like to know if a signing key store ( possible automatic key management too) is a feature you would be open too or even working on. If so I would be happy to try a implementation. From my understanding there was a similar feature from issue #386. Also you provide a rough idea how to do get signing keys from a remote source in #1276. But would be nice to have a better interface to set this up and configure it.

### Additional context

I guess like something similar to https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/automatic_key_management/

**Comment by kevinchalet** [comment]
> I understood I am not sponsor, however, I would like to know if a signing key store ( possible automatic key management too) is a feature you would be open too or even working on.

It's indeed something I'll likely work on in the future (but probably as a sponsors-only/pro feature).

Of course, feel free to create your own implementation, I'll be more than happy to add a link in the README once it's ready.
