### ISSUE TITLE
How to configure certificate validation?

### ISSUE THREAD

**Issue by jwillmer** [openiddict/openiddict-core#1979]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.0.0

### Question

We are working with a reverse proxy (traefik) that terminates the SSL and communicates on port 80 with our application. The certificate we are currently using is not valid. We configured the following  in our app to ignore certificate validation:

```
services.AddHttpClient(string.Empty, _ => { })
                    .ConfigurePrimaryHttpMessageHandler(() =>
                    {
                        return new HttpClientHandler
                        {
                            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                        };
                    });
```

However we still see the following when browsing to the app:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN1CLVD75HDV", Request id "0HN1CLVD75HDV:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see
[https://aka.ms/IdentityModel/PII.]'.](https://aka.ms/IdentityModel/PII.]%27.)
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see
[https://aka.ms/IdentityModel/PII.]'.](https://aka.ms/IdentityModel/PII.]%27.)
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
```

So the question is how to setup openIdDict httpClient to take custom httpClient that is registered in DI or how to configure it's settings to change CertificateValidation to accept any certificate?
 
The problem we have is with custom certificate not being recognized and throwing SSL validation error on openid-configuration endpoint. We need to allow it to ignore it.

**Comment by kevinchalet** [comment]
> So the question is how to setup openIdDict httpClient to take custom httpClient that is registered in DI or how to configure it's settings to change CertificateValidation to accept any certificate?

To tweak the HTTP client handler used by the OpenIddict validation stack:

```csharp
services.AddOpenIddict()
    .AddValidation(options =>
    {
        options.UseSystemNetHttp()
               .ConfigureHttpClientHandler(handler =>
               {
                   handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
               });
    });
```

To tweak the HTTP client handler used by the OpenIddict client stack:

```csharp
services.AddOpenIddict()
    .AddClient(options =>
    {
        options.UseSystemNetHttp()
               .ConfigureHttpClientHandler(handler =>
               {
                   handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
               });
    });
```

Or better, you can limit that to a specific provider (based on the provider name):

```csharp
services.AddOpenIddict()
    .AddClient(options =>
    {
        options.UseSystemNetHttp()
               .ConfigureHttpClientHandler("Local", handler =>
               {
                   handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
               });
    });
```

**Comment by MartisiusL** [comment]
Hello, thank you for the response. First thing to mention is that we are using version that is below 5.x.x which makes `ConfigureHttpClientHandler` not yet available. I saw other responses from you for versions 4.x.x about configuring it using this approach:

```
services.AddHttpClient("OpenIddict.Validation.SystemNetHttp")
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
    });
```

Which I'm also using. But the problem still persist. 
Now I think I managed to reproduce the same behavior locally, it doesn't throw SSL exception exactly, but it still thinks that it is inaccessible with such error:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN1DAC9Q27CR", Request id "0HN1DAC9Q27CR:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:44372/Development/.well-known/openid-configuration'.
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Maranics.UserManagement.Core.Tools.Helpers.ResponseHeadersConfigurationHelper.<>c.<<DisablePdfAndFlashCrossDomainRequests>b__1_0>d.MoveNext() in C:\src\maranics\UserManagementApp\Maranics.UserManagement\Maranics.UserM
anagement.Core\Tools\Helpers\ResponseHeadersConfigurationHelper.cs:line 29

```

However, OpenId configuration with the shown URL can be easily accessible in the browser (after accepting the risk for non secure certificate) and it is properly configured. 

My guess is that it is still using some different httpClient registration that does not have settings applied that ignore the certificate and therefore fails. We need to get a solution how to make that `ChallengeAsync` to use custom httpClient that is configured.

**Comment by MartisiusL** [comment]
I also have configuration for any default HttpClient as well

```
services.AddHttpClient(string.Empty, _ => { })
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        return new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true
        };
    });
```

**Comment by kevinchalet** [comment]
Hey,

> First thing to mention is that we are using version that is below 5.x.x which makes `ConfigureHttpClientHandler` not yet available. I saw other responses from you for versions 4.x.x about configuring it using this approach:

It's important to note 4.x is no longer supported. That said, these APIs were introduced in 4.3.0, so anything beyond that version should work.

> Which I'm also using. But the problem still persist.
Now I think I managed to reproduce the same behavior locally, it doesn't throw SSL exception exactly, but it still thinks that it is inaccessible with such error:

That exception indicates you're using the MSFT OIDC handler, which is completely unrelated to OpenIddict. My recommendation is to use the OpenIddict client. If you don't want to adopt it, the HTTP handler can be customized in the MSFT OIDC handler options (see https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.remoteauthenticationoptions.backchannelhttphandler?view=aspnetcore-8.0#microsoft-aspnetcore-builder-remoteauthenticationoptions-backchannelhttphandler).

> I also have configuration for any default HttpClient as well

OpenIddict uses a named HTTP client so it's not surprising your custom `ConfigurePrimaryHttpMessageHandler()` call doesn't apply to that one (and the MSFT OIDC handler doesn't use `HttpClientFactory` at all).

Hope it helped.

**Comment by jwillmer** [comment]
This information was very helpful and we where able to resolve our issue. Thank you very much!

**Comment by kevinchalet** [comment]
@jwillmer thanks for sponsoring the project! ❤️

**Comment by MayueCif** [comment]
> OpenIddict uses a named HTTP client so it's not surprising your custom `ConfigurePrimaryHttpMessageHandler()` call doesn't apply to that one (and the MSFT OIDC handler doesn't use `HttpClientFactory` at all).

@MartisiusL How did you solve this problem?
