### ISSUE TITLE
Windows Authentication

### ISSUE THREAD

**Issue by ivanmariychuk** [openiddict/openiddict-core#198]
Hello! Is it possible somehow to use both windows and custom authentication using WebListener instead of Kestrel? Maybe not with OpenIddict... I would appreciate any thoughts!

**Comment by kevinchalet** [comment]
> Is it possible somehow to use both windows and custom authentication using WebListener instead of Kestrel?

Since OpenIddict doesn't handle the authentication part for interactive flows like code or implicit, it should be definitely possible (you could even use Kestrel behind IIS for that).
