### ISSUE TITLE
Decoding token; Passing user name with token endpoint

### ISSUE THREAD

**Issue by piotrek-k** [openiddict/openiddict-core#199]
I have few questions:
1. How can I decode token generated by openiddict? [This decoder](http://jwt.calebb.net/) says my token needs to have three segments whatever that means.
2. Can I somehow configure what TokenEndpoint returns? I need to return username of token owner.

I've configured everyting exactly like in [README.md file](https://github.com/openiddict/openiddict-core#getting-started). I'm using `OpenIddict (1.0.0-alpha2-0417)`. With `ASP.net Core 1.0.0`.

**Comment by kevinchalet** [comment]
> 1. How can I decode token generated by openiddict? This decoder says my token needs to have three segments whatever that means. 

By default, OpenIddict uses encrypted tokens so you can't use any of these JWT debug tools.

> 1. Can I somehow configure what TokenEndpoint returns? I need to return username of token owner.

The username is returned in the identity token if you request the profile scope.

**Comment by piotrek-k** [comment]
@PinpointTownes thanks for response, but I still have some questions, if you don't mind.

> By default, OpenIddict uses encrypted tokens so you can't use any of these JWT debug tools.

I don't remember if I specified anything like key/password to encrypt this token. How can I check it and eventually modify it in my app?

I'm also interested in what exactly happens when I use:
`services.AddOpenIddict<something>().EnableTokenEndpoint("/connect/token")`
and call `mywebsite.com/connect/token` in my browser. Could you link to part of code that encrypts token data and produces http response? Or could you at least tell where to look for it?

**Comment by kevinchalet** [comment]
OpenIddict simply relies on the ticket serializer and the DataProtection stack offered by ASP.NET Core. You'll find all the details you need here: https://docs.asp.net/en/latest/security/data-protection/index.html

The serializer can be found in the Security repo: https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication/DataHandler
