### ISSUE TITLE
Scopes not being stored as a claim in identity token.

### ISSUE THREAD

**Issue by josh-sachs** [openiddict/openiddict-core#200]
When a user is authenticated using an access_token, the level of access can be determined by an authorization policy evaluating the "scope" claim. 

This does not appear to be available within the identity token received via the OpenIdConnect authentication scheme.

**Comment by kevinchalet** [comment]
This is now something you can easily do, since you're responsible of creating the `AuthenticationTicket` and populating it with the claims you need.
