### ISSUE TITLE
Oracle doesn't support `RepeatableRead` isolation level.

### ISSUE THREAD

**Issue by maliming** [openiddict/openiddict-core#2009]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

hi @kevinchalet

Today, a customer reported an error. I added an option in the abp framework to solve it. 

```cs
public class AbpOpenIddictStoreOptions
{
    public IsolationLevel? PruneIsolationLevel { get; set; }

    public IsolationLevel? DeleteIsolationLevel { get; set; }

    public AbpOpenIddictStoreOptions()
    {
        PruneIsolationLevel = IsolationLevel.RepeatableRead;
        DeleteIsolationLevel = IsolationLevel.Serializable;
    }
}
```

I think OpenidDict should also find a good way to be compatible with Oracle.

Thanks.

The error log:

```
[ERR] Transaction isolation level RepeatableRead not supported.
System.ArgumentException: Transaction isolation level RepeatableRead not supported.
at Devart.Data.Oracle.OracleTransaction..ctor(OracleConnection A_0, IsolationLevel A_1)
```

The code: https://github.com/search?q=repo%3Aopeniddict%2Fopeniddict-core+IsolationLevel.RepeatableRead&type=code

https://docs.oracle.com/en/database/oracle/oracle-database/19/cncpt/data-concurrency-and-consistency.html#GUID-2A0FDFF0-5F72-4476-BFD2-060A20EA1685

**Comment by kevinchalet** [comment]
Hey @maliming,

Thanks for your report!

Oracle is not "officially" supported in OpenIddict (let's say it's mostly untested), but unsupported isolation levels shouldn't be blocking as we're supposed to catch exceptions thrown while trying to create a new transaction:

https://github.com/openiddict/openiddict-core/blob/93b2bae00884e3e0c8d46fedcfd24402e0c6510c/src/OpenIddict.EntityFrameworkCore/OpenIddictEntityFrameworkCoreHelpers.cs#L231-L265

Do you have a more complete stack trace? Or a link to the original ABP support ticket?

Thanks.

**Comment by maliming** [comment]
Thanks for the explanation. OpenidDict has no problem with that. 👍 

I will update abp to compatible with this situation.

**Comment by kevinchalet** [comment]
Ah great! 👍🏻 

All the best.
