### ISSUE TITLE
OpenIdConnectOptions - resolve ClientId / ClientSecret dynamically

### ISSUE THREAD

**Issue by tedvanderveen** [openiddict/openiddict-core#202]
I have a ASP.Net WEB API application that is a "client" to a OpenIddict server. This API is used by various customers. And refresh token should be provided by the OpenIddict server in the correct customer scope. When configuring UseOpenIdConnectAuthentication on the WEB API Startup, we can set the ClientId / ClientSecret. But we would like to set these fields per request, depending on the customer token that the WEB API client provides. So can we set ClientId / ClientSecret dynamically per request, using a callback for example? Or what would be the preferred way of supporting this scenario?

**Comment by kevinchalet** [comment]
Since the OIDC middleware is not developed or maintained here, I moved your question to the appropriate repo: https://github.com/aspnet/Security/issues/953.
