### ISSUE TITLE
SPA and BFF on different sub-domains, BFFs for mobile apps

### ISSUE THREAD

**Issue by meywd** [openiddict/openiddict-core#2031]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.2.0

### Question

Continuing the discussion from the previous thread #2027

> "BFFs for mobile apps" don't exist: mobile apps can directly use OIDC/token authentication without requiring a cookie/token translation mechanism (which is what a BFF is, essentially). A BFF only makes sense for a SPA.

I don't know much about it, but it seem to be a thing, for API optimization and auth.

- [Brave Mobile World: OAuth in Native Apps](https://curity.medium.com/brave-mobile-world-oauth-in-native-apps-e1257be0c2d5)

> A **mobile** application should never be registered as a confidential client at an authorization server — it’s essential to adhere to this rule. If the app was issued a secret, then the secret would have to be compiled into the code distributed to the end users’ mobile devices. This would mean that anyone could decompile the application to retrieve the secret and use it to impersonate the legitimate app.

- [Backend For Frontend Authentication Pattern with Auth0 and ASP.NET Core](https://auth0.com/blog/backend-for-frontend-pattern-with-auth0-and-dotnet/)

> Public clients are those that run in places where secrets could be exposed as part of the source code or if the binaries are decompiled. These usually are single-page apps running in a browser or native apps running in user devices such as **mobile** phones or smart TVs. 

but I am not here to prove if it actually provides any benefits, as last discussed, The whole idea is doing SSO, multiple APIs, multiple SPAs(some end users, some internal\admin users) with one or more BFFs to secure them, plus potential 3rd party websites connecting to the APIs using App to App auth, 3rd party and 1st party mobile apps, and the auth server might move to its own domain.

and setting the domain value of the cookie on the BFF didn't work. do I need to set it on the API? if yes how since the API is using `AddValidation` because its using Introspection.

**Comment by kevinchalet** [comment]
> I don't know much about it, but it seem to be a thing, for API optimization and auth.
> [Brave Mobile World: OAuth in Native Apps](https://curity.medium.com/brave-mobile-world-oauth-in-native-apps-e1257be0c2d5)

I don't see anywhere in that post where they recommend using a BFF for a mobile application: **this post isn't about the BFF pattern at all** - it's not even mentioned - it simply clarifies the fact mobile applications should be declared as public clients (which is standard practice and fully supported by OpenIddict too)

> and setting the domain value of the cookie on the BFF didn't work. 

Unfortunately, you decided to ignore my recommendation to use a BFF per SPA and serve that SPA via the BFF to avoid any origin mismatch/cookie sharing issues (which is the standard approach) and opted for a more complex setup.

As I mentioned in the other thread, I'm unable to repro your issue locally and you didn't provide a repro yourself, so I can't help you more with that, unfortunately.

**Comment by meywd** [comment]
I managed to make things work by redirecting all traffic through the BFF then proxy the API to API and the UI to UI, now the problem here is a big a mount of work is needed to setup the dev environment for testing.(domain, host on iis, publish to update)

On the other hand I found about the Asp.net core React templates which could work as a middle ground, and for the UI + BFF I think it will be fine, however I also need to customize the UI of the Auth\SSO server, and checking the other recent thread about using SPA for UI, I found that you have APIs to use instead of MVC for authorization in the Mimban sample and you mention the  .NET 8.0 identity APIs, which I also tested.

Now does these APIs work fine with OpenIddict? for example, I login and use cookies, so now I have a cookie, can I get user info using that cookie? I am getting a 401 when I use UserInfo controller from Dantooine.

**Comment by meywd** [comment]
I made a minimal API and it worked
```
app.MapGet("/account/userInfo", async Task<IResult> (HttpContext context, ClaimsPrincipal user, UserManager<ApplicationUser> userManager) =>
{
    var _user = await userManager.GetUserAsync(user);
    if (_user == null)
    {
        return TypedResults.Challenge(
            authenticationSchemes: new List<string> { OpenIddictServerAspNetCoreDefaults.AuthenticationScheme },
            properties: new AuthenticationProperties(new Dictionary<string, string?>
            {
                [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.InvalidToken,
                [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] =
                    "The specified access token is bound to an account that no longer exists."
            }));
    }

    var claims = new Dictionary<string, object>(StringComparer.Ordinal)
    {
        // Note: the "sub" claim is a mandatory claim and must be included in the JSON response.
        [Claims.Subject] = await userManager.GetUserIdAsync(_user)
    };

    if (user.HasScope(Scopes.Email))
    {
        claims[Claims.Email] = await userManager.GetEmailAsync(_user) ?? "";
        claims[Claims.EmailVerified] = await userManager.IsEmailConfirmedAsync(_user);
    }

    if (user.HasScope(Scopes.Phone))
    {
        claims[Claims.PhoneNumber] = await userManager.GetPhoneNumberAsync(_user) ?? "";
        claims[Claims.PhoneNumberVerified] = await userManager.IsPhoneNumberConfirmedAsync(_user);
    }

    if (user.HasScope(Scopes.Roles))
    {
        claims[Claims.Role] = await userManager.GetRolesAsync(_user);
    }

    // Note: the complete list of standard claims supported by the OpenID Connect specification
    // can be found here: http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

    return TypedResults.Ok(claims);
}).RequireAuthorization();
```
However it seem using the `MapIdentityApi` register doesn't add scopes! I am not sure where I got this, but I am using both:
```
builder.Services.Configure<IdentityOptions>(options =>
{
    // Configure Identity to use the same JWT claims as OpenIddict instead
    // of the legacy WS-Federation claims it uses by default (ClaimTypes),
    // which saves you from doing the mapping in your authorization controller.
    options.ClaimsIdentity.UserNameClaimType = Claims.Name;
    options.ClaimsIdentity.UserIdClaimType = Claims.Subject;
    options.ClaimsIdentity.RoleClaimType = Claims.Role;
    options.ClaimsIdentity.EmailClaimType = Claims.Email;

    // Note: to require account confirmation before login,
    // register an email sender service (IEmailSender) and
    // set options.SignIn.RequireConfirmedAccount to true.
    //
    // For more information, visit https://aka.ms/aspaccountconf.
    options.SignIn.RequireConfirmedAccount = false;
});
```
and
```
        options.RegisterScopes(Scopes.Email, Scopes.Profile, Scopes.Roles, "api", "workflow");
```

**Comment by kevinchalet** [comment]
> I managed to make things work by redirecting all traffic through the BFF then proxy the API to API and the UI to UI

Nice 👍🏻 

> now the problem here is a big a mount of work is needed to setup the dev environment for testing.(domain, host on iis, publish to update)

Haha, yeah, I can imagine 😄 

> Now does these APIs work fine with OpenIddict? for example, I login and use cookies, so now I have a cookie, can I get user info using that cookie? I am getting a 401 when I use UserInfo controller from Dantooine.

No, you can't: the userinfo controller (that could also be a minimal API handler) is exclusively used for OIDC, which requires sending a valid access token.

> However it seem using the MapIdentityApi register doesn't add scopes! I am not sure where I got this, but I am using both:

That's expected, scopes are an OAuth 2.0/OpenID Connect concept: if you implement a custom, non-OIDC userinfo API, scopes won't be there at all.

**Comment by meywd** [comment]
> That's expected, scopes are an OAuth 2.0/OpenID Connect concept: if you implement a custom, non-OIDC userinfo API, scopes won't be there at all.

how to work around this? do an old fashioned Users API?

**Comment by kevinchalet** [comment]
> how to work around this? do an old fashioned Users API?

If you absolutely need a "userinfo" API that directly accepts cookies, yes. Otherwise, you could use your BFF proxy to handle the "cookie -> token conversion" and use a standard OIDC userinfo endpoint: in this case, you'll be able to use scopes.
