### ISSUE TITLE
invalid_token returned by authorization callback

### ISSUE THREAD

**Issue by verdie-g** [openiddict/openiddict-core#2048]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.4.0

### Question

I'm trying to develop a client for [Discord oauth2](https://discord.com/developers/docs/topics/oauth2) and I would need some assistance to understand why I'm getting a `invalid_token` in the authorization callback.

Here is the startup code:

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<OpenIddictDbContext>(options =>
{
    options.UseInMemoryDatabase("openiddict");
    options.UseOpenIddict();
});

builder.Services.AddControllers();

builder.Services.AddOpenIddict()
    .AddCore(options =>
    {
        options
            .UseEntityFrameworkCore()
            .UseDbContext<OpenIddictDbContext>();
    })
    .AddClient(options =>
    {
        var webIntegrationBuilder = options.UseWebProviders();

        string discordClientId = builder.Configuration["Discord:ClientId"];
        string discordClientSecret = builder.Configuration["Discord:ClientSecret"];

        webIntegrationBuilder.AddDiscord(discord =>
        {
            discord
                .SetClientId(discordClientSecret)
                .SetClientSecret(discordClientSecret)
                .SetRedirectUri("connect/callback-discord");
        });

        options.AllowAuthorizationCodeFlow();

        options.AddDevelopmentEncryptionCertificate()
            .AddDevelopmentSigningCertificate();

        options.UseAspNetCore()
            .EnableRedirectionEndpointPassthrough();
    });

var app = builder.Build();

app.UseRouting();
app.MapControllers();
app.Run();
```

After clicking the authorize button on https://discord.com/oauth2/authorize?client_id=[redacted]&response_type=code&redirect_uri=https://localhost:5203/connect/callback-discord&scope=identify&state=15773059ghq9183habm I'm redirected to https://localhost:5203/connect/callback-discord?code=e1yphO6zDF50eoDR6i1CJYIPY02t8R&state=15773059ghq9183habm and it returns
```
error:invalid_token
error_description:The specified token is invalid.
error_uri:https://documentation.openiddict.com/errors/ID2004
```

Here are the logs
```
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ResolveRequestUri.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+InferEndpointType.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ValidateTransportSecurityRequirement.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ValidateHostHeader.
The event OpenIddict.Client.OpenIddictClientEvents+ExtractRedirectionRequestContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ExtractGetOrPostRequest`1[[OpenIddict.Client.OpenIddictClientEvents+ExtractRedirectionRequestContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The redirection request was successfully extracted: {
  "code": "[redacted]",
  "state": "15773059ghq9183habm"
}.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ExtractRedirectionRequest.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ValidateAuthenticationType.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ValidateAuthenticationNonce.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+ValidateAuthenticationDemand.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+ResolveClientRegistrationFromAuthenticationContext.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+EvaluateValidatedUpfrontTokens.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+ResolveValidatedStateToken.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+ValidateRequiredStateToken.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+ResolveTokenValidationParameters.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.WebIntegration.OpenIddictClientWebIntegrationHandlers+Protection+AmendTokenValidationParameters.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+RemoveDisallowedCharacters.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+ValidateReferenceTokenIdentifier.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+ValidateIdentityModelToken.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+MapInternalClaims.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+RestoreTokenEntryProperties.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Protection+ValidatePrincipal.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateTokenContext was marked as rejected by OpenIddict.Client.OpenIddictClientHandlers+Protection+ValidatePrincipal.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+ValidateStateToken.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessAuthenticationContext was marked as rejected by OpenIddict.Client.OpenIddictClientHandlers+ValidateStateToken.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateRedirectionRequestContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ValidateTokens.
The event OpenIddict.Client.OpenIddictClientEvents+ValidateRedirectionRequestContext was marked as rejected by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ValidateTokens.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ValidateRedirectionRequest.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessRequestContext was marked as rejected by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ValidateRedirectionRequest.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+AttachErrorParameters.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+AttachHttpResponseCode`1[[OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+AttachCustomErrorParameters.
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+AttachCacheControlHeader`1[[OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+AttachHttpResponseCode`1[[OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+AttachCacheControlHeader`1[[OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The response was successfully returned as a plain-text document: {
  "error": "invalid_token",
  "error_description": "The specified token is invalid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2004"
}.
The event OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext was successfully processed by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ProcessLocalErrorResponse`1[[OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext was marked as handled by OpenIddict.Client.AspNetCore.OpenIddictClientAspNetCoreHandlers+ProcessLocalErrorResponse`1[[OpenIddict.Client.OpenIddictClientEvents+ApplyRedirectionResponseContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was successfully processed by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ApplyRedirectionResponse`1[[OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
The event OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext was marked as handled by OpenIddict.Client.OpenIddictClientHandlers+Authentication+ApplyRedirectionResponse`1[[OpenIddict.Client.OpenIddictClientEvents+ProcessErrorContext, OpenIddict.Client, Version=5.4.0.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]].
```

I'm not sure to understand what token means in this context. After some debugging, it seems like the error comes from there https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Client/OpenIddictClientHandlers.Protection.cs#L603-L606. What am I missing?

**Comment by kevinchalet** [comment]
Hey @verdie-g,

> I'm not sure to understand what token means in this context. After some debugging, it seems like the error comes from there https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Client/OpenIddictClientHandlers.Protection.cs#L603-L606. What am I missing?

The token mentioned here is the "state token" generated by OpenIddict to store per-authorization data and protect against session fixation/CSRF attacks (an associated cookie is automatically created by the ASP.NET Core host to act as a correlated value).

The `15773059ghq9183habm` state present in the logs is weird: by default, the OpenIddict client uses reference state tokens, so it stores the actual payload in the DB and generates a 256-bit reference ID that is base64url-encoded, which means you should get a 43-character token in practice. `15773059ghq9183habm` only includes 19 characters so it's very likely something funky is going on.

Are you specifying a custom `state` parameter when triggering a challenge?

Note: I just tried reproducing the issue locally with the Discord provider but wasn't able to.

**Comment by verdie-g** [comment]
Thanks for your quick answer.

> Are you specifying a custom state parameter when triggering a challenge?

Yes I understood that the state can be a random non-guessable string so just for the test I smashed some buttons on my keyboard. 

> the OpenIddict client uses reference state tokens, so it stores the actual payload in the DB and generates a 256-bit reference ID that is base64url-encoded

I'm not sure to understand when does OpenIddict has the opportunity to replace the state by a reference. When the client, hits Discord's authorization endpoint it provides the state parameter. Or maybe the `discord.com/oauth2/authorize/XXX` url should be generated by OpenIddict? 😬

**Comment by kevinchalet** [comment]
> Yes I understood that the state can be a random non-guessable string so just for the test I smashed some buttons on my keyboard.

Haha, no: for things to work correctly OOTB (i.e without some custom event handlers), the `state` must be created and managed by OpenIddict.

It's important to note that OpenIddict's `state` is not just a random ID, it stores critical *state* that will be accessible from the redirection/callback endpoint (e.g the registration ID, the nonce or the `code_verifier` if PKCE was used, etc.)

> I'm not sure to understand when does OpenIddict has the opportunity to replace the state by a reference.

The payload -> reference ID swapping logic is implemented by the `AttachTokenPayload` event handler:

https://github.com/openiddict/openiddict-core/blob/6ac8c2c53ef4008376b1b408d17efef13354a3b3/src/OpenIddict.Client/OpenIddictClientHandlers.Protection.cs#L951-L1014

The `GenerateToken(Context)` event is triggered as part of the `ProcessChallenge(Context)` event handling, when a state token must be generated. E.g for login state tokens:

https://github.com/openiddict/openiddict-core/blob/6ac8c2c53ef4008376b1b408d17efef13354a3b3/src/OpenIddict.Client/OpenIddictClientHandlers.cs#L5209-L5273

> When the client, hits Discord's authorization endpoint it provides the state parameter. Or maybe the `discord.com/oauth2/authorize/XXX` url should be generated by OpenIddict? 😬

**Yes**, unless you're doing something **extremely advanced** (that would require writing custom event handlers), it is expected that the challenge will be entirely handled by OpenIddict, from the `state` creation to the redirection to Discord's authorization endpoint.

If you use ASP.NET Core Identity and its default UI, the challenge will be started by Identity's UI when clicking on the "external provider" button.

If you don't use ASP.NET Core Identity or its default UI, you can manually trigger a challenge using the regular ASP.NET Core authentication APIs. E.g for a minimal API endpoint:

```csharp
// Add a minimal action responsible for triggering a Discord challenge
// and redirecting the user agent to the Discord authorization endpoint.
app.MapGet("challenge", () => Results.Challenge(properties: null, authenticationSchemes: [Providers.Discord]));
```

**Comment by verdie-g** [comment]
Okay, very interesting 🧐

Let me process all this and I'll get back to you. I'm trying to build a discord app and the authorization interactions are not very clear to me for now.

**Comment by kevinchalet** [comment]
> Let me process all this and I'll get back to you. I'm trying to build a discord app and the authorization interactions are not very clear to me for now.

Sure, don't hesitate if you need additional details or have any question 😃

**Comment by verdie-g** [comment]
So according to https://discord.com/developers/docs/quick-start/getting-started#installing-your-app I should hit the authorize endpoint with `scope=bot` and `permissions=XX` to install a bot to my server.

```diff
webIntegrationBuilder.AddDiscord(discord =>
{
    discord
        .SetClientId(discordClientId)
        .SetClientSecret(discordClientSecret)
        .SetRedirectUri("connect/callbackDiscord")
+       .AddScopes("bot");
});
```
~~It seems like this code will actually replace the `scope=identify` with `scope=bot`, I suppose `identify` is the default value if `AddScopes` is not called~~. 
This code adds `scope=bot` but doesn't remove the default `scope=identify`, also how can I add the `permissions` parameter? 🤔

Also, discord forces me to specify a redirect URL but at the time of the callback, I already gave Discord the credentials of my app to authenticate and it's added to my discord server so there is not much left to do. Can I just return 200? Maybe this callback is useful if some other random server wants to add my app, I can log "okay this guy added my app to this server"?
![image](https://github.com/openiddict/openiddict-core/assets/9092290/f9a10887-a9f1-4ca8-b4e6-50d0d8b3e733)

**Comment by kevinchalet** [comment]
> This code adds `scope=bot` but doesn't remove the default `scope=identify`, also how can I add the `permissions` parameter? 🤔

You can add custom parameters by attaching them to `AuthenticationProperties`:

```csharp
app.MapGet("challenge", () =>
{
    var properties = new AuthenticationProperties();
    properties.SetParameter("permissions", "1");

    return Results.Challenge(properties, [Providers.Discord]);
});
```

> Also, discord forces me to specify a redirect URL but at the time of the callback, I already gave Discord the credentials of my app to authenticate and it's added to my discord server so there is not much left to do. Can I just return 200? Maybe this callback is useful if some other random server wants to add my app, I can log "okay this guy added my app to this server"?
> ![image](https://private-user-images.githubusercontent.com/9092290/320655340-f9a10887-a9f1-4ca8-b4e6-50d0d8b3e733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTMwODQsIm5iZiI6MTcxMjYxMjc4NCwicGF0aCI6Ii85MDkyMjkwLzMyMDY1NTM0MC1mOWExMDg4Ny1hOWYxLTRjYTgtYjRlNi01MGQwZDhiM2U3MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjE0NjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGU3OTZiNGE1NDZjMjVjNzlhNTAyYmRiMjQ1NTBhZTNiODdhZjIxMTIxYzRiOWY4MTYzZjg4OTcxNGMzOTdjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oeTEKTXQpu1dBvT4RjnJ1PwCH8xJN32AUboBCYeZNjY)

AFAICT, the `redirect_uri` parameter isn't even used in the - very special/non-standard - "bot authorization flow" so it will never be invoked. Returning a 200 response should be fine.

**Comment by verdie-g** [comment]
Thanks, it's all clear now! About the initial issue, would it make sense to return a more explicit error, something like "The provided state token is invalid. Make sure the challenge was handled by OpenIddict"?

**Comment by kevinchalet** [comment]
Yeah, a more precise error message could certainly be returned. Here's the error message we're using when the correlation cookie is missing:

```
No correlation cookie associated with the specified state can be found. Please try logging in again. If the error persists, please contact the website owner.
```

(note: while quite precise, including `Make sure the challenge was handled by OpenIddict` in the user-facing message would be a bit misleading, as there's nothing the user himself can do to fix this error)

**Comment by verdie-g** [comment]
https://github.com/openiddict/openiddict-core/blob/6ac8c2c53ef4008376b1b408d17efef13354a3b3/src/OpenIddict.Abstractions/Descriptors/OpenIddictTokenDescriptor.cs#L42-L45

I see that a token has properties. Am I allowed to add some stuff there? My use-case is that I would like to associate a discord id and a steam id. Here is the flow I'm thinking about:
- User runs a command on discord
- The discord bot returns a button that links to steam login
- In the redirection endpoint I have the steam id but I would also need the discord id somehow

It would be great if the discord id could be in the data referenced by the state token. One issue is that Steam implements open id 2.0 so I suppose it would not work.

An alternative I was thinking about was that the discord bot could add an encrypt discord id in the redirect url.

**Comment by kevinchalet** [comment]
Yeah, you can use that property to store custom stuff (or you can create your own entities and stores, but it's more involved: https://documentation.openiddict.com/integrations/entity-framework-core.html#use-custom-entities).

That said, I'm not sure how that would work here: state tokens are created before the user is redirected to Discord, so there's no user information available at this stage at all. I guess you could tweak your bot to include the Discord ID - e.g as an encrypted and/or HMACed value - directly in the URL pointing to a custom endpoint on your website that would store it in `AuthenticationProperties.Items` before triggering a Steam challenge, but that wouldn't be super secure: if the user shared that link with someone else, that person could link his own Steam account with the victim's Discord account 😅

**Comment by verdie-g** [comment]
> if the user shared that link with someone else, that person could link his own Steam account with the victim's Discord account 😅

Damn you're right. Anyway, I think I'm diverging too much from the initial issue. Thanks for your answers!

**Comment by kevinchalet** [comment]
> Thanks for your answers!

My pleasure! Thanks for sponsoring the project 👍🏻 

> Anyway, I think I'm diverging too much from the initial issue.

No worries, it's always interesting and cool for me to see how you guys are using OpenIddict 😃

**Comment by xperiandri** [comment]
> The token mentioned here is the "state token" generated by OpenIddict to store per-authorization data

Thanks for this explananation. It was totally my case. I just had some wrong configuration in my Azure Cosmos DB JSON serializer property name mapper and my `IOpenIddictTokenStore` did not found the token
