### ISSUE TITLE
unauthorized_client when changing url

### ISSUE THREAD

**Issue by yayapsa** [openiddict/openiddict-core#2052]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

not sure

### Describe the bug

the redirect works without any issue if the url is pointed to FQDN but when changing to a URL name we get the error Sorry, there was an error : unauthorized_client
Request Id: 80000006-0001-e900-b63f-84710c7967bb

### To reproduce

Not sure where to look at

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!

**Comment by yayapsa** [comment]
@kevinchalet my co-worker David Mullings was the one that implemented it and I believe is was a sponsor/contributor - He is no longer around

**Comment by kevinchalet** [comment]
@yayapsa hum, what is his GitHub handle? It's worth noting that support is only available for individuals or companies that still have an active subscription.

**Comment by yayapsa** [comment]
> @yayapsa hum, what is his GitHub handle? It's worth noting that support is only available for individuals or companies that still have an active subscription.

I am not sure sir as I am new to this place but David is the one used to setup so I am not sure an active subscription is there

**Comment by yayapsa** [comment]
@kevinchalet please let me what I need to do to get support from your team before we make decision to look at other options

**Comment by kevinchalet** [comment]
As I mentioned, getting support requires an active sponsorship. If you're not familiar with GitHub Sponsors, I'd recommend reading https://docs.github.com/articles/sponsoring-an-open-source-contributor 😃 

Note: if you decide to sponsor the project, you'll also need to post a lot more details, because your issue is not really actionable with so few information.
