### ISSUE TITLE
 openiddict 5.0.1 => 5.1.0, breaking change when adding amr array claim to id_token

### ISSUE THREAD

**Issue by damienbod** [openiddict/openiddict-core#2061]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.1.0 or later

### Describe the bug

A partner OIDC client must get an **amr** claim with an array value back in the id_token for a specific flow to work. The claim is added as follows:

```csharp
claims.Add(new Claim("amr", "[\"fido\"]", JsonClaimValueTypes.JsonArray));
```

This results in the following claim in the id_token:

```json
"amr": [
    "fido"
  ],
```

This works fine in version 5.0.1 or older. When I update the packages to version 5.1.0 it no longer works.

Would it be possible to support this again like before? 

### To reproduce

Add the amr claim as an array to the id_token

### Exceptions (if any)

```shell
InvalidOperationException: The 'amr' claim present in the specified principal is malformed or isn't of the expected type.
```

**Comment by kevinchalet** [comment]
Hey,

> This works fine in version 5.0.1 or older. When I update the packages to version 5.1.0 it no longer works.

5.1.0 being stricter regarding the claim value types was a deliberate behavior change (see https://github.com/openiddict/openiddict-core/releases/tag/5.1.0 for more information).

The (quite) special `JSON_ARRAY` claim value type isn't indeed currently allowed/supported by the claim value type validation check, but I opened https://github.com/openiddict/openiddict-core/pull/2062 to support it in the next minor version.

**Comment by kevinchalet** [comment]
@damienbod the fix is included in the latest "nightly" build. Any chance you could give it a try? 😃

**Comment by damienbod** [comment]
Hi @kevinchalet 

Tested works perfect, thanks

Greetings Damien

**Comment by kevinchalet** [comment]
Great to hear. Thanks @damienbod!

**Comment by damienbod** [comment]
Hi @kevinchalet Thanks

Here's the repo where I use this:

https://github.com/damienbod/MfaServer

Microsoft Entra multifactor authentication external server using OpenIddict.

Greetings Damien
