### ISSUE TITLE
Quick question ... does openiddict only work with Entity Framework?

### ISSUE THREAD

**Issue by guilliho** [openiddict/openiddict-core#207]
Hi, I'm wondering if openiddict can be used with a different ORM like Dapper for example. If it's possible can you please point me in the right direction. 

Thank you!

**Comment by kevinchalet** [comment]
Hey,

Though only EF Core is supported OTB, OpenIddict offers `IOpenIddictXYZStore` interfaces you can implement to create your own store.

**Comment by guilliho** [comment]
Got it! That's what I needed! Thank you! Just one more thing, in order to use [Authorize] and  [Authorize(Roles="role")] in my Controllers, I would have to implement IRoleStore and IUserStore from Microsoft.AspNetCore.Identity since they also use EntityFramework right? I know that this question is not related to OpenIddict but I just wanted to ask in case OpenIddict handles this already.

Thanks!

**Comment by kevinchalet** [comment]
> Just one more thing, in order to use [Authorize] and [Authorize(Roles="role")] in my Controllers, I would have to implement IRoleStore and IUserStore from Microsoft.AspNetCore.Identity since they also use EntityFramework right?

The authorization stack is entirely based on claims and only needs a `ClaimsPrincipal` to work: it doesn't use stores at all. So you could have an "API project" using the JWT bearer middleware or the validation middleware without having to reference Identity or OpenIddict.

**Comment by guilliho** [comment]
Ahh I see! Great man! Thank you very much!

**Comment by vengi83644** [comment]
@GuilliHo  @kevinchalet  Is there a sample you have for OpenIdDict without EF?

**Comment by kevinchalet** [comment]
@GuilliHo I wrote this blog post about OpenIddict 3.0's degraded mode, that allows using it without a backing database: https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

OpenIddict natively supports EF 6, EF Core and MongoDB, and switching from one to another is quite easy: reference the stores package you need and call the appropriate `options.Use*()` extension from `services.AddOpenIddict().AddCore(options => { ... })`.
