### ISSUE TITLE
Calling AuthenticateInteractivelyAsync from api server in windows installed app

### ISSUE THREAD

**Issue by dgxhubbard** [openiddict/openiddict-core#2079]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.3.0

### Question

I added support for generating an access token from our api by calling AuthenticateInteractivelyAsync. It uses auth code flow. In debug and release, in visual studio it works great, but on install in release mode fails with "Object reference not set to an instance of an object." I am not sure what the problem is. We added this to support authorize in swagger and also for clients to generate an access token and test. The browser never open the login.

**Comment by dgxhubbard** [comment]
Api openiddict setup

`                builder.Services.AddDbContext<AppDbContext> ( options =>
                {
                    options.UseSqlite ( connectionString );
                    options.UseOpenIddict ();
                } );


                // Register the OpenIddict validation components.
                builder.Services.AddOpenIddict ()
                    .AddValidation ( options =>
                    {

                        // set url to listen on
                        // using idpports.json for port
                        // this is so user can specify port

                        var idpPortsPath = Ports.GetIdpPortsFilePath ();

                        LogProvider.Logger.LogInfo ( "ports.json path: " + idpPortsPath );


                        if ( !Ports.Exists ( idpPortsPath ) )
                            throw new InvalidOperationException ( "FAILED no ports file" );

                        var idpPorts = Ports.LoadPorts ( idpPortsPath );



                        // Note: the validation handler uses OpenID Connect discovery
                        // to retrieve the issuer signing keys used to validate tokens.
                        options.SetIssuer ( "https://localhost" + ":" + idpPorts.Port );
                        options.AddAudiences ( "gt_resource_server" );

                        // Register the signing and encryption credentials used to protect
                        // sensitive data like the state tokens produced by OpenIddict.
                        options.AddEncryptionCertificate ( xEncrypt )
                                .AddSigningCertificate ( xSigning );


                        // Register the System.Net.Http integration.
                        options.UseSystemNetHttp ();

                        // Register the ASP.NET Core host.
                        options.UseAspNetCore ();
                    } )

                    // Register the OpenIddict core components.
                    .AddCore ( options =>
                    {
                        // Configure OpenIddict to use the Entity Framework Core stores and models.
                        // Note: call ReplaceDefaultEntities() to replace the default OpenIddict entities.
                        options.UseEntityFrameworkCore ()
                                .UseDbContext<AppDbContext> ();
                    } )

                    // Register the OpenIddict client components.
                    .AddClient ( options =>
                    {
                        // Note: this sample uses the authorization code flow,
                        // but you can enable the other flows if necessary.
                        options.AllowAuthorizationCodeFlow ()
                            .AllowRefreshTokenFlow ();

                        // Register the signing and encryption credentials used to protect
                        // sensitive data like the state tokens produced by OpenIddict.
                        options.AddEncryptionCertificate ( xEncrypt )
                                .AddSigningCertificate ( xSigning );



                        /*
                        // Register the signing and encryption credentials.
                        options.AddDevelopmentEncryptionCertificate ()
                            .AddDevelopmentSigningCertificate ();
                        */

                        // Add the operating system integration.
                        options.UseSystemIntegration ()
                            .SetAllowedEmbeddedWebServerPorts ( 7000 );


                        // Register the System.Net.Http integration and use the identity of the current
                        // assembly as a more specific user agent, which can be useful when dealing with
                        // providers that use the user agent as a way to throttle requests (e.g Reddit).
                        options.UseSystemNetHttp ()
                            .SetProductInformation ( typeof ( Program ).Assembly );

                        // set url to listen on
                        // using idpports.json for port
                        // get path to idpports
                        // change directory as needed

                        var idpPortsPath = Ports.GetIdpPortsFilePath ();


                        if ( !Ports.Exists ( idpPortsPath ) )
                            throw new InvalidOperationException ( "FAILED no ports file" );

                        var idpPorts = Ports.LoadPorts ( idpPortsPath );



                        // Add a client registration matching the client application definition in the server project.
                        options.AddRegistration ( new OpenIddictClientRegistration
                        {
                            Issuer = new Uri ( "https://localhost:" + idpPorts.Port + "/", UriKind.Absolute ),

                            ClientId = "core_api_client",
                            RedirectUri = new Uri ( "http://localhost:7000/", UriKind.Absolute ),

                            Scopes = { Scopes.OpenId, "api" }
                        } );
                    } );

`

**Comment by dgxhubbard** [comment]
Controller to generate token

`        public GeenerateTokenController ( 
            IWebHostEnvironment hostingEnvironment,
            OpenIddictClientService service )
        {
            HostingEnvironment = hostingEnvironment;

            Service = service;

            if ( Service == null )
                throw new ArgumentNullException ( "IDP client service is null" );

        }
        

        #region Properties

        public IWebHostEnvironment HostingEnvironment
        { get; set; }

        public OpenIddictClientService Service 
        { get; set; }



        #endregion

        [ HttpGet]
        public async Task<ActionResult<StringResultDto>> Get ()
        {
            var res = new StringResultDto ();

            string accessToken = null;

            var stoppingToken = CancellationToken.None;

            try
            {
                if ( Service == null )
                    throw new NullReferenceException ( "IDP client service null" );

                // Ask OpenIddict to initiate the authentication flow (typically, by starting the system browser).
                var result1 = await Service.ChallengeInteractivelyAsync ( new ()
                {
                    CancellationToken = stoppingToken
                } );

                Console.WriteLine ( "System browser launched." );

                // Wait for the user to complete the authorization process.
                var result2 = await Service.AuthenticateInteractivelyAsync ( new ()
                {
                    Nonce = result1.Nonce
                } );

                accessToken = result2.BackchannelAccessToken ?? result2.FrontchannelAccessToken;

                Console.WriteLine ( accessToken );


                res.Result = accessToken;
            }
            catch ( Exception ex )
            {
                LogProvider.Logger.LogException ( "Error generating access token", ex );

                return BadRequest ( ex );
                
            }





            return Ok ( res );

        }
`

**Comment by dgxhubbard** [comment]
This problem happens when running as a windows service or running in IIS

**Comment by kevinchalet** [comment]
Hey,

> This problem happens when running as a windows service or running in IIS

`ChallengeInteractivelyAsync()` and `AuthenticateInteractivelyAsync()` not working in non-console/desktop applications - or mobile apps in a distant future 😄 - is definitely expected as they are exclusively meant to be used in user interactive processes (launching a browser doesn't make sense for a IIS or Windows Service app since there's no desktop to interactive with in this case).

To trigger a challenge in an ASP.NET Core app, you need to use the ASP.NET Core `Challenge()` API (accessible via `ControllerBase.Challenge()`, `Results.Challenge()` or using the low-level `IAuthenticationService.Challenge()` API). Take a look at the samples repo to see how it's done.

That said, getting a `NullReferenceException` is a bit crude (if you try the same operation when the ASP.NET Core host is registered and you're not using the ASP.NET Core authentication APIs, you get a better exception).

I'll investigate. Thanks for the report 👍🏻

**Comment by dgxhubbard** [comment]
Thank you!

**Comment by dgxhubbard** [comment]
Is this the one?
![image](https://github.com/openiddict/openiddict-core/assets/5032382/1856b50b-7513-4d71-b8b7-f5e3af0fd104)

**Comment by kevinchalet** [comment]
Yep, exactly 👍🏻 

Edit: consider removing `options.UseSystemIntegration()`: it only makes sense in a desktop/mobile apps and shouldn't be used in web apps 😃

**Comment by dgxhubbard** [comment]
I will do it!

**Comment by kevinchalet** [comment]
@dgxhubbard did that work? 😃
