### ISSUE TITLE
For testing purposes how to create a fake web provider that returns tokens from fake identity?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#2086]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.6

### Question

I implemented a test that spins up the sever and the client in the same test host process and tries to perform the Authorization Code flow.
How can I return the response from `authorize` endpoint without user interaction returning a code?

If this requires code to be written I'm ready to contribute. I just don't know what is needed for that.

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors who have active an active subscription (reminder: cancelling your subscription shortly after getting support is considered abusive, so the benefits of the selected tier are lost when doing that less than 12 months after subscribing).

For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you back on board!
