### ISSUE TITLE
Example in readme produces unexpected results

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#209]
The ROPC example in the README file returns 200 OK when credential are invalid.

return Json(... will return 200.

**Comment by jayrulez** [comment]
Should be BadResult(... when there is an error

**Comment by kevinchalet** [comment]
Nice catch. I'll replace it by `BadRequest` and decorate the action with `[Produces("application/json")]` to ensure the JSON formatter is always used to serialize the response.
