### ISSUE TITLE
ApplicationID and AuhtorizationId in Tokens

### ISSUE THREAD

**Issue by STS-SW** [openiddict/openiddict-core#2096]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.6

### Describe the bug

Hi all, 
I am implementing my data layer for a project I am involved.
I wonder why the Token entity has a reference to the Application Entity and also to the Authorization Entity since the Authorization Entity already has a reference to the Application Entity.

Can a Token be released for an Application different than the one that holds the Authorization?

### To reproduce

See the database structure

**Comment by kevinchalet** [comment]
Hi,

GitHub didn't recognized you as a sponsor. Did you sponsor the project using an entreprise account?

Cheers.

**Comment by STS-SW** [comment]
> Hi,
> 
> GitHub didn't recognized you as a sponsor. Did you sponsor the project using an entreprise account?
> 
> Cheers.

No, I am not actually, mine is a question and I didn't find any other place where put it. 
I am sorry.

**Comment by kevinchalet** [comment]
No problem. Given that support/questions are reserved to sponsors (as a way to encourage companies to sponsor the project), I'd recommend posting your question on community-driven platforms, like StackOverflow.

Cheers.
