### ISSUE TITLE
Net framework 4.8 MVC authentication troubles

### ISSUE THREAD

**Issue by lufo88ita** [openiddict/openiddict-core#2133]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.6.0

### Question

Hi Kevin,

Thanks for your work. My company sponsered you through the account SCP-srl, I'm a member of it.
https://github.com/orgs/SCP-srl/people

We configured with success a server with openiddict and a series of client (angular 2+) and api (net core 6+).
Now we have a problem with an old project using Asp net framework 4.8.
We read and use the sample Mortis 
https://github.com/openiddict/openiddict-samples/tree/dev/samples/Mortis
as a base, but it didn't work :-(

When the user insert his credentials and perform the login, the redirect page isn't called and instead the browser prompt a basic auth window.

Here the configuration of the project in asp.net 4.8:

```
var services = new ServiceCollection();

app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = "Cookies"
});

services.AddOpenIddict()
.AddClient(options =>
{
    options.AllowAuthorizationCodeFlow()
        .AllowRefreshTokenFlow();
    options.AddDevelopmentEncryptionCertificate()
           .AddDevelopmentSigningCertificate();
    options.DisableTokenStorage();

    // Register the OWIN host and configure the OWIN-specific options.
    options.UseOwin()
           .EnableRedirectionEndpointPassthrough()
           .EnablePostLogoutRedirectionEndpointPassthrough()
            .SetCookieManager(new SystemWebCookieManager());

    options.UseSystemNetHttp()
           .SetProductInformation(typeof(Startup).Assembly);

    var issuer = new Uri(ConfigurationManager.AppSettings["OidcAuthority"], UriKind.Absolute);
    var config = new OpenIddictClientRegistration()
    {
        Issuer = issuer,
        ClientId = ConfigurationManager.AppSettings["OidcClientId"],
        Scopes = { Scopes.OpenId, Scopes.Profile, Scopes.OfflineAccess, Scopes.Email, Scopes.Roles, "my_app_scope" },

        // Note: to mitigate mix-up attacks, it's recommended to use a unique redirection endpoint
        // URI per provider, unless all the registered providers support returning a special "iss"
        // parameter containing their URL as part of authorization responses. For more information,
        // see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.4.
        RedirectUri = new Uri("/Account/PostOidcLogin", UriKind.Relative),
        PostLogoutRedirectUri = new Uri("/logout", UriKind.Relative)
    };
    //try also to manually provide the key to decrypt the token
    //config.TokenValidationParameters.IssuerSigningKeys = GetSigningKeys(ConfigurationManager.AppSettings["OidcAuthority"]).Result;
    config.ResponseTypes.Add("code");

    options.AddRegistration(config);
})
.AddValidation(options =>
    {
        // Note: the validation handler uses OpenID Connect discovery
        // to retrieve the address of the introspection endpoint.
        options.SetIssuer(new Uri(ConfigurationManager.AppSettings["OidcAuthority"], UriKind.Absolute));

        // Register the System.Net.Http integration.
        options.UseSystemNetHttp();

        options.UseOwin();

        // Configure the validation handler to use introspection and register the client
        // credentials used when communicating with the remote introspection endpoint.
        options.AddAudiences("api-resource");
        options.UseIntrospection()
            .SetClientId("api-resource")
            .SetClientSecret(<client-secret>);
    });

var builder = new ContainerBuilder();

<many registrations of services>

//HTTP context and other related stuff
//register FakeHttpContext when HttpContext is not available
builder.RegisterControllers(typeof(Startup).Assembly);
builder.RegisterApiControllers(typeof(Startup).Assembly);

builder.Populate(services);

var container = builder.Build();

app.UseAutofacLifetimeScopeInjector(container);

// Register the OpenIddict middleware.
app.UseMiddlewareFromContainer<OpenIddictClientOwinMiddleware>();

// Set the dependency resolver for Web API.
DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
GlobalConfiguration.Configuration.DependencyResolver = new AutofacWebApiDependencyResolver(container);
```

the login is performed as:

```
[AllowAnonymous]
public ActionResult Login(string returnUrl)
{
    var context = HttpContext.GetOwinContext();

    var properties = new AuthenticationProperties
    {
        // Only allow local return URLs to prevent open redirect attacks.
        RedirectUri = Url.IsLocalUrl(returnUrl) ? returnUrl : "/"
    };

    // Ask the OpenIddict client middleware to redirect the user agent to the identity provider.
    context.Authentication.Challenge(properties, OpenIddictClientOwinDefaults.AuthenticationType);
    return new EmptyResult();

}
```

Can you help us?
Thanks in advance

**Comment by kevinchalet** [comment]
Hey @lufo88ita,

> Thanks for your work. My company sponsered you through the account SCP-srl, I'm a member of it.
https://github.com/orgs/SCP-srl/people

Thanks a lot for sponsoring the project. Much appreciated 👍🏻 

> When the user insert his credentials and perform the login, the redirect page isn't called and instead the browser prompt a basic auth window.

Interesting. I'd say it's not something OpenIddict is responsible for. Did you enable basic authentication in your IIS settings?

On a related note, I fixed a bug that prevented the Mortis sample from being launched correctly: https://github.com/openiddict/openiddict-samples/pull/327

**Comment by lufo88ita** [comment]
Hi, 

No, we double-checked it and I confirm there isn't any reference to basic authentication in our project. Still prompt it, in fact it's strange. Maybe is a fallback of OWIN? But in our project the owin configuration is:
```
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = "Cookies"
});
```
I forgot to mention that our tokens are encrypted.

**Comment by kevinchalet** [comment]
> Maybe is a fallback of OWIN?

It's unlikely: the only thing that the OWIN cookies middleware does is converting 401 responses to a 302 redirection to the login page (which was inspired by ASP.NET 4.x's `FormsAuthenticationModule`, that does something similar)

Recent versions of OpenIddict disable both the redirection enforced by the OWIN cookies middleware and the one applied by `FormsAuthenticationModule`, so it's very likely unrelated.

> No, we double-checked it and I confirm there isn't any reference to basic authentication in our project.

These things are typically not configured in your project, but directly in IIS: https://learn.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/basicauthentication

Does the - unmodified - Mortis sample work for you or is it affected too?

**Comment by lufo88ita** [comment]
Hi,
> Does the - unmodified - Mortis sample work for you or is it affected too?

We try Mortis example (without modification) and it works fine. 
We retry our applications (and the authentication server) in development environment, so the client is using IIS express.

After login, when the server redirects back to the client application ( "/Account/PostOidcLogin" ) the client return a 401 and _then_ open the basic authentication. We don't understand why.

**Comment by kevinchalet** [comment]
Can you please share the implementation of that `/Account/PostOidcLogin` action?

**Comment by lufo88ita** [comment]
Hi,
We remove the annotation Authorize from the controller which contain PostOidcLogin and then the method is correctly called:
here is the full method (copied and adapted from the mortis example)
```
[AcceptVerbs("GET", "POST")]
public async Task<ActionResult> PostOidcLogin()
{
    var context = HttpContext.GetOwinContext();
    var result = await context.Authentication.AuthenticateAsync(OpenIddictClientOwinDefaults.AuthenticationType);

    var claimsIdentity = result.Identity as ClaimsIdentity;
    if (claimsIdentity == null)
    {
        throw new InvalidOperationException("The external authorization data cannot be used for authentication.");
    }

    if (!claimsIdentity.IsAuthenticated)
    {
        throw new InvalidOperationException("The external authorization data cannot be used for authentication.");
    }

    // Build an identity based on the external claims and that will be used to create the authentication cookie.
    //
    // By default, all claims extracted during the authorization dance are available. The claims collection stored
    // in the cookie can be filtered out or mapped to different names depending the claim name or its issuer.
    var claims = result.Identity.Claims.Where(claim => claim.Type == ClaimTypes.NameIdentifier
    || claim.Type == ClaimTypes.Name
    || claim.Type == Claims.Private.RegistrationId
    || claim.Type == Claims.Private.ProviderName
    || claim.Type == "http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider");

    var identity = new ClaimsIdentity(claims,
        authenticationType: CookieAuthenticationDefaults.AuthenticationType,
        nameType: ClaimTypes.Name,
        roleType: ClaimTypes.Role);

    // Build the authentication properties based on the properties that were added when the challenge was triggered.
    var properties = new AuthenticationProperties(result.Properties.Dictionary
        .Where(item => item.Key == ".redirect" 
        || item.Key == OpenIddictClientOwinConstants.Tokens.BackchannelAccessToken
        || item.Key == OpenIddictClientOwinConstants.Tokens.BackchannelIdentityToken
        || item.Key == OpenIddictClientOwinConstants.Tokens.RefreshToken)
        .ToDictionary(pair => pair.Key, pair => pair.Value));

    context.Authentication.SignIn(properties, identity);
    return Redirect(properties.RedirectUri ?? "/");
}
```

But we have got the following error:
"A grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options." at the following row

` var result = await context.Authentication.AuthenticateAsync(OpenIddictClientOwinDefaults.AuthenticationType);`

We try to solve the problem by adding the following configuration
`config.GrantTypes.Add("authorization_code");`

What is our mistake?

**Comment by kevinchalet** [comment]
> But we have got the following error:
> "A grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options." at the following row

You get this error when the request was not recognized as a callback request: in most cases, because the actual address differed from the endpoint URI enabled in the options (here, `/Account/PostOidcLogin`).

Do you use IIS virtual paths? What's the complete/exact URI?

**Comment by lufo88ita** [comment]
the full redirect url is
`https://localhost:44334/Account/PostOidcLogin`
We are in debug both with the client and the server

`Do you use IIS virtual paths?`
No.

We also try to replace in the configuration the relative url with the absolute kind:
`RedirectUri = new Uri("https://localhost:44334/Account/PostOidcLogin", UriKind.Absolute)`

but the error is the same

**Comment by kevinchalet** [comment]
Weird. What's the value of the `path` variable when you do `var path = context.Request.PathBase + context.Request.Path;`?

**Comment by lufo88ita** [comment]
Hi,

Shame on us. The redirect url was wrong, we forgot we have an internal redirect that add the segment "it-IT".
Now, we are successfully authorized but we don't have any user claims.
We guess we are missing another call to the userInfo endpoint server.
Is it correct?

**Comment by kevinchalet** [comment]
> Shame on us. The redirect url was wrong, we forgot we have an internal redirect that add the segment "it-IT".

Haha, no worries 👍🏻 

>  Now, we are successfully authorized but we don't have any user claims.
>  We guess we are missing another call to the userInfo endpoint server.

The userinfo request is sent for you by OpenIddict and all the claims it could resolve from the identity token (if applicable) and the userinfo response (if applicable) can be extracted from `result.Identity.Claims`.

OpenIddict doesn't do any filtering so if the collection doesn't contain any user claim, it's because your server didn't include any user claim in the identity token/userinfo response.

**Comment by lufo88ita** [comment]
Correct. We better check the Mortis example and understand how inject all claims into the user context.

recap our mistakes:
"PostOidcLogin" method was under "Authorize"
The redirect url was wrong (missing it-IT)
Finally, missing to get the filter to the user claims that was present in Mortis example.

Now all seems work.
Thanks.
Have a nice weekend.

**Comment by kevinchalet** [comment]
> Now all seems work.

Great to hear! 👍🏻 

Have a nice weekend too!
