### ISSUE TITLE
Can't get refresh token even with scope offline_access

### ISSUE THREAD

**Issue by dreampper** [openiddict/openiddict-core#214]
Hello, I have already enabled the AllowRefreshTokenFlow() and I'm sending the scope offline_access. However, the response JSON only contains, token_type, access_token and expires_in.

I have noticed a thing: my Action which leads with the authentication hadn't these two lines:

```
ticket.SetResources(request.GetResources());
ticket.SetScopes(request.GetScopes());
```

I think they are necessary so that the refresh token can be sent, right?

But when I add these lines on my code, I get the folling error from logging:

![print](https://cloud.githubusercontent.com/assets/21696161/18187570/1c096ac8-7081-11e6-94ff-352e6fbaba78.png)

Does someone know what is happening? I need some table in my database besides the Identity tables (AspNetUsers, AspNetRoles, ect)?

**Comment by kevinchalet** [comment]
> I think they are necessary so that the refresh token can be sent, right?

They are (at least, the `SetScopes` line, that defines the scopes granted to the client app': in this case, the scopes the client sends in the `scope` parameter).

> Does someone know what is happening? I need some table in my database besides the Identity tables (AspNetUsers, AspNetRoles, ect)?

Any chance you could share your DB context?

**Comment by dreampper** [comment]
That's my dbcontext

```
 public class ApplicationDbContext : OpenIddictDbContext<ApplicationUserOpenIddict, IdentityRole<int>, int>
    {
        public ApplicationDbContext(DbContextOptions options)
        : base(options)
        {
        }
}
```

**Comment by kevinchalet** [comment]
Hum, weird. What's the store you're using? In-memory? MS SQL? SQLite?

**Comment by dreampper** [comment]
I'm using MySQL. When i remove the SetScopes, It works, but the refresh_token is not returned.

**Comment by kevinchalet** [comment]
Can you please try with another store?

**Comment by dreampper** [comment]
I'll try with another database and as I do It, I report you. Do you think It's a problem with the MySQL connector or with the OpenIddict?

**Comment by kevinchalet** [comment]
I suspect a bug with MySQL (at least, with the EF Core integration), as this feature works fine with in-memory/MS SQL.

**Comment by dreampper** [comment]
My team can only use MySQL and PosrgreSQL, but I'll try with MS Server and PostgreSQL. When I make tests with them, I post here.

**Comment by dreampper** [comment]
Just to know, which tables are involved in this scenario? So I can open an issue in the MySQL forum too.

**Comment by dreampper** [comment]
I have tested with PostgreSQL and that's the result:

> relation "dbo.OpenIddictTokens" does not exist

Which are the necessary tables?
