### ISSUE TITLE
Possible bug: ClientId and Scope Name are not unique

### ISSUE THREAD

**Issue by nachoRSK** [openiddict/openiddict-core#2156]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.6.0

### Question

Hi, I don't know if this is a bug or if there is a reason for it. I have noticed that after running EF Core migrations, the ClientId and the Scope name columns are not constrained to be unique. Is there a reason for this?

I used the Velusia sample, but the one responsible for this seems to be the OpenIddictEFCore package.

**Comment by kevinchalet** [comment]
Hi @nachoRSK,

> I don't know if this is a bug or if there is a reason for it. I have noticed that after running EF Core migrations, the ClientId and the Scope name columns are not constrained to be unique. Is there a reason for this?

What provider are you using? I tried to reproduce that locally with SQLite and SQL Server but in both cases, the indexes seem to be correctly created:

SQLite:

```sql
CREATE UNIQUE INDEX "IX_OpenIddictApplications_ClientId" ON "OpenIddictApplications" ("ClientId")
```

```sql
CREATE UNIQUE INDEX "IX_OpenIddictScopes_Name" ON "OpenIddictScopes" ("Name")
```

SQL Server:

```sql
CREATE UNIQUE NONCLUSTERED INDEX [IX_OpenIddictApplications_ClientId]
    ON [dbo].[OpenIddictApplications]([ClientId] ASC) WHERE ([ClientId] IS NOT NULL);
```

```sql
CREATE UNIQUE NONCLUSTERED INDEX [IX_OpenIddictScopes_Name]
    ON [dbo].[OpenIddictScopes]([Name] ASC) WHERE ([Name] IS NOT NULL);
```

**Comment by nachoRSK** [comment]
I'm sorry; I was looking at the constraints all the time, and I missed the indexes. Many thanks for the quick response.

**Comment by kevinchalet** [comment]
No problem 😄
