### ISSUE TITLE
Token endpoint and locked account

### ISSUE THREAD

**Issue by Qszer94** [openiddict/openiddict-core#217]
Hi I have a problem with token endpoint. 
I created custom controller action for token endpoint like in readme.
I made few changes for account locking system:

```
                // IF PASSWORD NOT CORRECT
                if (!await _userManager.CheckPasswordAsync(user, request.Password))
                {
                    if (_userManager.SupportsUserLockout)
                    {
                        await _userManager.AccessFailedAsync(user);
                    }
                    var failedAttempts = await _userManager.GetAccessFailedCountAsync(user);
                    var passwordInvalid = new ErrorViewModel()
                    {
                        Error = "Invalid grant",
                        ErrorDescription = String.Format("Password incorrect!  {0} z 5 attempts.", failedAttempts )
                    };
                    return Json(passwordInvalid);
                }

                // IF ACCOUNT LOCKED
                if (!await _userManager.IsLockedOutAsync(user))
                {
                    var lockoutEndTime = await _userManager.GetLockoutEndDateAsync(user);

                    var accountLocked = new ErrorViewModel()
                    {
                        Error = "Invalid grant",
                        ErrorDescription = "Account locked! Wait " + lockoutEndTime.Value.Minute + "minutes."
                    };
                    return Json(accountLocked);
                }
```

Unless user reach limit of attempts all is fine, but when user account is locked server not hit my action.
I'm getting 400 (Bad Request), but it's not my response:

```
{
error:"invalid_grant"
error_description:"Account locked out."
}
```

**Comment by kevinchalet** [comment]
That's because OpenIddict makes a similar check internally, so a request never reaches your controller if the account is locked. I suppose we could remove it, but I'm not sure I'm a huge fan of that.

**Comment by Qszer94** [comment]
In my opinion Openiidict should check if request is valid and contains required params, also if params are valid. Locked accout or Two-factor authentication shouldn't be checked intenally, cause thats features of Identity and each user may want to customize it.

**Comment by jayrulez** [comment]
@PinpointTownes I have to agree with @Qszer94 here.

This check should be application logic and not library logic.

I know openiddict is just to make openidconnect more palatable for most devs but I think this has gone just 1 step too far in doing so.

**Comment by jayrulez** [comment]
@PinpointTownes I have to agree with @Qszer94 here.

This check should be application logic and not library logic.

I know openiddict is just to make openidconnect more palatable for most devs but I think this has gone just 1 step too far in doing so.

**Comment by kevinchalet** [comment]
Okay, I'm sold, let's remove the internal check. I'll work on that in the next few days.

**Comment by kevinchalet** [comment]
Fixed by https://github.com/openiddict/openiddict-core/issues/220.
