### ISSUE TITLE
Custom Claims and Stateless API Question

### ISSUE THREAD

**Issue by levitatejay** [openiddict/openiddict-core#218]
I've read that a common use for OpenID Connect is to have a stateless api by including custom claims in the ID token JWT. These claims can contain different information that can be used by the server for authorisation (such as "IsAdmin": false) without having to hold a session for each user or query the database on each request.

First I want to confirm I have the following information correct:
- Access tokens don't contain custom claims
- Access tokens are used to authenticate incoming requests with the "app.UseOAuthValidation();" in Startup
- ID tokens contain custom claims
- ID tokens have nothing to do with authentication... the server can't/doesn't do anything with them by default

If the above is correct then should I design something like the following for my stateless API?
- Users get both an access token and an ID token from auth endpoint
- All subsequent requests to the API have both the access and id tokens included in headers
- I write some middle-ware that runs after the authentication middle-ware. It will get the ID token from the request headers and parse the contained custom claims so they are ready to be used by the authorisation handlers.

Is this the normal way people are doing this? It seems a little overkill/redundant to use 2 different tokens in this scenario.

**Comment by kevinchalet** [comment]
> Access tokens don't contain custom claims

False. Access tokens can contain any claim you want.

> Access tokens are used to authenticate incoming requests with the "app.UseOAuthValidation();" in Startup

True.

> ID tokens contain custom claims

True (tho' it's generally recommended to use the standard claim names)

> ID tokens have nothing to do with authentication... the server can't/doesn't do anything with them by default

False... and true. While identity tokens can't be used for "API authentication", this doesn't mean they have nothing to do with authentication, as they are used by client apps' to determine who the user is. 

> Is this the normal way people are doing this? It seems a little overkill/redundant to use 2 different tokens in this scenario.

It is clearly an overkill. It's also wrong to send an identity token to the resource server (= API), since it's generally not listed a valid audience for these tokens.

I suppose your confusion comes from the fact you thought access tokens couldn't contain custom claims. But they can.

**Comment by levitatejay** [comment]
Thanks for the quick response!

I think I'm getting confused by something... 

In question: https://github.com/openiddict/openiddict-core/issues/165 you said:

> Claims are never returned as (non-standard) token response properties. Use the identity token instead.

Could you clarify what you meant here as that would seem to contradict what you just posted?

**Comment by kevinchalet** [comment]
> Could you clarify what you meant here as that would seem to contradict what you just posted?

`identity token claims` != `token response properties`.

As the name suggests, "identity token claims" are the claims stored inside an identity token. Token response properties are simply what you get when receiving a token response (e.g an access or an identity token, or the `expires_in` property):

``` json
{
  "access_token": "2YotnFZFEjr1zCsicMWpAA",
  "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOWdkazcifQ...",
  "token_type": "bearer",
  "expires_in": 3600,
  "custom_property": "value"
}
```

Unlike OpenID Connect (which is a recent spec), OAuth2 had no standard way to flow user attributes (like a user identifier) so it was quite common to use token response properties for that. With OpenID Connect, this part was standardized (user attributes are flowed as identity token claims).

While ASOS (the underlying OpenID Connect server framework behind OpenIddict) [allows you to return custom properties](http://stackoverflow.com/questions/34074787/overriding-tokenendpoint-in-aspnet-security-openidconnect-server) (even complex JSON objects), this is not something OpenIddict allows you to do, to encourage you to use the identity token.

**Comment by levitatejay** [comment]
Thank you, that has helped clear things up a lot.
