### ISSUE TITLE
Support for user registration - prompt=create

### ISSUE THREAD

**Issue by jhartmann123** [openiddict/openiddict-core#2185]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

`OpenIddictConstants.Prompts` currently does not support the value `create` used for initiating user registration.

Spec: https://openid.net/specs/openid-connect-prompt-create-1_0.html

As it looks like on a first glance, the `Prompts`-class is just missing the value, as the rest is basically a normal authorization / login flow.

**Comment by kevinchalet** [comment]
Hey,

Enhancement suggestions are reserved to sponsors but I liked the idea and decided to implement the complete specification in OpenIddict 6.0: https://github.com/openiddict/openiddict-core/pull/2197.

**Comment by jhartmann123** [comment]
Oh, sorry, I was sure my company sponsored you the last ~1.5 years, but looking at the GitHub sponsors it doesn't look like that. I'll look into that.

Thanks for implementing that feature anyway! 💯
