### ISSUE TITLE
Can not find Controller or View for Account/Register and Account/Login for Velusia server

### ISSUE THREAD

**Issue by TanPM91** [openiddict/openiddict-core#2189]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

latest

### Question

Im trying make SSO provider for my website like google / facebook login provider and Im following up the code in file _LoginPartial and see 2 routes like

>       <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
>       <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>

But i cannot find the View and Controller file of Account/Register and  Account/Login

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
