### ISSUE TITLE
Guidance on how to use Dev Tunnels/Ngrok with OpenIddict WebProviders - ADFS

### ISSUE THREAD

**Issue by gentledepp** [openiddict/openiddict-core#2202]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.6.0

### Question

Technically: As no PR of mine is merged as of yet - am I a contributor?
If not - you can ignore me.

Otherwise:

I am sure this affects many developers, therefore I would love to see some guidance on how to use Openiddict with MS Dev Tunnels or ngrok.

The reason being, that when using the sample in #2201, the login works as long as I use `https://localhost:44349`

As soon as I enable the dev tunnel, the problem is that we call the `Account/ExternalLogin` endpoint using the dev-tunnel fqdn
![image](https://github.com/user-attachments/assets/2dd9c74d-50c1-4882-9bb2-af1bc5fcd123)

Therefore, the cookie `OpenIddict.Client.State.***` has this domain set too.

Now, as soon as ADFS redirects back, it does so redirecting to `https://localhost:44349`
![image](https://github.com/user-attachments/assets/77928284-60d8-4116-96af-9b8744455bcc)
and because of that, the cookie is not provided.

Now this is becasue the redirecturi is specified relatively:
![image](https://github.com/user-attachments/assets/0ca064cf-2800-4a95-b3b2-d87b4410e992)

If I now set it to a FQDN (the dev tunnel url)
![image](https://github.com/user-attachments/assets/650fd4aa-ffe5-4b9b-a9da-8486e554b65a)

then I _do_ get the cookie provided
![image](https://github.com/user-attachments/assets/d2690964-ac29-46e3-9bb6-1ce4d6a78eb8)

**but** openiddict fails to detect the `OpenIddictClientEndpointType` and threfore throws in the `ValidateAuthenticationDemand` handler
![image](https://github.com/user-attachments/assets/c0cf5d4a-fa51-473e-86f0-cd1a196b4ace)

This is because of the nature of MS Dev tunnels: They just redirect to your server running on localhost.
For that reason, the `InferEndpointType` handler cannot figure out the type, since it matches the fully qualified redirectentpoint URI of the dev tunnel to localhost:

![image](https://github.com/user-attachments/assets/a673ced2-e219-48f4-9201-482e3e777502)

So what is the best option to overcome this?

Btw: I would include this into my "dev tunnel" guide in the docs page of openiddict of course.

**Comment by gentledepp** [comment]
So... I found the solution to this.

The problem, as I already wrote, is, that the MS Dev Tunnel does not forward the tunnel's domain.
Therefore, even though we initiate the login request using tunnel domain, the cookie is set for that domain, but the callback from microsoft is returned to https://localhost:44349, causin the cookie to be missing.

The solution therefore is to configure the Microsoft Dev Tunnel to use the tunnel domain (forwarding the host header to iis/kestrel)

Open tunnel view
![image](https://github.com/user-attachments/assets/5b0617fb-7afd-4677-8a64-e80b88cdd0e0)


Select settings of your tunnel and check the "use tunnel domain" for your https port (44349) in our case:
![image](https://github.com/user-attachments/assets/f3451bb7-5bfa-484e-a86b-d7fd32cdbe28)

This will cause you to get an error with IIS Express
![image](https://github.com/user-attachments/assets/6d92d83b-8b06-4c28-84d8-24a3d7170592)

... so you need to add a binding for that host name in the applicationhost.config:

```diff

   <bindings>
        <binding protocol="http" bindingInformation="*:55946:localhost" />
+         <!-- accept any host header -->
+        <binding protocol="https" bindingInformation="*:44349:*" /> 
        <binding protocol="https" bindingInformation="*:44349:localhost" />
    </bindings>

```

or if you want to be more specific:

```diff

   <bindings>
        <binding protocol="http" bindingInformation="*:55946:localhost" />
+         <!-- accept any host header -->
+        <binding protocol="https" bindingInformation="*:44349:vsr1d2md-44349.euw.devtunnels.ms" /> 
        <binding protocol="https" bindingInformation="*:44349:localhost" />
    </bindings>

```

**Comment by gentledepp** [comment]
I will create a PR on the documentation site for this.

**Comment by kevinchalet** [comment]
You got it right, it's indeed caused by the fact the `Host` header isn't preserved by default (which is stupid, IMHO), which not only affects OpenIddict, but basically any ASP.NET Core component relying on `HttpRequest.Scheme` or `HttpRequest.Host`.

> I will create a PR on the documentation site for this.

Thanks!
