### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by gentledepp** [openiddict/openiddict-core#2203]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Improved error messages - more details.

When trying to get `ActiveDirectoryFederationServices` to work (see #2201), I got an error response from Azure Entry ID because of some configuration error.

The sever response from OpenIddict was:

> error:invalid_request
> error_description:No correlation cookie associated with the specified state can be found. Please try logging in again. If the error persists, please contact the website owner.
> error_uri:https://documentation.openiddict.com/errors/ID2129 

This response 
- does not give any hint on the actual issue 
- and the error uri points to a 404

However, as I was debugging the source, I could look into the `HandleErrorResponse` handler, that throws this issue, does have much more information available:

> context.Response.Error= "invalid_request"
> context.Response.ErrorDescription = "AADSTS50146: This application is required to be configured with an application-specific signing key. It is either not configured with one, or the key has expired or is not yet valid. Trace ID: 314a447a-2aae-43f4-a745-b19f5e587e00 Correlation ID: dee29343-fe83-4c4b-9f61-591f1f30d286 Timestamp: 2024-10-08 08:45:10Z"
> context.Response.ErrorUri = "https://login.microsoftonline.com/error?code=50146"

So, why exactly are those informations
 - [ ] neither returned in the error response
 - [ ] nor logged?
 
The handler could be improved to include all error details if present:
 ```diff
/// <inheritdoc/>
public ValueTask HandleAsync(HandleTokenResponseContext context)
{
    if (context is null)
    {
        throw new ArgumentNullException(nameof(context));
    }

    // For more information, see https://datatracker.ietf.org/doc/html/rfc6749#section-5.2.
    if (!string.IsNullOrEmpty(context.Response.Error))
    {
        context.Logger.LogInformation(SR.GetResourceString(SR.ID6206), context.Response);

+        if (context.Response.ErrorDescription != null)
+            context.Logger.LogInformation(context.Response.ErrorDescription, context.Response);
+        if (context.Response.ErrorUri != null)
+            context.Logger.LogInformation(context.Response.ErrorUri, context.Response);


+        var b = new System.Text.StringBuilder();
+        b.AppendLine(SR.GetResourceString(SR.ID2147));
+        if(context.Response.ErrorDescription != null)
+            b.AppendLine(context.Response.ErrorDescription);
+        if (context.Response.ErrorUri != null)
+            b.AppendLine(context.Response.ErrorUri);

        context.Reject(
            error: context.Response.Error switch
            {
                Errors.AccessDenied         => Errors.AccessDenied,
                Errors.AuthorizationPending => Errors.AuthorizationPending,
                Errors.ExpiredToken         => Errors.ExpiredToken,
                Errors.InvalidClient        => Errors.InvalidClient,
                Errors.InvalidGrant         => Errors.InvalidGrant,
                Errors.InvalidScope         => Errors.InvalidScope,
                Errors.InvalidRequest       => Errors.InvalidRequest,
                Errors.SlowDown             => Errors.SlowDown,
                Errors.UnauthorizedClient   => Errors.UnauthorizedClient,
                Errors.UnsupportedGrantType => Errors.UnsupportedGrantType,
                _                           => Errors.ServerError
            },
+            description: b.ToString(),
            uri: SR.FormatID8000(SR.ID2147));

        return default;
    }

    return default;
}

```
 
Is this
 - [ ] because of some security risk (i do not see one)
 - [ ] because of performance response (they do have to be very compelling to omit this valuable information)
 - [ ] or because the standard says so? (in which case I would start doubting the standard 👀)
 - [ ] or because it was simply not yet implemented 🚀

**Comment by kevinchalet** [comment]
> When trying to get `ActiveDirectoryFederationServices` to work (see #2201), I got an error response from Azure Entry ID because of some configuration error.

Well, you're not supposed to use that provider with Entra ID: ADFS is an on-premise solution that doesn't have a lot in common with Azure AD/Entra ID 😄

> So, why exactly are those informations neither returned in the error response

Not flowing the error details is actually 100% deliberate: it's generally not a huge deal for authorization responses (since the details are usually attached in the query string/request form unencrypted), but it's a lot more problematic for things like token responses, that can contain PII or security-sensitive stuff.

Also, we generally try to avoid reflecting values users can set in error details, as it can be used to display offensive messages or be used for phishing campaigns.

> nor logged?

The entire authorization response - including the error details - is already logged when extracting it:

```
OpenIddict.Client.OpenIddictClientDispatcher: Information: The redirection request was successfully extracted: {
  "error": "access_denied",
  "state": "r39jf920C17tUvp59S0aWpIojSe3WB-ugry_PMn1Aig"
}.
```

**Comment by gentledepp** [comment]
> The entire authorization response - including the error details - is already logged when extracting it:
> 
> ```
> OpenIddict.Client.OpenIddictClientDispatcher: Information: The redirection request was successfully extracted: {
>   "error": "access_denied",
>   "state": "r39jf920C17tUvp59S0aWpIojSe3WB-ugry_PMn1Aig"
> }.
> ```

I am missing this part:

>AADSTS50146: This application is required to be configured with an application-specific signing key. It is either not configured with one, or the key has expired or is not yet valid. Trace ID: 314a447a-2aae-43f4-a745-b19f5e587e00 Correlation ID: dee29343-fe83-4c4b-9f61-591f1f30d286 Timestamp: 2024-10-08 08:45:10Z 
(from `context.Response.ErrorDescription`)

and that one 
> "https://login.microsoftonline.com/error?code=50146" 
(from `context.Response.ErrorUri`)


> Well, you're not supposed to use that provider with Entra ID: ADFS is an on-premise solution that doesn't have a lot in common with Azure AD/Entra ID 

Too bad. I need to migrate an asp.net mvc project that uses 
`Microsoft.Owin.Security.WsFederation` `UseWsFederationAuthentication` 😣
I thought based on the name, this should be ok ;-)

But ok, i will check how to switch to Entra Id then

**Comment by kevinchalet** [comment]
> I am missing this part:

All the parameters should be present (they aren't in the snippet I shared because I used Twitter to test it and it doesn't return a description/URI).

> But ok, i will check how to switch to Entra Id then

Use the Microsoft provider.

**Comment by kevinchalet** [comment]
Oh wait, your issue was at the token request phase, not the authorization response. In this case, the whole response should be logged too. Here's what I'm getting with GitHub when using an invalid client secret:

```
OpenIddict.Client.OpenIddictClientDispatcher: Information: The token request was rejected by the remote authorization server: {
  "error": "incorrect_client_credentials",
  "error_description": "The client_id and/or client_secret passed are incorrect.",
  "error_uri": "https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#incorrect-client-credentials"
}.
```

**Comment by gentledepp** [comment]
Can you please just let me know one more thing?
- where exactly do I find the logs (only in the console, right?)
- and is there a possibility to add a correlation id?

I now realize, that most of the logging needs to be on the server side.
But if we do have issues with a customer trying to authenticate a new client (as an example), I would like to be able to provide the exact logs of this failed attempt.
Is anything like this planend?
May I contribute something like it?
