### ISSUE TITLE
Response of userinfo endpoint

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#221]
Should the userinfo endoint not return 401 when the access token expires rather than a 400?

The example here: http://openid.net/specs/openid-connect-core-1_0.html#UserInfoError

shows 401.

This also supports 401:

http://www.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.wlp.nd.doc/ae/twlp_oidc_userinfo_endpoint.html

**Comment by kevinchalet** [comment]
That's deliberate.

There are currently a bunch of bugs in both the OWIN/Katana and ASP.NET Core security stacks that makes returning a 401 response from an authentication middleware a real trap (e.g https://github.com/aspnet/Security/issues/930). Due to this bug, a 401 response might be intercepted by another middleware (e.g one of the cookies middleware registered by ASP.NET Core Identity) and replaced by a 302 response redirecting the user agent to the login endpoint.

Returning a 400 response is not ideal (because it's not spec-compliant), but it's likely better than a redirection.

**Comment by jayrulez** [comment]
Ah I see. I hope this will get resolved sooner than later.

I guess I'll need to hack around this for now.

I want to do automatic token refreshing in my client. 

Is is safe to rely on the presence of "Expired token" in the response content to signify that the token has expired. Do you imagine any situation in which you would change this text?

I don't want the refresh token code to run on every bad request so I need to limit it to just unauthorized requests:

```
    public async Task<HttpResponseMessage> RequestAsync(HttpOptions options)
    {
        options.Url = GetAbsoluteUrl(options.Url);

        if (options.Headers == null)
        {
            options.Headers = new Dictionary<string, string>();
        }

        // get access token stored on the client
        var accessToken = this.GetAccessToken();

        if (!string.IsNullOrEmpty(accessToken))
        {
            Log.Debug(LOG_TAG, $"Adding 'Authorization' header 'Bearer {accessToken}'");

            options.Headers.Add("Authorization", $"Bearer {accessToken}");
        }

        var response = await this.HttpUtility.RequestAsync(options);

        var responseText = await response.Content.ReadAsStringAsync();

        // Is it safe to to do this @PinpointTownes ?
        if (response.StatusCode == HttpStatusCode.BadRequest && responseText.Contains("Expired token"))
        {
            Log.Debug(LOG_TAG, $"Unauthorized request. Access token may have expired.");

            lock (this)
            {
                // get refresh token stored on client
                var refreshToken = this.GetRefreshToken();

                if (!string.IsNullOrEmpty(refreshToken))
                {
                    try
                    {
                        Log.Debug(LOG_TAG, $"Attempting to refresh the access token.");
                        // try to refresh token, stores new access and refresh tokens on client if successful
                        this.RefreshTokenAsync().RunSynchronously();
                    }
                    catch (Exception ex)
                    {
                        Log.Debug(LOG_TAG, ex.Message);
                        // unauthorized request and token could not be refreshed successfully
                        // try to logout user from server and remove tokens stored on the client
                        this.SignoutAsync().RunSynchronously();
                    }
                }
            }

            // gets access token stored on client
            accessToken = this.GetAccessToken();

            if (!string.IsNullOrEmpty(accessToken))
            {
                Log.Debug(LOG_TAG, $"Retrying the request with 'Authorization' header 'Bearer {accessToken}'.");

                options.Headers["Authorization"] = $"Bearer {accessToken}";

                return await this.HttpUtility.RequestAsync(options);
            }
        }

        return response;
    }
```

**Comment by kevinchalet** [comment]
> Ah I see. I hope this will get resolved sooner than later.

Unfortunately, it's not a bug I can work around, so it entirely depends on the goodwill of the ASP.NET team (it was already super hard to convince them this was a bug...). And AFAICT, it doesn't seem to be a high priority item for them.

> Is is safe to rely on the presence of "Expired token" in the response content to signify that the token has expired. Do you imagine any situation in which you would change this text?

This bug only affects 401 responses that would be normally returned by an authentication middleware like ASOS/OpenIddict, so it doesn't affect your own APIs (protected either by the JWT middleware or by the validation middleware) as long as you use `[Authorize(ActiveAuthenticationSchemes = "Bearer")]` or update the default authorization policy to only trigger the JWT/validation middleware.

In practice, this only affects token, userinfo, introspection and revocation requests, where ASOS will always return a 400 response when a 401 one should be returned (e.g when the access token is expired or when client authentication is incorrect).

That said, I don't understand why you're using the userinfo endpoint for that. In practice, you only query it after an authentication flow so the chances of getting an "expired token" error are extremely low (it's even almost impossible).

**Comment by jayrulez** [comment]
I see. So it's not big of an issue in my case then.

I was calling the userinfo endpoint on the splash screen so the token would be refreshed if it expired. This could be any secured endpoint really.
