### ISSUE TITLE
jwks_uri metadata entry openid connect

### ISSUE THREAD

**Issue by Cooltisch** [openiddict/openiddict-core#2212]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.8.0

### Question

I have already seen some tickets that deal with the problem that the jwks_uri url is different from the other endpoints.
Unfortunately only for versions older than version 5
My metadata output is as follows:

“issuer": ‘https://localhost:5017/’,
    “token_endpoint": ‘https://localhost:5017/test/openiddictservice/connect/token’,
    “revocation_endpoint": ‘https://localhost:5017/test/openiddictservice/connect/revoke’,
    “jwks_uri": ‘https://localhost:5017/.well-known/jwks’,

How can I ensure that the jwks_uri also works with the output 
https://localhost:5017/test/openiddictservice/.well-known/jwks as well.
Normally the service runs behind an Azure Application Gateway instance and I have the same problem there.

.Net Code 
            options.SetTokenEndpointUris(new Uri($"/test/openiddictservice/connect/token", UriKind.Relative))
                    .SetRevocationEndpointUris(new Uri($"/test/openiddictservice/connect/revoke", UriKind.Relative))
                    .SetConfigurationEndpointUris(new Uri($"/test/openiddictservice/.well-known/openid-configuration", UriKind.Relative));

br Holger

**Comment by kevinchalet** [comment]
Hey @Cooltisch,

Thanks a lot for sponsoring the project, much appreciated! ❤️ 

> How can I ensure that the jwks_uri also works with the output
https://localhost:5017/test/openiddictservice/.well-known/jwks as well.

Assuming I got your question right, you can customize the JWKS URI using `options.SetCryptographyEndpointUris(...)`.

It's worth noting this method (and the endpoint itself) was renamed to `options.SetJsonWebKeySetEndpointUris(...)` in OpenIddict 6.0 preview 1 to make things easier for new users: https://github.com/openiddict/openiddict-core/releases/tag/6.0.0-preview1.

Hope it'll help!

Cheers.

**Comment by Cooltisch** [comment]
Hi Kevin
thanks the service is running now correctly.

br Holger

**Comment by kevinchalet** [comment]
Doing some housecleaning, but please don't hesitate to reopen if you have any other question 😃 

All the best.
