### ISSUE TITLE
How to sign user out from a single web provider

### ISSUE THREAD

**Issue by corentinbst** [openiddict/openiddict-core#2213]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.8.0 (latest)

### Question

I'm currently in the process of putting together an authentication server using OpenIddict (which is fantastic btw). Basically, users cannot sign up and are not registered with their email or anything. The app's admins register the users themselves with a login (say, "jsmith" for the sake of example). The admins themselves also setup the federated identities: for instance, if they want a specific user to be able to sign-in with Google, they have to enable Google SSO for their organization and then bind an email to the internal user.

Currently I'm supporting three different authentication methods: Google, Microsoft/Entra and an internal scheme which authenticates the users using their admin-assigned usernames and their own password (stored & hashed using Argon2).
Because of the constraints I previously mentioned, I chose not to use ASP .NET Core Identity. And so when the user requests an authorization (to the /authorize endpoint) which challenges him to login if he's not already, he is then redirected to the main login page which prompts him to choose between either Google, MS or username+password.

So far so good, everything works very well except for one use-case. When the user logs in using a federated identity (say Google), I include email in the scopes and then do a database lookup to find the user linked to that google email account. If I cannot find it, I redirect the user to a page which tells me that no account is bound to his email with a button to go back to the main login page. At this point, what I want to do is sign him out of Google; otherwise, when he clicks on Google again (maybe he used the wrong account) he is automatically authenticated and redirected again to the failure page.

I tried to do it by creating an endpoint that my "redirect to main login page" would point to. What this endpoint does is very simple:
```C#
[HttpGet("logout/federated")]
public SignOutResult LogoutFederated(string? returnUrl, string provider) => SignOut(new AuthenticationProperties
{
    RedirectUri = returnUrl
}, provider);
```
In my tests, the `provider` is set to the constant `Providers.Google` from OpenIddict because I'm mostly testing using my Google account. Do note that the redirection probably won't work but that's not the issue. I also tried with `await HttpContext.SignOutAsync` and then redirecting ; i could probably solve that myself. The issue is that, in any case, I get an exception related to the fact that I cannot sign-out from this endpoint. I can't figure it out and the reason for it not working is completely alien to me. Besides, it's extremely hard to solve by searching or even reading the source (source generation and everything else makes it very opaque, for me at least).

The rest is pretty standard, Google is configured with `AddGoogle`, a client id, a client secret and a proper callback url where I retrieve the Google email and sign-in the user using a cookie scheme which is the default and only registered cookie scheme. Or if the email is not bound as I said, I redirect the user to the previously mentioned page and the button to disconnect from the current federated provider & return to the main login page.

As a matter of fact my authorization code and logic is extremely similar to your "Dantooine" sample which was of a huge help to me. My project is a MVC ASP .NET Core web app. The differences are of course the base authentication logic and the fact that my authentication server is also an OpenIddict client in order to use federated providers.

Of course, I can provide more info if required. Thanks in advance, your help would mean a lot.

**Comment by kevinchalet** [comment]
Hi,

> At this point, what I want to do is sign him out of Google; otherwise, when he clicks on Google again (maybe he used the wrong account) he is automatically authenticated and redirected again to the failure page.

You can't: Google doesn't offer an end session endpoint for relying-party-initiated logouts (I guess they don't want to allow third-party clients to log users out of all their services?).

> The issue is that, in any case, I get an exception related to the fact that I cannot sign-out from this endpoint. I can't figure it out and the reason for it not working is completely alien to me.

You can trigger sign-out operations from any endpoint so it's way more likely you were instead getting this error:

```InvalidOperationException: The 'end_session_endpoint' cannot be resolved from the authorization server configuration or doesn't represent a valid absolute URI, which may indicate this endpoint is not supported or is not enabled in the server configuration.```

... which basically tells you it's not a feature supported by the provider.

With a provider that offers an end session endpoint, triggering a logout is very easy:

https://github.com/openiddict/openiddict-core/blob/319511fa6dacaa9fa3793405fda102bebcba0079/sandbox/OpenIddict.Sandbox.AspNetCore.Client/Controllers/AuthenticationController.cs#L73-L119

So, it's basically a dead end.

That said, you can approach the problem differently by using the `prompt` authorization parameter: the value `select_account` should do what you need. You can attach it to the `AuthenticationProperties` you create when doing the challenge:

```csharp
var properties = new AuthenticationProperties(new Dictionary<string, string>
{
    // Note: when only one client is registered in the client options,
    // specifying the issuer URI or the provider name is not required.
    [OpenIddictClientAspNetCoreConstants.Properties.ProviderName] = provider,
})
{
    // Only allow local return URLs to prevent open redirect attacks.
    RedirectUri = Url.IsLocalUrl(returnUrl) ? returnUrl : "/"
};

// Note: the "PromptValues" was named "Prompts" in OpenIddict 5.x.
properties.SetParameter(Parameters.Prompt, PromptValues.SelectAccount);

// Ask the OpenIddict client middleware to redirect the user agent to the identity provider.
return Challenge(properties, OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
```

Hope it'll help.

**Comment by corentinbst** [comment]
Hi Kévin,

Yes that was the exact error. I got confused and I thought that the error message was talking about **my** server, which doesn't make sense now that you mention it since in this configuration OpenIddict is acting as a client. What I wanted to do was to sign-out the user not from Google altogether but rather "dissociate" his current Google account from my auth server in order to present him with the same screen he is shown when he logs in using Google for the first time (on my server).

I also thought about the solution you mentioned, initally I wanted to try with `prompt=login` but `select_account` might be closer to what I need. I'll try it when I get some time. I will probably need to pass a query parameter along with the return url so that the user isn't asked to select his account if he's already logged in with Google using an email address that's bound to an internal account.

A few things while I'm at it.

- In the last bit of code you put in your reply, am I correct in assuming that it's a bit old and that it's now possible to directly challenge `Providers.Google` instead of putting the provider in the properties? That's what I did at least and it seems to work, although perhaps it's not the correct way to do it?

- As well, I read that OpenIddict's client is **stateful** but it means that the state is persisted in database, not in memory right? I intend to host my authorization server in Google Cloud Run which as you probably know is serverless.

**Comment by kevinchalet** [comment]
> I also thought about the solution you mentioned, initally I wanted to try with prompt=login but select_account might be closer to what I need. I'll try it when I get some time.

👍🏻 

> In the last bit of code you put in your reply, am I correct in assuming that it's a bit old and that it's now possible to directly challenge Providers.Google instead of putting the provider in the properties? That's what I did at least and it seems to work, although perhaps it's not the correct way to do it?

Both options work and are fully supported: https://documentation.openiddict.com/integrations/aspnet-core#authentication-scheme-forwarding 😃 

> As well, I read that OpenIddict's client is stateful but it means that the state is persisted in database, not in memory right? I intend to host my authorization server in Google Cloud Run which as you probably know is serverless.

Right: you'll need to ensure all your "instances" have access to the same crypto material (signing and encryption keys) and the same database, where state tokens will be persisted.

Cheers.

**Comment by kevinchalet** [comment]
Doing some housecleaning, but feel free to reopen if you still have questions 😃
