### ISSUE TITLE
How to allows a service to both authenticate tokens it issues itself and authenticate tokens from another service on a different port?

### ISSUE THREAD

**Issue by kieuvo96** [openiddict/openiddict-core#2219]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.3.0

### Question

I'm trying config like this but it not working. 
services.AddOpenIddict()
.AddValidation(options =>
{
options.UseLocalServer();
options.EnableAuthorizationEntryValidation();

  options.SetIssuer("https://localhost:7226/");
  options.AddEncryptionKey(new SymmetricSecurityKey(
       Convert.FromBase64String(Configuration["OpenIddict:EncryptionKey"] ?? string.Empty)));
  options.UseSystemNetHttp();

  options.UseAspNetCore();
});

**Comment by kevinchalet** [comment]
Hey,

GitHub didn't recognize you as a sponsor. Did you sponsor the project using a different/corporate account?

Cheers.

**Comment by kieuvo96** [comment]
No, I didn't. But I want to ask for my problem, where can I create question?
Thanks!

**Comment by kevinchalet** [comment]
You can post your question on a community-driven platform like StackOverflow: https://stackoverflow.com/questions/tagged/openiddict.
