### ISSUE TITLE
2FA support?

### ISSUE THREAD

**Issue by norcis** [openiddict/openiddict-core#222]
Hello,

I'm creating rest api and first party native mobile app which will consume it. To authorize API access and authenticate users I want to implement OpenId Connect with 2FA. 

It would look like this: 

1) in the app, user enters his username/password or use Facebook/Google etc.
2) if it's validated, server send SMS with shared secret to customer associated phone number.
3) clients enters PIN code received by SMS in the app. This pin could be passed to server to get token or maybe it should be stored in app and used for signing future requests. I'm not sure which flow should be used in such case.

Any recommendations how to do that with openiddict?

**Comment by kevinchalet** [comment]
Hey.

2FA is supported with interactive flows like code or implicit for a simple reason: OpenIddict doesn't handle the authentication part, which is something you must implement yourself. In practice, this is often handled using the `AccountController` that comes with the default template when you select individual authentication (it uses ASP.NET Core Identity under the hood).

If you need more information about Identity's 2FA functionalities, consider opening a new ticket here: https://github.com/aspnet/Identity/issues.
