### ISSUE TITLE
UseQuartz throw error MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

### ISSUE THREAD

**Issue by wangyuzhu** [openiddict/openiddict-core#2229]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

OpenIddict.Quartz 5.8.0

### Describe the bug

 builder.Services.AddOpenIddict()
     .AddCore(options =>
     {
         options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
         options.UseQuartz();
     })；

UseQuartz  throw error   >>>>>>>>>>>>>>>>>  This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

### To reproduce

 builder.Services.AddOpenIddict()
     .AddCore(options =>
     {
         options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
         options.UseQuartz();
     })；

UseQuartz  throw error   >>>>>>>>>>>>>>>>>  This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

DELETE `o`
FROM `OpenIddictTokens` AS `o`
WHERE `o`.`Id` IN (
    SELECT `o0`.`Id`
    FROM `OpenIddictTokens` AS `o0`
    LEFT JOIN `OpenIddictAuthorizations` AS `o1` ON `o0`.`AuthorizationId` = `o1`.`Id`
    WHERE (`o0`.`CreationDate` < @__date_0) AND (((((`o0`.`Status` <> 'inactive') OR `o0`.`Status` IS NULL) AND ((`o0`.`Status` <> 'valid') OR `o0`.`Status` IS NULL)) OR (`o1`.`Id` IS NOT NULL AND ((`o1`.`Status` <> 'valid') OR `o1`.`Status` IS NULL))) OR (`o0`.`ExpirationDate` < UTC_TIMESTAMP()))
    ORDER BY `o0`.`Id`
    LIMIT @__p_1
)

**Comment by hosamyousof** [comment]
@kevinchalet Since MySQL cleanup tasks aren't planned for support, could you provide guidance on how I can manually handle these cleanup operations?

**Comment by jeroenbai** [comment]
Workaround: DisableBulkOperations. https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1903#issuecomment-2377309644

```
builder.Services.AddOpenIddict()

  .AddCore(options =>
  {
      options.UseEntityFrameworkCore()
          .DisableBulkOperations()
          .UseDbContext<OpendIdDictContext>();
  });
```
