### ISSUE TITLE
I want to send custom parameter from openiddict server to angular application

### ISSUE THREAD

**Issue by MinaKevin** [openiddict/openiddict-core#2231]
### Personal contribution

- [X] I'm not interested in submitting a pull request and understand that this provider may not be fixed in the near future without my contribution.

### Version

5.7

### Provider name

OpenIddict

### Describe the bug

I want to send custom parameter from openiddict server to angular application such as language but I don't set it user token 

### To reproduce

-

**Comment by kevinchalet** [comment]
Hi,

The issue template you selected is exclusively for reporting issues affecting an OAuth 2.0/OIDC social/enterprise provider integration that is part of the `OpenIddict.Client.WebIntegration` package. Unfortunately, your question is unrelated.

For general support, please consider sponsoring the project. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!

**Comment by MinaKevin** [comment]
I ask about question can send parameter from openiddict server to angular application . I use oauth grant type code with pkce 
and I don't know where I log my question?
