### ISSUE TITLE
How to get OpenIddict to recognise incoming https requests (k8s/nginx)

### ISSUE THREAD

**Issue by freever** [openiddict/openiddict-core#2235]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.8.0

### Question

I have been battling with this one for almost a week, and am at wits end. I have an OpenIddict auth server set up to run inside a kubernetes cluster behind NGINX. I have been trying without success to get OpenIddict to work in this environment but continually get stuck in some or other manifestation of https request processing. Essentially, https requests from outside end up being seen as http inisde.

There are numerous other issues here and elsewhere that discuss this and all appear to agree on one thing: asp.net core must be set up correctly to allow the relevant headers through so that the scheme is inferred correctly throughout. 

So, right after 
```app = builder.Build()```

I have 
```
app.Use(async (context, next) =>
{
    Console.Out.WriteLine("______ FIRST MIDDLEWARE ______");
    await next();
});
app.UseForwardedHeaders(k8sConfig);
```
This works, up to a point. If I create a simple "MapGet" endpoint the logs tell me that there are no ForwardedHeader warnings (there had been before I got the k8sConfig right) and the middleware pipeline kicks in and HttpContext.Request.Scheme is correctly seen as https:
![image](https://github.com/user-attachments/assets/ddf19156-9f80-4888-b67e-e1641b47fd0c)

However, when any calls come in relating to OpenIddict, for example getting the openid-configutation document, the line "______ FIRST MIDDLEWARE ______" does not appear anywhere in the logs, and the request is seen as http all the way through, and the document therefore ends up with the incorrect http urls. From this I infer that the UseForwardedHeaders middleware is also not being invoked and thus does not appear to be a solution to the problems I am experiencing. 

As a workaround, I have been able to force the correct scheme by intercepting the request:
```

                    options.AddEventHandler<ProcessRequestContext>(builder =>
                    {
                        builder.UseInlineHandler(async context =>
                        {
                            context.BaseUri = new Uri(configuration.GetAuthority());
                            await Task.CompletedTask;
                        });
                    }); 
```

This also works, up to a point, and I can authenticate using postman's auth code flow. But further problems surface later which makes me think my workaround is flimsy. 

What I really want is to get the problem fixed at source, which is to get the correct request scheme recognised by the OpenIddict processes - and it seems I have no way to insert any middleware into the pipeline _before_ OpenIddict kicks in. Even in a simple MapGet situation my request pipeline shows OpenIddict executing code before the very first middleware I am able to execute, so I don't understand even conceptually how I would configure ASP.net to play nicely with OpenIddict if the only way I have to influence ASP.net (middleware) only gets called once OpenIddict is finished processing. 

Any help would be appreciated at this point.

**Comment by freever** [comment]
I have actually managed to get it working eventually... the https thing was a red herring; the real problem was the size of the headers causing a 502 error...

**Comment by kevinchalet** [comment]
Glad you sorted it out!

It's hard to say what's going on exactly without seeing the complete app pipeline, but here's a few remarks:
  - OpenIddict integrates to the ASP.NET Core pipeline using an `IAuthenticationRequestHandler` so it's invoked at the exact moment the ASP.NET Core authentication middleware executes.
  - The default web host registers the authentication middleware for you, but if you register it manually in your code, it will detect it and won't register it twice.
  - The default web host registers the forwarded headers middleware for you using an `IStartupFilter`, so you could just amend the default options via the DI container instead of calling `app.UseForwardedHeaders(...)`: https://github.com/dotnet/aspnetcore/blob/536282fce03c5bd012500976a3300699a655fe40/src/DefaultBuilder/src/WebHost.cs#L269

All the best.
