### ISSUE TITLE
AccessToken reach at the ExpirationDate, but it's status is still valid, can it auto change to be invalid

### ISSUE THREAD

**Issue by Zombieppp** [openiddict/openiddict-core#2240]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.3.0

### Question

AccessToken reach at the ExpirationDate, but it's status is still valid, can it auto change to be invalid；

as you can see, i set accesstoken lifetime to be one minute, but after the ExpirationDate it's status is still valid, if it's status is valid, quartz can not remove this token, how to solve 
this issue?
![image](https://github.com/user-attachments/assets/32f39d41-2f16-4f29-bdea-55849414d8f2)

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!

Happy holidays 🎄
