### ISSUE TITLE
Support for abstract providers

### ISSUE THREAD

**Issue by sashok2k** [openiddict/openiddict-core#2241]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

6.0.0.0

### Question

First of all, apologies for tricking about sponsorship, but I believe i'm asking quite important question, which will be useful for everyone:

So far, looking at source codes I understood that it's not possible to add any proproriatory oauth provider. As soon as adding new web provider will require to add new provider to `OpenIddictClientWebIntegrationProviders.xml`, it mean that OpenIdDict  implementation will not allow to integrate any other than listed providers. That appers to be a big problem, especially when using OpenIdDict together with ABP, as ABP references official OpenIdDict libs. That's blocks use of ABP for building our app.

Is there any plan to support custom, case specific providers? So we'll be able to develop our own lib and register implementations for handlers(e.g fetching user info from some specific storage)?

**Comment by kevinchalet** [comment]
> So far, looking at source codes I understood that it's not possible to add any proproriatory oauth provider. As soon as adding new web provider will require to add new provider to `OpenIddictClientWebIntegrationProviders.xml`, it mean that OpenIdDict implementation will not allow to integrate any other than listed providers.

The whole point of the `OpenIddict.Client.WebIntegration` companion package is to offer ready-to-use integrations that everyone can use without recreating them from scratch on their side: encouraging developers to submit their contribution is a core point of the thing 😄

> Is there any plan to support custom, case specific providers? So we'll be able to develop our own lib and register implementations for handlers(e.g fetching user info from some specific storage)?

`OpenIddict.Client.WebIntegration` is built on top of the generic OpenIddict client: you can adopt a similar approach if you really want, but the most common and logical approach is to just submit the provider you want to support.
