### ISSUE TITLE
It's very difficult to get this library working

### ISSUE THREAD

**Issue by atrauzzi** [openiddict/openiddict-core#225]
A terrible issue title to be sure.  But I really wanted to highlight some frustrations I'm having in trying to get up and running with this library.

Most of my difficulties seem to be focused around the use of generics and also pre-filled generic implementations the documentation guides me into using.  I'm in the process of going through the setup instructions, but I'd like to switch my key type from `string` to `int`.  For something so simple, I feel like I'm encountering just far too many road blocks to justify using this library.

It appears as though the moment I deviate from the one hard-wired configuration, I'm in a predicament where nothing lines up anymore and I can't seem to get anything to behave.  There's so much duplication of names with various generic parameters and overlap with existing identity types...  It would also appear as though I have an ordeal waiting for me if I want to get any control over the names of my tables.

I'm wondering if the generics-based approach this library takes perhaps bends generics too far and maybe it would be better served by just requiring some simple interfaces be implemented.  My experience both consuming and producing libraries has taught me that it's better to use interfaces and allow your consumers to still retain control of their classes.

Apologies for the anecdotal account, but I'll happily answer any specific questions about aspects of my experience.

**Comment by kevinchalet** [comment]
Sorry to hear that.

I think it's important to note that this pattern is not really specific to OpenIddict since it's massively used by Identity itself (https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs#L84). We try to reuse the same approach in OpenIddict, for consistency.

I agree generics make everything much harder to understand and to configure, but it's the price to pay for being able to easily use your own models instead of having to inherit from or reuse the built-in ones. If the ASP.NET team had adopted a different pattern, I'd have too, but unfortunately, that's not the case. Maybe you could ping the ASP.NET team about your concerns, but I doubt anything will change at this point.

**Comment by atrauzzi** [comment]
I definitely get where you're coming from.  I think it just means that anything identity-related is not for me, and I'm stuck hand-rolling my own.

Everybody's gotta have a hobby! ;)

**Comment by kevinchalet** [comment]
Hehe.

If you're comfortable with OAuth2/OpenID Connect, you can try ASOS, the underlying OIDC server middleware behind OpenIddict: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server

Unlike OpenIddict, it doesn't rely on Identity and implementing the membership part is left as an exercise. It's the equivalent of the `OAuthAuthorizationServerMiddleware` in the ASP.NET Core world.

FWIW, I wrote a blog posts series about ASOS in July: http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-introduction/

**Comment by atrauzzi** [comment]
Sorry, can you elaborate on what `OAuthAuthorizationServerMiddleware` is?

**Comment by kevinchalet** [comment]
It was the OAuth2 server middleware developed for OWIN/Katana. It was used in the ASP.NET Web API templates for Visual Studio.

I'm sure there are many resources about this stack. It was a really popular solution.

**Comment by atrauzzi** [comment]
Oh, interesting.  So ASOS would help me cut down on the logic-side of things, requiring me to just fetch and bridge my values into it, eh?

**Comment by kevinchalet** [comment]
Pretty much, yeah. ASOS only cares about the OpenID Connect details, nothing more... so it doesn't handle authentication and doesn't care how your users log in or register. You're free to bring your own abstractions and your own implementations for that.

**Comment by atrauzzi** [comment]
That's awesome, definitely no reason to reinvent the wheel here!  I'll jump over there, thanks for the tip :)
