### ISSUE TITLE
Settings and Configuration Wiki Article fallen out of date

### ISSUE THREAD

**Issue by gilessmart** [openiddict/openiddict-core#228]
I noticed a couple of things that might be improved in the ["Settings and Configuration" WIKI article](https://github.com/openiddict/openiddict-core/wiki/Configuration-and-options). Apologies in advance if anything turns out to be my misunderstanding.
- Description for "AuthenticationScheme" describes "Issuer"
- Default for "AuthenticationScheme" is given as "oidc-server" but ASOS source code appears to use "ASOS"
- "RefreshTokenLifetime" is given as 6 hours but ASOS source code appears to use 14 days
- The default for "AllowInsecureHttp" could state that the property is automatically enabled when running in a development environment (as the xml comments in the ASOS source does)

I'd assumed that I'd be able to fork the WIKI and make a pull request, so I've made these changes (locally) to the article as well as updating the descriptions with those from the XML comments in the code and a couple of other things. But pull requests for WIKI repos aren't supported so I've manually published a fork, in case anyone with access wants to manually merge my changes in. The fork is [here](https://github.com/gilessmart/openiddict-core-wiki).

Thanks for a great project. I'll continue to try to get to grips with it!

**Comment by kevinchalet** [comment]
Haha, nice catch! :+1: 

Yeah, both the ASOS XML code documentation and this wiki page need a serious rework. It's something I plan to do latter this year, after ASOS beta7 is officially released (I'm working on it ATM): https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/324.

> The default for "AllowInsecureHttp" could state that the property is automatically enabled when running in a development environment (as the xml comments in the ASOS source does)

Actually, this feature was removed to be consist with the ASP.NET Core security middleware, that don't use the environment name for setting this kind of properties automagically. I'll update the associated comment and "merge" your wiki changes tonight. Thanks!

> Thanks for a great project. I'll continue to try to get to grips with it!

Thanks for the kind word! :clap:

**Comment by kevinchalet** [comment]
Closing as we now have a dedicated repo for documentation, where all these options will be explained: https://github.com/openiddict/openiddict-documentation. I plan to remove the wiki once the docs are ready.
