### ISSUE TITLE
Support for .net 4.6.1

### ISSUE THREAD

**Issue by joshgarwood** [openiddict/openiddict-core#229]
Hi there!  I'm very eager to use this library as was using the built-in Microsoft auth solution with Identity, then realized I couldn't use the default SignInManager to get JWT's.  So, OpenIddict seems to be a perfect solution for me.  Unfortunately, I'm having trouble installing it.  Upon adding the necessary dependencies (OpenIddict and OAuth.Validation), I get an error when the packages are installed:

`Unable to resolve 'OpenIddict (>= 1.0.0)' for '.NETFramework,Version=v4.6.1'`

The "frameworks" node in my package.json looks like this:

`"frameworks": {
    "net461": {}
    }`

Is this supported, or will I not be able to use OpenIddict?

Thanks for your time!

**Comment by kevinchalet** [comment]
Hey.

.NET Desktop 4.6.1 should be fully supported as OpenIddict targets `net451`.

Are you sure you have added the `aspnet-contrib` feed to your `NuGet.config` file?

**Comment by joshgarwood** [comment]
You are correct; sorry for the confusion!  It was the nuget file i was missing... I need to follow directions better, ha
