### ISSUE TITLE
User UI management out of the box.

### ISSUE THREAD

**Issue by Bartmax** [openiddict/openiddict-core#23]
We should provide a UI to manage users out of the box.

User creation, listing, editing, claims inspection/modification, revocation, token issued, etc.

**Comment by ghost** [comment]
In my opinion the authorization server is not responsible for providing a user management UI. This could be done by a plugin, e.g. OpenIddict.UI? What do you think?

**Comment by kevinchalet** [comment]
Yup, ideally, this new management should have its own repository :smile:

**Comment by ctolkien** [comment]
What's the thoughts on this needing to integrate with an existing "admin" system that would be part of the application? Or should it be entirely standalone as per the reeeaally old asp.net membership UI that was shipped previously?

**Comment by kevinchalet** [comment]
Closing, as this is not a good fit for the core repo.
