### ISSUE TITLE
Ability to use EF6 instead of EFCore?

### ISSUE THREAD

**Issue by joshgarwood** [openiddict/openiddict-core#230]
Hey folks!

Sorry to be a bother, but I saw in the documentation that it would be possible to use another version of EF (ie: EF6) instead of EFCore.  In looking at the sample project I'm not quite sure how to do this...  I currently have Identity implemented with EF6 within my .NET Core project, but am not sure how to leverage OpenIddict with that implementation.  

From the ReadMe it seems like I would basically need to make my Identity Models (ApplicationUser, ApplicationRole, etc) inherit from the OpenIddict implementation, and then initialize OpenIddict with those... Would I still be able to leverage the OpenIddict stores though (ie: the TokenStore)?  Or would I need to write that myself.

**A full list of which interfaces/classes that need to be implemented/written in order to leverage EF6 would be extremely helpful** :)

Any help would be much appreciated.

Thanks!

**Comment by kevinchalet** [comment]
Hey,

> Would I still be able to leverage the OpenIddict stores though (ie: the TokenStore)? Or would I need to write that myself.

The `OpenIddictXYZStore` implementations provided by `OpenIddict.EntityFramework` are specific to EF Core and cannot be used with EF 6.

To support EF 6, you'll have to implement the `IOpenIddictXYZStore` interfaces yourself. For that, I'd recommend copying the EF Core entities/stores and tweak them to make them work with EF 6: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.EntityFramework

To register your stores, you'll have to use the built-in DI container. Here's how we do that for the EF Core stores: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFramework/OpenIddictExtensions.cs

Good luck!

**Comment by joshgarwood** [comment]
Hey Kevin!  Thanks so much for the insight and direction on getting this done.  After a _lot_ of trying (and failing), I believe I have all of the Stores and Entities/Models implemented. 

That said, I do have another question... The **AddOpenIddict** extension method... I'm getting a type conversion error when calling that method in the Startup.cs ConfigureServices method.  But when looking at the code for that extension, it looks like it should be fine to use my custom entities instead of the OpenIddict entities.  So... This is what you have in the repo right now for the AddOpenIddict method:

```
public static OpenIddictBuilder AddOpenIddict<TUser, TRole, TApplication, TAuthorization, TScope, TToken>(
            [NotNull] this IServiceCollection services)
            where TUser : class
            where TRole : class
            where TApplication : class
            where TAuthorization : class
            where TScope : class
            where TToken : class 
{ 

           // Other cool stuff...
}
```

The reason I feel like I should be able to call this method with my entities is that he restriction on those generic types is only **class** and not **OpenIddictUser** for instance.  Does that make sense?  Here's the call I'm making:

`services.AddOpenIddict<ApplicationUser, ApplicationRole, ApplicationApp, ApplicationAuthorization, ApplicationScope, ApplicationToken, NoblyContext, int>();`

For reference, here's an what my ApplicationScope class looks like:

```

public class ApplicationScope : IdentityScope<int>
{
}

public class IdentityScope : IdentityScope<string>
    {
        public IdentityScope()
        {
            Id = Guid.NewGuid().ToString();
        }
    }

    public class IdentityScope<TKey> where TKey : IEquatable<TKey>
    {
        public virtual string Description { get; set; }
        public virtual TKey Id { get; set; }
    }
```

I know I could use the OpenIddictScope, but for other classes (like OpenIddictUser), I had to implement my own model because OpenIddictUser depends on EF Core.  So using OpenIddictScope for the sake of simplicity, shouldn't I still be able to call AddOpenIddict() in the ConfigureServices method since the type restriction is only "class"?

Sorry for the long-winded question, but any hep would be much appreciated.

Thanks!

**Comment by kevinchalet** [comment]
> shouldn't I still be able to call AddOpenIddict() in the ConfigureServices method since the type restriction is only "class"?

You should be able to use the shortest `AddOpenIddict` overload defined in `OpenIddict.Core` (but not the longest overloads used by `OpenIddict`, as they rely on the EF stores).

What's the exact error you're seeing?

**Comment by joshgarwood** [comment]
Hey Kevin!  Thanks for the response!  I would have thought so too, but here is the error I'm getting:

![image](https://cloud.githubusercontent.com/assets/1417324/18839911/bef5fffa-83da-11e6-9bec-2c07fb01de0f.png)

**Comment by kevinchalet** [comment]
Hey Josh,

As mentioned, the longest overloads can't work with custom stores.
FWIW, I'm considering removing them for clarity.

**Comment by joshgarwood** [comment]
Oh, i thought you said the longest overloads would work, 

> You should be able to use the longest AddOpenIddict overload defined in OpenIddict.Core (but not the shortest overloads...)

Lemme see if I missed something.

**Comment by kevinchalet** [comment]
@joshgarwood that's what I get for answering while doing something else at the same time... :sweat_smile:

**Comment by joshgarwood** [comment]
Haha, no worries; still very helpful :)  It worked as soon as I removed the `<...NoblyContext, int>` types.

Many thanks!!

**Comment by dazinator** [comment]
Hi guys. I am using EF Core, but I don't want my ApplicationUser class to use inheritance. May I ask - is inheritance necessary? Or an interface would be preferable in my case?

**Comment by kevinchalet** [comment]
@dazinator if you don't want to inherit from the `OpenIddict*` entities, the "punishment" is the same as the one inflicted by Identity: you must provide your own stores, since the built-in ones only work with the default entities :smile:

**Comment by dazinator** [comment]
Ok thats cool, I can implement custom stores :-)
Cheers!

**Comment by kevinchalet** [comment]
Hey guys,

I'm considering creating an "official" EF6 stores package for OpenIddict.
Do you think it's worth it?

**Comment by Bartmax** [comment]
How many people uses EF6 with OpenIddict? If we get many 👍 I think it would be worth it, but I'm no so sure.
