### ISSUE TITLE
Cannot get access token by postman

### ISSUE THREAD

**Issue by DCTruong** [openiddict/openiddict-core#236]
Hi PinpointTownes,

I have a project using your great OpenIdDict. I have followed your setup but I cannot get access token by Postman - the request binding is always null. Could you please help to check? Thank you very much.

Please look at the screenshot: 

![issue](https://cloud.githubusercontent.com/assets/2047342/19215699/682c1e6c-8dcf-11e6-80e9-b9be4191ae80.png)

Regards,
Truong

**Comment by kevinchalet** [comment]
Hey @DCTruong,

Any chance you could also share your `Configure` method?

**Comment by DCTruong** [comment]
Sure Pinpoint. Thanks for your response. I attached the Configure method bellow.

![configmethod](https://cloud.githubusercontent.com/assets/2047342/19227079/e359796c-8ede-11e6-9ccf-20fd406a7d46.png)

I have also checked with your sample My.Server and I can test authentication/authorization flow with My.Client but not with Postman. I think there is something wrong with my Postman config.

Thanks,
Truong

**Comment by kevinchalet** [comment]
I can see in your screenshot that you're using `form-data` instead of `x-www-form-urlencoded`, which is not expected to work (as the OAuth2 specification requires url-encoding). Can you try to fix that?

The weird thing is that your MVC controller shouldn't be invoked for an invalid request. Here's what you should get instead:

``` json
{
  "error": "invalid_request",
  "error_description": "A malformed token request has been received: the 'Content-Type' header contained an unexcepted value. Make sure to use 'application/x-www-form-urlencoded'."
}
```

When you tested, are you sure `app.UseOpenIddict()` and `app.UseMvcWithDefaultRoute()` were in this exact order?

**Comment by DCTruong** [comment]
Thank you very much. I followed your two suggestions and the problem is solved. Thanks again for your great support.

Truong

**Comment by kevinchalet** [comment]
@DCTruong just to be sure, you're now seeing the exact error message I mentioned when using `form-data`, right?

**Comment by DCTruong** [comment]
Yes, It is. Thanks a lot.
And if You you do not mind me asking another question related to ADFS Server?

I have the ADFS Server that is used to authenticate AD Users(on-premise) and issue token(SAML) to Replying Parties along with "Registered User". Could please you give me advice or show me how to use both kind of Users to provide authentication/Authorization to my WebAPI? Can we integrate ADFS authentication into OpenIdDict or my service have to use two authentication servers?

Thanks,
Truong

**Comment by kevinchalet** [comment]
@DCTruong you can find more information about this scenario here: http://stackoverflow.com/questions/38470683/is-it-possible-to-use-openiddict-and-ldap-together.

Hope it'll help.
