### ISSUE TITLE
Connect call connect/token in latest version 0448

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#238]
I am using postman and connecting to localhost:5000/connect/token passing the following parameters

![image](https://cloud.githubusercontent.com/assets/7406381/19275961/09bfbb86-8fcd-11e6-9e62-2914f25eaaf5.png)

But i seem to get a message in the console saying

> info: OpenIddict.Infrastructure.OpenIddictProvider[0]
>       The token request validation process was skipped because the client_id parameter was missing or empty.

Then i provide my client_id in my postman call, and i get this message in console

> The token request validation process was not fully validated because the client 'bd000383-acd9-46fc-a7d5-1f1f128fa285' was a public application.

I am just trying to login using username and password on my angular2 SPA application.  I am using JWT tokens.  Below is my startup.cs configuration for openiddict-core

```
public void ConfigureServices(IServiceCollection services)
{
    // identity
    services.AddIdentity<ApplicationUser, ApplicationRole>(config =>
    {
        // if we are accessing the /api and an unauthorized request is made
        // do not redirect to the login page, but simply return "Unauthorized"
        config.Cookies.ApplicationCookie.Events = new CookieAuthenticationEvents
        {
            OnRedirectToLogin = ctx =>
            {
                if (ctx.Request.Path.StartsWithSegments("/api"))
                    ctx.Response.StatusCode = (int)HttpStatusCode.Unauthorized;

                return System.Threading.Tasks.Task.FromResult(0);
            }
        };
    })
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

    // Register the OpenIddict services, including the default Entity Framework stores.
    services.AddOpenIddict<ApplicationUser, ApplicationDbContext>()
        // Enable the token endpoint (required to use the password flow).
        .EnableTokenEndpoint("/connect/token")

        // use JWT
        .UseJsonWebTokens()

        // Allow client applications to use the grant_type=password flow.
        .AllowPasswordFlow()

        .DisableHttpsRequirement()

        // Register a new ephemeral key, that is discarded when the application
        // shuts down. Tokens signed using this key are automatically invalidated.
        // This method should only be used during development.
        .AddEphemeralSigningKey();
    }
}


public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    // enable JWTBearer
    app.UseJwtBearerAuthentication(new JwtBearerOptions
    {
        Authority = "http://localhost:5000",
        AutomaticAuthenticate = true,
        AutomaticChallenge = true,
        Audience = "http://localhost:5000",
        RequireHttpsMetadata = false
    });

    // Note: OpenIddict must be added after ASP.NET Identity and the external providers.
    app.UseCsp(options => options
            .DefaultSources(directive => directive.Self())
            .ImageSources(directive => directive
                .Self()
                .CustomSources("data:"))
            .ScriptSources(directive => directive
                .Self()
                .UnsafeInline()
                .UnsafeEval()                               // google charts
                .CustomSources("https://www.google.com", "https://www.gstatic.com", "https://ajax.aspnetcdn.com"))    // google charts, google charts, jquery validation (login)
            .StyleSources(directive => directive
                .Self()
                .UnsafeInline()
                .CustomSources("https://fonts.googleapis.com", "https://www.google.com", "https://ajax.googleapis.com", "https://www.gstatic.com"))     // google fonts, google charts, google charts
            .FontSources(directive => directive
                .Self()
                .CustomSources("https://fonts.gstatic.com"))   // google fonts
        );

    app.UseXContentTypeOptions();
    app.UseXfo(options => options.Deny());
    app.UseXXssProtection(options => options.EnabledWithBlockMode());

    // comment this out and you get an error saying 
    // InvalidOperationException: No authentication handler is configured to handle the scheme: Microsoft.AspNet.Identity.External
    app.UseIdentity();

    app.UseOpenIddict();
}
```

if any of this is wrong, please let me know as i was previously using version 0404, and this worked fine, but now i have upgraded, its asking for the client_id etc

**Comment by kevinchalet** [comment]
Do you have a token endpoint action, like in the sample?

https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AuthorizationController.cs#L127

**Comment by Gillardo** [comment]
No, i have not got an AuthorizationController.  Is this now needed?

**Comment by kevinchalet** [comment]
It is. OpenIddict no longer handles the authentication part when using the password flow (and there's a plan to decouple it from ASP.NET Core Identity).

**Comment by Gillardo** [comment]
I have added the authorizationController from the example you sent, now i get this error?

> InvalidOperationException: Unable to resolve service for type 'OpenIddict.OpenIddictApplicationManager`1[OpenIddict.OpenIddictApplication`1[System.String]]' while attempting to activate 'm2i.Unite.Web.Controllers.AuthorizationController'.

But i cannot see where in the Server example it injects this?

**Comment by kevinchalet** [comment]
@Gillardo use `OpenIddictApplicationManager<OpenIddictApplication>` when using the default key type.

**Comment by Gillardo** [comment]
lol, just fixed that...but thanks.

Now though i am able to call the API, although i still have to provide a client_id and resource for using JWT, which aint a problem, just making sure this is needed?

But now, if i pass the access_token via an Authorization call, my user is not found.

I get an error in the console that says

> info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
>       Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token:

**Comment by kevinchalet** [comment]
> Now though i am able to call the API, although i still have to provide a client_id and resource for using JWT, which aint a problem, just making sure this is needed?

The `client_id` parameter is only required if you use the new `RequireClientIdentification()` option.

**Comment by Gillardo** [comment]
Ok @PinpointTownes my fault, i should of looked at the obvious comment above that line.

I have now added `.UseJsonWebTokens()` now getting this error

> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'http://localhost:5000' or validationParameters.ValidAudiences: 'null'.

But in my original request to `connect/authorize` i am passing in the resource parameter of http://localhost:5000 ??

**Comment by kevinchalet** [comment]
> But in my original request to connect/authorize i am passing in the resource parameter??

You must call `ticket.SetResources("xyz")` to allow OpenIddict to use the xyz resource as a valid audience. The `resource` parameter can still be used as a hint, but it has no effect unless you do something like `ticket.SetResources(request.GetResources())`.

**Comment by kevinchalet** [comment]
@Gillardo I suppose it's working, now? :smile:

**Comment by Gillardo** [comment]
@PinpointTownes nope still not working.  If i remove the "resource" property from my call to `connect/authroize` and then use the access_token on a protected api call, i still get an exception in the console saying

> info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[1]
>       Failed to validate the token eyJhbGciOiJSUzI1NiIsImtpZCI6IjlCWlVPQkFGN0VQTlNaUU1MMjU1OTdDREZXSF9XUkxYLVBQSlZaS0MiLCJ0eXAiOiJKV1QifQ.eyJ1bmlxdWVfbmFtZSI6ImRhcnJlbi5naWxsYXJkQG1lYXN1cmUyaW1wcm92ZS5jb20iLCJlbWFpbCI6ImRhcnJlbi5naWxsYXJkQG1lYXN1cmUyaW1wcm92ZS5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjMzN2Y4YzA1LTdmOWQtNDc1YS1hMTA2LWUxNzlmZjUyZDNiMSIsImp0aSI6IjZlMGFmYTMyLTFkMTQtNDNhMi1hMjQzLTFiMmNhNDFmYzQ4ZiIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOlsib3BlbmlkIiwiZW1haWwiLCJwcm9maWxlIl0sInN1YiI6IjIxOTM4MmFiLTVmYzQtNGJiMS05NWU4LWViNzdhNjY1YWM3YiIsImF6cCI6IjYwNTk5YjMxLTMwZWEtNDAzZC1iMGJlLTI3NGNmZjQwYTYxNiIsIm5iZiI6MTQ3NjIxNjAzNCwiZXhwIjoxNDc2MjE3ODM0LCJpYXQiOjE0NzYyMTYwMzQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC8ifQ.tN1Y0HPmCyfpFVS4AoWJyLSD0JgtmfcP4-7eagJuFR8OEsf8HMYHmk9q_gdwzu4DV3cxDZPm_mVRy043emdPWFcCOCQBEicsMK8pJYYgPazQrx5paRGepobrLUX1p8gy4bguWgW_mtZO5hsMfoVW4Ms22h4Et3BZ9C9FnyRexJAnac0tW44FDwkUqvnWnwQM8_GeU820BDVx04YwGm6o6dKuc7ZZjyQ0tujQCYRo0JKjhfJqZA5ezb8eo2CWeKi_Ufn-1-EalRB7mCNl61SViTlvlYyr6rQAeeoCE5UoxnO_IQYtUt2yWVy4yrakOc51q6UbkmD2k3QgEbrFFrj0NQ.
> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'http://localhost:5000' or validationParameters.ValidAudiences: 'null'.
>    at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
>    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
> info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
>       Bearer was not authenticated. Failure message: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'http://localhost:5000' or validationParameters.ValidAudiences: 'null'.
> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
>       Authorization failed for user: .
> warn: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
> info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
>       Executing ChallengeResult with authentication schemes ().
> info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[12]
>       AuthenticationScheme: Identity.Application was challenged.

**Comment by kevinchalet** [comment]
Do you call ticket.SetResources(...) as suggested?

**Comment by Gillardo** [comment]
No, i dont want to use resource if possible... If i have to, where do i need to put that?

Also noticed that i get this message in the console when calling the `connect/authorize` method

> info: Microsoft.AspNetCore.Mvc.SignInResult[1]
>       Executing SignInResult with authentication scheme (ASOS) and the following principal: System.Security.Claims.ClaimsPrincipal.
> info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
>       No explicit audience was associated with the access token.
> info: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[10]
>       AuthenticationScheme: ASOS signed in.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action m2i.Unite.Web.Controllers.AuthorizationController.Exchange (m2i.Unite.Web) in 665.8742ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 1294.7995ms 200 application/json;charset=UTF-8

**Comment by kevinchalet** [comment]
You must call ticket.SetResources(...) after creating the AuthenticationTicket and before returning a SignInResult.

**Comment by Gillardo** [comment]
And is this mandatory?  Just wondered why it aint included in the example if it is?

**Comment by kevinchalet** [comment]
It is. It's not included in the sample because it uses the default token
format, that doesn't require setting an audience.

**Comment by Gillardo** [comment]
@PinpointTownes fair enough.. Thanks for all your help. Last thing.. role doesnt seem to be included as a claim anymore, when you pass a scope of role??  Is this something that i now need to implement?
