### ISSUE TITLE
Connected host has failed to respond 999.99.999.999:80 - Using sub folder website

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#239]
My code all works when i am developing which i use localhost:5000.

I have now published my code and uploaded to the site which uses child folders....Eg.
http://www.my-url.co.uk/folder1
http://www.my-url.co.uk/folder2

When i call folder1/connect/token or folder2/connect/token with a valid username and password, i get a token returned.

But if i try to connect to a protected api resource, i get this weird message returned on the server??

> An unhandled exception occurred while processing the request.
> 
> SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 999.99.999.999:80 <!---- THIS IS THE IP OF THE ACTUAL SERVER
> MoveNext
> 
> WebException: Unable to connect to the remote server
> MoveNext
> 
> HttpRequestException: An error occurred while sending the request.
> MoveNext
> 
> IOException: IDX10804: Unable to retrieve document from: 'http://www.my-url.co.uk/folder1/.well-known/openid-configuration'.
> MoveNext
> 
> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://www.my-url.co.uk/folder1/.well-known/openid-configuration'.
> MoveNext

I am using JWT Token, and have added this to my `Startup.cs` file

```
// enable JWTBearer
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    Authority = "http://www.my-url.co.uk/folder1",
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    Audience = "http://www.my-url.co.uk/folder1",
    RequireHttpsMetadata = false
});
```

And in my `AuthorizationController.cs` file i have added this line as well to my `Exchange` and `Accept` methods

```
// Set resource
ticket.SetResources(new string[] { "http://www.my-url.co.uk/folder1" });
```

I wonder if the problem is that something is trying to connect to my IP address, but not using the sub folder as well, as you can see above in the error it says

> connected host has failed to respond 999.99.999.999:80

But i think this should be 

> connected host has failed to respond 999.99.999.999:80/folder1

Any ideas what it could be??

**Comment by kevinchalet** [comment]
> Any ideas what it could be??

It's seems ultra clear to me: the JWT middleware tries to download the discovery document from OpenIddict and fails to do so because it's unreachable (hence the `SocketException`).

You likely have a routing or firewall issue somewhere in your infrastructure.

> But i think this should be connected host has failed to respond 999.99.999.999:80/folder1

Not really as there's no "path" notion with sockets . It's an HTTP artifact.

**Comment by Gillardo** [comment]
@PinpointTownes  thanks for that...I did wonder if it was a firewall issue.  I have just setup the whole server using a root URL (no folders) and i am getting the same issue.  I will keep you posted

**Comment by Gillardo** [comment]
@PinpointTownes seemed to fix the firewall issue, now just getting this exception?

An unhandled exception occurred while processing the request.

> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://www.my-url.co.uk/.well-known/openid-configuration'.

**Comment by kevinchalet** [comment]
I doubt your issue is fixed if you're getting the same error :trollface:

**Comment by Gillardo** [comment]
Not getting the same error, i dont think, as now it doesnt say that the server isnt responding....

**Comment by kevinchalet** [comment]
It's easy to confirm: navigate to `http://www.my-url.co.uk/.well-known/openid-configuration` with your browser. If you get the discovery document, then it's another routing/firewall issue.

**Comment by Gillardo** [comment]
Where is this file actually created? Or what method is called on a controller to get this file?

**Comment by kevinchalet** [comment]
It's dynamically generated by OpenIddict.

**Comment by Gillardo** [comment]
so is there a controller method that is called with the route of ".well-known/openid-configuration", and from there it generates the output?

**Comment by kevinchalet** [comment]
It's not a controller (it operates at the middleware level), but that's the idea, yep.

**Comment by Gillardo** [comment]
@PinpointTownes sorry for all the questions, just not sure how this would be a "firewall" issue now.  Could it be a permission issue, as in needing "write" capability or something?  Or does the "middleware" not actually create a file, just generates the output directly?

**Comment by kevinchalet** [comment]
> Or does the "middleware" not actually create a file, just generates the output directly?

That's how it works, yup.

**Comment by Gillardo** [comment]
Does it do this via a particular port other then 80?

**Comment by Gillardo** [comment]
I am guessing i cant see this code via github to see myself?

**Comment by kevinchalet** [comment]
> Does it do this via a particular port other then 80?

No.

> I am guessing i cant see this code via github to see myself?

The code is there: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Discovery.cs

... and the unit tests there: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/test/AspNet.Security.OpenIdConnect.Server.Tests/OpenIdConnectServerHandlerTests.Discovery.cs

**Comment by Gillardo** [comment]
@PinpointTownes  thanks for all you help, this is now working

**Comment by Gillardo** [comment]
@PinpointTownes  this issue is not fixed.  It seems that when i am looking at a website that is specific to a sub folder (www.my-url.co.uk/folder1), the call is still to www.my-url.co.uk/.well-known/openid-configuration

Surely this should be to the www.my-url.co.uk/folder1/.well-known/openid-configuration ??

**Comment by kevinchalet** [comment]
Note: the JWT middleware is not something I maintain. If you believe there's a bug with its discovery feature, maybe it would be better to open a ticket here: https://github.com/aspnet/Security.
