### ISSUE TITLE
UserId no longer saved when refresh token is serialized.

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#241]
I see some major changes were done recently that broke a few things.

I managed to update my code base to accommodate the update by now but there is one thing missing.

Previously, the user id was associated with the refresh token stored in the database. 

This is no longer the case.

Do you have any plans to restore this behaviour @PinpointTownes ?

I was using the refresh tokens as a list of sessions for the user (session data stored in a child table: Location, Device token [for push notifications], etc...)...

I also used it for remote revocation of tokens (Sign out other sessions).

**Comment by kevinchalet** [comment]
> This is no longer the case.
> Do you have any plans to restore this behaviour @PinpointTownes ?

Yep, this is a direct (and expected) consequence of removing the Identity dependency from `OpenIddict.Core`.

This is something I'd like to reintroduce in beta1/beta2 and I'm currently trying to determine what would be the best option for that.

**Comment by jayrulez** [comment]
Do you have an ETA(ball park) for beta1/beta2?

**Comment by kevinchalet** [comment]
Nope, but I'll keep you informed of the progress :smile: 

In the meantime, keep using the alpha2 bits.

**Comment by jayrulez** [comment]
Thank you. I'm looking forward to the update.

**Comment by jayrulez** [comment]
👍 

Lots of changes to  make

**Comment by kevinchalet** [comment]
> Lots of changes to make

Note that this feature itself is transparent. The only thing you have to do is migrate your DB to ensure the `Subject` column is correctly added :smile:

**Comment by jayrulez** [comment]
Yea... However, I worked around the issue before so I'll need to drop that code.

Well I just finished all of that. Working on splitting the auth server from the resource server now :)
