### ISSUE TITLE
Example of how to use refresh_token on web app

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#244]
As the title states.  I have seen a few questions on here asking how to do this, but still not exactly sure of what is needed.  It would be great if someone could upload some sample code to we all understand how to do it....

**Comment by kevinchalet** [comment]
This thread should help: http://stackoverflow.com/questions/40032851/how-to-handle-expired-access-token-in-asp-net-core-using-refresh-token-with-open.
