### ISSUE TITLE
Authorization server for multiple resource servers / clients

### ISSUE THREAD

**Issue by ksmuthuus** [openiddict/openiddict-core#245]
@PinpointTownes  I am building an Auth server leveraging OpenIdDict via ASP.NET Identity CORE.  This Auth server should be leveraged by other clients applications (with its own Resource servers) coming up in future.  Just need some thoughts on how to segregate users (with corresponding roles) of multiple applications.  One thought is getting client_id from client app and save username in ASPNetUsers table by prefixing client_id.  as <username>_<client_id>.  Is it correct way or any other suggestions you can provide .......

**Comment by kevinchalet** [comment]
> Just need some thoughts on how to segregate users (with corresponding roles) of multiple applications. 

I'm not sure to understand why would you do that, TBH.

**Comment by geocine** [comment]
@ksmuthuus  you can make use of the JWT claims to add details like roles or tenant ids if you will. I am not talking about ASP.NET Identity CORE though but that is usually how you do it.

**Comment by ksmuthuus** [comment]
Thanks to @PinpointTownes  and @geocine  for your response.  The situation where I am more confused to arrive at solution goes like this:
1) Application A => User name(abc@domain.com) => Roles(Admin, Guest)
2) Application B => User name(abc@domain.com) => Roles(Admin).

M questions are:
1) If the same unique user name record be shared across both applications or should the user name be marked with prefix/sufix are create two records one for each application?
2) If same user record is shared across both applications, I think the application clients should get only its respective claims i.e.., A => Admin & Guest & B=> Guest. Is it possible with existing model (or) new columns to be added  to ASpNetRoles (or) AspNetUserRoles tables.

**Comment by geocine** [comment]
@ksmuthuus  
1. I agree with your illustration above can be done by using the same unique name record on both applications. No need for a prefix/suffix
2. You could pass the application id along with the stuff on the password flow during token request. But this is not a built in functionality so what you could do is re-purpose the `client_id` parameter which is used on the authorization code flow to act as application id which is essentially also an application identifier on the authorization code flow. Then based on that application id you could add the role claims and add the application id as well on the claim. As for the tables you may have to add an applications table that would identify roles for the user for the particular application.
