### ISSUE TITLE
Refresh Token when using UseJsonWebTokens

### ISSUE THREAD

**Issue by geocine** [openiddict/openiddict-core#246]
I don't get the `refresh_token` using the `grant_type: password` . I am using `UseJsonWebTokens`. Is refresh tokens supported when using JWT? If not, where could I plug my custom implementation?

If have `scope: offline_access` set. I get this error:

```
Cannot create a DbSet for 'OpenIddictToken' because this type is not included in the model for the context.
```

> Note: I have implemented my own User models

**Comment by kevinchalet** [comment]
The questions seems clear enough to me: your DbContext doesn't have the `DbSet<OpenIddictToken>` set required by OpenIddict to store the authorization codes/refresh tokens.

Make sure your `DbContext` inherits from `OpenIddictDbContext`.

**Comment by geocine** [comment]
Is there a way I could use my own entity like `DbSet<MyOwnToken>` I don't want to use the OpenIddictToken ?

**Comment by kevinchalet** [comment]
Sure. In this case, you'll have to create your own `IOpenIddictTokenStore` implementation.

**Comment by geocine** [comment]
Thanks. Then how would I tell OpenIddict to use it? I know how to do it for `IUserStore` and `IRoleStore` like so

``` csharp
services.AddIdentity<User, Role>()
```

Where my `IUserStore` is using `User` and `IRoleStore` is using `Role`

**Comment by kevinchalet** [comment]
It works exactly the same way: `services.AddOpenIddict<...>()` has overloads that allow you to specify custom entity types. The object it returns (`OpenIddictBuilder`) has methods you can use to register your custom stores.

**Comment by geocine** [comment]
@PinpointTownes  I don't know what is wrong so I have added it this way:

``` csharp
services.AddOpenIddict<SDBContext>()
.AddTokenStore<TokenStore>();
services.AddScoped<IOpenIddictTokenStore<Token>, TokenStore>();
```

Then my `TokenStore` looks like this

``` csharp
    public class TokenStore : IOpenIddictTokenStore<Token>
    {
       //implementation here
    }
```

Yet I get this error:

```
An exception of type 'System.InvalidOperationException' occurred in OpenIddict.Core.dll but was not handled in user code

Additional information: Custom stores must implement IOpenIddictTokenStore.

```

**Comment by kevinchalet** [comment]
Wrong `AddOpenIddict` overload.

**Comment by geocine** [comment]
@PinpointTownes . You mean this overload right?

```
AddOpenIddict<TApplication, TAuthorization, TScope, TToken, TContext, TKey>
```

I don't have implementations for TApplication , TAuthorization , I want to use the existing one

**Comment by kevinchalet** [comment]
> You mean this overload right?

I do.

> I don't have implementations for TApplication , TAuthorization , I want to use the existing one

Then use `OpenIddictApplication` and `OpenIddictAuthorization` as the generic arguments?

**Comment by geocine** [comment]
@PinpointTownes . Thank you so much for your help . I was able to do it

```
AddOpenIddict<OpenIddictApplication<int, Token>, OpenIddictAuthorization<int, Token>, OpenIddictScope<int>, Token, SDBContext, int>()
```

Thank you for making this library flexible enough to make these customization 👍

**Comment by kevinchalet** [comment]
@geocine glad you like it :tada:
