### ISSUE TITLE
cors works for access token but not for refresh token

### ISSUE THREAD

**Issue by joel00** [openiddict/openiddict-core#250]
I can get valid access tokens and refresh tokens using CORS but when i try to refresh the access token (using angular2) i get a "XMLHttpRequest cannot load http://localhost:5000/connect/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access."

I can refresh the tokens using postman.

What I'm doing wrong?

 public RefreshToken() {
        return this.http
            .post(
            this._baseUrl + 'connect/token',
            this.urlEncodeValues({
                'grant_type': 'refresh_token',
                'refresh_token': localStorage.getItem('refresh_token')
            }),
            this.options // new Headers({ 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json' });
            )
            .map(this.extractData)
            .map((res) => {
                if (res.access_token) {
                    localStorage.setItem('access_token', res.access_token);
                    localStorage.setItem('refresh_token', res.refresh_token);
                    localStorage.setItem('id_token', res.id_token);
                }
            })
            .catch(this.handleError);

**Comment by kevinchalet** [comment]
@joel00 CORS is not added for you (at least, not in the current bits) so it's something you must configure yourself. I suppose there's something wrong with your CORS policy.

**Comment by joel00** [comment]
after several hours... I did not respect the order of cors...

https://docs.asp.net/en/latest/security/cors.html
"... CORS middleware must precede any defined endpoints in your app that you want to support cross-origin requests..."

 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
           ........
           app.UseCors(builder => {  <------- 
                builder.WithOrigins("http://localhost:4200").AllowAnyMethod().AllowAnyHeader();
            });

```
        app.UseIdentity();
        app.UseOAuthValidation();
        app.UseOpenIddict(); <----------
        app.UseMvc();
```

..........

**Comment by kevinchalet** [comment]
Glad you found the root cause of your issue :clap:
