### ISSUE TITLE
How do you use an external provider with tokens?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#252]
In the samples, this works because it uses tokens.  In my application, i am using JWT tokens.

I have tried to change the code to work but when i try and call `/connect/authorize` from another method, i get an exception thrown saying

> An OpenID Connect response cannot be returned from this endpoint.

If a user logs in to my application using an external provider, how can i create a local access_token for the user to use on my site?  I nearly have all the blocks to do this apart from this...

**Comment by Gillardo** [comment]
So far, i have this on my `AuthorizationController`. I just want to return something similar to when we call `/connect/token`

```
[HttpGet]
[Route("~/connect/externalLogin")]
public async Task<IActionResult> ExternalLoginAsync(string provider, string idToken)
{
    var info = await _signInManager.GetExternalLoginInfoAsync();
    if (info == null)
            return new BadRequestResult();

    // Sign in the user with this external login provider if the user already has a login
    var email = info.Principal.FindFirstValue(ClaimTypes.Email);
    var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);

    if (result.Succeeded)
    {
        // get account
        var account = await _userManager.FindByEmailAsync(email);

        // Create a new authentication ticket.
        var ticket = await CreateTicketAsync(new OpenIdConnectRequest { Scope = "profile email" }, account);

        // Returning a SignInResult will ask OpenIddict to issue the appropriate access/identity tokens.
        return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
    }
    else
    {
        // logged in using external provider, now we need to login locally
        var account = await _userManager.FindByEmailAsync(email);

        // account has been created, so this is not valid
        if (account == null)
            return new BadRequestResult();

        // add login to account
        var loginResult = await _userManager.AddLoginAsync(account, info);

        if (loginResult == IdentityResult.Success)
        {
            // Create a new authentication ticket.
            var ticket = await CreateTicketAsync(new OpenIdConnectRequest { Scope = "profile email" }, account);

            // Returning a SignInResult will ask OpenIddict to issue the appropriate access/identity tokens.
            return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
        }

    }

    return new BadRequestResult();
}
```

**Comment by kevinchalet** [comment]
You can't return an OIDC response from an arbitrary action, that is not identified as an authorization or token endpoint: this is exactly what this check and the `InvalidOperationException` it throws try to prevent.

Give @shaunluttin's sample a try to see how you're supposed to implement external authentication support: https://github.com/openiddict/openiddict-samples/tree/master/samples/ImplicitFlow/AuthorizationServer

**Comment by Gillardo** [comment]
@PinpointTownes I am not sure i understand, there is no difference between the normal samples of using an external identity provider and the example link you have sent.  There is no way to return an OIDC response from logging with an external identity provider in that sample that i can see?

Ideally, i would like to login with the external identity provider on the client, which can be done, pass up the idToken from the external identity to validate it, then if valid, exchange it for an accessToken locally.

This is how it is described here on the google page [here](https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token)

**Comment by kevinchalet** [comment]
@Gillardo I posted my answer there: http://stackoverflow.com/questions/40257981/exchanging-a-google-idtoken-for-local-openid-token-c-sharp/40260960#40260960
