### ISSUE TITLE
Do you have used OpenIddict with the new Core 1.1?

### ISSUE THREAD

**Issue by felipesantanadev** [openiddict/openiddict-core#253]
After I have installed the Core 1.1, I'm having problems with OpenIddict.

First of all, the project is throwing the message "OpenIddictUser<> could not be found".

I have already imported the OpenIddict.

That's my project.json:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library":"1.6.1-preview1-24530-04",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Identity.Dapper": "0.3.0-alpha",
    "OpenIddict": "1.0.0-*",
    "MailKit": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6.1": {
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by kevinchalet** [comment]
`OpenIddictUser` was removed a week ago (https://github.com/openiddict/openiddict-core/commit/bc5f21ad26714fc486de73c9df6634aaff0a038d). It has nothing to do with .NET Core 1.1.0

Use `IdentityUser` instead and it should work (you might have to migrate or recreate your database).

**Comment by kevinchalet** [comment]
Looks like your issue is now solved: https://github.com/aspnet/EntityFramework/issues/6868.

**Comment by felipesantanadev** [comment]
Yes, thank you @PinpointTownes !
