### ISSUE TITLE
Error "client_id was missing" after upgrade 0473 -> 0478

### ISSUE THREAD

**Issue by Maarten88** [openiddict/openiddict-core#259]
Thanks for this great project, I am trying to use it for a separate openid connect server that is part of a larger application, using the out-of-the-box features, but replacing all identity stores. (I don't like EF :-)

My project.json had "OpenIddict.Core": "1.0.0-*" in it, and it just got upgraded to 1.0.0-beta1-0478.

Now I get an error on post of /connect/authorize/accept:
error:invalid_request
error_description:client_id was missing

This worked before. It still works if I copy the previous assemblies for OpenIdDict.Core and AspNet.Security.OpenIdConnect.Server back.

I tried to figure out what changed by going through the commit history, but can't find an explanation.

I don't have "RequireClientIdentification"; my configuration is this (I use a custom store), the code is mostly copied from the Mvc.Server sample:

    // Register the OpenIddict services.
    services.AddOpenIddict<MyClientApplication, MyAuthorization, MyScope, MyToken>()
    .AddApplicationStore<OrleansApplicationStore>()
    .AddAuthorizationStore<OrleansAuthorizationStore>()
    .AddScopeStore<OrleansScopeStore>()
    .AddTokenStore<OrleansTokenStore>()
    .AddSigningCertificate(
        assembly: typeof(Startup).GetTypeInfo().Assembly,
        resource: "Resources.SigningCertificateRSA.pfx",
        password: configuration["PfxPassword"])
    .AllowPasswordFlow()
    .AllowAuthorizationCodeFlow()
    .AllowRefreshTokenFlow()
    .AllowImplicitFlow()
    // .RequireClientIdentification()
    .EnableAuthorizationEndpoint("/connect/authorize")
    .EnableIntrospectionEndpoint("/connect/introspect")
    .EnableTokenEndpoint("/connect/token")
    .EnableLogoutEndpoint("/connect/logout")
    .EnableUserinfoEndpoint("/connect/userinfo")
    // During development, you can disable the HTTPS requirement.
    .DisableHttpsRequirement()
    .UseJsonWebTokens()
    .AllowCustomFlow("facebook")
    .AddMvcBinders();

**Comment by kevinchalet** [comment]
Starting with https://github.com/openiddict/openiddict-core/commit/135da2f6114ceb1d3d596190dccc3ef403b74cca, request caching is no longer enabled by default (you must call `EnableRequestCaching()` to enable it).

I suspect your application depends on the request_id dance to work correctly. Can you try enabling request caching to see if it works?

**Comment by Maarten88** [comment]
That was it, thanks. Everything works again after this single line fix. Do I also need to implement/configure a requestcache for scale-out?

**Comment by kevinchalet** [comment]
Glad it works 😄 

Yes, using a "real" distributed cache like Redis or SQL Server is recommended. By default, OpenIddict uses the distributed cache retrieved from the DI container, so it's as easy as calling `services.AddRedis()`.

**Comment by kevinchalet** [comment]
You can read https://docs.asp.net/en/latest/performance/caching/distributed.html for more information.
