### ISSUE TITLE
Where is the IOpenIddictUserStore class?

### ISSUE THREAD

**Issue by dazinator** [openiddict/openiddict-core#260]
I was just searching this repo for `IOpenIddictUserStore` - as I am trying to implement my own one, but I can't seem to spot it anywhere.. Has it been removed recently? Or am I going mental..

**Comment by kevinchalet** [comment]
It was removed as part of the PR decoupling `OpenIddict.Core` from ASP.NET Core Identity.

If you need to provide your own user store, consider inheriting directly from `IUserStore`.

**Comment by dazinator** [comment]
Ok thats really cool, so does that mean that OpenIdDict Core doesn't need me to implement a user store any more in order to function? I have implemented the other custom stores.

**Comment by kevinchalet** [comment]
That's right.

That said, if you use ASP.NET Core Identity to authenticate your users, you'll need it or you won't be able to use Identity's UserManager/SignInManager.

**Comment by dazinator** [comment]
Yep that's cool, cheers.
