### ISSUE TITLE
What is the right way to attach custom claims to identity and access tokens?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#263]
I can either add them in `AuthorizeController.CreateTicketAsync` method or in an override of `SignInManager.CreateUserPrincipalAsync`

@PinpointTownes, which way is better?

**Comment by kevinchalet** [comment]
There's even a third option: creating your own `IUserClaimsPrincipalFactory`.

Simply choose the option you prefer.

**Comment by xperiandri** [comment]
Is there a sample with `IUserClaimsPrincipalFactory`?

**Comment by kevinchalet** [comment]
Ask the ASP.NET Identity folks :smile:
