### ISSUE TITLE
Management UI / Dashboard

### ISSUE THREAD

**Issue by dazinator** [openiddict/openiddict-core#264]
Just wondering if there was any kind of UI for managing / administering clients etc?

**Comment by kevinchalet** [comment]
> Just wondering if there was any kind of UI for managing / administering clients etc?

Nope. That said, it would make a nice contrib project :smile: 

(BTW, it's a duplicate of https://github.com/openiddict/openiddict-core/issues/23)

**Comment by dazinator** [comment]
Got ya! I wouldn't expect any contrib from me on this in the near term, i'm absolutely choca at the moment 😄Maybe one day though.. One sunny afternoon perhaps!

**Comment by kevinchalet** [comment]
So no management UI/dashboard 😄
