### ISSUE TITLE
Authentication TicketId is not the same as the ticet id saved on the refresh token.

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#265]
I overrode the method Task SerializeRefreshToken(SerializeRefreshTokenContext context) to save a session entity in the database identified by the authentication ticket id:

``
        public override async Task SerializeRefreshToken(SerializeRefreshTokenContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var services = context.HttpContext.RequestServices.GetRequiredService<OpenIddictServices<TApplication, TAuthorization, TScope, TToken>>();

            var dbContext = context.HttpContext.RequestServices.GetRequiredService<ApplicationDbContext>();

            var identifier = await services.Tokens.CreateAsync(OpenIdConnectConstants.TokenTypeHints.RefreshToken);

            if (string.IsNullOrEmpty(identifier))
            {
                throw new InvalidOperationException("The unique key associated with a refresh token cannot be null or empty.");
            }

            var requestUserId = context.Request.GetParameter<string>("user_id");

            if (string.IsNullOrEmpty(requestUserId))
            {
                throw new InvalidOperationException("The 'user_id' parameter is not present in the OpenIdConnectRequest.");
            }

            var sessionId = Guid.Parse(identifier);
            var userId = Guid.Parse(requestUserId);
            DeviceType deviceType;

            try
            {
                deviceType = context.Request.GetParameter<DeviceType>("device_type");
            }
            catch (Exception)
            {
                deviceType = DeviceType.Other;
            }

            var deviceId = context.Request.GetParameter<string>("device_id");
            var deviceName = context.Request.GetParameter<string>("device_name");

            // Clean up sessions for this device id
            var sessions = dbContext.Sessions.Include(s => s.Token).Where(s => s.DeviceId.Equals(deviceId, StringComparison.OrdinalIgnoreCase)).ToList();

            var sessionIds = sessions.Select(s => s.Id);

            sessions.ForEach(s =>
            {
                if(sessionIds.Any(i => i.Equals(s.Id)))
                {
                    dbContext.Tokens.Remove(s.Token);
                }
            });
            
            var session = new Session()
            {
                Id = sessionId,
                UserId = userId,
                CreatedAt = DateTime.UtcNow,
                DeviceType = deviceType,
                DeviceId = deviceId,
                DeviceName = deviceName
            };

            dbContext.Sessions.Add(session);

            await dbContext.SaveChangesAsync();

            // Attach the key returned by the underlying store
            // to the refresh token to override the default GUID
            // generated by the OpenID Connect server middleware.
            context.Ticket.SetTicketId(identifier);
        }
``

We are using this for listing all the sessions of the current user.

My controller is like this:

``
                var authInfo = await Request.HttpContext.Authentication.GetAuthenticateInfoAsync(OAuthValidationDefaults.AuthenticationScheme);

                var ticketId = authInfo.Properties.Items.FirstOrDefault(p => p.Key.Equals(".ticket_id"));

                var user = await GetCurrentUserAsync();
                var sessions = _dbContext.Sessions.Include(s => s.Token).Where(e => e.UserId.Equals(user.Id)).ToList();

                var model = new SessionListViewModel();

                sessions.ForEach(s =>
                {
                    if(s.Id.ToString().Equals(ticketId.Value))
                    {
                        model.Current = s.ToViewModel();
                    }else
                    {
                        model.Remote.Add(s.ToViewModel());
                    }
                }); 

                return Ok(model);
``

However, the ticket id I get here does not match the one saved on the refresh token so my current session is always null.

Did I misinterpret the the purpose of the ticket id or is it an issue that they are not matching?

@PinpointTownes

**Comment by kevinchalet** [comment]
Ticket identifiers are unique and are bound to a specific token, not to the entire chain of tokens that are derived from a refresh tokens.

So when you use `var authInfo = await Request.HttpContext.Authentication.GetAuthenticateInfoAsync(OAuthValidationDefaults.AuthenticationScheme);`, you actually retrieve the token identifier associated with the access token, not with the refresh token.

**Comment by jayrulez** [comment]
Ok, thanks for pointing that out.

That gives me another idea, I can bind my session to the chain of tokens from the refresh token by setting a property which stores the session id on the ticket... given the session is already bound to the refresh token.

Do you see any problems with this?

Also, the final step here to achieve what I want is a way to treat the access token is invalid if there is no session entity matching the session property from the ticket for the given access token.

What will I need to override to accomplish this?

Regards

**Comment by kevinchalet** [comment]
> Also, the final step here to achieve what I want is a way to treat the access token is invalid if there is no session entity matching the session property from the ticket for the given access token.

With https://github.com/openiddict/openiddict-core/pull/284, you're now responsible of handling the refresh token requests, so you can easily add that logic in your token action.
