### ISSUE TITLE
How to use my own user and roles store ?

### ISSUE THREAD

**Issue by AbdoDabbas** [openiddict/openiddict-core#266]
Is there a way instead of depending on EntityFramework store to build my own ? I may use DB system which is not supported with EF ?
Is this something to do with `openiddict` library or `asp.net core identity` ?

**Comment by kevinchalet** [comment]
You can definitely create your own OpenIddict stores (you'll need to implement `IOpenIddictApplicationStore` and `IOpenIddictTokenStore`).

If you decide to use ASP.NET Core Identity for the authentication part, you'll also have to implement the `IUser*Store` interfaces.

**Comment by AbdoDabbas** [comment]
@PinpointTownes any samples or articles to read about it in details ?

**Comment by kevinchalet** [comment]
http://lmgtfy.com/?q=ASP.NET+Core+Identity+custom+store

**Comment by replaysMike** [comment]
Funny, Google's first hit is this page (don't you love sarcasm?)

**Comment by kevinchalet** [comment]
> don't you love sarcasm?

I personally do.

On a more serious note, while we can't afford writing and maintaining docs on how to create custom stores for ASP.NET Core Identity, a dedicated documentation page for custom OpenIddict stores is definitely planned: https://github.com/openiddict/openiddict-documentation/issues/9

**Comment by kevinchalet** [comment]
BTW, for those interesting in having a look at non-EF-based OpenIddict stores, Orchard's OpenID module has custom stores that use YesSql (a "document-oriented SQL DB" provider): https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.OpenId/YesSql/Services

**Comment by zeus82** [comment]
I just came across this because I want to use a store that doesn't work with EF, but the above link no longer works.  Is there an update example for using a custom store?

**Comment by skyland-zero** [comment]
> I just came across this because I want to use a store that doesn't work with EF, but the above link no longer works. Is there an update example for using a custom store?

https://github.com/OrchardCMS/OrchardCore/tree/main/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores
