### ISSUE TITLE
Implement Custom UserRole Support

### ISSUE THREAD

**Issue by artem-leonov** [openiddict/openiddict-core#269]
OpenIddictDbContext not support using User  inherited from IdentityUser<TKey, TUserClaim, TUserRole, TUserLogin>. Error is "The type 'User' cannot be used as type parameter 'TUser' in the generic type or method 'OpenIddictDbContext<TUser, TRole, TKey>'. There is no implicit reference conversion from 'User' to 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUser<int>'"

**Comment by kevinchalet** [comment]
`OpenIddictDbContext` doesn't support the longest generic `IdentityDbContext` signature, because it's frankly a mess. Consider inheriting directly from `IdentityDbContext` and configuring the entity sets manually if you need to support this scenario.

**Comment by artem-leonov** [comment]
Ok, thanks
