### ISSUE TITLE
Cookies Problem

### ISSUE THREAD

**Issue by jasdefer** [openiddict/openiddict-core#270]
I am using the Authorization Code Grant for my web app and web api. Sometimes I catch some errors for a few users on the web app, thrown by Microsoft.AspNetCore.Authentication.Cookies: 

> An unhandled exception has occurred: The chunked cookie is incomplete. Only 1 of the expected 2 chunks were found, totaling 4021 characters. A client size limit may have been exceeded.

The cookies seems to be too large for some clients. I use cookie authentication on the client side:

```c#
app.UseCookieAuthentication(new CookieAuthenticationOptions
	{
		AutomaticAuthenticate = true,
		AutomaticChallenge = true,
		LoginPath= new PathString("/Authentication/SignIn"),
		LogoutPath = new PathString("/Authentication/SignOut"),
	});
```

with the following scope on the `OpenIdConnectOptions`: `{ "email", "roles", "offline_access" }`

I am stuck and not sure what I should do now. I cannot recreate this problem, and this problem seems to occur mostly on Safari. Is it better to use the HTML5 Local Storage instead of cookies? I can provide more information about the problem, but I am not sure what is relevant.

**Comment by kevinchalet** [comment]
This is not an OpenIddict-specific issue, as it impacts everyone using the cookies middleware. 

Consider reducing the number of claims you're using to limit the final cookie size. 
You can also set SaveTokens to false.

**Comment by jasdefer** [comment]
Okay thank you for the reply. I will try to look into the cookie middleware. I only use the email, roles and offline_access claim. No further claims.  Can I set the SaveTokens to false, if I need the access token for the communication with the web api? Or will the access token be saved somewhere else, if the SaveTokens parameter is set to false?

**Comment by kevinchalet** [comment]
`email` and `roles` are scopes, not claims.

Concerning your second question, you can't set SaveTokens to false if you need the tokens (obviously).

**Comment by jasdefer** [comment]
Yes this is true, but the email and roles scope is resulting in special claims, if I am not wrong. I didn't add any special claims. The principal of my ticket contains the default claims (role, nameidentifier, jti, id_token, confidential, aud, nonce, at_hash, exp, etc. ).
I am surprised, that the resulting cookie is too big for some browsers. But you are right, this has nothing to do with openiddict. I will ask elsewhere, and maybe I already have an idea for a solution: Adding a custom `ITicketStore` as the `SessionStore` in the `CookieAuthenticationOptions`.
