### ISSUE TITLE
Saml2 support

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#272]
Been reading online and apparently you can use openId as a proxy to use Saml2....is this something that can work in this project?

Sorry if I am completely off, but need saml2 support now for a client and hoping I can use this somehow...

**Comment by kevinchalet** [comment]
Without native support in ASP.NET Core, OpenIddict can't be integrated in a SAML2P/WS-Fed environment.

Though ASP.NET Core doesn't support SAML2P nor WS-Fed (yet), but there are community projects you can try. Take a look at https://github.com/aspnet/Security/issues/1026 for more information.

**Comment by Gillardo** [comment]
Thanks for the advice @PinpointTownes .  I got a feeling i am going to hate trying to work this out

**Comment by kevinchalet** [comment]
@Gillardo good luck! :sweat_smile:
