### ISSUE TITLE
Token provider/retriever/resolver

### ISSUE THREAD

**Issue by NtFreX** [openiddict/openiddict-core#278]
I'm using asp.net **core** web api with an additional signalr host. From looking into this library I found that the accesstoken and stuff is read from the web request header. But I saw that in signalr you cannot set an header and it's excpected from you that you include your access token into the querystring.

No I wondered if I can easily create a token retriever which supports both locations without needing to rewrite the middleware?

**Comment by kevinchalet** [comment]
Yep. Take a look at this sample: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/SignalR/HelloSignalR/Startup.cs#L28

**Comment by NtFreX** [comment]
~~I think this is only for asp.net but not asp.net core?~~ I found the following solution:

```
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    Events = new JwtBearerEvents()
    {
        OnMessageReceived = async (ctx) =>
        {
            ctx.Token = ctx.Request.Query["<qs-name>"];
        }
    }
}
```

**Comment by kevinchalet** [comment]
As you can see... https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/SignalR/HelloSignalR/project.json#L32
