### ISSUE TITLE
Auth Fails When Resource Server did not Provide Token

### ISSUE THREAD

**Issue by mattwcole** [openiddict/openiddict-core#279]
I have been successfully using OpenIddict to secure a simple API where the resource and token endpoints are hosted together. I am having trouble scaling the application horizontally behind a load balancer. It seems that requests for resources made to servers that did not generate the token fail to validate the token, even though they all use the same certificate to sign tokens. Here is my setup code:

```csharp
services.AddOpenIddict<ContactCentreContext>()
    .AddMvcBinders()
    .AllowPasswordFlow()
    .AllowRefreshTokenFlow()
    .EnableTokenEndpoint("/connect/token")
    .AddSignCertificate(new X509Certificate2(_hostSettings.CertFile, _hostSettings.CertPassword));
```

```csharp
app.UseOAuthValidation();
app.UseOpenIddict();
```

And the error on the server:

```
Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'
AuthenticationScheme: "Bearer" was challenged
```

It looks like [UseOAuthIntrospection](https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Startup.cs#L69) may be related, but this method is no longer on the API.

**Comment by kevinchalet** [comment]
The signing credentials are only used for the tokens produced by IdentityModel (i.e the identity tokens, and the access tokens when you use JWT): the opaque tokens use a different serialization mechanism that relies on ASP.NET Core Data Protection, so make sure your key ring is correctly synchronized across your machines: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview

Related post: http://stackoverflow.com/questions/38541772/authorize-via-jwt-token

**Comment by mattwcole** [comment]
Ahh that explains it, thanks for your help!

**Comment by mattwcole** [comment]
I've swapped to JWTs, but this has introduced a new issue.

```
Failed to validate the token <prints-token-here>
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
```

I've checked `.well-known/jwks` and the key ID for my token is present. The modifications I made to my setup are

```csharp
services.AddOpenIddict<ContactCentreContext>()
    .AddMvcBinders()
    .AllowPasswordFlow()
    .AllowRefreshTokenFlow()
    .EnableTokenEndpoint("/connect/token")
    .AddSignCertificate(new X509Certificate2(_hostSettings.CertFile, _hostSettings.CertPassword))
    .UseJsonWebTokens();
```

```csharp
app.UseOpenIddict();
app.UseJwtBearerAuthentication();
```

If it isn't immediately obvious what is wrong here, I can open a new issue.

**Comment by kevinchalet** [comment]
Unlike the aspnet-contrib validation middleware, the JWT bearer middleware developed by MSFT is not configuration-less so `app.UseJwtBearerAuthentication()` will never work if you don't set up the Authority.

Consider using the default token format + the validation middleware or take a look at the ASP.NET Core documentation to see how you're supposed to configure it.

**Comment by mattwcole** [comment]
Thanks again for your help. I was eventually able get JWTs working. I followed the same approach detailed in a [previous issue](https://github.com/openiddict/openiddict-core/issues/181#issuecomment-236651208), but in my case, I had to disable audience validation (I noticed that `aud` was missing from my token).

```csharp
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    Authority = "http://localhost:5000",    // Must match resource parameter on token request.
    RequireHttpsMetadata = false,
    TokenValidationParameters = new TokenValidationParameters
    {
        ValidateAudience = false
    }
});
```

**Comment by kevinchalet** [comment]
Disabling audience validation is not something I'd recommend.

Instead, add `ticket.SetResources("resource_server")` in your `CreateTicketAsync` method (which will set the access token audience) and add `Audience = "resource_server"` in the JWT options.

**Comment by mattwcole** [comment]
I was looking for a way to do this before disabling the validation. Works perfectly!
