### ISSUE TITLE
Implement CORS support

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#28]
In the current bits, the CORS support is far too large (we use wildcards everywhere :smile:) and needs to be fully re-worked.

**Comment by damccull** [comment]
CORS currently installed stuff is being moved to OpenIddict.Security.OpenIddictExtensions.UseCORS() in #38 for whoever gets on this.

**Comment by kevinchalet** [comment]
I removed the default CORS registration. We'll probably want to re-introduce it in the future, but in the meantime, removing it makes OpenIddict much safer.

https://github.com/openiddict/openiddict-core/commit/4199fa23d613bc4d3ff48bbb9d53f0ca1eae4b81

**Comment by ilmax** [comment]
We should allow configuring CORS application dependently, so Ideally we can store all CORS informations

In the past I've done something like the following in a OWIN `OAuthAuthorizationServerProvider`

``` cs
var audience = audienceManager.FindAudienceById(clientId);
context.OwinContext.Set(CorsKeys.AllowedOrigins, audience.AllowedOrigins);
// Some time later
var allowedOrigins = context.OwinContext.Get<string[]>(CorsKeys.AllowedOrigins);
context.OwinContext.Response.Headers.Add("Access-Control-Allow-Origin", allowedOrigins);
```

All the allowed origins were added to the context based on `client_id` some 
The same can be done with the other CORS related settings.

/cc @PinpointTownes  @Bartmax

**Comment by kevinchalet** [comment]
@ilmax do you strongly feel we should have a list of allowed origins? Using an "allow all" policy for all the non-interactive endpoints (configuration, crypto, introspection, revocation, token, userinfo) would make the work item much easier to implement :smile: 

Actually, I'm not convinced using a fine-grained CORS policy is really useful from a security perspective as all these endpoints don't use "automatic authentication schemes" like cookies (the token/revocation/introspection endpoints can use basic authentication, but only for client app authentication, not user authentication).

Also, I'm not sure why we'd treat client apps declaring a public origin differently than the others. IMHO, all client apps must be regarded as potentially hostile.

**Comment by ilmax** [comment]
No strong opinion, we could go with the "allow all" approach and eventually add a more fine graded control, if needed, later on.

**Comment by Ciantic** [comment]
Currently I can't access the WWW-Authenticate on the _client_ side, I think OpenIddict reponds with this:

```
Access-Control-Allow-Origin:*
Content-Type:application/json; charset=utf-8
Date:Fri, 15 Jul 2016 14:38:43 GMT
Server:Kestrel
Transfer-Encoding:chunked
WWW-Authenticate:Bearer error="invalid_token", error_description="The audience is invalid"
```

If I try to call in _browser_ `xhr.getResponseHeader("WWW-Authenticate")` it gives me error: Refused to get unsafe header "WWW-Authenticate"

Which means that the Response given by OpenIddict is incorrect.

I `UseCors()` in other requests and they have headers correctly:

```
Access-Control-Allow-Headers:authorization,www-authenticate
Access-Control-Allow-Origin:*
Date:Fri, 15 Jul 2016 14:38:43 GMT
Server:Kestrel
```

But I think because ASOS is on lower level, this: `Access-Control-Allow-Headers:authorization,www-authenticate` doesn't get there.

**Comment by kevinchalet** [comment]
> Currently I can't access the WWW-Authenticate on the client side, I think OpenIddict reponds with this:

Very unlikely. Sounds like a challenge response returned by the JWT middleware.
Since CORS support was completely removed from the latest bits, so it's likely an issue with your own policy.

**Comment by shaunluttin** [comment]
> IMHO, all client apps must be regarded as potentially hostile.

In that case, `AllowAnyOrigin` makes the most sense. Then constrain the allowed headers and methods.

**Comment by jersiovic** [comment]
Any advance on that?

**Comment by kevinchalet** [comment]
Unfortunately, the current model of the CORS stack in ASP.NET Core 1.x and 2.x doesn't allow us to implement this feature safely as we have no way to ensure the CORS policy chosen by OpenIddict won't be ignored/overridden if the developer calls `app.UseCors(... policy... );` after the CORS headers were applied by OpenIddict using its own policies (in this case, the authorization or the logout endpoint might be included in the CORS policy, which would be terrible).

Instead, we're doing to add documentation indicating how to protect the authorization endpoint action and ensure it's not included in a CORS policy.
