### ISSUE TITLE
"client_id missing" error when disabling request caching 

### ISSUE THREAD

**Issue by pealmeid** [openiddict/openiddict-core#280]
Hello,

I've been studying the sample code for OpenIddict and I came across an odd behavior that I don't know if it is a bug or by design.

To reproduce, simply run the `Mvc.Server/Mvc.Client` samples with the `EnableRequestCaching()` line in `ConfigureServices` (file `Startup.cs` for the `Mvc.Server` sample) commented out.

When I do it I get the following error immediately after authorizing access (after logging in with email and password):

![img](https://cloud.githubusercontent.com/assets/6384219/20648701/2c3e2ee4-b495-11e6-8b09-ef981fe45df8.jpg)

The log output for the error is:

`AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Error: The authorization request was rejected because the mandatory 'client_id' parameter was missing.`

However, if you check the URL in the browser, the "client_id" is explicitly mentioned (which makes sense, because the request is no longer cached):

![img](https://cloud.githubusercontent.com/assets/6384219/20648686/f0bf5992-b494-11e6-9443-79e3ab9ede0b.jpg)

I checked the source code and noticed that when request caching is disabled the `OpenIdConnectRequest` has an empty `RequestId` field  and the corresponding HTTP request doesn't have a `request_id` field.

So I guess my question(s) is(are):
* Is using `EnableRequestCaching()` mandatory?
* If not, shouldn't the sample code be able to pick up `client_id` from the URL?
* And if so, shouldn't the error message mention `missing request_id` instead of `missing client_id`?

Thanks in advance and congratulations on an excellent project that has helped me enormously in learning both ASPNET Core and Authentication/Authorization/OpenID.

**Comment by kevinchalet** [comment]
Note: it's always better to post a tiny comment indicating how you solved your issue, as it might interest other people.

> Is using EnableRequestCaching() mandatory?

No, but the MVC sample requires it, because it uses the `request_id` parameter to store the request details across the login/external login pages.

> If not, shouldn't the sample code be able to pick up client_id from the URL?

When sending a POST authorization request, the parameters must be form-urlencoded. Here, they are in the query string, so this can't work. To make the sample work, you'd have to copy the authorization parameters to make sure they are correctly flowed.

See https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Views/Shared/Authorize.cshtml#L14-L16 for an example.

> Thanks in advance and congratulations on an excellent project that has helped me enormously in learning both ASPNET Core and Authentication/Authorization/OpenID.

Glad you like it :smile:

**Comment by pealmeid** [comment]
Thanks for the reply! I figured out how to make it work and was about to add a comment describing it, but you beat me to it...

My solution was basically the same but not as elegant, I added all the parameters to `AuthorizeViewModel` and passed them to the View individually instead of using the `@foreach (var parameter in Model.Item1.GetParameters())` loop.

Once again, thanks a lot for your work and support!

**Comment by kevinchalet** [comment]
> My solution was basically the same but not as elegant, I added all the parameters to AuthorizeViewModel and passed them to the View individually

That's the right thing to do :smile: 
The ASOS sample doesn't use a view model because it wanted it to be as tiny as possible, so it uses tuples instead,
