### ISSUE TITLE
Get Token Success,but Authorization error invalid_grant:The user profile is no longer available

### ISSUE THREAD

**Issue by Lissbrict** [openiddict/openiddict-core#281]
- get token: /api/connect/token

post man
prarm:
`
client_id:9dced70411684af890f1b6af12f06f7c
grant_type:password
username:dengyuehua
password:123456?zzA
scope:offline_access
`
result:
`
{
  "token_type": "Bearer",
  "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IlNDLUFGSU5WM0JYSkdRRFFDSjNUM0wxRUhGTE1FX1RRTUxFNlZQLU4iLCJ0eXAiOiJKV1QifQ.eyJ1bmlxdWVfbmFtZSI6ImRlbmd5dWVodWEiLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6ImUzNWYwZGU1LTNmZDMtNDRmZi05YWJhLWU1ZmM0NTIxZDI3YyIsInJvbGUiOlsi5Y-45py6Iiwi5LmY5a6iIl0sImp0aSI6ImM5OWYzZjYzLWRiYTItNDA3OC05NmU0LWIzYTc0NGNiYjZkOSIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyIsInN1YiI6IjEyODk5MTMxMDM4MDYyMzk2MTIiLCJhenAiOiI5ZGNlZDcwNDExNjg0YWY4OTBmMWI2YWYxMmYwNmY3YyIsIm5iZiI6MTQ4MDMyMjUyNCwiZXhwIjoxNDgwMzI0MzI0LCJpYXQiOjE0ODAzMjI1MjQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6Mjc3MS8ifQ.VKyyNYlXsW6gjPU7ycUtrc8xnO2ANlOVJKic2CNU2ZtHmYWzrY7JGqd6hThiEkw5p5gZGK6LGuyRlSCUA8XRK0aH0sNYv9DJixqrXDATA4FSHc5ZP3tNq1wpYr-EDJSkxJKkR1tBGn0jAt_iFLz1jamebDcYklrufn6mGMT_0xM8LMuaMoA1ItnBuVSG1z6qnvwy3RsPU3u4yKeB8AQd7nqcrWC06Tk1JE1q-0P_jBu1nM1BCH6DqzYAtcxkEWexIJAnPY6r-J6-gBtGi10NIZWHq7sCXXOsrro3ltEcDOgJutejcnb7O6V2WCWfXPph_yGxwALm7Vgvf3y63z78GA",
  "expires_in": 1800,
  "refresh_token": "CfDJ8EvieMEQWABBtDg7DZ3OEQoP0ewuZ70_0fUGGrAgUKNXOOiJSlRnQsm39OwvWo9wbLJqGD3QIl6zVI2jmCT2fJHbhDb7lWsczLzfzLCIttvycAUKKM8Jp0JqqAb72sStnAHK2pUm0HLBdiKL3GoAMll8JqDhYfJRXmP7FEyolhX4oaghoE2OspzvSjT4Gm3SiFVJKBqspacMrIYNiu3Dk51M4iff5wHbeuAe7Ond9vwpjP5ZrpcRSSsdIRiR_owKXVlXkCncg8j6_wP2OnTMy5f7yY4OifgurBsCX04SVeIHPx-nNV7Wg-J93wK5jbMZJSfKa61Nz4_7aCjN8jsfYGNnufPNzTUK2NsWuVtjmo5TREIoXtwsI9nWvDvfLXiV-1qfJP_pt2OJIhGAkBkUYSIUKAQ8Isus-CHE_3V46KvSfp8wTlhp9b_A1K9avUW21derYeYv8S3QvNiWuoWh3TP1Aba4pC3ESXCHKU6jkhSqpSEAxK4CQCsrk7MRA83Ly1wG-3-FFc1RPMNX1JRSvlsZulVQTYOvitgXq5O-YYJm8oYUUkvt3tArlZttddOjbY8u5yjwl9s9yFC8kT8Wp3YMsr98id8ufRI7e4ajh0wtU2VbF4q2v6cQB7mQqnMMwR93rwABEDapNyGlbbXIanUzkhMekv0grdzu0_fX0ucjCukyJYiVcj3hUAiaW2t-pF4g20kyYowvqxpSPUviFFe5IKsYKeL1HDmSNB-Cx1Zt4NII7f3dvp_KzHFVm7LEtTRrarYOmmreXGJQEEQsZRPMKtWj_GsgaoucTTrV5U7656Kf_bA4rigbNb6tK-7TUueekpasb61CDUxNODSqL5PNg1MpaHUo9b2t_PsaIZK4k64Rr7uZRXFR58ps3Bs1FeKK8qMZhLREOsbeccQICl7TImTKIBW548CSZgDOPZrQrw-AP4CnCt5gBRaw_xx4qsmfP5He6cpsiXPNgHhNTB0zXe9kKaRKBrx_0MEGSWf3LbAoV467iGkXxenXkBLfNiNd4l4mhNPyZqzyhR-gV-3fR-8nMoPxpp7zvXyoj1YBKWBeUn89j_HHpD-EWtif3cwXCLaAI7LHRJPJF7dmHErD_LWbeYi5VS4OgjXpRu6m9MPZfFbjmPDdJAuBAsDBfYcH5Hjl8NYk02wTeYp29EI"
}
`
- but Authorization error invalid_grant:The user profile is no longer available

Authorization  code
`
heraders 
- Authorization:Bearer access_token 
`

**Comment by kevinchalet** [comment]
This error is returned by the sample when the user profile was not found in the database: https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AccountController.cs#L44-L50.
