### ISSUE TITLE
Using OpenIddict to secure Web API

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#285]
Hi,
I have a simple SSO website setup using .NET Identity Core and OpenIddict. 

I'd like to expose a method to relying parties to allow adding a user. I've created the method and added the [Authorize] attribute and I can now create an OAuth2 token and call the CreateUser method via Postman. However, this means that any authenticated user can call the method which I don't want. I've added [Authorize(Roles= "API")] but it does not work, the token doesn't seem to hold info on the roles. 

Has anyone implemented anything like this?

**Comment by kevinchalet** [comment]
It would help if you share your claims generation code. Assuming you're using the client credentials grant to authenticate your API, you should be able to add a specific claim indicating whether the token represents a user or an application.

Then, you could use the authorization stack to set up an authorization policy requiring this specific claim (e.g `policy.RequireClaim("caller_type", "application")`.

**Comment by daver77** [comment]
I'm using the tools in Postman to get the token. I was using 'Authorization Code' grant type, I've switched to Client Credentials but Postman gives the error "error getting access token from client_credentials flow. Could not send request". I have .AllowClientCredentialsFlow() in ConfigureServices.

**Comment by kevinchalet** [comment]
Have you implemented client credentials support in your token endpoint action?

**Comment by daver77** [comment]
Ah, I have now :)

**Comment by daver77** [comment]
I've added a Role to CreateTicket and added the attribute [Authorize(Roles = "API")] to my method, it works but i'm guessing it's not the best way to implement it.

`        
            identity.AddClaim(ClaimTypes.Role, "API",
                OpenIdConnectConstants.Destinations.AccessToken,
                OpenIdConnectConstants.Destinations.IdentityToken);      
        }`

**Comment by daver77** [comment]
Updated the API method attribute to...
`[Authorize(Policy = "API Access")]`
and added to startup...
`options.AddPolicy("API Access",
                    policy => policy.RequireClaim(ClaimTypes.Role, "API"));`

This setup would give every application access to my API though. Is there anything available to store claims per application?

**Comment by kevinchalet** [comment]
> Is there anything available to store claims per application?

You can easily implement that in `CreateTicketAsync`.

**Comment by daver77** [comment]
Do you mean like this?
`if (application.ClientId=="app1"){// add claim}`
I was hoping for something database driven

**Comment by shao200** [comment]
I can't test the zirku project at all, can't access the api through the Client
