### ISSUE TITLE
How to Logout / mark Token invalid (Question)

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#287]
Hey there!
I am a little stuck here:
When just using Token-based-authentication [ no cookies ], what would be the right way to logout/signout/ tell the server the access_token is invalid?

`return SignOut(OpenIdConnectServerDefaults.AuthenticationScheme);`

does not seem to work, as the access_token still works...

I do get a 

> OpenIddict.Infrastructure.OpenIddictProvider: Information: The logout request validation process was skipped because the post_logout_redirect_uri parameter was missing.

Warning. But that does not mean the entire logout-process is skipped, does it?

Thanks a lot for your amazing work!

**Comment by kevinchalet** [comment]
Hey.

Revoking an access token is not supported, for performance reason (as you'd have to make a DB roundtrip for each API call). That's the reason why their lifetime is short (30 minutes by default).

To revoke a refresh token, don't use the logout endpoint (which is only meant to delete cookies during an interactive workflow like the code flow). Instead, use the revocation endpoint, as described in https://tools.ietf.org/html/rfc7009.

> Warning. But that does not mean the entire logout-process is skipped, does it?

It's not a warning, just an information.

> Thanks a lot for your amazing work!

Thanks for the kind words! :smile:

**Comment by ghost** [comment]
Ah, alright!  Thank you for clarifying that!

**Comment by xperiandri** [comment]
Is custom revocation logic required?
