### ISSUE TITLE
Cannot create a DbSet for 'OpenIddictApplication' because this type is not included in the model for the context

### ISSUE THREAD

**Issue by rajivcodes** [openiddict/openiddict-core#289]
When I click on the client web app signin button, it throws this error

It redirects to the server and thriws this error:
InvalidOperationException: Cannot create a DbSet for 'OpenIddictApplication' because this type is not included in the model for the context.
Microsoft.EntityFrameworkCore.DbContext.Set<TEntity>()

Broader Picture: 
What I am trying to do is use the server sample to create an API app, So how will i convert this into an API app?
Then create a new xamarin mobile app that will use these APIs to get data.

Any help and suggesstions will be highly appreciated!

RP

**Comment by kevinchalet** [comment]
Does your DB context inherit from `OpenIddictDbContext`?

Please share your `ApplicationDbContext` signature and your OpenIddict configuration.

**Comment by rajivcodes** [comment]
public class ApplicationDbContext : OpenIddictDbContext<ApplicationUser, ApplicationRole, long>
where can i find OpenIddict configuration?
If this is what you mean?

            services.AddOpenIddict<ApplicationDbContext>()
            // Register the OpenIddict services, including the default Entity Framework stores.            
                // Register the ASP.NET Core MVC binder used by OpenIddict.
                // Note: if you don't call this method, you won't be able to
                // bind OpenIdConnectRequest or OpenIdConnectResponse parameters.
                .AddMvcBinders()

                // Enable the authorization, logout, token and userinfo endpoints.
                .EnableAuthorizationEndpoint("/connect/authorize")
                .EnableLogoutEndpoint("/connect/logout")
                .EnableTokenEndpoint("/connect/token")
                .EnableUserinfoEndpoint("/Account/Userinfo")

                // Note: the Mvc.Client sample only uses the code flow and the password flow, but you
                // can enable the other flows if you need to support implicit or client credentials.
                .AllowAuthorizationCodeFlow()
                .AllowPasswordFlow()
                .AllowRefreshTokenFlow()

                // Make the "client_id" parameter mandatory when sending a token request.
                .RequireClientIdentification()

                // During development, you can disable the HTTPS requirement.
                .DisableHttpsRequirement()

                // When request caching is enabled, authorization and logout requests
                // are stored in the distributed cache by OpenIddict and the user agent
                // is redirected to the same page with a single parameter (request_id).
                // This allows flowing large OpenID Connect requests even when using
                // an external authentication provider like Google, Facebook or Twitter.
                .EnableRequestCaching()

                // Register a new ephemeral key, that is discarded when the application
                // shuts down. Tokens signed using this key are automatically invalidated.
                // This method should only be used during development.
                .AddEphemeralSigningKey();

**Comment by kevinchalet** [comment]
As mentioned in the README, you must use the `services.AddOpenIddict<ApplicationDbContext, long>()` overload when using a custom key type.

**Comment by rajivcodes** [comment]
Ok so now it gives me this error when I click on "welcome Anonymous" signin.
Ooooops, something went really bad! :(
but it definitely helped get rid of the previous error. Thanks!

**Comment by rajivcodes** [comment]
I will close the issue as I think the main problem was resolved. Thank you very much for your help!

**Comment by azim-bl** [comment]
I am getting the same error like this. 

Here is my configuration:




           public void ConfigureServices(IServiceCollection services)
            {
            services.AddMvc().AddXmlSerializerFormatters();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.AddDbContext<ApiHubContext>(options =>
            {
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"));
                options.UseOpenIddict<ApplicationClient, ApplicationAuthorization, ApplicationScope, ApplicationToken, long>();
            });
            services.AddOpenIddict()
                .AddCore(options =>
                {
                    options.UseEntityFrameworkCore().UseDbContext<ApiHubContext>();
                })
                .AddServer(options =>
                {
                    options.UseMvc();
                    options.EnableTokenEndpoint("/connect/token");
                    options.AllowClientCredentialsFlow().AllowRefreshTokenFlow();
                    options.SetAccessTokenLifetime(TimeSpan.FromMinutes(10));
                    options.SetRefreshTokenLifetime(TimeSpan.FromMinutes(4));
                    options.AcceptAnonymousClients();
                })
                .AddValidation();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = OpenIddictValidationDefaults.AuthenticationScheme;
            });
        }

My Db Context:
        

         public class ApiHubContext : DbContext
         {
        public ApiHubContext(DbContextOptions options)
             : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            //builder.UseOpenIddict();
            builder.UseOpenIddict<ApplicationClient, ApplicationAuthorization, ApplicationScope, ApplicationToken, long>();
        }
    }

    public class ApplicationClient : OpenIddictApplication<long, ApplicationAuthorization, ApplicationToken>
    {
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
    }

    public class ApplicationAuthorization : OpenIddictAuthorization<long, ApplicationClient, ApplicationToken> { }
    public class ApplicationScope : OpenIddictScope<long> { }
    public class ApplicationToken : OpenIddictToken<long, ApplicationClient, ApplicationAuthorization> { }

I am trying to add some extra field in OpenIddictApplication and this was successfully updated. But when i request for token i got this error
**Cannot create a DbSet for 'OpenIddictApplication' because this type is not included in the model for the context.**

I have checked this link : https://github.com/openiddict/openiddict-core/issues/434

**Comment by cryo75** [comment]
I also added a couple of properties to the application and I get the same exception when starting the server. How was this problem solved?

**Comment by kevinchalet** [comment]
@cryo75 see https://documentation.openiddict.com/integrations/entity-framework-core.html.

**Comment by cryo75** [comment]
Thanks it works now.
