### ISSUE TITLE
Customize Views

### ISSUE THREAD

**Issue by Bartmax** [openiddict/openiddict-core#3]
Currently views are loaded as embedded resources that cannot be changed without affecting the source package.

Ideally we could use something like this: https://github.com/aspnet/FileSystem/issues/49 if it's ever implemented.

**Comment by kevinchalet** [comment]
Will be fixed via https://github.com/openiddict/core/pull/25 :dancers:

**Comment by kevinchalet** [comment]
Wooops, forgot to close this ticket :smile: 

Merged: https://github.com/openiddict/core/commit/7795fbe7958e2683330a94606fd529c79d3daae6
