### ISSUE TITLE
Rename Application model ID property for better inheritance

### ISSUE THREAD

**Issue by damccull** [openiddict/openiddict-core#30]
@PinpointTownes I would like to suggest renaming OpenIddict.Models.Application.ApplicationID to OpenIddict.Models.Application.Id to allow for better inheritance in EF. If I name my class something different (MyApplication), then I can't use ApplicationID as the EF id because EF expects it to be named either "Id" or "MyApplicationId". There is an annotation you can put on the field to tell it which one to use, but that would have to be done on the parent class (Application) or overridden, and isn't as pretty or concise.

**Comment by kevinchalet** [comment]
Good idea! Wanna submit a PR? :smile:

**Comment by damccull** [comment]
Sure! Give me a day or two.

**Comment by damccull** [comment]
Pull request https://github.com/openiddict/core/pull/31

**Comment by kevinchalet** [comment]
Merged, thanks: https://github.com/openiddict/core/commit/592cca06f07cd0e69186b96b8ca7810d27bd71e8 :clap:
