### ISSUE TITLE
OpenIdDict & Ionic 2

### ISSUE THREAD

**Issue by frankps** [openiddict/openiddict-core#300]
Dear,
We're creating a mobile app with Ionic 2 and integrated OpenIdDIc successfully with client credentials & tokens. Nice work!
But: I woud like to convert it to the implicit flow (so we can use Facebook & Google)
No I wonder what the redirect_uri should be for apps.
Can somebody help?
Thanks, Frank

**Comment by kevinchalet** [comment]
I'd personally go with the code flow. Don't hesitate to take a look at the Cordova sample for ASOS to see how it works: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/tree/master/samples/Cordova.
