### ISSUE TITLE
AddStore<T> methods all throw exceptions when using a sub-class of OpenIddictToken<TKey>

### ISSUE THREAD

**Issue by scionwest** [openiddict/openiddict-core#309]
I have a custom Token class I've created that subclasses `OpenIddictToken<TKey>` and I'm using it in a custom `OpenIddictTokenStore<TToken>` implementation.

### Token

```c#
public class JwtToken : OpenIddictToken<Guid>
{
    public DateTime CreatedAt { get; set; }
    public DateTime Expiration { get; set; }
}
```

### Store

```c#
public class TokenStore : IOpenIddictTokenStore<JwtToken>
{
    public Task<string> CreateAsync(string type, CancellationToken cancellationToken) { // .... }
    public Task<JwtToken> FindByIdAsync(string identifier, CancellationToken cancellationToken) { // .... }
    public Task RevokeAsync(JwtToken token, CancellationToken cancellationToken) { // .... }
}
```

When I register the token using the `OpenIddictBuilder`, it throws an exception at runtime telling me that I've not implemented the `IOpenIddictTokenStore<TToken>` interface. Digging around [I noticed that this exception](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/OpenIddictBuilder.cs#L277-L280) is thrown if the `OpenIddictBuilder.TokenType` does not match the token type associated with the custom store. In this case, the default is the built-in token type, which won't be the same as my inherited Type.

The following extension method shows how I'm using the `OpenIddictBuilder`.

```c#
public static IServiceCollection AddSecurity(this IServiceCollection services)
{
    // Configure the OpenIddict to use bearer token auth.
    return services.AddOpenIddict(builder =>
    {
        builder
            .AddApplicationStore<ApplicationStore>()
            .AddTokenStore<TokenStore>()
            .AddMvcBinders()
            .EnableTokenEndpoint("/connect/token")
            .AllowPasswordFlow()
            AddEphemeralSigningKey();
            DisableHttpsRequirement();;
    });
}
```

I also noticed that the `OpenIddictBuilder.TokenType` has the `[EditorBrowsable]` attribute applied preventing it from being seen in intellisense. If I manually assign the `TokenType` myself, this exception goes away but it is hidden and no one would know that it existed unless they looked at the source.

```c#
public static IServiceCollection AddSecurity(this IServiceCollection services)
{
    // Configure the OpenIddict to use bearer token auth.
    return services.AddOpenIddict(builder =>
    {
        builder.TokenType = typeof(JwtToken);
        builder
            .AddApplicationStore<ApplicationStore>()
            .AddTokenStore<TokenStore>()
            .AddMvcBinders()
            .EnableTokenEndpoint("/connect/token")
            .AllowPasswordFlow()
            AddEphemeralSigningKey();
            DisableHttpsRequirement();;
    });
}
```

It appears that this will be a problem for every one of the store interfaces, if they are subclassed and do not use the built-in Types. Could this be changed so that the builder methods take the Token/Application/Authorization/etc type as well? The implementation could look like:

```c#
public OpenIddictBuilder AddTokenStore<TStore, TToken>() where TStore : class
    => AddTokenStore(typeof(TStore), typeof(TToken));

public virtual OpenIddictBuilder AddTokenStore([NotNull] Type storeType, [NotNull] Type tokenType) {
    if (storeType == null) {
        throw new ArgumentNullException(nameof(storeType));
    }

    this.TokenType = tokenType;
    var contract = typeof(IOpenIddictTokenStore<>).MakeGenericType(this.TokenType);
    if (!contract.IsAssignableFrom(storeType)) {
        throw new InvalidOperationException("Custom stores must implement IOpenIddictTokenStore.");
    }

    Services.AddScoped(contract, storeType);
     return this;
}
```
With the API usage looking like this.

```c#
public static IServiceCollection AddSecurity(this IServiceCollection services)
{
    // Configure the OpenIddict to use bearer token auth.
    return services.AddOpenIddict(builder =>
    {
        builder
            .AddApplicationStore<ApplicationStore, CustomApp>()
            .AddTokenStore<TokenStore, JwtToken>()
            .AddMvcBinders()
            .EnableTokenEndpoint("/connect/token")
            .AllowPasswordFlow()
            AddEphemeralSigningKey();
            DisableHttpsRequirement();;
    });
}
```

I can work on that and issue a PR if that change is feasible to you.

**Comment by kevinchalet** [comment]
When using a custom entity (derived from the default entities or not), you need to use the generic `services.AddOpenIddict()` overload, that will set the `OpenIddictBuilder` type properties for you: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/OpenIddictExtensions.cs#L52.

**Comment by scionwest** [comment]
Thanks, I missed those overloads.
