### ISSUE TITLE
Single Sign Out

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#312]
Hi,
Are there any plans to implement "Single Sign Out"? The front-channel spec seems to be the most obvious to implment as we hold the logout URL's.

http://openid.net/specs/openid-connect-frontchannel-1_0.html

**Comment by kevinchalet** [comment]
ASOS/OpenIddict already offer an `end_session_endpoint` (known as the "logout endpoint"), but if you want to implement distributed logout, it's currently up to you to track the relying parties the user logged into and return a page containing the iframes pointing to the `frontchannel_logout_uri` of all the clients.

https://github.com/openiddict/openiddict-samples/blob/master/samples/ImplicitFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L69-L79

**Comment by daver77** [comment]
Thanks

Will ASOS replace OpenIddict once it hits RC?

**Comment by daver77** [comment]
Thanks. Are there any methods to return all OpenIddictApplications or would I need to add that?

**Comment by kevinchalet** [comment]
> Will ASOS replace OpenIddict once it hits RC?

No. OpenIddict will continue to use ASOS to handle the OIDC protocol details, and there's absolutely no plan to merge them, as they have different objectives and different audiences (ASOS is really for advanced users).

> Thanks. Are there any methods to return all OpenIddictApplications or would I need to add that?

Not yet, but I'll end up adding one at some point, as Orchard2's OpenID module needs a similar thing.

**Comment by luboid** [comment]
Hi @kevinchalet 

I'm trying to implement SSO and want to sign out all dependent apps which use cookie auth schemas. I saw the link you post above but it isn't valid anymore.  Can you point out the new location of the sample?

**Comment by dahovey** [comment]
@kevinchalet The link to sample is out-of-date (404). Is there any updated guidance/documentation/samples on implementing front-channel logout for signed-in applications?
