### ISSUE TITLE
Feature Request: Multiple Redirect Uri's for the same client Id

### ISSUE THREAD

**Issue by josh-sachs** [openiddict/openiddict-core#316]
It would be a nice (default) feature to be able to white-list more than 1 redirectUrl for a given clientId.  Google Developer API console does this for example. 

Sorry for the brevity, I think the request is pretty straight forward.  Obviously trash it if it doesn't seem worth doing.

**Comment by kevinchalet** [comment]
See http://stackoverflow.com/questions/39025834/register-multiple-redirecturis for the reason why it's deliberately not supported.

That said, if you have a concrete use case where such a feature would be important, I'm all ears :smile:

**Comment by josh-sachs** [comment]
Sure, I'll give it a go :)

We have development, staging and production versions of the same app - all requiring different application keys (currently).  In order to manage deployments, I have to do an ENVIRONMENT call prior to loading our SPA so that the server can dynamically issue a clientId based on the detected environment.  This is undesirable overhead and delays time to first interaction. 

Even more, we have different "local" host names that people can use to debug various mobile devices and things against their respective local development instances (using hamachi).  Every time we get a new developer, with a new local VPN we have to create a new host name, new application, and new ENVIRONMENT modification. 

Ideally we could have one clientId and whitelist all the various environments that application is authorized to exist within.  I think this conforms with the spirit of the redirectUri parameter within the spec.

**Comment by kevinchalet** [comment]
This makes sense, tho' I'm not sure I want to encourage the scenario you describe, as using the same application registration with both production and testing environments is not considered as "good practice" (the client secrets used in production shouldn't be used during testing, as they may be leaked).

The good news is that allowing users to control how the `redirect_uri` is validated is definitely supported, as `OpenIddictApplicationManager.ValidateRedirectUriAsync` can be replaced with your own logic. For that, subclass `OpenIddictApplicationManager` and override `ValidateRedirectUriAsync`. Then, register your manager in the DI container using `services.AddOpenIddict().AddApplicationManager<CustomManager>()`.

**Comment by kevinchalet** [comment]
> I think this conforms with the spirit of the redirectUri parameter within the spec.

Sure it does, but it's worth noting that OpenIddict's objective is to encourage people to do the right thing, which often implies using stricter rules than the ones defined by the specification.

People who feel more comfortable with the protocol details are encouraged to use ASOS (that gives you full control to validate the `redirect_uri`).

**Comment by josh-sachs** [comment]
`using the same application registration with both production and testing environments is not considered as "good practice" (the client secrets used in production shouldn't be used during testing, as they may be leaked).`

I'm not sure what there is to be leaked.  The clientId is included in the SPA regardless of environment and is not secret, the redirect_uri identifies endpoints that the Auth Server is allowed to hand tokens issued against that clientId back to.   

Obviously you're more of an expert in this than I am.  I'll look into the ValidateRedirectUriAsync override you mentioned.   Thanks for the discussion.

**Comment by kevinchalet** [comment]
Sure, in your case there's no secret because it's a public client, but if we introduce the ability to register multiple addresses, people will want to use it with confidential clients too.

**Comment by Biarity** [comment]
What if I need to have a different redirect_uri specifically for silent logins? This is usually required to reduce load when using iframes - see https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow.

**Comment by kevinchalet** [comment]
It's now supported: `OpenIddictApplicationDescriptor.RedirectUris` is a collection that allows you to register multiple uris.

**Comment by mrukas** [comment]
@kevinchalet: I just noticed this old post and found out that it is not possible to add relative redirect uris via the OpenIddictApplicationManager. Is there any way besides overriding the ValidateAsync method?
I know that these would not be spec compliant.

**Comment by kevinchalet** [comment]
@mrukas as soon as you need to do non-standard stuff, you need to use the events model: https://documentation.openiddict.com/guides/index.html#events-model

**Comment by mrukas** [comment]
@kevinchalet: I was talking about adding the redirect uris via ApplicationManager. I could not find a way how to change the validation of the uris without overriding the ValidateAsync method. I think you were talking about validating the redirect uris during an HTTP call. :)
