### ISSUE TITLE
Temporary ticket / Short expiry date ticket

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#317]
Our application allows users to sign in as per normal, so will refer to that as a NORMAL ticket.  Also in our application, we need to be able to allow a user to obtain a resource, as if they were another user (impersonate), refer to this as IMPERSONATE ticket.

Is there a way to make an IMPERSONATE ticket a shorter life span than a normal ticket?  Can i add something to this ticket to say its an impersonate ticket, and thus a user should not be able to use this ticket to try and connect to resources that they are not supposed to??

So far in my code, i have managed to create an IMPERSONATE ticket in my .net code, by using a rest client to connect to my application (itself) and use ASSERTION grant as explained [here](http://stackoverflow.com/questions/40257981/exchanging-a-google-idtoken-for-local-openid-token-c-sharp/40260960#40260960), passing in the username to login as in the assertion parameter.  

This all works, but currently the accessToken returned is the same as if the user had logged in.  I dont see anywhere that i can add a claim the to the ticket, or be able to set a shorter expiry time on the ticket from the code in my AuthorizationController.cs as below (which is same as samples), so currently this ticket could be used to access other resources which i dont want.  Once i have a claim in the ticket to state it is "different" i can then add the appropriate code to my authorization handlers, to check if the user can access that resource being validated.

Any tips on how to 

```
private async Task<AuthenticationTicket> CreateTicketAsync(OpenIdConnectRequest request, User user)
{
	// Set the list of scopes granted to the client application.
	// Note: the offline_access scope must be granted
	// to allow OpenIddict to return a refresh token.
	var scopes = new[] {
		OpenIdConnectConstants.Scopes.OpenId,
		OpenIdConnectConstants.Scopes.Email,
		OpenIdConnectConstants.Scopes.Profile,
		OpenIdConnectConstants.Scopes.OfflineAccess,
		OpenIddictConstants.Scopes.Roles
	}.Intersect(request.GetScopes());

	// Create a new ClaimsPrincipal containing the claims that
	// will be used to create an id_token, a token or a code.
	var principal = await _signInManager.CreateUserPrincipalAsync(user);

	// Note: by default, claims are NOT automatically included in the access and identity tokens.
	// To allow OpenIddict to serialize them, you must attach them a destination, that specifies
	// whether they should be included in access tokens, in identity tokens or in both.

	foreach (var claim in principal.Claims)
	{
		// Always include the user identifier in the
		// access token and the identity token.
		if (claim.Type == ClaimTypes.NameIdentifier)
		{
			claim.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
								  OpenIdConnectConstants.Destinations.IdentityToken);
		}

		// Include the name claim, but only if the "profile" scope was requested.
		else if (claim.Type == ClaimTypes.Name && scopes.Contains(OpenIdConnectConstants.Scopes.Profile))
		{
			claim.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
								  OpenIdConnectConstants.Destinations.IdentityToken);
		}

		// Include the role claims, but only if the "roles" scope was requested.
		else if (claim.Type == ClaimTypes.Role && scopes.Contains(OpenIddictConstants.Scopes.Roles))
		{
			claim.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
								  OpenIdConnectConstants.Destinations.IdentityToken);
		}

		// The other claims won't be added to the access
		// and identity tokens and will be kept private.
	}

	// Create a new authentication ticket holding the user identity.
	var ticket = new AuthenticationTicket(
		principal, new AuthenticationProperties(),
		OpenIdConnectServerDefaults.AuthenticationScheme);

	// Set resource
	ticket.SetResources(new string[] { _appSettings.Url + _appSettings.BasePath });

	// Set scopes
	ticket.SetScopes(scopes);

	return ticket;
}
```

**Comment by kevinchalet** [comment]
Read https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/ to see how you can add your own claims.

To set the access token lifetime, use `ticket.SetAccessTokenLifetime(...)`.
