### ISSUE TITLE
Add new APIs to allow listing the existing OpenID applications

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#320]
https://github.com/openiddict/openiddict-core/issues/312#issuecomment-270163621

**Comment by pholly** [comment]
I use Controller Scaffolding to view and edit OpenID Applications.
To get around the limitation of being able to scaffold models that are not in your own projects, I subclass `OpenIddictApplication` and create a MVC Scaffold controller using that as the model. Once its scaffolded I change all references to my subclass back to `OpenIddictApplication`.

**Comment by xperiandri** [comment]
@pholly, maybe it would be nice to contribute this to a sample?
@PinpointTownes, do you plan to include it into OpenIddict itself? Or a separate package?

**Comment by kevinchalet** [comment]
@xperiandri we now have a `ListAsync()` method: https://github.com/openiddict/openiddict-core/issues/464#issuecomment-331437806

That said, we'll probably add a simpler overload taking `count` and `skip` parameters like the one the Orchard module has.

**Comment by kevinchalet** [comment]
@pholly @xperiandri a new overload will be introduced as part of https://github.com/openiddict/openiddict-core/pull/480.

```csharp
/// <summary>
/// Executes the specified query.
/// </summary>
/// <param name="count">The number of results to return.</param>
/// <param name="offset">The number of results to skip.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
/// <returns>
/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
/// whose result returns all the elements returned when executing the specified query.
/// </returns>
Task<TApplication[]> ListAsync([CanBeNull] int? count, [CanBeNull] int? offset, CancellationToken cancellationToken);
```

**Comment by pholly** [comment]
Cool. I ended up creating Entity Framework scaffolding controllers to
handle CRUD for Applications.

**Comment by kevinchalet** [comment]
@pholly ah yeah, that's a good option too :+1:

**Comment by kevinchalet** [comment]
Closing, as the API was implemented in the latest OpenIddict RC1 bits.
