### ISSUE TITLE
[bug] Invalid post logout redirect uri with MS OpenIdConnect 1.1.0

### ISSUE THREAD

**Issue by HolyHorseman** [openiddict/openiddict-core#321]
Dear Kevin,
It is sick news. ( ▼-▼ )
Today I had created a new client project, and updated all MS lib by NuGet. Though it is a big mistake to update. 
I found from output window that logout uri was not defined in startup.cs. Through great effort I could not get cause about error.

So I had recreated a project without update. OMG, that was well.
After I updated references one by one, I got it at last -  Microsoft.AspNetCore.Authentication.OpenIdConnect(verions 1.1.0).
It changes logout redirect uri to 'http://[IP: Port]/signout-callback-oidc'.

Those are well references in my project.

    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",

    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0", <-- it is well, no use 1.1.0

    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "type": "build",
      "version": "1.0.0-preview2-final"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"

**Comment by HolyHorseman** [comment]
Aha…… In fact, we can think of it as MS wrong, too.

**Comment by kevinchalet** [comment]
It's not a bug, but a deliberate breaking change in ASP.NET Core 1.1.0. You can find more information on this thread: https://github.com/aspnet/Security/pull/925.

**Comment by HolyHorseman** [comment]
Thank you, I got it.

Remark below to all in the trouble.

Using MS OpenIdConnect version 1.0.0,
1. define `PostLogoutRedirectUri` with client's uri;
2. in server's database, `RedirectUri` is `http://<ClientHost>/signin-oidc`, `LogoutRedirectUri` is `http://<ClientHost>/`.

Using MS OpenIdConnect version 1.1.0,
1. define `CallbackPath` with client's path(no uri; `PostLogoutRedirectUri` is invalid);
2. in server's database, `RedirectUri` is `http://<ClientHost>/signin-oidc`, `LogoutRedirectUri` is `http://<ClientHost>/signout-callback-oidc`.
P.S. Thank Kevin for your great effort again.

**Comment by kevinchalet** [comment]
> P.S. Thank Kevin for your great effort again.

Thanks for the kind words 😄 

@Tratcher looks like this (breaking) change is not listed in the aspnet/Announcements repo.
Do you think it would be worth posting a ticket for this change?

**Comment by Tratcher** [comment]
I can write up an announcement in the Security repo if you think it would help. The feature and change are too esoteric to warrant posting in aspnet/Announcements.

**Comment by kevinchalet** [comment]
> I can write up an announcement in the Security repo if you think it would help.

That would be great, thanks. The same question has been asked 4 or 5 times here or on the Gitter channel, so I think it's common enough to deserve an announcement :+1:

**Comment by Tratcher** [comment]
Posted: https://github.com/aspnet/Security/issues/1087

**Comment by kevinchalet** [comment]
Thanks @Tratcher :+1: 

FYI, I opened a new thread for removing `PostLogoutRedirectUri` in 2.0.0: https://github.com/aspnet/Security/issues/1089.

**Comment by pealmeid** [comment]
Hello @HolyHorseman, I followed your instructions but I'm still getting the `Invalid post_logout_redirect_uri` error. It's not clear to me how to configure both the client and the server.

Considering the server as `http://server:5000` and the client as `http://client:4000`, what are the values for the client and server config? Here's what I'm trying (with no success):

Client:
- No `PostLogoutRedirectUri`
- `CallbackPath = "/signin-oidc",`
- `SignedOutCallbackPath = "/signout-callback-oidc",`

Server:
- `LogoutRedirectUri = "http://client:4000/signout-callback-oidc",`
- `RedirectUri = "http://localhost:4000/signin-oidc"`

I tried different permutations of the full URI and the path in the different client and server options, but to no avail. Can you help me figure out how to make this configuration work? Thanks in advance.

**Update:** I was making a mistake and not regenerating the server database as I tried the different options. Because of that my changes did not "stick" and I kept getting the error. Regenerating the database with the options mentioned above working without any problems.

**Comment by HolyHorseman** [comment]
Hello @pealmeid, I'm pleasure that is helpful for you. 
We should give thanks to @PinpointTownes.

**Comment by sinhpham** [comment]
I'm having trouble with OIDC sending the wrong redirect uri, (http://mydomain/signin as opposed to httpS://mydomain/signin), so the whole flow fails. How does the auto-detect redirect URI work and how can I force it to use httpS?

My scenario is I'm running asp.net core behind a reverse proxy that does SSL termination and redirects all http requests to httpS.

**Comment by Tratcher** [comment]
@sinhpham See https://github.com/aspnet/Docs/issues/2384

**Comment by sinhpham** [comment]
Thanks @Tratcher for the link, that fixed my problem.
