### ISSUE TITLE
Updating (custom) claims on identity token refresh

### ISSUE THREAD

**Issue by jooooel** [openiddict/openiddict-core#323]
Hi,
I'm sorry if this question has been answered before, but I can't seem to find it.

I'm using the refresh flow like described in this sample [https://github.com/openiddict/openiddict-samples/tree/master/samples/RefreshFlow](url).

In addition to the standard claims, we also add our custom claims to the user identity, like this:

```C#
private async Task<AuthenticationTicket> CreateTicketAsync(OpenIdConnectRequest request, User user)
{
	// Create a new ClaimsPrincipal containing the claims that
	// will be used to create an id_token, a token or a code.
	var principal = await _signInManager.CreateUserPrincipalAsync(user);

	// This is where we add our custom claims, removed some for clarity.
	var customClaims = new List<Claim>();
	customClaims.Add(new Claim(UserClaims.AccountId, accountUser.AccountId.ToString(), ClaimValueTypes.Integer));
	customClaims.Add(new Claim(UserClaims.SomeClaims,
		user.SomeClaims
			.Select(claim => claim.Value)
			.ToList()
			.ToSerializedString(camelCase: true), JsonClaimValueTypes.JsonArray));

	var identity = (ClaimsIdentity)principal.Identity;
	identity.AddClaims(customClaims);

	foreach (var claim in principal.Claims)
	{
		claim.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
							  OpenIdConnectConstants.Destinations.IdentityToken);
	}

	// Create a new authentication ticket holding the user identity.
	var ticket = new AuthenticationTicket(
		principal, new AuthenticationProperties(),
		OpenIdConnectServerDefaults.AuthenticationScheme);

	if (!request.IsRefreshTokenGrantType())
	{
		ticket.SetScopes(new[] {
			OpenIdConnectConstants.Scopes.OpenId,
			OpenIdConnectConstants.Scopes.Email,
			OpenIdConnectConstants.Scopes.Profile,
			OpenIdConnectConstants.Scopes.OfflineAccess,
			OpenIddictConstants.Scopes.Roles
		}.Intersect(request.GetScopes()));
	}
	
	return ticket;
}
```

The problem is that when a refresh token is used and a new token is issued, the custom claims aren't updated. I understand that this might not be something that is supported? But I have a hard time finding what approach I should use instead?

My use case is something like this:
- User logs in to client (angular app)
- An access token (used for access to the API) and an id token (JWT, used by the client to get information about the authenticated user) are issued, along with a refresh token.
- Some information about the user changes (one of the custom claims, like username or whatever)
- When a new access token and id token are issued using the refresh token, they should contain the updated claims.

Thank you! Really enjoy working with OpenIddict, feels really good. Just hoping I'm using it the right way :)

**Comment by jooooel** [comment]
Never mind! I didn't realize quite a bit has changed in the last beta (compared to the previous version I was running). I'm now doing like you do in the samples, regenerating the ticket on ` if (request.IsRefreshTokenGrantType())`.

And everything seems to be working fine :) Thanks!

**Comment by kevinchalet** [comment]
> And everything seems to be working fine :) Thanks!

Nice! :+1:
