### ISSUE TITLE
Invalid signatures on jwt.io for id_token

### ISSUE THREAD

**Issue by asadsahi** [openiddict/openiddict-core#325]
Hi,

Apologies as it might not be an issue, but for better understanding, what is the reason when I try to decode id_token on jwt.io, it give invalid signatures message?

![image](https://cloud.githubusercontent.com/assets/3470892/21849861/e3a09a8a-d7ff-11e6-8ded-59fe30928269.png)

**Comment by kevinchalet** [comment]
Hey,

This message indicates it can't validate the signature protecting the JWT token. But it's not surprising, as the public key textbox is empty.

**Comment by asadsahi** [comment]
Okay, is that the dynamic key generated when we add Openiddict service?
....
.AddEphemeralSigningKey

**Comment by kevinchalet** [comment]
It is. You can retrieve the public using the JWK endpoint, at http://[root address]/.well-known/jwks

**Comment by asadsahi** [comment]
Oo I see. which one is that?

```
{
"keys": [
{
"kid": "7CUQHWSDIY1KGP8BMJF98RT-Y0QDKKPENTAOMDTT",
"use": "sig",
"kty": "RSA",
"alg": "RS256",
"e": "AQAB",
"n": "7CuqHwsDiy1kGp8bmJf98RT-y0QdkKPentAOmDTtTwbH1_YsU982GLpM7oqkKYIQ2jo_4rydgLi3XiJkrMgyrmFz0uYCmlWCLyMMCMxPWTGIqqPM1QMfsIG0A2bfC7sNYHwDuJAC6r5rlrO3RoDQQIV7Dq_2afk0n5G7aXvxG3UT_a9CwopQ4RtT5UrpwINKatyKKnzoCPtqCECaJm3OCzz-xm3k55HUSQtIRylA_i6quSFBPfI5W1MpDv43_FUw9y6gmqo4Q_9UjynemRxuBBJCQgamLjwbAnUnX-wgBsCUAIMpnfTEsV2N-UWfB2IUwdXVT03TZ6YJzUzv760LeQ"
}
]
}
```

**Comment by kevinchalet** [comment]
https://stackoverflow.com/questions/38998702/verify-a-signature-in-jwt-io

**Comment by asadsahi** [comment]
@PinpointTownes Thanks, perfectly answers the question.

**Comment by jotabe-net** [comment]
Easier way: the endpoint return a JWKS string, but jwt.io expects a JWK. It's as easy as taking the firs entry of the `keys` arry, and paste it in jwt.io textbox. In this case:
```
{
"kid": "7CUQHWSDIY1KGP8BMJF98RT-Y0QDKKPENTAOMDTT",
"use": "sig",
"kty": "RSA",
"alg": "RS256",
"e": "AQAB",
"n": "7CuqHwsDiy1kGp8bmJf98RT-y0QdkKPentAOmDTtTwbH1_YsU982GLpM7oqkKYIQ2jo_4rydgLi3XiJkrMgyrmFz0uYCmlWCLyMMCMxPWTGIqqPM1QMfsIG0A2bfC7sNYHwDuJAC6r5rlrO3RoDQQIV7Dq_2afk0n5G7aXvxG3UT_a9CwopQ4RtT5UrpwINKatyKKnzoCPtqCECaJm3OCzz-xm3k55HUSQtIRylA_i6quSFBPfI5W1MpDv43_FUw9y6gmqo4Q_9UjynemRxuBBJCQgamLjwbAnUnX-wgBsCUAIMpnfTEsV2N-UWfB2IUwdXVT03TZ6YJzUzv760LeQ"
}
```
