### ISSUE TITLE
Creating a new OpenIddictApplication in Controller

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#329]
Hi,
I'm trying to create some admin pages to manage OpenIddictApplications, I have some code to create one in StartUp.Configure but it relies on IApplicationBuilder.

Has anyone got some code to create an OpenIddictApplication inside a Controller?

**Comment by kevinchalet** [comment]
> I'm trying to create some admin pages to manage OpenIddictApplications, I have some code to create one in StartUp.Configure but it relies on IApplicationBuilder.

You can inject `OpenIddictApplicationManager` anywhere in your code, using DI.
