### ISSUE TITLE
Get connect/token return 500 code - No authentication handler is configured to handle the scheme: ASOS

### ISSUE THREAD

**Issue by tomasjurasek** [openiddict/openiddict-core#332]
`
Hi,
I have problem with openiddict token. When i call connect/token i get -
 **"InvalidOperationException: No authentication handler is configured to handle the scheme: ASOS"**

Here is my startup.cs setup.

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
            });

            services.AddIdentity<AppUser, AppRole>()
                .AddEntityFrameworkStores<AppDbContext, int>()
                .AddDefaultTokenProviders();

            services.AddOpenIddict()
                .AddEphemeralSigningKey()
                .DisableHttpsRequirement()
                .EnableTokenEndpoint("/connect/token")
                .AllowPasswordFlow()
                .AllowRefreshTokenFlow()
                .UseJsonWebTokens();

            services.AddMvc();

            return ConfigureStructureMap(services);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseDeveloperExceptionPage();
            app.UseStaticFiles();

            app.UseCors(builder =>
            builder.AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
             );

            app.UseOAuthValidation();
            app.UseMvc();
            app.UseOpenIddict();

        }
`

and my ConnectController.cs like [here](https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/)

When i call token in postman

![postman](https://cloud.githubusercontent.com/assets/1623933/22030580/51693e22-dcde-11e6-8900-b609c12da58b.PNG)

Do you have some idea?
Thanks

**Comment by kevinchalet** [comment]
1. The OpenIddict middleware (`app.UseOpenIddict()`) is not at the right place. It must be added before MVC.

2. The parameters in your screenshots are invalid. Use the standard naming or bad surprises will happen.

**Comment by tomasjurasek** [comment]
`Thanks, I also changed


    public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                options.UseOpenIddict<int>(); // <--- ADD
            });

            services.AddIdentity<AppUser, AppRole>()
                .AddEntityFrameworkStores<AppDbContext, int>()
                .AddDefaultTokenProviders();



            services.AddOpenIddict<int>()
                .AddEntityFrameworkCoreStores<AppDbContext>()  //<----ADD
                .AddEphemeralSigningKey()
                .DisableHttpsRequirement()
                .EnableTokenEndpoint("/connect/token")
                .AllowPasswordFlow()
                .AllowRefreshTokenFlow()
                .UseJsonWebTokens();


            services.AddMvc();


            return ConfigureStructureMap(services);
        }

And add

    public DbSet<OpenIddictApplication<int>> OpenIddictApplications { get; set; }
`


Now i get - **"Application not found in the database: ensure that your client_id is correct."**
Is same sample, where I can register my app?

**Comment by kevinchalet** [comment]
FYI, the password flow sample can be found here: https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow/AuthorizationServer
