### ISSUE TITLE
Refresh token expiration time

### ISSUE THREAD

**Issue by psp589** [openiddict/openiddict-core#335]
How could I know the expiration time for a refresh token? and how could I change it?

**Comment by Bartmax** [comment]
when you get the token, it has an `expire_in` value.

You can read the [Wiki](https://github.com/openiddict/openiddict-core/wiki/Configuration-and-options) to see how to change configuration values.

**Comment by psp589** [comment]
Thanks seen the Wiki , I saw the times and the default configuration, I don't get how could be happenning this issue https://github.com/OrchardCMS/Orchard2/issues/534 (we're using orchard 2 with openiddict there)

**Comment by psp589** [comment]
Well, the problem seems to be fixed, thank you!

**Comment by Bartmax** [comment]
@psp589 if it's possible, will be good if you can post how you solved your problem in case someone else gets in here for future reference. Thanks and I'm glad you solved it!

**Comment by psp589** [comment]
Hi @Bartmax , it's solved here https://github.com/OrchardCMS/Orchard2/commit/5675b47abce9110b290dfa06eb17bb8247c901c8
