### ISSUE TITLE
Grant Type is always invalid after the last update

### ISSUE THREAD

**Issue by dreampper** [openiddict/openiddict-core#342]
Hi, after the last update we are receiving `OpenIdConnectConstants.Errors.UnsupportedGrantType` when sending a request with `grant_type: password` to the token endpoint.

Is there something that we are doing wrong?
```

        [HttpPost("token")]
        [Produces("application/json")]
        public async Task<IActionResult> Token(OpenIdConnectRequest request)
        {
                if (request.IsPasswordGrantType())
                {
                       /// NOT REACHED
                }
      }
```

**Comment by kevinchalet** [comment]
I can't reproduce it locally.

If you believe it's a bug, please provide a minimal, complete, and verifiable example.
