### ISSUE TITLE
Revoke All Refresh Tokens of User

### ISSUE THREAD

**Issue by jedielson** [openiddict/openiddict-core#349]
Hi.

I'm using password grant flow, with Identity.

I want to kill all refresh token for a user, every time a login its executed.
I need this to kill its "session" even when he sign in with a different device, like other pc, or smartphone.

So, how can I do it?

Can I just do a `UserManager.UpdateSecurityStampAsync(user.Id);`, or I need something else?

Thank you so much for your help!

**Comment by kevinchalet** [comment]
Hey,

To make them more visible for the community, questions should be posted on StackOverflow: https://stackoverflow.com/questions/tagged/openiddict.

See you there!

**Comment by jedielson** [comment]
Sorry! =]

here is the question,

https://stackoverflow.com/questions/41942482/revoke-all-refresh-tokens-of-user

Just in Case ;)

**Comment by kevinchalet** [comment]
No prob' :sweat_smile: 

Answer posted. Hope it will help.
