### ISSUE TITLE
Signing certificate with thumbprint not working anymore (Azure)

### ISSUE THREAD

**Issue by Ciantic** [openiddict/openiddict-core#350]
I had this code running in production previously:

```
openIdDict.AddSigningCertificate(Configuration.GetOrFail("OpenId:SigningCertificateThumbprint"))
```

Some update between 1.0.0-alpha2-0448 and beta2-0549 made above code useless in Azure.

If I use EphemeralSigningKey it starts working again.

**Comment by kevinchalet** [comment]
> Some update between 1.0.0-alpha2-0448 and beta2-0549 made above code useless in Azure.

This is really vague. Can you be more specific? Are you seeing an exception?

**Comment by Ciantic** [comment]
I could not find any exception, all Controller Actions (with Authorization in front) started to give Bad Gateway. I actually rolled back, now testing in staging... I'll try to find a better exception tomorrow.

**Comment by kevinchalet** [comment]
Enable logging and post the traces when you have a minute. I'll take a look.

**Comment by kevinchalet** [comment]
I can't reproduce it.

If you believe it's a bug, please provide a minimal, complete, and verifiable example.
