### ISSUE TITLE
What's the purpose of OpenIddictScopeManager and related types

### ISSUE THREAD

**Issue by Lukazoid** [openiddict/openiddict-core#351]
What is the actual purpose of the `OpenIddictScopeManager<TScope>`, it doesn't contain any public methods so I cannot see how it would be used.

As per above, does this not make the `IOpenIddictScopeStore<TScope>` and `OpenIddictScope<TKey>` types also useless?

I am probably just missing something here.

**Comment by kevinchalet** [comment]
The scope manager/store is a WIP.

**Comment by Lukazoid** [comment]
That would be what I was missing then. Thanks for getting back to me.
