### ISSUE TITLE
Question: Accessing authentication ticket information

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#352]
Is there any way I can access the auth ticket info set on the auth server when it is separate from the resource server?

**Comment by kevinchalet** [comment]
Hey,

To make them more visible for the community, questions should be posted on StackOverflow: https://stackoverflow.com/questions/tagged/openiddict.

See you there!

**Comment by jayrulez** [comment]
Thanks for the pointer.

I posed the question there.
