### ISSUE TITLE
HttpContext handled outside a Web API controller has no Identity

### ISSUE THREAD

**Issue by dreampper** [openiddict/openiddict-core#356]
I'm using a WebSocket middleware which handles the HttpContext during the connection. The problem is that wherever I try to handle the context outside the Web API controller, the Identity is always null.

What I'm thinking is that: inside a Controller, the request has the Authorization Bearer TOKEN so It's possible to get the User.Identity. Outside the controller, like in the Middleware, the request could not has the Authorization header, so the HttpContext.User.Identity could be null.

I don't know if a CookieAuthentication could fix it or how to use CookieAuthentication together with OpenIddict connections.

What do you think about that?

**Comment by kevinchalet** [comment]
Consider flowing the access token via the query string: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/SignalR/HelloSignalR/Startup.cs#L28
