### ISSUE TITLE
What is the difference between  `access_token` and  `id_token` ?

### ISSUE THREAD

**Issue by Lissbrict** [openiddict/openiddict-core#358]
I get  `access_token`  and `id_token` through the API
question:
 - What is the difference between  `access_token` and `id_token` ?
 - Why `assess_token` and `id_token` resolved after the different Audience ?

**Comment by kevinchalet** [comment]
Hey,

To make them more visible for the community, questions should be posted on StackOverflow: https://stackoverflow.com/questions/tagged/openiddict.

See you there!
