### ISSUE TITLE
Error with latest version 

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#359]
Hi there, 
I am just trying to update Openiddict to the latest version [-beta2-0556 at this point].

Now the following error occurs when first trying to access the database:

> System.TypeLoadException: 'Die Methode "ApplyServices" im Typ "OpenIddict.EntityFrameworkCore.OpenIddictExtension`5" der Assembly "OpenIddict.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.'   [ = "The method ... has no Implementation"]

thrown by the "UseOpenIddict() part here:

```
  services.AddDbContext<DataAccess.ApoNextDbContext>(options =>
            {
                options.UseSqlServer(Configuration["Data:ApoNextDb"]);
               options.UseOpenIddict();
            });
```

I am surely missing something.. but what ?  Could it be using asp.net core / ef core preview 1.2.0.-preview1-23456 ?

**Comment by kevinchalet** [comment]
Hey,

> Could it be using asp.net core / ef core preview 1.2.0.-preview1-23456 ?

Yes, the signature of the `ApplyServices` method has changed in EF Core 1.2/2.0: https://github.com/aspnet/EntityFramework/pull/7464/files#diff-9bbea77ce009e5466562d04f3c02d22aR156

**Comment by ghost** [comment]
Alright, thanks!

**Comment by harisbotic** [comment]
Is this going to be solved any soon?

**Comment by kevinchalet** [comment]
@harisbotic there's currently no plan to start working on an ASP.NET Core 2.0-compatible version (it would be premature).
