### ISSUE TITLE
Invalid object name 'OpenIddictApplications'

### ISSUE THREAD

**Issue by digital-nomad17** [openiddict/openiddict-core#362]
I am running into a sqlexception when I add the openiddict database to the application. Here is a screen shot of the error - http://i.imgur.com/mFIj9ku.png. I am not sure what this error means. Any ideas? I am running code off of the sample.

**Comment by Bartmax** [comment]
![image](https://cloud.githubusercontent.com/assets/3386797/23089876/b5eda2bc-f56f-11e6-9a02-aaa536e86050.png)

including image on GitHub.

What's wondering me about this, is the error message mentions OpenIddictApplicationS (with an S).
Can you show the dbcontext class?

**Comment by kevinchalet** [comment]
I'd bet @Bartmax gave you the right answer: the entity sets needed by OpenIddict are not correctly registered, you're probably missing an `options.AddOpenIddict()` call somewhere in the EF context options.

If you're still seeing this error, feel free to post more details and I'll reopen the ticket.

**Comment by digital-nomad17** [comment]
Here's a screenshot of my DbContext class. 
![image](https://cloud.githubusercontent.com/assets/1823832/23224286/bc4d29ae-f8fb-11e6-94b2-4a54a37f5a33.png)

**Comment by kevinchalet** [comment]
And you're sure your context is correctly configured, as mentioned in the Getting started section?

https://github.com/openiddict/openiddict-core#getting-started

**Comment by digital-nomad17** [comment]
I set everything up as described in the 'Getting started section' and I am checking against the sample application but I am still encountering the error. I double checked the getting started section and the sample against my code and there's no major differences. I am convinced it's an issue with my sqlserver config.
![image](https://cloud.githubusercontent.com/assets/1823832/23284073/6aad1d3c-f9f7-11e6-92ed-1d15ee6f72ff.png)

EDIT -----

I resolved the problem. It was an issue with the connection string for my database.

**Comment by hajimenez** [comment]
> I set everything up as described in the 'Getting started section' and I am checking against the sample application but I am still encountering the error. I double checked the getting started section and the sample against my code and there's no major differences. I am convinced it's an issue with my sqlserver config.
> ![image](https://cloud.githubusercontent.com/assets/1823832/23284073/6aad1d3c-f9f7-11e6-92ed-1d15ee6f72ff.png)
> 
> EDIT -----
> 
> I resolved the problem. It was an issue with the connection string for my database.

Can I Have a sample of your conection string for .net core?

**Comment by AuriR** [comment]
Make sure you create a migration after updating Program.cs/Startup.cs (depending on your setup). So, use **Add-Migration AddOpenIddictEntities** or something you like, and it will create the migration. Then, **Update-Database** and the issue should go away. I suggest backing up the db before you do this, just in case you want to revert.

**Comment by DanOpcode** [comment]
@AuriR Thanks, creating a migration did the trick for me.

**Comment by AuriR** [comment]
Perfect. You're welcome, @matachi - glad it worked!!
