### ISSUE TITLE
Ability to change token expiry at token request time

### ISSUE THREAD

**Issue by gecko-8** [openiddict/openiddict-core#364]
Hi,
I have a use case where multiple app types (web and mobile) are using the same token-flow authorization server. I'd like to have different expiry times for the different types (probably using different token endpoints) but I can't figure out a way to override the values set with SetAccessTokenLifetime and SetRefreshTokenLifetime. Is there a way to do this?
Thanks,
Jason

**Comment by kevinchalet** [comment]
Answered here: http://stackoverflow.com/questions/42442109/is-there-a-way-to-have-different-ticket-expiry-lengths-in-openiddict.
