### ISSUE TITLE
Generate a local token using another identity provider?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#366]
When using this with google+ i was told by @PinpointTownes that because you cannot generate a token via a server side method (which i would love), I was suppose to use the Assertion method in order to generate a local token.  This was easy enough and since i was using google+ javascript code to log the user is, it made sense.

Now i have also implemented functionality to allow the users to login via SAML2.  I have a SAML method that gets called when the user has logged in via the SAML2 provider.  Now because this happens server side, am i still supposed to have to use Assertion to generate a local token for the user?  This means that i have to in effect get the server to call itself, which doesnt seem right to me?

So my steps are as follows:

1. User clicks on a button on my UI
2. A server method is called on my webapi, which directs user to SAML identity provider.
3. User logins in
4. User is directed back to a different method on my web api, where i now have the username of the user. (Here i would like to generate a local token and return it)

Because i cannot generate a token, my process then continues as follows
5. In the method that the user is directed back to, i generate a HTTP POST request to /connect/token using assertion, passing the name of the user that has successfully logged in via SAML2.
6. OpenId generates the token and returns to same method
7.  I return the token to the user

As i said, i dont see why we should have to generate a HTTP request on the server to call itself to obtain a token?? If that is the way it is supposed to work, so be it, but wanted to make sure i havent missed something that could be done instead.

**Comment by kevinchalet** [comment]
Since you're now doing interactive/redirection-based authentication, consider using the implicit flow: https://github.com/openiddict/openiddict-samples/tree/master/samples/ImplicitFlow
