### ISSUE TITLE
Limit access to one mobile app

### ISSUE THREAD

**Issue by Zain-Alabdin** [openiddict/openiddict-core#367]
Hi,
Thanks for your project it saved me a lot of time :)
I am using password flow and it's great but I also want to limit access to the application to my mobile app.... can you show me a sample on how to implement it?
(I'm using SSL so I can have a key on both ends at it checks if it matches)
I want this on all requests including requests which do not require member authentication.
Thank you so much

**Comment by kevinchalet** [comment]
Hey,

> I am using password flow and it's great but I also want to limit access to the application to my mobile app.... can you show me a sample on how to implement it?

You could use client authentication as demonstrated in the code flow sample, but it's almost pointless in a mobile apps, as the credentials can be intercepted or stolen from the binaries.

**Comment by Zain-Alabdin** [comment]
Thanks a lot for the timely reply!
Thanks for pointing out that problem, do you have any recommendation to overcome it?

**Comment by kevinchalet** [comment]
Closing, as this topic is now discussed here: http://stackoverflow.com/questions/42510675/limiting-accessing-web-api-to-application
