### ISSUE TITLE
Add draft device_code flow

### ISSUE THREAD

**Issue by cmsd2** [openiddict/openiddict-core#374]
Add support for the draft device_code flow
https://tools.ietf.org/html/draft-ietf-oauth-device-flow
(currently version 04, expiring August 2017)

The device code flow is designed for input-constrained environments, but may be useful whenever a client application cannot launch a web browser for the authorization code flow.

The device code flow adds a new `response_type` to acquire a code, and a new `grant_type` to the token exchange to swap the code for a token.

Flow:
1. user interacts with device
2. device posts to device code creation endpoint with `response_type=device_code`
3. device receives device_code and `user_code` and `verification_uri` for user to authorize code
4. device starts polling the token exchange endpoint with `grant_type="urn:ietf:params:oauth:grant-type:device_code"`
5. user navigates to `verification_uri` and enters `user_code`
6. user accepts (or denies) authorization of application with scope
7. device receives either the token or an error response of `authorization_pending`, `slow_down` or `expired_token`

The flow can in theory be implemented entirely outside of `openiddict-core`.
A sample project demonstrating the flow would need the components in the list below.
The components could then be folded in as appropriate into openiddict's subprojects.

Components required:
1. Constants for the new `response_type` and `grant_type` values
2. EF `DeviceCode` model
3. EF `DeviceCode` store
4. `DeviceCode` store interface
5. `DeviceCode` manager
6. `OpenIdConnectRequest` extension to detect new grant_type and response_type
7. `OpenIddictBuilder` extension to `AllowDeviceCodeFlow`
8. AuthorizationController endpoint to mint new device code (or fold it in to existing token exchange endpoint which openiddict might not like)
9. Authorization mvc actions, views and view models to get the form to enter the code, post the form back, post accept/deny confirmation back
10. Possibly add the `device_authorization_endpoint` to the discovery metadata

Point 8 might not be smooth because the rfc assumes the `/connect/token` endpoint will be reused. OpenIddict seems to require that all requests destined for that endpoint are token exchange requests and therefore have a `grant_type`.

Additional Considerations:
1. Does OpenIddict need to be directly responsible for rate-limiting token exchange attempts, or is that the responsibility of a reverse-proxy?
2. Come up with recommendations for sensible defaults: code expiry time and user and device code lengths.
3. Perhaps support user codes with pluggable generation schemes such as phrases rather than random letters.

**Comment by kevinchalet** [comment]
Now that the device grant type was officially adopted (in August 2019), its addition to OpenIddict can be safely considered: such support will be introduced in 3.0 and be available for ASP.NET Core 2.1, 2.2, 3.0 and OWIN/Katana 4.0 apps.

> Does OpenIddict need to be directly responsible for rate-limiting token exchange attempts, or is that the responsibility of a reverse-proxy?

As device codes are not limited by artificial length limits, securing the token exchange part is not really a problem, as they have enough entropy to make rate-limiting unnecessary.

User code "validation" (at the verification endpoint) is a whole different story, as user codes have much less entropy. I considered it, but decided it was too much work for the initial implementation. 

> Come up with recommendations for sensible defaults: code expiry time and user and device code lengths.

I opted for a 10-minute lifetime for both the user and device codes, which seemed like a reasonable value. For better usability by users using non-Latin-based keyboards, I opted for a digit-only scheme with 12 digits from 0 to 9, separated by dashes for increased readability. This should provide almost ~40 bits of entropy.

> Perhaps support user codes with pluggable generation schemes such as phrases rather than random letters.

Users will be able to replace the default handler responsible of creating the user code if they prefer a different scheme.
