### ISSUE TITLE
How to get token id from database

### ISSUE THREAD

**Issue by altair256** [openiddict/openiddict-core#381]
Hello! I see [#136](https://github.com/openiddict/openiddict-core/issues/136#issuecomment-225068490) about revoke token and i not understand how find current token id witch I want to revoke.

```
var token = await _tokenManager.FindByIdAsync(id);
```
Can you help me please? Thank you!

**Comment by kevinchalet** [comment]
You can use `OpenIddictTokenManager.FindBySubjectAsync("user identifier")` to retrieve the tokens associated with a specific user.

**Comment by altair256** [comment]
Yes, I know this. But if I need a specific token, how to get it id? Example one user can log in from multiple locations and I want revoke one of his tokens.

**Comment by kevinchalet** [comment]
The token identifier associated with a specific token can be retrieved via the introspection endpoint (`jti`).

Alternatively, you can also directly use ASP.NET Core's `TicketDataFormat` to unprotect a refresh token and extract the corresponding `AuthenticationTicket`, whose identifier can be retrieved using `ticket.GetTicketId()`. Here's how we instantiate it in ASOS: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerMiddleware.cs#L122-L126

**Comment by altair256** [comment]
Thank you for answer! As I understand under` jti` you meat `Logout `end point? That is, I have to implement something like:
`public async Task<IActionResult> Logout(OpenIdConnectRequest request)`
If so, what parameters should be passed there?

**Comment by kevinchalet** [comment]
> As I understand underjti you meat Logoutend point?

No no, I mean the introspection endpoint (which is transparently implemented for you by OpenIddict, so no need to provide an action for this endpoint).

For more info, don't miss: https://tools.ietf.org/html/rfc7662#section-2.1.

**Comment by altair256** [comment]
> For more info, don't miss: https://tools.ietf.org/html/rfc7662#section-2.1.

Ok. but I not understand how this help me get token id? I did not find there token id param.

I'm interested in the token id

![default](https://cloud.githubusercontent.com/assets/3997002/25086442/52b6ab42-2370-11e7-8ccc-0e47aa0f1545.png)

Example revoke token by subject I do so
```
  [HttpPost]
        public async Task<IActionResult> RevokeToken()
        {                               
            var id = await GetCurrentUserId();            
            var tokens = await _tokenManager.FindBySubjectAsync(id, CancellationToken.None);
            foreach (var token in tokens)
            {                
                await _tokenManager.RevokeAsync(token, CancellationToken.None);
            }
            return Ok();
        }
```
I need to do the same only with the token ID.

**Comment by kevinchalet** [comment]
> I need to do the same only with the token ID.

I don't understand. Are you trying to retrieve the token identifier associated with a token, or remove a token corresponding to a given identifier?

For the later, use `OpenIddictTokenManager.FindByIdAsync("8895")`.

**Comment by altair256** [comment]
I want that when a user logs out of the system the token is removed from the database, but only a specific token, and not all tokens associated with this user. To do this, I need to find the identifier of the token to remove it from the database. But I do not know how to get this identifier and whether this is possible in principle. That is, I want to get the token ID associated with the user who will log off the system.

**Comment by kevinchalet** [comment]
You can't do that, as there's no direct relationship between the user session (= represented by an authentication cookie managed by Identity) and the refresh tokens (that are usually not revoked after an interactive logout, BTW).

**Comment by altair256** [comment]
Thank you! I understood.

**Comment by kevinchalet** [comment]
@altair256 note: if you want to manually implement such a scenario, you can use the new `OpenIddictAuthorizationManager<TAuthorization>` class, create a new ad-hoc "authorization" per login using `CreateAsync()`, store the authorization identifier as a claim in the Identity authentication cookie and bind the `AuthenticationTicket` you return from `CreateTicketAsync()` to the authorization you created:

```
ticket.SetProperty(OpenIddictConstants.Properties.AuthorizationId,
    value: await _authorizationManager.GetIdAsync(authorization));
```

During the signout process, retrieve the authorization using the identifier stored in the Identity cookie and revoke it. All the associated tokens will be revoked. 

Unfortunately, there's no sample that demonstrates how to do that, so you're pretty much on your own.

**Comment by altair256** [comment]
Ok. Thanks again. I will try to do this.

**Comment by MDzyga** [comment]
Hello,
I have similar problem. I'm using OpenIdDict in version 3.1 and client credentials flow.
My OpenIdDict server is configured to use Introspection because it can work in proxy mode.  If I configure validation to useLocalServer, I see more claims (e.g. oi_tkn_id, scope) but then server rejects token because signing keys are different.

```
services.AddOpenIddict()
                .AddCore(options =>
                {
                    options.UseEntityFrameworkCore()
                        .UseDbContext<ApplicationDbContext>()
                        .ReplaceDefaultEntities<Client, Authorization, Scope, Token, int>();
                })
                .AddServer(options =>
                {
                    options
                        .SetTokenEndpointUris("/connect/token")
                        .SetRevocationEndpointUris("/connect/revocation")
                        .SetIntrospectionEndpointUris("/connect/introspect");

                    options.AddEventHandler<OpenIddictServerEvents.ProcessSignInContext>(builder =>
                    {
                        builder.UseInlineHandler(context =>
                        {
                            if (context.Transaction.Request != null)
                            {
                                context.Response["scope"] = string.Join(" ", context.Transaction.Request.GetScopes().OrderBy(z => z));
                            }

                            return default;
                        });
                    });

                    options.AddEventHandler<OpenIddictServerEvents.ProcessChallengeContext>(builder =>
                    {
                        builder.UseInlineHandler(context =>
                        {
                            var authPropertiesKey = typeof(AuthenticationProperties).ToString();
                            if (context.Transaction.Properties.ContainsKey(authPropertiesKey))
                            {
                                var props = context.Transaction.Properties[authPropertiesKey] as AuthenticationProperties;
                                context.Response["message"] = props.Items["message"];
                            }

                            return default;
                        });
                    });

                    options.AllowClientCredentialsFlow();
                    options.AllowPasswordFlow();
                    options.AllowRefreshTokenFlow();

                    options.UseReferenceRefreshTokens();

                    options.RegisterScopes(
                        OpenIddictConstants.Permissions.Scopes.Profile.Replace(OpenIddictConstants.Permissions.Prefixes.Scope, string.Empty),
                        OpenIddictConstants.Permissions.Scopes.Roles.Replace(OpenIddictConstants.Permissions.Prefixes.Scope, string.Empty),
                        CustomScopes.APPLICATION,
                        CustomScopes.IDENTITY_SETUP,
                        CustomScopes.SUPPORT_PACKAGE);

                    options.SetAccessTokenLifetime(TimeSpan.FromHours(1));
                    options.SetRefreshTokenLifetime(TimeSpan.FromDays(7));

                    options.AddEncryptionCertificate(signingCertificate)
                        .AddSigningCertificate(signingCertificate);

                    options.DisableAccessTokenEncryption();

                    options.UseAspNetCore()
                        .EnableTokenEndpointPassthrough();
                })
                .AddValidation(options =>
                {
                    options.Configure(c =>
                    {
                        c.TokenValidationParameters.ValidateIssuer = false;
                        c.TokenValidationParameters.ValidateIssuerSigningKey = false;
                    });

                    options.SetIssuer("https://localhost:44322/");

                    options.UseIntrospection()
                        .SetClientId(GeneralConstants.APP_CLIENT_ID)
                        .SetClientSecret(GeneralConstants.APP_CLIENT_SECRET);

                    options.UseSystemNetHttp();

                    //options.UseLocalServer();

                    options.UseAspNetCore();
                });
```
