### ISSUE TITLE
Directions for installing with MSBuild

### ISSUE THREAD

**Issue by digital-nomad17** [openiddict/openiddict-core#382]
Hi,

I just updated my project to Asp.net core 1.0.1 with visual studio and there's no project.json. It apparently has been [deprecated ](https://wildermuth.com/2016/05/12/The-Future-of-project-json-in-ASP-NET-Core)in favor of using MsBuild(xml). Could someone update the how to with the new build system?

**Comment by kevinchalet** [comment]
The docs folks at Microsoft have written a few guides to ease the migration process. You can find them here: https://docs.microsoft.com/en-us/dotnet/articles/core/migration/ and https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj.
