### ISSUE TITLE
Automatic signing key creation

### ISSUE THREAD

**Issue by dazinator** [openiddict/openiddict-core#386]
I like this feature: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/129

Perhaps worth adding it to OpenIdDict?

**Comment by kevinchalet** [comment]
FYI, this feature was removed in ASOS beta7 a few months ago because it was unreliable, despite numerous tries to harden it: http://kevinchalet.com/2016/11/30/the-new-aspnet-contrib-packages-are-out/

For more information, read https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/269 and https://github.com/openiddict/openiddict-core/issues/204.

**Comment by dazinator** [comment]
Thanks. If i understand correctly, feature was removed because write access to the folder where keys were persisted, could not be guaranteed for some production environment scenarios.

I'm curious to know if there is some reasoning behind not making this directory configurable (like dataprotection API does)

**Comment by kevinchalet** [comment]
> I'm curious to know if there is some reasoning behind not making this directory configurable (like dataprotection API does)

Yep: https://github.com/openiddict/openiddict-core/issues/106#issuecomment-218912174

**Comment by dazinator** [comment]
Thanks

I'm probably too late now to offer up my humble opinion, but as this is the internet, I feel I can get away with it:

> The cool thing about this feature is that it was fully automatic: you didn't have to configure anything. Having to configure this feature seems to defeat its entire purpose. And in this case, it's probably "as complicated" as configuring an embedded X509 certificate, which is what we recommend when going live.

I do think that the complexity in specifying a directory is much simpler, than the complexity of working through the following though:

> When testing OpenIddict, you don't have to configure anything as the default samples use an embedded test certificate, that doesn't have to be persisted in the machine store.
When creating your own project based on OpenIddict, you can generate your own certificate using a tool like self-cert (please give it a try and tell me what you think) and embed it in the assembly. Nothing to persist in the certificate store in this scenario.
When going live, the certificate should be stored in the machine store, but storing it as an embedded resource should also be supported for convenience.

The first, let's me specify a configurable value, and move on. No special configuration or special actions required on my part. A rudimentary scaling comes for free, as this can be a shared folder. My only concern would be that someone should really backup the keys in this directory in production.

The second scenario requires I switch hat's, grab a tool, generate a self signed cert (pfx), embed it, but also, along the way it forces me to ask questions like these:

1. Do we have a special certificate for production use? 
2. Do I need to use the machine store for production? 
3. Who is going to ensure the certifiate is deployed to production machine store?
3. Is it really ok to use a self-signed certificate on production - or do we need to purchase a certificate? 
4. Is it ok to add the pfx to source control? (especially if the project is open source - how many developers will lazily end up using the open source pfx in production?)
5. Should the application fallback to the embedded cert if one in the machine store is not available (more work, and potentially dangerous if this means it ends up using the open source pfx).

I think the main reason the second scenario is more complicated than the first, is that: 
1. The pfx becomes an asset that has be managed by the developer - forcing them to ask questions about it, especially if they are not used to dealing with pfx's. 
2. It requires the application to behave differently on production, where you want the machine store to be used. This requires you to put some additional code in place so that your application behaves differently on different environments - e.g on Dev, use ephemeral, on Test --> use embedded pfx, on Production --> use Cert store.

With the directory approach, you can forget all about pfx's.

1. The key is never an asset that is part of the solution so the developer doesn't have to ask any questions or even understand pfx's or how to manage them.
2. The application behaves consistently irrespective of environment. No special casing dev, test, or UAT. This also means less likelihood of hitting an issue that only happens on one environment due to one code path only executing on one environment.

Even though the private keys are created in a folder, they are still secure because they are encrypted via DataProtection, so I can't see a problem from a security perspective. 

I will try out the generate self signing cert tool though, it probably beats using IIS.

**Comment by dazinator** [comment]
Just listing some thoughts out loud on some other options:

1. Allow open id dict to generate a PFX and add it to machine cert store automatically for re-use - dismissing this as giving a website process write access to machine cert store is a big no-no security wise i'd imagine.
2. Allow open id dict to generate a PFX and add it to the current user cert store automatically for re-use? - Wouldn't work in a web farm scenario, with multiple servers generating their own independent pfx's in their own user stores. Also not sure if app pool identity can even have a certificate user store. 
3. Allow open id dict to generate a PFX, and write it to some directory automatically for re-use. This is pretty much the old feature but with PFX in the equation where it doesn't really need to be - as no real benefit to using PFX format if doing this, can just write the private key encrypted.

**Comment by kevinchalet** [comment]
@dazinator thanks to the new X.509 certificate creation APIs introduced in `netcoreapp2.0`, this is something we could now easily implement in both ASOS and OpenIddict for ASP.NET Core 2.0.

Are you still interested in this feature?

**Comment by dazinator** [comment]
Sure, but how are you thinking it would work? Are you thinking the x509 cert would be automatically saved to a configurable folder location? If so - what are the benefits of generating a X.509 cert over just saving the key, encrypted via data protection `Protect()` ?

**Comment by kevinchalet** [comment]
> Are you thinking the x509 cert would be automatically saved to a configurable folder location?

I'm tempted to think it would be preferable to keep this feature development-only.
In this case, storing the certificate in the X.509 machine/user store would be my preferred option.

Something like that:

## ASOS

```csharp
// By default, generate a RSA development certificate
// and store it in StoreName.My/StoreLocation.CurrentUser.
public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials);

public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials, StoreName name, StoreLocation location);

public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials, [NotNull] string algorithm);

public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials,
    [NotNull] string algorithm, StoreName name, StoreLocation location);
```

## OpenIddict

```csharp
// By default, generate a RSA development certificate
// and store it in StoreName.My/StoreLocation.CurrentUser.
public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder);

public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder, StoreName name, StoreLocation location);

public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder, [NotNull] string algorithm);

public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder,
    [NotNull] string algorithm, StoreName name, StoreLocation location);
```

**Comment by dazinator** [comment]
Do those certifcate store API's work accross platforms other than windows, that net core runs? I'm not a linux guru but I think linux does have the concept of certificate stores. If this is a windows only thing, then I think it would still be better to just encrypt the key with DPAPI and save it to a user directory which is something that should be supported everywhere.

**Comment by kevinchalet** [comment]
`X509Store` is cross-platform (with a few limitations on macOS IIRC).
Though I haven't tested them yet, I believe the new certificate creation APIs are also x-plat.

**Comment by dazinator** [comment]
Cool - if this is going to work cross plat, and allow stuff to "just work" in development then I am all for it!
I guess, in your application, you would have code that says when running in development mode, make a call to ensure the cert exists or is created, on startup. When running in production mode, you would have an alternate code path that just tells it what cert store / cert to point at, and then rely on some other provisioning process to make sure those certs exist. Does that sound about right to you?

**Comment by kevinchalet** [comment]
> I guess you would have code that says when running in development mode, make a call to ensure the cert exists or is created, on startup.

That would be `AddDevelopmentCertificate`'s mission, yeah.

> When running in production mode, you would have an alternate code path that just tells it what cert store / cert to point at, and then rely on some other provisioning process to make sure those certs exist.

For production, I believe a CLI tooling story would be a much better approach. You could directly create and persist production-ready certificates using cmd.

Something like...

```
dotnet openiddict certificates create --type Signing --persist
```

I'll take a look at the EF tooling to see how complicated it would be to create such a CLI tool.

**Comment by kevinchalet** [comment]
Updated API proposal (IdentityModel doesn't support DSA and ECDSA certificates, so it's not worth having an overload allowing to configure the algorithm):

## ASOS

```csharp
/// <summary>
/// Registers (and generates if necessary) a user-specific development certificate
/// used to sign the tokens issued by the OpenID Connect server.
/// </summary>
/// <param name="credentials">The signing credentials.</param>
/// <returns>The signing credentials.</returns>
public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials);

/// <summary>
/// Registers (and generates if necessary) a user-specific development certificate
/// used to sign the tokens issued by the OpenID Connect server.
/// </summary>
/// <param name="credentials">The signing credentials.</param>
/// <param name="subject">The subject name associated with the certificate.</param>
/// <returns>The signing credentials.</returns>
public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials,
    [NotNull] X500DistinguishedName subject);

/// <summary>
/// Registers (and generates if necessary) a user or machine-specific development
/// certificate used to sign the tokens issued by the OpenID Connect server.
/// </summary>
/// <param name="credentials">The signing credentials.</param>
/// <param name="name">The name of the X.509 store.</param>
/// <param name="location">The location of the X.509 store.</param>
/// <returns>The signing credentials.</returns>
public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials, StoreName name, StoreLocation location);

/// <summary>
/// Registers (and generates if necessary) a user or machine-specific development
/// certificate used to sign the tokens issued by the OpenID Connect server.
/// </summary>
/// <param name="credentials">The signing credentials.</param>
/// <param name="subject">The subject name associated with the certificate.</param>
/// <param name="name">The name of the X.509 store.</param>
/// <param name="location">The location of the X.509 store.</param>
/// <returns>The signing credentials.</returns>
public static IList<SigningCredentials> AddDevelopmentCertificate(
    [NotNull] this IList<SigningCredentials> credentials,
    [NotNull] X500DistinguishedName subject, StoreName name, StoreLocation location);
```

## OpenIddict

```csharp
/// <summary>
/// Registers (and generates if necessary) a user-specific development
/// certificate used to sign the JWT tokens issued by OpenIddict.
/// </summary>
/// <param name="builder">The services builder used by OpenIddict to register new services.</param>
/// <returns>The <see cref="OpenIddictBuilder"/>.</returns>
public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder);

/// <summary>
/// Registers (and generates if necessary) a user-specific development
/// certificate used to sign the JWT tokens issued by OpenIddict.
/// </summary>
/// <param name="builder">The services builder used by OpenIddict to register new services.</param>
/// <param name="subject">The subject name associated with the certificate.</param>
/// <returns>The <see cref="OpenIddictBuilder"/>.</returns>
public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder,
    [NotNull] X500DistinguishedName subject);

/// <summary>
/// Registers (and generates if necessary) a user or machine-specific development
/// certificate used to sign the JWT tokens issued by OpenIddict.
/// </summary>
/// <param name="builder">The services builder used by OpenIddict to register new services.</param>
/// <param name="name">The name of the X.509 store.</param>
/// <param name="location">The location of the X.509 store.</param>
/// <returns>The <see cref="OpenIddictBuilder"/>.</returns>
public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder, StoreName name, StoreLocation location);

/// <summary>
/// Registers (and generates if necessary) a user or machine-specific development
/// certificate used to sign the JWT tokens issued by OpenIddict.
/// </summary>
/// <param name="builder">The services builder used by OpenIddict to register new services.</param>
/// <param name="subject">The subject name associated with the certificate.</param>
/// <param name="name">The name of the X.509 store.</param>
/// <param name="location">The location of the X.509 store.</param>
/// <returns>The <see cref="OpenIddictBuilder"/>.</returns>
public static OpenIddictBuilder AddDevelopmentSigningCertificate(
    [NotNull] this OpenIddictBuilder builder,
    [NotNull] X500DistinguishedName subject, StoreName name, StoreLocation location);
```

**Comment by dazinator** [comment]
I'll pretend I know enough about certs that I am familiar with those terms from your last statement. 
One quick suggestion, if calling those API's are idempotent, might be better to call them something like `EnsureDevelopmentSigningCertificate` rather than `Add` - assuming it only adds them if necessary.

**Comment by kevinchalet** [comment]
> One quick suggestion, if calling those API's are idempotent, might be better to call them something like EnsureDevelopmentSigningCertificate rather than Add - assuming it only adds them if necessary.

Please note that the `AddDevelopmentSigningCertificate()` method won't be automatically called by OpenIddict. It's an opt-in feature that requires invoking it explicitly. As such, the `Add` prefix seemed appropriate.

To make sure this feature is visible enough, I've updated the exception messages that are thrown when no signing credentials are registered (e.g when using JWT as the access token format or when enabling implicit flow support).

See https://github.com/openiddict/openiddict-core/issues/427 for more information.
