### ISSUE TITLE
Sample project with JWT token and Introspection

### ISSUE THREAD

**Issue by ryzenalways** [openiddict/openiddict-core#388]
Hi,

I am trying to setup a auth server with jwt token based on the sample code. But keep getting a 500 error. Is it possible for you to build a sample application with this requirement Or can you please point me to the right direction?

Thanks.

**Comment by kevinchalet** [comment]
Hi,

> Is it possible for you to build a sample application with this requirement

Actually, there's already a sample that uses introspection: https://github.com/openiddict/openiddict-samples/tree/master/samples/ImplicitFlow

> I am trying to setup a auth server with jwt token based on the sample code.

Tho' it's definitely supported, using JWT and introspection doesn't make much sense, as the tokens can be validated by the resource servers without having to use introspection.
