### ISSUE TITLE
Openiddict Unable to resolve service for type 'OpenIddict.Core.IOpenIddictApplicationStore`

### ISSUE THREAD

**Issue by trzewior** [openiddict/openiddict-core#389]
Hey im following this sample (https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/) and im getting the error as in the post title:
http://stackoverflow.com/questions/43536709/openiddict-unable-to-resolve-service-for-type-openiddict-core-iopeniddictapplic

**Comment by kevinchalet** [comment]
Hey. 

Have you registered the OpenIddict stores, as mentioned in the SO thread?

**Comment by kevinchalet** [comment]
Closing, as your question was answered here by Set: http://stackoverflow.com/questions/43536709/openiddict-unable-to-resolve-service-for-type-openiddict-core-iopeniddictapplic.
