### ISSUE TITLE
Access to earlier builds of openiddict

### ISSUE THREAD

**Issue by astegmaier** [openiddict/openiddict-core#390]
Is there any way to get access to alpha builds of openiddict? I'm trying to follow along with Valerio De Sanctis' [excellent book](http://a.co/8xZfy9L) about angular2, and the sample code requires openiddict 1.0.0-alpha2-0419. It looks like the earliest version available on the [myget feed](https://www.myget.org/feed/aspnet-contrib/package/nuget/OpenIddict) is 1.0.0-beta2-0559. There were some major changes between these two versions, including the removal of the OpenIddictDbContext class, so I can't get the sample code from the book running with the newer version.

This is just for learning purposes so I can understand the other aspects of how Valerio has implemented the flows. I'm sure there is a way to update Valerio's sample to the modern build of openiddict, but my main goal is not to become an expert in the differences between these two versions of openiddict--just to observe and learn from the other aspects of the sample app.

**Comment by kevinchalet** [comment]
> Is there any way to get access to alpha builds of openiddict?

Nope, sorry. The alpha builds have been removed from the MyGet feed (mainly because the ASP.NET Core VS tooling was unable to display the recent versions ; see https://github.com/aspnet/Tooling/issues/828 for more information).

I haven't read Valerio's book, so I can't tell which flow(s) his sample uses, but up-to-date samples can be found here: https://github.com/openiddict/openiddict-samples/tree/master/samples.

> I'm sure there is a way to update Valerio's sample to the modern build of openiddict, but my main goal is not to become an expert in the differences between these two versions of openiddict--just to observe and learn from the other aspects of the sample app.

I guess you should contact @Darkseal and suggests him to update his sample app. I'm available for help, if needed.

**Comment by astegmaier** [comment]
Thanks for the response!

I went ahead and tried to move Valerio's sample to the latest builds of openiddict. You can see the result here: https://github.com/astegmaier/OpenGamesListWebApp_Chapter10-updated. The "Initial Checkin" is Valerio's code, and the other checkins are the changes I had to make.

It seems to be building and running more-or-less without errors. However, POST calls to the endpoint "http://localhost:5000/api/connect/token" that include all the right keys (i.e. client_id, username, password, scope, and grant_type) are returning "404 not found." (If the keys are wrong or you put extra ones, like client_secret, it will return a specific error, so clearly some kind of validation is happening, just not the full login process).

It seems that there is no actual special controller in Vallerio's code that implements this endpoint. Was it the case that 1.0.0-alpha2-0419 builds of OpenIddict would somehow take care of this for you (through the magic of app.UseOpenIddict() or some other middle-ware), but newer versions do not?

@Darkseal or @PinpointTownes -- do you have any ideas how to get your sample app working as originally designed?

**Comment by kevinchalet** [comment]
> Was it the case that 1.0.0-alpha2-0419 builds of OpenIddict would somehow take care of this for you (through the magic of app.UseOpenIddict() or some other middle-ware)

That's right: the alpha bits used to handle tokens requests for you but this design was not flexible and we opted for something different when decoupling OpenIddict from ASP.NET Core Identity in the subsequent releases, and you now have to implement a custom action for that.

Here's how you can do that: https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs

If you don't use Identity, don't miss this blog post that demonstrates how to use OpenIddict with your own authentication method: http://kevinchalet.com/2017/01/30/implementing-simple-token-authentication-in-aspnet-core-with-openiddict/

**Comment by astegmaier** [comment]
Ah--that make so much more sense. I thought I was going crazy! I'll take a look at the sample you mentioned and see if I can get it working. Thanks so much for taking the time to help me. And thanks also for making OpenIddict--it's super awesome!

Re: the change to require folks to implement their own endpoints, I can understand why it's an improvement to make OpenIddict more flexible. However, for newbies like myself who are trying to stay "within the rails" and use the builtin identity system, it seems to have the downside of adding a lot of boilerplate code to the app, and adding to the surface area where it's easy to make a mistake. 

One idea I wanted to toss out there: would it be possible to have the best of both-worlds approach where by default, OpenIddict would require the developer to implement a custom endpoint, but where there would be a configuration option (say app.UseOpenIddictDefaultEndpointWithIdentity, or something like that) that would cause the openiddict middle-ware to take over this job? I get that this wouldn't work in all cases, but maybe it could focus on the most common flows/endpoint requirements first, and expand over time?

Has this been suggested before? I'm sure you considered the tradeoffs in making the decision to remove it in the first place. Also, I'm super new to the area, so I'm sure there are gotchas that I'm not aware of, but I wanted to see what you thought.

**Comment by kevinchalet** [comment]
> Thanks so much for taking the time to help me. And thanks also for making OpenIddict--it's super awesome!

Haha, thanks for the kind words!

> However, for newbies like myself who are trying to stay "within the rails" and use the builtin identity system, it seems to have the downside of adding a lot of boilerplate code to the app, and adding to the surface area where it's easy to make a mistake.

That's right. If you use ASP.NET Core Identity 1.1, you can simplify the authorization controller sample a bit by using the new `SignInManager.CheckPasswordSignInAsync(user, password)` API instead of these ~50 lines: https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L61-L109.

> One idea I wanted to toss out there: would it be possible to have the best of both-worlds approach where by default, OpenIddict would require the developer to implement a custom endpoint, but where there would be a configuration option (say app.UseOpenIddictDefaultEndpointWithIdentity, or something like that) that would cause the openiddict middle-ware to take over this job?

This is definitely possible, and could even be part of a contrib OpenIddict + Identity package. Here's how it could be done:

```csharp
public static class OpenIddictWithIdentityExtensions
{
    public static IApplicationBuilder UseOpenIddictDefaultEndpointWithIdentity(this IApplicationBuilder app)
    {
        if (app == null)
        {
            throw new InvalidOperationException(nameof(app));
        }

        app.UseOpenIddict();
        app.UseMiddleware<OpenIddictWithIdentityMiddleware>();

        return app;
    }
}
```

```csharp
public class OpenIddictWithIdentityMiddleware
{
    private readonly RequestDelegate _next;

    public OpenIddictWithIdentityMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(
        HttpContext context,
        SignInManager<ApplicationUser> signInManager,
        UserManager<ApplicationUser> userManager)
    {
        // Determine whether the request is a token request. If it's not, don't
        // handle it here and invoke the rest of the ASP.NET Core pipeline.
        var request = context.GetOpenIdConnectRequest();
        if (request == null || !request.IsTokenRequest())
        {
            await _next(context);

            return;
        }

        if (request.IsPasswordGrantType())
        {
            var user = await userManager.FindByNameAsync(request.Username);
            if (user == null)
            {
                await context.Authentication.ForbidAsync(OpenIdConnectServerDefaults.AuthenticationScheme);

                return;
            }

            // Validate the username/password parameters and ensure the account is not locked out.
            var result = await signInManager.CheckPasswordSignInAsync(user, request.Password, lockoutOnFailure: true);
            if (!result.Succeeded)
            {
                await context.Authentication.ForbidAsync(OpenIdConnectServerDefaults.AuthenticationScheme);

                return;
            }

            // Create a new authentication ticket containing the user claims.
            var ticket = await CreateTicketAsync(signInManager, request, user);

            // Ask OpenIddict to return a token response containing the access token.
            await context.Authentication.SignInAsync(ticket.AuthenticationScheme, ticket.Principal, ticket.Properties);

            return;
        }

        else if (request.IsRefreshTokenGrantType())
        {
            // Retrieve the authentication data stored in the encrypted refresh token.
            var info = await context.Authentication.GetAuthenticateInfoAsync(
                OpenIdConnectServerDefaults.AuthenticationScheme);

            // Validate the security stamp stored inside the refresh token.
            var user = await signInManager.ValidateSecurityStampAsync(info.Principal);
            if (user == null)
            {
                await context.Authentication.ForbidAsync(OpenIdConnectServerDefaults.AuthenticationScheme);

                return;
            }

            // Create a new authentication ticket, but reuse the properties stored
            // in the refresh token, including the scopes originally granted.
            var ticket = await CreateTicketAsync(signInManager, request, user, info.Properties);

            // Ask OpenIddict to return a token response containing the access token.
            await context.SignInAsync(ticket.AuthenticationScheme, ticket.Principal, ticket.Properties);

            return;
        }

        throw new NotImplementedException("The specified grant type is not implemented.");
    }

    private async Task<AuthenticationTicket> CreateTicketAsync(
        SignInManager<ApplicationUser> signInManager,
        OpenIdConnectRequest request, ApplicationUser user,
        AuthenticationProperties properties = null)
    {
        // Create a new ClaimsPrincipal containing the claims that
        // will be used to create an id_token, a token or a code.
        var principal = await signInManager.CreateUserPrincipalAsync(user);

        // Create a new authentication ticket holding the user identity.
        var ticket = new AuthenticationTicket(principal, properties,
            OpenIdConnectServerDefaults.AuthenticationScheme);

        if (!request.IsRefreshTokenGrantType())
        {
            // Set the list of scopes granted to the client application.
            // Note: the offline_access scope must be granted
            // to allow OpenIddict to return a refresh token.
            ticket.SetScopes(new[]
            {
                OpenIdConnectConstants.Scopes.OpenId,
                OpenIdConnectConstants.Scopes.Email,
                OpenIdConnectConstants.Scopes.Profile,
                OpenIdConnectConstants.Scopes.OfflineAccess,
                OpenIddictConstants.Scopes.Roles
            }.Intersect(request.GetScopes()));
        }

        ticket.SetResources("resource_server");

        // Note: by default, claims are NOT automatically included in the access and identity tokens.
        // To allow OpenIddict to serialize them, you must attach them a destination, that specifies
        // whether they should be included in access tokens, in identity tokens or in both.

        foreach (var claim in ticket.Principal.Claims)
        {
            // Never include the security stamp in the access and identity tokens, as it's a secret value.
            if (claim.Type == signInManager.Options.ClaimsIdentity.SecurityStampClaimType)
            {
                continue;
            }

            var destinations = new List<string>
            {
                OpenIdConnectConstants.Destinations.AccessToken
            };

            // Only add the iterated claim to the id_token if the corresponding scope was granted to the client application.
            // The other claims will only be added to the access_token, which is encrypted when using the default format.
            if ((claim.Type == OpenIdConnectConstants.Claims.Name && ticket.HasScope(OpenIdConnectConstants.Scopes.Profile)) ||
                (claim.Type == OpenIdConnectConstants.Claims.Email && ticket.HasScope(OpenIdConnectConstants.Scopes.Email)) ||
                (claim.Type == OpenIdConnectConstants.Claims.Role && ticket.HasScope(OpenIddictConstants.Claims.Roles)))
            {
                destinations.Add(OpenIdConnectConstants.Destinations.IdentityToken);
            }

            claim.SetDestinations(destinations);
        }

        return ticket;
    }
}
```

> Has this been suggested before? I'm sure you considered the tradeoffs in making the decision to remove it in the first place.

Sure. More and more people wanted to have more control over the authentication method or the claims generation process (e.g to add custom claims to the list prepared by Identity) and this approach seemed more flexible than forcing everyone to use our own logic.

Actually, we had 2 choices: opting for an "OpenIddict + Identity package using a default logic that would make 'most people' happy" approach (what you suggest) or opting for a template-based approach, where we provide a reasonable implementation you can easily customize in your own code.

We opted for the second option because it seemed to offer more control to the developer (to use his/her own authentication method or to use his own consent templates for interactive flows) and because it was consistent with what Identity does with its `AccountController`/`ManageController` templates.

**Comment by astegmaier** [comment]
This is awesome! I really appreciate the detailed response. I'm going to chew on this for a while and update the Valerio's sample code to use this pattern. Once I get my head around all the options and the optimal flow, I might consider making a package for others to use in the pattern you suggested. I'll reach out for feedback once I have something to share.

**Comment by Bartmax** [comment]
I may have an idea to balance those 2 options, will think about it a create a new issue if i found a reasonable actionable work.
