### ISSUE TITLE
Implement access token revocation for password flow

### ISSUE THREAD

**Issue by moraleslos** [openiddict/openiddict-core#393]
Currently access tokens in password flow can not be revoked.  Would like this to be implemented in future versions and can think of a couple of reasons:  1) explicit logout in a web app the uses password flow and 2) prohibit use of services after a certain amount of invocations (e.g. SLA).

**Comment by NtFreX** [comment]
I thought an access token white/black list is not in openiddict for performance reasons? Also limiting an ressource on the amount of requests sounds like an implementation detail not to be tied to authorization.

**Comment by kevinchalet** [comment]
We will do that as part of https://github.com/openiddict/openiddict-core/issues/393, but for every supported flow (not just password).
