### ISSUE TITLE
can't install openiddict with asp core

### ISSUE THREAD

**Issue by devjaw** [openiddict/openiddict-core#396]
hi 

i'm trying to install openiddict with my project (asp core 1.1.1) 
and give me this error : 

> Unable to resolve 'OpenIddict.Mvc (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.	

> Unable to resolve 'OpenIddict (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.

> Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.

this is my NuGet.config
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
  </packageSources>
</configuration>`

**Comment by kevinchalet** [comment]
Hi,

There's no RTM release for OpenIddict, so `1.0.0` is not a valid version. Use `1.0.0-*` to use the latest nightly build.

**Comment by devjaw** [comment]
yes i'm using 1.0.0-* 
i added the following lines to csproj file : 
`    <PackageReference Include="AspNet.Security.OAuth.Validation" Version="1.0.0-*" />
    <PackageReference Include="OpenIddict" Version="1.0.0-*" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="1.0.0-*" />
    <PackageReference Include="OpenIddict.Mvc" Version="1.0.0-*" />
`

**Comment by kevinchalet** [comment]
Reopening, as demanded privately.

**Comment by kevinchalet** [comment]
@devjaw could you please try running `dotnet restore` and share what you get?

**Comment by devjaw** [comment]
@PinpointTownes thank you for reopening, 
 yes i tried dotnet restore. nothing happened.

**Comment by kevinchalet** [comment]
> yes i tried dotnet restore. nothing happened.

To ensure you're not missing something obvious, please copy/paste the console output you're seeing.

**Comment by devjaw** [comment]
this the output

> Restoring packages for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj...
  Restoring packages for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj...
  Restoring packages for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj...
  Restoring packages for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj...
  Restore completed in 1.84 sec for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj.
  Restore completed in 1.77 sec for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj.
  Restore completed in 1.77 sec for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj.
  Generating MSBuild file C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\obj\ang.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\obj\project.assets.json
  Restore completed in 5.14 sec for C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\ang.csproj.
  
 

>  NuGet Config files used:
>       C:\Users\user\Documents\Visual Studio 2017\Projects\ang\ang\NuGet.Config
>       C:\Users\user\AppData\Roaming\NuGet\NuGet.Config
>       C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
>   
>   Feeds used:
>       https://api.nuget.org/v3/index.json
>       https://www.myget.org/F/aspnet-contrib/api/v3/index.json
>       https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
>       C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

**Comment by kevinchalet** [comment]
Then what's the problem if it restores fine?

**Comment by devjaw** [comment]
this is my dependencies :  
![1](https://cloud.githubusercontent.com/assets/15944990/25837159/43078570-349d-11e7-9423-b27a8651e1d5.jpg)

**Comment by devjaw** [comment]
i did `dotnet restore` again and it looks like the problem is solved and now i can use `options.UseOpenIddict();` in Startup.cs   ! but the following error is still showing to me : 

> Unable to resolve 'OpenIddict.Mvc (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.
> Unable to resolve 'OpenIddict (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.
> Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.

also , it show me a warning in openiddict dependencies  : 

> Dependency conflict. 'OpenIddict' expected '1.0.0-*' but received '1.0.0-beta2-0614'

**Comment by kevinchalet** [comment]
Could you please try specifying an explicit version and see what it does? (e.g `1.0.0-beta2-0614`)

Related ticket: https://github.com/aspnet/Tooling/issues/1035.

**Comment by ghost** [comment]
'dotnet restore' worked for me but I have to do it every time after I do rebuild instead of build.

**Comment by brenmartin** [comment]
Has anyone got a permanent solution to this i have to run dotnet restore everytime i add/update a reference. This is annoying

**Comment by brenmartin** [comment]
Updating references numbers for all OpenIddict from 1.0.0-* to 1.0.0-beta2-0614 did the job

**Comment by trashvin** [comment]
the solution by @brenmartin works when I do the restore on my machine.However, once in publish it to VSTS the restore fails with the following error:

```
> 
> 2017-09-14T04:48:19.8102473Z Errors in d:\a\1\s\aTrack.WS\aTrack.WS.csproj
> 2017-09-14T04:48:19.8112488Z     Unable to resolve 'OpenIddict.Mvc (>= 1.0.0-rc1-0670)' for '.NETCoreApp,Version=v1.1'.
> 2017-09-14T04:48:19.8112488Z     Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0-rc1-0670)' for '.NETCoreApp,Version=v1.1'.
> 2017-09-14T04:48:19.8112488Z     Unable to resolve 'OpenIddict (>= 1.0.0-rc1-0670)' for '.NETCoreApp,Version=v1.1'.
> 2017-09-14T04:48:19.8122487Z 
> 2017-09-14T04:48:19.8122487Z NuGet Config files used:
> 2017-09-14T04:48:19.8122487Z     d:\a\1\Nuget\tempNuGet_27.config
> 
```
Any idea why this issue occurs in VSTS?

**Comment by JonSomNor** [comment]
This did the trick for me:
https://github.com/emonney/QuickApp/issues/4
