### ISSUE TITLE
Use Dapper instead of EntityFramework Core

### ISSUE THREAD

**Issue by gtzinos** [openiddict/openiddict-core#399]
I'm developing a Web API with .Net core api 1.1. After searching I can't find any document or sample that use authorization without the use of Entity Framework. Instead of this i need to use dapper with a mysql connector in order to connect my app with a mysql server. Is it possible to do it with your library ? If yes please can i have an example ?

**Comment by kevinchalet** [comment]
EntityFramework Core has a MySQL connector, so you can use our default EF Core-based stores with your MySQL database.

If you prefer using Dapper, create your own stores and register them in the DI container. Take a look at https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.EntityFrameworkCore to see how it's done.

**Comment by gtzinos** [comment]
Thank you very much.
