### ISSUE TITLE
ID is varchar(255)

### ISSUE THREAD

**Issue by gtzinos** [openiddict/openiddict-core#402]
HI,
I am using your library and i checked in my mysql database, that the user id is defined as varchar(255). Why not int or long with auto incremental option ?

**Comment by kevinchalet** [comment]
We use the same default key type as ASP.NET Core Identity (string). If you want to customize the default key type of the OpenIddict entities, use the `services.AddOpenIddict<TKey>()` overload that accepts a key type generic parameter.

**Comment by gtzinos** [comment]
I think that for performance is better to use a number instead of string. I am not sure if is good to follow Entity Framework guidelines.

**Comment by kevinchalet** [comment]
> I am not sure if is good to follow Entity Framework guidelines.

Consistency always wins and that's why `string` is the default key type in OpenIddict. As I said, you're free to choose a different key type like `int` or `long` :smile:

**Comment by gtzinos** [comment]
Hehe okay.
