### ISSUE TITLE
Sample of EnableRevocationEndpoint

### ISSUE THREAD

**Issue by jsinh** [openiddict/openiddict-core#403]
@PinpointTownes First of all, I must appreciate what you did with openiddict.

I am following samples for PasswordFlow to create access_token and refresh token - and want to have way (endpoint) to revoke issued (not yet expired token) in this flow.

I did same as sample for `EnableTokenEndpoint` in `AuthorizationController.cs` and that works

I do not see in the sample is what exactly do to when we `EnableRevocationEndpoint` - can you please guide through what should i code in `AuthorizationController.cs` for `RevocationEndpont` to invalidate issued access_token / refresh_token

Some snippet of my Startup.cs (`AuthorizationController.cs` is ditto as you have in sample:

`ConfigureService` method:
```
            services.AddCors();
            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("MyDataConnection"), sqlServerOptions => { sqlServerOptions.MigrationsAssembly("MyApp.DataAccess"); });
                options.UseOpenIddict();
            });

            services
                .AddIdentity<ApplicationUser, ApplicationRole>()
                //.AddUserStore<ApplicationUser>()
                //.AddRoleStore<ApplicationRole>()
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders();

            services.Configure<IdentityOptions>(options =>
            {
                options.ClaimsIdentity.UserNameClaimType = OpenIdConnectConstants.Claims.Name;
                options.ClaimsIdentity.UserIdClaimType = OpenIdConnectConstants.Claims.Subject;
                options.ClaimsIdentity.RoleClaimType = OpenIdConnectConstants.Claims.Role;
            });

            services.AddOpenIddict(options =>
            {
                options.AddEntityFrameworkCoreStores<AppDbContext>();
                options.AddMvcBinders();
                options.EnableTokenEndpoint("/api/account/token");
                options.EnableUserinfoEndpoint("/api/account/info");
                options.EnableRevocationEndpoint("/api/account/revoke");
                options.AllowPasswordFlow().AllowRefreshTokenFlow();
                options.SetAccessTokenLifetime(TimeSpan.FromMinutes(1)); // For testing purpose kept it short
                if (Environment.IsDevelopment())
                {
                    options.DisableHttpsRequirement();
                }
            });

            services.AddMvc();
```

`Configure` method:
```
            app.UseOAuthValidation();
            app.UseMvc();
```

Thanks in advance

**Comment by kevinchalet** [comment]
> First of all, I must appreciate what you did with openiddict.

Glad you like it!

> I do not see in the sample is what exactly do to when we EnableRevocationEndpoint - can you please guide through what should i code in AuthorizationController.cs for RevocationEndpont to invalidate issued access_token / refresh_token

There's no custom code to add to use the revocation endpoint as OpenIddict handles revocation requests internally.

Note that you can't currently revoke access tokens (see https://github.com/openiddict/openiddict-core/issues/191 and https://github.com/openiddict/openiddict-core/issues/393 for more context).
