### ISSUE TITLE
404 response when token is invalid or missing

### ISSUE THREAD

**Issue by davidtimovski** [openiddict/openiddict-core#404]
I've set up OpenIddict and everything works fine but there's something puzzling me.

When I send a request without a token or one where the token is wrong I get a response code of 404. That seems somewhat counterintuitive. Shouldn't I get a response code of 400 (bad request) when the token is missing and a 401 (unauthorized) when it's invalid?

**Comment by kevinchalet** [comment]
Duplicate of https://github.com/openiddict/openiddict-core/issues/337 ?

**Comment by davidtimovski** [comment]
Ahhh, should've found that. It's a duplicate alright.
Thank you.
