### ISSUE TITLE
Support high dpi nuget icon. Size from 64 to 256

### ISSUE THREAD

**Issue by Bartmax** [openiddict/openiddict-core#405]
https://github.com/openiddict/openiddict-core/blob/dev/build/packages.props#L13

```
<PackageIconUrl>https://avatars3.githubusercontent.com/u/13908567?s=256</PackageIconUrl>
```

**Comment by kevinchalet** [comment]
According to https://docs.microsoft.com/en-us/nuget/schema/nuspec, the icon URL is a "URL for a 64x64 image with transparency background to use as the icon for the package in UI display" so I'm not sure higher definitions are (officially) supported. I took a brief look at the .NET Core/ASP.NET Core packages and they all use 64x64 icons.

I'm not opposed to this change, but I want to make sure it won't have any side effect with clients that can't/don't handle high-definition icons. Maybe it would be worth pining the NuGet folks to see if they have a story for high DPI.

**Comment by Bartmax** [comment]
Asking ...
https://github.com/NuGet/Home/issues/5346

**Comment by kevinchalet** [comment]
Closing, as we didn't hear back from the NuGet folks.

**Comment by Bartmax** [comment]
not really much compromise from the nuget team but ...

https://github.com/NuGet/Home/issues/5346#issuecomment-325086938
