### ISSUE TITLE
netcoreapp2.0 - Could not load type 'Microsoft.AspnetCore.Builder.AuthenticationOptions'

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#406]
I am trying to rebuild my project from EF6 + net461, to EFCore2.0 + netcoreapp2.0.

Everything seems to compile but when i try and run my application, i can the following exception

![image](https://user-images.githubusercontent.com/7406381/26923239-6b5f385c-4c39-11e7-8441-0fffe387f292.png)

This seems to happen on this line `options.EnableAuthorizationEndpoint("/connect/authorize");` within my call to `services.AddOpenIddict`

Is there anyway to get round this, or is this a bug, or something else??

Encase it helps, running `dotnet --info` i get the following output

![image](https://user-images.githubusercontent.com/7406381/26923393-de3ec3ce-4c39-11e7-9433-9ab8fed06b99.png)

**Comment by Bartmax** [comment]
I don't think OpenIddict supports netcoreapp2.0 yet see https://github.com/openiddict/openiddict-core/issues/398

**Comment by kevinchalet** [comment]
@Bartmax is right. I'll close this ticket so we can focus on the other one.
