### ISSUE TITLE
Nginx proxy Authorization server, Refresh token fial 

### ISSUE THREAD

**Issue by Lissbrict** [openiddict/openiddict-core#407]
this my ` Authorized server` Architecture:

![default](https://user-images.githubusercontent.com/22954464/26923942-477a73ce-4c76-11e7-92d6-3f5d049d0bcf.png)

- Program configuration

```C#

   builder = 
                    .AddSigningCertificate(typeof(Startup).GetTypeInfo().Assembly,
                        "certificate.pfx", "****************************")
                ;
   builder.AddMvcBinders()
 .EnableRequestCaching()
 .EnableTokenEndpoint("/connect/token")
 .AllowPasswordFlow()
 .AllowRefreshTokenFlow()
 .RequireClientIdentification()
 .UseJsonWebTokens()
```

**Comment by kevinchalet** [comment]
Closing, as your ticket is not actionable.

If you still need help, post complete details about what's not working and at least share your logs.
