### ISSUE TITLE
Return more standard info from OpenID Connect Discovery endpoint

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#412]
It would be nice provide already available values there and to be able to configure more options of discovery endpoint
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by kevinchalet** [comment]
What values are you particularly interested in?

**Comment by xperiandri** [comment]
- registration_endpoint
- scopes_supported
- response_types_supported
- claim_types_supported
- claims_supported
- service_documentation
- claims_locales_supported
- ui_locales_supported
- op_policy_uri
- op_tos_uri

**Comment by kevinchalet** [comment]
> registration_endpoint

Dynamic client registration is not yet supported by ASOS/OpenIddict. We'll expose this value once it is.

> scopes_supported

We already return a hardcoded scopes list. Making that configurable is planned.

> response_types_supported

It's already fully supported.

> claim_types_supported

ASOS/OpenIddict only support normal claims (not distributed or aggregated claims). Returning this parameter is not planned.

For the others, I'm not against supporting them. We just have to find a way to expose them without adding too many options in the OpenIddict stuff.
