### ISSUE TITLE
401 Invalid Access Token because of version missmatch

### ISSUE THREAD

**Issue by MJomaa** [openiddict/openiddict-core#413]
This is just an information post. The issue has been solved.

**My issue was following:**
I've upgraded an application from 1.0.0 to 1.1.2 and suddenly I got 401.
It said  **invalid_token**  and returned **401**, but the token is valid and in the logs you could see:

> AspNet.Security.OAuth.Validation.OAuthValidationMiddleware:Information: Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.

**Versions used:**
OpenIddict: 1.0.0-beta2-0585
OpenIddict.EntityFrameworkCore: 1.0.0-beta2-0585
OpenIddict.Mvc: 1.0.0-beta2-0585
AspNet.Security.OAuth.Introspection: 1.0.0
AspNet.Security.OAuth.Validation: 1.0.0

**Steps to reproduce:**

- Download: https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow/
- Go to the subfolder /AuthorizationServer
- Update all packages to 1.1.2
- Use officially released OpenIddict packages.
- Rebuild (to restore packages, etc.)
- Start the server
- Test with the client app.

**Expected:**
200 Ok, Authorized, valid token

**Actual:**
401, Unauthorized, invalid_token

**How to solve this:**
Just update the OpenIddict packages to 1.0.0-beta2-0615  (or newer in case you read this later)

- Install-Package OpenIddict -Version 1.0.0-beta2-0615 -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json
- Install-Package OpenIddict.EntityFrameworkCore -Version 1.0.0-beta2-0615 -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json
- Install-Package OpenIddict.Mvc -Version 1.0.0-beta2-0615 -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json

**Comment by kevinchalet** [comment]
Thanks for the detailed report, @MJomaa :+1:
