### ISSUE TITLE
AuthorizationController at /connect/token not being called

### ISSUE THREAD

**Issue by LimeyTX** [openiddict/openiddict-core#414]
I recently asked a [this](https://stackoverflow.com/questions/44915677/jwt-openiddict-and-asp-net-core-500-internal-server-error/44915942?noredirect=1#comment76820923_44915942) question on StackOverflow which has not been resolved.
As a way of diagnosing the problem I opened a completely new project based on [this](http://blog.medhat.ca/2017/03/token-authentication-with-openiddict-in.html) example. Although, as far as I can see, I have followed this to the letter, when I use Postman to get a token from localhost:5000/connect/token the code in the AuthorizationServer doesn't even get entered when I start debugging.  Instead, I get a 400 error with the following response.
`{
    "error": "invalid_request",
    "error_description": "The mandatory 'grant_type' parameter is missing."
}`

The log shows
`AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The token request was successfully extracted from the HTTP request: {}.
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Error: The token request was rejected because the grant type was missing.
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The token response was successfully returned: {
  "error": "invalid_request",
  "error_description": "The mandatory 'grant_type' parameter is missing."
}.
`
The URL to the server was 
`localhost:5000/connect/token?username=username&grant_type=password&password=password`

I have replaced the username and password for my security.

I don't understand why the token request is rejected.

**Comment by kevinchalet** [comment]
> Although, as far as I can see, I have followed this to the letter

If that was true, you wouldn't see this error :trollface: 

Both the OAuth2 specification and the tutorial you mentioned are pretty clear about the fact the token request parameters must be specified in the request form (formurl-encoding) and **not in the query string**.

Fix that, and it should work.

**Comment by LimeyTX** [comment]
I really can’t believe how dumb I was. It’s working fine I was just using Postman incorrectly.

I have been struggling with this for days! I guess senility has finally set in. I had set the Content-Type in the header, but I put the data in the params.

Gawd, now maybe I can make some progress!

Thanks.

**Comment by kevinchalet** [comment]
lol, no problem :sweat_smile: 

Glad you sorted it out.
