### ISSUE TITLE
Can not install latest OpenIDDict 2 into .netcore 2

### ISSUE THREAD

**Issue by amasasi** [openiddict/openiddict-core#417]
I am trying to install in the AspetCore 2.0 but it fails to install from Nuget and  gives the following results in the Output window

  GET https://api.nuget.org/v3/registration2-gz-semver2/openiddict/index.json
  GET https://www.myget.org/F/aspnet-contrib/api/v3/registration1/openiddict/index.json
  OK https://www.myget.org/F/aspnet-contrib/api/v3/registration1/openiddict/index.json 498ms
  NotFound https://api.nuget.org/v3/registration2-gz-semver2/openiddict/index.json 664ms
Restoring packages for C:\Users\ayubu\Documents\Visual Studio 2017\Projects\Cloud Microfinance\VikobaApplication.Core1\VicobaApplication\VicobaApplication.csproj...
  GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/netstandard.library/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.primitives/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.options/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.authentication/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.diagnostics.abstractions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.diagnostics.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.caching.abstractions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.caching.abstractions/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.diagnosticsource/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.diagnostics.diagnosticsource/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.extensions/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.extensions/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencymodel/index.json
  GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.dependencymodel/index.json
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.primitives/index.json 937ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/netstandard.library/index.json 942ms
  OK https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 1224ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json 1154ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/index.json 1248ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.logging.abstractions/index.json 1149ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.authentication/index.json 1155ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.options/index.json 1170ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json 1185ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.diagnostics.abstractions/index.json 1181ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.caching.abstractions/index.json 1192ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.diagnostics.diagnosticsource/index.json 872ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json 816ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.extensions/index.json 836ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json 1108ms
  NotFound https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.dependencymodel/index.json 1132ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json 1682ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/index.json 1692ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json 2114ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication/index.json 2107ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json 2134ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.diagnostics.abstractions/index.json 2141ms
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.diagnosticsource/index.json 2232ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.caching.abstractions/index.json 2574ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging/index.json 2473ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json 2500ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http.extensions/index.json 2866ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencymodel/index.json 2866ms
Package restore failed. Rolling back package changes for 'VicobaApplication'.

**Comment by kevinchalet** [comment]
Unfortunately, these logs contain no error, so it's hard to say what's causing your issue. Is that all you have?

**Comment by amasasi** [comment]
It is that all, but i have noted that i didn't put the proper nuget source, now fixed
