### ISSUE TITLE
Pull all OpenIddict applications and un-encrypted client secrets

### ISSUE THREAD

**Issue by FrogsLegs** [openiddict/openiddict-core#418]
I have several created a client applications and they're stored in the database, I now need to show each customer their ClientID / Secret on a page within our web portal. The Client Secret is encrypted in the database, how do I retrieve this and decrypt it to show to the customer?

Thanks,
Leigh

**Comment by kevinchalet** [comment]
> The Client Secret is encrypted in the database, how do I retrieve this and decrypt it to show to the customer?

The client secret is not encrypted, it's hashed ([using PBKDF with HMAC-SHA256](https://github.com/henkmollema/CryptoHelper/blob/master/src/CryptoHelper/Crypto.cs)). You can't retrieve the original secret once it's stored in the database, for obvious security reasons.

Instead, have you considered offering a way to simply reset the client secret?

**Comment by FrogsLegs** [comment]
Thanks @PinpointTownes, the customer is never shown the Secret. We create it for them the first time they log into the portal with a new account. It looks like I'll need to implement some form of secure email mechanism in order to send the secret when it is generated. 

Thanks for your reply
Leigh

**Comment by FrogsLegs** [comment]
Would it be safe to encrypt the Client Secret and decrypt it from my database when the customer needs to view it? Similarly to if you had API access to PayPal or DropBox, you can log on to each respective site and see both the the Client ID & Secret?

**Comment by kevinchalet** [comment]
> Would it be safe to encrypt the Client Secret and decrypt it from my database when the customer needs to view it?

Not sure I would recommend it, but it's technically doable. Of course, it's always preferable to only show the client secret - ideally, generated using a crypto-secure RNG - when the user creates the application, but if your flow doesn't allow that...
