### ISSUE TITLE
How to decode refresh token?

### ISSUE THREAD

**Issue by kamleshdelat** [openiddict/openiddict-core#419]
I am trying 
services.AddDataProtection()
        .SetApplicationName("Testervice")
        .ProtectKeysWithCertificate(newCert);

but got error 

System.Security.Cryptography.CryptographicException: was not found in the key ring
--

**Comment by kevinchalet** [comment]
This is not an OpenIddict error. You likely have an issue with how your DataProtection keys are stored or encrypted at rest. If you need additional guidance, feel free to open a ticket here: https://github.com/aspnet/DataProtection.
