### ISSUE TITLE
Validate token by subdomain/Issuer

### ISSUE THREAD

**Issue by ArtemAlekhin** [openiddict/openiddict-core#421]
Hello.
I would like to use OpenIddict to develop a multi-tenancy application. Each my client has its own subdomain on my application (sub1.example.com, sub2.example.com). Can you please tell me how to implement the validation of the token separately for each subdomain/Issuer?
For example, after receiving a token at http://**sub1**.example.com/connent/token the issued token should **not be valid** for resource http://**sub2**.example.com/api/values and should be valid for http://**sub1**.example.com/api/values

**Comment by kevinchalet** [comment]
Hey,

The scenario you describe is implemented in Orchard for ASP.NET Core, so feel free to give it a try: https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Startup.cs

The important part is to specify a "derived" `IDataProtectionProvider` per tenant, so your tokens are only valid (at the crypto level) for the tenant that issued them: 
  - https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Startup.cs#L39
  - https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Startup.cs#L76
  - https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Startup.cs#L120

**Comment by ArtemAlekhin** [comment]
Hi.
Thank you very much Kevin for your help.

I'm looking at the design of the Orchard2 project, but it seems difficult for me to understand.
I figured out that I need to use the IDataProtectionProvider for each individual tenant
`protector = dataProtectionProvider.CreateProtector(tenantName);`

But I do not understand how I can use the IDataProtectionProvider **instance for an individual tenant** in services.AddOpenIddict(options => options.UseDataProtectionProvider(protector)) and app.UseOAuthValidation(options => options.DataProtectionProvider = protector) methods.
I do not quite understand how multi-tenancy works in an Orchard2 project.
For multi-tenancy I use [SaasKit](https://github.com/saaskit/saaskit)

**Comment by kevinchalet** [comment]
> I do not quite understand how multi-tenancy works in an Orchard2 project.

@sebastienros will surely know better than me, but basically Orchard creates a separate services container + a middleware pipeline per tenant. I've never used SaasKit so I'm not sure exactly if it could support multiple DI containers.

Note: OpenIddict for ASP.NET Core 2.0 will get better multitenancy support. I'm currently writing a blog post about that.

**Comment by amasasi** [comment]
@PinpointTownes  i am waiting to read the blogpost on openididict multitenancy support

**Comment by sebastienros** [comment]
@amasasi me too

**Comment by kevinchalet** [comment]
@sebastienros while you're here, feel free to add more details about how OrchardCore handles multitenancy... I'm sure it would help @ArtemAlekhin :sweat_smile:

**Comment by ArtemAlekhin** [comment]
SaasKit has a method that creates [multi-tenant middleware pipelines](http://benfoster.io/blog/aspnet-core-multi-tenant-middleware-pipelines) - app.UsePerTenant. 
Now I can set DataProtectionProvider for UseOAuthValidation middleware per tenant
```
app.UsePerTenant<Tenant>((context, builder) =>
{
    builder.UseOAuthValidation(options =>
    {
        options.DataProtectionProvider = dataProtectionProvider.CreateProtector(context.Tenant.Name);
    });

//set DataProtectionProvider per tenant for OpenIddict 
}
```
But, app.UseOpenIddict() does not have options argument.
How I can set DataProtectionProvider instance for OpenIddict in **Configure** method?

**Comment by kevinchalet** [comment]
> How I can set DataProtectionProvider instance for OpenIddict in Configure method?

You can't. OpenIddict works exactly like Identity (and all the authentication middleware in ASP.NET Core 2.0): it requires configuring the options in `ConfigureServices`.

**Comment by sebastienros** [comment]
In Orchard each tenant gets its own set of services, so each tenant can have different options and configured services. Same thing for middlewares.

**Comment by sebastienros** [comment]
Maybe take a look at https://github.com/OrchardCMS/OrchardCore.Samples if you want to try it.

**Comment by ArtemAlekhin** [comment]
@PinpointTownes Do I understand correctly that after app.UseOpenIddict(), DataProtectionProvider  can not be specified at runtime?

**Comment by kevinchalet** [comment]
Not sure I understand your question, sorry.

2017-08-03 16:44 GMT+02:00 ArtemAlekhin <notifications@github.com>:

**Comment by ArtemAlekhin** [comment]
@PinpointTownes Sorry for my bad explanation.

If it would be possible to set DataProtectionProvider option for OpenIddict middleware at runtime, and not just in the `services.AddOpenIddict()` method, it would immediately solve my problem

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IDataProtectionProvider dataProtectionProvider)
{
    app.UseMultitenancy<Tenant>();

    //UsePerTenant called with each request
    app.UsePerTenant<Tenant>((context, builder) =>
    {
        var protector = dataProtectionProvider.CreateProtector(context.Tenant.Name);

        builder.UseWhen(httpContext => !httpContext.Request.Path.StartsWithSegments("/api/connect/token"),
            applicationBuilder =>
            {
                applicationBuilder.UseOAuthValidation(options =>
                {
                    options.DataProtectionProvider = protector;
                });
            });

        builder.UseWhen(httpContext => httpContext.Request.Path.StartsWithSegments("/api/connect/token"),
            applicationBuilder =>
            {
                SetDataProtectionProviderMethod(protector); // <- ???

                //Not work
                //OpenIddictOptions openIddictOptions = app.ApplicationServices.GetService<IOptions<OpenIddictOptions>>().Value;
                //openIddictOptions.DataProtectionProvider = protector;
            });
    });

    app.UseOpenIddict();
    app.UseMvc();
}
```
When application starts:
    1) app.UseMultitenancy
    2) app.UseOpenIddict
    3) app.UseMvc
When request handling:
    1) app.UsePerTenant

**Comment by kevinchalet** [comment]
As I already said, what you're trying to do is not supported by OpenIddict, just like it's not supported by Identity. 

In 2.0, all the 'app.UseXYZ()` extensions associated with the security middleware (e.g OpenIddict, the validation middleware, the cookies middleware, Identity, etc.) will be gone, so the approach used by SaasKit won't be feasible at all.

Give Orchard's multitenancy a try if you want something that plays nicely with OpenIddict for ASP.NET Core 1.x.

**Comment by ArtemAlekhin** [comment]
Thanks again Kevin for the detailed explanation.
