### ISSUE TITLE
Sample contains HTTP RFC Violation

### ISSUE THREAD

**Issue by HelloKitty** [openiddict/openiddict-core#423]
In the AuthorizationController it returns BadRequest for various failed authentication results. However the [HTTP RFC for BadRequest](https://tools.ietf.org/html/rfc7231#section-6.5.1) states:

> The 400 (Bad Request) status code indicates that the server cannot or
   will not process the request due to something that is perceived to be
   a client error (e.g., malformed request syntax, invalid request
   message framing, or deceptive request routing).

I don't think that applies to providing invalid credentials.

**Comment by kevinchalet** [comment]
Returning a 400 response is required by the OAuth2/OpenID Connect specifications:
  - https://tools.ietf.org/html/rfc6749#section-5.2
  - http://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse

**Comment by HelloKitty** [comment]
I see, you're right. Such a shame that it appears to conflict.
