### ISSUE TITLE
Using rc2 nightly builds fails

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#43]
Currently the nightly builds are beoken with a webapplication exception in startup.cs.  is there not a normal nuget package i can refernece to use this??

**Comment by kevinchalet** [comment]
The nightly builds work fine, and no, there's no "normal" NuGet package, only RC2 nightly packages.

**Comment by Gillardo** [comment]
If i create a new web application and follow the instructions on the readme file it errors....

**Comment by kevinchalet** [comment]
I'm not really good at psychic debugging. If you don't share - at least - the error message you're seeing, there's nothing we can do for you.

**Comment by Gillardo** [comment]
Sorry not at laptop atm. It is something about webapplication but i will get the error for u later

**Comment by Gillardo** [comment]
I was doing it with a brand new application thus why confused. Will post error as soon as i can

**Comment by jimnorth55** [comment]
Pardon my jumping in here, but I have a related question...  If I want to incorporate OpenIddict into an existing "rc1-final" solution (consisting of several projects), is it a requirement that I convert the entire Solution to use rc2 nightly builds for all asp.net 5 dependencies?   Thanks.

**Comment by kevinchalet** [comment]
> Is it a requirement that I convert the entire Solution to use rc2 nightly builds for all asp.net 5 dependencies?

Yes, you can't mix RC1 and RC2 packages in the same application (at least, not without seeing tons of exceptions at runtime :smile:)

**Comment by kevinchalet** [comment]
@Gillardo are you still seeing an error?

**Comment by Gillardo** [comment]
Yes i am, but i do not think it is your code, but maybe you can still help.  I have updated all my packages to rc2, but when i build, this line is invalid

```
// Entry point for the application.
public static void Main(string[] args) => new WebApplication.Run<Startup>(args);
```

If i add a using like so `using Microsoft.AspNet.Hosting.Internal;`

Then it appears that the Run method is no longer there??

What do i need to change this to?  Really want to try out your software, so if you can help, that would be great

**Comment by kevinchalet** [comment]
The hosting API has been completely revamped: https://github.com/aspnet/Announcements/issues/131

Take a look [at this commit](https://github.com/openiddict/core/commit/ec34de77244b1dd6235cff99e46c22ef91c09c0c) to see how we fixed the OpenIddict samples to use the new API.

**Comment by Gillardo** [comment]
Thank you!!!! I will now try and install your software

**Comment by sashasochka** [comment]
Possible somebody knows if it's possible to use rc2 projects on Azure App Service? Does it support rc-2 version of dnx?
