### ISSUE TITLE
Invalid refresh tokens after apppool recycle

### ISSUE THREAD

**Issue by joelnotified** [openiddict/openiddict-core#430]
Hi!
I have password flow with refresh tokens set up according to your examples and everything works as expected when running on localhost.

When deployed to IIS, we receive a 400 Bad Request `{"error":"invalid_grant","error_description":"The specified refresh token is invalid."}` when trying to refresh a token after the application pool has been recycled.

I'm guessing there is something that is being held in memory regarding the refresh tokens, and that memory is dropped when the pool is recycled.

Is this the expected behaviour or should a refresh work after a recycle?

**Comment by kevinchalet** [comment]
Hi @joelnotified,

When deploying your app to IIS, you must configure Data Protection to ensure it uses a persisted key ring. See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview for more information.

**Comment by joelnotified** [comment]
That did the trick. Thank you! Haven't read up on .NET Core enough I guess.

**Comment by sir-boformer** [comment]
If you stumble across this issue, various solutions can be found here:

https://stackoverflow.com/questions/37099136/aspnet-core-using-in-memory-repo-for-data-protection-when-running-in-iis

Running [this shell script](https://github.com/aspnet/DataProtection/blob/b876319379248788100e0dec3ed54ff9076bc752/Provision-AutoGenKeys.ps1) for every AppPool seems to be the best solution.
