### ISSUE TITLE
Implement reference tokens support as an opt-in feature

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#433]
## Objective:

Offering built-in support for reference tokens in OpenIddict, so that things like immediate access token revocation can be easily achieved in OpenIddict-based apps.

## Proposed API:

```csharp
/// <summary>
/// Configures to OpenIddict to use reference tokens, so that authorization codes,
/// access tokens and refresh tokens are stored as ciphertext in the database
/// (only an identifier is returned to the client application). Enabling this option
/// is useful to keep track of all the issued tokens or when storing a very large
/// number of claims in the authorization codes, access tokens and refresh tokens.
/// Note: this option cannot be used when configuring JWT as the access token format.
/// </summary>
/// <param name="builder">The services builder used by OpenIddict to register new services.</param>
/// <returns>The <see cref="OpenIddictBuilder"/>.</returns>
public static OpenIddictBuilder UseReferenceTokens([NotNull] this OpenIddictBuilder builder)
{
    if (builder == null)
    {
        throw new ArgumentNullException(nameof(builder));
    }

    return builder.Configure(options => options.UseReferenceTokens = true);
}
````

## Usage:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Register the OpenIddict services.
    services.AddOpenIddict(options =>
    {
        // ...

        // Configure OpenIddict to use reference tokens.
        options.UseReferenceTokens();
    });
}
```

Open question: should we have an equivalent to the aspnet-contrib validation middleware for reference tokens, or is the introspection middleware enough for this task?

**Comment by kinosang** [comment]
one more question, if we use reference tokens without a new validation middleware, how can we get Userinfo endpoint working? I don't want to use the introspection middleware in the OpenID Connect Server project, it's ugly and waste.

**Comment by kevinchalet** [comment]
Currently, it's introspection or nothing.

**Comment by kinosang** [comment]
@PinpointTownes I see. but when I try to use the introspection endpoint to validate the token with Postman, it always return false.

e.g.

POST http://localhost:55179/Api/Introspect
token=_YMBhvhLMzZm9th6kcreFY0s243-9EyK7qCmUqQmKyE

```json
{
    "active": false
}
```

**Comment by kevinchalet** [comment]
What do the logs say?

**Comment by kinosang** [comment]
It says `The introspection request was rejected because the access token was issued to a different client or for another resource server.`

but I've already set the RP to "http://localhost:55179/"

**Comment by kevinchalet** [comment]
Does the client id assigned to your resource server match the resource set when calling `ticket.SetResources()`?

**Comment by kinosang** [comment]
@PinpointTownes you mean I should add the client id to the array of resource servers for `ticket.SetResources()`?

**Comment by kevinchalet** [comment]
That's what I mean (and how introspection works in general). Create a client registration for your OIDC server and assign it a unique client identifier. Then, add it to the resources list using `ticket.SetResources()`.

**Comment by kinosang** [comment]
Now I get

```json
{
    "resource": "http://localhost:55179/ 8418D046-356B-46FB-A551-09B1217144CE",
    "token_type": "Bearer",
    "access_token": "4KSDU8pycrdkkzmYa8nLzBsSms3WMXzpYobNDZoxgaA",
    "expires_in": 3600
}
```

but the token is still not work with introspection.

**Comment by kevinchalet** [comment]
Share your complete configuration and logs. Otherwise it's impossible to help you.

**Comment by kinosang** [comment]
my mistake, the url of this server is not `http://localhost:55179/`. it listen on 55179 if I start it in VS. but it listen on 5000 when I start it via `dotnet run`.

thanks a lot.

sorry for wasting your time.

**Comment by JakeLokkesmoe** [comment]
Are there any plans right now for a validation middleware for reference tokens other than introspection?

**Comment by kevinchalet** [comment]
@JakeLokkesmoe nope, not right now. I don't have enough bandwidth for that ATM as I'm focusing on releasing the first public version of OpenIddict (RC1).

**Comment by JakeLokkesmoe** [comment]
@PinpointTownes ok. Thanks

**Comment by jayrulez** [comment]
@PinpointTownes now that the rc1 versions have been released, would you give another look at the middleware for validating reference tokens?

**Comment by a-a-k** [comment]
is there any point to use reference id tokens?

**Comment by kevinchalet** [comment]
> is there any point to use reference id tokens?

It's not supported (and  couldn't be implemented in a standard way anyway)
