### ISSUE TITLE
Question : 

### ISSUE THREAD

**Issue by scharada** [openiddict/openiddict-core#435]
Hi, first thank you for sharing this great piece of software.

i am new to openiddict and looking to integrate it into an existing platform.
here is the scenario i am looking at:
the existing platform is a multi-tenant framework , it does take care of everything needed to handle tenants, users, registration, authentication .... all the nine yards. however, when it comes to external authentication, it's a bit cumbersome and lacks flexibility. in other words, hard to extend and breaks existing features if you need to extend it or change it's behavior. i.e. : you must login with a real user in order to get a token for querying APIs, which is not a good approach in many usage scenarios.

what i want to achieve is have a way to authenticate internal and external through the same process using a combination of key/app secret to generate a token used to make API calls. 
is this scenario possible ?

thank you in advance.

**Comment by kevinchalet** [comment]
Hey,

> what i want to achieve is have a way to authenticate internal and external through the same process using a combination of key/app secret to generate a token used to make API calls.

It sounds a bit vague, but that should be possible using the code or implicit flows, depending on the nature of your client apps.
