### ISSUE TITLE
POST Json: The specified 'Content-Type' header is not valid

### ISSUE THREAD

**Issue by criistii** [openiddict/openiddict-core#437]
Hi,
I just started using your product and it seems an excellent solution for my Web API. Great work. I managed to make the app work with POST form parameters. However, I would like to be able to POST Json, since this will be the standard communication with the web-services. Is this possible?

{
	"username" : "user",
	"password" :"****",
	"grant_type" : "password"
}

**Comment by kevinchalet** [comment]
Hey @criistii and thanks for the kind words! :+1: 

> Is this possible?

Nope, it's not. The OAuth2 specification explicitly requires sending the token request parameters using the "formurl" encoding. JSON is not allowed and thus not supported.

**Comment by criistii** [comment]
I understand. Thanks for clearing that up for me.
