### ISSUE TITLE
validate id token

### ISSUE THREAD

**Issue by chriseugenerodriguez** [openiddict/openiddict-core#438]
Hi,

I would like to know the settings I need to add to validate id token for the front end. I am using angular 2. oidc-client.js thanks.

**Comment by kevinchalet** [comment]
Hi,

Take a look at the implicit flow sample:
  - https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/AureliaApp/src/open-id-connect-configuration.ts
  - https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/AuthorizationServer/Startup.cs

**Comment by kevinchalet** [comment]
@premiumwd you're welcome.
