### ISSUE TITLE
OpenIddict schema not getting created

### ISSUE THREAD

**Issue by peterman304** [openiddict/openiddict-core#439]
Steps to reproduce...

1. Clone sample project.
2. Run openiddict-password-flow-sample AuthorizationServer & Client App.
3. Ensure database & schema is created
4. Remove the OpenIddict tables
5. Run openiddict-password-flow-sample AuthorizationServer & Client App again
6. OpenIddict tables do not get created.

It seems to me that the OpenIddict schema only is created when AspNetCoreIdentity schema is created.

Problem:
I'm adding this to an existing project where the AspNetCoreIdentity schema is already in place, and therefor the OpenIddict schema is not getting created.

Surely I can't be the only one this is happening too, am I miss understanding how EF is working?

Yes, context.Database.EnsureCreated() is being invoked...

**Comment by kevinchalet** [comment]
As the name suggests, `context.Database.EnsureCreated()` only ensures that the database is created, it doesn't check whether all the tables are present or not.

To add the OpenIddict entities in an existing app, use the EF Core migrations.

**Comment by peterman304** [comment]
@PinpointTownes Thanks, the description of .EnsureCreated() suggested that if the database does not exist it will be created and all of the schema. I thought maybe it still check the entire schema.

I'll use migrations, thanks Pinpoint.

**Comment by ddydeveloper** [comment]
@PinpointTownes good evening! 

Maybe I am not completely understand, could you explain how to set up the OpenIdDict db tables. Now I am working on the old project and try to migrate to the .net 2 version. There is an initial migration with openiddict tables, but I think this tables should be updated for the 2 version. 

Cause I am getting DbUpdateException, related with the missing columns, such as:

> Invalid column name 'ConcurrencyToken'.
Invalid column name 'Properties'.
Invalid column name 'Scopes'.
Invalid column name 'Status'.
Invalid column name 'Type'.
