### ISSUE TITLE
can't install openiddict

### ISSUE THREAD

**Issue by holap** [openiddict/openiddict-core#441]
Hi, I followed the instruction to add OpenIddict (2) packages, but Visual Studio can't find them.
![image](https://user-images.githubusercontent.com/6776194/29993712-c63fe38e-8fbe-11e7-8fc8-ba1f7d8883b2.png)

Any suggestion? Anyone has done it successfully?

**Comment by kevinchalet** [comment]
Hey,

Have you tried to restart VS?

**Comment by Murf** [comment]
Solution is to remove/not add "NuGet.Config" and instead add the aspnet-contrib package source via the configuration UI

**Comment by kevinchalet** [comment]
Can you please try to specify an explicit version? E.g 2.0.0-preview1-0649.

**Comment by holap** [comment]
Finally I was able to install openiddict with the command at this link https://www.myget.org/feed/aspnet-contrib/package/nuget/OpenIddict.

PM> Install-Package OpenIddict -Version 2.0.0-preview1-0649 -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json

After a restart of Visual Studio errors disappeared.

**Comment by kevinchalet** [comment]
This is likely a NuGet bug, probably related to https://github.com/NuGet/Home/issues/5537. I suppose it will be "solved" as soon as OpenIddict is uploaded to NuGet.org.

/cc @mishra14

**Comment by mishra14** [comment]
@PinpointTownes, I am not certain it is a nuget issue. I do not see open id dict on nuget.org. Plus the instructions by @holap seem to correct, if the package is only available on a specific source.

**Comment by kevinchalet** [comment]
> I do not see open id dict on nuget.org.

That's why I said `I suppose it will be "solved" as soon as OpenIddict is uploaded to NuGet.org` (i.e it's not yet on NuGet.org) :sweat_smile:

**Comment by kevinchalet** [comment]
Now that the OpenIddict packages are on NuGet.org, you should no longer see this error.

Read the announcement here: http://kevinchalet.com/2017/10/20/the-new-asos-and-openiddict-packages-are-now-on-nuget-org/.
