### ISSUE TITLE
~/connect/authorize endpoints decorated with Authorize

### ISSUE THREAD

**Issue by frostythecodeman** [openiddict/openiddict-core#442]
Hello, after taking a look at your server sample and trying it myself I noticed that the methods tied to the ~/connect/authorize endpoint are decorated with the Authorize attribute. Could you kindly explain why this is? 

Of course, when I try to use the authorization flow using postman it fails until I remove the Authorize decoration. Am I missing something?

**Comment by kevinchalet** [comment]
Hey,

> Could you kindly explain why this is?

The `[Authorize]` attribute is simply here to automatically redirect the user to the login page if he/she's no already logged in.

Could you tell us more about the issue you're seeing?

**Comment by frostythecodeman** [comment]
The use case is really when using postman and the authorization tab then selecting OAuth 2.0. 

I entered the information for the server but it always fails, I assume it fails due to the authorize decoration.

**Comment by kevinchalet** [comment]
Are you using the standalone/desktop Postman version? If so, please try with the Google Chrome extension version.

**Comment by frostythecodeman** [comment]
I am loading it from google chrome. Once the authorize attrib decorates the method it doesn't go through. Looking forward to your insight, how would it go through in postman if the Authorize is still decorating the method?

**Comment by kevinchalet** [comment]
Take a look at the "cookies" window to ensure the cookie is correctly retrieved by Postman.
