### ISSUE TITLE
 Unable to create or track an entity of type 'OpenIdTokenExtension' because it has a null primary or alternate key value.

### ISSUE THREAD

**Issue by maksym-devpro** [openiddict/openiddict-core#444]
Hello everyone

Please help me with customizing OpenIddictApplication

First of all I found how solved this issue here
https://github.com/openiddict/openiddict-core/issues/434

So I have next implementation custom OpenIdApplication:

    public class OpenIdApplicationExtension : OpenIddictApplication<string, OpenIdAuthorizationExtension, OpenIdTokenExtension>
    {
        public virtual OpenIdApplicationInfo OpenIdApplicationInfo { get; set; }

        public Guid? OpenIdApplicationInfoId { get; set; }
    }

    public class OpenIdAuthorizationExtension : OpenIddictAuthorization<string, OpenIdApplicationExtension,  OpenIdTokenExtension>
    {
    }

    public class OpenIdScopeExtension : OpenIddictScope<string>
    {
    }

    public class OpenIdTokenExtension : OpenIddictToken<string, OpenIdApplicationExtension,  OpenIdAuthorizationExtension>
    {
    }

		services.AddOpenIddict<OpenIdApplicationExtension,
                                    OpenIdAuthorizationExtension,
                                    OpenIdScopeExtension,
                                    OpenIdTokenExtension>
                (options =>
                {
                    options.AddEntityFrameworkCoreStores<ApplicationDbContext>();
                    options.AddMvcBinders();
                    options.EnableAuthorizationEndpoint(RouteConst.OAuth.AUTHORIZE)
                        .EnableLogoutEndpoint(RouteConst.OAuth.LOGOUT)
                        .EnableTokenEndpoint(RouteConst.OAuth.TOKEN)
                        .EnableUserinfoEndpoint(RouteConst.USERINFO);

                    options.AllowAuthorizationCodeFlow();

                    options.EnableRequestCaching();
                });

            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseSqlServer(aspUsersConStr);
                options.UseOpenIddict<
                                      OpenIdApplicationExtension,
                                      OpenIdAuthorizationExtension,
                                      OpenIdScopeExtension,
                                      OpenIdTokenExtension,
                                      string>();
            });

  

In this method I get error
 	public async Task<IActionResult> GetIdentityTokenAsync(OpenIdConnectRequest request, ClaimsPrincipal claimsPrincipal)
        {
            // Retrieve the profile of the logged in user.
            ApplicationUser user = await this._userManager.GetUserAsync(claimsPrincipal);

            if (user == null)
            {
                return this.CreateErrorUiResponse(OpenIdConnectConstants.Errors.ServerError, SERVER_ERROR);
            }

            ClaimsPrincipal principal = await this._signInManager.CreateUserPrincipalAsync(user);
        
            AuthenticationTicket ticket = this._tokenManager.CreateAuthenticationTicket(request, principal);
            
            // Returning a SignInResult will ask OpenIddict to issue the appropriate access/identity tokens.
            return this.SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
        }

When I try  SignIn ticket I get error
InvalidOperationException: Unable to create or track an entity of type 'OpenIdTokenExtension' because it has a null primary or alternate key value.
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap.Add(InternalEntityEntry entry)

http://screenshots.client-demo-site.net/scn-20170906-151221-rw1qy.png

Please explain where there can be an error in code.

kind regards

**Comment by kevinchalet** [comment]
Could you please try to add a constructor that populates the `Id` property?

Something like that:

```csharp
public class OpenIdTokenExtension : OpenIddictToken<string, OpenIdApplicationExtension,  OpenIdAuthorizationExtension>
{
    public OpenIdTokenExtension()
    {
        // Generate a new string identifier.
        Id = Guid.NewGuid().ToString();
    }
}
```

**Comment by maksym-devpro** [comment]
thank you so much!!
It's works!

**Comment by kevinchalet** [comment]
Glad it solved your issue :+1:
