### ISSUE TITLE
Request to Sign up page

### ISSUE THREAD

**Issue by sharifnascenia** [openiddict/openiddict-core#447]
I the Mvc.CLient Porject the following code take the request to 
“Login” action of the “AccountController” in  Mvc.Server  Project
With  a  request token id

`[HttpGet("~/signin")]
        public ActionResult SignIn()
        {
            // Instruct the OIDC client middleware to redirect the user agent to the identity provider.
            // Note: the authenticationType parameter must match the value configured in Startup.cs
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectDefaults.AuthenticationScheme);
        }
`
I think the schema actually take the AuthenticationScheme  from start up 
` .AddCookie(options =>
            {
                options.LoginPath = new PathString("/signin");
            })
`
Now the question is I want to go directly to the  “Register” action of the “AccountController” in  Mvc.Server  Project With  a  request token id  similar as the log in request

How can I go to the “Register” action of the “AccountController” having token so that after registration I can stay signed in?

Thanks

**Comment by kevinchalet** [comment]
One option is to avoid decorating your `Authorize` action with `[Authorize]` and manually use `RedirectToAction` to redirect the user to the page you want, based on specific conditions (e.g a parameter in the URL).

**Comment by anorborg** [comment]
@PinpointTownes, I have a follow-up question on this. Where is the logic that determines where the user is sent when challenged? I don't see any references to the Account/Login view in any of the configuration or code?

**Comment by kevinchalet** [comment]
@anorborg assuming your authorization endpoint is protected by cookies authentication, this is handled by the MSFT cookie handler:

  - https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L456
  - https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/PostConfigureCookieAuthenticationOptions.cs#L47
  - https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationDefaults.cs#L27

**Comment by anorborg** [comment]
Thanks @PinpointTownes !
