### ISSUE TITLE
Question: openiddict-core/samples/mvc.client: User.Identity.Name null

### ISSUE THREAD

**Issue by UnknownQuestions** [openiddict/openiddict-core#449]
Hi,
I'm trying out the sample from openiddict-core, but can't figure out why User.Identity.Name always returns null (mvc.client/views/shared/home.cshtml).
I thought
`
services.Configure<IdentityOptions>(options =>
{
options.ClaimsIdentity.UserNameClaimType = OpenIdConnectConstants.Claims.Name;
options.ClaimsIdentity.UserIdClaimType = OpenIdConnectConstants.Claims.Subject;
options.ClaimsIdentity.RoleClaimType = OpenIdConnectConstants.Claims.Role;
});
`
would automatically map these things?
As a complete noobie I tried to add this configuration to the mvc.client startup, but that didn't make any difference.
Could someone lead me into the right direction plz?
thx

**Comment by daiiawn** [comment]
We are also having a similar issue on our side having upgraded to core 2.0. Logging in seems to be working fine and we're getting a token passed back to the client. But when the client is trying to do any authenticated action and passing the token back to the server, if we try and access the OpenIdConnectConstants.Claims.Subject value, it is always null and not giving us the userID.

**Comment by kevinchalet** [comment]
For `Identity.Name` to be non-null, you must disable the claims mapping feature used by the OIDC handler and set the correct claim types. Here's an example of how to do that (all the samples have been updated to use this approach): https://github.com/openiddict/openiddict-core/commit/ae54086ae993d17cf884cf0a719fa3f1bd0c65a8.
