### ISSUE TITLE
Embedding OpenIddict in MVC app question

### ISSUE THREAD

**Issue by jimnorth55** [openiddict/openiddict-core#45]
It appears that your Mvc.Server sample would provide a starting place for building an MVC application with an embedded OpenIddict server.  Is this correct, and are there any caveats?

**Comment by kevinchalet** [comment]
Yes, the Mvc.Server sample demonstrates how you can integrate your own OpenID Connect server to support interactive flows (which is the recommended approach).

We don't provide a sample for the resource owner password grant yet, but @capesean wrote [one for his blog](http://capesean.co.za/blog/asp-net-5-jwt-tokens/): https://github.com/capesean/openiddict-test.

**Comment by jimnorth55** [comment]
Thank you for your time and assistance!
