### ISSUE TITLE
The application associated with the token cannot be found

### ISSUE THREAD

**Issue by nourBerro** [openiddict/openiddict-core#456]
visual studio upgraded the openiddic library  automatically because i used 1.0.0-* version, so i got version : 1.0.0-rc1-0684
but when i  AllowRefreshTokenFlow i got this exception "The application associated with the token cannot be found"

i understood that this exception thrown because there is no application data in database, but why do i need application Data in the database when im not using any external resources. and how do i solve this issue

**Comment by kevinchalet** [comment]
Thanks for reporting that, it's indeed an unwanted regression.

I just committed a fix and new packages were published to the MyGet.org. Please give the `1.0.0-rc1-0686` packages a try and let me know if you're still seeing this exception.
