### ISSUE TITLE
changelog for new releases

### ISSUE THREAD

**Issue by adnan-kamili** [openiddict/openiddict-core#457]
Hi, 

Do you maintain a changelog for the new releases so that we can take necessary changes if required in the code.

**Comment by kevinchalet** [comment]
I opened a ticket on the docs repo to track that: https://github.com/openiddict/openiddict-core/issues/457.

In the meantime, you can read https://github.com/openiddict/openiddict-core/issues/462 for more information about the most visible recent change.

**Comment by bastienJS** [comment]
No changelog please, rather sth like: https://github.com/angular/angular-cli/releases
