### ISSUE TITLE
Enumerating OpenIddictApplications via manager

### ISSUE THREAD

**Issue by HenrikTP** [openiddict/openiddict-core#464]
I am trying to make an interface for managing client applications on my OpenIddict auth server.

Not being able to get info from context (not out of the box) i looked at the OpenIddictApplicationManager and it has 1 method of enumerating applications "ListAsync" but I can not seem to figure out how it is used.

Can anyone provide an example or maybe an alternative way to accomplish this?

(I want to load the OpenIddictApplications into a List<MyApplicationViewModel> and it looks like the ListAsync<MyApplicationViewModel> supports that operation directly via a MyApplicationViewModel[] if i can only figure out the syntax).

**Comment by kevinchalet** [comment]
> Not being able to get info from context (not out of the box)

Note that you can add a `public DbSet<OpenIddictApplication> Applications` property to your DB context if you want to expose the application entity and use it your own code.

> Can anyone provide an example or maybe an alternative way to accomplish this?

The syntax is quite straightforward. For instance, if you want to retrieve 10 applications (and skip the 20 first ones for pagination), you can use:

```csharp
var apps = await _applicationManager.ListAsync(applications =>
    applications.OrderBy(application => application.ClientId)
                .Take(10)
                .Skip(20), CancellationToken.None);
```

If you need to retrieve all the applications and project them to `MyApplicationViewModel` without any filtering, you probably can do:

```csharp
var apps = await _applicationManager.ListAsync(applications => applications.Select(application => new MyApplicationViewModel { ClientId = application.Client }), CancellationToken.None);
```

**Comment by HenrikTP** [comment]
Thank you for the answer.
