### ISSUE TITLE
Setting up custom scope

### ISSUE THREAD

**Issue by HenrikTP** [openiddict/openiddict-core#465]
I am fairly new to openid and auth in mvc and are creating an openiddict auth server and client mvc app as shown in the authorization code flow sample. I need to add companyid from my application user to my claims and are trying to figure out the steps needed.

So far i found out the following:
1. I add the scope to ticket in AuthrizationController.CreateTicketAsync in call to ticket.SetScopes.
2. I add the destination to my claims in AuthrizationController.CreateTicketAsync
3. I add the check for scope and conditionally add claims in UserInfoController
4. I add the scope to my options when calling AddOpenIdConnect in my client so it will be added to requests.

This seems to be working as intended. 

Can someone pls. comment on these steps or maybe point out a sample that shows this particular kind of implementation? (It seems very basic but i have no idea if i have done something really bad in the process).

/thx

**Comment by HenrikTP** [comment]
Hmm...maybe this should have been posted in stackoverflow. Closing this one.

**Comment by kevinchalet** [comment]
Feel free to post the link once you posted it.

**Comment by HenrikTP** [comment]
I posted it on StackOverflow https://stackoverflow.com/questions/46401049/setting-up-custom-scope-for-openiddict-mvc-core-2-0
