### ISSUE TITLE
Tokens with no expiration are not allowed

### ISSUE THREAD

**Issue by adnan-kamili** [openiddict/openiddict-core#470]
I am implementing personal access tokens (JWT) as a replacement for Api Key. The token is issued by a separate endpoint (not openiddict). 

I have kept the structure similar to the jwt tokens issued by the openiddidct `token` endpoint.

Everything works fine, but if I create a personal access token with no expiry (no `exp` claim), **openiddict middleware** rejects the request:

"www-authenticate": "Bearer error=\"invalid_token\", error_description=\"The token has no expiration\"",

How can I prevent that from happening? Is there some config to allow that. 

Please note I am allowing users to revoke the personal access token by storing `jti` in the database for personal access tokens.

**Comment by kevinchalet** [comment]
That's not an OpenIddict error but something returned by the JWT handler.

Feel free to ask your question here: https://github.com/aspnet/Security.

**Comment by adnan-kamili** [comment]
Setting `RequireExpirationTime = false` in `TokenValidationParameters` fixed the issue
