### ISSUE TITLE
The specified authorization code is no longer valid

### ISSUE THREAD

**Issue by adnan-kamili** [openiddict/openiddict-core#471]
Hi,

I am trying the autorization_code grant type. Everything works fine and I can see code getting generated in the addressbar:

`https://app.getpostman.com/oauth2/callback?code=CfDJ8H0dZC4WZVpMpIpqgakyGz8jr-0YKMnFhQXMcEEXgQCdpW2-hUi25ZR9FXXxepHSWdZadNV9S_dAi6aAHjm.....`

When I try to generate the access token using the code, I get the error:

```
{
    "error": "invalid_grant",
    "error_description": "The specified authorization code is no longer valid."
}
```

I checked the database and I see that `CipherText` and `Hash` columns have null values rest all other fields are correctly populated.

Following is the request log:

[16:32:56 INF] The token request was successfully extracted from the HTTP request: {
  "client_id": "369c2a2b171e4bce970b84810b8a7a49",
  "code": "[removed for security reasons]",
  "grant_type": "authorization_code",
  "redirect_uri": "https://www.getpostman.com/oauth2/callback",
  "client_secret": "[removed for security reasons]"
}.

OpenIddict.OpenIddictHandler:Information: The token request was successfully validated.
info: OpenIddict.OpenIddictHandler[0]
      The token request was successfully validated.
[16:32:57 INF] The token request was successfully validated.

fail: OpenIddict.OpenIddictHandler[0]
      The token request was rejected because the authorization code or the refresh token was expired.
OpenIddict.OpenIddictHandler:Error: The token request was rejected because the authorization code or the refresh token was expired.
[16:32:57 ERR] The token request was rejected because the authorization code or the refresh token was expired.
OpenIddict.OpenIddictHandler:Information: The token response was successfully returned: {
  "error": "invalid_grant",
  "error_description": "The specified authorization code is no longer valid."
}.

**Comment by kevinchalet** [comment]
Hey,

> I checked the database and I see that CipherText and Hash columns have null values rest all other fields are correctly populated.

These properties are only used when enabling reference tokens.

Authorization codes expire after 5 minutes by default. Are you sure you're not waiting too much time before redeeming your authorization code?

**Comment by adnan-kamili** [comment]
Thanks, it seemed to be the time issue only. I wonder what is the purpose of **azp** claim in the token created through code flow.

Secondly, the access token created would expire after some time - 3600 seconds, how will the client again get the access token, as code will expire after 5 mins?

Do I need to provide refresh token too to the client, I suppose that should be must to allow the client to get the token again.

**Comment by kevinchalet** [comment]
> I wonder what is the purpose of azp claim in the token created through code flow.

azp = authorized party (the client app which is allowed to present a token).

> Do I need to provide refresh token too to the client, I suppose that should be must to allow the client to get the token again.

Yes. Take a look at the refresh token flow sample to see how it's implemented.
