### ISSUE TITLE
Can I use mvc client with ImplicitFlow?

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#472]
Can I use mvc client with ImplicitFlow?

I have a fully API project.
I need to authenticate an MVC project .

Project.API = API only
Project.Web = MVC and will consume the API for all, it only render the views with html helper

It is a project only for the frontend, but it is not SPA yet, all routes are made by the server

How do I do that?

**Comment by kevinchalet** [comment]
> Can I use mvc client with ImplicitFlow?

Although I don't recommend it, you can.

> How do I do that?

Register your MVC app as a public app and it should be enough.
