### ISSUE TITLE
Implement JWT on resource server API auth

### ISSUE THREAD

**Issue by HenrikTP** [openiddict/openiddict-core#473]
HI! 

I have put up this question on stackoverflow:

[openiddict-mvc-core-2-0-and-jwt-on-resource-server-api](https://stackoverflow.com/questions/46422535/openiddict-mvc-core-2-0-and-jwt-on-resource-server-api
)
The question was a little diffuse when I first entered it but I edited it and it is now 2 specific questions about JWT on resource server and I'm sure its pretty straight-forward. So if you can spare time to look at it again (I suspect that you may have seen it when it was not as well defined) I would really appreciate it. (I only need these 2 questions answered to be able to finish this entire task).

**Comment by HenrikTP** [comment]
@PinpointTownes could I ask you to take a look at this at some point? (I think you may have seen it b4 I edited it).
Should I re-post it in full here?

**Comment by kevinchalet** [comment]
I'll try to post an answer today, but basically you shouldn't use the OIDC handler for your resource server. Use the JWT handler instead.

**Comment by kevinchalet** [comment]
Answered on SO.
