### ISSUE TITLE
What is hybrid client?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#475]
Is it a concept of some standard?

**Comment by kevinchalet** [comment]
It's an OpenIddict concept inspired by how the hybrid flow works.

In a nutshell: hybrid clients behave the exactly same way as confidential clients except they are allowed to retrieve an access token from the authorization endpoint. This allows creating "hybrid" applications that have a JS frontend using the access token directly and a server-side backend retrieving another access token using the authorization code.
