### ISSUE TITLE
Refresh token request always returns 400 in 2.0.0-rc1-0713 

### ISSUE THREAD

**Issue by korzh** [openiddict/openiddict-core#476]
Hello,

We updated to version 2.0.0-rc1-0713 version 2 days ago. Since that time all requests to /connect/token with "refresh_token" grant type return 400 (Bad Request) code. The refresh token we send is exactly the same we got from original /connect/token request with "password" grant type. 
We didn't change anything except obvious changes in our implementation of IOpenIddictApplicationStore because of the changes in the interface in the latest update.

Here is the log from the Output panel:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:28186/connect/token application/x-www-form-urlencoded 2317
Microsoft.AspNetCore.Cors.Infrastructure.CorsService:Information: Policy execution successful.
OpenIddict.OpenIddictHandler:Information: The token request was successfully extracted from the HTTP request: {
  "refresh_token": "[removed for security reasons]",
  "client_id": "aistant-web",
  "grant_type": "refresh_token",
  "scope": "openid offline_access profile roles kb"
}.
OpenIddict.OpenIddictProvider:Debug: The token request validation process was not fully validated because the client 'aistant-web' was a public application.
OpenIddict.OpenIddictHandler:Information: The token request was successfully validated.
OpenIddict.OpenIddictProvider:Error: The token request was rejected because the refresh token was no longer valid.
OpenIddict.OpenIddictHandler:Error: The token request was rejected with the following error: invalid_grant ; The specified refresh token is no longer valid.
OpenIddict.OpenIddictHandler:Information: The token response was successfully returned: {
  "error": "invalid_grant",
  "error_description": "The specified refresh token is no longer valid."
}.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 193.5445ms 400 application/json;charset=UTF-8
```
I've placed a breakpoint on the first line of Exchange method of my AuthorizationController but it's not hit during this request.

**Comment by kevinchalet** [comment]
Hey,

Is your `OpenIddictTokens` table correctly populated? Does the token entry have a valid state?

I just pushed an update that includes the token identifier in the log messages. That should help you find the corresponding entry in the database.

**Comment by korzh** [comment]
Thank you. I will try it out.

**Comment by korzh** [comment]
That was it. It appears we didn't save token status before (just forgot to set Status property during token creation).
It also appears that it was not important before that update 2 days ago. :)
