### ISSUE TITLE
HTTP request with invalid access_token in the Authorization Bearer header goes on indefinitely (times out)

### ISSUE THREAD

**Issue by ArcadeRenegade** [openiddict/openiddict-core#481]
For some reason, when I do a web request with an invalid access_token in the Authorization Bearer header on my production server it goes on indefinitely until it times out.

When I do the same web request in debug mode with Visual Studio 2017 it correctly returns an immediate 4XX error.

But on my production server I have this timeout issue. It is an AWS Elastic Beanstalk environment with 2 web servers with a Redis cache for data protection / key storage behind a load balancer. The load balancer serves HTTPS:443 traffic and port forwards it to HTTP:80.

Any ideas?

**Comment by kevinchalet** [comment]
> Any ideas?

To be honest, absolutely no idea. I've deployed a bunch of OpenIddict-based apps to AWS and I've never seen such a weird thing.

**Comment by ArcadeRenegade** [comment]
Okay, this seems to have happened because I was not properly handling the forwarded headers from the load balancer. Once I set that up, the timeout stopped happening for invalid accesstokens.

Final Edit: I realized what was happening after fixing all this. An invalid access token was returning a redirect to the HTTP:80 /account/login url but that does not exist since I'm not using cookies. Also, I disabled the HTTP:80 listener on the load balancer since I exclusively use HTTPS:443. So it was just stuck timing out trying to follow the redirect :) setting up the forwarded headers stopped the timeout because it went to HTTPS:443 but still returned the 404 error because of the redirect. I changed the default schemes and now we're GUCCI 

@PinpointTownes it is returning a status code 404 rather than 401 though. I saw your response in #337 but I do have app.UseAuthentication() in my Configure() method as app.UseIdentity() is now depreciated. I do not want to use cookies in my application so I'm not sure if there is something I'm missing here now that I'm on ASP.NET Core 2.0.

Edit: ok setting the default schallenge schema to oauth bearer fixes that and now it returns a valid 401 and does not try to redirect to /Account/Login thus getting the 404 since that does not exist.

            services.AddAuthentication(options =>
            {
                options.DefaultChallengeScheme = OAuthValidationDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = OAuthValidationDefaults.AuthenticationScheme;
            }).AddOAuthValidation();


If anyone has the same timeout issue with a load balancer make sure you install the Microsoft.AspNetCore.HttpOverrides NuGet package and then add the middleware in your Startup.cs.

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, AppDbContext dbContext, RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            app.UseForwardedHeaders(GetForwardedHeadersOptions());

            ....................
        }

        private static ForwardedHeadersOptions GetForwardedHeadersOptions()
        {
            ForwardedHeadersOptions forwardedHeadersOptions = new ForwardedHeadersOptions()
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            };

            forwardedHeadersOptions.KnownNetworks.Clear();
            forwardedHeadersOptions.KnownProxies.Clear();

            return forwardedHeadersOptions;
        }

**Comment by kevinchalet** [comment]
Thanks for the detailed explanation. Hopefully, it will help other people in the same situation :clap:
