### ISSUE TITLE
PostLogoutRedirectUris and RedirectUris seem to have wrong return type

### ISSUE THREAD

**Issue by anorborg** [openiddict/openiddict-core#482]
It looks like `PostLogoutRedirectUris` and `RedirectUris` on `OpenIddictApplication` were changed recently to support multiple uris. There code looks good, but I installed the latest from myget and the return types appear to be strings oddly:

<img width="612" alt="capture 2017-10-06 at 5 42 31 am" src="https://user-images.githubusercontent.com/264755/31278816-5ba5719e-aa5b-11e7-99be-47ed4db5298b.png">
<img width="574" alt="capture 2017-10-06 at 5 42 11 am" src="https://user-images.githubusercontent.com/264755/31278817-5bbdde1e-aa5b-11e7-8580-b0c3659f4a73.png">

I have removed and re-added the packages. The version should be "2.0.0-rc1-0719". I honestly don't see from the code where it was ever properties with the plural names and string return type so not sure what it is.

Using Visual Studio Code 1.17.0 on macOS High Sierra. dotnet version 2.0.0

If there is any additional info that could help debug, let me know.

**Comment by kevinchalet** [comment]
Did you read the XML documentation?

**Comment by anorborg** [comment]
Apologies, I was confused by the updated example code here:

https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Startup.cs#L153

but now see a different class is being used as well.
