### ISSUE TITLE
"The entity type'OpenIddictToken' was not found" when scope=offline_access

### ISSUE THREAD

**Issue by matteobortolazzo** [openiddict/openiddict-core#483]
Hi, I'm trying to implement refresh tokens so I updated to 1.0.0-rc-1-0724 and I copied Startup and AuthController from the refresh [sample](https://github.com/openiddict/openiddict-samples/tree/master/samples/RefreshFlow/AuthorizationServer).

Everything works like before but when I add scope=offline_access it gives me "The entity type'OpenIddictToken' was not found".

The only thing I added is: 
`var identity = (ClaimsIdentity)principal.Identity;
            identity.AddClaim(OpenIdConnectConstants.Claims.Subject,
                user.Id.ToString(), OpenIdConnectConstants.Destinations.AccessToken,
                OpenIdConnectConstants.Destinations.IdentityToken);
            identity.AddClaim(OpenIdConnectConstants.Claims.Email,
                user.Email, OpenIdConnectConstants.Destinations.AccessToken,
                OpenIdConnectConstants.Destinations.IdentityToken);
            var roles = await _userManager.GetRolesAsync(user);
            foreach (var role in roles)
            {
                identity.AddClaim(OpenIdConnectConstants.Claims.Role,
                    role, OpenIdConnectConstants.Destinations.AccessToken,
                    OpenIdConnectConstants.Destinations.IdentityToken);
            }`

**Comment by kevinchalet** [comment]
The exception indicates the OpenIddict entities are not correctly registered in the database so make sure there's nothing wrong there.

**Comment by matteobortolazzo** [comment]
This is my configuration:
![Conf](http://i.imgur.com/SlnFBuo.png)

Already added a migration.

**Comment by kevinchalet** [comment]
Do the 4 OpenIddict tables exist in the database?

**Comment by matteobortolazzo** [comment]
Yes, without "scope=offline_access" it works fine.

**Comment by kevinchalet** [comment]
> without "scope=offline_access" it works fine

Because in this case, it doesn't create and persist a refresh token entry in the database.

You most likely have an issue with your EF or SQL config.

**Comment by matteobortolazzo** [comment]
Every other request to the DB works.
How can I find where the issue is?
This is the migration.
![](http://i.imgur.com/iUCcB7w.png)

**Comment by matteobortolazzo** [comment]
Any suggestions? I really need this. The only thing I'm asking is if there's a way to find out where the problem is.

**Comment by kevinchalet** [comment]
> Any suggestions? I really need this. The only thing I'm asking is if there's a way to find out where the problem is.

I see in the first screenshot that you use Guid as the key type when calling `options.UseOpenIddict<Guid>()` but not when calling `services.AddOpenIddict()`. Use `services.AddOpenIddict<Guid>()` and try again.

**Comment by kevinchalet** [comment]
@matteobortolazzo did that fix your issue?

**Comment by tplooker** [comment]
If it helps anyone else I had to explicitly tell my DbContext in onmodelcreating to scaffold the OpenIddict objects with 

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    //Scaffold in the required OpenIddict tables into the database
    modelBuilder.UseOpenIddict();
    base.OnModelCreating(modelBuilder);
}
```

**Comment by kevinchalet** [comment]
Closing as we haven't heard back from the OP.
