### ISSUE TITLE
Scope Restrictions per Application

### ISSUE THREAD

**Issue by matthewwren** [openiddict/openiddict-core#488]
Hi there,

This is my first time implementing an oAuth server, so I just have a couple of noob questions.

Is there a way out of the box that I can restrict which scopes an application may request?  My current thought is deriving from the application class and adding the scope restrictions there, but I wanted first to check if that is the right thing to do in openiddict?

Also, I don't want to allow the user name to be passed to the client, only the token, and just use that to grab a couple of bits of data.  In other words the user will remain anonymous to the client and the client will query for certain data to authorise access to restricted pages based on certain attributes of the user.  From what I can tell the only claim I have to return is the subject, which amounts to the user id (not the user name), which is fine.

Thank you for any help in advance.

**Comment by kevinchalet** [comment]
Hey,

> My current thought is deriving from the application class and adding the scope restrictions there, but I wanted first to check if that is the right thing to do in openiddict?

Yep, this is indeed the right thing to do. To create custom entities, create classes derived from the default OpenIddict models and use the correct overloads to register them:

```csharp
public class MyApplication : OpenIddictApplication<long, MyAuthorization, MyToken>
{
    public bool CanUseProfileScope { get; set; }
}
public class MyAuthorization : OpenIddictAuthorization<long, MyApplication, MyToken> { }
public class MyScope : OpenIddictScope<long> { }
public class MyToken : OpenIddictToken<long, MyApplication, MyAuthorization> { }
```

```csharp
services.AddOpenIddict<MyApplication, MyAuthorization, MyScope, MyToken>();
```

```csharp
services.AddDbContext<ApplicationDbContext>(options =>
{
    options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
    options.UseOpenIddict<MyApplication, MyAuthorization, MyScope, MyToken, long>();
});
```

Then, in your authorization controller, you can add custom logic to either reject the request when the client requests the `profile` scope when it's not allowed to do so or simply ignore the `profile` scope when you create the authentication ticket (both are allowed by the OAuth2 specification).

```csharp
var application = await _applicationManager.FindByClientIdAsync(request.ClientId, HttpContext.RequestAborted);
if (!application.CanUseProfileScope && request.HasScope(OpenIdConnectConstants.Scopes.Profile))
{
    return BadRequest(new OpenIdConnectResponse
    {
        Error = OpenIdConnectConstants.Errors.InvalidRequest,
        ErrorDescription = "This client application is not allowed to request the 'profile' scope."
    });
}
```

**Comment by matthewwren** [comment]
Thank you very much for your help.  I did exactly what you said and it all works, although I added a string array of scopes to the derived application class.  To see how I used that to restrict the scopes requested see the code at the bottom of this post.

I do have one further related problem in that I can't seem to stop the client from the demo code requesting the "profile" scope.  Do you know how you turn that off/on in OpenIddict, it seems to be requesting it automatically.  Here is the client startup class:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })

            .AddCookie(options =>
            {
                options.LoginPath = new PathString("/signin");
            })

            .AddOpenIdConnect(options =>
            {
                options.ClientId = "xyz";
                options.ClientSecret = "5191D32A-8FA7-4C85-80AC-8294D3D518F6";
                options.RequireHttpsMetadata = false;
                options.GetClaimsFromUserInfoEndpoint = false;
                options.SaveTokens = true;
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
                options.Authority = "https://localhost:12345/";
                options.Scope.Add("custom");
                options.SecurityTokenValidator = new JwtSecurityTokenHandler
                {
                    InboundClaimTypeMap = new Dictionary<string, string>()
                };
            });
            services.AddMvc();
            services.AddSingleton<HttpClient>();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseDeveloperExceptionPage();
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvc();
        }
    }
===========================================================

As promised here is how I restrict the scopes requested per application.

The authorize method is as follows:

        [Authorize, HttpGet("~/connect/authorize")]
        public async Task<IActionResult> Authorize(OpenIdConnectRequest request)
        {
            Debug.Assert(request.IsAuthorizationRequest(),
                "The OpenIddict binder for ASP.NET Core MVC is not registered. " +
                "Make sure services.AddOpenIddict().AddMvcBinders() is correctly called.");

            var application = await _applicationManager.FindByClientIdAsync(request.ClientId, HttpContext.RequestAborted);
            if (application == null)
            {
                return View("Error");
            }

            var scopes = request.GetScopes();
            **var unauthorizedScopes = scopes.Where(x => !application.Scopes.Contains(x)).ToList();
            if (unauthorizedScopes.Any())
            {
                return BadRequest(new OpenIdConnectResponse
                {
                    Error = OpenIdConnectConstants.Errors.AccessDenied,
                    ErrorDescription = $"You are not authorized to request the scopes {string.Join(",", unauthorizedScopes)}."
                });
            }**

            return View(new AuthorizeViewModel
            {
                ApplicationName = application.DisplayName,
                RequestId = request.RequestId,
                Scope = request.Scope
            });
        }

Then the code for creating the ticket is as follows:

        private async Task<AuthenticationTicket> CreateTicketAsync(
            OpenIdConnectRequest request, 
            ApplicationUser user,
            AuthenticationProperties properties = null)
        {
            var principal = await _signInManager.CreateUserPrincipalAsync(user);

            var ticket = new AuthenticationTicket(principal, properties, OpenIdConnectServerDefaults.AuthenticationScheme);

            if (!request.IsAuthorizationCodeGrantType() && !request.IsRefreshTokenGrantType())
            {

                var application = await _applicationManager.GetAsync(x => x.Where(y => y.ClientId == request.ClientId), new CancellationToken());

                var scopes = request.GetScopes();
                ticket.SetScopes(new[]
                {
                    OpenIdConnectConstants.Scopes.OpenId,
                    CustomOpenIdConnectConstants.Scopes.Custom
                }.Intersect(scopes).Intersect(application.Scopes));
            }

            ticket.SetResources("resource_server");
            foreach (var claim in ticket.Principal.Claims)
            {
                if (claim.Type == _identityOptions.Value.ClaimsIdentity.SecurityStampClaimType)
                {
                    continue;
                }
                var destinations = new List<string>
                {
                    OpenIdConnectConstants.Destinations.AccessToken
                };
                if (claim.Type == CustomOpenIdConnectConstants.Claims.Custom && ticket.HasScope(CustomOpenIdConnectConstants.Scopes.Custom))
                {
                    destinations.Add(OpenIdConnectConstants.Destinations.IdentityToken);
                }
                claim.SetDestinations(destinations);
            }
            return ticket;
        }

**Comment by kevinchalet** [comment]
> Do you know how you turn that off/on in OpenIddict, it seems to be requesting it automatically.

OpenIddict doesn't handle the client part. You can force the OIDC handler not to send the `profile` scope by calling `options.Scope.Clear()` in the OIDC options.

**Comment by kevinchalet** [comment]
Note: since you're implementing an interactive flow, you should return a view instead of a JSON response as I initially suggested (I thought you were using the password flow).

Alternatively, you can also ask OpenIddict to return the user back to the client:

```csharp
if (unauthorizedScopes.Any())
{
    var properties = new AuthenticationProperties(new Dictionary<string, string>
    {
        [OpenIdConnectConstants.Properties.Error] = OpenIdConnectConstants.Errors.InvalidRequest,
        [OpenIdConnectConstants.Properties.ErrorDescription] = $"You are not authorized to request the scopes {string.Join(",", unauthorizedScopes)}."
    });

    // Ask OpenIddict to return an invalid_request error to the client application.
    return Forbid(properties, OpenIdConnectServerDefaults.AuthenticationScheme);
}
```

**Comment by matthewwren** [comment]
Great.  That is all working.  Many thanks for your help.
