### ISSUE TITLE
An unhandled exception after updating to 2.0.0-rc1-0733

### ISSUE THREAD

**Issue by korzh** [openiddict/openiddict-core#489]
My project has updated to the version 2.0.0-rc1-0733 of OpenIddict today (we set version as "2.0.0-*" to always compile against the latest update). 
We modified our implementation for stores and replaced all arrays used there with ImmutableArray.  
Then we compiled and ran the project. 
The app runs well but during the token exchange process we got the following exception:
```
An unhandled exception of type 'System.ExecutionEngineException' occurred in AspNet.Security.OpenIdConnect.Extensions.dll
```
The exception occurs during controller's SingIn method call.

**Comment by kevinchalet** [comment]
As announced on Gitter, I had to introduce API changes in ASOS 2.0.0-rc1 for OpenIddict RC1, which required rebuilding the `2.0.0-rc1-final` version. Can you please remove the ASOS bits from your .nuget\packages folder and try again?

**Comment by kevinchalet** [comment]
Here are the packages you must remove before restoring:

![image](https://user-images.githubusercontent.com/6998306/31493546-fa37a180-af4f-11e7-8c2d-51b72a5f280c.png)

**Comment by korzh** [comment]
Yes. It works!
Thank you.

I didn't have any 'owin.security.*' packages in my Nuget cache by the way

**Comment by kevinchalet** [comment]
Let's keep this ticket open to make it more visible, in case other people would see a similar exception.

> I didn't have any 'owin.security.*' packages in my Nuget cache by the way

These packages are only used if you develop a legacy OWIN/Katana app :smile:

**Comment by ArcadeRenegade** [comment]
Hi @PinpointTownes 

I am getting this error after the latest update. This is with a brand new clean migration and database.

An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
lambda_method(Closure , QueryContext , ValueBuffer )

Stack Query Cookies Headers
NullReferenceException: Object reference not set to an instance of an object.
lambda_method(Closure , QueryContext , ValueBuffer )
Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper+TypedProjectionShaper.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable+AsyncEnumerator+<BufferlessMoveNext>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy+<ExecuteAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable+AsyncEnumerator+<MoveNext>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Linq.AsyncEnumerable+<SingleOrDefault_>d__381.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+TaskResultAsyncEnumerable+Enumerator+<MoveNext>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+ExceptionInterceptor+EnumeratorExceptionInterceptor+<MoveNext>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<ExecuteSingletonAsyncQuery>d__23.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OpenIddict.Core.OpenIddictTokenStore+<GetAuthorizationIdAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OpenIddict.OpenIddictProvider+<CreateTokenAsync>d__24.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
OpenIddict.OpenIddictProvider+<SerializeRefreshToken>d__40.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler+<SerializeRefreshTokenAsync>d__27.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler+<SignInAsync>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationService+<SignInAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.SignInResult+<ExecuteResultAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by ArcadeRenegade** [comment]
Disregard. Deleting those package folders from C:\Users\Me\\.nuget\packages and then restoring packages fixed the issue.

**Comment by kevinchalet** [comment]
@ArcadeRenegade interesting, that looks like an EF issue and the API change that requires clearing your packages shouldn't cause that.

It seems EF didn't like this query:

```csharp
var key = await GetAsync(tokens =>
    from element in tokens
    where element.Id.Equals(token.Id)
    select element.Authorization.Id, cancellationToken);

return ConvertIdentifierToString(key);
```

**Comment by kevinchalet** [comment]
The error message looks identical to [the one reported in this EF Core bug](https://github.com/aspnet/EntityFrameworkCore/issues/9804), tho' the root cause seems different (the OpenIddict entities don't use inheritance).

Do you use custom entities?

**Comment by ArcadeRenegade** [comment]
I use Hangfire, Identity with a custom AppUser\<int> and AppRole\<int>, and many custom entity classes for the business logic.

**Comment by kevinchalet** [comment]
I meant custom OpenIddict entities, and more particularly the token and authorization classes.

**Comment by ArcadeRenegade** [comment]
Oh I see. No I don't have any custom OpenIddict entities. I basically have the same code as the OAuth sample but I added a custom Facebook and Google external login flow. And my Identity entities use \<int> keys. I also specify \<int> keys for OpenIddict.

I also move the OpenIddict entities to their own schema in my DbContext.OnModelCreating:

```
builder.Entity<OpenIddictApplication<int>>(e => { e.ToTable("Applications", "OpenIddict"); });

builder.Entity<OpenIddictAuthorization<int>>(e => { e.ToTable("Authorizations", "OpenIddict"); });

builder.Entity<OpenIddictScope<int>>(e => { e.ToTable("Scopes", "OpenIddict"); });

builder.Entity<OpenIddictToken<int>>(e => { e.ToTable("Tokens", "OpenIddict"); });
```

**Comment by kevinchalet** [comment]
Okay, good to know. Please let me know if you see this exception again so we can consider using a different API to retrieve the authorization identifier associated with a token.

**Comment by Gillardo** [comment]
Cleared nuget and ran `dotnet restore`, and mine working to. Thank you!

**Comment by kevinchalet** [comment]
@Gillardo on a totally unrelated note, did you have a chance to test the "official" Entity Framework 6 stores? They'll be part of the RC1 release, so that would be cool to determine if you see any missing feature/bug.

**Comment by Gillardo** [comment]
Yep I am using them now they seem to be working fine.

Migrations aren't included at the moment are they? As I have experienced
problems when changes have been done but I have just deleted the tables and
entry in migration history table and all ok
