### ISSUE TITLE
Authorizations instead of Tokens

### ISSUE THREAD

**Issue by korzh** [openiddict/openiddict-core#491]
You probably meant to use Authorizations property here instead of Tokens.

https://github.com/openiddict/openiddict-core/blob/4f4eb4348713ce46227ee4851ead201d212798d3/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictAuthorizationStore.cs#L335

**Comment by kevinchalet** [comment]
Yep, nice catch @korzh!

Thanks for reporting this bug. I fixed it in both the OpenIddict 1.x and 2.x branches and new packages should be pushed soon to MyGet by the CI server: https://github.com/openiddict/openiddict-core/commit/8404db2bec2ba9ae76778049e72860a9959cda01.
