### ISSUE TITLE
A lot of Breaking changes

### ISSUE THREAD

**Issue by AhmedRagheb** [openiddict/openiddict-core#493]
I am using openiddict in a project and every time I build it, I got Database breaking changes. 

- Is it a right approach to change Db with nullable columns without any backward compatible and without any script update the Database automatically?

- Is this library that we can use in big important projects or this is a side-fun project and there is no any rules for pushing or code-review?

I hope that my question is being understood correctly, I don't mean to underestimate your effort but also I face a lot of problems because of these many breaking changes.

**Comment by kevinchalet** [comment]
> Is it a right approach to change Db with nullable columns any without any backward compatible and without any script update the Database automatically?

"scripts" are specific to the database engines they are written for and I can't reasonably write one for every engine out there (SQL Server, PostgreSQL, MySQL, etc...).

Assuming you're using the Entity Framework Core stores, you're encouraged to use the migrations system, which is a manual operation but works generally well.

> Is this library that we can use in big important projects or this is a side-fun project and there is no any rules for pushing or code-review?

I've personally used it in security-critical projects and most of the recent breaking changes introduced in OpenIddict are directly linked to features needed in these projects.

Concerning your second point, the rules are extremely clear: I'm perfectly allowed by the semver spec to introduce any breaking change I need in pre-release versions. Maybe you haven't realized it but OpenIddict is still in pre-release (RC1 will be pushed to NuGet.org this week).

Yet, when you use pre-release software, one of the rules you have to accept is that breaking changes can be added at any time, specially if you're always using the latest packages.

Hope it answers your concerns.
