### ISSUE TITLE
The expiration date associated with a refresh token entry is not respected

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#496]
Earlier today @dasMulli (thanks to him!) reported a bug with the default refresh token handling that causes the dynamic `ExpirationDate` value stored in the database to be ignored by OpenIddict: concretely, this means that refresh tokens are considered as expired when their original expiration date is reached (just like what happens when sliding expiration is disabled).

The bug has been identified and fixed locally. Since it's a quite annoying bug, I'll likely release a hotfix this week.

In the meantime, you can use rolling tokens to work around this bug.

**Comment by kevinchalet** [comment]
Fixed: https://github.com/openiddict/openiddict-core/commit/0a409a3013453f5e1e29a9db3069dd70726e9684.

**Comment by Bartmax** [comment]
Do we know when this bug was introduced? Pretty sure I experimented this (several months ago) but I ended up using disabled sliding expiration so I never realized there was a bug.

**Comment by kevinchalet** [comment]
@Bartmax I think this regressed when introducing reference tokens support.
