### ISSUE TITLE
404 Not Found When accessing controller action annotated with [Authorize]

### ISSUE THREAD

**Issue by kkagill** [openiddict/openiddict-core#498]
Hi, I've been using openiddict since aspnet core 1.1 (working great), and decided to switch to aspnet core 2.0 recently. However, I am encountering some odd issue while I was migrating it. I am using password flow, and depending on the user role, I am trying to prohibit/allow user's access to an action. In short, I keep getting 404 Not Found. Tested on aspnet core 1.1, but it works well. 

# **core 1.1:**

    public class ValuesController : Controller
    {
        [Authorize(Roles = "Admin")]
        [HttpGet("admin")]
        public string Admin()
        {
            return "success";
        }
    }

startup.cs

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddDbContext<TestContext>(options =>
	{
		options.UseSqlServer(Configuration.GetConnectionString("TestAPI"),
		 b => b.MigrationsAssembly("Test.API"));
		options.UseOpenIddict();
	});    
   
	services.AddIdentity<ApplicationUser, IdentityRole>(options =>
	{
	    // ...        
	})
	.AddEntityFrameworkStores<TestContext>()
	.AddDefaultTokenProviders();
  
	services.Configure<IdentityOptions>(options =>
	{
		options.ClaimsIdentity.UserNameClaimType = OpenIdConnectConstants.Claims.Name;
		options.ClaimsIdentity.UserIdClaimType = OpenIdConnectConstants.Claims.Subject;
		options.ClaimsIdentity.RoleClaimType = OpenIdConnectConstants.Claims.Role;
	});

	services.AddOpenIddict(options =>
	{              
		options.AddEntityFrameworkCoreStores<TestContext>();
		options.AddMvcBinders();
		options.EnableTokenEndpoint("/connect/token");
		options.AllowPasswordFlow();
		options.DisableHttpsRequirement();

		options.UseJsonWebTokens();
		options.AddEphemeralSigningKey();
	});                  
   
	services.AddMvc();        
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, TestDbInitializer seeder)
    {
        loggerFactory.AddConsole(Configuration.GetSection("Logging"));
	loggerFactory.AddDebug();
 
	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
	JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

	app.UseJwtBearerAuthentication(new JwtBearerOptions
	{
		Authority = "http://localhost:50181/",
		Audience = "resource_server",
		RequireHttpsMetadata = false,
		TokenValidationParameters = new TokenValidationParameters
		{
			NameClaimType = OpenIdConnectConstants.Claims.Subject,
			RoleClaimType = OpenIdConnectConstants.Claims.Role
		}
	});

	app.UseIdentity();
	app.UseOpenIddict();         
	app.UseOAuthValidation();
	app.UseMvcWithDefaultRoute();
    }`

# **core 2.0**

    public class ValuesController : Controller
    {
        [Authorize(Roles = "Admin")]
        [HttpGet("admin")]
        public string Admin()
        {
            return "success";
        }
    }

startup.cs

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {          
            services.AddDbContext<TestContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("TestAPI"),
                b => b.MigrationsAssembly("TestAPI"));
                options.UseOpenIddict();
            });
			
            services.AddIdentity<ApplicationUser, IdentityRole>(options =>
            {
			    // ...
            })
                .AddEntityFrameworkStores<TestContext>()
                .AddDefaultTokenProviders();

          
            services.AddAuthentication()
                .AddOAuthValidation();

            services.Configure<IdentityOptions>(options =>
            {
                options.ClaimsIdentity.UserNameClaimType = OpenIdConnectConstants.Claims.Name;
                options.ClaimsIdentity.UserIdClaimType = OpenIdConnectConstants.Claims.Subject;
                options.ClaimsIdentity.RoleClaimType = OpenIdConnectConstants.Claims.Role;
            });

        
            services.AddOpenIddict(options =>
            {               
                options.AddEntityFrameworkCoreStores<TestContext>();
                options.AddMvcBinders();
                options.EnableTokenEndpoint("/connect/token");
                options.AllowPasswordFlow();
                options.DisableHttpsRequirement();

                options.UseJsonWebTokens();
                options.AddEphemeralSigningKey();
            });
            
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, DbInitializer seeder)
        {
            app.UseDeveloperExceptionPage();

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

			// Error saying it is deprecated
            app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                Authority = "http://localhost:50181/",
                Audience = "resource_server",
                RequireHttpsMetadata = false,
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = OpenIdConnectConstants.Claims.Subject,
                    RoleClaimType = OpenIdConnectConstants.Claims.Role
                }
            });

            app.UseAuthentication();
            app.UseMvcWithDefaultRoute();
            app.UseWelcomePage();    
        }
    }
    }

Tested on aspnet core 1.1 using postman, **/connect/token** returns valid JWT token and **/api/values/admin** returns 200 OK with the return message "success".

When testing with core 2.0, first I commented out 

    app.UseJwtBearerAuthentication section 
    && options.UseJsonWebTokens();
    && options.AddEphemeralSigningKey();

and **/connect/token** returns valid JWT token, but **/api/values/admin** returns 404 NOT FOUND.

I guess it is not recognizing [Authorize] annotation. Help is appreciated!

**Comment by kevinchalet** [comment]
Yo,

You're seeing a 404 response because the cookies handler managed by Identity is trying to redirect you to the login page, for which you don't have a controller.

To prevent that, decorate your API endpoints with `[Authorize(AuthenticationSchemes = "Bearer")]`. Alternatively, you can use path-based selection: https://stackoverflow.com/questions/46464469/how-to-configureservices-authentication-based-on-routes-in-asp-net-core-2-0/46475072#46475072.

**Comment by kkagill** [comment]
Thanks for your reply. 

**1.**
    [Route("api/[controller]")]
    [Authorize(AuthenticationSchemes = "Bearer")]
    public class ValuesController : Controller
    {
        [Authorize(Roles = "Admin")]
        [HttpGet("admin")]
        public string Admin()
        {
            return "success";
        }
    }

**2.**
Created `CustomAuthenticationSchemeProvider ` class and in startup.cs,
`services.AddSingleton<IAuthenticationSchemeProvider, CustomAuthenticationSchemeProvider>();` and in the `ValuesController`

    public ValuesController(IAuthenticationSchemeProvider provider)
    {
        _provider = provider;
    }

    [Authorize(Roles = "Admin")]
    [HttpGet("admin")]
    public string Admin()
    {
        _provider.GetAllSchemesAsync();
        return "success";
    }

Either way results in 401 Unauthorized when accessing Admin action with an admin account. Perhaps I'm not following it correctly?

**Comment by kkagill** [comment]
@PinpointTownes Works with `[Authorize(AuthenticationSchemes = "Bearer")]` when I comment out 

`options.UseJsonWebTokens();` and `options.AddEphemeralSigningKey();` in startup.cs

However, in this case I won't be able to [decode](https://jwt.io/) my access_token to check what information it contains. 

I think the problem comes from configure method where

        JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
        JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

       // Error saying it is deprecated
        app.UseJwtBearerAuthentication(new JwtBearerOptions
        {
            Authority = "http://localhost:50181/",
            Audience = "resource_server",
            RequireHttpsMetadata = false,
            TokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = OpenIdConnectConstants.Claims.Subject,
                RoleClaimType = OpenIdConnectConstants.Claims.Role
            }
        });

this section of code has been deprecated in .net core 2.0
Any workaround to enable that part please?

**Comment by tplooker** [comment]
@kkagill I could be wrong, but does the below work?

```
services.AddAuthentication(o =>
                {
                    o.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(options =>
                {
                    options.Audience = "resource-server";
                    options.Authority = Configuration["frontEndUrl"];
                    options.RequireHttpsMetadata = false;
                    options.IncludeErrorDetails = true;
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = OpenIdConnectConstants.Claims.Subject,
                        RoleClaimType = OpenIdConnectConstants.Claims.Role
                    };
                })
```

**Comment by kkagill** [comment]
@tplooker You got it right! Thanks!

I had to take out `.AddOAuthValidation();`

     services.AddAuthentication()
                 .AddOAuthValidation();

because I get an exception `System.InvalidOperationException: 'Scheme already exists: Bearer'`

OAuth2 validation handler could be registered in Configure method in .Net core 1.1 before.
`app.UseOAuthValidation();`
 
Hmm, now my concern is where I can register the OAuth2 validation handler or is it not important?

**Comment by tplooker** [comment]
@kkagill  I have just got bearer token auth fully working finally! My version doesnt require registering the OAuth2 handler my services.AddAuthentication() is pretty much as above.

**Comment by kkagill** [comment]
@tplooker Congrats! so I guess AddAuthentication() middleware is going through some sort of validation process as well.
