### ISSUE TITLE
Openiddict release roadmap

### ISSUE THREAD

**Issue by jduenas** [openiddict/openiddict-core#50]
Hi, I'm currently working on a web api and openiddict was exactly what I was looking for. So far it's working great! Thanks for the hard work. I'm currently using it to generate jwt tokens. 

Would you be able to share your thoughts on Openiddict's release roadmap?

**Comment by soeron** [comment]
This would be interesting to me too. And also would like to ask if you plan to implement unit tests?

**Comment by kevinchalet** [comment]
> Would you be able to share your thoughts on Openiddict's release roadmap?

Ideally, I'd like to release a first alpha next month (when RC2 final ships). Sadly, there are still many things to do, and I'm quite busy ATM, so there's absolutely no guarantee. If you want to contribute, don't hesitate, PRs are welcome! :smile: 

> And also would like to ask if you plan to implement unit tests?

Yes, that's planned. The first bunch of tests will be pushed to ASOS soon. No timeline for OpenIddict, though. If you want to submit a PR for that, that would be a great contribution! :clap:

**Comment by ghost** [comment]
You mentioned that there is still many things to do. Would you like to share it with us? I'd like to contribute. I gained a lot of insights working on enterprise identity solutions with AD/ADFS, IdentityServer, OAuth2 and OIDC.

I like this project because it's still small and lean.

**Comment by kevinchalet** [comment]
> I like this project because it's still small and lean.

Thanks. Glad you like it! :clap: 

> You mentioned that there is still many things to do. Would you like to share it with us? I'd like to contribute.

Sure. Most of these things are decorated with the ["help wanted"](https://github.com/openiddict/core/labels/help%20wanted) label and the most important ones are decorated with ["important"](https://github.com/openiddict/core/labels/important):
- CORS support: https://github.com/openiddict/core/issues/28
- Scope support: https://github.com/openiddict/core/issues/16 (it's assigned to Massimiliano but he's been very busy so he'll need to re-assign this task)
- Authorization storage: https://github.com/openiddict/core/issues/17

**Comment by ghost** [comment]
So are the assignees working on it?

#17 Implement authorization storage for instance is assigned to Bartmax

**Comment by kevinchalet** [comment]
@nklap looks like Bart is busy ATM. If you're interesting in contributing to this work item, feel free! :smile:

**Comment by Bartmax** [comment]
I won't be able to help for at least 15 days. I will unassign myself now and take a look at items for pickup later. I will be implementing in production in a few weeks so expect me to be more active soon.
