### ISSUE TITLE
Weirdest problem ever :-) Openiddict 1.0.0 RC2

### ISSUE THREAD

**Issue by GuidoNeele** [openiddict/openiddict-core#506]
I've got the weirdest problem. I'll try to explain what is happening.

Got a Xamarin Forms application (problem occurs both on iOS and Android) with a login page, organisations page and files page. The login page calls the auth server and requests an access_token. The access_token is successfully retrieved and is used to request a list of organisations which are returned without a problem. An organisation is then selected (doesn't matter which one) and the files page is loaded for that organisation. The files are requested but I get a 401 Unauthorized response, with the following message:
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Server: Kestrel
WWW-Authenticate: Bearer error="invalid_token", error_description="The access token is not valid."
Request-Context: appId=cid-v1:fb336710-34e4-45ca-a11b-a4c85af310d5
X-Powered-By: ASP.NET
Date: Thu, 09 Nov 2017 18:55:48 GMT
Content-Length: 0
}}
The debugger is stopped at this moment so I copy the access_token from the request and execute the same call in postman, the request returns without a problem, status 200 OK. So the token is still valid. Strange thing is that the log of the auth server was indeed showing a return value of active false for the introspect request. I then continue the application and automatically renew the access_token by using the refresh_token, reload the files page and the call to files succeeds.

Somehow, somewhere the token is probably being altered but I don't no how and if that really is the case. Is there a way to log the received token in the web api and if so how would I do that?

------------------------- auth server log -------------------------
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://xxx/connect/introspect application/x-www-form-urlencoded 1759
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The introspection request was successfully extracted from the HTTP request: {
  "token": "[removed for security reasons]",
  "token_type_hint": "access_token",
  "client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "client_secret": "[removed for security reasons]"
}.
Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'__EFMigrationsHistory');
Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'__EFMigrationsHistory');
Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory:Information: Executed DbCommand (1ms) [Parameters=[@__identifier_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [application].[Id], [application].[ClientId], [application].[ClientSecret], [application].[DisplayName], [application].[PostLogoutRedirectUris], [application].[RedirectUris], [application].[Timestamp], [application].[Type]
FROM [OpenIddictApplications] AS [application]
WHERE [application].[ClientId] = @__identifier_0
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The introspection request was successfully validated.
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The introspection request was rejected because the token was invalid.
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The introspection response was successfully returned: {
  "active": false
}.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 120.0931ms 200 application/json;charset=UTF-8

**Comment by kevinchalet** [comment]
You can change the default log level to `Trace` in the ASP.NET Core options to include the potentially sensitive data (including the access token received by the introspection endpoint).

**Comment by GuidoNeele** [comment]
Tried everything but I don't get to see the trace logs. I attach a remote debugger to an Azure app service could this be the problem for not seeing trace logs?

**Comment by kevinchalet** [comment]
>  I attach a remote debugger to an Azure app service could this be the problem for not seeing trace logs?

I don't think so.

Have you tried to add `.ConfigureLogging(options => options.AddConsole(LogLevel.Trace)).ConfigureLogging(options => options.AddDebug(LogLevel.Trace))` in `Program.Main()`?

**Comment by GuidoNeele** [comment]
Turned out I was looking at the wrong line in the log. The message "[removed for security reasons]" is still displayed but below it is a trace debug line that does show the token. Have my problem fixed, don't really know why it didn't work but I was refreshing the token far too often.
