### ISSUE TITLE
Concurrency Token

### ISSUE THREAD

**Issue by sethen** [openiddict/openiddict-core#507]
I have no idea what's going on here but I can't seem to start my app in a production environment because of the following error:

```
Nov 10 20:28:38 localhost dotnet-example[3511]: fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
Nov 10 20:28:38 localhost dotnet-example[3511]:       Failed executing DbCommand (31ms) [Parameters=[@__identifier_0='?'], CommandType='Text', CommandTimeout='30']
Nov 10 20:28:38 localhost dotnet-example[3511]:       SELECT "application"."Id", "application"."ClientId", "application"."ClientSecret", "application"."ConcurrencyToken", "application"."DisplayName", "applicati
Nov 10 20:28:38 localhost dotnet-example[3511]:       FROM "OpenIddictApplications" AS "application"
Nov 10 20:28:38 localhost dotnet-example[3511]:       WHERE "application"."ClientId" = @__identifier_0
Nov 10 20:28:38 localhost dotnet-example[3511]:       LIMIT 2
Nov 10 20:28:38 localhost dotnet-example[3511]: Npgsql.PostgresException (0x80004005): 42703: column application.ConcurrencyToken does not exist
```

This seems to be looking for a column called `CocurrencyToken` and looking in the database, I see no column in in the `OpenIddictApplications` table for it.  How do I solve this issue?

**Comment by sethen** [comment]
So, I was able to fix this issue by creating the column myself and everything seemed fined -- however I am still confused on how my application even got into this state to begin with?  Any ideas?

**Comment by kevinchalet** [comment]
> however I am still confused on how my application even got into this state to begin with?

You likely migrated from the 2.0.0-rc1-final bits to our nightly RC2 builds, where the `Timestamp` rowversion properties have all been replaced by `ConcurrencyToken` properties to work around a MySQL limitation (see https://github.com/openiddict/openiddict-core/issues/497 for more information).

When a DB schema change is introduced, you're encouraged to use Entity Framework's migrations API instead of updating the tables yourself.

**Comment by sethen** [comment]
I didn't update anything myself.  I simply shut down the service in systemd and started it back up again and it was in this state.  _Nothing_ was updated by me or done to the database.  

I do have the line `<PackageReference Include="OpenIddict" Version="2.0.0-*" />` in a `.csproj` file.  Is this what you're referring to?

**Comment by jasoncavett** [comment]
@PinpointTownes I was curious about your remark to use the EF migrations API as well. I just ran into this same thing and it's just from updating a package. I don't see any way in which to use migrations. Could you please clarify your comment? Would be much appreciated.

**Comment by sethen** [comment]
If anyone else runs into this issue, the problem was that I didn't make the migrations.  The reason being is because I was unaware that anything in the Openiddict library had changed causing a need for a migration.  Once I made the migration and ran it on the database all is well.
