### ISSUE TITLE
Usage of ValidateClientSecretAsync and the publicity of client_id

### ISSUE THREAD

**Issue by Tornhoof** [openiddict/openiddict-core#511]
Hi,
what is your point of view on the publicity of client_id in the auth flows?
According to https://tools.ietf.org/html/rfc6749#section-2.2 it's not a secret, some recommend that it should not be guessable (e.g. https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)

If your opinion is, that it should not be guessable and is rather something similar to a user name, you might want to reconsider the usage of ``ValidateClientSecretAsync``. Currently you check if the client_id results in an application, e.g.
https://github.com/openiddict/openiddict-core/blob/38e69a70341f70c035dd48271b7281565d5fd323/src/OpenIddict/OpenIddictProvider.Introspection.cs#L52-L64
and return early if no application can be found for that id. This might be used to optimize a phishing attack against client_ids, simply by checking the return time of the method calls during auth, because a fairly time intensive step is not down (your PBKDF2 password verfication).

For usernames this is then usually called a user enumeration attack, timing attacks for them are probably quite rare, usually you look at the error messages. (https://www.owasp.org/index.php/Testing_for_Account_Enumeration_and_Guessable_User_Account_(OTG-IDENT-004))

You might want to normalize the error messages, currently you have atleast two different descriptions and add a Fake password check in all error cases (just run your PBKDF2 password verification) so the method runtime is not that much different.

**Comment by kevinchalet** [comment]
Yo,

Client identifiers are public so there's, IMHO, no point trying to make them hard to guess (OpenIddict deliberately allows you to create a client registration with a simple/readable `client_id` like `react_management_interface`).

Even if we reworked the introspection logic to execute a fake client secret check, you could still use the authorization endpoint to determine whether a `client_id` is valid or not (and in this case, there's no secret you can validate).

Concerning the second point, all the samples we have deliberately use the same approach as the official VS templates, that make a 2-step check when verifying the username/password (which is indeed prone to the attack you mentioned).

We could definitely rework our samples to make a fake password verification, but it would be almost pointless as an attacker could use the user registration page to do exactly the same thing (an error is returned if the username is not unique).

/cc @blowdart in case he'd like to add more details about the templates.

**Comment by Tornhoof** [comment]
Thanks for your explanation.

**Comment by blowdart** [comment]
I have nothing to add, your reasoning is sound.

**Comment by Tornhoof** [comment]
Then let's close this.

**Comment by Bartmax** [comment]
if I understand correctly templates are subpar and does not shows best practices. (?)

**Comment by blowdart** [comment]
That's an interesting reading, but it's not how I would see it obviously. As @PinpointTownes says "_it would be almost pointless as an attacker could use the user registration page to do exactly the same thing_". I'd remove the word always from that.
