### ISSUE TITLE
Session timeout after 5 minutes of inactivity

### ISSUE THREAD

**Issue by GuidoNeele** [openiddict/openiddict-core#512]
I've got an auth server and a mvc application. After 5 minutes of inactivity on the MVC app the session is being invalidated and the user is redirected to the login page. Have been googling for an explanation of this behavior and found 2 possible reasons.
1. App pool idle timeout
2. Cookie security timestamp validation (http://www.jamessturtevant.com/posts/ASPNET-Identity-Cookie-Authentication-Timeouts/)

The app pool idle timeout should not be a problem because I set the Azure settings to be always on and the site is being pinged every 5 minutes. The seconds doesn't seem to work with openid and I'm a bit stuck now. How can I prevent the cookie from being invalidated?

Using OpenIdDict 1.0.0.RC2 and ASP.NET Core 1.1

**Comment by kevinchalet** [comment]
Have you configured ASP.NET Core Data Protection?

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore1x

**Comment by GuidoNeele** [comment]
No haven't configured it, so I'm using the default settings. Should I do that?

**Comment by kevinchalet** [comment]
If you use Azure Web Apps, it should be configured for you. For every other environment, you have to configure it yourself: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#data-protection.

(it's worth noting that your question is not really linked to OpenIddict since you mentioned yourself that cookies were impacted. This is not a part handled by OpenIddict)

**Comment by GuidoNeele** [comment]
Any ideas how I can solve 5 minutes timeout problem? Could the data protection settings have anything to do with it?

**Comment by kevinchalet** [comment]
> Could the data protection settings have anything to do with it?

Have you tried?

If it still doesn't work, I suggest opening a new thread here to get help from the ASP.NET team: https://github.com/aspnet/Security

**Comment by GuidoNeele** [comment]
Added services.AddDataProtection(); and problem was solved! Thanks a bunch!
