### ISSUE TITLE
Connecting openiddictapplication to scopes/authorizations

### ISSUE THREAD

**Issue by gustavdw** [openiddict/openiddict-core#515]
I've got a client_credentials flow up and running and can access my resources using the access token returned, but I need to secure what resources each application part of this flow may access. I'm creating policies for this, that are used by my controllers. 

So currently I seed the application into the database, is one supposed to use the OpenIddictAuthorizationManager to connect the application to what scopes can be requested and attached to the token as claims?

**Comment by kevinchalet** [comment]
Scopes an application can request are typically validated/granted in the authorization controller, when calling `ticket.SetScopes(...)`. See https://github.com/openiddict/openiddict-core/issues/488 for more information.

**Comment by gustavdw** [comment]
Thanks, however that solution stores scopes in each application instead of referencing the allowed scopes from a store of existing scopes. What is the OpenIddictScopes table used for in the database, it seems to have no relations to any other entity?

**Comment by kevinchalet** [comment]
> What is the OpenIddictScopes table used for in the database

Automatic scopes validation and scopes permissions have both been added in RC2. Read https://openiddict.github.io/openiddict-documentation/features/application-permissions.html and http://kevinchalet.com/2018/02/19/openiddict-rc2-is-now-on-nuget-org/ for more information.
