### ISSUE TITLE
400 BadRequest with this error when trying to retrieve https://aspnetcorespa.herokuapp.com/.well-known/openid-configuration document over https

### ISSUE THREAD

**Issue by asadsahi** [openiddict/openiddict-core#518]
![image](https://user-images.githubusercontent.com/3470892/33294805-2893934c-d3ca-11e7-8582-b50fba060e95.png)

Even deployed on https url, not sure what is causing this error. Any idea?

**Comment by kevinchalet** [comment]
@asadsahi https://github.com/aspnet/Docs/issues/2384 will put you on the right track.

**Comment by asadsahi** [comment]
Thanks @PinpointTownes. Just managed to get it working [this](https://github.com/aspnet/Docs/issues/2384#issuecomment-297980490) resolved the issue deploying the application on herku as container app.
