### ISSUE TITLE
Error when using UseOpenIddict<>()

### ISSUE THREAD

**Issue by jerriep** [openiddict/openiddict-core#524]
I am starting to play with OpenIddict and was using one of the generic overloads when calling `UseOpenIddict` to use an `int` primary key, e.g.

```
services.AddDbContext<SlackMapDbContext>(options =>
{
    // Configure the context to use Microsoft SQL Server.
    options.UseSqlServer(Configuration.GetConnectionString("SlackMapDbContext"));

    // Register the entity sets needed by OpenIddict.
    // Note: use the generic overload if you need
    // to replace the default OpenIddict entities.
    options.UseOpenIddict<int>();
});
```

Then when calling the authorize endpoint (or when trying to load the seed data), I was getting the following error:

```
Cannot create a DbSet for 'OpenIddictApplication' because this type is not included in the model for the context
```

This was a bit weird, because the tables were included in the database migration scripts, so it seems as though the OpenIddict types are registered on the database context.

Playing around with it I changed my code to use the non-generic version:

```
services.AddDbContext<SlackMapDbContext>(options =>
{
    // Configure the context to use Microsoft SQL Server.
    options.UseSqlServer(Configuration.GetConnectionString("SlackMapDbContext"));

    // Register the entity sets needed by OpenIddict.
    // Note: use the generic overload if you need
    // to replace the default OpenIddict entities.
    options.UseOpenIddict();
});
```

This time it worked fine. So it seems something strange is up when using the generic overload to specify a different type for the primary key.

Unless I missed something... ? 

Here is the commit for the change: 
https://github.com/jerriep/SlackMap/commit/130b535ebc3a330cc77c695aeb469bcd0cd4836d

The majority of that was the migrations which were re-generated. In essence it was just changing from using the generic version to the non-generic version

**Comment by kevinchalet** [comment]
Calling `options.UseOpenIddict<int>()` is not enough as it only configures Entity Framwork Core to use the OpenIddict models. You must also replace `services.AddOpenIddict()` by `services.AddOpenIddict<int>()` so that the managers/stores are registered with the correct models.

**Comment by jerriep** [comment]
Aah ok. Thought it was probably something I missed.

I am happy using `string` for the PK though, so I'll carry on with it as-is. Got a basic OpenIddict working with Slack, so pretty happy about that 😎

**Comment by kevinchalet** [comment]
Congrats :clap:

**Comment by jerriep** [comment]
It's your samples that are very useful 😀
