### ISSUE TITLE
Refresh flow in Authorization Code

### ISSUE THREAD

**Issue by ferry-j-ispnext** [openiddict/openiddict-core#527]
Hi,

There is no documentation for the refresh flow. I want to obtain a refresh token after logging in. This login process can be local or with Facebook/Google account. So I want to use the Authorization code flow for this to handle.

But how to get a refresh token after logging in?
Can't find any specific information...

**Comment by kinosang** [comment]
see [OpenID Connect spec](http://openid.net/specs/openid-connect-core-1_0.html), add `offline_access` into scopes.

**Comment by ferry-j-ispnext** [comment]
Got it working,

1.  Open Login screen via authorization code: (http://my-app.net/connect/authorize?client_id={clientid}&response_type=code&redirect_uri={myredirect}&scope=openid profile roles email **offline_access**
2. catch the code which is coming back in the redirect URL
3. POST connect/token (post in x-www-form-urlencoded):
	- “grant_type" = "authorization_code"
	- "code" = "{code received in step 2}"
	- "redirect_uri" = "{myredirect}"
	- "client_id" = “{clientid}”
	- "client_secret" = ""
4. catch the refresh_token from step 3 in the redirect_uri
5. POST connect/token (post in x-www-form-urlencoded):
	- “client_id” = “{clientid}”
	- “grant_type = “refresh_token”
	- “scope” = “openid profile”
	- “refresh_token” = “{refresh token (obtained in step 4)}”

**Comment by xperiandri** [comment]
It's better not to do this yourself. Do you know how to check token signature or hash?
