### ISSUE TITLE
Consider throwing an exception when SignIn is called with an unauthenticated identity

### ISSUE THREAD

**Issue by jerriep** [openiddict/openiddict-core#528]
I am getting a 403 forbidden when passing an OpenIddict issued access token to an end point which I have configured to use the Bearer authentication scheme.

My OpenIddict config is as follows:

```
services.AddOpenIddict(options =>
{
    options.AddEntityFrameworkCoreStores<SlackMapDbContext>();
    options.AddMvcBinders();
    options.EnableAuthorizationEndpoint("/connect/authorize")
        .EnableLogoutEndpoint("/connect/logout")
        //.EnableIntrospectionEndpoint("/connect/introspect")
        .EnableUserinfoEndpoint("/api/userinfo");
    options.AllowImplicitFlow();
    options.DisableHttpsRequirement();
    options.AddEphemeralSigningKey();
});
```

And configured OAuth validation:

```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie()
    .AddOAuth("Slack", o =>
    {
       //...
    })
    .AddOAuthValidation();
```

The endpoint in question is configured as follows:

```
[Authorize(AuthenticationSchemes = OAuthValidationDefaults.AuthenticationScheme)]
[HttpGet("~/connect/claims")]
public IActionResult Claims()
{
    return Json(User.Claims.Select(c =>
        new
        {
            c.Type,
            c.Value
        }));
}
```

But when I call that endpoint passing the access token as a Bearer token, I get a 403 Forbidden. Here is the logs:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/connect/claims
info: AspNet.Security.OAuth.Validation.OAuthValidationHandler[8]
      AuthenticationScheme: Bearer was successfully authenticated.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: 2.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ForbidResult[1]
      Executing ForbidResult with authentication schemes (Bearer).
info: AspNet.Security.OAuth.Validation.OAuthValidationHandler[13]
      AuthenticationScheme: Bearer was forbidden.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action SlackMap.Controllers.AuthorizationController.Claims (SlackMap) in 30.2106ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 33.8362ms 403
```

Any way for me to track this down? I cannot seem to get proper information in the logs as to why it is failing.... :(

Full source is over at https://github.com/jerriep/SlackMap/tree/master/api

**Comment by kevinchalet** [comment]
Getting a 403 means your authorization policy didn't pass, which is confirmed by the logs:

> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: 2.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.

Unfortunately, this is absolutely not something managed by OpenIddict nor by the aspnet-contrib validation handler so we have no control over what's logged.

> Actually, I wish the authorization stack logged more data by default. It should at least log the requirements that were not satisfied, and ideally why there were not satisfied (e.g the claims requirement could log both the expected value and the actual value while the roles requirement could mention the missing role).

https://github.com/aspnet/Security/issues/1259#issuecomment-335684015

**Comment by kevinchalet** [comment]
Actually, the problem is right here: https://github.com/jerriep/SlackMap/blob/master/api/Controllers/AuthorizationController.cs#L111

You must choose the overload that takes an `authenticationType` string parameter (you can use a dummy value if you want). If you don't, `ClaimsIdentity.AuthenticationType` is null and since `ClaimsIdentity.IsAuthenticated` is a simple null or empty check made on `ClaimsIdentity.AuthenticationType`, the identity will be considered as "non-authenticated".

It's dumb, but it's part of the BCL so we have no control over that either... :cry:

**Comment by jerriep** [comment]
> Unfortunately, this is absolutely not something managed by OpenIddict nor by the aspnet-contrib validation handler so we have no control over what's logged.

Yes this part was confusing to me because on the one hand the logs showed that the OAuth validation handler successfully authenticated the user but on the other hand I still got the Forbidden result. 

There are so many moving parts that it is difficult to know where to look for the problem :(

Your solution for passing an `authenticationType` to `ClaimsIdentity` worked though. Now I am back in business!

Thanks for the quick help

**Comment by kevinchalet** [comment]
> There are so many moving parts that it is difficult to know where to look for the problem :(

Please post a message here to say you'd like more logs for the authorization stack: https://github.com/aspnet/Security/issues/1259.

One thing we could do in OpenIddict is throw an `InvalidOperationException` when you call `SignIn` with a `ClaimsPrincipal` that contains an identity with a null authentication type. It would make this BCL requirement easier to discover.
