### ISSUE TITLE
How is the token validated on a resource server?

### ISSUE THREAD

**Issue by Biarity** [openiddict/openiddict-core#529]
Correct me if I'm wrong, but from what I understand [from this code](https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/ResourceServer01/Startup.cs), resource servers are supposed to validate the tokens by calling the authorization server's introspection endpoint? 

Isn't that ineffective? Making a call to the authorization server each time a user makes a request seems excessive. Is there a way to, for example, specify an RSA key container and use that instead?

**Comment by kinosang** [comment]
If you're not using the reference token, you can validate tokens on RP "offline". Use the OAuth validator or JWT validator.

Or if you've enabled the reference token, you can use `AspNet.Security.OAuth.Introspection` for that.

**Comment by Biarity** [comment]
I'm using self-contained JWT tokens (`OpenIddictTokens` table will always be empty).

I think I missed the "JWT validator", never heard of that before! Mind pointing me to relevant documentation?

**Comment by kinosang** [comment]
some resources helpful:

http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-registering-the-middleware-in-the-asp-net-core-pipeline/

https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/ResourceServer01/Startup.cs#L30-L51
