### ISSUE TITLE
Why not nuget ?

### ISSUE THREAD

**Issue by erikrenaud** [openiddict/openiddict-core#536]
Hi all ! 
I was just wondering why this project was on myget instead of nugget.org ? 

is it just not done yet or maybe not a goal of the project ?

**Comment by kevinchalet** [comment]
Hey,

Actually, it's already on NuGet.org: https://www.nuget.org/profiles/openiddict
Our README should be definitely updated to reflect that. Want to send a PR? :smile:

**Comment by erikrenaud** [comment]
Great, just added the PR #537 . Might have another as I look to add cosmosdb support.
