### ISSUE TITLE
How to hash client secret to insert into database manually?

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#540]
Maybe create a dotGet package?
https://medium.com/@tonerdo/introducing-dotget-an-installer-for-net-core-cli-apps-9ba79ac7cd89

**Comment by kinosang** [comment]
I do that with a simple console project with only one line codes:

```csharp
Console.WriteLine(CryptoHelper.Crypto.HashPassword("a password"));
```

or you can use a random string generator such as `RNGCryptoServiceProvider` with Base64 encoding to get a random key.

**Comment by kevinchalet** [comment]
> or you can use a random string generator such as RNGCryptoServiceProvider with Base64 encoding to get a random key.

It's possible, but you'll have to override the default application managers (`Crypto.HashPassword` uses a special format that embeds a version, the hash and the salt in the same payload)

**Comment by kinosang** [comment]
@PinpointTownes

my mistake, I mean use `RNGCryptoServiceProvider` to generate random string, then use `Crypto.HashPassword` for hashing.

**Comment by xperiandri** [comment]
I post [dotnet global commands tutorial](https://github.com/dotnet/core/blob/master/samples/dotnetsay/README.md) here in order someone (maybe me or my student) will create such a command.
