### ISSUE TITLE
What is a hybrid application

### ISSUE THREAD

**Issue by erikrenaud** [openiddict/openiddict-core#543]
What is a hybrid application  ?

I can't seem to find what it does by reading the code...

From my understanding:
confidential apps : apps with a client secret that MUST be provided and flows fail if they don't require a client secret (i.e. implicit flow). What about AuthorizationCode flow with pkce that doesn't require a client secret - how are those defined ?
public apps  apps without a client secret and flows fail if they require de client secret. Is this where AuthorizationCode flow without client secret fits in ?

hybrid : ???

Thanks  !

**Comment by kevinchalet** [comment]
https://github.com/openiddict/openiddict-core/issues/475 should put you on the right track.

**Comment by erikrenaud** [comment]
Great - i think i understand a bit more - i`ve ready in other issues or commits that the authorizationCode flow is supported without secrets and pkce.

Is that in the a confidential, hybrid or public app ?

**Comment by kevinchalet** [comment]
> Is that in the a confidential, hybrid or public app ?

Public. Hybrid apps can use the code flow, but they must use their client secret to communicate with the token endpoint.

**Comment by erikrenaud** [comment]
Thanks so much for the quick answers, this is a great project but making the right config choices is not always clear...

**Comment by kevinchalet** [comment]
Thanks for the kind words.

> Making the right config choices is not always clear...

I agree. That's why putting effort into the documentation is essential.

There's an ticket for the client type docs: https://github.com/openiddict/openiddict-documentation/issues/7. Would you be interested in contributing?

**Comment by erikrenaud** [comment]
Yeah, i`ll try to produce something by the mvp summit.
