### ISSUE TITLE
Can we use EF6 instead of EF7?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#55]
I have an existing database that uses EF6.1 and i would like to use that is possible.  I cannot update my existing database to EF7, because you cant define complex properties yet.

I just wonder if this is possible and what i would have to implement to do this.

**Comment by kevinchalet** [comment]
Yes, it's possible. You'll have to create your own implementation of the [`IOpenIddictStore` interface](https://github.com/openiddict/core/blob/dev/src/OpenIddict.Core/IOpenIddictStore.cs#L6) and register it in your DI container:

``` csharp
services.AddScoped<IOpenIddictStore<ApplicationUser, Application>, YourImplementation>();
```

**Comment by Gillardo** [comment]
It doesnt seem to be possible... Unless i am missing something.  I have implemented my own service implementing `IOpenIddictStore`, but my website now cannot reference `UserManager` or `UserStore` because these exist in both library as seen in this message.

Also the IOpenIddictStore implements the interface Microsoft.AspNet.Identity.IUserStore which is in Identity 3.

![image](https://cloud.githubusercontent.com/assets/7406381/12645494/4bfa8ce0-c5c2-11e5-95ae-4138d90f1ea3.png)

**Comment by kevinchalet** [comment]
Of course, you can't reference both Identity 2 and Identity 3. You need to provide your own implementation, you can't reuse the Identity 2 EF package.
