### ISSUE TITLE
unable to create oauth applications

### ISSUE THREAD

**Issue by adnan-kamili** [openiddict/openiddict-core#557]
After updating to the latest version, the application creation code started crashing with following error:

`Unexpected character encountered while parsing value: h. Path ''`

Following is my code:
```
            OAuthApplication oauthApplication = mapper.Map<OAuthApplication>(viewModel);
            oauthApplication.User = user;
            oauthApplication.TenantId = user.TenantId;
            oauthApplication.CreatedAt = DateTime.UtcNow;
            oauthApplication.ModifiedAt = DateTime.UtcNow;
            oauthApplication.ClientId = Guid.NewGuid().ToString("N");
            string clientSecret = Guid.NewGuid().ToString("N");
            await _applicationManager.CreateAsync(oauthApplication, clientSecret, cancellationToken);
```

**Comment by kinosang** [comment]
The latest version add a new field named `Permissions`, it should be a JSON-encoded array of the permissions <del>and cannot set to Null or empty string at this time</del>.

You can have a look at the sample.

https://github.com/openiddict/openiddict-core/blob/f503fb7e7a10a8dd86b27111515dda813cdc939c/samples/Mvc.Server/Startup.cs#L147-L162

**Comment by kevinchalet** [comment]
@adnan-kamili don't miss the migration guide: https://openiddict.github.io/openiddict-documentation/guide/migration.html

Also, consider using the `CreateAsync()` overload that accepts an `OpenIddictApplicationDescriptor` instance. It will take care of encoding all the properties.

@kinosang actually, the field can be null or empty (we assimilate that to empty permissions), but if you manually populate `OpenIddictApplication.RedirectUris`, `OpenIddictApplication.Permissions` or `OpenIddictApplication.PostLogoutRedirectUris`, you must JSON-encode them properly.

It's also worth noting that permissions are completely optional in the latest RC2 bits: https://openiddict.github.io/openiddict-documentation/features/application-permissions.html

**Comment by kinosang** [comment]
@PinpointTownes got it.

**Comment by adnan-kamili** [comment]
Thanks for the clarification.  My OAuthApplication contains more properties than available in the descriptor. I will have to extend the descriptor class too.

I tried folllowing but got the same error:

```
            OAuthApplication oauthApplication = mapper.Map<OAuthApplication>(viewModel);
            oauthApplication.User = user;
            oauthApplication.TenantId = user.TenantId;
            oauthApplication.CreatedAt = DateTime.UtcNow;
            oauthApplication.ModifiedAt = DateTime.UtcNow;
            oauthApplication.ClientId = Guid.NewGuid().ToString("N");
            oauthApplication.Permissions = JsonConvert.SerializeObject(new List<string>()
            {
                OpenIddictConstants.Permissions.Endpoints.Authorization,
                OpenIddictConstants.Permissions.Endpoints.Token,
                OpenIddictConstants.Permissions.GrantTypes.AuthorizationCode,
                OpenIddictConstants.Permissions.GrantTypes.RefreshToken
            });
```

**Comment by kevinchalet** [comment]
> I tried folllowing but got the same error:

Does your mapper JSON-encode the `RedirectUris`/`PostLogoutRedirectUris` properties?

**Comment by adnan-kamili** [comment]
Thanks it worked, but now I am having issues deleting the application. 

`            await _applicationManager.DeleteAsync(oauthApplication);
`
I am getting following error:

```
[10:09:55 ERR] Method 'Boolean Equals(Int32)' declared on type 'System.IEquatable`1[System.Int32]' cannot be called with instance of type 'System.Nullable`1[System.Int32]' 
Feb 17 15:39:55:  System.ArgumentException: Method 'Boolean Equals(Int32)' declared on type 'System.IEquatable`1[System.Int32]' cannot be called with instance of type 'System.Nullable`1[System.Int32]' 
```
@PinpointTownes The schema changes quite often, I believe atleast once every few months. I wonder why schema isn't get finalized yet.

**Comment by kevinchalet** [comment]
> I am getting following error:

It's an EF Core 1.x and 2.x bug (already hit in a different place). I'll try to fix it and re-push new RC2 packages with the fix.

> @PinpointTownes The schema changes quite often, I believe atleast once every few months. I wonder why schema isn't get finalized yet.

Adding new features generally requires adding new columns so it's pretty much unavoidable. 

That said, authorizations and scopes - that were WIP in RC1 - are now finalized so I don't think we'll have new schema changes in the next version.

It's also worth noting we now have a non-breaking option for storing data: JSON properties (e.g `OpenIddictApplication.Properties`). It's the new approach the OrchardCore OpenID module (based on OpenIddict) uses to store Orchard-specific data without requiring new columns.

Post-RTM, we'll use this JSON bag to store additional data if we need to.

**Comment by kevinchalet** [comment]
@adnan-kamili fix pushed. New `1.0.0-rc2-final` and `2.0.0-rc2-final` packages are available on the MyGet feed (if you've already downloaded these versions, remove the `OpenIddict` folders from `C:\Users\[your username]\.nuget\packages`).

The fix will be part of the packages published to NuGet.org next week.

**Comment by adnan-kamili** [comment]
@PinpointTownes 

Hi in the rc3 the code fails to compile. I managed to update but got stuck in two places:

```
services.AddOpenIddict<OAuthApplication, OAuthAuthorization, OAuthScope, OAuthToken>(options =>
            {
```
does not compile. Tried following but no luck:

```
 services.AddOpenIddict()
            // Register the OpenIddict core services.
            .AddCore<OAuthApplication, OAuthAuthorization, OAuthScope, OAuthToken>(options =>
            {
                // Register the Entity Framework stores and models.
                options.UseEntityFrameworkCore()
                    .UseDbContext<ApplicationDbContext>();
            })
```

Also `OpenIddictConstants` is no more recognized.

**Comment by kevinchalet** [comment]
Hey.

The next syntax is demonstrated here: https://kevinchalet.com/2018/06/20/openiddict-rc3-is-out/

**Comment by kevinchalet** [comment]
> Also OpenIddictConstants is no more recognized.

It's in `OpenIddict.Abstractions` now.
