### ISSUE TITLE
Solution won't build

### ISSUE THREAD

**Issue by barriestewart** [openiddict/openiddict-core#56]
I'm not sure if anyone else is having the same issue but the solution doesn't build for me. I've run `dnvm upgrade -u` and `dnvm list` is showing me as running `1.0.0-rc2-16357 clr x86 win` with that being the default alias.

When I try to build the solution I get a lot of errors which may be due to breaking changes in the RC2 nightlies. I was just wondering if anyone else was experiencing the same issue? One example of compilation error is this:

```
options.FileProvider = new CompositeFileProvider(
    options.FileProvider,
    new EmbeddedFileProvider(
        assembly: typeof(OpenIddictController<,>).GetTypeInfo().Assembly,
        baseNamespace: typeof(OpenIddictController<,>).Namespace));
```

That no longer works and has to be changed to this:

```
options.FileProviders.Add(new EmbeddedFileProvider(
    assembly: typeof (OpenIddictController<,>).GetTypeInfo().Assembly,
    baseNamespace: typeof (OpenIddictController<,>).Namespace));
```

**Comment by kevinchalet** [comment]
I guess you're using more recent packages than the ones we officially support (https://www.myget.org/gallery/aspnetvnext). If you've used packages from the `aspnetcidev` feed, you'll need to wipe your `.dnx\packages` folder and run `dnu restore` to download and use the right packages.

**Comment by barriestewart** [comment]
Yep - that fixed it. I ran `dnu feeds list` from the root of the `core` folder just to check if I had any global config that was overriding the project but that just returned this:

```
Feeds in use:
    https://www.myget.org/F/aspnet-contrib/api/v2
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    https://www.myget.org/F/aspnetvnext/api/v2
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    http://www.myget.org/f/aspnetwebstacknightly/
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    http://www.myget.org/F/azureadwebstacknightly/
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    https://www.myget.org/F/roslyn-nightly
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    https://www.myget.org/F/dotnet-core/
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
    https://api.nuget.org/v3/index.json
      Origin: C:\GitWorkTemp\openiddict\core\.\nuget.config
```

Just for clarity, my steps to fix this were:
1. Close all instances of VS2015
2. Ensure I was back to a clean version of your code by running `git reset --hard`
3. Delete the contents of `%UserProfile%\.dnx\packages`
4. Run `dnu restore` from the root of the project
5. Opened VS2015, ran a build and there were no errors
6. I had to delete my ReSharper cache as that was still highlighting the previous errors
