### ISSUE TITLE
Update SetApplicationIdAsync()/SetAuthorizationIdAsync() to be compatible with QueryTrackingBehavior.NoTracking

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#565]
When query tracking is disabled, Entity Framework (Core) cannot detect that the application/authorization we bind to an authorization or a token already exists and thus tries to re-insert it, resulting in a duplicate element exception:

```text
An unhandled exception occurred while processing the request.
SqlException: Violation of PRIMARY KEY constraint 'PK_OpenIddictApplications'. Cannot insert duplicate key in object 'dbo.OpenIddictApplications'. The duplicate key value is (83280f64-a53c-4e62-a3b1-e3a9f34c1a70).
The statement has been terminated.
```

While disabling query tracking in non-readonly scenarios is definitely not recommended, we could improve that by explicitly telling EF the associated entity should be ignored.

Existing method:

```csharp
var application = await Applications.FindAsync(cancellationToken, ConvertIdentifierFromString(identifier));
if (application == null)
{
    throw new InvalidOperationException("The application associated with the authorization cannot be found.");
}

authorization.Application = application;
```

Suggested fix:

```csharp
var application = await Applications.FindAsync(cancellationToken, ConvertIdentifierFromString(identifier));
if (application == null)
{
    throw new InvalidOperationException("The application associated with the authorization cannot be found.");
}

// If the application is not tracked (e.g because query/change tracking was disabled),
// attach it and mark it as unchanged to prevent the change tracker from treating it
// as a new entity, which may otherwise result in a "duplicate key" SQL exception.
var entry = Context.Entry(application);
if (entry.State == EntityState.Detached)
{
    entry.State = EntityState.Unchanged;
}

authorization.Application = application;
```

**Comment by Smartware** [comment]
If I reference 2.0.0-rc3 can I revert back to EF DBContext set to QueryTrackingBehavior.NoTracking?

**Comment by kevinchalet** [comment]
> If I reference 2.0.0-rc3 can I revert back to EF DBContext set to QueryTrackingBehavior.NoTracking?

Once such support is added in the RC3 nightly builds, yes.

**Comment by kevinchalet** [comment]
For the record: I've tried dozens of combinations to make the `QueryTrackingBehavior.NoTracking` mode "kinda work" for write scenarios (for which the EF Core team strongly discourages using it): it's pointless.

The best approach to ensure OpenIddict doesn't choke when this mode is enabled is to ensure all the OpenIddict entities are always tracked by EF Core's tracker, in every circumstance. This is what the PR https://github.com/openiddict/openiddict-core/pull/575 will do.

@Smartware I'll let you know when a RC3 nightly build including the change is available.

**Comment by kevinchalet** [comment]
Updated packages are on the MyGet.org feed. Lemme know when you have a chance to try them.
