### ISSUE TITLE
Unable to specify Claims Issuer

### ISSUE THREAD

**Issue by levia7han** [openiddict/openiddict-core#571]
When settings options I have tried to override the claims issuer but it seems as if the setting is being ignored. 
```
services.AddOpenIddict(options =>
{
    options.AddEntityFrameworkCoreStores<ApplicationDbContext>();
    options.AddMvcBinders();
    options.EnableTokenEndpoint("/connect/token");
    options.AllowPasswordFlow().AllowRefreshTokenFlow();
    options.DisableHttpsRequirement();
    options.UseJsonWebTokens();

    options.AddSigningKey(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Tokens:Key"])));
     options.Configure(config =>
      {
           config.ClaimsIssuer = "MyApp";
      });
 });
```

Yet I still get an error when the token is being validated that the issuer is incorrect. 

the .well-known/openid-configuration is also still showing
```
{"issuer":"http://localhost:28674/","token_endpoint":"http://localhost:28674/connect/token","jwks_uri":"http://localhost:28674/.well-known/jwks","grant_types_supported":["password","refresh_token"],"scopes_supported":["openid","offline_access"],"id_token_signing_alg_values_supported":["RS256"],"subject_types_supported":["public"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"claims_supported":["aud","exp","iat","iss","sub"],"claims_parameter_supported":false,"request_parameter_supported":false,"request_uri_parameter_supported":false}
```
Not sure what I am doing wrong here.

**Comment by kevinchalet** [comment]
`ClaimsIssuer` is a generic ASP.NET Core property we don't use. If you want to use a static issuer instead of the default mechanism (that computes it using the Host header), use `options.SetIssuer(...)`.

**Comment by levia7han** [comment]
That worked, sorta. I guess maybe I am misunderstanding how this whole thing should be working. 

I have an angular 4 front end trying to connect to the web api back end with jwt tokens.
The web api is located at localhost:28674 but the angular program runs at localhost:4200. 
In the past I have always just set the issuer as 'myappname'. Maybe this was wrong, but it had worked. 

I am only able to use a URI for the `options.SetIssuer()`
I end up with an error that looks like this when authenticating. 
 ```
{OriginalFormat}: Failed to validate the token {Token}.
Application version: 1.0.0.0
AspNetCoreEnvironment: Development
CategoryName: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Client IP address: 127.0.0.1
DeveloperMode: true
Event time: 3/13/2018 6:16:57 PM
Exception: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'http://localhost:4200/'. Did not match: validationParameters.ValidIssuer: 'MyAppName' or validationParameters.ValidIssuers: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateIssuer(String issuer, JwtSecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
Exception type: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException
Message: Failed to validate the token ...
Node name: ...
Operation ID: 9a447f5f-4ef2215d04dad1b8
Operation name: GET ...
Operation parent ID: |9a447f5f-4ef2215d04dad1b8.
Problem ID: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException at 
Role instance: ...
SDK version: aspnet5c:2.1.1
Severity level: Information
Token: ...
 ```
How would you recommend I set this up so that it works?

**Comment by kevinchalet** [comment]
Generally, the `iss` of a JWT token corresponds to the address of the authorization server that issued it (and when the JWT is an identity token, it's even mandatory).

Why not configuring your JWT handler to use `http://localhost:28674/` as the issuer?

**Comment by levia7han** [comment]
First off, Thanks for helping me so quickly. I appreciate it greatly. 

I guess the reason why I am trying not to change the iss in the handler is due to having this run on different servers, across load balancers, and in docker containers. 
Although it seems my way might not be up to standards, it was easier to just put one issuer across the board and not have to deal with trying to set the issuer per instance. Which I felt could cause needless confusion or problems on the ops guys (and me) when they are trying to deploy this. 

I did get it to work by changing the jwt validation parameters to have an issuer of `http://localhost:4200` which is what it was getting from the issued jwt. 
_(though I would think that the issuer on the token should be `http://localhost:28674` as 4200 is the angular address)_
But that only fixes my problem in the short term. 

In the end it just seems to be some confusion on my end, but I think I am starting to see how this works now. I just need to get it working for this scenario.

**Comment by kevinchalet** [comment]
> First off, Thanks for helping me so quickly. I appreciate it greatly.

In most cases, the issuer is a public address (e.g `http://connect.mysuperwebsite.com/`), not an internal address. Whether your site is hosted in a web farm on different servers has generally no impact on how your OpenID Connect clients connect to your server (since they use the public address).

**Comment by levia7han** [comment]
I feel kinda stupid. It all just clicked. Everything is working as it should now. Thank you for your time.
