### ISSUE TITLE
ConnectionString support at configuration time

### ISSUE THREAD

**Issue by a-patel** [openiddict/openiddict-core#572]
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
    {
        options.UseSqlServer(configuration["Data:DefaultConnection:ConnectionString"]);
        //options.UseOpenIddict(); // alternative of this dependancy
    });

     services.AddOpenIddict(options =>
    {
        // Register the Entity Framework stores.
        options.AddEntityFrameworkCoreStores(configuration["Data:DefaultConnection:ConnectionString"]);
    });
}
```

**Comment by a-patel** [comment]
In some cases,
DbContext is not directly used, and used IDbContext instead.

in such cases, we can use 'ConnectionString'

Note: not Asp.Net Identity used.
I am limited to used Connection String only

**Comment by a-patel** [comment]
It may already support this feature, but did not found the solution.

Thanks in Advance.

**Comment by kevinchalet** [comment]
I don't understand the question, sorry. Care to post more details? :sweat_smile:

**Comment by a-patel** [comment]
Is it possible to configure 'OpenIddict' by  passing connection string (without EF Database Context)  only at application startup?

**Comment by kevinchalet** [comment]
The connection string is configured in the EF context options, not in the OpenIddict options. So no (and honestly, it doesn't make much sense).

**Comment by a-patel** [comment]
`
public void ConfigureServices(IServiceCollection services)
{
    services.AddOpenIddict(options =>
    {
        // Register the Entity Framework stores usnig connection string???
        options.AddEntityFrameworkCoreStores(configuration["Data:DefaultConnection:ConnectionString"]);
    });
}
`
I want something like this...

**Comment by kevinchalet** [comment]
That's not how it works.
