### ISSUE TITLE
Implementing custom store 

### ISSUE THREAD

**Issue by luboid** [openiddict/openiddict-core#574]
Hello,
I'am trying to implement custom store without Entity Framework, but there exists methods like: 
```c#
IOpenIddictScopeStore<TScope>:

public override Task<long> CountAsync<TResult>([NotNull] Func<IQueryable<TScope>, IQueryable<TResult>> query, CancellationToken cancellationToken)

```
if this method is mandatory, if yes - how query parameter can be converted to plain SQL.

**Comment by kevinchalet** [comment]
Hey,

> if this method is mandatory, if yes

Implementing it with real logic is only required if you use the `OpenIddictScopeManager.CountAsync([query])` API (which is primarily offered as a helper for paging in admin UIs and is not internally used by OpenIddict). If you can't implement it, simply make it return an exception:

```csharp
public override Task<long> CountAsync<TResult>(
    [NotNull] Func<IQueryable<TScope>, IQueryable<TResult>> query, CancellationToken cancellationToken)
    => throw new NotSupportedException();
```

The two other methods that use this pattern are `GetAsync([query])` and `ListAsync([query])`. They are used by the default base stores as a way to simplify stores that support LINQ (so they don't have to implement all the `Find*Async` methods).

If your stores don't support LINQ, make `GetAsync([query])` and `ListAsync([query])` return a `NotSupportedException` and override all the `Find*Async()` methods to use manual queries.

**Comment by kevinchalet** [comment]
If you want a real world example, you can take a look at the OrchardCore OpenID stores: they are based on SQL, use their own entities and don't inherit from our abstract classes: https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.OpenId/YesSql/Services

**Comment by luboid** [comment]
Thanks

**Comment by zeus82** [comment]
I'm looking to create my own custom store, but that link isn't working.  Is there another more recent example?
