### ISSUE TITLE
Request Claims using Scope Values

### ISSUE THREAD

**Issue by ISTAnsver** [openiddict/openiddict-core#581]
Hi, how I can realize [this](http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) using OpenIddict? I try set scopes to tickets, but it doesn't work.

My code when I'm creating ticket is

```C#
ticket.SetScopes(new[]
{
    OpenIdConnectConstants.Scopes.Profile
    OpenIdConnectConstants.Scopes.Email
    OpenIdConnectConstants.Scopes.OfflineAccess
}.Intersect(request.GetScopes()));

```

OfflineAccess works fine.

Through postman I send request with next scope parameters `profile email offline_access`. When I put gotten JWT to debugger [jwt.io](https://jwt.io/) I get next data

```JSON
{
  "sub": "0d566f63-d990-4be8-9573-71341daaee81",
  "token_usage": "access_token",
  "jti": "d0d8627c-74e5-4cc0-8792-0f8a25835b3d",
  "scope": [
    "profile",
    "email",
    "offline_access"
  ],
  "nbf": 1522219977,
  "exp": 1522220877,
  "iat": 1522219977,
  "iss": "http://localhost:63653/"
}
```

I see email and profile in scope, but don't see claims `email` for email address, `name, family_name, given_name` and other claims.
What preconditions I must perform? How I can get this claims?

**Comment by kevinchalet** [comment]
> I see email and profile in scope, but don't see claims email for email address, name, family_name, given_name and other claims.
What preconditions I must perform? How I can get this claims?

You must add them to the ticket principal (Identity will only add the username and the role claims). E.g:

```csharp
var principal = await _signInManager.CreateUserPrincipalAsync(user);
var ticket = new AuthenticationTicket(principal, properties,
    OpenIdConnectServerDefaults.AuthenticationScheme);
var identity = (ClaimsIdentity) principal.Identity;

if (ticket.HasScope(OpenIdConnectConstants.Scopes.Profile))
{
    var name = new Claim(OpenIdConnectConstants.Claims.GivenName, "Bob");
    name.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken);

    identity.AddClaim(name);
}
```

If you don't use ASP.NET Core Identity, you can take a look at these files for actual examples that show how to create arbitrary identities:
  - https://github.com/openiddict/openiddict-compliance/blob/dev/src/OpenIddict.Compliance/Controllers/AuthenticationController.cs
  - https://github.com/openiddict/openiddict-compliance/blob/dev/src/OpenIddict.Compliance/Controllers/AuthorizationController.cs
