### ISSUE TITLE
How to add route param to token endpoint

### ISSUE THREAD

**Issue by adnan-kamili** [openiddict/openiddict-core#582]
I have a multi-tenant app, so need to add account slug to the url:

.EnableTokenEndpoint("/connect/{slug}/token");

It didn't work. Is this supported?

**Comment by kevinchalet** [comment]
> Is this supported?

No, it's not (just like in all the middleware developed by Microsoft, that don't support "parameters" in their `PathString` options).

For scenarios that require rock-solid multi-tenancy, I recommend going with OrchardCore, which has an OpenID module (based on OpenIddict). It's still quite young, but it's constantly updated.

**Comment by adnan-kamili** [comment]
@PinpointTownes I don't think we can shift now, is there any other option.

Like sending it as a query param, but the opeinddict request view model doesn't seem to support additional parameters.

This is very crucial for us, does IdentityServer4 support route params?

**Comment by kevinchalet** [comment]
Using a custom parameter is definitely possible. You can access it via `(string) request["slug"]`.

**Comment by adnan-kamili** [comment]
@PinpointTownes But wouldn't it be an addition to OpenId Connect, or is sending custom post param & query params fine. We support password credentials, client credentials, implicit flows

**Comment by kevinchalet** [comment]
Using custom parameters is allowed by the OAuth2/OIDC specifications but beware of interoperability issues if your clients don't allow specifying custom parameters.

Using a separate/isolated OpenIddict instance per tenant (with different databases/tables and separate cryptographic keys) is almost always a better option. That's what the OrchardCore OpenID module does.

**Comment by kevinchalet** [comment]
I posted more details about another option here: https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login/49682427#49682427.

**Comment by CiprianPorumbescu** [comment]
@PinpointTownes I've tried implementing your second example using JWT 

Accessing [http://localhost:2934/fabrikam/.well-known/openid-configuration](http://localhost:2934/fabrikam/.well-known/openid-configuration) works as expected but when trying to access a resource I get the following error: 

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:2934/.well-known/openid-configuration  
info: OpenIddict.OpenIddictHandler[0]
      The configuration request was successfully extracted from the HTTP request: {}.
info: OpenIddict.OpenIddictHandler[0]
      The configuration request was successfully validated.
info: OpenIddict.OpenIddictHandler[0]
      The configuration response was successfully returned: {
        "issuer": "http://localhost:2934/",
        "token_endpoint": "http://localhost:2934/connect/token",
        "jwks_uri": "http://localhost:2934/.well-known/jwks",
        "grant_types_supported": [
          "password",
          "refresh_token"
        ],
        "scopes_supported": [
          "openid",
          "offline_access"
        ],
        "id_token_signing_alg_values_supported": [
          "RS256"
        ],
        "subject_types_supported": [
          "public"
        ],
        "token_endpoint_auth_methods_supported": [
          "client_secret_basic",
          "client_secret_post"
        ],
        "claims_supported": [
          "aud",
          "exp",
          "iat",
          "iss",
          "sub"
        ],
        "claims_parameter_supported": false,
        "request_parameter_supported": false,
        "request_uri_parameter_supported": false
      }.

Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys: '[PII is hidden]', 
token: '[PII is hidden]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
```

I suspect that the error comes from the fact that [http://localhost:2934/.well-known/openid-configuration](http://localhost:2934/.well-known/openid-configuration) is called instead of [http://localhost:2934/fabrikam/.well-known/openid-configuration](http://localhost:2934/fabrikam/.well-known/openid-configuration)

And here's the code sample [https://github.com/CiprianPorumbescu/TestMultiTenantAuth](https://github.com/CiprianPorumbescu/TestMultiTenantAuth)

**Comment by kevinchalet** [comment]
Your authority/configuration metadata endpoint is wrong. If you use the ˋfabrikam` tenant, use ˋhttp://localhost:port/fabrikam` as the authority.

**Comment by CiprianPorumbescu** [comment]
I'm using the same api for a multitenant environemnt so I need to be able to do auth for both `http://localhost:port/fabrikam1` and `http://localhost:port/fabrikam2`

Can I change the authority/configuration based on the current tenant?

**Comment by kevinchalet** [comment]
The solution described in the SO answer consists in creating separate/isolated issuers. You can’t arbitrarily pick one and expect the JWT handler to also validate tokens issued by the other ones. 

You can use a similar approach and create a custom monitor for the JWT options.

**Comment by CiprianPorumbescu** [comment]
Thanks so much, it worked.

> You can’t arbitrarily pick one and expect the JWT handler to also validate tokens issued by the other ones.

I was aware of that but unfortunately I never thought to apply the same mechanism to the JWT options. It seems so obvious now

**Comment by kevinchalet** [comment]
Glad it worked :tada:

**Comment by indranilatcal** [comment]
Hi @kevinchalet 

I tried to add multi-tenancy based on option 2 suggested in https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login/49682427#49682427 (i.e. by "Override the options monitor used by OpenIddict to use per-tenant options". However, the well-known config is not available under /mytenantname/.well-known/openid-configuration. Likewise, when I try to hit it from the client, I get the error "The client registration corresponding to the specified issuer cannot be found in the client options". For reference, my code is under https://github.com/indranilatcal/MultiTenancy. Any help will be greatly appreciated.

Thanks
