### ISSUE TITLE
Method not found: 'System.Linq.IQueryable`1<!0> OpenIddict.Core.IOpenIddictApplicationStore`1.get_Applications()'.

### ISSUE THREAD

**Issue by TheBoneJarmer** [openiddict/openiddict-core#584]
Hi

I just started developing on an existing project which was made by others and I just cannot make it run. I stumble on a MethodNotFound exception:

Method not found: 'System.Linq.IQueryable`1<!0> OpenIddict.Core.IOpenIddictApplicationStore`1.get_Applications()'.'

I never worked with OpenIddict before so I have no clue what causes this error. I do asume it is not something I can repair since this is in the source of openiddict. But perhaps it is a version mismatch. I do not know. Can you guys look at this? I have version 2.0.0-rc1-0669 installed.

**Comment by kevinchalet** [comment]
Hey,

> But perhaps it is a version mismatch.

Most likely, yes. The method mentioned in the exception message was removed a while ago (and I'm not even sure it was part of a public/stable release). You'll have to update your existing project to use a supported version (at the time of writing, `2.0.0-rc2-final` is the latest stable version).
