### ISSUE TITLE
Expose roles to the userinfo endpoint

### ISSUE THREAD

**Issue by chrisjmccrum** [openiddict/openiddict-core#59]
Similar to the roles option for the identity_token, I propose the userinfo endpoint should give info on the roles of the user. This would eliminate the need to generate & decrypt an additional token just for user attributes.

**Comment by kevinchalet** [comment]
Actually, it's already supported: https://github.com/openiddict/core/blob/dev/src/OpenIddict.Core/OpenIddictProvider.cs#L86-L92 :smile:
