### ISSUE TITLE
JWT using custom symmetric key not validating

### ISSUE THREAD

**Issue by gecko-8** [openiddict/openiddict-core#592]
Hi there,
I'm using OpenIDDict to enable jwt tokens in my ASP.NET Core 2 api application. I'm manually setting the key using AddSigningKey. When I generate a token and try to validate it (using [https://www.jsonwebtoken.io/](url) with my custom key, it's telling me the signature is invalid. My key is a BASE64 encoded 256bit string. Here's my config:
    // Register database context
    services.AddDbContext<AdmazingContext>(opt =>
    {
        opt.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
        opt.UseOpenIddict();
    });

    // Identity Framework
    services.AddIdentity<ApplicationUser, IdentityRole>()
        .AddEntityFrameworkStores<MyContext>()
        .AddDefaultTokenProviders();

    services.Configure<IdentityOptions>(options =>
    {
        options.ClaimsIdentity.UserNameClaimType = OpenIdConnectConstants.Claims.Name;
        options.ClaimsIdentity.UserIdClaimType = OpenIdConnectConstants.Claims.Subject;
        options.ClaimsIdentity.RoleClaimType = OpenIdConnectConstants.Claims.Role;
    });

    // Register the OpenIddict services.
    services.AddOpenIddict(options =>
    {
        // Register the Entity Framework stores.
        options.AddEntityFrameworkCoreStores<MyContext>();

        // Register the ASP.NET Core MVC binder used by OpenIddict.
        // Note: if you don't call this method, you won't be able to
        // bind OpenIdConnectRequest or OpenIdConnectResponse parameters.
        options.AddMvcBinders();

        // Enable the token endpoint.
        options.EnableTokenEndpoint("/api/authorization/token");

        // Enable the password flow.
        options.AllowPasswordFlow()
            .AllowRefreshTokenFlow();

        // During development, you can disable the HTTPS requirement.
        options.DisableHttpsRequirement();

        // Note: to use JWT access tokens instead of the default
        // encrypted format, the following lines are required:
        //
        options.UseJsonWebTokens();
        var key = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["Jwt:Key"]));
        options.AddSigningKey(key);
        //options.AddEphemeralSigningKey();
    });

I also tried encoding the key as UTF-8. Am I doing this right or am I missing something?
Thanks,
Jason

**Comment by kevinchalet** [comment]
Hey,

I tried with jwt.io and it worked with an ASCII-encoded secret. I haven't been able to make the Stormpath site work so I suspect there's simply a bug there.

**Comment by gecko-8** [comment]
Ah, okay, I'll be able to test better once I have the Javascript client setup for it. Thanks for the quick response.

**Comment by kevinchalet** [comment]
If there's a bug on our side, it's not in OpenIddict itself. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet is the component responsible of serializing and signing our JWTs.
