### ISSUE TITLE
OpenIddictCoreExtensions.AddCore not available in latest OpenIddict.Core Nuget package

### ISSUE THREAD

**Issue by themidnightgospel** [openiddict/openiddict-core#597]
[Getting started](https://github.com/openiddict/openiddict-core#getting-started) section provides following code to setup OpenIdDict 

```C#
services.AddOpenIddict()
        .AddCore(options =>
        ....
```

`OpenIddictCoreExtensions.AddCore` extension method is not present in latest [OpenIddict.Core 2.0.0-rc2-final](https://www.nuget.org/packages/OpenIddict.Core/2.0.0-rc2-final) version.

`Microsoft.Extensions.DependencyInjection.OpenIddictCoreExtensions` was created 7 days ago and it's assigned to `2.0.0-rc3` version, while `2.0.0-rc2-final` version was uploaded 2 month ago on Nuget.

Either upload `2.0.0-rc3` version on Nuget or update **Getting started** section, so that it's consistent.

**For those facing same issue**

Refer to [openiddict-samples](https://github.com/openiddict/openiddict-samples) for *old-style* openiddict setup.

**Comment by kevinchalet** [comment]
RC3 is coming soon. 

For RC2, you can find the instructions here: https://github.com/openiddict/openiddict-core/blob/2.0.0-rc2/README.md

**Comment by kevinchalet** [comment]
OpenIddict RC3 is on NuGet.org.

You can read the announcement here: https://twitter.com/PinpointTownes/status/1009078430602850304.
