### ISSUE TITLE
[Question] Multiple openiddict instances

### ISSUE THREAD

**Issue by philippk80** [openiddict/openiddict-core#607]
Hello,

I have the requirement to have one openiddict instance on the local network as fallback and one in the cloud on the internet. Is there a way to achieve this? This means I need two instances that synchronize each other or not? I've read about a public key that is able to validate tokens two but isn't able to create some.
Is this the right path to search informations?

Thanks.

**Comment by kinosang** [comment]
You should configure the data protection manually to specify a key to sign, verify, encrypt and decrypt the payload of tokens, or the tokens will be invalid when your system switch from the cloud to the fallback or vice versa.

Then you can configure the locally fallback system to use the same database of the cloud one, or create a mirror or slave.

**Comment by philippk80** [comment]
Thanks for answering.

Are you talking about configuring the data protecting asp .net core? 
(Like described here: https://docs.microsoft.com/de-de/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.0&tabs=aspnetcore2x )

Are there any best practices to exchange that keys between the two instances or would you recommend to set the keys to a fixed value on both instances?

**Comment by kinosang** [comment]
@philippk80 

Yep, openiddict and the ASOS (AspNet.Security.OpenIdConnect.Server) use the ASP.NET Core Data Protection.

BTW, I chose to use a fixed key on both side, I use the Azure Key Vault, but if you does not trust it (for the SLA etc), you can create your own encrypted store (see https://andrewlock.net/creating-a-custom-iconfigurationprovider-in-asp-net-core-to-parse-yaml/).

**Comment by philippk80** [comment]
In my scenario the slave will register himself on the master at runtime. Could I implement an api to retrieve the key from the master that is only accesible with a specific claim assigned to the slave? Or would this be a bad idea for security reasons? I mean offering a key over an api sounds bad to my ears. But I would love when this replication could be automated. That would make it much more easier for the enduser when configuring the system.

**Comment by kinosang** [comment]
@philippk80  Use a famous key establishment logic maybe better if you decide to offer the key over an API, but I don't know if exist algorithm are compatible with the Data Protection feature.

I've done some search for you, see https://en.wikipedia.org/wiki/Key_exchange and https://crypto.stackexchange.com/questions/5069/is-there-a-symmetric-key-cryptography-based-on-key-establishment-techniques.

If you already has pre-shared keys (include asymmetric keys), there's no reason to establishment a new one, I think a pre-shared key is fine enough.

**Comment by philippk80** [comment]
Again thanks for the amount of information!

So as conclusion I thought about following:

Administrator starts setup on slave with a login to the master.
So the slave has the accesstoken and is able to create a "system-user" for the slave.
With this the slave is able to retrieve a refresh token to get access tokens for auth everytime with it's own account.
With the "system-user" registering process a claim will be added to give access to the data protection configuration.
Once this is retrieved the claim will be removed. I think this won't be a problem on security side. The only way to get the keys I would see is getting login data from a user with administrator rights... but then he could do everything directly without getting the keys.
Maybe there should be a warning in the administrator user interface when this process is used so the administrator is able to react with allowing the users to change their passwords and exchange the keys.

So for now the only thing that is unclear for me is the database part. In EF generally I'm able to track changes when I add triggers in the class that derives from IdentityDbContext. With this I'm able to synchronize the slave database over a secured channel. (https://github.com/NickStrupat/EntityFramework.Triggers/)
Or am I wrong with this?

**Comment by kinosang** [comment]
@philippk80 use the database-level master-slave or mirror function, or something alike

**Comment by philippk80** [comment]
Then I have to expose the database over the internet. Wouldn't that be bad? 
In my mindset is set that you try everytime to disallow direct access to databases.

**Comment by kinosang** [comment]
@philippk80 

> Then I have to expose the database over the internet.

Not at all, just use some tunnel like SSH or VPN, or config the firewall to only allow access from your site (local network).

**Comment by philippk80** [comment]
I think a SSH tunnel established by login of the login would be a good option. Thanks for helping with all that information. 👍 
I will no close this issue because we're drifting into stuff that isn't related to openiddict. 😄
