### ISSUE TITLE
Passing DbContextOptions to OpenIddictContext

### ISSUE THREAD

**Issue by barriestewart** [openiddict/openiddict-core#61]
The `OpenIddictContext` class extends `IdentityDbContext` but doesn't appear to provide any explicit constructor. It would be nice if this class provided constructors in line with the public constructors provided by `IdentityDbContext` which would, in turn, call the base `IdentityDbContext`. For example, it would be nice to be able to have a class extending `OpenIddictContext` which looks like this:

```
    public class ApplicationDbContext : OpenIddictContext<ApplicationUser, Application, ApplicationRole, string>
    {
        public ApplicationDbContext(DbContextOptions options) : base(options)
        {

        }
    }
```

At the moment that wouldn't work because `OpenIddictContext` just has a default paramaterless constructor. If the above suggestion was implementing and it would allow us to create the context manually and pass configuration options like this:

```
        var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
        optionsBuilder.UseInMemoryDatabase();
        var context = new ApplicationDbContext(optionsBuilder.Options);
```

That can be useful when running tests. At the moment I can get around this by extending `IdentityDbContext` and manually adding `public DbSet<Application> Applications { get; set; }` to my class but your recommended approach is to directly extend `OpenIddictContext`.

**Comment by kevinchalet** [comment]
Good idea, feel free to send a PR to fix that :clap:

**Comment by barriestewart** [comment]
Ok I'll take a look.

**Comment by kevinchalet** [comment]
Merged, thanks: https://github.com/openiddict/openiddict-core/commit/9ea6a517bd6c0adff3db3988a89abeff5c14db7c :clap:
