### ISSUE TITLE
OpenIdDict with MySql throws key too long on seeding db

### ISSUE THREAD

**Issue by Myrmex** [openiddict/openiddict-core#618]
Hello, I'm trying to use OpenIdDict with MySql instead of SQLServer, but this seems to throw because of the database model.

I have created a full repro sample (which also works as an example for using this library in a password flow scenario) at <https://github.com/Myrmex/oid-credentials/tree/master/OidCredentials>. This code uses MySql, but you can easily change it to reproduce this error, as follows:

1.downgrade to .NET Core 2.0 because 2.1 is known to have issues with Oracle (and Pomelo) drivers. This probably requires downgrading OpenIdDict, too.

2.in Startup.cs, method ConfigureServices, replace the SQL Server line with this:

```cs
options.UseMySQL(_configuration["Data:DefaultConnection:ConnectionString"]);
// options.UseSqlServer(_configuration["Data:DefaultConnection:ConnectionString"]);
```

3.in appsettings.json change the connection string from SQL Server to MySql: from

```json
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Server=(local)\\SqlExpress;Database=oid;Trusted_Connection=True;MultipleActiveResultSets=true;"
    }
  }
```

to (use your local MySql credentials replacing these `X`):

```json
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Server=localhost;Database=oid;Uid=X;Pwd=X;SslMode=none"
    }
  }
```

If using 2.1, this throws on startup, when initializing the database (see <https://github.com/aspnet/EntityFrameworkCore/issues/11078> and <https://bugs.mysql.com/bug.php?id=89855&thanks=sub>, but this is a MySql issue):

```
System.NotImplementedException HResult=0x80004001 Message=The 'MySQLNumberTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider. 
```

Downgrading to .NET Core 2.0 removes the issue, but throws another exception, which seems related to the field length of some table in the authentication model:

```
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Specified key was too long; max key length is 3072 bytes
  Source=MySql.Data
```

Did anyone try to use OpenIdDict with MySql? Is this really an issue to be fixed by changing its data models?

**Comment by kevinchalet** [comment]
> Did anyone try to use OpenIdDict with MySql?

2 of my clients have OpenIddict 2.0 RC2 instances targeting MySQL (used in production) and they both work flawlessly. They both use Pomelo, as the official driver was too buggy when they started deploying their apps.

We had an issue with timestamp fields in RC1 - used as concurrency checks - but they were replaced by simpler strings in RC2: https://github.com/openiddict/openiddict-core/issues/497.

**Comment by kevinchalet** [comment]
I've tried with the OI MVC sample and with your app and I haven't been able to reproduce your issue with Pomelo.EntityFrameworkCore.MySql 2.0.1.

**Comment by Myrmex** [comment]
What a quick reply! So I'll have to switch to Pomelo, hoping that this does not break anything else :). Thanks!
