### ISSUE TITLE
Enabling scope validation and anonymous clients rejection by default in OpenIddict RC3

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#621]
Starting with RC3, OpenIddict will now enforce scope validation and reject token and revocation requests that don't specify a `client_id`.
In RC2, these checks were opt-in (enabled via `options.EnableScopeValidation()` and `options.RequireClientIdentification()`) ; in RC3, they are now opt-out.

# How do I react to this change?

If, after migrating to RC3, you see errors similar to these ones:

> invalid_scope - The specified 'scope' parameter is not valid.

Simply add the scopes you want to use to the list of registered scopes:

```csharp
services.AddOpenIddict()

    // Register the OpenIddict server handler.
    .AddServer(options =>
    {
        options.RegisterScopes(OpenIdConnectConstants.Scopes.Email,
                               OpenIdConnectConstants.Scopes.Profile,
                               OpenIddictConstants.Scopes.Roles);
    });
```

> invalid_request - The mandatory 'client_id' parameter is missing.

Add an application entry for the client application and send the corresponding `client_id` as part of the token request:

```csharp
var descriptor = new OpenIddictApplicationDescriptor
{
    ClientId = "postman",
    DisplayName = "Postman",
    Permissions =
    {
        OpenIddictConstants.Permissions.Endpoints.Token,
        OpenIddictConstants.Permissions.GrantTypes.Password,
        OpenIddictConstants.Permissions.GrantTypes.RefreshToken,
        OpenIddictConstants.Permissions.Scopes.Email,
        OpenIddictConstants.Permissions.Scopes.Profile,
        OpenIddictConstants.Permissions.Scopes.Roles
    }
};

await _applicationManager.CreateAsync(descriptor);
```

# What if I prefer disabling these validation checks?

To disable these checks, you can use `options.DisableScopeValidation()` and `options.AcceptAnonymousClients()`:

```csharp
services.AddOpenIddict()

    // Register the OpenIddict server handler.
    .AddServer(options =>
    {
        options.AcceptAnonymousClients();
        options.DisableScopeValidation();
    });
```

Note: if you already use `options.EnableScopeValidation()` and/or `options.RequireClientIdentification()` in your code, you can safely remove these calls.

**Comment by MaklaCof** [comment]
`await _applicationManager.CreateAsync(descriptor);` what is `_applicationManager` adn where should I put this code? In `startup.cs`?

**Comment by kevinchalet** [comment]
https://github.com/openiddict/openiddict-core/blob/7cf18dc1eaf4c60f0cd672a2db965084ac17cd7f/samples/Mvc.Server/Startup.cs#L177-L197
