### ISSUE TITLE
Full release

### ISSUE THREAD

**Issue by LunicLynx** [openiddict/openiddict-core#629]
Not to be picky. But why are there only pre releases?

From what i gather, you could already make a 2.0.0 release and instead of RC2,3,4 make patch releases?

Am I missing something?
Or are you suggesting to **not** use your library in production environment?

**Comment by kinosang** [comment]
Features and APIs are still not stable, I think it's why there's no release published.

**Comment by kevinchalet** [comment]
> From what i gather, you could already make a 2.0.0 release and instead of RC2,3,4 make patch releases?

OpenIddict strictly follows SemVer. If we wanted to introduce API changes in a released version, we'd have to release new major versions every time. Would having an OpenIddict `4.0.0` version be better than `2.0.0-rc3`? I don't think so.

That said, I mentioned it in my blog post: it's the last RC version: RTM is the next step.

**Comment by LunicLynx** [comment]
I see. Thanks for the info

- closed
