### ISSUE TITLE
Any way to change the default /Account/Login login path?

### ISSUE THREAD

**Issue by davidtimovski** [openiddict/openiddict-core#630]
When configuring cookie authentication it's usually done by setting the `options.Cookies.ApplicationCookie.LoginPath` property of the IdentityOptions argument. Not sure how to do it in OpenIddict though.

**Comment by kevinchalet** [comment]
This endpoint is not managed by OpenIddict, it's purely a cookie handler/Identity thing.

To change it, use `services.ConfigureApplicationCookie()`.
