### ISSUE TITLE
Application store must not require OpenIddict application to be nonabstract and has parameterless constructor

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#631]
You can apply this constraint to generic Descriptor and get the type from it.

Current implementation breaks my scenario where I want to have `WebApplication` and `ExternalApplication` classes derived from `abstract TenantApplication: OpenIddictApplication<Guid>`.
 Where WebApplicaton is used for in-house MVC app and ExternalApplication for third-party apps.

**Comment by kevinchalet** [comment]
We can't do that because of https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictApplicationStore.cs#L712-L721.

It's not clear why you have 2 separate entities for representing the application but what prevents you from making your store generic?

**Comment by xperiandri** [comment]
Do you mean register generic store without type parameter and then resolve it with type parameter?

**Comment by kevinchalet** [comment]
Yup.

**Comment by xperiandri** [comment]
Remove that method at all
Then [here](https://github.com/openiddict/openiddict-core/blob/e9c796ca37cb6970afceb4fb08b5321a783236a2/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L164) you will do 

``` C#
public virtual async Task<TDerivedApplication> CreateAsync(
    [NotNull] OpenIddictApplicationDescriptor<TDerivedApplication> descriptor, CancellationToken cancellationToken = default)
	where TDerivedApplication: new, TApplication
{
    if (descriptor == null)
    {
        throw new ArgumentNullException(nameof(descriptor));
    }

    var application = new TDerivedApplication()

...
}
```

**Comment by kevinchalet** [comment]
It's not a good option. `OpenIddictApplicationDescriptor` should be non-generic to work with the non-generic `IOpenIddictApplicationManager` interface.

I can't see why you couldn't achieve a similar result at the store level by making your custom stores generic. You can even write your own `IOpenIddictApplicationStoreResolver` if the logic used to resolve your generic store is a bit complex.

**Comment by kevinchalet** [comment]
If having a `new` constraint is really blocking, I'm not opposed to removing it and replacing it by an expression-tree-based/activator-based approach that would differ the check at runtime: it would only throw an exception if you tried to use `CreateAsync(OpenIddictApplicationDescriptor)`.

**Comment by xperiandri** [comment]
The issue is that with constraint I will never be able to get all apllications at once. Becuase non abstract entity class must have discriminator in EF Core.
And I obligated to do this

``` C#
entity.HasDiscriminator<AppOwnership>(nameof(TenantApplication.Ownership))
      .HasValue<TenantApplication>(AppOwnership.Undefined)
      .HasValue<WebApplication>(AppOwnership.Internal)
      .HasValue<ExternalApplication>(AppOwnership.External);
```

instead of

``` C#
entity.HasDiscriminator<AppOwnership>(nameof(TenantApplication.IsExternal))
      .HasValue<WebApplication>(false)
      .HasValue<ExternalApplication>(true);
```

**Comment by kevinchalet** [comment]
Are you interested in submitting a PR removing the `new()` constraints from the stores? Replacing them by `Activator.CreateInstance` should be enough (and shouldn't hurt perf' too much as we'd use default constructors).

**Comment by xperiandri** [comment]
OK, I will do that

**Comment by kevinchalet** [comment]
@xperiandri if you want that in RTM, we'll need to make the change in the next few days so we have enough time to test it.

**Comment by kevinchalet** [comment]
Note: I backported this PR to OpenIddict 1.x so you can support the same scenarios in 1.x.
