### ISSUE TITLE
After update how to use UseDefaultModels()

### ISSUE THREAD

**Issue by devpedrofranco** [openiddict/openiddict-core#635]
I have update my OpenIddict-Core from 2.0.0-rc3-0883 to 2.0.0-rtm-1034 now i'm getting the options.UseDEfaultModels() don't exists anymore.

How do i pass this option in new version ?

Thanks.

**Comment by kevinchalet** [comment]
This extension was removed and is not part of the latest release (`2.0.0-rc3-final`). For more information, you can read https://github.com/openiddict/openiddict-core/issues/608 and https://kevinchalet.com/2018/06/20/openiddict-rc3-is-out/.

**Comment by devpedrofranco** [comment]
Thanks @PinpointTownes 

Where i can see the new model? 

Cause my application use reverse migration so i have to create this on hand.

**Comment by kevinchalet** [comment]
The new models (for EF Core) are here: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.EntityFrameworkCore.Models

There's no difference between them and the models used in RC2. No schema/database change should be required.

**Comment by devpedrofranco** [comment]
After the update i'm gotting the follow error, i was think that is because the model, but u sayed that no difference, could u take a look @PinpointTownes  ? 

![image](https://user-images.githubusercontent.com/10779853/42177753-50e8b3a6-7e04-11e8-8e76-55240a21e700.png)


This is what i have changed in my Startup:

![image](https://user-images.githubusercontent.com/10779853/42220469-68461bc8-7ea5-11e8-8dd6-02c073216af7.png)

**Comment by kevinchalet** [comment]
It has nothing to do with the EF model itself. It's a functional change regarding app permissions, which is explained in the blog post I mentioned :smile:

**Comment by devpedrofranco** [comment]
The problem is ocurring by the field Permissons, In other versions I believe it was not being validated.
I just update this field and put to be generate when the OpenIddictApplications register is created.

update OpenIddictApplications
SET [Permissions] = '["ept:token","gt:client_credentials"]'
