### ISSUE TITLE
Cannot restore dependencies

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#64]
Tried restoring my dependencies today, using `dnu restore` and option via visual studio, but i seem to get this error?

I have noticed that the readme file has changed, and the nuget.config file sources have changed to include

`<add key="AspNetCiDev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />`

If i remove this, then my project cant find these dependencies, but if i include it i get the error below...?

I am using dnvm 1.0.0-rc2-16357 x64

>   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.mvc/index.json 1546ms
> Unable to locate Dependency Microsoft.AspNetCore.Authentication >= 1.0.0-rc2-16366
> Unable to locate Dependency Microsoft.Extensions.FileProviders.Embedded >= 1.0.0-rc2-16053
> Unable to locate Dependency Microsoft.AspNetCore.StaticFiles >= 1.0.0-rc2-16273
> Unable to locate Dependency Microsoft.AspNetCore.Identity >= 1.0.0-rc2-16470
> Unable to locate Dependency Microsoft.AspNetCore.Cors >= 1.0.0-rc2-16264
> Unable to locate Dependency Microsoft.Extensions.Caching.Memory >= 1.0.0-rc2-16131
> Unable to locate Dependency Microsoft.Extensions.Configuration >= 1.0.0-rc2-16090
> Unable to locate Dependency Microsoft.AspNetCore.Authentication >= 1.0.0-rc2-16397
> Unable to locate Dependency Microsoft.Extensions.Logging.Abstractions >= 1.0.0-rc2-16110
> Unable to locate Dependency Microsoft.Extensions.Caching.Abstractions >= 1.0.0-rc2-16131
> Unable to locate Dependency Microsoft.AspNetCore.Hosting.Abstractions >= 1.0.0-rc2-16343
> Unable to locate Dependency Microsoft.AspNetCore.Identity.EntityFrameworkCore >= 1.0.0-rc2-16470
> Unable to locate Dependency Microsoft.Extensions.FileProviders.Composite >= 1.0.0-rc2-16053
> Unable to locate Dependency Microsoft.AspNetCore.Hosting >= 1.0.0-rc2-16297
> Unable to locate Dependency Microsoft.AspNetCore.Mvc >= 1.0.0-rc2-17094
> Writing lock file E:\github\unite\src\m2i.Unite.Web\project.lock.json
> Restore complete, 11414ms elapsed
> 
> Errors in E:\github\unite\src\m2i.Unite.Web\project.json
>     Unable to locate Dependency Microsoft.AspNetCore.Authentication >= 1.0.0-rc2-16366
>     Unable to locate Dependency Microsoft.Extensions.FileProviders.Embedded >= 1.0.0-rc2-16053
>     Unable to locate Dependency Microsoft.AspNetCore.StaticFiles >= 1.0.0-rc2-16273
>     Unable to locate Dependency Microsoft.AspNetCore.Identity >= 1.0.0-rc2-16470
>     Unable to locate Dependency Microsoft.AspNetCore.Cors >= 1.0.0-rc2-16264
>     Unable to locate Dependency Microsoft.Extensions.Caching.Memory >= 1.0.0-rc2-16131
>     Unable to locate Dependency Microsoft.Extensions.Configuration >= 1.0.0-rc2-16090
>     Unable to locate Dependency Microsoft.AspNetCore.Authentication >= 1.0.0-rc2-16397
>     Unable to locate Dependency Microsoft.Extensions.Logging.Abstractions >= 1.0.0-rc2-16110
>     Unable to locate Dependency Microsoft.Extensions.Caching.Abstractions >= 1.0.0-rc2-16131
>     Unable to locate Dependency Microsoft.AspNetCore.Hosting.Abstractions >= 1.0.0-rc2-16343
>     Unable to locate Dependency Microsoft.AspNetCore.Identity.EntityFrameworkCore >= 1.0.0-rc2-16470
>     Unable to locate Dependency Microsoft.Extensions.FileProviders.Composite >= 1.0.0-rc2-16053
>     Unable to locate Dependency Microsoft.AspNetCore.Hosting >= 1.0.0-rc2-16297
>     Unable to locate Dependency Microsoft.AspNetCore.Mvc >= 1.0.0-rc2-17094

Please advise

> System.ArgumentException: More than one runtime.json file has declared imports for 'win7-x86'
> Parameter name: runtimeName
>    at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2
>  effectiveRuntimeSpecs, HashSet`1 allRuntimeNames, Func`2 circularImport)
>    at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2
>  effectiveRuntimeSpecs, HashSet`1 allRuntimeNames)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> ##    at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
> 
> Restore failed
> More than one runtime.json file has declared imports for 'win7-x86'
> Parameter name: runtimeName

**Comment by kevinchalet** [comment]
That's likely caused by the fact you're using an old DNX runtime.
Read http://stackoverflow.com/a/35519150/542757 for a quick migration guide.

**Comment by Gillardo** [comment]
@PinpointTownes thanks for the reply.  I am using the latest dnvm install.  I have run 

```
set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/
dnvm upgrade -u
```

But this did not upgrade anything as it said 1.0.0-rc2-16357 is the latest version (i am using x64)

I have changed the nuget.config sources, including `<clear />` at the start, but upon running `dnu restore` i still get the error

> System.ArgumentException: More than one runtime.json file has declared imports for 'win7-x86'
> Parameter name: runtimeName
>    at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2
>  effectiveRuntimeSpecs, HashSet`1 allRuntimeNames, Func`2 circularImport)
>    at Microsoft.Dnx.Tooling.RestoreCommand.FindRuntimeDependencies(String runtimeName, List`1 runtimeFiles, Dictionary`2
>  effectiveRuntimeSpecs, HashSet`1 allRuntimeNames)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
> 
> Restore failed
> More than one runtime.json file has declared imports for 'win7-x86'
> Parameter name: runtimeName
> 
> NuGet Config files used:
>     C:\Users\Darren\AppData\Roaming\NuGet\nuget.config
>     E:\github\unite\nuget.config
> 
> Feeds used:
>     https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/
>     https://api.nuget.org/v3-flatcontainer/
>     https://www.myget.org/F/aspnet-contrib/api/v3/flatcontainer/

I installed the .NET CLi and see that there is a `dotnet restore` command, so i have tried that too, but this says that 

> warn : The file 'C:\Users\Darren\AppData\Local\NuGet\v3-cache\8f4358f45e87338232123d05bea76a3f13464d9a$_F_aspnetcidev_ap
> i_v3_index.json\nupkg_System.Runtime.4.0.21-rc2-23728.dat' is corrupt.

Here is my dnvm list
![image](https://cloud.githubusercontent.com/assets/7406381/13321404/ba98146e-dbc6-11e5-97f4-7a9a70164e2f.png)

**Comment by kevinchalet** [comment]
Have you tried running `dnvm update-self` to update your DNVM?

**Comment by Gillardo** [comment]
Yep, my actual dnvm version is as so

![image](https://cloud.githubusercontent.com/assets/7406381/13321551/87ddff4c-dbc7-11e5-8007-47ff59021e80.png)

**Comment by kevinchalet** [comment]
Ahhh, you're using Powershell. Don't forget it doesn't support SET for creating environment variables. Use the appropriate syntax or use a good old console.

**Comment by Gillardo** [comment]
@PinpointTownes since your "in the know", can i ask you some questions.  This works btw, i can compile, although now my website doesnt load, says imports are recognised for some reason when i try to run it via IISExpress.  

Yet if i run `dotnet run` (which i assume is correct now?) then i get a compile error, saying my appsettings.json file isnt found.  Upon looking at it, it thinks that the applicationRoot now includes `\bin\Debug\dnx451\win7-x64\` after it, which it never had before?

I have tried `dnx web` from command line, which gives me the same imports error as IISExpress

I guess i am still supposed to be pointing projects to use framework dnx451, i cant target dnxcore5 as reference some projects that do not yet support this.

Sorry i know none of this is your problem, but since you know how to upgrade your projects to rc2 latest, i thought you may know.

Here is screen shot of imports error

![test](https://cloud.githubusercontent.com/assets/7406381/13351876/9dc804e6-dc81-11e5-94cb-4ce499c3fa49.gif)

**Comment by kevinchalet** [comment]
For the dotnet run error, no idea, sorry. You should open a ticket on the CLI repository. 

Concerning the error bug, it's a breaking in MVC: https://github.com/aspnet/Mvc/commit/80b6996701ca240b8b4b1ba8f56c7ecae3e69b60#commitcomment-16288972.

**Comment by Gillardo** [comment]
So this is why my project fails on all imports now?  And there is no fix yet?

**Comment by Gillardo** [comment]
I am guessing then this is why yrou project does not currently run, when i download the zip and try to run the Mvc.Server sample now as well??

**Comment by kevinchalet** [comment]
Yes, all the ASP.NET Core projects using MVC and running on DNX are impacted.

**Comment by Gillardo** [comment]
How can they not realise that before release?

**Comment by kevinchalet** [comment]
This is an intentional breaking change. If the ASP.NET team doesn't revert it, I'll have to push this (horrible) workaround:

``` csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using Microsoft.Extensions.PlatformAbstractions;

namespace Microsoft.AspNetCore.Mvc.Infrastructure {
    public class DnxAssemblyProvider : IAssemblyProvider {
        private readonly ILibraryManager _libraryManager;

        public DnxAssemblyProvider(ILibraryManager libraryManager) {
            _libraryManager = libraryManager;
        }

        /// <summary>
        /// Gets the set of assembly names that are used as root for discovery of
        /// MVC controllers, view components and views.
        /// </summary>
        // DefaultControllerTypeProvider uses CandidateAssemblies to determine if the base type of a POCO controller
        // lives in an assembly that references MVC. CandidateAssemblies excludes all assemblies from the
        // ReferenceAssemblies set. Consequently adding WebApiCompatShim to this set would cause the ApiController to
        // fail this test.
        protected virtual HashSet<string> ReferenceAssemblies { get; } = new HashSet<string>(StringComparer.Ordinal) {
            "Microsoft.AspNetCore.Mvc",
            "Microsoft.AspNetCore.Mvc.Abstractions",
            "Microsoft.AspNetCore.Mvc.ApiExplorer",
            "Microsoft.AspNetCore.Mvc.Core",
            "Microsoft.AspNetCore.Mvc.Cors",
            "Microsoft.AspNetCore.Mvc.DataAnnotations",
            "Microsoft.AspNetCore.Mvc.Formatters.Json",
            "Microsoft.AspNetCore.Mvc.Formatters.Xml",
            "Microsoft.AspNetCore.Mvc.Localization",
            "Microsoft.AspNetCore.Mvc.Razor",
            "Microsoft.AspNetCore.Mvc.Razor.Host",
            "Microsoft.AspNetCore.Mvc.TagHelpers",
            "Microsoft.AspNetCore.Mvc.ViewFeatures"
        };

        /// <inheritdoc />
        public IEnumerable<Assembly> CandidateAssemblies {
            get {
                return GetCandidateLibraries().SelectMany(l => l.Assemblies)
                                              .Select(Load);
            }
        }

        /// <summary>
        /// Returns a list of libraries that references the assemblies in <see cref="ReferenceAssemblies"/>.
        /// By default it returns all assemblies that reference any of the primary MVC assemblies
        /// while ignoring MVC assemblies.
        /// </summary>
        /// <returns>A set of <see cref="Library"/>.</returns>
        protected virtual IEnumerable<Library> GetCandidateLibraries() {
            if (ReferenceAssemblies == null) {
                return Enumerable.Empty<Library>();
            }

            // GetReferencingLibraries returns the transitive closure of referencing assemblies
            // for a given assembly.
            return ReferenceAssemblies.SelectMany(_libraryManager.GetReferencingLibraries)
                                      .Distinct()
                                      .Where(IsCandidateLibrary);
        }

        private static Assembly Load(AssemblyName assemblyName) {
            return Assembly.Load(assemblyName);
        }

        private bool IsCandidateLibrary(Library library) {
            Debug.Assert(ReferenceAssemblies != null);
            return !ReferenceAssemblies.Contains(library.Name);
        }
    }
}
```

``` csharp
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Reflection.PortableExecutable;
using System.Text;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Microsoft.Dnx.Compilation.CSharp;
using Microsoft.Extensions.CompilationAbstractions;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.PlatformAbstractions;

#if DNXCORE50
using System.Runtime.Loader;
#endif

namespace Microsoft.AspNetCore.Mvc.Razor.Internal {
    /// <summary>
    /// A type that uses Roslyn to compile C# content and <see cref="ILibraryExporter"/> to find out references.
    /// </summary>
    public class DnxRoslynCompilationService : ICompilationService {
        private readonly ConcurrentDictionary<string, AssemblyMetadata> _metadataFileCache =
            new ConcurrentDictionary<string, AssemblyMetadata>(StringComparer.OrdinalIgnoreCase);

        private readonly IApplicationEnvironment _environment;
        private readonly ILibraryExporter _libraryExporter;
        private readonly RazorViewEngineOptions _options;
        private readonly Lazy<List<MetadataReference>> _applicationReferences;

#if DNXCORE50
        private readonly RazorLoadContext _razorLoadContext = new RazorLoadContext();
#endif

        /// <summary>
        /// Initalizes a new instance of the <see cref="DnxRoslynCompilationService"/> class.
        /// </summary>
        /// <param name="environment">The environment for the executing application.</param>
        /// <param name="libraryExporter">The library manager that provides export and reference information.</param>
        /// <param name="host">The <see cref="IMvcRazorHost"/> that was used to generate the code.</param>
        /// <param name="optionsAccessor">Accessor to <see cref="RazorViewEngineOptions"/>.</param>
        /// <param name="fileProviderAccessor">The <see cref="IRazorViewEngineFileProviderAccessor"/>.</param>
        /// <param name="loggerFactory">The <see cref="ILoggerFactory"/>.</param>
        public DnxRoslynCompilationService(
            IApplicationEnvironment environment,
            ILibraryExporter libraryExporter,
            IMvcRazorHost host,
            IOptions<RazorViewEngineOptions> optionsAccessor,
            IRazorViewEngineFileProviderAccessor fileProviderAccessor) {
            _environment = environment;
            _libraryExporter = libraryExporter;
            _options = optionsAccessor.Value;
            _applicationReferences = new Lazy<List<MetadataReference>>(GetApplicationReferences);
        }

        public CompilationResult Compile(RelativeFileInfo fileInfo, string compilationContent) {
            var assemblyName = Path.GetRandomFileName();

            var sourceText = SourceText.From(compilationContent, Encoding.UTF8);
            var syntaxTree = CSharpSyntaxTree.ParseText(
                sourceText,
                path: assemblyName,
                options: _options.ParseOptions);

            var references = _applicationReferences.Value;

            var compilation = CSharpCompilation.Create(
                assemblyName,
                options: _options.CompilationOptions,
                syntaxTrees: new[] { syntaxTree },
                references: references);

            using (var ms = new MemoryStream()) {
                using (var pdb = new MemoryStream()) {
                    var result = compilation.Emit(ms);
                    if (!result.Success) {
                        return GetCompilationFailedResult(
                            fileInfo.RelativePath,
                            compilationContent,
                            assemblyName,
                            result.Diagnostics);
                    }

                    ms.Seek(0, SeekOrigin.Begin);

                    var assembly = LoadStream(ms, assemblySymbols: null);

                    var type = assembly
                        .GetExportedTypes()[0];

                    return new CompilationResult(type);
                }
            }
        }

        internal CompilationResult GetCompilationFailedResult(
            string relativePath,
            string compilationContent,
            string assemblyName,
            IEnumerable<Diagnostic> diagnostics) {
            var diagnosticGroups = diagnostics
                .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                .GroupBy(diagnostic => diagnostic.Location.GetMappedLineSpan().Path, StringComparer.Ordinal);

            var failures = new List<Diagnostics.CompilationFailure>();
            foreach (var group in diagnosticGroups) {
                var sourceFilePath = group.Key;

                var compilationFailure = new Diagnostics.CompilationFailure(
                    sourceFilePath,
                    string.Empty,
                    compilationContent,
                    group.Select(GetDiagnosticMessage));

                failures.Add(compilationFailure);
            }

            return new CompilationResult(failures);
        }

        private static Diagnostics.DiagnosticMessage GetDiagnosticMessage(Diagnostic diagnostic) {
            var mappedLineSpan = diagnostic.Location.GetMappedLineSpan();
            return new Diagnostics.DiagnosticMessage(
                diagnostic.GetMessage(),
                CSharpDiagnosticFormatter.Instance.Format(diagnostic),
                mappedLineSpan.Path,
                mappedLineSpan.StartLinePosition.Line + 1,
                mappedLineSpan.StartLinePosition.Character + 1,
                mappedLineSpan.EndLinePosition.Line + 1,
                mappedLineSpan.EndLinePosition.Character + 1);
        }

        private Assembly LoadStream(MemoryStream ms, MemoryStream assemblySymbols) {
#if DNX451
            return Assembly.Load(ms.ToArray(), assemblySymbols?.ToArray());
#else
            return _razorLoadContext.Load(ms, assemblySymbols);
#endif
        }

        private List<MetadataReference> GetApplicationReferences() {
            var references = new List<MetadataReference>();

            // Get the MetadataReference for the executing application. If it's a Roslyn reference,
            // we can copy the references created when compiling the application to the Razor page being compiled.
            // This avoids performing expensive calls to MetadataReference.CreateFromImage.
            var libraryExport = _libraryExporter.GetExport(_environment.ApplicationName);
            if (libraryExport?.MetadataReferences != null && libraryExport.MetadataReferences.Count > 0) {
                Debug.Assert(libraryExport.MetadataReferences.Count == 1,
                    "Expected 1 MetadataReferences, found " + libraryExport.MetadataReferences.Count);
                var roslynReference = libraryExport.MetadataReferences[0] as IRoslynMetadataReference;
                var compilationReference = roslynReference?.MetadataReference as CompilationReference;
                if (compilationReference != null) {
                    references.AddRange(compilationReference.Compilation.References);
                    references.Add(roslynReference.MetadataReference);
                    return references;
                }
            }

            var export = _libraryExporter.GetAllExports(_environment.ApplicationName);
            if (export != null) {
                foreach (var metadataReference in export.MetadataReferences) {
                    // Taken from https://github.com/aspnet/KRuntime/blob/757ba9bfdf80bd6277e715d6375969a7f44370ee/src/...
                    // Microsoft.Extensions.Runtime.Roslyn/RoslynCompiler.cs#L164
                    // We don't want to take a dependency on the Roslyn bit directly since it pulls in more dependencies
                    // than the view engine needs (Microsoft.Extensions.Runtime) for example
                    references.Add(ConvertMetadataReference(metadataReference));
                }
            }

            return references;
        }

        private MetadataReference ConvertMetadataReference(IMetadataReference metadataReference) {
            var roslynReference = metadataReference as IRoslynMetadataReference;

            if (roslynReference != null) {
                return roslynReference.MetadataReference;
            }

            var embeddedReference = metadataReference as IMetadataEmbeddedReference;

            if (embeddedReference != null) {
                return MetadataReference.CreateFromImage(embeddedReference.Contents);
            }

            var fileMetadataReference = metadataReference as IMetadataFileReference;

            if (fileMetadataReference != null) {
                return CreateMetadataFileReference(fileMetadataReference.Path);
            }

            var projectReference = metadataReference as IMetadataProjectReference;
            if (projectReference != null) {
                using (var ms = new MemoryStream()) {
                    projectReference.EmitReferenceAssembly(ms);

                    return MetadataReference.CreateFromImage(ms.ToArray());
                }
            }

            throw new NotSupportedException();
        }

        private MetadataReference CreateMetadataFileReference(string path) {
            var metadata = _metadataFileCache.GetOrAdd(path, _ => {
                using (var stream = File.OpenRead(path)) {
                    var moduleMetadata = ModuleMetadata.CreateFromStream(stream, PEStreamOptions.PrefetchMetadata);
                    return AssemblyMetadata.Create(moduleMetadata);
                }
            });

            return metadata.GetReference(filePath: path);
        }

#if DNXCORE50
        private class RazorLoadContext : AssemblyLoadContext {
            protected override Assembly Load(AssemblyName assemblyName) {
                return Default.LoadFromAssemblyName(assemblyName);
            }

            public Assembly Load(Stream assembly, Stream assemblySymbols) {
                return LoadFromStream(assembly, assemblySymbols);
            }
        }
#endif
    }
}
```

``` csharp
public void ConfigureServices(IServiceCollection services) {
    // Note: to make sure MVC works on DNX, the assembly provider and the compilation service must be replaced.
    // See https://github.com/aspnet/Mvc/commit/80b6996701ca240b8b4b1ba8f56c7ecae3e69b60#commitcomment-16288972
    if (DnxPlatformServices.Default?.LibraryManager != null) {
        services.AddSingleton(CompilationServices.Default.LibraryExporter);
        services.AddSingleton(DnxPlatformServices.Default.LibraryManager);

        services.AddTransient<IAssemblyProvider, DnxAssemblyProvider>();
        services.AddSingleton<ICompilationService, DnxRoslynCompilationService>();
    }
}
```

**Comment by Gillardo** [comment]
@PinpointTownes that bug fix seems to sort the import errors and the site now runs.  Now i think a namespace of something has changed as my Views/OpenIddict/Error.cshtml and other pages are reporting errors with the using statement `@using Microsoft.IdentityModel.Protocols.OpenIdConnect`

**Comment by Gillardo** [comment]
Duh, @PinpointTownes dont worry i realise that this is because you havent yet uploaded the AddMvcDnx fix yet.  Just let me know when you have please. Thanks

**Comment by kevinchalet** [comment]
That's planned, but I'm seeing weird restore issues when trying to update OpenIddict.Mvc to use AddMvcDnx. 

I'll investigate.

**Comment by ghost** [comment]
@Gillardo Did adding MvcDnx fix your _The type or namespace name 'xxxxx' could not be found_ ?

**Comment by Gillardo** [comment]
It did in my project. Just waiting for openiddict to be updated as it
currently says it now when i access the views in openiddict.assets, like
authorize etc

**Comment by kevinchalet** [comment]
I just pushed a commit to fix/work around that: https://github.com/openiddict/openiddict-core/commit/a6b85f1f15b8d50d9097b57e0628ede3c412f7cf

Give the CI server a few minutes before updating your packages.

**Comment by kevinchalet** [comment]
The new package is online :smile:
