### ISSUE TITLE
How to sign out some certain user

### ISSUE THREAD

**Issue by antonsacz** [openiddict/openiddict-core#642]
Hello,

in the system, I'm currently working on an admin could mark user account as "Disabled", is there any way to force logout process for this user immediately (probably invalidate all issued tokens)?

Thanks,
Anton

**Comment by kevinchalet** [comment]
Hey,

To revoke all the tokens associated with a specific subject (i.e user) **that are stored in the database**, you can do something like that:

```csharp
// tokenManager is of type OpenIddictTokenManager<OpenIddictToken>.
foreach (var token in await tokenManager.FindBySubjectAsync("subject/user identifier"))
{
    if (await tokenManager.IsValidAsync(token))
    {
        await tokenManager.RevokeAsync(token);
    }
}
```

It's worth noting it will only work with authorization codes or refresh tokens OOTB: by default, tokens are not stored in the database and thus can't be revoked. If you need support for immediate revocation, you'll have to use reference tokens (by calling `options.UseReferenceTokens()` in both the server and validation options).
