### ISSUE TITLE
NullReferenceException in OpenIddictServerProvider.ApplyAuthorizationResponse

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-core#643]
[This line](https://github.com/openiddict/openiddict-core/blob/0cf731166482040d2d1a60a3fa3b8b3db6ee3fdc/src/OpenIddict.Server/Internal/OpenIddictServerProvider.Authentication.cs#L496) produces exception because of `context.Request` is null

Maybe it must be `context.Request?.RequestId`?

**Comment by kevinchalet** [comment]
Nice catch. Thanks for reporting this bug :+1: 

I'll fix it and make sure it's included in the nightly and RTM bits.
