### ISSUE TITLE
Sample code in readme requires context

### ISSUE THREAD

**Issue by gregsdennis** [openiddict/openiddict-core#646]
The sample code in the repo's README file contains references that only exist in the sample server project.  It's not exactly a copy/paste as the reader is lead to believe.

The missing references are  `ApplicationDbContext` and `ApplicationUser`.  It also requires the user to add a SQL Server connection string under `Data:DefaultConnection:ConnectionString` in the *appsettings.config* file.

It took me a while it figure this out.  I thought I was missing Nuget package references.

**Comment by kevinchalet** [comment]
Here's what the README says:

> Have an existing project or create a new one: when creating a new project using Visual Studio's default ASP.NET Core template, using individual user accounts authentication is strongly recommended. When updating an existing project, you must provide your own AccountController to handle the registration process and the authentication flow.

`ApplicationDbContext` and `ApplicationUser` are ASP.NET Core Identity artifacts and are present when using the mentioned template. Did you use this template or did you create an application from scratch?

**Comment by gregsdennis** [comment]
I created one from scratch using an empty template.

I had planned on just using client auth only, so I didn't need user accounts.  Then I changed my mind afterward.

**Comment by kevinchalet** [comment]
@gregsdennis so this explains why the things you mentioned were missing. If you think you can improve the README, feel free to submit a PR.
