### ISSUE TITLE
JWT refresh token storage & validation

### ISSUE THREAD

**Issue by matthiasleitner** [openiddict/openiddict-core#648]
I am using openiddict with JWT and have the problem that all refresh token become invalid once I redeploy the application using docker. 

Since I've set a SinginKey I assumed that all tokens should stay valid regardless of application lifetime. 

We use EntityFramework token store and there are refresh token objects in the database but they don't contain the actual token values.

Can someone clarify how the refresh tokens are validated?

Thanks in advance

**Comment by kevinchalet** [comment]
> Can someone clarify how the refresh tokens are validated?

They are generated and validated using ASP.NET Core Data Protection, on which your signing key has no effect.

https://stackoverflow.com/questions/42628862/openiddict-401-errors-when-two-or-more-service-instance-count/42632239#42632239 should put you on the right track.

**Comment by matthiasleitner** [comment]
@PinpointTownes thanks for the link

two questions on that:
1. The SO answer notes that Core Data Projection is only used 

> unless you explicitly opt for JWT as the access token format

does this mean its not used if I am calling **AddJwtBearer**?

2. The Microsoft actually cover the handling for key handling for docker containers, is this something openiddict can cover using its token persistence? 
```
Persisting keys when hosting in a Docker container
When hosting in a Docker container, keys should be maintained in either:

A folder that's a Docker volume that persists beyond the container's lifetime, such as a shared volume or a host-mounted volume.
An external provider, such as Azure Key Vault or Redis.
```

**Comment by kevinchalet** [comment]
Authorization codes and refresh tokens are always encrypted using Data Protection, independently of the format used for access tokens. In other words, authorization codes and refresh tokens CAN'T be JWT tokens.

Concerning DP, OpenIddict will use whatever you configure globally. If you configure DP to store the key ring in a Docker volume, it will use it.

**Comment by matthiasleitner** [comment]
I've now tried to implement a store based on entity framework like shown below, unfortunately the  DataProtectionKeyRepository implementing IXmlRepository is never being called on new token generation.

```
public static class DataProtectionKeyExtensions
    {
        public static IDataProtectionBuilder PersistKeysToSql(this IDataProtectionBuilder builder)
        {
            if (builder == null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            return builder.Use(ServiceDescriptor.Singleton<IXmlRepository, DataProtectionKeyRepository>());
        }

        public static IDataProtectionBuilder Use(this IDataProtectionBuilder builder, ServiceDescriptor descriptor)
        {
            if (builder == null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            if (descriptor == null)
            {
                throw new ArgumentNullException(nameof(descriptor));
            }

            for (int i = builder.Services.Count - 1; i >= 0; i--)
            {
                if (builder.Services[i]?.ServiceType == descriptor.ServiceType)
                {
                    builder.Services.RemoveAt(i);
                }
            }

            builder.Services.Add(descriptor);

            return builder;
        }
    }
}
```


I am setting it up like this in startup.cs


```
   var encryptionSettings = new AuthenticatedEncryptorConfiguration()
            {
                EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
            };   

 services.AddDataProtection()                    
                    .SetApplicationName("my-application")
                    .PersistKeysToSql()                   
                    .UseCryptographicAlgorithms(encryptionSettings);
```


Any ideas on that? Thanks in advance!

**Comment by kevinchalet** [comment]
The XML repository service is not registered via DI but as an option. Take a look at https://github.com/aspnet/DataProtection/blob/master/src/Microsoft.AspNetCore.DataProtection.AzureStorage/AzureDataProtectionBuilderExtensions.cs#L170 to see how you can override the default instance.

If you have questions about DP, I encourage you to post them on the DP repo as the ASP.NET team has much more bandwidth than I have to answer general ASP.NET questions: https://github.com/aspnet/DataProtection

**Comment by matthiasleitner** [comment]
Setting it as an option worked - thanks for your help @PinpointTownes
