### ISSUE TITLE
CryptoHelper

### ISSUE THREAD

**Issue by henkmollema** [openiddict/openiddict-core#65]
I noticed that you removed CryptoHelper from the project. Is there any issue you ran into? I've just deployed a new version using the latest RC2 bits: https://www.nuget.org/packages/CryptoHelper/1.0.0-rc2-build02.

**Comment by kevinchalet** [comment]
> Is there any issue you ran into?

Hey!

Yep, I had to temporarily remove CryptoHelper when migrating all the aspnet-contrib projects to the latest ASP.NET Core/.NET CLI bits as it was referencing the old `Microsoft.AspNet` packages, which prevented OpenIddict from building correctly: https://github.com/openiddict/openiddict-core/commit/c8d8afccd0a6b14d59ffe4d4c5e8b59bf60a4f32

AFAICT, you haven't migrated to the new `Microsoft.AspNetCore` packages yet: https://github.com/henkmollema/CryptoHelper/blob/master/src/CryptoHelper/project.json#L22. Of course, I'll bring back CryptoHelper in OpenIddict when a compatible version is released :clap: 

Thanks!

**Comment by henkmollema** [comment]
Ah, you're right. I've updated the package to use the AspNetCore packages: https://www.nuget.org/packages/CryptoHelper/1.0.0-rc2-build03. I'll send a PR using CryptoHelper.

**Comment by kevinchalet** [comment]
Merged, thanks! :+1: 

https://github.com/openiddict/openiddict-core/commit/cac0a3594ef9637a72a4016345899e90dd5993e7 :clap:
