### ISSUE TITLE
netcoreapp2.0 - Could not load type 'Microsoft.AspnetCore.Builder.AuthenticationOptions'

### ISSUE THREAD

**Issue by tschennie** [openiddict/openiddict-core#651]
I migrated my project from ASP.NET Core 1.1 to 2.0 and with starting the WebAPI, I got following exception within the **Program.BuildWebHost**:

_**System.TypeLoadException: "Could not load type 'Microsoft.AspNetCore.Builder.AuthenticationOptions' from assembly 'Microsoft.AspNetCore.Authentication, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."**_

I'm using following versions:

>     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
>     <PackageReference Include="AspNet.Security.OAuth.Introspection" Version="1.0.0" />
>     <PackageReference Include="AspNet.Security.OAuth.Validation" Version="1.0.0" />
>     <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="5.1.5" />
>     <PackageReference Include="OpenIddict" Version="1.0.0-rc2-0784" />
>     <PackageReference Include="OpenIddict.Core" Version="1.0.0-rc2-0784" />
>     <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="1.0.0-rc2-0784" />
>     <PackageReference Include="OpenIddict.Mvc" Version="1.0.0-rc2-0784" />
>     <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.5" />
>     <PackageReference Include="System.Runtime" Version="4.3.0" />
>     <PackageReference Include="Swashbuckle" Version="6.0.0-beta902" />
>     <PackageReference Include="Serilog" Version="2.6.0" />
>     <PackageReference Include="Serilog.Sinks.AzureTableStorage" Version="4.0.0" />
>     <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
>     <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
>     <PackageReference Include="System.Net.Security" Version="4.3.2" />

**Comment by kevinchalet** [comment]
If you Google this error, you'll see it's caused by the fact you're mixing packages designed for ASP.NET Core 1.x and packages written for 2.x. Migrate everything to the latest version and it will work.
