### ISSUE TITLE
404 when using options.AcceptAnonymousClients() in RC3

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#654]
I get a 404 response when I POST to /connect/token in my .NET Core 2.1 app.  The request doesn't include client_id, but I'm using the new options.AcceptAnonymousClients() in RC3, so I'd expect this be fine and get a token in the response.   

This is from the console log:
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 POST http://localhost:5001/connect/token application/x-www-form-urlencoded 61
> info: OpenIddict.Server.OpenIddictServerHandler[0]
>       The token request was successfully extracted from the HTTP request: {
>         "username": "Administrator",
>         "password": "[removed for security reasons]",
>         "grant_type": "password"
>       }.
> dbug: OpenIddict.Server.OpenIddictServerProvider[0]
>       The token request validation process was partially skipped because the 'client_id' parameter was missing or empty.

This is from my Startup class:

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("MyDb"));
                options.UseOpenIddict();
            });
           
            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddOpenIddict()
                .AddCore(options => options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>())
                .AddServer(options =>
                {
                    options.UseMvc();
                    options.EnableTokenEndpoint("/connect/token");
                    options.AllowPasswordFlow();
                    options.DisableHttpsRequirement(); 
                    options.AcceptAnonymousClients();
                    options.UseJsonWebTokens();
                    options.AddEphemeralSigningKey();
                });
        }

Am I doing something wrong?

**Comment by kevinchalet** [comment]
Does your authorization controller have appropriate routes that match the token endpoint path?

**Comment by ghost** [comment]
Thanks @PinpointTownes. No, I'd messed-up my controller. As soon as I fixed it, it worked. I'd just misunderstood the console output.  Thank you.
