### ISSUE TITLE
Cant validate opacue token while using tenant example. Access token was invalid.

### ISSUE THREAD

**Issue by unixrex** [openiddict/openiddict-core#655]
Hello! I have some issue while using example implementation of tenant there - https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login.

Just using code flow sample to add example implementation and cant validate request to {tenant}/api/userinfo

Logs:

Got token:

Performing protect operation to key {270f5b10-d8a5-4983-8213-a7c1db6fef52} with purposes ('E:\openiddict-samples-dev\samples\CodeFlow\AuthorizationServer', '/test', 'OpenIdConnectServerHandler', 'AccessTokenFormat', 'ASOS').
A new access token was successfully generated using the specified data format: _____ , name: _______ ; [.scopes, ["openid","email","profile"]], [.resources, ["resource_server"]], [.presenters, ["postman"]], [.issued, Fri, 10 Aug 2018 09:55:57 GMT], [.expires, Fri, 10 Aug 2018 10:
55:57 GMT], [.authorization_id, __________], [.token_id, ____________], [.audiences, ["resource_server"]].

Try test/api/userinfo:

Request starting HTTP/1.1 GET http://localhost:54540/test/api/userinfo application/vnd.api+json
Performing unprotect operation to key {270f5b10-d8a5-4983-8213-a7c1db6fef52} with purposes ('E:\openiddict-samples-dev\samples\CodeFlow\AuthorizationServer', 'OpenIdConnectServerHandler', 'AccessTokenFormat', 'ASOS').
**Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.**

Only difference in purposes. Can this influence the validation? If so, how to add tenant purpose to OpenId validation options?

**Comment by kevinchalet** [comment]
Hey,

> Only difference in purposes. Can this influence the validation?

Definitely. That's even the whole point: not being able to decrypt an access token if the receiver is not the expected one.

The validation part should be fairly identical, except you'll amend `OpenIddictValidationOptions` instead of `OpenIddictServerOptions`.

**Comment by unixrex** [comment]
Did I understand correctly - i must create custom OpenIddictValidationOptions in OpenIddictServerOptionsProvider to add tenant purpose? or?

**Comment by kevinchalet** [comment]
You must create a custom `OpenIddictValidationOptionsProvider` and an `OpenIddictValidationOptionsInitializer`, exactly like the server ones, but with `OpenIddictValidationOptions` instead of `OpenIddictServerOptions`.

**Comment by unixrex** [comment]
Yeap! Thx for a beautiful library!

**Comment by kevinchalet** [comment]
Glad you like it :smile:
