### ISSUE TITLE
Entity Framework Error: Second operation

### ISSUE THREAD

**Issue by peterfournier** [openiddict/openiddict-core#656]
Hi,

Currently I've been experiencing this error when working with OpenIddict:

_A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe._

I believe it's stemming from some .FirstOrDefaultAsync() calls that are not being awaited, e.g. OpenIddictScopeStore.cs line 183. There are more throughout the core.

Here is a [link](https://jimlynn.wordpress.com/2017/11/16/entity-framework-error-a-second-operation-started-on-this-context-before-a-previous-operation-completed-any-instance-members-are-not-guaranteed-to-be-thread-safe/) describing the issue.

Thanks,
Pete

**Comment by kevinchalet** [comment]
Hey Pete,

That's the first time I hear that. Any chance you could share your Startup and your dependencies?

> I believe it's stemming from some .FirstOrDefaultAsync() calls that are not being awaited, e.g. OpenIddictScopeStore.cs line 183. There are more throughout the core.

Very unlikely. It's a very common optimization (described here: https://particular.net/blog/async-await-tips-and-tricks) and it shouldn't cause such issues.

**Comment by kevinchalet** [comment]
@peterfournier FWIW, RTM is shipping soon. If there's a bug somewhere (in OI or EF), it would be nice to know it before we release it. Please let me know if you're still blocked by this threading issue.

**Comment by peterfournier** [comment]
Hey, apologies for the late reply. 

I'm not 100% sure it's OpenIddict. It might be exposing an issue with my DI in my own application. The error does do away however when I remove the authorization attributes on my api controllers, that lead me to believe it was OpenIddict.

Anyway, thanks for your time. I'll continue digging.

**Comment by kevinchalet** [comment]
@peterfournier hey. Is your app OSS and visible somewhere so I can take a look?
