### ISSUE TITLE
Missing client_id parameter in token request authorization code flow using postman

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#658]
Hi everyone,

I have an issue with my authorizatian. I created an application and I added my authorization and token endpoint. I used mostly the same code as in the samples solutions from github to get aquainted with the code and openiddict. When I try to test the authrization code flow with postman I get an error in the token endpoint, generated in openiddict code, saying the required client_id is missing.

> error:invalid_request
error_description:The mandatory 'client_id' parameter is missing.

 However, when I look at the request sent by postman I see the client_id parameter supplied in the querystring. Does this need to be in the form and, if so, how do I force postman to send it in the form instead of querystring? Or is there something else I am doing wrong?

Here is a copy of my request sent by postman:

> **General**
>
>Request URL:https://localhost:44390/connect/authorize?response_type=code&state=&client_id=postman&scope=email%20profile&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback
Request Method:POST
Status Code:400 
Remote Address:[::1]:44390
Referrer Policy:no-referrer-when-downgrade]
>
>**Response Headers**
>
>cache-control:no-cache
content-length:90
content-type:text/plain;charset=UTF-8
date:Mon, 20 Aug 2018 06:50:25 GMT
expires:Thu, 01 Jan 1970 00:00:00 GMT
pragma:no-cache
server:Kestrel
status:400
x-powered-by:ASP.NET
x-sourcefiles:=?UTF-8?B?QzpcVXNlcnNcYmtvb2lcRG9jdW1lbnRzXFdvcmtcTW92aWVCYXNlXEFQSVxNb3ZpZUJhc2UuQVBJXGNvbm5lY3RcYXV0aG9yaXpl?=
>
>**Request Headers**
>
>:authority:localhost:44390
:method:POST
:path:/connect/authorize?response_type=code&state=&client_id=postman&scope=email%20profile&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding:gzip, deflate
accept-language:nl
cache-control:max-age=0
content-length:255
content-type:application/x-www-form-urlencoded
cookie:.AspNet.Consent=yes; .AspNetCore.Antiforgery.Fm_cNTCLM-A=CfDJ8HXCIIfn9QNAkX_hflLNTOlIPcaYO3Z9RrTKgt6z4xgKhkTOTV3_DlcArMSOqKcUpu20A_Kw0KLqMx4FZIjrXeD_Usb6520npi4A8cjDsGCb5in61icGPRKID42hjP4r66lJYIm1kpWxx90Mil871S4; .AspNetCore.Identity.Application=CfDJ8HXCIIfn9QNAkX_hflLNTOkQegYlE2kj8DvsXo1xXeXZSirhXWfJnh48bvGqmxrbxCG6h4AcCC3aX_Vpc9DSYbXD1tpIKt79PzHjkPaCBPp67-avdUve3FvXOdj7BEVAgxeBhC8SqpzeeqNbV8_IYgiVQ0ohdL7n7-KdOOT1sXXnfyBRgipQOUtZB3bjABpdN-c5UXPbNHKaWxbYPZ7jJ4XF9prcG7WEgz2bulwntAC4nY9Bc5nx0D0frA-5_Brpdtnii3peszxIhm11Gv6yM90u02cHIznaXqSIZ6d7Z8Dtfx7_IUCezcumO4GKMswIoiiKxMvWk7aobawPnoWrk-l2RHj717lDRfqN468yoa75bvOw-dm4j60UWqJquLhyxoWEeRD0lnXUHQN2EOZMdYaQ1UcEnk6LX3JvJLa7_AgdS_QssReNWGA0Oy4cJ1jB-ws-gBKmnCO25bgshKq2i3YAo_r-WptkLWprnhQS9gRa9guACHS0K1SbHYVIqhh6IKJveA2iLcH5Ta9fF7YdKeuP9nzO4Lo6n955nvjKeo7XiLCxNNh-V9bU4hzx6l3I-9n7MG_vOv1RLbvKjrU9BcbGxScfJYxykDTQbEKW2k8C
origin:https://localhost:44390
referer:https://localhost:44390/connect/authorize?response_type=code&state=&client_id=postman&scope=email%20profile&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/6.2.4 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36
x-devtools-request-id:13292.21
>
>**Query String Parameters**
>
>response_type:code
state:
client_id:postman
scope:email profile
redirect_uri:https://www.getpostman.com/oauth2/callback
>
>**Form Data**
>request_id:
submit.Accept:Yes
__RequestVerificationToken:CfDJ8HXCIIfn9QNAkX_hflLNTOm3GzeaQv-giosXTGXmjZFFOFIkZMPYs3yemUi4yNN8BB33snGBZfT5EZrnY1UKA0nZlGXGTctzQiQt8ZbVKCKpfdxei1tOx_MSgoDFUx6f8NCNzvpdcyR6qyHljnpRtYx6-3vqaLO_DD0wdQpjS13RaBjmOwX9imedfZtPE1idtA

Kind regards

**Comment by ghost** [comment]
Hi,

A short update on this. I found out that Postman is posting the consent form with parameters as querystring instead of form serialization. Content type seems correct: x-wwwform-urlencoded. When I manually post with parameters as form all goes well. Anyone else experienced the same issue?

**Comment by kevinchalet** [comment]
Hey. 

The OAuth2/OpenID Connect specifications are pretty clear about that: when using GET, the OIDC parameters must be flowed as query string parameters and when using POST, they must be specified as form parameters.

**Comment by ghost** [comment]
Hey Kevin,

Thanks for your response. I have read the specifications as well and it makes perfect sense. So kudos for the library and samples. Therefor my question if anyone knows of this issue with postman. Maybe not the right place though but I wanted to place an update on the issue.

**Comment by ghost** [comment]
Hey Kevin, one update on this. I found out the problem was in my view. When it posts it only posts the form. Since the client_id etc. are not part of the form they are not serialized in the form data. I tricked it by making these part of the viewmodel and give them a hidden field. This doesn't feel right however because these fields can be tampered with. Furthermore in the sample, inclusief in the samples repo for the code flow I am not seeing the same hidden fields in the view. I still have a feeling I am missing some crucial and maybe  trivial point, but I can 't seem to figure out what. I am fairly new to all this and I'm sorry if I'm wasting your time. I feel stupid 😆.

**Comment by kevinchalet** [comment]
> This doesn't feel right however because these fields can be tampered with.

Nah, it's fine (one could change the parameters in the query string anyway).

> Furthermore in the sample, inclusief in the samples repo for the code flow I am not seeing the same hidden fields in the view. 

The sample uses request caching: https://github.com/openiddict/openiddict-core/blob/9a0689150765df61c4ad2d5f22b8c79c8e63cd34/samples/Mvc.Server/Startup.cs#L104-L109

**Comment by ghost** [comment]
Hey, thank you so much. I got my authentication set up. Both on the server side and my angular app. I still think the request caching solution is cleaner and I will set it up too.

Thanks for all the help. Kudos.
