### ISSUE TITLE
Custom JWT vs Openiddict

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#660]
I currently issue tokens myself in my web api with JwtSecurityToken and I use standard ASP.NET Core middleware calling AddJwtBearer to verify the tokens. It works fine.

What advantage will give me using OpenID Connect  over the approach described above? How to answer myself question "Do I need OpenID Connect?"

From my basic understanding about OpenID Connect, it is used to allow third parties to access your API. But I make API for myself and not for third parties and I don't know why should I favor OpenIddict over my simple approach.

**Comment by kevinchalet** [comment]
Related topic: https://github.com/aspnet/Security/issues/1723.
