### ISSUE TITLE
Update sql tables on migration to .net 2 

### ISSUE THREAD

**Issue by ddydeveloper** [openiddict/openiddict-core#664]
@PinpointTownes good evening!

It is unclear for me how to update SQL tables with add-migration command. Now, when I try to create new migration all openiddict tables getting removed: 

       protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OpenIddictScopes");

            migrationBuilder.DropTable(
                name: "OpenIddictTokens");

            migrationBuilder.DropTable(
                name: "OpenIddictAuthorizations");

            migrationBuilder.DropTable(
                name: "OpenIddictApplications");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "OpenIddictApplications",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    ClientId = table.Column<string>(nullable: true),
                    ClientSecret = table.Column<string>(nullable: true),
                    DisplayName = table.Column<string>(nullable: true),
                    LogoutRedirectUri = table.Column<string>(nullable: true),
                    RedirectUri = table.Column<string>(nullable: true),
                    Type = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OpenIddictApplications", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "OpenIddictScopes",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    Description = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OpenIddictScopes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "OpenIddictAuthorizations",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    ApplicationId = table.Column<string>(nullable: true),
                    Scope = table.Column<string>(nullable: true),
                    Subject = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OpenIddictAuthorizations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_OpenIddictAuthorizations_OpenIddictApplications_ApplicationId",
                        column: x => x.ApplicationId,
                        principalTable: "OpenIddictApplications",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "OpenIddictTokens",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    ApplicationId = table.Column<string>(nullable: true),
                    AuthorizationId = table.Column<string>(nullable: true),
                    Subject = table.Column<string>(nullable: true),
                    Type = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OpenIddictTokens", x => x.Id);
                    table.ForeignKey(
                        name: "FK_OpenIddictTokens_OpenIddictApplications_ApplicationId",
                        column: x => x.ApplicationId,
                        principalTable: "OpenIddictApplications",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId",
                        column: x => x.AuthorizationId,
                        principalTable: "OpenIddictAuthorizations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_OpenIddictApplications_ClientId",
                table: "OpenIddictApplications",
                column: "ClientId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_OpenIddictAuthorizations_ApplicationId",
                table: "OpenIddictAuthorizations",
                column: "ApplicationId");

            migrationBuilder.CreateIndex(
                name: "IX_OpenIddictTokens_ApplicationId",
                table: "OpenIddictTokens",
                column: "ApplicationId");

            migrationBuilder.CreateIndex(
                name: "IX_OpenIddictTokens_AuthorizationId",
                table: "OpenIddictTokens",
                column: "AuthorizationId");
        }

So it seems I didn't include something to provide openiddict SQL tables migration  

I've include this packaes into my MVC and database projects:

> PackageReference Include="OpenIddict" Version="2.0.0-rc3-final"
> PackageReference Include="OpenIddict.EntityFrameworkCore" Version="2.0.0-rc3-final"

And the DBContext registration code looks like this:

        services.AddDbContext<LcdContext>(options =>
        {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                options.UseOpenIddict();
        });

Maybe I am not completely understand, could you explain how to set up the OpenIdDict db tables. Now I am working on the old project and try to migrate to the .net 2 version. There is an initial migration with openiddict tables, but I think this tables should be updated for the 2 version.

Cause I am getting DbUpdateException, related with the missing columns, such as:

Invalid column name 'ConcurrencyToken'.
Invalid column name 'Properties'.
Invalid column name 'Scopes'.
Invalid column name 'Status'.
Invalid column name 'Type'.

**Comment by kevinchalet** [comment]
Hey,

Any chance you could list the steps that led to this oddity?
Would https://openiddict.github.io/openiddict-documentation/guide/migration.html#ensure-migrations-are-correctly-enabled-for-your-project help solve your issue?

**Comment by ddydeveloper** [comment]
@PinpointTownes , thank you for the reply!

I've solved my problem, it was more about the Entity Framework migration changes in .net core 2.1 version, not the Openiddict problem! 

Sorry for the anxiety.

**Comment by Booster2ooo** [comment]
@ddydeveloper Hello, could you discribe your fix please ? I'm facing the same problem but can't figure out the solution :'(

**Comment by ddydeveloper** [comment]
@Booster2ooo I've updated my nuget references of the .net core and entity framework and have added a one more migration included openiddict updates.

After I have updated the db and get the working stuff.

Hope it will be usefull
