### ISSUE TITLE
Multiple token endpoints

### ISSUE THREAD

**Issue by ddydeveloper** [openiddict/openiddict-core#667]
Good morning!

Is it possible to implement multiple token end points? 
    `options.EnableTokenEndpoint("/connect/token");
     options.EnableTokenEndpoint("/connect/token2");
    `

It can be useful, for instance, when you have multiple client apps but with the different user access rules: admin app, log app, etc. 

Sure we can implement logic inside the single endpoint, but in this case I should pass something, like a ClientId.

Actually, I've just add client Id and match it as OpenIdConnectRequest parameter.

What the flow would you prefer?

**Comment by kevinchalet** [comment]
Hey,

Technically, it's possible to force OpenIddict to listen on multiple paths. There's a sample in this blog post: https://kevinchalet.com/2018/07/02/implementing-advanced-scenarios-using-the-new-openiddict-rc3-events-model/

```csharp
options.EnableTokenEndpoint("/connect/token");

options.AddEventHandler<OpenIddictServerEvents.MatchEndpoint>(notification =>
{
    // By default, only requests sent to /connect/token will be treated as valid
    // token requests by OpenIddict. This custom logic allows requests pointing
    // to /connect/second-token-endpoint to be treated the same way so that
    // requests can be sent to one of the two addresses without any distinction.
    var request = notification.Context.HttpContext.Request;
    if (request.Path == "/connect/second-token-endpoint")
    {
        notification.Context.MatchTokenEndpoint();
    }
    return Task.CompletedTask;
});
```

(the syntax will vary a bit in the RTM nightly builds)

Now, would I personally recommend it? **Very likely not**, as it will force your clients to manually specify a custom token endpoint URL instead of the one returned by the OIDC discovery endpoint: it's counter-intuitive.

If you only want to have multiple MVC actions (e.g one per client) for the token endpoint, then having a single address and custom MVC actions+constraints to internally dispatch your token requests to multiple code paths would be by favorite approach.

E.g:

```csharp
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public class ForSpecificApplicationsAttribute : Attribute, IActionConstraint
{
    public ForSpecificApplicationsAttribute(params string[] clientIds)
        => ClientIds = new ReadOnlyCollection<string>(clientIds);

    public IReadOnlyList<string> ClientIds { get; }

    public int Order => 0;

    public bool Accept(ActionConstraintContext context)
    {
        var request = context.RouteContext.HttpContext.GetOpenIdConnectRequest();
        if (request == null)
        {
            throw new InvalidOperationException("The OpenID Connect request cannot be retrieved.");
        }

        if (string.IsNullOrEmpty(request.ClientId))
        {
            throw new InvalidOperationException("The client identifier cannot be retrieved.");
        }

        for (var index = 0; index < ClientIds.Count; index++)
        {
            if (string.Equals(request.ClientId, ClientIds[index], StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }
}
```

```csharp
[HttpPost("~/connect/token"), Produces("application/json")]
[ForSpecificApplications("internal_client_1", "internal_client_2")]
public async Task<IActionResult> TokenEndpointActionForSpecificApps(OpenIdConnectRequest request)
{
    // ...
}

[HttpPost("~/connect/token"), Produces("application/json")]
public async Task<IActionResult> TokenEndpointActionForOtherApps(OpenIdConnectRequest request)
{
    // ...
}
```

**Comment by ddydeveloper** [comment]
@PinpointTownes  thank you so mauch! 

Actually, I just want to provide the most predictable and simple flow for authenticating user through the multiple SPA apps. 

The same user can work with one app, but can't access the admin one, for instance. I want to keep all of the authentication logic inside one API, but separate authentication process for different apps. 

And what do you think about ClientId usage? What if we register client apps with ClientId? We can send it and manage authentication process manually by getting ClientId property of the OpenIdConnectRequest instance.

**Comment by ddydeveloper** [comment]
But in my case I need smth like mixed Password and ClientId flow: use the credentials to authenticate the user and ClientId to define the authentication rules.

**Comment by kevinchalet** [comment]
> But in my case I need smth like mixed Password and ClientId flow: use the credentials to authenticate the user and ClientId to define the authentication rules.

You can certainly do that, as the password flow supports client authentication. But don't forget SPA are public clients by definition as they can't keep a secret really secret (since it's accessible by the browser and the user), so you can't be 100% sure the request comes from a trusted app, even if it specified a `client_id`.

**Comment by ddydeveloper** [comment]
@PinpointTownes , if it is possible could you provide an example how to combine password and client workflow. 

Actually it is not required to follow this approach, but I really can't find the best way, how to use the same endpoint to authorize a lot of clients without sending this info through the authentication request.

This looks like potentially weakness even if I set client_guid (let's say the "guid" instead of the "client_id" just not to confuse the flow and final result) and check it on the server-side.

**Comment by adadurov** [comment]
@ddydeveloper , as you mentioned SPA clients, it it seems there are only front-channel communications involved in your use cases, right? However, it's not clear whether you plan on using individual user accounts along with the apps, or not?

**Comment by ddydeveloper** [comment]
@adadurov I need to provide the clients credentials usage. Maybe the problem more about the authorization, not the authentication.

I have two client apps written with the angular framework, one for the ordinary users and one for administrators only. 

So, maybe the right way is to authenticate users by token endpoint and manage the access on the client sides by guards, for instance. But it seems not secure and I prefer to provide such opportunity for the server side.

**Comment by adadurov** [comment]
@ddydeveloper , indeed, I believe you could solve it with authorization policies based on roles, permissions and/or scopes.

**Comment by ddydeveloper** [comment]
@adadurov  @PinpointTownes, thank you for discussion! Close the issue

**Comment by gentledepp** [comment]
> ```cs
> OpenIddictServerEvents.MatchEndpoint
> ```

It seems this sample is not valid anymore.
I cannot find this type in the entire codebase:
`OpenIddictServerEvents.MatchEndpoint`

Was it renamed?

**Comment by gentledepp** [comment]
I just found out.
Easy enough, you can now add multiple uris for any endpoint:
```csharp
// Register the OpenIddict server components.
            .AddServer(options =>
            {   
                // Enable the authorization and token endpoints.
                options.SetAuthorizationEndpointUris("connect/authorize")
                       .SetTokenEndpointUris("connect/token", "token");  //setting multiple token endpoints
```

What I _did_ forget was to also add this route to my controller action:

```diff
    [HttpPost]
    [Route("~/connect/token")]
+    [Route("~/token")]
    public async Task<ActionResult> Exchange()
    {
```
