### ISSUE TITLE
TKey<int> or <Guid> Not working when using ReplaceDefaultEntities<TKey>

### ISSUE THREAD

**Issue by pabhashasync** [openiddict/openiddict-core#668]
Right now is not possible to change the Id Keys to Guid or int. The db context does not recognize the entities, and I tried different workaround and none of them worked.
Please review how ReplaceDefaultEntities<Tkey> works together with the UseOpenIddict<Tkey>.

**Comment by kevinchalet** [comment]
Post your code.

**Comment by pabhashasync** [comment]
I tried different ways, none worked. This is the basic configuration one I tried :
http://prntscr.com/kxoor2

**Comment by kevinchalet** [comment]
What’s the exact exception you’re getting when using this configuration?

**Comment by pabhashasync** [comment]
It says that the db context cannot find the entity `OpenIddictAuthorizations<int>`
I also tried explicitily adding the OpenIddict in the dbContext, and as well using `options.UseOpenIddict<All OpenIdDict entities>()` and none solved the exception.
Since most people do not like to have Id as string, would be great to have more documentation on how to chanhe the Id types. There is no documentation about and no working example using `TKey`.

**Comment by kevinchalet** [comment]
> It says that the db context cannot find the entity OpenIddictAuthorizations<int>

I need the complete exception, including the exact message and the stack trace.

> Since most people do not like to have Id as string, would be great to have more documentation on how to chanhe the Id types. There is no documentation about and no working example using TKey.

The process is explained in the README.md and what you have should work.

I tested locally and it worked fine. Consider posting uploading a repro on GitHub and I'll take a look.

**Comment by ghost** [comment]
Here is the basic code example using int as primary key 
https://github.com/alespab/openiddict-replacing-primary-key

Note that I tried different variants, and none works. Similar code works fine with version 1. The problem comes with version 2 giving any kind of error.

**Comment by cristian-eriomenco** [comment]
Was this solved? I get same issue but using it as a Guid instead of int.

**Comment by kevinchalet** [comment]
@cristian-eriomenco AFAICT, there was no issue on my side. What's the actual exception you're seeing?
