### ISSUE TITLE
Cannot use custom schema

### ISSUE THREAD

**Issue by jmelosegui** [openiddict/openiddict-core#669]
Hi, 

I am using version RC3 and I want to change the tables to a custom schema `Security`

I have the following code in the method `OnModelCreating(ModelBuilder modelBuilder)`

```CSharp
            modelBuilder.Entity<OpenIddictApplication<int>>()
                        .ToTable("OpenIddictApplications", "Security");

            modelBuilder.Entity<OpenIddictAuthorization<int>>()
                        .ToTable("OpenIddictAuthorizations", "Security");

            modelBuilder.Entity<OpenIddictScope<int>>()
                        .ToTable("OpenIddictScopes", "Security");

            modelBuilder.Entity<OpenIddictToken<int>>()
                        .ToTable("OpenIddictTokens", "Security");
```

I have also using the models in the new `OpenIddict.EntityFrameworkCore.Models` namespace.

When running the application I get the following error

> System.Data.SqlClient.SqlException: 'Invalid object name 'OpenIddictScopes'.'

![image](https://user-images.githubusercontent.com/450246/45930606-60502280-bf30-11e8-8e93-b753257f6b66.png)

Tables are in the correct schema in the database

![image](https://user-images.githubusercontent.com/450246/45930920-18cb9580-bf34-11e8-87a9-2295ffa61ae8.png)

**Comment by kevinchalet** [comment]
Hey,

Hard to say what's going on. Could you try to revert the tables names back to their original names to see if the message disappears? If anything, it would likely be an EF Core issue, as we don't deal with schema names ourselves.

**Comment by brett-m** [comment]
I have done exactly the same as @jmelosegui and renamed the tables to a custom schema.

@PinpointTownes , I can confirm that renaming the tables back to the original names that it works; that is the error goes away.

The error is occurring in in OpenIddict.EntityFrameworkCore.OpenIddictScopeStore in method FindByNameAsync.

**Comment by kevinchalet** [comment]
@brett-m unfortunately, I'm not able to reproduce the error locally: I tested with migrations and without and it worked flawlessly in both cases.

Any chance you could upload a repro?
