### ISSUE TITLE
ResolveContextType : Sequence contains more than one element

### ISSUE THREAD

**Issue by DarrenARBell** [openiddict/openiddict-core#67]
Hi
I'm customizing the OpenIddictStore by inheriting from it. And I believe that this is causing the issue. What's my best approach to solving it. One solution would be to use `FirstOrDefault()` instead of `SingleOrDefault()` in the method  `private static Type ResolveContextType([NotNull] OpenIddictServices services)` but I dont believe this is the correct approach as its just hiding the fact there seem to be two stores. Is there a way to clear the original store from the services and just replace it with my customized store.

Regards

**Comment by kevinchalet** [comment]
Hey and thanks for reporting this bug :clap: 

I guess you're calling `UseEntityframework()` from `AddOpenIddictCore(config => { ... })`?
If yes, then it's expected, as it only works with the built-in instance.
To register a custom store, you must use the DI extensions (`AddScoped` in this case).

That said, that's something I'll improve. I'll push a big PR adding a `UseStore` method to easily register a custom store soon :clap:

**Comment by DarrenARBell** [comment]
Hi. Yes I am in deed calling `UseEntityFramework()`. I've given the `AddScoped` a bash and that seems to be working for me. 
Thanks for the library and the help!

**Comment by kevinchalet** [comment]
> Thanks for the library and the help!

Thanks! :smile: 

Fixed as part of https://github.com/openiddict/openiddict-core/commit/5899533ae7028a30cb126de38713b7d8793ca653.
