### ISSUE TITLE
Add claim on access_token by api 

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#671]
I want to create a service to only authenticate users in different softwares(products). The openiddict will only have basic user information, ID, Name, Email, Password.
For each software will have its API and also a table called UserInfo that will have additional user information

How do I add custom claims in access_token after authenticated by the openiddict?

**Comment by kevinchalet** [comment]
I'm not sure what's the point of your question as you recently declared you were using IdSrv and posted exactly the same question on their repo yesterday.

I hope you don't think I have time to waste answering fake questions?

**Comment by marcrib** [comment]
Hello @PinpointTownes 

Yes, I also asked the same question in Idsrv
As described, I want to have a single microservice for user authentication for several different softwares.

All my searches so far have been with Idsrv, but OpenIddict seems easier to implement and more complete examples.

Also the support and answers are faster, clearly you care more about the project

Sorry, I did not mean to offend you or make you lose time.

**Comment by rodrigocezar** [comment]
Use a custom event handler

https://kevinchalet.com/2018/07/02/implementing-advanced-scenarios-using-the-new-openiddict-rc3-events-model/

**Comment by marcrib** [comment]
@rodrigocezar  ResourceAPI include the claims iand not the openIddict

**Comment by kevinchalet** [comment]
With OpenIddict, you're responsible of creating the `ClaimsIdentity`/`ClaimsPrincipal` used to create tokens. To support your scenario, you'd just have to add new claims here: https://github.com/openiddict/openiddict-samples/blob/dev/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L84-L91

```csharp
var identity = (ClaimsIdentity) principal.Identity;
identity.AddClaim(new Claim(...));
```

**Comment by marcrib** [comment]
@PinpointTownes how my resource api add claim in access_token?

**Comment by kevinchalet** [comment]
Resource APIs don't issue tokens so your question makes no sense: it's the authorization server that produces tokens and I showed you how you can add custom claims.
