### ISSUE TITLE
Multi tenant guidance (in relation to different auth types such as Facebook, Azure AD etc)

### ISSUE THREAD

**Issue by tjpeel** [openiddict/openiddict-core#672]
I would like to configure OpenIddict so that different authentication types (Facebook, Azure AD etc) can be configured by tenant.

I have referenced this guidance - https://stackoverflow.com/a/49682427/31412 - and have path based tenants running, which works well.

Each tenant might have different authentication types configured and they should be configured at runtime. They cannot be added during startup and there may be multiple Facebook logins for example so the authentication scheme name will need to be unique.

How might this requirement be configured within OpenIddict please?

I have noted these sources whilst reviewing potential options:

https://github.com/aspnet/Security/issues/1179#issuecomment-295904139
https://github.com/aspnet/AuthSamples/tree/master/samples/DynamicSchemes
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.OpenId

I believe the OrchardCore.OpenId supports this requirement so any direct links into the module's source would help cut through some of the Orchard specific configuration that I'm not familiar with.

Many thanks

**Comment by tjpeel** [comment]
I've looked briefly at the Orchard source in relation to the OpenID options and can't see much difference in what I have running in my project (based on the tenant config from SO link above).

I think the resultant work for this is what I would need?

https://github.com/OrchardCMS/OrchardCore/issues/2029

**Comment by kevinchalet** [comment]
> I've looked briefly at the Orchard source in relation to the OpenID options and can't see much difference in what I have running in my project (based on the tenant config from SO link above).

OrchardCore achieves multitenancy by having a separate DI container per tenant, which is very different from what I described in my SO post, that uses a single DI container for everything, but different options instance per tenant.

If you want to use Facebook/Azure AD with OpenIddict and adopt the same pattern as the one described in the SO thread, you definitely can. You'd have to create custom `IOptionsMonitor<Facebook>`/`IConfigureNamedOptions<FacebookOptions>` exactly like I did for the OpenIddict server options.

**Comment by tjpeel** [comment]
@PinpointTownes thanks for getting back to me.

> If you want to use Facebook/Azure AD with OpenIddict and adopt the same pattern as the one described in the SO thread, you definitely can. You'd have to create custom `IOptionsMonitor<Facebook>`/`IConfigureNamedOptions<FacebookOptions>` exactly like I did for the OpenIddict server options.

I think this is fine if a specific auth type is available all the time, but if one tenant has it enabled and another tenant doesn't then the configuration convention becomes a little counter intuitive. As you can't remove it once configured. You're left with having to fake it and configure dummy required data and then never let it be used in the UI. Unless I'm unaware of a better way round this?

I got round it by using `IAuthenticationSchemeProvider.AddScheme` on startup and loading all auth types for all tenants (currently a small number of tenants so negligible being run for all).

```
public class CompanyTenantInitialiser
{
    private readonly IAuthenticationSchemeProvider _authenticationSchemeProvider;
    private readonly IOptionsMonitorCache<FacebookOptions> _facebookOptionsMonitorCache;
    private readonly IPostConfigureOptions<FacebookOptions> _facebookPostConfigureOptions;
    private readonly IOptionsMonitorCache<OpenIdConnectOptions> _openIdConnectOptionsMonitorCache;
    private readonly IPostConfigureOptions<OpenIdConnectOptions> _openIdConnectPostConfigureOptions;
    private readonly ICompanyRepository _companyRepository;

    public CompanyTenantInitialiser(
        IAuthenticationSchemeProvider authenticationSchemeProvider,
        IOptionsMonitorCache<FacebookOptions> facebookOptionsMonitorCache,
        IPostConfigureOptions<FacebookOptions> facebookPostConfigureOptions,
        IOptionsMonitorCache<OpenIdConnectOptions> openIdConnectOptionsMonitorCache,
        IPostConfigureOptions<OpenIdConnectOptions> openIdConnectPostConfigureOptions,
        ICompanyRepository companyRepository)
    {
        _authenticationSchemeProvider = authenticationSchemeProvider;
        _facebookOptionsMonitorCache = facebookOptionsMonitorCache;
        _facebookPostConfigureOptions = facebookPostConfigureOptions;
        _openIdConnectOptionsMonitorCache = openIdConnectOptionsMonitorCache;
        _openIdConnectPostConfigureOptions = openIdConnectPostConfigureOptions;
        _companyRepository = companyRepository;
    }

    public async Task Init()
    {
        var companies = await _companyRepository.GetAll();

        foreach (var company in companies)
        {
            AddFacebook(company);
            AddAzureActiveDirectory(company);
        }
    }

    private void AddAzureActiveDirectory(Company company)
    {
        foreach (var authScheme in company.AuthSchemes.Where(
            x => x is AzureActiveDirectoryAuthScheme).Cast<AzureActiveDirectoryAuthScheme>())
        {
            var name = $"{company.Domain}-{authScheme.Name}";

            _authenticationSchemeProvider.AddScheme(new AuthenticationScheme(name, authScheme.DisplayName, typeof(OpenIdConnectHandler)));

            // As a general configuration rule, the app manifest in Azure should be changed so that:
            // 
            // "groupMembershipClaims": null,
            // ... becomes ...
            // "groupMembershipClaims": "SecurityGroup",
            //
            // This will then return groups

            var options = new OpenIdConnectOptions
            {
                ClientId = authScheme.ClientId,
                Authority = $"https://login.microsoftonline.com/{authScheme.TenantId}",
                UseTokenLifetime = true,
                CallbackPath = $"/signin-azureactivedirectory-{company.Domain}",
                // This should be dev server only, all prod should be secure
                RequireHttpsMetadata = false,
                // This is taken from the AddCookie call in Startup
                SignInScheme = Constants.AuthCookie.External
            };
            
            // This is simulating what the dotnetcore configuration architecture does
            _openIdConnectPostConfigureOptions?.PostConfigure(name, options);

            _openIdConnectOptionsMonitorCache.TryAdd(name, options);
        }
    }

    private void AddFacebook(Company company)
    {
        foreach (var authScheme in company.AuthSchemes.Where(
            x => x is FacebookAuthScheme).Cast<FacebookAuthScheme>())
        {
            var name = $"{company.Domain}-{authScheme.Name}";

            _authenticationSchemeProvider.AddScheme(new AuthenticationScheme(name, authScheme.DisplayName, typeof(FacebookHandler)));

            var options = new FacebookOptions
            {
                AppId = authScheme.ClientId,
                AppSecret = authScheme.ClientSecret,
                CallbackPath = $"/signin-facebook-{company.Domain}",
                // This is taken from the AddCookie call in Startup
                SignInScheme = Constants.AuthCookie.External
            };

            // This is simulating what the dotnetcore configuration architecture does
            _facebookPostConfigureOptions?.PostConfigure(name, options);

            _facebookOptionsMonitorCache.TryAdd(name, options);
        }
    }
}
```

The above supports Facebook and Azure AD. Additional service registrations are needed as per the dotnetcore startup `Add*(...)` calls for each auth type:

```
services.TryAddSingleton<IPostConfigureOptions<FacebookOptions>, OAuthPostConfigureOptions<FacebookOptions, FacebookHandler>>();
services.TryAddSingleton<IPostConfigureOptions<OpenIdConnectOptions>, OpenIdConnectPostConfigureOptions>();
```

And you can see the options generated being added to their respective caches, which are used when the auth type is selected in the UI.

```
IOptionsMonitorCache<FacebookOptions>
IOptionsMonitorCache<OpenIdConnectOptions>
```

This only problem with this approach is that it's circumventing the dotnetcore configuration model. If I use the `services.AddAuthentication(...).AddFacebook(...).AddOpenIdConnect(...)` methods then the relevant services are registered in DI without me needing to know about it. The solution I have is that I need to monitor future dotnetcore changes and replicate any subtle additions that might be added to the configuration process, if that makes sense?

But then the flip side is that I don't think I can do what I want any other way so it's a point I might have to live with.

**Comment by kevinchalet** [comment]
> As you can't remove it once configured. You're left with having to fake it and configure dummy required data and then never let it be used in the UI. Unless I'm unaware of a better way round this?

In theory, you could do something like that:

```csharp
services.AddAuthentication().AddFacebook();
services.Configure<AuthenticationOptions>(options => options.SchemeMap.Remove("Facebook"));
```

Sadly, this just won't work because `AuthenticationOptions` actually maintains 2 disconnected collections ; so even if you remove the scheme from the dictionary, the scheme will be registered anyway: https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Authentication.Abstractions/AuthenticationOptions.cs

> The solution I have is that I need to monitor future dotnetcore changes and replicate any subtle additions that might be added to the configuration process, if that makes sense?

What you have is fine and quite similar to what we do in OrchardCore. The only difference is that we register an `IConfigureOptions<AuthenticationOptions>` instead of using `IAuthenticationSchemeProvider`: https://github.com/OrchardCMS/OrchardCore/blob/7f96af08e60c31944f83e8c7bdb0ce34424f5bb2/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs#L57-L86

**Comment by tjpeel** [comment]
Thanks, that's a great help.

**Comment by tjpeel** [comment]
Thanks, that's a great help.

**Comment by tjpeel** [comment]
@PinpointTownes actually, sorry, your final comment:

> What you have is fine and quite similar to what we do in OrchardCore. The only difference is that we register an `IConfigureOptions<AuthenticationOptions>` instead of using `IAuthenticationSchemeProvider`

How would this help as the `IConfigureOptions<AuthenticationOptions>` implementation would only be called if I made a call to `AddFacebook()` or `AddGoogle()` etc? This is different to me using `IAuthenticationSchemeProvider`.

Or am I missing something?

Thanks

**Comment by kevinchalet** [comment]
> How would this help as the IConfigureOptions<AuthenticationOptions> implementation would only be called if I made a call to AddFacebook() or AddGoogle() etc?

No, `IConfigureOptions<AuthenticationOptions>` is always called, even if you don't use `AddFacebook()`. 

FWIW, registering an `IConfigureOptions<AuthenticationOptions>` is pretty much what `AddFacebook()` and similar extensions do under the hood.

**Comment by tjpeel** [comment]
> No, `IConfigureOptions<AuthenticationOptions>` is always called, even if you don't use `AddFacebook()`.

Yes, can see it's called, apologies. But I still think I'm missing something in my understanding.

Considering this:

```
public class CompanyTenantConfiguration : 
    IConfigureOptions<AuthenticationOptions>, 
    IConfigureNamedOptions<FacebookOptions>
{
    private readonly ICompanyRepository _companyRepository;

    public CompanyTenantConfiguration(ICompanyRepository companyRepository)
    {
        _companyRepository = companyRepository;
    }

    public void Configure(AuthenticationOptions options)
    {
        var companies = _companyRepository.GetAll().GetAwaiter().GetResult();

        foreach (var company in companies)
        {
            foreach (var authScheme in company.AuthSchemes.Where(
                x => x is FacebookAuthScheme).Cast<FacebookAuthScheme>())
            {
                var name = $"{company.Domain}-{authScheme.Name}";

                options.AddScheme<FacebookHandler>(name, authScheme.DisplayName);

                /*
                _authenticationSchemeProvider.AddScheme(new AuthenticationScheme(name, authScheme.DisplayName, typeof(FacebookHandler)));

                var options = new FacebookOptions
                {
                    AppId = authScheme.ClientId,
                    AppSecret = authScheme.ClientSecret
                };

                // This is simulating what the dotnetcore configuration architecture does
                _facebookPostConfigureOptions?.PostConfigure(name, options);

                _facebookOptionsMonitorCache.TryAdd(name, options);
                */
            }
        }
    }

    public void Configure(FacebookOptions options) => Debug.Fail("Method should not be called");

    public void Configure(string name, FacebookOptions options)
    {
        // Would check name is one we have added above
        // Then configure the Facebook options
    }
}
```

The above adds the Facebook handler for each company who has a corresponding Facebook auth scheme enabled. 

I have also added the following to my startup class:

```
services.AddSingleton<IConfigureOptions<AuthenticationOptions>, CompanyTenantConfiguration>();
services.AddSingleton<IConfigureNamedOptions<FacebookOptions>, CompanyTenantConfiguration>();
```

But the Configure call of FacebookOptions is never called, as I have never defined any FacebookOptions alongside adding the scheme.

Also, the `AddFacebook()` framework call deals with adding the post configure options to DI so I would still need to do all this myself.

All in all I can't see how much different (or the benefit of) this approach is to the way I was doing it before with `IAuthenticationSchemeProvider`. I do find the APIs a little counter intuitive to be honest.

**Comment by kevinchalet** [comment]
> But the Configure call of FacebookOptions is never called, as I have never defined any FacebookOptions alongside adding the scheme.

Replace:

```csharp
services.AddSingleton<IConfigureNamedOptions<FacebookOptions>, CompanyTenantConfiguration>();
```
... by

```csharp
services.AddSingleton<IConfigureOptions<FacebookOptions>, CompanyTenantConfiguration>();
```

> Also, the AddFacebook() framework call deals with adding the post configure options to DI so I would still need to do all this myself.

Sure. Did I say something that made you think otherwise?

> All in all I can't see how much different (or the benefit of) this approach is to the way I was doing it before with IAuthenticationSchemeProvider.

If you're happy with `IAuthenticationSchemeProvider`, don't hesitate to use it (I just suggested a different approach that I personally prefer).

**Comment by tjpeel** [comment]
Thanks again for your assistance. And didn't mean to infer any problems with what you had suggested, I was just trying to understand the second approach (hope I didn't cause offence). I've got an example working now based on the change you noted.

From my review/research/testing of OAuth2/OpenID Connect servers/frameworks, OpenIddict has been the best to work with, most logical to implement/customise and most intuitive considering the API/framework it exposes. As such, it has been selected as the auth server in my current consulting role.

All the best and thanks again :)
