### ISSUE TITLE
Using openiddict with android/ios native apps keeping user logged in

### ISSUE THREAD

**Issue by GuidoNeele** [openiddict/openiddict-core#674]
What is the best way to use openiddict with ios/android native apps that need to keep the user logged in at all time? I would like the following:
1. User opens the app for the first time.
2. User needs to login using username and password + 2fa
3. User is logged in and receives token
4. Token is used to call api
5. User closes app and returns 5 days later
6. Token is used to call api
7. etc

What's the best way to set this up?
Thanks

**Comment by marcrib** [comment]
hi @GuidoNeele 
This is a logic that you should determine in your android application / ios
Openiddict provides the token and refresh token

In android you have the following methods to store your token
https://developer.android.com/guide/topics/data/data-storage

**Comment by GuidoNeele** [comment]
> hi @GuidoNeele
> This is a logic that you should determine in your android application / ios
> Openiddict provides the token and refresh token
> 
> In android you have the following methods to store your token
> https://developer.android.com/guide/topics/data/data-storage

Hi @marcrib,

Yes I understand. But what is the best practice in this case? Short lived access tokens and long lived refresh tokens (6 months/1 year) based on client_id? Get a new access token each time the user opens the app?
If I extend the lifetime of the refresh token by that much it probably would be good (for extra security) to tie the token with the device ID, right? 

It also would be nice to show the users their current logins and active devices on profile page so they can revoke their refresh tokens, which will force them to login the next time when they open the app.

I'm missing some guidance/best practice for this type of security.

**Comment by Bartmax** [comment]
@GuidoNeele I think best practice is to have short lived access tokens and long lived refresh token.

My logic is simple as this:
Access tokens have access to the app / data, you normally don't validate the access token on every request, on the other hand, you can always validate when issuing a refresh token.

So if you want to prevent a user for accessing the system for whatever reason, or the access token got leaked you just invalidate it at the server and you don't re-issue a new token when refresh is requested.

In terms of "how much" i think on the lines of: short lived access tokens (days) and long lived refresh tokens, (whatever make sense for a user not using the app in x period of time to re enter credentials, I think in the x months space, not years)
