### ISSUE TITLE
OpenIddict for multiple applications - one central place for authentication 

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#675]
I want to create a scenario like this image

![0003](https://user-images.githubusercontent.com/31016251/46772762-00979c80-ccd0-11e8-99e3-098e70e031ba.png)
_(Image from google)_

The three applications are mult tenant with different business logic and all my tables contains a TenantId column to be filtered, dbo.Products.Where (x => x.TenantId == MyTenantId)
In each application the user may have a different TenantId

My question are:

1 - Can I use openIddict in this scenario?
2 - Who should store and return the TenantId?
3 - Who should provide authorization for the user to be able to access a particular application?

Congratulations @PinpointTownes , your project is objective and very easy to implement.

I spent days studying identityserver and openiddict. By far OpenIddict is much simpler and easier, it's a really opensource project with the purpose of helping the community. I thank you for your effort.

I'd like to know if there's any way I can help you with some documentation or anything.I do not have technical knowledge for new implementations

**Comment by kinosang** [comment]
If you use the interactive flow, users are redirected to the OpenId Connect when login from the apps, you can filter the authentication requests on the side of OpenIddict to prevent users from unauthorized app (e.g. throw an exception in `AuthorizationController.Authorize`) and return the TenantId within the AccessToken and/or IdToken.

For password flow, just filter the requests in the token endpoint.

**Comment by marcrib** [comment]
> If you use the interactive flow, users are redirected to the OpenId Connect when login from the apps, you can filter the authentication requests on the side of OpenIddict to prevent users from unauthorized app (e.g. throw an exception in `AuthorizationController.Authorize`) and return the TenantId within the AccessToken and/or IdToken.
> 

But how Auth server will return the Tenant? In each application the user may have a different TenantId
This is my biggest doubt.

I thought about having a project that handles subscription/payment/tenant and users. This way I could control all the rules (subscription/payment/tenant) and return the token

But in several surveys they say that the authserver should only be authserver (only user data and token)

I think wrong?

**Comment by kinosang** [comment]
Create your own tables in your database (the database of your OpenIddict server) to store the TenantId, ApplicationId, and the UserId, btw, create an API for your applications (with client credentials grants) to manage the TenantId.

**Comment by marcrib** [comment]
> Create your own tables in your database (the database of your OpenIddict server) to store the TenantId, ApplicationId, and the UserId, btw, create an API for your applications (with client credentials grants) to manage the TenantId.

I assume that the project that will use OpenIddict will do much more than just user authentication, sure?

**Comment by kinosang** [comment]
> I assume that the project that will use OpenIddict will do much more than just user authentication, sure?

It's also provide the APIs, or you can create a standalone Resource Provider project to do that. On a RP, you can validate the access tokens via the Introspection Endpoint.

For more information about the IdP (Identity Provider), RP (Resource Provider) and the client, have a look at https://www.oauth.com
