### ISSUE TITLE
Tkey of Int or Guid not working on ReplaceDefaultEntities

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#676]
Here is the basic code example using int as primary key
https://github.com/alespab/openiddict-replacing-primary-key

Note that I tried different variants, and none works. Similar code works fine with version 1. The problem comes with version 2 of openIdDict which is giving any kind of error.

**Comment by kevinchalet** [comment]
It works like a charm on my machine (except I had to manually update the .csproj as it referenced a .props file not present in the project, which is a simple copy of the password sample and not a repro of your own).

As I said last time, without a complete strack trace, it's impossible to help you.
