### ISSUE TITLE
How are tokens regenerated without logging back in

### ISSUE THREAD

**Issue by davebat** [openiddict/openiddict-core#679]
Hi,

This is less of an issue and more of a query of what is going on behind the scenes, if this would be more suitable for StackOverflow please let me know.

I have a separate client MVC app, a Web Api resource server and authorization server, set up to support the code flow as in the sample provided. I am also using the JWT token format for my access and identity tokens. 

Everything is working nicely, but I have encountered the following which i don't quite understand.

I set a very short time span of 45 seconds on my authentication cookie that is set on the MVC client after a successful OpenId challenge. Once this expires if i refresh the page I am redirected to the auth server which issues a brand new set of tokens, but it does this without requiring me to log back in.

Why does it issue new tokens without a further challenge? I can see in the code it authenticates against the ASOS scheme, is it using the original authorization code to re-issue the tokens, and if so how long is that valid for?

If not how does it authenticate again without re-entering credentials?

Thanks

**Comment by kevinchalet** [comment]
Hey,

> If not how does it authenticate again without re-entering credentials?

You probably didn't realize it - since it's set up for you by `services.AddIdentity()` - but the MVC server sample also uses cookies authentication (separate from the MVC client cookie). It's precisely what keeps the "user session" alive and allows skipping the authentication screen.

To control the duration, you can use the standard Identity extensions:

```csharp
services.ConfigureApplicationCookie(options => { ... });
```

**Comment by davebat** [comment]
Thankyou for your quick response, I had missed that, makes perfect sense now. 

Cheers
