### ISSUE TITLE
No way to generate token on behalf of user

### ISSUE THREAD

**Issue by garyapps** [openiddict/openiddict-core#680]
I cannot find a way to generate a token on behalf of a user in my asp.net core web app. How can I generate bearer tokens inside a controller action and return it as part of a view when when using openiddict?

To provide some background -
I am building an asp core website which uses the built in asp identity authentication system. This provides cookie based authentication. The user logs in and can then navigate to member only parts of the site. The site also has an api (developed as part of the same project) which will be used by JavaScript Ajax calls from the pages of the site. So the website is the consumer of its own api. 

I would like to use bearer tokens to authenticate these api calls from the web pages. However I am unable to figure out how to get a bearer token for the already logged in user. Ideally I would get the bearer token in the controller action, and then inject into the code of the view (maybe as a hidden field or directly into the JavaScript code itself), so that it can be used by the JavaScript code that makes the ajax calls to the api. 

Unfortunately the only method I can figure out to get a token is to have the user (who is already logged in) enter their username and password one again on the page, and then make a call to the openiddict token endpoint using these credentials in order to obtain a token. This is not a good flow since a logged in user should not have to reenter their credentials. 

How does one directly get the bearer token on the server side before rendering the page so that it can be directly injected into the page’s code? Is this functionality not exposed, and if so are their plans to do this? (Note that I do not have access to the user’s passwords either, since these are stored in hashed form in the database).  

If openiddict is not the correct tool for this job, and is only intended for third party api access, please let me know, and I apologize for the confusion. (Do feel free to suggest an alternative approach if anyone knows one).

**Comment by kevinchalet** [comment]
Generating tokens yourself is something you could do, but it's really not the right solution to your demand.

For the kind of hybrid server-side/SPA apps you describe, I'd probably go with an interactive flow like code and configure the MVC app to use the OIDC client handler developed by MSFT. To make the access token accessible to the JS front-end, you could do something like that and expose it via the Razor view: https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Client/Controllers/HomeController.cs#L32

**Comment by PatrikTrestik** [comment]
Hi. I need this functionality for our legacy OWIN base app. What I need is exactly same as in provided sample (HomeController.cs) but in OWIN environment.
Is it possible?

Other option is to generate access token from ClaimsPrincipal. I also do no know how to do it.
