### ISSUE TITLE
Should openiddict be in a separate project ?

### ISSUE THREAD

**Issue by ghost** [openiddict/openiddict-core#681]
It's a more a question than an issue. I am new to the whole identity server world.

I'd like to start from scratch a new web app with an UI (mvc), a backend (webapi) and a database.
Nothing fancy. All in asp.net core.

Usually, I use the System.IdentityModel.Tokens.Jwt package on both ui and backend. I have a login an register views. The controller tied to them calls the backend which will generate and issue a bearer. This token will be inspected and validated by the UI (jwt middleware). 

At this point, authorization on the UI is handled.

Whenever a new call to the backend by the UI is needed, the UI will add the bearer to the header so the the backend will authorize based on it.

The backend and ui have the same validations options.

Questions :
- Does oppeniddict seat inside the webapi ? Or it should be another project in the solution ?
- Does opeeniddict seat also in the UI to handle external logins ? 

I can't find online a clear definition of all of those flows :

    Authorization code flow sample
    Implicit flow sample
    Password flow sample
    Client credentials flow sample
    Refresh flow sample

Can I have a one line use case example ?

I hate asp.net identity because it forces the UI to access the database directly.

Thanks a lot !

**Comment by kevinchalet** [comment]
> Does oppeniddict seat inside the webapi ? Or it should be another project in the solution ?

Both options are possible. If you have a few first-party clients, no need to have it in a separate project. If you plan to have many third-party clients and expect a more intense workload, you may want to consider putting it in a dedicated app.

> Does opeeniddict seat also in the UI to handle external logins ?

OpenIddict by itself doesn't handle the external login step, but in general, you'll let Identity and its account controllers (or built-in Razor Pages UI in 2.1) handle the authentication - internal or external - before the user is redirected back to the OpenIddict authorization controller to finalize the authorization process.

> Can I have a one line use case example ?

https://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-choosing-the-right-flows/

**Comment by ghost** [comment]
Thanks for all the pointers.
I feel that the security I am trying to put in place is too much.

I am planning to just add cookie authentication on the web client with some socials authentication too. 
I'll save those user datas using the api without security (they are all in the same secured network).

The web app is not an SPA. 

Am i wrong ?

**Comment by promising1** [comment]
Hi @kevinchalet,
On that same note, I wasn't able to find an example of controllers using the `[Authorize]` attribute within the same scope of OpenIddict, can you point me in the right direction?

We have an authority service, using OpenIddict, to manage authorization/authentication for our ecosystem. This part works perfectly. But, internally (within the same project as OpenIddict), we have a few controllers we expose to manager users, permissions, roles and applications. How do we set those to use the token?

**Comment by smargoli2** [comment]
@kevinchalet , are any of the samples set up with OpenIddict in a separate project? I would love to see an example of that for reference.
