### ISSUE TITLE
Client scope permissions are not checked as expected on version 2.0.0-rc3-final

### ISSUE THREAD

**Issue by nurhat** [openiddict/openiddict-core#682]
Hi,

With password grant type, clients can request any registered scope even if the permission for the scope is not given. Is it an issue with the release or sth else. When I investigate the part of code , it seems it should work as expected.

Thx.
Nurhat

**Comment by kevinchalet** [comment]
Hey,

Thanks for reporting this security issue, which causes scope permissions to be ignored for public clients (confidential clients are not impacted).

I'll take care of fixing it and make sure it's included in the RTM release.

Thanks!

**Comment by kevinchalet** [comment]
Fixed by https://github.com/openiddict/openiddict-core/commit/e7c4942777984d677b745af90a25c9352ac90cf7.

New nightly builds should be pushed to MyGet.org within in the next minutes.

Thanks again for reporting it :+1:

**Comment by nurhat** [comment]
Thank you for the quick fix,  when it will be released on nuget.org?
