### ISSUE TITLE
"cannot insert NULL values in the Status column" error since update 1135

### ISSUE THREAD

**Issue by alejandronic** [openiddict/openiddict-core#685]
Hi, I', using openIddict in my app made in core2.0/angular.
Since version 2.0.0-rtm-1135 update I can't update my database with the last migration created, because i get this error:
You can not insert the NULL value in the 'Status' column, table 'Salud.dbo.OpenIddictTokens'. The column does not support NULL values. UPDATE error.
I checked Status column and there is several rows with null value in it with different dates.
How can i solve this problem being able to continue updating this dependencie?
Thank you very much.

**Comment by kevinchalet** [comment]
Hey,

> I checked Status column and there is several rows with null value in it with different dates.
How can i solve this problem being able to continue updating this dependencie?

This property was never supposed to be nullable and we started setting the default status to `valid` in February. In the RTM bits, we're going to fix this oversight and make the column non-nullable.

To solve your issue, simply assign a value - e.g `valid` - to the null entries before executing the migration. E.g using SQL Server:

```sql
UPDATE [dbo].[OpenIddictAuthorizations]
SET [Status] = N'valid'
WHERE [Status] IS NULL
```

You may also want to execute `OpenIddictAuthorizationManager.PruneAsync` to get rid of obsolete entries.

**Comment by alejandronic** [comment]
Thank you for the quick response.
I didn't want to update the database without asking you first.
I'm using openIddict 2.0 since around november 2017.
I did what you said and it worked.
Thanks again.
