### ISSUE TITLE
Roadmap of the Stable release of version 2.0 and new features

### ISSUE THREAD

**Issue by a-patel** [openiddict/openiddict-core#686]
What is the estimated date of the Stable release of version 2.0?
And new features and major changes?
How it will handle refresh token scenario?
Which .NET Core framework support?

**Comment by kevinchalet** [comment]
> What is the estimated date of the Stable release of version 2.0?

Later today, with 1.0.0 too.

> And new features and major changes?

Compared to RC3? Nope, mostly bug fixes and some improvements based on internal and external feedback.

> How it will handle refresh token scenario?

Same way as previous iterations.

> Which .NET Core framework support?

OpenIddict 1.0 runs on >.NET Framework 4.5 and >.NET Core 1.0.
OpenIddict 2.0 runs on >.NET Framework 4.6.1 and >.NET Core 2.0.

**Comment by a-patel** [comment]
@PinpointTownes thanks.

**Comment by kevinchalet** [comment]
https://kevinchalet.com/2018/11/01/openiddict-1-0-and-2-0-general-availability/
