### ISSUE TITLE
Use more meaningful message for ValidatePostLogoutRedirectUriAsync 

### ISSUE THREAD

**Issue by ahanoff** [openiddict/openiddict-core#687]
@PinpointTownes thanks for amazing library.

Today I tried to logout using post_logout_redirect_uri parameter and got the following message:

> The specified 'post_logout_redirect_uri' parameter is not valid.

but after review the source code, I figure out that the actual reason was my client permissions. I had to simply add logout permission:

`OpenIddictConstants.Permissions.Endpoints.Logout`

Is it possible for ValidatePostLogoutRedirectUriAsync function throw more meaningful exception? Thank you!

**Comment by kevinchalet** [comment]
> @PinpointTownes thanks for amazing library.

Thanks for the kind words! :+1: 

> Is it possible for ValidatePostLogoutRedirectUriAsync function throw more meaningful exception? Thank you!

We can certainly update the log message to make that clearer. Would you like to send a PR?

**Comment by ahanoff** [comment]
@PinpointTownes I will do it next week, thanks
