### ISSUE TITLE
How can i register the ephemeral key in JWT bearer authentication on the auth server?

### ISSUE THREAD

**Issue by georgeonofrei** [openiddict/openiddict-core#688]
Hello,

First off I want to congratulate you on the great package that you are creating and the OAuth documentation that you have provided in various locations.

In my case, I have an openiddict server that is working fine and in development i am using ephemeral key. I would have liked to use symmetric key, but i am using implicit flow and it's not possible (exception is thrown during runtime).

The server needs to accept the token generated by itself, which brings up a problem in development because I need to provide to AddJwtBearer the above generated key.

The draft code is:
 

>            services.AddOpenIddict()
>                 .AddCore(options =>
>                 {
>                       ...
>                 })
>                 .AddServer(options =>
>                 {
>                     options.UseMvc();
>                     options
>                         .EnableAuthorizationEndpoint("/connect/authorize")
>                         .EnableUserinfoEndpoint("/api/user/info");
>                     .....
>                     options.AllowImplicitFlow();
>                     .....
>                     if (environment.IsDevelopment() || environment.IsTesting())
>                     {
>                         options.AddEphemeralSigningKey();
>                     }
>                     else
>                     {
>                         options.AddSigningCertificate(configuration["Server:Certificate"]);
>                     }
>                     var issuerRaw = configuration["Server:Issuer"];
>                     if (Uri.IsWellFormedUriString(issuerRaw, UriKind.Absolute))
>                     {
>                         options.SetIssuer(new Uri(issuerRaw));
>                     }
>                     .....
>                     options.UseJsonWebTokens();
>                 });
>             // beginning of workaround
>             SecurityKey key = null;
>             services.Configure<OpenIddictServerOptions>("ASOS", opt =>
>             {
>                 key = opt.SigningCredentials[0].Key;
>             });
>             // end of workaround
>             services.AddAuthentication(IdentityConstants.ApplicationScheme)
>                 .AddJwtBearer(options =>
>                  {
>                      var issuerRaw = configuration["Server:Issuer"];
>                      options.Authority = issuerRaw;
>                      options.Audience = "resource_server";
>                      options.RequireHttpsMetadata = false;
>                      options.TokenValidationParameters = new TokenValidationParameters();
>                      options.TokenValidationParameters.ValidateAudience = true;
>                      options.TokenValidationParameters.ValidateIssuer = true;
>                      options.TokenValidationParameters.ValidateLifetime = true;
>                      options.TokenValidationParameters.ValidateIssuerSigningKey = true;
>                      options.TokenValidationParameters.IssuerSigningKey = key;
>                      options.TokenValidationParameters.ValidIssuer = issuerRaw;
>                      .....
>                  })
>                 .AddIdentityCookies();

Currently I am using the highlighted workaround to get the generated key from the OpenIddictServerOptions. Unfortunately, the options.TokenValidationParameters.ValidateIssuerSigningKey = false; is not working, so I cannot deactivate this entirely. Furthermore, how can I go about this ephemeral key in development when other services need to validate the generated tokens?

Some somewhat related question is how can I set the correct AddJwtBearer Issuer+Authority without reading it from configuration. I think it's not really viable to automatically compute it from the server as it may be behind a LB during production, but I am more interested how other people are going around this.

Thanks,
George

**Comment by kevinchalet** [comment]
Hey,

> First off I want to congratulate you on the great package that you are creating and the OAuth documentation that you have provided in various locations.

Thanks for the kind words!

> In my case, I have an openiddict server that is working fine and in development i am using ephemeral key. I would have liked to use symmetric key, but i am using implicit flow and it's not possible (exception is thrown during runtime).

You can register multiple keys: symmetric keys will be preferred for access tokens, while only asymmetric keys will be used for identity tokens.

> Furthermore, how can I go about this ephemeral key in development when other services need to validate the generated tokens?

A super simple solution would be to populate the JWT options from the OpenIddict server options. Here's an example (it requires ASP.NET Core 2.1):

```csharp
services.AddOptions<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme)
    .Configure<IOptionsMonitor<OpenIddictServerOptions>>((options, monitor) =>
    {
        options.TokenValidationParameters.IssuerSigningKey =
            (from credentials in monitor.Get(OpenIddictServerDefaults.AuthenticationScheme).SigningCredentials
             select credentials.Key).First();
    });
```

> Some somewhat related question is how can I set the correct AddJwtBearer Issuer+Authority without reading it from configuration. I think it's not really viable to automatically compute it from the server as it may be behind a LB during production, but I am more interested how other people are going around this.

You could write and register a custom `IConfigureOptions<JwtBearerOptions>` taking an `IHttpContextAccessor` constructor dependency and inferring the authority from the host. But obviously it only works locally, not for resource servers hosted in separate apps.
