### ISSUE TITLE
Using the code flow sample how to get the clientId at Login

### ISSUE THREAD

**Issue by davebat** [openiddict/openiddict-core#689]
Hi,

I am extending identity to be multi tenanted, and as users will be separated by client the clientId seems ideal for this use. 

At the login screen on my auth server I would like to access the clientId of the request, but it doesnt seem to be available in the httpContext.

I looked at using  the following in my client

   options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = new CustomOpenIdConnectEvents(AuthConfig).RedirectToIdentityProvider
                };

but I cant see the clientId, how do I obtain it, I assume it must form part of the request? 

Thanks

**Comment by kevinchalet** [comment]
Hey,

For multi-tenancy, my recommendation is to go with a single OpenIddict/OpenID Connect client handler and multiple options, resolved per request:
  - https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login
  - https://stackoverflow.com/questions/52955238/how-can-i-set-the-authority-on-openidconnect-middleware-options-dynamically/52977687#52977687

If you prefer your approach, you can retrieve the client_id from the authorization endpoint using `request.ClientId`, assuming you inject `OpenIdConnectRequest` in your MVC action.

**Comment by davebat** [comment]
Thanks, I've got quite far along with the separate client approach now so will probably have to stick with that. 

I can access clientId in the authorize endpoint, but I would like to use this as part of the login process which is hit before.

PS - The more I've been using this framework the more impressed I am, its incredibly useful, thanks!

**Comment by kevinchalet** [comment]
If you want to keep using `[Authorize]` for your authorization endpoint, you can do something like that:

```csharp
services.ConfigureApplicationCookie(options => options.Events.OnRedirectToLogin = context =>
{
    // If the request is an OpenID Connect authorization request,
    // append the tenant identifier to the login page address.
    var request = context.HttpContext.GetOpenIdConnectRequest();
    if (request != null && request.IsAuthorizationRequest() &&
        request.HasParameter("tenant_id"))
    {
        context.RedirectUri = QueryHelpers.AddQueryString(context.RedirectUri,
            "tenant_id", (string) request["tenant_id"]);
    }

    context.Response.Redirect(context.RedirectUri);

    return Task.CompletedTask;
});
```

Alternatively, you can remove the `[Authorize]` attribute from your authorization endpoint and do that:

```csharp
services.ConfigureApplicationCookie(options => options.Events.OnRedirectToLogin = context =>
{
    // If a tenant identifier was attached to the challenge properties, update the login page URL.
    if (context.Properties.Items.TryGetValue("tenant_id", out string tenant))
    {
        context.RedirectUri = QueryHelpers.AddQueryString(context.RedirectUri, "tenant_id", tenant);
    }

    context.Response.Redirect(context.RedirectUri);

    return Task.CompletedTask;
});
```

```csharp
[HttpGet("~/connect/authorize")]
public async Task<IActionResult> Authorize(OpenIdConnectRequest request)
{
    // If the user is not logged in, trigger a challenge.
    var result = await HttpContext.AuthenticateAsync();
    if (result?.Principal == null)
    {
        var properties = new AuthenticationProperties();

        // If a tenant identifier was specified, store in the properties.
        var tenant = (string) request["tenant_id"];
        if (!string.IsNullOrEmpty(tenant))
        {
            properties.Items.Add("tenant_id", tenant);
        }

        return Challenge(properties);
    }

    // ...
}
```

**Comment by kevinchalet** [comment]
> PS - The more I've been using this framework the more impressed I am, its incredibly useful, thanks!

Glad you like it! :smile:

**Comment by davebat** [comment]
First approach works perfectly - thank you again for the assistance
