### ISSUE TITLE
Customization response of endpoint ```/connect/token```

### ISSUE THREAD

**Issue by TerraVenil** [openiddict/openiddict-core#692]
Hi! Is it possible to enhance response to endpoint ```/connect/token```, for example with additional field like ```expires_at``` which contains time of expiration not just a seconds (```expires_in```) as a recommended per OAuth2 spec? One of the pros for that to skip calculation logic on the client to track token expiration. Besides as I understand when response generated we already have current property. Also I think about introducing introspection point but would at be additional complexity to receive info about only one property ```expires_at```?

**Comment by javico2609** [comment]
i need too this feature, to change token_type for TokenType and access_token = AccessToken

**Comment by kevinchalet** [comment]
https://stackoverflow.com/questions/53261820/how-to-customize-the-authorization-error-produced-by-openiddict should put you on the right track.
