### ISSUE TITLE
OpenIddictApplication is not included in the model for the context

### ISSUE THREAD

**Issue by felipesantanadev** [openiddict/openiddict-core#693]
I have read similar issues in order to try solving my problem, but I didn't find any answer that could help me.

I'm trying to find an client application:

`var clientApplication = await _applicationManager.FindByClientIdAsync(client.ClientId);`

But I'm getting the error:

> Cannot create a DbSet for 'OpenIddictApplication' because this type is not included in the model for the context.

That is my configurations:

```
public static IServiceCollection ConfigureDatabase(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddEntityFrameworkNpgsql()
                    .AddDbContext<MillouContext>(options =>
                    {
                        options.UseNpgsql(configuration.GetConnectionString("PostgresConnection"));
                        options.UseOpenIddict<long>();
                    });

            return services;
        }

        public static IServiceCollection ConfigureIdentity(this IServiceCollection services)
        {
            services.AddIdentity<User, IdentityRole<long>>()
                    .AddEntityFrameworkStores<MillouContext>()
                    .AddDefaultTokenProviders();

            return services;
        }

        public static IServiceCollection ConfigureOpenIddict(this IServiceCollection services)
        {

            // Register the OpenIddict service
            services.AddOpenIddict()
                    .AddCore(options =>
                    {
                        // Configure OpenIddict to use the Entity Framework Core stores and entities.
                        options.UseEntityFrameworkCore()
                               .UseDbContext<MillouContext>()
                               .ReplaceDefaultEntities<long>();
                    })
                    .AddServer(options =>
                    {
                        // Register the ASP.NET Core MVC binder used by OpenIddict.
                        // Note: if you don't call this method, you won't be able to
                        // bind OpenIdConnectRequest or OpenIdConnectResponse parameters.
                        options.UseMvc();

                        // Enable the authorization and token endpoints (required to use the code flow).
                        options.EnableAuthorizationEndpoint("/auth/authorize")
                               .EnableLogoutEndpoint("/auth/logout")
                               .EnableTokenEndpoint("/auth/token")
                               .EnableUserinfoEndpoint("/api/userinfo");

                        // Allow client applications to use the code flow.
                        options.AllowAuthorizationCodeFlow();

                        // Allow client applications to use the grant_type=password flow.
                        options.AllowPasswordFlow();

                        options.AllowRefreshTokenFlow();

                        // During development, you can disable the HTTPS requirement.
                        options.DisableHttpsRequirement();

                        // Accept token requests that don't specify a client_id.
                        options.AcceptAnonymousClients();
                    })

                    // Register the OpenIddict validation handler.
                    // Note: the OpenIddict validation handler is only compatible with the
                    // default token format or with reference tokens and cannot be used with
                    // JWT tokens. For JWT tokens, use the Microsoft JWT bearer handler.
                    .AddValidation();

            return services;
        }
```
Those extensions are applied in my Web API:

```
public void ConfigureServices(IServiceCollection services)
        {
            services.ConfigureDatabase(Configuration);
            services.ConfigureIdentity();
            services.ConfigureOpenIddict();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }
```

I think OpenIddictDbContext is not longer in use, Am I right?

How could I solve the problem?

**Comment by frankvdb7** [comment]
I'm also receiving this error doing something like this in my application. Debugging shows that the OpenIddict models are indeed missing in the entity list of the datbase context.

**Comment by kevinchalet** [comment]
@itsfelipesan what's the type of the `_applicationManager` field? I suspect you're using `OpenIddictApplicationManager<OpenIddictApplication>` instead of `OpenIddictApplicationManager<OpenIddictApplication<long>>`.

If you don't care about the actual entity type, you can also use `IOpenIddictApplicationManager`, which is not generic.

@fmavdb you should post some code. Otherwise, it's hard to say what's going on.

**Comment by frankvdb7** [comment]
> @itsfelipesan what's the type of the `_applicationManager` field? I suspect you're using `OpenIddictApplicationManager<OpenIddictApplication>` instead of `OpenIddictApplicationManager<OpenIddictApplication<long>>`.
> 
> If you don't care about the actual entity type, you can also use `IOpenIddictApplicationManager`, which is not generic.
> 
> @fmavdb you should post some code. Otherwise, it's hard to say what's going on.

Adding OpenIddictApplication<long> works! It's very easy to overlook something like this, I'm glad it's solved, thanks!

**Comment by felipesantanadev** [comment]
> @itsfelipesan what's the type of the `_applicationManager` field? I suspect you're using `OpenIddictApplicationManager<OpenIddictApplication>` instead of `OpenIddictApplicationManager<OpenIddictApplication<long>>`.
> 
> If you don't care about the actual entity type, you can also use `IOpenIddictApplicationManager`, which is not generic.
> 
> @fmavdb you should post some code. Otherwise, it's hard to say what's going on.

You're right. The problem was the entity type. I thought we should specify it only during OpenIddict configuration.
