### ISSUE TITLE
Migration rollback failed

### ISSUE THREAD

**Issue by ddydeveloper** [openiddict/openiddict-core#694]
Good morning! 

I've updated the following packages: 
OpenIddict
OpenIddict.Core
OpenIddict.EntityFrameworkCore
OpenIddict.Mvc

2.0.0-rc3-final to "2.0.0

After I've created migration with the set of openiddict schema changes. Update-database was successfully but, unfortunately, I can't rollback to the previous migration, the error is: 

>  Failed executing DbCommand (20ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DECLARE @var6 sysname;
SELECT @var6 = [d].[name]
FROM [sys].[default_constraints] [d]
INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id]
WHERE ([d].[parent_object_id] = OBJECT_ID(N'[OpenIddictTokens]') AND [c].[name] = N'ReferenceId');
IF @var6 IS NOT NULL EXEC(N'ALTER TABLE [OpenIddictTokens] DROP CONSTRAINT [' + @var6 + '];');
ALTER TABLE [OpenIddictTokens] ALTER COLUMN [ReferenceId] nvarchar(max) NULL;

> The index 'IX_OpenIddictTokens_ReferenceId' is dependent on column 'ReferenceId'.
The index 'IX_OpenIddictTokens_ReferenceId' is dependent on column 'ReferenceId'.
ALTER TABLE ALTER COLUMN ReferenceId failed because one or more objects access this column.

The problem seems somewhere here:

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "ReferenceId",
                table: "OpenIddictTokens",
                maxLength: 100,
                nullable: true,
                oldClrType: typeof(string),
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "ReferenceId",
                table: "OpenIddictTokens",
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 100,
                oldNullable: true);
        }

I've tried to re-create index IX_OpenIddictTokens_ReferenceId but without any good results. Could you advise how to cope with it?

**Comment by kevinchalet** [comment]
Hey,

> Could you advise how to cope with it?

Honestly? No idea :smile:

I've tested the "normal" path and decided to revert some of the schema changes introduced in RTM to ensure everyone could migrate flawlessly, but I haven't tried the opposite way.

That said, all these changes are minor tweaks (mostly column length changes). You should be able to use the latest schema with OpenIddict RC3.

**Comment by ddydeveloper** [comment]
@PinpointTownes Hey, thank you for reply!

I hope there will be no needs to rollback the DB schema :) But just wanted to be sure that there won't be unexpected problems!
