### ISSUE TITLE
ValidateAsync does not cater for Updates

### ISSUE THREAD

**Issue by Kukks** [openiddict/openiddict-core#695]
Trying to update an existing Application however the `OpenIddictApplicationManager` throws a validation error saying that `An application with the same client identifier already exists` even though I am doing an `Update` and not `Create`

**Comment by kevinchalet** [comment]
This error is only returned if we can find an existing entry in the database with the same key AND if the keys of the updated and existing applications don't exactly match (binary comparison):

> https://github.com/openiddict/openiddict-core/blob/e1a7832a6cd3645c12b910eb5e51f93cc66f345c/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs#L1019-L1025

What's the key type you're using? Is there a chance two calls to `GetIdAsync` might produce different results for the same entity?

**Comment by Kukks** [comment]
Using the default key type, `string`. 
No, no chance for that. 
 I have a custom application type, but still the same key and only added fields.

**Comment by kevinchalet** [comment]
Then no idea. This method is heavily used in OrchardCore and no similar bug has been reported so far.

Consider posting a repro on GitHub (one that builds and runs) and I'll take a look.
