### ISSUE TITLE
ROPC is secure? Which flow to choose?

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#696]
I recently read that ROPC may have several security holes, this link addresses some of them:
https://tools.ietf.org/html/rfc6749#section-10.7
brute force, save password in client log, others ...

What is your opinion about this?

I think it should be a question that many novice developers, like me

Which flow to choose when your client is just a SPA and a mobile app?

**Comment by kevinchalet** [comment]
> What is your opinion about this?

Technically, the ROPC flow is very much like the API equivalent of any login page, so I have nothing against it as long as it's properly used (I know some identity experts would like to kill it, but that's not my case).

You can find more information about ROPC (and the other flows) here: https://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-choosing-the-right-flows/

> Which flow to choose when your client is just a SPA and a mobile app?

SPA = implicit flow.
Mobile app = code flow.

**Comment by marcrib** [comment]
Very thanks @PinpointTownes 

I do not know why they do not like ROPC, it's a transparent authentication

Others flow require to use razor. Exist other alternative? Create a authserver use only api and spa framework?
