### ISSUE TITLE
While doing silentRenew token manually I get "Frame window timed out"

### ISSUE THREAD

**Issue by MunazzahNawaz** [openiddict/openiddict-core#703]
I have checked many links but no solution worked for me. 
I am using oidc-client in angular 6 app and I am calling 
this.userManager.signinSilent(); to refresh tokens, and getting "Frame window timed out" error. I have checked all redirect Uris also and everything seems to be OK. here is my config:

{
        authority:  'https://localhost:44360/',
        client_id: 'SPA_Client',
        redirect_uri: 'http://localhost:4200/auth-callback',
        post_logout_redirect_uri:  'http://localhost:4200/',
        response_type: 'id_token token',
        scope: 'openid profile roles api country',
        filterProtocolClaims: true,
        loadUserInfo: true,
        automaticSilentRenew: true,
        accessTokenExpiringNotificationTime: 300,
        silent_redirect_uri: 'http://localhost:4400/auth-refresh'
    };

**Comment by kevinchalet** [comment]
Did you take a look at the logs? This may be the cause of an invalid request, for which you couldn't be redirected to the `silent_redirect_uri`.
