### ISSUE TITLE
How to customise what claims are included in JWT

### ISSUE THREAD

**Issue by davebat** [openiddict/openiddict-core#704]
Hi,

I am comfortable with adding my own claims to the JWT, but was wondering if there is a way to stop some of the existing claims being added.

My decoded token looks like this:

{
  "sub": "62bf7a04-da00-4279-975e-39538c5c77ff",
  "name": "dbattersby@example.com",
  "EntityId": "2",
  "token_usage": "access_token",
  "jti": "32bcb635-8d30-4b29-9cbe-636e3041f290",
  "cfd_lvl": "private",
  "scope": [
    "openid",
    "profile",
    "roles"
  ],
  "aud": "CustomerPortal",
  "azp": "CustomerPortalUA",
  "nbf": 1544014148,
  "exp": 1544015948,
  "iat": 1544014148,
  "iss": "http://localhost/CustomerPortal.Api.Authentication"
}

Is there a way to remove the scope claim? the only reason I want to was in the interest of keeping the JWT as light as possible.

Thanks,
Dave

**Comment by kevinchalet** [comment]
Something like that should do what you want:

```csharp
public class CustomAccessTokenHandler : JwtSecurityTokenHandler
{
    public override JwtSecurityToken CreateJwtSecurityToken(SecurityTokenDescriptor tokenDescriptor)
    {
        // Remove all the scope claims from the access token.
        foreach (var scope in tokenDescriptor.Subject.FindAll(OpenIddictConstants.Claims.Scope).ToList())
        {
            tokenDescriptor.Subject.RemoveClaim(scope);
        }

        return base.CreateJwtSecurityToken(tokenDescriptor);
    }
}
```

```csharp
services.AddOpenIddict()
    .AddCore(options =>
    {
        // ...
    })

    .AddServer(options =>
    {
        // ...

        options.Configure(o => o.AccessTokenHandler = new CustomAccessTokenHandler());

        // Don't call options.UseJsonWebTokens() or the custom handler will be replaced.
    })
    
    .AddValidation(options =>
    {
        // ...
    });
```

Would I recommend it? It depends, as the scope claims are extremely useful for your APIs (assuming you use scopes, of course): they are a great way to limit what client applications are allowed to do/access on behalf of the authenticated users, so if you have third-party clients, I encourage you to use them.

**Comment by davebat** [comment]
thankyou, thats exactly what I need. I appreciate your point about third party access and will think about whether  this is really the approach i want

**Comment by mgritcan** [comment]
@kevinchalet thanks for your great effort to answer to all of us! I appreciate it very much!
Could you please point me towards docs where I could see how in version 5.7.0 it is possible to implement a CustomAccessTokenHandler ? I tried the way you suggested above, but the version 5.7.0 does not contain a property for `AccessTokenHandler ` like it was previously `options.Configure(o => o.AccessTokenHandler = new CustomAccessTokenHandler());`
