### ISSUE TITLE
Multiple authorizations for the same identity user?

### ISSUE THREAD

**Issue by kueronya** [openiddict/openiddict-core#707]
Hello 

I am implementing resource owner password flow along with a custom urn:ietf:params:oauth:grant-type:google_access_token flow for single sign on. 

The latter is creating a single authorization record on the first sign in, while the password flow is creating an authorization record on every sign in. I feel like i'm doing something wrong here. Should there multiple authorizations for the same user and should different flows reuse the same authorization?

I would be glad if someone can point me in the right direction. Thank you
   
Token endpoint looks like this:
```
[HttpPost ("api/connect/token"), Produces ("application/json")]
        public async Task<IActionResult> Exchange (OpenIdConnectRequest request) {

            // password flow
            if (request.IsPasswordGrantType ()) {
                var user = await _userManager.FindByNameAsync (request.Username);
                if (user == null) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                            ErrorDescription = "The username/password couple is invalid."
                    });
                }

                // Validate the username/password parameters and ensure the account is not locked out.
                var result = await _signInManager.CheckPasswordSignInAsync (user, request.Password, lockoutOnFailure : false);
                if (!result.Succeeded) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                            ErrorDescription = "The username/password couple is invalid."
                    });
                }

                // Create a new authentication ticket.
                var ticket = await CreateTicketAsync (request, user);

                return SignIn (ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);

            // refresh flow
            } else if (request.IsRefreshTokenGrantType ()) {
                // Retrieve the claims principal stored in the refresh token.
                var info = await HttpContext.AuthenticateAsync (OpenIdConnectServerDefaults.AuthenticationScheme);

                var user = await _userManager.GetUserAsync (info.Principal);
                if (user == null) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                            ErrorDescription = "The refresh token is no longer valid."
                    });
                }

                // Ensure the user is still allowed to sign in.
                if (!await _signInManager.CanSignInAsync (user)) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                            ErrorDescription = "The user is no longer allowed to sign in."
                    });
                }

                // Create a new authentication ticket, but reuse the properties stored
                // in the refresh token, including the scopes originally granted.
                var ticket = await CreateTicketAsync (request, user, info.Properties);

                return SignIn (ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);

            // assertion grant flow
            } else if (request.GrantType == "urn:ietf:params:oauth:grant-type:google_access_token") {
                // Reject the request if the "assertion" parameter is missing.
                if (string.IsNullOrEmpty (request.Assertion)) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.InvalidRequest,
                            ErrorDescription = "The mandatory 'assertion' parameter was missing."
                    });
                }

                try {
                    // Validate the access token using Google's token validation
                    var payload = await GoogleJsonWebSignature.ValidateAsync (request.Assertion);

                    var user = await _userManager.FindByEmailAsync (payload.Email);

                    if (user != null) {

                        if (!await _signInManager.CanSignInAsync (user)) {
                            return BadRequest (new OpenIdConnectResponse {
                                Error = OpenIdConnectConstants.Errors.InvalidGrant,
                                    ErrorDescription = "The user is no longer allowed to sign in."
                            });
                        }
                        // Create a new authentication ticket and return sign in
                        var ticket = await CreateTicketAsync (request, user);
                        return SignIn (ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);

                    } else {

                        // Create a new ClaimsIdentity containing the claims that
                        // will be used to create an id_token and/or an access token.
                        var identity = new ClaimsIdentity (OpenIdConnectServerDefaults.AuthenticationScheme);

                        // Create a new authentication ticket holding the user identity.
                        var ticket = new AuthenticationTicket (
                            new ClaimsPrincipal (identity),
                            new AuthenticationProperties (),
                            OpenIdConnectServerDefaults.AuthenticationScheme);

                        ticket.SetScopes (
                            OpenIdConnectConstants.Scopes.OpenId,
                            OpenIdConnectConstants.Scopes.OfflineAccess);

                        return SignIn (ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
                    }
                } catch (InvalidJwtException) {
                    return BadRequest (new OpenIdConnectResponse {
                        Error = OpenIdConnectConstants.Errors.AccessDenied,
                            ErrorDescription = "The provided token is invalid"
                    });
                }

            }

            return BadRequest (new OpenIdConnectResponse {
                Error = OpenIdConnectConstants.Errors.UnsupportedGrantType,
                    ErrorDescription = "The specified grant type is not supported."
            });
        }
```

**Comment by kevinchalet** [comment]
Hey,

Here's how it works: by default, OpenIddict creates a **new ad-hoc and independent authorization** each time an authorization code or refresh token is about to be returned to the client application, which includes the authorization code flow, the password flow or any custom flow as long as a refresh token is returned. This authorization is automatically reused when receiving a `grant_type=refresh_token` request so OpenIddict doesn't have to create multiple authorizations for the same chain of tokens.

In many cases, you'll indeed want to re-use existing authorizations, if possible. Since this logic is app-specific, it's not something OpenIddict will do for you OOTB. To re-use an existing authorization, retrieve it from the DB using the `OpenIddictAuthorizationManager.FindAsync()` methods or create a new one and attach the authorization identifier to the authentication ticket using `ticket.SetInternalAuthorizationId(await _authorizationManager.GetIdAsync(authorization))`.

That's precisely what we do in Orchard's OpenID module so feel free to take a look at the authorization controller it uses if you want to see a real world implementation in action: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs

**Comment by kueronya** [comment]
Thank you @PinpointTownes ! I really appreciate your dedication to this whole topic. Learned so much just reading through your various comments.

That said, is there any downside reusing authorizations?

**Comment by TerraVenil** [comment]
Hi, @PinpointTownes. Am I right understand that based on previous example with Orchard when call to token endpoint you generate a new access/refresh tokens EVERY time without reusing existing one??? I thought you should always reuse existing access_refresh token keys. From that perspective do we need endpoint for access_token generation based on refresh_token if we can always reuse password grant_type to acquire a new tokens?

**Comment by kevinchalet** [comment]
Hey @TerraVenil,

Orchard's OpenID module will generate a new refresh token for every `grant_type=refresh_token` or `grant_type=password` token request,

If you simply send a refresh token request (`grant_type=refresh_token`), it won't generate a new refresh token but just an access token. You can force it to issue a new refresh token every time by turning on rolling tokens in the advanced options.

> From that perspective do we need endpoint for access_token generation based on refresh_token if we can always reuse password grant_type to acquire a new tokens?

Using the ROPC flow is fine if you do it just once, when the user initially enters his credentials. If you store them to issue `grant_type=password` requests later, then you're going it completely wrong and that's fundamentally bad as you should never store user passwords in a non-hashed form. Use the refresh token mechanism to get a new access token when the first one is expired.
