### ISSUE TITLE
Where are properties of OpenIddictApplications and OpenIddictScopes been used?

### ISSUE THREAD

**Issue by jinweijie** [openiddict/openiddict-core#708]
Hi Kevin, 

Thanks for this great project. One quick question is that, in the OpenIddictApplications and OpenIddictScopes tables, there are Properties columns. But I couldn't find where the properties columns been used. Is it for future extensibility or did I miss to find the usage?

Thanks for advance.

Weijie

**Comment by kevinchalet** [comment]
Hey,

> Thanks for this great project.

Glad you like it!

> Is it for future extensibility or did I miss to find the usage?

That's exactly what they are used for: extensibility. Most notably, they are used in the OrchardCore OpenID module as a way to store Orchard-specific data without having to make any schema change ; which is particularly important, as we want to be able to use the management UI feature with any non-Orchard OpenIddict deployment (if we had schema differences, it wouldn't work and you'd get exceptions telling you expected SQL columns cannot be found).

Here's how it looks like in action: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.OpenId.Core.EntityFrameworkCore/Services/OpenIdApplicationStore.cs#L77-L91.

**Comment by jinweijie** [comment]
Thanks a lot for the prompt reply, very clear now, you may close this issue.

Thanks & Happy New Year!
