### ISSUE TITLE
Why Openiddict automatically validate client_id?

### ISSUE THREAD

**Issue by azim-bl** [openiddict/openiddict-core#710]
I want to generate a token with four parameter client_id,client_secret, username & user password. Client_Id & client_secret are optional requirement. When I generate token with username & user password its working fine but when i try to pass client_id, it fails with 500 internal server error.

When i check the log and found: No database provider has been configured for this DbContext.

My Service Configuration:

public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        services.AddDbContext<DbContext>(options =>
        {
            options.UseOpenIddict();
        });

        services.AddOpenIddict()
            // Register the OpenIddict core services.
            .AddCore(options =>
            {
                options.UseEntityFrameworkCore().UseDbContext<DbContext>();
            })

            .AddServer(options =>
            {
                options.UseMvc();
                options.EnableTokenEndpoint("/connect/token");
                options.AllowPasswordFlow().AllowRefreshTokenFlow();
                options.SetAccessTokenLifetime(TimeSpan.FromMinutes(10));
                options.SetRefreshTokenLifetime(TimeSpan.FromHours(4));
                options.AcceptAnonymousClients();
                options.DisableHttpsRequirement();

            })
            .AddValidation();
        services.AddAuthentication(options =>
        {
            options.DefaultScheme = OpenIddictValidationDefaults.AuthenticationScheme;
        });
    }

 Asp.net Core Log: 

 fail: Microsoft.AspNetCore.Server.Kestrel[13]
  Connection id "0HLJJPK2L74A1", Request id "0HLJJPK2L74A1:00000003": An 
  unhandled exception was thrown by the application.
  System.InvalidOperationException: No database provider has been 
  configured for this DbContext. A provider can be configured by 
  overriding the DbContext.OnConfiguring method or by using AddDbContext 
  on the application service provider. If AddDbContext is used, then also 
  ensure that your DbContext type accepts a DbContextOptions<TContext> 
  object in its constructor and passes it to the base constructor for 
  DbContext.

  at System.Threading.Tasks.ValueTask`1.get_Result()
  at 
  OpenIddict.Core.OpenIddictApplicationManager`1.FindByClientIdAsync(String 
  identifier, CancellationToken cancellationToken)
  at OpenIddict.Core.OpenIddictApplicationManager`1. 
  OpenIddict.Abstractions.IOpenIddictApplicationManager. 
  FindByClientIdAsync(String identifier, CancellationToken 
  cancellationToken)

Problem is this only happen when i pass client_id on token request. I think this client_Id is automatically validate by openiddict. I want to validate this client_id on my '/connect/token' method.

I don't configure any dbcontext in my application. 

Is there any way to disabled the automatically client_id validation ?

**Comment by kinosang** [comment]
see #701

**Comment by azim-bl** [comment]
@kinosang I read this , but i cant understand what need to do on my case .

**Comment by kevinchalet** [comment]
I posted an explanation on SO: https://stackoverflow.com/questions/54061296/why-openiddict-automatically-validate-client-id/54112110#54112110.
