### ISSUE TITLE
unable to authenticate ASOS token in asp .net identity core 2.0

### ISSUE THREAD

**Issue by anujamalviya** [openiddict/openiddict-core#714]
i am trying to generate token using openiddict ASOS authentication in asp .net core identity 2.0, the generated token does not allow me to authenticate the user, the userContext object is getting null value due to my code below in startup.cs:

services.AddIdentity<User, Role>()
.AddEntityFrameworkStores(SomedbContext)
.AddDefaultTokenProviders();

The same code i am using for asp .net core solution and it was working fine with above lines.
Is there any way out in asp .net core identity to authenticate the ASOS token.

**Comment by kevinchalet** [comment]
I'm not sure I understand what you mean. Care to explain?

**Comment by anujamalviya** [comment]
My code is like this
```
public void ConfigureServices(IServiceCollection services)
        {
             services
                .AddAuthentication(OAuthValidationDefaults.AuthenticationScheme)
                .AddOAuthValidation()
                .AddOpenIdConnectServer(options =>
                {
                    options.ProviderType = typeof(AuthorizationProvider);
                    options.TokenEndpointPath = "/authtoken";
                    options.AllowInsecureHttp = true;
                    options.ApplicationCanDisplayErrors = true;
                });
            services.AddScoped<AuthorizationProvider>();
            services.AddDbContext<SecurityDataContext>(options =>
                options.UseSqlServer(Configuration["DatabaseConnection"]));
            services.AddIdentity<User, Role>()
                .AddEntityFrameworkStores<SecurityDataContext>();
}
```

Authorization Attribute
```
//[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
    public class FeatureAuthorizeAttribute : AuthorizeAttribute, IAuthorizationFilter
    {       
        public void OnAuthorization(AuthorizationFilterContext context)
        {
            var user = context.HttpContext.User;
            if (!user.Identity.IsAuthenticated)
            {
                context.Result = new UnauthorizedResult();
                return;
            }
}
```

If I remove the line 
```
services.AddIdentity<User, Role>()
                .AddEntityFrameworkStores<SecurityDataContext>();
```
context.HttpContext.User is giving me correct data in AuthorizationFilter, when I pass the token bearer from client application

adding 
```
services.AddIdentity<User, Role>()
                .AddEntityFrameworkStores<SecurityDataContext>();
```
context.HttpContext.User is coming null

**Comment by kinosang** [comment]
> i am trying to generate token using openiddict ASOS authentication in asp .net core identity 2.0, the generated token does not allow me to authenticate the user, the userContext object is getting null value due to my code below in startup.cs:
> 
> services.AddIdentity<User, Role>()
> .AddEntityFrameworkStores(SomedbContext)
> .AddDefaultTokenProviders();
> 
> The same code i am using for asp .net core solution and it was working fine with above lines.
> Is there any way out in asp .net core identity to authenticate the ASOS token.

@anujamalviya you should add OpenId Connect token Authentication extension or OpenIddict.Validation extension to your Core Authentication

**Comment by anujamalviya** [comment]
> I'm not sure I understand what you mean. Care to explain?

added more details

**Comment by AnandKThakur** [comment]
@PinpointTownes Could you please help us to solve above issue

**Comment by kinosang** [comment]
You mean you want to valid the ASOS token without asp.net core Identity?

You should create your own core Authentication middleware to do that, all the tokens are protected with asp.net core DataProtection, you can create a DP instance with the same key of ASOS and unprotect the token by using the DP instance, then you got the payload.

**Comment by kevinchalet** [comment]
@anujamalviya @AnandKThakur the issue is with the default schemes. This thread should put you on the right track: https://github.com/openiddict/openiddict-core/issues/436#issuecomment-325369288

**Comment by anujamalviya** [comment]
@PinpointTownes  Thank you so much!
