### ISSUE TITLE
NOT working on Chrome

### ISSUE THREAD

**Issue by lutaiphong** [openiddict/openiddict-core#721]
Hi,

I'm not sure why but all of your `Authorization code` and `Implicit` examples are NOT working on Chrome. Firefox is ok, Edge is ok, even Internet Explorer is ok.
This issue happens with the examples in this repository and also in `openiddict-samples`

OS: Windows 10 Pro
Chrome version: 71.0.3578.98 (Official Build) (64-bit)

Hope you could have some time to look at it.

BTW, the project is wonderful.

Thanks,
Phong

**Comment by kevinchalet** [comment]
Hey.

Interesting. I use Chrome and I haven't noticed any issue lately. Any chance you could describe what's not working for you?

**Comment by lutaiphong** [comment]
Sorry, I forget this part.

The registration flow is fine, but the login isn't.
I'll try to record it to show.

**Comment by lutaiphong** [comment]
[Here](https://drive.google.com/drive/folders/1QXKm_14u3SwcP5bx5PBvvMDxIADPZ-gQ?usp=sharing) you are.

**Comment by kevinchalet** [comment]
@lutaiphong well, the only thing I can see is Visual Studio's main window, without any file opened 😄

**Comment by lutaiphong** [comment]
Sorry, stupid me.

[Here](https://tinytake.s3.amazonaws.com/pulse/lutaiphong/attachments/9873771/TinyTake10-02-2019-10-07-23.mp4) is the correct one.

**Comment by kevinchalet** [comment]
Weird. Is there anything interesting in the Chrome logs? In the ASP.NET Core logs? Is the ASP.NET Core Identity cookie correctly sent?

**Comment by lutaiphong** [comment]
OMG. I must go kill myself.
Cognito mode went through easily.
The reason must be one of my extension...
Thanks a lot, @PinpointTownes , you save my day.

I gotta close this.
