### ISSUE TITLE
External login .AddAzureAD not working

### ISSUE THREAD

**Issue by Krangth** [openiddict/openiddict-core#722]
I was able to get this sample to successfully authenticate against my Azure AD v2 App Registration which is configured for single tenancy. However, I have been unable to get OpenIddict to successfully authenticate with it. In fiddler the two apps send the same requests to Microsoft and get the same replies. The sample app is signed in at the end, but OpenIddict doesn't seem to complete the process. I don't doubt that the problem is with Azure AD as I have been able to successfully sign into to numerous other providers such as Facebook, Google, and even Office365.

This is the sample app is from [https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp)

There is a link to download the sample from a link on that page, but here it is again for easy reference: [source code](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/archive/aspnetcore2-2.zip)

I believe the problem is in the AccountController.ExternalLoginCallback at 
`var info = await _signInManager.GetExternalLoginInfoAsync();`

I think this is the relevant code:

```
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
.AddAzureAD(options =>
{
	options.Instance = "https://login.microsoftonline.com/";
	options.TenantId = "guid";
	options.Domain = "localhost";
	options.ClientId = "guid";
	options.ClientSecret = "pwd";
	options.CallbackPath = "/signin-oidc";
});

services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
	options.Authority = options.Authority + "/v2.0/";
	options.ResponseType = OpenIdConnectResponseType.Code;
}
```

**Comment by kevinchalet** [comment]
Wooops, looks like I missed this thread. Do you still need help?

**Comment by Krangth** [comment]
Unfortunately, I never resolved the issue and had to move on. I felt that the problem with with Azure AD anyway. Perhaps something has changed on their end. I do not think I'll be able to allocate any time to reviewing this problem any time soon even though you are ready :(
I'll post again if I can get back into it and still have an issue.
