### ISSUE TITLE
External Authorize server

### ISSUE THREAD

**Issue by phonglt7** [openiddict/openiddict-core#723]
Hi,

I'd set up my project using OpenIddict successfully.
Register, login, logout, authorize is ok, on the same server.
However, we have a new urgent request that we need to separate the Authorization out of the Authorization Server.
Consider this: 
- Authorization Server A will receive a request at /connect/token and returns access_token.
- Client B will add access_token to the header and make a request to Resource Server C.
- Resource Server C mark the controller with [Authorize] can validate access_token of Client B and let it in.

Please show me how to setup like that.

Thanks,
Phong.

**Comment by kinosang** [comment]
Use JWT, or the Introspection middleware in Resource Server.
