### ISSUE TITLE
Could OpenIdDict support Table storage instead of EntityFramework?

### ISSUE THREAD

**Issue by ianpowell2017** [openiddict/openiddict-core#724]
Hi, 

I was just wondering how hard this would be to use Azure table storage instead of Entity Framework?

I am currently using ElCamino.AspNetCore.Identity.AzureTable nuget package for storage of user credentials and looking to add OpenIdDIct.

I currently have no requirement to use SQL server in the solution.

Please advise where I should start?

**Comment by kevinchalet** [comment]
Hey,

> I was just wondering how hard this would be to use Azure table storage instead of Entity Framework?

Hard, I dunno but painful, yeah, likely. The main challenge to solve would be to deal with partition and row keys.

> Please advise where I should start?

You can take a look at the MongoDB stores, tho' I'm not sure it will help, as Mongo's API is much simpler to use than ATS 😅

**Comment by ianpowell2017** [comment]
The problem I am facing is that a site I am working on uses https://github.com/dlmelendez/identityazuretable which uses Azure table storage as its underlying data source.

I have the requirement to add OAuth Code flow to the website and found this project which shows a lot of promise.  Any help you can offer would be very appreciated.

**Comment by kevinchalet** [comment]
I don't plan to add support for ATS myself, but if you have precise questions about the OpenIddict integration part, feel free to ask.
