### ISSUE TITLE
Cannot run and use two identity server in integrations tests

### ISSUE THREAD

**Issue by jonathanantoine** [openiddict/openiddict-core#726]
Hello,

I have an integration test which run 2 identity server both using OpenIddict.
I can call the first one and it works fine but when I call the second one, I get this error :

```Unable to resolve service for type 'XXX.Api.IntegrationTests.Infra.XXIntegrationTestDbContext' while attempting to activate 'OpenIddict.EntityFrameworkCore.OpenIddictAuthorizationStore`5[OpenIddict.EntityFrameworkCore.Models.OpenIddictAuthorization`1[System.Int64],OpenIddict.EntityFrameworkCore.Models.OpenIddictApplication`1[System.Int64],OpenIddict.EntityFrameworkCore.Models.OpenIddictToken`1[System.Int64],XXX.Api.IntegrationTests.Infra.XXXIntegrationTestDbContext,System.Int64]'. POST http://localhost/connect/token```

Where "XXIntegrationTestDbContext" is the type of the DbContext in my first identity server. I wonder it this scenario is possible and if some "static" cache is hitting me in the face here ?

Thanks a lot !

**Comment by jonathanantoine** [comment]
I did have a workaround and a possible cause, these services uses static cache and therefore does not allow the described scenario :

- OpenIddictApplicationStoreResolver
- OpenIddictAuthorizationStoreResolver
- OpenIddictScopeStoreResolver
- OpenIddictTokenStoreResolver

As a work-around, I created my own version of the services and registered them :
  ```services.AddSingleton<IOpenIddictApplicationStoreResolver, OpenIddictApplicationStoreResolver>();
services.AddSingleton<IOpenIddictAuthorizationStoreResolver, OpenIddictAuthorizationStoreResolver>();
services.AddSingleton<IOpenIddictAuthorizationStoreResolver, OpenIddictAuthorizationStoreResolver>();
services.AddSingleton<IOpenIddictScopeStoreResolver, OpenIddictScopeStoreResolver>();
services.AddSingleton<IOpenIddictTokenStoreResolver, OpenIddictTokenStoreResolver>();```

**Comment by kevinchalet** [comment]
Hey,

I identified this issue a few weeks ago thanks to another report and fixing it is indeed on my radar (actually, I started working on a PR last week). The fix would be to remove the static cache and replace it by a private singleton cache injected via DI, whose lifetime would match the lifetime of the root DI container.

The EF Core/EF 6/NHibernate stores are impacted, but not the MongoDB stores as they don't use static caches.

In the meantime, the workaround you did is the right way to go.

Cheers.

**Comment by jonathanantoine** [comment]
Thanks and thank you again for this awesome project!

**Comment by fingers10** [comment]
Hi Jonathanantonie,

I'm also trying to write integration test with openiddict in asp.net core 2.2 web api. But when I make a request to token end point to get bearer token, I'm getting 400 Bad Request. Please could you assist or share some code on how to get bearer token in integration tests?

Thanks,
Abdul

**Comment by kevinchalet** [comment]
FYI: the fix was backported to 2.x as part of the 2.0.1 release.
