### ISSUE TITLE
What is the best flow for spa and mobile applications?

### ISSUE THREAD

**Issue by marcrib** [openiddict/openiddict-core#727]
Password Flow is not secure
Implicit flow is not secure

For oauth2 the two flow are not secure

Is not it really safe?
To this day several frameworks by default implement password flow or simple jwt generation (not password flow, not send client and secret in request)

Which one should we use?

Many developers just want to make their applications safer, but why so many rules?

**Comment by xperiandri** [comment]
Implicit or Hybrid
Anyway it is implicit for SPA
Open popup, navigate to auth URI, catch when redirected to redirect URI, get tokens
