### ISSUE TITLE
Add Client Id and Secret to Password Flow

### ISSUE THREAD

**Issue by kguernsey** [openiddict/openiddict-core#728]
I would like to include the Client Id and Secret in the Password Flow, but I can't figure out how to include them in the request. 

Any help would be appreciated. 

Thanks

**Comment by kevinchalet** [comment]
It works the same way as the other flows that use the token endpoint. You can either:
  - Specify them in the request form, using `client_id` and `client_secret`.
  - Specify them in the `Authorization` header, using basic authentication: https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by kguernsey** [comment]
Thanks - I'll give it a try. 

I appreciate your fast reply.

**Comment by xperiandri** [comment]
@kguernsey just use IndentityModel NuGet
