### ISSUE TITLE
OpenIddict Store with Stored Procedure SQL - IQueryable

### ISSUE THREAD

**Issue by auriou** [openiddict/openiddict-core#730]
Hi, I'm implementing OpenIddict Store classes to use SQL stored procedures because we can not use EF in my business.
I have a problem with ListAsync methods that have IQueryable arguments because for a stored procedure it does not make any sense because the parameters are determined.
I can return the entire table and then convert the result to IQueryable with .AsQueryable (), but that will degrade the performance.
I would like to know if these methods, using IQueryable, are used by the OpenIddict engine or they are only used when using the store management methods.
Thank you

**Comment by kevinchalet** [comment]
Hey Philippe,

> I would like to know if these methods, using IQueryable, are used by the OpenIddict engine or they are only used when using the store management methods.

They are only used by the `OpenIddictXYZManager.CountAsync()/GetAsync()/ListAsync()` overloads accepting queryable delegates, that only exist to allow users to execute arbitrary queries in an asynchronous way. They are not used by OpenIddict.

In your case, I'd simply throw a `NotSupportedException`. It's what we do in the YesSql stores for OrchardCore: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Stores/OpenIdApplicationStore.cs#L51

**Comment by auriou** [comment]
Great, thank you Kevin
