### ISSUE TITLE
How to implement API keys?

### ISSUE THREAD

**Issue by NetTecture** [openiddict/openiddict-core#732]
Stnadard scenario access tokens are short term and not revocable - which makes total sense if you have the code in place to use a refresh token.

API keys otoh should not be too long and *must* be revocable and durable - people do not want to upgrade their excep spreadsheets every week, i.e.

is there any code example how to implement an API key based on openiddict?´as server? Need to add API keys to my servers.

**Comment by kevinchalet** [comment]
I'm afraid API keys are not a good fit for OpenIddict, which is an OpenID Connect library.

The closest equivalent you can find in the OAuth2/OpenID Connect world is the client credentials grant type: https://tools.ietf.org/html/rfc6749#section-4.4

**Comment by NetTecture** [comment]
So basically implement a SECOND security database somehow?

And no, client credentials do not work. Clients include non modifiable software like i.e. Excel (that can handle REST API's, in our case OData, for reporting). I can enter an API key. Entering the access token is not wanted due to excessively small lifetime and roles (noramlly with an API key you acutally allow further limitation - yes, the customer can edit records, but the api key for reporting is read only).

Imagine Azure DevOps, i.e. - oauth 2 can be used for user identification, but I can ALSO, once logged in, ask for a (limited, with scopes) API key.

So, you mean for this I have to implement the whole stack myself? There is no support i.e. to generate a long duration access token (sure in an API I have to write) and store it in the openiddict token table?

And yes, I could manually (with a special endpoint) generate extreme long duration access tokens - but I fail to see an easy way then to revoke them. Or I basically generate an API level token issue point taht hands out log duration access tokens (180 days) and can handle the additional scopes, but then I actually have to switch over to reference tokens, so I get an authentication call? There is no way to mix jwt (access/refresh token combo) and reference tokens in one endpoint?

**Comment by kevinchalet** [comment]
Looks like you're trying to use OpenIddict for something it hasn't been designed for, which is probably not a good idea. If you want to use API keys, implementing your own `AuthenticationHandler` (or picking an existing one developed by the community) would be a much better approach.
