### ISSUE TITLE
ConfirmEmailAsync flow exit with exception during user validation process

### ISSUE THREAD

**Issue by dbarrios1907** [openiddict/openiddict-core#733]
Hi, 

Im trying to get a activation flow with OpenIddict, i have followed all migration configuration steps to latest version 2.0.0-rc3-final, authentication working as expected, but while activating user using EmailConfirmedAsync exits with following exception during ValidateUserAsync step:

![image](https://user-images.githubusercontent.com/12056326/54500934-c1195000-4900-11e9-9a56-6e4b8b21557e.png)

However, securityStamp is not empty, and setup within user entity. 

this is my updated configuration of OpenIndict:

![image](https://user-images.githubusercontent.com/12056326/54500975-063d8200-4901-11e9-996a-dbab5420547a.png)

And My activation logic:

![image](https://user-images.githubusercontent.com/12056326/54501175-77ca0000-4902-11e9-83d8-b4d39c3cbe06.png)

Is this a bug or im missing a configuration step to make activation flow works properly ?

Thanks ahead, Regards !

**Comment by kevinchalet** [comment]
Hey,

I'm not sure to understand how OpenIddict may impact the fact a user - managed by ASP.NET Core Identity - doesn't have a security stamp? It looks like a question for the ASP.NET folks to me.

Are you 100% confident your user has a security stamp assigned?
