### ISSUE TITLE
Refresh_token in cluster environment

### ISSUE THREAD

**Issue by phonglt7** [openiddict/openiddict-core#738]
Hi,

Currently, I'm using OpenIddict in JWT.
Everything works fine until we deployed it on production.
Our production site setup as:
- 1 load balancer for below A, B.
- 2 containers (name A, B) as Authorization servers.

The issue happens when A issue tokens (access_token and refresh_token) and somehow if the load balancer point to the container B, it can't deserialize the refresh_token, then it returned
> The specified refresh token is invalid
Then if the load balancer point to A, it works fine.

Please show me how to overcome this issue.

Thanks,
Phong.

**Comment by kevinchalet** [comment]
Hey,

https://github.com/openiddict/openiddict-core/issues/720#issuecomment-460656652 should put you on the right track 😄

**Comment by phonglt7** [comment]
Awesome @PinpointTownes . Thanks a lot!
