### ISSUE TITLE
Unable to locate Dependency Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by haroldma-zz** [openiddict/openiddict-core#74]
`Unable to locate Dependency Microsoft.Extensions.DependencyModel >= 1.0.0-dev-1452673922`

That's following the Readme guide.

**Comment by kevinchalet** [comment]
Not sure what's the point of opening a ticket to immediately close it, but anyway: this package has been reversioned: clear your .nuget\packages folder in your Windows profile folder.

**Comment by haroldma-zz** [comment]
Solved it by doing just that. Hence why I closed it.

**Comment by kevinchalet** [comment]
In general, it's better to post the solution, since it may be useful for someone else.
