### ISSUE TITLE
Support Source Link

### ISSUE THREAD

**Issue by hermanho** [openiddict/openiddict-core#741]
Support Source Link on NuGet will improve the experiences on source debugging.

Ref:
https://github.com/dotnet/sourcelink

**Comment by kevinchalet** [comment]
Good idea. Let's do that as part of the 3.0 update!

**Comment by kevinchalet** [comment]
Would you be interested in submitting a PR to enable it?

**Comment by kevinchalet** [comment]
Looks like we got that for free when moving to Arcade 😄
