### ISSUE TITLE
GetOpenIdConnectRequest() without EnableTokenEndpoint() to use it in GraphQL

### ISSUE THREAD

**Issue by PayteR** [openiddict/openiddict-core#743]
Hi, is there a way how to get `OpenIdConnectRequest` 
```
// this is always null
OpenIdConnectRequest request = httpContextAccessor.HttpContext.GetOpenIdConnectRequest();
```
withtout enabling EnableTokenEndpoint?

I need it to make it work in GraphQL. GraphQL uses only one http endpoint url to make all requests, so i can't set endpoint to that. Any idea? thx

**Comment by PayteR** [comment]
I dig deeper and realized, that i don't really need to have `OpenIdConnectRequest`, i could SignIn with 

```
await httpContextAccessor.HttpContext.SignInAsync(ticket.AuthenticationScheme, ticket.Principal, ticket.Properties);
```
But i get error `An authorization or token response cannot be returned from this endpoint`

From this, https://stackoverflow.com/questions/42048770/asp-net-core-openiddict-throws-an-openid-connect-response-cannot-be-returned-fr  i understand that i need to avoid default checking of EnableTokenEndpoint url. 

What i basicaly want to do, is to be able create and retrieve login/refresh token anywhere i want, is it possible? thx

**Comment by kevinchalet** [comment]
Hey,

It's not exactly clear to me what you're trying to achieve. Why do you want to return an OIDC response from a GraphQL endpoint? 😕

**Comment by PayteR** [comment]
@PinpointTownes i just want to generate Token from my graphql endpoint, but i don't know how...

**Comment by kevinchalet** [comment]
@PayteR it's not supported (and will never be): OpenIddict deliberately prevents you from returning token responses from endpoints it doesn't manage.
