### ISSUE TITLE
need openiddict base on netstandard 2.1

### ISSUE THREAD

**Issue by daview** [openiddict/openiddict-core#744]
A project base on netstandard 2.1 and package reference the openiddict, but build failure:

the type System.Threading.Tasks.ValueTask is conflict.

**Comment by kevinchalet** [comment]
It's a known issue, that should be fixed in the next .NET Core 3.0 preview: https://github.com/dotnet/corefx/issues/36719.

**Comment by kevinchalet** [comment]
https://github.com/dotnet/corefx/issues/36719 was just closed, so the fix should likely land in the next .NET Core 3.0 preview.
