### ISSUE TITLE
Refresh token not being returned

### ISSUE THREAD

**Issue by jerriep** [openiddict/openiddict-core#747]
I am authorizing a user with OpenIddict using the implicit grant flow and want to have a refresh token returned, but for some reason OpenIddict is only returning an `id_token` and an `access_token`.

I have OpenIddict configured as follows:

```
services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore()
            .UseDbContext<CloudpressDbContext>();
    })
    .AddServer(options =>
    {
        options.UseMvc();

        options.EnableAuthorizationEndpoint("/connect/authorize")
            .EnableLogoutEndpoint("/connect/logout")
            .EnableIntrospectionEndpoint("/connect/introspect")
            .EnableTokenEndpoint("/connect/token");

        options.RegisterScopes(OpenIdConnectConstants.Scopes.Email,
            OpenIdConnectConstants.Scopes.Profile);

        options.AllowImplicitFlow()
            .AllowRefreshTokenFlow();
        options.AddEphemeralSigningKey();
    })
    .AddValidation();
```

This is the configuration for my client that I registered with OpenIddict:

```
var descriptor = new OpenIddictApplicationDescriptor
{
    ClientId = clientId,
    DisplayName = "My Client",
    RedirectUris = {new Uri("https://localhost:5001"), new Uri("https://oidcdebugger.com/debug")},
    Permissions =
    {
        OpenIddictConstants.Permissions.Endpoints.Authorization,
        OpenIddictConstants.Permissions.GrantTypes.Implicit,
        OpenIddictConstants.Permissions.GrantTypes.RefreshToken,
        OpenIddictConstants.Permissions.Scopes.Profile
    }
};
```

And this is the authorization request I am sending

```
https://localhost:44389/connect/authorize?client_id=my-client&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug&scope=openid%20profile%20offline_access&response_type=token%20id_token&response_mode=fragment&nonce=ujihoe7seq
```

Is there anything obvious you can see that I am missing?

**Comment by jerriep** [comment]
FWIW, I had a look at the `OpenIddictTokens` table and it contains no records. I assume this is related?

**Comment by kevinchalet** [comment]
It's actually much simpler: no refresh token can be returned when using the implicit flow. While there's a way to force OpenIddict to issue one by leveraging the events model, I don't recommend it - specially for new applications - as it's a clear violation of the OAuth 2.0/OpenID Connect specifications.

Instead, consider using silent authorization requests (with `prompt=none`). The implicit flow in the samples repo demonstrate how to do that.

**Comment by jerriep** [comment]
Thank you for the reply Kevin. I am actually coming to the conclusion that going with a Personal Access Token based approach is probably going to be less hassle in the long term.

The "clients" in my case is a Google Docs Add-On (and in the future, an Office Add-In). Their support for OIDC and OAuth 2 are questionable and I think I may run into many other issues following that approach.

A personal access token will be much simpler and just as effective.
