### ISSUE TITLE
Authorization Claims Request Parameter Support

### ISSUE THREAD

**Issue by anorborg** [openiddict/openiddict-core#749]
I was looking for a way to augment specific claims based on the context. I realize scope is one way to accomplish this, but was looking for potentially something more granular and found the "claims" Request Parameter here https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter. I was trying to figure out how to implement this in OpenIddict-Core when usering the "userinfo" parameter. I realize I can add the claims to the access_token I return, but how would I make the userinfo endpoint aware of the specified claims? So that it knows to return them? Any guidance would be appreciated as I'm just getting into the more advanced OpenID Connect features. Thanks

**Comment by kevinchalet** [comment]
There's no built-in mechanism for that, but you could store the claims list as a claim in your `ClaimsPrincipal`. You could alternatively store it as an authentication property in `AuthenticationProperties`.

**Comment by anorborg** [comment]
Thanks @PinpointTownes! Forgive my ignorance, but if I and the claims list as a claim to the `ClaimsPrincipal`, that would then place it in the access_token, correct? Then on the call to the userinfo endpoint, it will be available on the current `HttpContext.User`? And in the case of the `AuthenticationProperties`, they would be stored in a cookie? If so how would I access those on the userinfo endpoint?

**Comment by kevinchalet** [comment]
> Forgive my ignorance, but if I and the claims list as a claim to the ClaimsPrincipal, that would then place it in the access_token, correct? Then on the call to the userinfo endpoint, it will be available on the current HttpContext.User?

Correct.

> And in the case of the AuthenticationProperties, they would be stored in a cookie? If so how would I access those on the userinfo endpoint?

Actually no, adding it to `AuthenticationProperties` would also place it in the access token (not as a claim but as a special authentication property). You can access it via `(await HttpContext.AuthenticateAsync("Bearer"))?.Ticket.Properties`.
