### ISSUE TITLE
Visual Studio doesn't seem to support RC2

### ISSUE THREAD

**Issue by haroldma-zz** [openiddict/openiddict-core#75]
Gives a not found when restoring. I've updated the NuGet.config. Downloading the sample projects seems to work but when I try to upgrade one of the templates from VS it just goes haywire.

![image](https://cloud.githubusercontent.com/assets/5519816/13849723/b99a7af8-ec2d-11e5-9c5b-c0570b36b851.png)

Example error:
`The dependency Microsoft.Extensions.Caching.Abstractions 1.0.0-rc2-20247 in project .. does not support framework DNX,Version=v4.5.1.`

**Comment by kevinchalet** [comment]
> Gives a not found when restoring. I've updated the NuGet.config

Congrats, that's the least actionable ticket I've ever read. Do you really think we have psychic debugging skills? :smile: 

FYI, there's currently a NuGet bug that prevents our projects from restoring and compiling correctly. It should be fixed soon, tho.

**Comment by haroldma-zz** [comment]
:laughing: thought that maybe I skipped a step haha

Is the NuGet bug strictly with openiddict or expands to the whole aspnet-contrib?

**Comment by kevinchalet** [comment]
It impacts all the ASP.NET Core projects, including the packages maintained by the ASP.NET team (that don't build correctly on DNX) and the aspnet-contrib projects.

**Comment by shima20** [comment]
So there's no way to use an rc1 version of openiddict?

**Comment by kevinchalet** [comment]
> So there's no way to use an rc1 version of openiddict?

No, absolutely no way.

**Comment by haroldma-zz** [comment]
Seems to be working fine now.

**Comment by shima20** [comment]
Hmm, I'm still having the same issue

**Comment by shima20** [comment]
Same issue still for me.

**Comment by kevinchalet** [comment]
FYI, I've finally found a workaround to make both DNX and CLI work. The new packages are online.
