### ISSUE TITLE
Curious key generation when using Guid keys

### ISSUE THREAD

**Issue by 1619digital** [openiddict/openiddict-core#750]
I'm using  `ReplaceDefaultEntities<Guid>()` ... and curious about how key generation is working.

There's something a bit fishy about the keys in my [OpenIddictAuthorizations] table - they all end the same! I'm not sure it's a big deal, but it is a bit odd. Or, maybe I've just been very lucky and should buy a lottery ticket.

![image](https://user-images.githubusercontent.com/1035220/59964922-5bd88a80-94ff-11e9-8188-233d85f2c099.png)

EDIT - I now see they're sequential (it's the bit in the middle rather than the end). Which is fine I guess as long as they're not exposed, which I don't think they are.  Feel free to ignore, just thought it was curious.

**Comment by kinosang** [comment]
https://en.wikipedia.org/wiki/Globally_unique_identifier
https://microsoft.fandom.com/wiki/Globally_Unique_Identifier

the final 7 octets are a 56-bit host ID in the form specified by the address family

**Comment by kevinchalet** [comment]
Yeah, that's an EF Core/SQL Server thing, not something specific to OpenIddict 😃
