### ISSUE TITLE
AllowHybridFlow not available.

### ISSUE THREAD

**Issue by binq1000** [openiddict/openiddict-core#752]
I'm trying to create a application that uses "code id_token" as response type.
Even if i specify that it should allow all 5 Flows and a custom flow that takes those response types as a parameter, i still get response type not supported.

The client will be a .Net framework 4.6.1 MVC app that uses OWIN. In https://stackoverflow.com/a/33662736/7957165 @PinpointTownes says that just code is not supported, but code and id_token with a specific token implementation would work, but I'm already having trouble just enabling the hybrid flow.

**Comment by kevinchalet** [comment]
The hybrid flow is available when both the code and implicit flows are enabled (using `AllowAuthorizationCodeFlow()` and `AllowImplicitFlow()`). Did you do that?

**Comment by binq1000** [comment]
Hey very sorry, it seems that the 'Unsupported response type' error came from the own code in my authorize method.

I already tried it with both enabled, but the problem was in my own code.
