### ISSUE TITLE
Support Different Refresh Token & Access Token Lifetime For Different Clients

### ISSUE THREAD

**Issue by talhumy** [openiddict/openiddict-core#756]
Hello,
Can I set different token expiration for different clients?

**Comment by kevinchalet** [comment]
Sure: https://stackoverflow.com/questions/42442109/is-there-a-way-to-have-different-ticket-expiry-lengths-in-openiddict

```csharp
ticket.SetAccessTokenLifetime(TimeSpan.FromSeconds(1));
```

**Comment by talhumy** [comment]
Thank you so much :-)
