### ISSUE TITLE
Consider using Darc to manage dependencies

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#759]
Documentation: https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md

The only pain point is that Darc seems to require authentication for some of its core features. We'll need to see if it also applies to public NuGet/MyGet repositories.

**Comment by xperiandri** [comment]
What is the benefit of it?
Is there any introductory video about Darc?

**Comment by kevinchalet** [comment]
The main advantage is the impressive dependencies flow mechanism, that allows sending changes subscriptions: when a package (or a whole set of packages) is updated, a Microsoft-operated bot called Maestro automatically opens a PR with the necessary changes in each repository.

It's also a very convenient way for Arcade to auto-update itself, as Maestro also creates PRs when Arcade itself is updated (e.g https://github.com/aspnet/AspNetCore/pull/13702).

However, it's not clear whether DARC can be used by non-MSFT projects, since most of its features require authentication.

**Comment by anorborg** [comment]
(Hey you considered [dependabot](https://dependabot.com)?. Acquired by github and now free.

**Comment by kevinchalet** [comment]
@anorborg very good idea! Do you know whether it now supports dependencies versions defined in external `.props` files?

https://github.com/openiddict/openiddict-core/blob/dev/eng/Versions.props

**Comment by joaomsa** [comment]
Dependabot does support versions specified in prop files
https://github.com/dependabot/dependabot-core/issues/541#issuecomment-423818311

**Comment by kevinchalet** [comment]
Closing for now, as neither Dependabot nor RenovateBot can currently help us with keeping Arcade up-to-date (which was the most compelling reason to use them).
