### ISSUE TITLE
System.Security.Cryptography.CryptographicException using latest dnx 1.0.0-rc2-20222 clr x86 win

### ISSUE THREAD

**Issue by BearTM** [openiddict/openiddict-core#77]
I've cloned the current version of OpenIddict, and have installed the latest dnx 1.0.0-rc2-20222 clr x86 win. The projects all compile successfully, however I'm encountering a runtime error:

An exception of type 'System.Security.Cryptography.CryptographicException' occurred in Microsoft.AspNetCore.DataProtection.dll but was not handled in user code

`// Add OpenIdConnectServerMiddleware to the ASP.NET 5 pipeline.`
`builder.AddModule("ASOS", 0, map => map.UseOpenIdConnectServer(builder.Options));`

I've attempted to also compile capesean's openiddict-test, and my own RC2 development, and in each case I receive the same runtime exception.

Have I missed an assembly or neglected to update some references in the project?

**Comment by BearTM** [comment]
Exception Detail:

[openiddict-exception.txt](https://github.com/openiddict/openiddict-core/files/185354/openiddict-exception.txt)

**Comment by kevinchalet** [comment]
It's a (terrible) bug in the ASP.NET Core Data Protection stack: https://github.com/aspnet/DataProtection/issues/129

I'm not sure why it's not fixed yet but you can probably disable logging or lower the log level to work around it.

/cc @Eilon @blowdart

**Comment by blowdart** [comment]
Tagging us in the actual data protection issue would have been more useful.

**Comment by kevinchalet** [comment]
You're watching the DP repo, so you should be aware of this bug without needing additional buzzing, no? :santa:

**Comment by blowdart** [comment]
Do you realise how many issues and commits I see every day? If I don't get tagged I don't see it, and as I don't own that repo or triage for it I don't check it.

And tagging me in personal repos ends up in my personal inbox, which always annoys.

**Comment by kevinchalet** [comment]
> And tagging me in personal repos ends up in my personal inbox, which always annoys.

No, what's really annoying is dealing with bugs you - the ASP.NET team - are supposed to triage and fix. TBH, it even became super annoying these days and hearing your silly remarks is not really helpful. I don't expect gratefulness, just a bit of compassion.

Anyway, lesson learned, I won't ping you and I'll ask people to move their issues to the appropriate ASP.NET repos. After all, someone once told me you were paid for that.
