### ISSUE TITLE
Port the AspNet.Security.OpenIdConnect.Extensions tests

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#774]
In 1.x/2.x, OpenIddict relied on a bunch of extensions provided by ASOS as part of the `AspNet.Security.OpenIdConnect.Extensions` package.

When decoupling OpenIddict from ASP.NET Core, most of these extensions have been updated to act on `ClaimsPrincipal` instead of `AuthenticationTicket` (which means what used to be stored in authentication properties is now stored as claims)

We'll need to port the corresponding unit tests: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/test/AspNet.Security.OpenIdConnect.Extensions.Tests/OpenIdConnectExtensionsTests.cs

**Comment by kevinchalet** [comment]
@IgorHrabrov you did a great job with the primitives tests. Would you be interested in porting the `AspNet.Security.OpenIdConnect.Extensions` tests too? 😃

**Comment by IgorHrabrov** [comment]
@PinpointTownes , yes, I can try, you can assign it to me

**Comment by kevinchalet** [comment]
Thanks!
