### ISSUE TITLE
Disable refresh token revocation

### ISSUE THREAD

**Issue by GuidoNeele** [openiddict/openiddict-core#783]
We are having some trouble with our iPhone apps where users are being logged out because the access token couldn't be refreshed. The problem seems to be related to the racing condition that was mentioned in issue https://github.com/openiddict/openiddict-core/issues/462#issuecomment-330270543. 

Currently we are using rolling tokens but I would like to stop with those to keep the refresh tokens alive and prevent this problem. The problem is that I can't just switch because a lot of users will no longer stay logged in, since switching means no refresh tokens will be returned anymore and the current app still thinks it does (resulting in overwriting the refresh token with a null value).

So I need a switch period. The idea I have is to keep using rolling tokens for now but not revoking past refresh tokens like the comment in the code says https://github.com/openiddict/openiddict-core/blob/e1c6ce833cf791bbafc89380eaefff68b97ecc5d/src/OpenIddict.Server/OpenIddictServerOptions.cs#L252
My question is how can I disable automatic revocation of refresh tokens? I don't see a property in the options and haven't found a way in the source code except for the comment mentioning that it can be done.

**Comment by kevinchalet** [comment]
The option mentioned in the XML docs is `DisableTokenStorage()`, that will tell OpenIddict to not store any token in the database. There's currently no option that would do just what you're looking for.

The relevant code is here: https://github.com/openiddict/openiddict-core/blob/ab9b77a8bb1907c2013c802d0cd44c418d79979e/src/OpenIddict.Server/Internal/OpenIddictServerProvider.cs#L140-L203

**Comment by GuidoNeele** [comment]
Thanks for the fast reply! Thought I had a way to give myself some time, but alas. I will turn off background fetch for the iOS app, because it looks like fetch is often triggered while opening the app resulting in two services asking for the token to be refreshed at the same time, one fails and logs out the user.

**Comment by kevinchalet** [comment]
It’s worth noting that all the features that rely on token storage haven’t been ported to the new 3.0 design yet so it’s possible we may have a way to do that in 3.0 (e.g by removing the event handler responsible of revoking previous tokens).

On a related note, I’m desperately looking for code contributors for 3.0. If you’re interested, let me know. You’ll find some details here: https://github.com/openiddict/openiddict-core/issues/736

**Comment by GuidoNeele** [comment]
To be honest I feel I have too little knowledge of the OpenId protocol and security protocols in general to contribute code to the project. I never really looked into the inner workings of it, until today.

**Comment by kevinchalet** [comment]
Well, the two most important tasks consist in adding unit tests for the new `IOpenIddictServerEventHandler` implementations and porting existing functional tests from previous versions, which shouldn't require any particular security knowledge, and can easily be split if you don't want to/can't contribute to the entire thing 😄

https://github.com/openiddict/openiddict-core/issues/761
https://github.com/openiddict/openiddict-core/issues/762

**Comment by GuidoNeele** [comment]
I can't promise you anything but I'll have a look this weekend.
