### ISSUE TITLE
Add unit tests for the new OpenIddict.Validation, OpenIddict.Validation.AspNetCore, OpenIddict.Validation.Owin, OpenIddict.Validation.DataProtection and OpenIddict.Validation.ServerIntegration handlers

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#807]
Starting with 3.0, most of the validation logic is now contained in implementations of `IOpenIddictValidationHandler<TContext>`, that can be easily unit-tested without using `TestServer`. As part of the 3.0 work, we need to add unit tests for all these handlers.

**Comment by gustavdw** [comment]
I've started on this one, working on the validation handlers at the moment.

**Comment by kevinchalet** [comment]
@gustavdw excellent, thanks for contributing! 👏

**Comment by kevinchalet** [comment]
@gustavdw don't hesitate to ping me if you have any question or need help.
