### ISSUE TITLE
ResourceController message API is always returning Bad Request for me

### ISSUE THREAD

**Issue by noizecamp** [openiddict/openiddict-core#811]
I am trying to use MVC Client and Server sample applications. Everything works fine until Message API endpoint is invoked. User is always null for me, hence throwing bad request. I am still a bit new to this OIDC implementation so any help would be grateful.

P.S. I tried decorating the method with Authorize attribute but did not work as well.

var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return BadRequest();
            }

**Comment by kevinchalet** [comment]
What OpenIddict version do you use?

**Comment by noizecamp** [comment]
Version 3.0.0 Alpha 1 I suppose. I did not do much. Just cloned the dev branch and ran Mvc.Server and Mvc.Client to test out the flow. Everything was okay till I reach the following point but clicking on "Query the resource controller" gives me the bad request. 

![image](https://user-images.githubusercontent.com/11703462/65888371-fe8f8780-e3d1-11e9-9291-70e178d0b453.png)

**Comment by kevinchalet** [comment]
The validation handler was reintroduced very recently (less than 3 days ago). Are you sure your clone has the latest commits?

**Comment by noizecamp** [comment]
I pulled the latest codes and that fixed it. Thank you!
