### ISSUE TITLE
Port the AspNet.Security.OpenIdConnect.Primitives tests

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#817]
As part of 3.0, we'll need to port the ASOS primitives tests to OpenIddict: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/tree/dev/test/AspNet.Security.OpenIdConnect.Primitives.Tests

The new primitives live here: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.Abstractions/Primitives

Note: a few tests will need to be added to test the new `TryGetParameter` methods in `OpenIddictMessage` and `OpenIddictParameter`. Tests for `OpenIddictExtensions.GetResponseTypes()` will also be needed.

**Comment by IgorHrabrov** [comment]
Hello @PinpointTownes, I can help here.

**Comment by kinosang** [comment]
@IgorHrabrov PRs are welcome :)

**Comment by kevinchalet** [comment]
@IgorHrabrov excellent, thanks! Let us know if you need help! 👏
