### ISSUE TITLE
What do I need to do to enable SSL

### ISSUE THREAD

**Issue by kairohmer** [openiddict/openiddict-core#82]
Hi,
I'm wondering if there are any changes in the setup to enable https.
I changed the IIS Express settings of the sample server. The page can be accessed in the browser, but the postman test described at the bottom of the startup.cs fails after waiting a longer time. (... I updated the authentication and token url)

while listening on http everything works as expected.

Thanks!

**Comment by kevinchalet** [comment]
Hey,

AFAIK, having the override headers middleware and the IIS platform handler middleware in the Startup class should be enough for IIS Express + SSL to work correctly (assuming VS is correctly updating the IIS settings).

You should ping @guardrex on JabbR, he's definitely the guy to ask :smile:

**Comment by guardrex** [comment]
@kairohmer Take a look at ...

https://github.com/aspnet/Home/issues/1331
https://github.com/aspnet/Hosting/issues/629 (scroll down about half-way in the discussion)

If you're talking about the latest bits for `WebHostBuilder` and `Microsoft.AspNetCore.Server.IISIntegration`, there are recent Announcements ...

https://github.com/aspnet/Announcements/issues/163
https://github.com/aspnet/Announcements/issues/164

[EDIT] Although Chris's comment here is old, this is the kicker that it should work: https://github.com/aspnet/Home/issues/1003
