### ISSUE TITLE
Authenticated request has an incorret RoleClaimType

### ISSUE THREAD

**Issue by NicolasDorier** [openiddict/openiddict-core#828]
I am using OpenIddict2.0.

My `UserManager` create a principal when it treat the OpenIdRequest, this `UserManager` is using the ClaimType `role`.

Then, when the user is using the token for accessing a resource, the `Identity.RoleClaimType` is set to `http://schemas.microsoft.com/ws/2008/06/identity/claims/role` instead of `role`.
The claim `role` is included in the principal, but because it is not `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`, `ClaimsPrincipal.IsInRole` returns false.

Is there a way for me to customize how OpenIddict is creating the ClaimsPrincipal to fix this?

**Comment by kevinchalet** [comment]
Same root cause as https://github.com/openiddict/openiddict-core/issues/829: the claim types are not stored in JWT tokens, so you must set them yourself.

In 2.0, the MSFT JWT handler is what validates JWT tokens so you'll have to configure it to use different values. Here's how you can do that: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Validation/OpenIddictValidationOptions.cs#L88-L89

**Comment by NicolasDorier** [comment]
Awesome, this make sense thanks!

**Comment by kinosang** [comment]
How's it going with OpenIddict 3.0 (beta2) for `NameClaimType` and `RoleClaimType`? I have tried to set those options but not work.

```
.AddValidation(options => {
...
    options.UseIntrospection();
...
    options.Configure(config => {
        config.TokenValidationParameters.AuthenticationType = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
        config.TokenValidationParameters.NameClaimType = "name";
        config.TokenValidationParameters.RoleClaimType = "role";
    });
}
```

**Comment by kevinchalet** [comment]
The `NameClaimType`/`RoleClaimType` are currently not honored when using introspection, as the `ClaimsIdentity` is not created by IdentityModel but by OpenIddict in this case.

I opened https://github.com/openiddict/openiddict-core/issues/1026 to track that. It's trivial to fix, so let me know if you're interested in sending a PR 😄

**Comment by kevinchalet** [comment]
It will be fixed in the next release. In the meantime, it's very easy to work around using a tiny handler that runs after `PopulateClaims` and recreates the identity with the correct name/role claim types:

```csharp
options.AddEventHandler<HandleIntrospectionResponseContext>(builder =>
    builder.SetOrder(Introspection.PopulateClaims.Descriptor.Order + 1_000)
        .UseInlineHandler(context =>
        {
            if (context.Principal != null)
            {
                var identity = (ClaimsIdentity) context.Principal.Identity;
                identity = new ClaimsIdentity(identity.Claims,
                    context.Options.TokenValidationParameters.AuthenticationType,
                    context.Options.TokenValidationParameters.NameClaimType,
                    context.Options.TokenValidationParameters.RoleClaimType);

                context.Principal = new ClaimsPrincipal(identity);
            }

            return default;
        }));
```
