### ISSUE TITLE
Identity.AuthenticationType is not OpenIddictValidationDefaults.AuthenticationScheme

### ISSUE THREAD

**Issue by NicolasDorier** [openiddict/openiddict-core#829]
I made a bunch of AuthorizationHandlers each handling their special type of identity.

For example, I can use this for the cookie authorization handler. (Where `Policies.CookieAuthentication` is the name of my authentication Scheme, `Identity.Application`)

```csharp
protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, PolicyRequirement requirement)
{
    if (context.User.Identity.AuthenticationType != Policies.CookieAuthentication)
        return;
```

However, for openiddict I needed to do

```csharp
protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, PolicyRequirement requirement)
{
    if (context.User.Identity.AuthenticationType != "AuthenticationTypes.Federation")
        return;
```
Which is different from `OpenIddictValidationDefaults.AuthenticationScheme`.

Is it normal?

**Comment by kevinchalet** [comment]
> Is it normal?

Yes, it is. The authentication type is typically not stored in JWT tokens (unlike Data Protection tokens) so it's never preserved between the moment you create the principal and the moment you consume it. When deserializing a JWT token, the authentication type is arbitrarily set by IdentityModel to `AuthenticationTypes.Federation`, which is the default type: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L128

If you need full fidelity for the authentication type, you can switch to Data Protection tokens.

**Comment by kevinchalet** [comment]
Note: if you don't like the `AuthenticationTypes.Federation` value, you can override it in the token validation parameters, in either the MSFT JWT handler (2.0) or the OpenIddict validation handler (3.0).

**Comment by NicolasDorier** [comment]
I'll leave it at Federation, if it is not a bug then all is fine
