### ISSUE TITLE
AccessFailedCount on Master Slave cluster

### ISSUE THREAD

**Issue by phonglt7** [openiddict/openiddict-core#830]
Hi, we have an issue happened after the database move to cluster.
We have a writer database and a reader database.

After moving, the AccessFailedCount didn't increase anymore after a failed attempt.

Here is the debug output we got
<img width="1675" alt="Untitled" src="https://user-images.githubusercontent.com/46190930/66798013-d6a63500-ef36-11e9-9014-beac1bd97e93.png">

As we observe, it happened when the `CheckPasswordSignInAsync` calls `UserManager.AccessFailedAsync`.

Please help me on this case.

Thanks,
Phong.

**Comment by kevinchalet** [comment]
Hey,

It's not clear to me how your question is related to OpenIddict. For general questions about Identity, you should go to https://github.com/aspnet/AspNetCore/issues and post a ticket there, so that the ASP.NET team can take a look at your problem.

**Comment by phonglt7** [comment]
The reason is that the original code which is using OpenIddict worked fine for the Single database.
However it didn't on Cluster, then I assume that it's must be some kind of config of OpenIddict. 
I wonder if you ever applied OpenIddict on the cluster database?

**Comment by kinosang** [comment]
@phonglt7 `UserManager.AccessFailedAsync` is part of AspNetCore, not OpenIddict. Please use https://github.com/aspnet/AspNetCore/issues to report your problem.
