### ISSUE TITLE
The 'offline_access' scope is not allowed.

### ISSUE THREAD

**Issue by PaulCombal** [openiddict/openiddict-core#835]
Hello,

Forgive me if it's a basic question, but I could not find an answer to it online or in the docs.
I'm trying to generate refresh tokens for my app, but I can't get an authorization code since I'm getting the error: `invalid_request The 'offline_access' scope is not allowed.`

I'm getting this error on this URL: 
`http://localhost:5001/connect/authorize?response_type=code&redirect_uri=myuri&client_id=mvc&scope=openid+profile+email+roles+offline_access`

Everything works fine without offline_access, except that I can't have refresh tokens..

Do you need more info from me? Can anyone help me out on this?

Thanks

**Comment by kevinchalet** [comment]
Hey,

Are you sure the refresh token flow is allowed in the OpenIddict server options?
Not enabling it causes this error:

https://github.com/openiddict/openiddict-core/blob/2abdd3c3f906f9015291f4dbab6b64c6ed38f006/src/OpenIddict.Server/Internal/OpenIddictServerProvider.Authentication.cs#L175-L184

You'll also need to make sure application is granted the `OpenIddictConstants.Permissions.GrantTypes.RefreshToken` permission for things to work flawlessly (otherwise, you'll get a `The client application is not allowed to use the 'offline_access' scope` error).

**Comment by PaulCombal** [comment]
Thank you very much, I fixed the issue using this in Startup:
`options.AllowAuthorizationCodeFlow().AllowRefreshTokenFlow();`

Though, I still don't get a refresh token when I get the access token, which I would like.

Here is the code of my request to get an access token:
```csharp
            var form = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("grant_type", "authorization_code"),
                new KeyValuePair<string, string>("code", code.Code),
                new KeyValuePair<string, string>("redirect_uri", code.RedirectUri),
                new KeyValuePair<string, string>("client_id", "mvc"),
                new KeyValuePair<string, string>("client_secret", "mysecret")
            };

            var request = new HttpRequestMessage(HttpMethod.Post, "http://localhost:5001/connect/token")
            {
                Content = new FormUrlEncodedContent(form)
            };
```

And using the debugger on my authorization server, I can see that the ticket I create has the scope `offline_access`. From the samples:

```csharp
            // Create a new authentication ticket, but reuse the properties stored
            // in the authorization code, including the scopes originally granted.
            var ticket = await CreateTicketAsync(request, user, info.Properties);

            return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
```
Did I miss something?

**Comment by kevinchalet** [comment]
2 things that would help determine what's going on:
  - The ASP.NET Core logs, with the default log level lowered to Trace.
  - The source of `CreateTicketAsync()` to be sure there's nothing wrong there.

FWIW, the `CreateTicketAsync()` helper used in the samples proved to be too confusing so I updated the 2.0.1 samples (in the samples repo) to use a simpler and more explicit approach, similarly to what will be recommended for OpenIddict 3.0.

**Comment by PaulCombal** [comment]
Good to know, I'll probably migrate when I will have time. After digging a little more into the issue, it is definitely a deserialization issue on my end, sorry for bothering you. I think this issue has been resolved.

Thank you so much for your help!

**Comment by kevinchalet** [comment]
C'était avec plaisir :smile:
