### ISSUE TITLE
EntityFramework.Models giving warning with .NETCoreApp3.0

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#836]
If i include version 2.0.1 or even the latest 3.0.0-alpha1-1184 preview of this project, then i get the following warning, even though it all builds and works correctly

> Package 'OpenIddict.EntityFramework 2.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'.

**Comment by kevinchalet** [comment]
The EF 6 package shipping with OpenIddict 2.x only supports .NET Framework >=4.6.1 so it's not meant to be used on .NET Core, tho' you shouldn't hit any particular issue.

For official .NET Core support, use the OpenIddict 3.x nightly builds, that reference EF 6.3 and are cross-compiled for both `net461` and `netstandard2.1`.

> the latest 3.0.0-alpha1-1184 preview of this project

This is not the latest version. Make sure you use the new OpenIddict MyGet feed, whose address is mentioned in the README.
