### ISSUE TITLE
Metadata requests must be made via GET

### ISSUE THREAD

**Issue by CryptoMinerd** [openiddict/openiddict-core#840]
@PinpointTownes I think I may have a quick bug fix submission for you. I am not totally sure so forgive if I messed up how to fix it.

Symptom: When running metadata discovery against the new 3.0.0-alpha bits #758 I noticed that it will accept either a GET or POST request.

Issue: The specification says only GET is allowed. See http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

Resolution: I ran the code and figured out how handler is called. I noticed that a handler that accepts only GET is registered here: https://github.com/openiddict/openiddict-core/commit/9ee38c0efb05b2413a0f768bb2694134bbbb68aa#diff-1f8e566cd90f8a70d4db0c1a21fa958bR25

Somehow ExtractGetOrPostRequest handler is still getting called?

Ah... ha found it: https://github.com/openiddict/openiddict-core/commit/9ee38c0efb05b2413a0f768bb2694134bbbb68aa#diff-45728cc9ac32ab3a5ff26569a97c5de9R322

Line should read:

`.UseSingletonHandler<ExtractGetRequest<TContext>>()`

Instead of:

`.UseSingletonHandler<ExtractGetOrPostRequest<TContext>>()`

Causation: VS auto-complete or copy-paste issue... :-)

**Comment by kevinchalet** [comment]
Haha, nice catch and thanks for the bug report :smile:

> Causation: VS auto-complete or copy-paste issue... :-)

Definitely a copy and paste issue here 😄

**Comment by kevinchalet** [comment]
Fixed (both the ASP.NET Core and OWIN hosts were impacted, because well, bad copy and paste 🤣)
