### ISSUE TITLE
Is there a way to get this to work with RC1?

### ISSUE THREAD

**Issue by renatohh** [openiddict/openiddict-core#85]
Is there a way to get this to work with RC1?
thanks

**Comment by kevinchalet** [comment]
Unfortunately, no: OpenIddict will only work with RC2.

FWIW, the ASP.NET team is finalizing the RC2 packages. They will be likely released in the next few weeks.

**Comment by BrainCrumbz** [comment]
Just a recent update on RC2 state of the art: http://www.hanselman.com/blog/AnUpdateOnASPNETCore10RC2.aspx

**Comment by kevinchalet** [comment]
@BrainCrumbz FYI, OpenIddict now targets the RC2 "CI release" packages: https://github.com/openiddict/openiddict-core/issues/91#issuecomment-213397775.
