### ISSUE TITLE
If the user denies resource access, redirect to home doesn't work in client sample

### ISSUE THREAD

**Issue by Rathavithey** [openiddict/openiddict-core#852]
An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
<img width="405" alt="11" src="https://user-images.githubusercontent.com/29189233/70128044-ca289800-16ae-11ea-8197-1a49c65916ba.PNG">

After we click No, Do Not Allow button, It's show image error as below
<img width="923" alt="22" src="https://user-images.githubusercontent.com/29189233/70128059-d0b70f80-16ae-11ea-964b-2b426782e6bd.PNG">

Kindly help me as possible.

**Comment by kevinchalet** [comment]
I don't think you're using OpenIddict, to which this repository is entirely dedicated... our MVC client 3.0 sample correctly handles `access_denied` errors.

**Comment by Rathavithey** [comment]
I am using OIDC.
And try to create a test project to connect with Identity server 4
It's okay if I accepted consent, But it's getting an error when I Don't Allow the consent.
May you can tell more details about my issue?
