### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#858]
We'll need to:
  - Introduce new APIs to get localized versions of the application display name and scope description/display name.
  - Use `IStringLocalizer` to localize all the error messages used by OpenIddict. We'll store the resources as .resx files.

**Comment by kevinchalet** [comment]
@hishamco @agriffard @sebastienros FYI, OpenIddict 3.0 beta 3 has been entirely updated to use `ResourceManager`/`IStringLocalizer` and all its resource strings are now available in French (except exceptions, assertions and log messages).

It would be nice if we could determine together whether additional languages should be added in the next beta versions to offer a complete localization experience in the OpenID module.

**Comment by sebastienros** [comment]
Interesting to find out how we can handle po files for external libraries. I assume we canthe po extractor on openiddict directly. Then should the po files be handled in openiddict, or/and could it be part of the module in OC. Or could OC be able to find the po files as embedded resources, but still work wit h local files if provided.

**Comment by hishamco** [comment]
AFAIK OC is disabled the `ResourceManagerStringLocalizer` by default, further more OC are using PO files

**Comment by hishamco** [comment]
Seems I clicked the "Comment" button after some seconds from Seb's comment :)

>  I assume we canthe po extractor on openiddict directly.

Disagree, because this will limit the openiddict in terms of localization, I agree with you if it's a part of the module in OC, or find away to map OC po files localization into openiddict resx files

**Comment by kevinchalet** [comment]
@sebastienros PO files were a very interesting option, but depending on an OrchardCore package was a bit problematic for versioning due to the "circular" dependency this would have introduced. Instead, the culture neutral resources are stored in a .resx file and Arcade automatically produces XLIFF files for the languages we want to support. The XLIFF files are then used to build satellite assemblies that are all stored in the `OpenIddict.Abstractions` package (I don't plan to create a dedicated package per culture at this point).

> AFAIK OC is disabled the `ResourceManagerStringLocalizer` by default, further more OC are using PO files

@hishamco yeah, that was one of the pain points. Luckily, I was able to solve it by simply registering a `IStringLocalizer<OpenIddictResources>` service that is based on `ResourceManager`. This way, the open generic service `IStringLocalizer<T>` is not used for the OpenIddict localizer:

https://github.com/openiddict/openiddict-core/blob/8085ca176b08d76c98ccb75084fd336df61af3b3/src/OpenIddict.Core/OpenIddictCoreExtensions.cs#L105-L115

**Comment by kevinchalet** [comment]
Closing this issue, as the infrastructure is now in place. If you have ideas on additional languages we should support, please post there: https://github.com/openiddict/openiddict-core/issues/1051.

**Comment by kevinchalet** [comment]
@hishamco BTW, would you be interested in providing the Arabic translation? At the time of writing, there are ~120 strings to translate. XLF files can be easily opened in tools like Poedit for a complete GUI experience.

Existing translations can be found here: https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.Abstractions/Resources/xlf

Please let me know if you're interested 😃

**Comment by hishamco** [comment]
Sure, I hope to find a time to do it ASAP

**Comment by kevinchalet** [comment]
@hishamco fantastic, thanks a lot! 😃 

I opened https://github.com/openiddict/openiddict-core/pull/1058 to add `OpenIddictResources.ar.xlf` to the repo. Let me know if you have any question/remark.

**Comment by hishamco** [comment]
Just assign it to me, I'm cloning the repo, if there's anything related I will rely there ...
