### ISSUE TITLE
Investigate using endpoint routing in the ASP.NET Core host

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#859]
https://github.com/aspnet/AspNetCore/issues/17615

These 3 modes are currently supported by OpenIddict's ASP.NET Core 2.x and 3.x host:

  - Pass-through mode (enabled globally - per endpoint - using e.g `options.UseAspNetCore() .EnableAuthorizationEndpointPassthrough()`): in this case, OpenIddict extracts the OIDC payload, validates it and allows the rest of the ASP.NET Core pipeline to be invoked.

  - Pass-through mode (enabled dynamically using OpenIddict's `context.SkipRequest()` API): it works like the previous mode, but pass-through is configured dynamically, per request, by calling `context.SkipRequest()` from an OpenIddict event handler. This is commonly used to transparently handle authorization requests that can processed immediately (e.g when `prompt=none` is specified and the user is already logged in) without preventing other requests from reaching the MVC authorization controller (typically, when you need to render a consent form).

  - Non-pass-through mode: in this case, requests are exclusively handled using OpenIddict's events model. This is the expected operating mode for things like discovery, introspection or revocation requests, but we shouldn't prevent them from being handled manually later in the pipeline.

We'll need to determine how ASP.NET Core 5.0's plans may affect corresponding scenarios.

@Tratcher could endpoint routing be used with these 3 modes? I'm not too concerned by the "routing" aspect - which seems flexible enough - but the "endpoint" part seems way more limiting in our case, as there's no way for an endpoint to declare it's not going to "handle" a request.

**Comment by Tratcher** [comment]
> @Tratcher could endpoint routing be used with these 3 modes? I'm not too concerned by the "routing" aspect - which seems flexible enough - but the "endpoint" part seems way more limiting in our case, as there's no way for an endpoint to declare it's not going to "handle" a request.

Endpoints would be for the non-pass through mode. You'd need to opt-out of endpoints for the other two.

**Comment by kevinchalet** [comment]
That's unfortunate as it's fairly unpractical for average users.

Correct me if I'm wrong but the only point of using endpoint routing is to avoid instantiating handlers that are eventually not going to handle requests that don't match the expected URL path. Couldn't you only use the "routing" part while still keeping `HandleRequestAsync()`?

Something like that (in `AuthenticationMiddleware`):

```csharp
var endpoint = context.GetEndpoint();
if (endpoint != null)
{
    var scheme = endpoint.Metadata.GetMetadata<AuthenticationEndpointMetadata>()?.Scheme;
    if (!string.IsNullOrEmpty(scheme))
    {
        var handlers = context.RequestServices.GetRequiredService<IAuthenticationHandlerProvider>();

        var handler = await handlers.GetHandlerAsync(context, scheme.Name) as IAuthenticationRequestHandler;
        if (handler != null && await handler.HandleRequestAsync())
        {
            return;
        }
    }
}
```

**Comment by Tratcher** [comment]
Clever, we might be able to do something like that. You'd still need to run HandleRequestAsync for some other scenarios (Negotiate), and you'd still need a plan to handle fall-through (Skip) that still allowed other HandleRequestAsync's to run.

**Comment by kevinchalet** [comment]
Excellent, good to know we're on the same page!

/cc @rynowak I believe you're the Routing Master, so please don't hesitate if you have any remark regarding the scenarios I mentioned 😄

**Comment by Tratcher** [comment]
Looking at this sample again, I'm not sure it accomplishes anything new. Either way you need something like scheme.Options.UseEndpoints to create the endpoints, so you can use that to skip them in the auth middleware. The endpoint definition can call HandleRequestAsync itself, it doesn't need the auth middleware to do that.

**Comment by kevinchalet** [comment]
> The endpoint definition can call HandleRequestAsync itself, it doesn't need the auth middleware to do that.

The problem is that it's normally done by `app.UseEndpoints()`, which is basically the very last middleware to be invoked. Even if the "endpoints" stack was updated to include a "non-terminating" option,, you can no longer decide to invoke the rest of the pipeline at that stage, since there's basically nothing registered after `app.UseEndpoints()` (except the 404 handler). 

When `HandleRequestAsync` is invoked by the authentication middleware, you don't have this problem, since it's usually registered super early.

**Comment by Tratcher** [comment]
But `Skip` isn't enough there if you want to run a different endpoint, you actually have to replace the endpoint or re-run routing.

**Comment by Tratcher** [comment]
Again, if you want a fall through option then you need to completely opt out of using endpoints for auth.

**Comment by kevinchalet** [comment]
> But Skip isn't enough there if you want to run a different endpoint, you actually have to replace the endpoint or re-run routing.

It's pretty much why I think routing and endpoints should be decoupled. We'd have very few design issues if authentication could use routing without endpoints, that are way too limited.

> Again, if you want a fall through option then you need to completely opt out of using endpoints for auth.

I suppose that's what I'll end up doing, sadly.

**Comment by rynowak** [comment]
I don't have a super ton of context what's going on here 😁 - what can I help with?

> It's pretty much why I think routing and endpoints should be decoupled. 

Routing (selecting an endpoint) is decoupled from the rest of the pipeline (make decisions based on an endpoint's metadata/run the endpoint).  Hopefully that's clear enough, but you don't have to be "the router" to set the endpoint for a request.

**Comment by Tratcher** [comment]
@rynowak let's take the design discussion back to aspnet/AspNetCore#17615.

**Comment by kevinchalet** [comment]
@rynowak oops, sorry, I read somewhere that you and @Tratcher had a chat about endpoint routing and authentication, so I assumed you had the full context already 😄 

I opened this thread so we can discuss the special needs OpenIddict has - [detailed in my initial post](https://github.com/openiddict/openiddict-core/issues/859#issue-535098171) - and whether it could be updated to use endpoint routing as part of ASP.NET Core 5.0 if such a change was eventually adopted.

Routing - stricto sensu - is likely not going to be much of an issue for me, but endpoints are currently too limited for OpenIddict to use them: they are invoked fairly late in the request processing pipeline and don't support "composition": you can't declare within an endpoint delegate that you're not going to fully handle the request and that you'd want the request to be processed by the rest of the pipeline, as you can do with middleware and authentication handlers.

Yet, OpenIddict relies on being able to analyze a request, validate it **and** give back control to the rest of the pipeline to take further actions. For instance, here's what happens when it receives an OpenID Connect authorization request:

  - It extracts the OIDC payload from the HTTP request (either from the form if it's a POST request or from the query string if it's a GET request).

  - It validates the OIDC request (e.g do we have all the mandatory parameters? Is the `redirect_uri` correctly formed? Do we recognize the `client_id`? Is the `redirect_uri` a registered callback?)

  - Once it's done, how things work depend on whether the developer enabled pass-through or not:
      - If pass-through was not enabled, the request must be handled using OpenIddict's events model (it's very similar to ASP.NET Core's authentication handlers events model).

      - If pass-through was enabled, OpenIddict asks ASP.NET Core to keep invoking the other middleware in the pipeline. The typical case is that the authorization request will be eventually handled by a MVC controller or a Carter module, where the developer will either return a consent view or do `return SignIn(...)` to trigger an authorization response. You can take a look at https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AuthorizationController.cs#L90 for an example.

The problem I have is that pass-through is not possible with ASP.NET Core endpoints, so if "endpoint routing" - i.e routing **and** endpoints - was used by ASP.NET Core's authentication handlers, it's not something we could leverage, unfortunately.

**Comment by rynowak** [comment]
> Routing - stricto sensu - is likely not going to be much of an issue for me, but endpoints are currently too limited for OpenIddict to use them: they are invoked fairly late in the request processing pipeline and don't support "composition": you can't declare within an endpoint delegate that you're not going to fully handle the request and that you'd want the request to be processed by the rest of the pipeline, as you can do with middleware and authentication handlers.

Based on this I don't think Endpoints are a good fit for what you're trying to do.

**Comment by kevinchalet** [comment]
Roger, @rynowak. Now, the question is: could authentication handlers depend on routing without forcing the use of endpoints?

Because AFAICT, the motivation to use that is to avoid creating instances of authentication handlers that are not going to handle the request (i.e because the request path doesn't match the registered path), which is more a routing concern than anything else.

**Comment by rynowak** [comment]
> Because AFAICT, the motivation to use that is to avoid creating instances of authentication handlers that are not going to handle the request (i.e because the request path doesn't match the registered path), which is more a routing concern than anything else.

I'll catch up with @Tratcher on this discuss then. It sounds like there's a desire to improve this, but I'm not sure why it requires anything other than looking at the currently selected endpoint.

**Comment by kevinchalet** [comment]
Looks like https://github.com/dotnet/aspnetcore/issues/17615 hasn't been very active lately so closing for now.
