### ISSUE TITLE
EnableRevocationEndpoint works with no auth

### ISSUE THREAD

**Issue by tanveer-ali** [openiddict/openiddict-core#860]
There are 2 issues which I didn't any solution yet.
using version 2.0.1 

- Using this endpoint options.EnableRevocationEndpoint("/revoke"), I created one endpoint and added some logic but the endpoint never gets hit. However, if I make a request to that endpoint providing the refresh token in the token field all works but just for that refresh token. I need to revoke all refresh tokens for that user which I am unable to do using this endpoint.

- EnableRevocationEndpoint("/revoke") works with no auth provided which it shouldn't as I need this endpoint to work by providing the authentication

**Comment by kevinchalet** [comment]
> I need to revoke all refresh tokens for that user which I am unable to do using this endpoint.

You'll need to create a custom event handler for `HandleRevocationRequestContext` and do that manually, as OpenIddict only revokes the received token.

> EnableRevocationEndpoint("/revoke") works with no auth provided which it shouldn't as I need this endpoint to work by providing the authentication

I'm not able to reproduce that: if I send a revocation request without a `client_id`, it returns an error:

```json
{
    "error": "invalid_request",
    "error_description": "The mandatory 'client_id' parameter is missing."
}
```

If the request don't specify the `client_id` (assuming the client is a confidential client), I get the expected error:

```json
{
    "error": "invalid_client",
    "error_description": "The 'client_secret' parameter required for this client application is missing."
}
```

And if the credentials are invalid... I also get the correct error:

```json
{
    "error": "invalid_client",
    "error_description": "The specified client credentials are invalid."
}
```

**Comment by tanveer-ali** [comment]
Actually I was expecting to verify access token before allowing the revoke endpoint but I guess that's not the standard as I looked here:
https://connect2id.com/products/server/docs/api/token-revocation

I wanted this revocation to be done from SPA which doesn't have client secret as its a public site. So I guess my option is to perform this through confidential client?

Also I added a confidential client in the database manually but i am receiving this error

```
{
    "error": "unauthorized_client",
    "error_description": "This client application is not allowed to use the revocation endpoint."
}
```

**Comment by kevinchalet** [comment]
> I wanted this revocation to be done from SPA which doesn't have client secret as its a public site. So I guess my option is to perform this through confidential client?

No, it works with public clients too.

> Also I added a confidential client in the database manually but i am receiving this error

This error sounds pretty clear to me: you forgot to grant the revocation endpoint permission to your client.

**Comment by tanveer-ali** [comment]
Thanks right this works with public clients too but revoking tokens with public clients without any credentials isn't secure so it's better to use it with some backend API i.e. confidential client which will at least be secure. Thanks for the answers @PinpointTownes

**Comment by kevinchalet** [comment]
If your "proxy" endpoint simply accepts a token and calls the authorization server with its credentials, I'm not sure how this makes it "more secure". And frankly, there are much more evil things to do with a leaked token than to revoke it... 🤣

**Comment by tanveer-ali** [comment]
what I mean is that at least I can an endpoint in the backend API which is JWT protected from the client and that API i.e. confidential client can revoke it. For revocation, you don't want anyone to revoke any token so can't do this with the public client
