### ISSUE TITLE
How can I get the authorization code for the user who is currently logged in?

### ISSUE THREAD

**Issue by ianpowell2017** [openiddict/openiddict-core#862]
Hello, 

I am hoping someone can advise me how i can get an authorization code for the currently logged in user.  I am trying to implement App to App Linking for an Amazon project. On this [page](https://developer.amazon.com/docs/account-linking/app-to-app-account-linking.html#step-6), it says 
```The security provider that you use must authorize calls from the app to the app's backend server and provide a server-side API to get the authorization code for the user who is currently logged in to your app. (That is, it needs to provide the authorization code for the user's account in your service.) Alexa will exchange this code for your user's access token to access the user's resources.```
Would someone advise or at least point me in the right direction.

Thanks in advance for any help you can offer me.

**Comment by kevinchalet** [comment]
Hey,

Isn't that the classical authorization code you get as part of the code flow? You'll need to start an authorization dance using an OIDC client to get one so you can send it to Amazon. You can take a look at the code flow demo to see how it's done.

**Comment by ianpowell2017** [comment]
Hi, thanks for taking the time to respond.  Is there any other way to do this?
The steps Amazon require do not permit another oauth code flow dance.

**Comment by kevinchalet** [comment]
Nope. And it's not clear to me why you'd want another way to achieve that. What's wrong with the standard flow?

**Comment by ianpowell2017** [comment]
Personally, I don't see anything wrong with the standard flow.  Except that I am trying to build a system that works with the Amazon flow they've outlined in the link I referred to earlier.

If the customer connects their Amazon account to my website, the OAuth code flow system works fine. Amazon also allows the customer to connect my website to the customers Amazon account (same as earlier just from the other direction), then the process is outlined in the article I linked to earlier.

By allowing the customer to connect my website to the customers Amazon account, I would be able to offer the customer further help.

**Comment by kevinchalet** [comment]
I sadly don't have much free time to dedicate to understanding how Amazon implemented their super weird non-standard flow, but it seems like you could create a client registration for Amazon and initiate an authorization code flow with the `client_id` assigned to Amazon and a `redirect_uri` you own, pointing to a page where you'd intercept the authorization code from the query string and send it to Amazon's services.

It won't be trivial since all this stuff is completely non-standard.

**Comment by ianpowell2017** [comment]
Ok thank you very much
