### ISSUE TITLE
HttpContext.GetOpenIddictServerRequest() is null

### ISSUE THREAD

**Issue by arthas1888** [openiddict/openiddict-core#863]
I'm trying to reproduce the example for OpenIddict 3.x, however when I test with a js client, postman or mobile client (Android) always I get the same error The OpenID Connect request cannot be retrieved, it means when I do a request for connect/token/ this value HttpContext.GetOpenIddictServerRequest() is null, but I don't know how to fill it, the code is the same than the repository so I don't need to share here, thank you for your answer, I will be looking forward...

**Comment by kevinchalet** [comment]
Does your code call `options.UseAspNetCore().EnableTokenEndpointPassthrough()`? Are you sure the route exactly matches the registered endpoint path?

**Comment by arthas1888** [comment]
yes, of course, 

`// Register the ASP.NET Core host and configure the ASP.NET Core-specific options.
                    options.UseAspNetCore()
                           .EnableTokenEndpointPassthrough()
                           .DisableTransportSecurityRequirement(); // During development, you can disable the HTTPS requirement.`

totally, I am using the correct endpoint, when I have to migrate always there are a lot of bugs, because the code change completely so I decided to use Identity Server 4, thanks

**Comment by kevinchalet** [comment]
> totally, I am using the correct endpoint, when I have to migrate always there are a lot of bugs

Yet you're the only one impacted by that bug, that may be in OpenIddict... or in your code.
And luckily, no, the number of bugs reported so far is quite low, specially considering the quite massive refactoring.

> so I decided to use Identity Server 4, thanks

Excellent choice. Since you'll benefit from another free OSS project, consider contributing or sponsoring it.

**Comment by kevinchalet** [comment]
> totally, I am using the correct endpoint

And BTW, no, you're not using "exactly the same address": `/connect/token/` is different from `/connect/token`. In 3.x, the logic that treated such paths as identical was not ported from 2.x but I'll consider changing that to make migration easier.

https://github.com/openiddict/openiddict-core/issues/866

**Comment by arthas1888** [comment]
thank you for everything, the support is so good, I really appreciate your work here, and I like working much more with this library but sadly I had to change  

> Excellent choice. Since you'll benefit from another free OSS project, consider contributing or sponsoring it.
I'm gonna keep that in mind

**Comment by bytefish** [comment]
This is probably really embarrassing on my side, but I stumbled upon the same issue and the problem was, that I was missing a preceeding "/", when defining the TokenEndpointUrl:

```csharp
options.SetTokenEndpointUris("api/connect/token")
```

 This leads to Openiddict not resolving the Enpoint Type and thus the Request from ``GetOpenIddictServerRequest()`` is null. When I am defining it as:

```csharp
options.SetTokenEndpointUris("/api/connect/token")
```

Then everything works as expected.

@kevinchalet Thanks for the great library and documentation. It was a joy to get started with it.

**Comment by kevinchalet** [comment]
@bytefish thanks!

**Comment by sridhargiri** [comment]
I also had this issue then Removed call to services.AddHttpContextAccessor in startup.cs

**Comment by Camuvingian** [comment]
Having `applicationBuilder.UseMvc()` before `applicationBuilder.UseAuthentication` and/or `applicationBuilder.UseAuthorization()` can also cause this issue. A school boy error for sure, but may help someone none-the-less. :]. Thanks to Kevin for all the hard work on this project.

**Comment by zhlavinka** [comment]
> This is probably really embarrassing on my side, but I stumbled upon the same issue and the problem was, that I was missing a preceeding "/", when defining the TokenEndpointUrl:
> 
> ```cs
> options.SetTokenEndpointUris("api/connect/token")
> ```
> 
> This leads to Openiddict not resolving the Enpoint Type and thus the Request from `GetOpenIddictServerRequest()` is null. When I am defining it as:
> 
> ```cs
> options.SetTokenEndpointUris("/api/connect/token")
> ```
> 
> Then everything works as expected.
> 
> @kevinchalet Thanks for the great library and documentation. It was a joy to get started with it.

THANK YOU for adding that. It would have taken me a long time to catch that *facepalm*

**Comment by amadare42** [comment]
Another stupid mistake that can cause this is forgetting to set `app.UseAuthentication()` in Startup.

**Comment by stancoffyn** [comment]
I ran into this issue myself. I had 
`_.SetTokenEndpointUris("token");`
whereas my route for my token on my auth controller was "api/v1.0/Authorization/token" this mismatch was preventing the token from rendering thank you @kevinchalet for the inspiration to check this.

**Comment by selfmadecode** [comment]
in my case I forgot to add 
`app.UseAuthentication();`

**Comment by sorcerb** [comment]
If you have this issue and you use revers proxy (Nginx + Docker) read this: https://github.com/openiddict/openiddict-core/issues/1613
