### ISSUE TITLE
 openiddict-core and Ocelot ApiGateway

### ISSUE THREAD

**Issue by icebergdelphi** [openiddict/openiddict-core#865]
Hello, I have a question, I want to know if there is any example of how to use openiddict-core with Ocelot ApiGateway, because there are only examples with IdentityServer 4 or JWT and ocelot, I have tried to make some example with openiddict-core and Ocelot, but I always have the answer 401 or errors. Thank you so much.

**Comment by kevinchalet** [comment]
Hey,

I'm not super familiar with Ocelot, but AFAICT, it simply uses ASP.NET Core's authentication stack, so you should be able to easily leverage either OpenIddict's validation handler (in 2.x for the default access token type and in 3.x, for both JWT and Data Protection tokens) or the regular JWT bearer handler developed by Microsoft.

If you have a repro app that uses OpenIddict and Ocelot, I don't mind taking a look to ensure things are correctly configured.
