### ISSUE TITLE
How to have OpenIddict.Core dependencies only use RC2 instead of RC3?

### ISSUE THREAD

**Issue by shima20** [openiddict/openiddict-core#87]
How do I prevent OpenIddict.Core to use only the RC2 dependencies instead of RC3

![image](https://cloud.githubusercontent.com/assets/9735056/14540815/de04d5f4-023b-11e6-81e9-18f4f0a7c25f.png)

**Comment by kevinchalet** [comment]
OpenIddict uses the ASP.NET Core RC3 packages as it needs a few bug fixes that are not included in the latest RC2 nightly builds (like the JWT bug).

The "RC2 final" packages should include them so we'll move back to RC2 when they are ready. In the meantime, the RC3 packages should work fine.

**Comment by shima20** [comment]
Thanks @PinpointTownes
