### ISSUE TITLE
Add integration tests for the verification/device endpoints and the device code grant type

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#892]
Device code support was added in 3.0 alpha1 before we started porting the integration tests. Now that it is almost complete, new tests will need to be added for that feature.

**Comment by ajfleming1** [comment]
Is the device code flow ready for test as of today? I was trying to think how many different tests would be needed to cover the flow.

**Comment by kevinchalet** [comment]
> Is the device code flow ready for test as of today?

Yep, I think no non-trivial change will be introduced at this point (I'm quite satisfied of the result).

> I was trying to think how many different tests would be needed to cover the flow.

Hard to say how many exactly, but probably a hundred at most. That said, a very large part can actually be copied from existing integration tests:

  - For the device endpoint: the tests can all be adapted from `OpenIddictServerIntegrationTests.Exchange.cs`, as the device endpoint is quite similar to the token endpoint, but much simpler (we'll just need the client, permissions and scopes validation tests).

  - For the verification endpoint: this endpoint is mostly designed as pass-through thing and there's not much logic (e.g there's no parameter validation). This part only consists in copying the `Extract*Request`/`Validate*Request`/`Handle*Request`/`Apply*Response` tests from another endpoint (e.g `ExtractTokenRequest_AllowsHandlingResponse`)

  - For the token endpoint: the device device grant works like the authorization code grant, we should be able to copy the existing tests that validate things like the presenters are handled correctly.

Let me know if you're still interested 😄

**Comment by ajfleming1** [comment]
I am still interested but I do have a full time job and I don't know how urgent this is. I haven't looked at the code very much so I don't think think I can commit to more than completing a few tests a week sight unseen. Also, I will probably have questions along the way. If that's okay with you I can get started.

**Comment by kevinchalet** [comment]
Thanks!

Since the device code support is a totally new feature, adding tests is much less urgent as there's no risk of regression for people who decide to migrate from a previous version.

Feel free to split the task into multiple PRs if it's easier for you. And don't hesitate to ask questions if you have any 😄

**Comment by ajfleming1** [comment]
Just for my own curiosity, in general what is the design pattern used for OpenIddict? I am getting a little confused when I look at some of the classes like OpenIddictServerHandlers and all the Descriptors. I just want to be able to understand from an OOP point of view how everything is organized and the execution flows from an initial request to providing a response.

**Comment by kevinchalet** [comment]
OpenIddict 1.x/2.x and ASOS 1.x/2.x historically used the same approach as Katana's `OAuthAuthorizationServerMiddleware`, where the logic was almost entirely contained in private 
methods (under the `OAuthAuthorizationServerHandler` class) and where extensibility was possible using a fairly simple events model centered around the `OAuthAuthorizationServerProvider` class.

I was a huge fan of this pattern and used it quite extensively. Unfortunately, it was a bit limited for OpenIddict as you could only have 1 event handler per event type.

In OpenIddict 3.x, I decided to revamp the events model to make it way more flexible. As part of this task, all the logic was moved to specialized events handlers.

Plugged together, these handlers form an event pipeline (more or less complex depending on the endpoint type) that define how a request is processed - from the moment we extract it to the moment we return a response - and that you can tweak to exactly fit your needs: you can remove an event handler, re-add it with a different order, or even add custom event handlers to precisely change how OpenIddict works.

It's certainly more complex than the previous design, but it's also infinitely more customizable.

This new design is also what powers OpenIddict's new degraded mode (aka `ASOS-like` mode). When enabled, some of the default event handlers - typically, all the handlers that depend on the OpenIddict DB managers - are disabled. When opting for this mode, you don't have to register the OpenIddict core services (i.e the `.AddCore(options => ...)` stuff), but you must register custom handlers to take care of the things OpenIddict doesn't validate for you in this mode (e.g client validation), exactly like in ASOS.

This particular design was mentioned in my OpenIddict 3.0 roadmap post: https://github.com/openiddict/openiddict-core/issues/736
