### ISSUE TITLE
Implement userinfo support

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#9]
ASOS now supports userinfo requests: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/97

**Comment by kevinchalet** [comment]
I'll take this one :clap: 

@ilmax @Bartmax what should we expose? The username, the email address, the name?

**Comment by ilmax** [comment]
What about exposing all claims of current users by default, and allow the user to confirue a UseinfoClaimFilter to select wich claim hide?

**Comment by kevinchalet** [comment]
Not sure how I feel exposing all the claims by default, specially since one could store critical claims that are not directly related to the user's profile, like access tokens.

I think we should only expose the standard claims defined by the OIDC specs: http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

@Bartmax your thoughts?

**Comment by Bartmax** [comment]
Let's have a IList<Claims> UserInfoClaims that the developer can add any claim with the standard claims defined by OIDC as default and expose those.

**Comment by ilmax** [comment]
LGTM

**Comment by kevinchalet** [comment]
Postponed until https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/109 is done :tada:

**Comment by kevinchalet** [comment]
Done: https://github.com/openiddict/core/pull/19

We may re-consider adding a extensibility hook in the future.
