### ISSUE TITLE
Refresh token multiple times with refreshtoken

### ISSUE THREAD

**Issue by Tsjerno** [openiddict/openiddict-core#916]
Question,

I'm using the openiddict orchardcore module.
There I've seen the following behaviour.
-> Get access token with offline_access.
System returns accesstoken and refresh_token (eg UvhcWzipcg)

Then I'm exchanging the refesh_token(UvhcWzipcg) for a new one. 
System returns new refresh_token (_rUgzgg2WQ).
So far so good.

Due to multi threading issues (my bad) It can happen that refresh_token (UvhcWzipcg) is exchanged for a second time. (I should not do that, but it happens now).

After exchanging token UvhcWzipcg again, my new token (_rUgzgg2WQ) is redeemed.

My question, is this expected behaviour? 

Right now I'm going to prevent that my client can exchange the same token multiple times. And I'm gonna try to simulate the behaviour in just openiddict, to see where this happens.

I know when multiple refresh tokens for the same user/client_id combination are generated and one of them is exchanged, all others are redeemed. I can follow this behaviour, one client should cache only one refresh_token.

**Comment by kevinchalet** [comment]
> My question, is this expected behaviour?

Yes: once you **explicitly opt** for rolling tokens, trying to redeem a refresh token multiple times - concurrently or not - always results in a single request being honored. All the OpenIddict stores use optimistic concurrency (even the YesSql stores, that now support it), so when a race condition happens, a special exception is thrown and caught by OpenIddict to return a proper error instead of a server error.

If this is inconvenient, consider disabling rolling tokens.
More info at https://github.com/openiddict/openiddict-core/issues/462.

**Comment by Tsjerno** [comment]
Thanks for your response. 
I get the point from #462. In a concurrent system I get that this happens. So exchanging the token twice gives an error at the second exchange.

The concurrency is a problem in my App. I can handle this. 
What I did not expect is that when exchanging a refresh token which is already redeemed that all valid tokens for the authorization(user_id/client_id) are redeemed. (These valid tokens are newer (in time))

It is in the word "previous". 

// When rolling tokens are enabled, try to revoke all the previously issued tokens
// associated with the authorization if the request is a refresh_token request.
// If the operation fails, silently ignore the error and keep processing the request:
// this may indicate that one of the revoked tokens was modified by a concurrent request.

Previous -> (all other token) or (previous in time). So my newer token is not redeemed. 
I would expect previous in time. So when exchanging a redeemed token, the openId server should just give an error, and not redeem valid tokens. (which are created later in time)

What is expected behaviour is that when there are 3 valid refresh tokens for a authorizationID, that if one of them is exchanged that all others are redeemed. It should not occur that there is more than one valid refresh token for a authorizationID.

**Comment by kevinchalet** [comment]
There are actually 2 mechanisms that shouldn't be mixed up to fully understand how things work when rolling tokens are enabled:
  - In the normal case, when sending a unique refresh token request, OpenIddict marks all the tokens using the same authorization identifier as the refresh token as revoked. In this case, the new access and refresh tokens returned in the token response are fully usable. This matches the code comment you mentioned. In 3.0, it's handled by the `RevokeExistingTokenEntries` handler:

https://github.com/openiddict/openiddict-core/blob/8b097321c3ba92c20b75bcaf75f1d4318c11838e/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L2597-L2670

  - In the pathological case, when multiple token requests with the same refresh token are sent (concurrently or serially), OpenIddict detects it was already redeemed and assumes that the refresh token was compromised. When such a case occurs, the entire authorization chain - i.e all the tokens previously issued - and the authorization itself are automatically revoked and no new token is returned. In this case, the application must start a new authorization process from scratch. This matches how OpenIddict treats authorization codes, for which we're strongly encouraged to provide such countermeasures. This might be surprising at first, but the specification lists that as a way to inform the client application about a potential token leakage. In 3.0, it's handled by the `ValidateTokenEntry` handler:

https://github.com/openiddict/openiddict-core/blob/8b097321c3ba92c20b75bcaf75f1d4318c11838e/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L725-L930

**Comment by Tsjerno** [comment]
Disabling rolling tokens works for my concurrent/serial case. I can continue.
I get the point of revoking all tokens in the chain.
I think I'm looking for a rollingtokens (light) version.
rfc6749#section-10.5 for authorizationcodes is absolutely necessary.
But for refreshtokens I'm looking for a solution in between. When a refreshtoken gets leaked I don't want it to be usefull (rollingtokens). But I don't want my current chain to be disabled after someone abuses this token. (or my own app refreshes twice). 

Thanks for giving more explanation on this subject. This issue can be closed.

**Comment by kevinchalet** [comment]
I hear your concerns. I'll think more about it and decide if it's worth changing the behavior in 3.0.
