### ISSUE TITLE
Accessing (custom) fields in OpenIdConnectRequest broken

### ISSUE THREAD

**Issue by NetTecture** [openiddict/openiddict-core#917]
2.0.1 on Dotnet Core 3.1. Endpoint routing is disabled.

I am trying to access custom fields in OpenIdConnectRequest. This worked in dotnet core 2.2 and the openiddict version I had installed at this time.

Basically for reasons of statistics I am supposed to send additional information with an authorization request.

I see no way now to get this information. All fields except the required fields seem to be removed. We are using (on the list to replace) the passwort grant at the moment, and all but username and password are filtered out. In the past, when we added additional fields to the submitted form data, we could access it using.

> Request.Form.TryGetValue("application", out var appOut)

After the update now I get this in the immediate window:

? Request.Form.Keys
Count = 3
    [0]: "grant_type"
    [1]: "username"
    [2]: "password"

All other fields have been removed.

If I ask for the headers, I get:

? Request.Headers.Keys
Count = 3
    [0]: "Accept"
    [1]: "Host"
    [2]: "Content-Type"

althroughI am sending additional headers.

It seems that the processing is removing all additional information.

How can I pass through this additional information for my request?

I have tried:

* Setting headers
* Adding fields to the request
* Adding the fields to the url

None of them contain the data.

**Comment by kevinchalet** [comment]
All the request parameters (extracted from the request form for a POST request or from the query string for a GET request) are stored in the `OpenIdConnectRequest` (`OpenIddictRequest` in 3.0).

You can retrieve custom parameters by doing `request["custom_parameter"]`. Explicit conversion operators are available, so that you can do things like `(string) request["custom_parameter"]` or `(int?) request["custom_parameter"]`.

> All fields except the required fields seem to be removed.

It's not something ASOS or OpenIddict do (no matter what's the version you're using, we never mutable the request data) so it's likely caused by something else (e.g a bad proxy?)

**Comment by NetTecture** [comment]
@kevinchalet 

Nope, not seeing them.

? tokenRequest
Parameters: 3
    AccessToken: null
    AcrValues: null
    Assertion: null
    Audiences: null
    Claims: null
    ClaimsLocales: null
    ClientAssertion: null
    ClientAssertionType: null
    ClientId: null
    ClientSecret: null
    Code: null
    CodeChallenge: null
    CodeChallengeMethod: null
    CodeVerifier: null
    Display: null
    GrantType: "password"
    IdTokenHint: null
    IdentityProvider: null
    LoginHint: null
    MaxAge: null
    Nonce: null
    Parameters: Count = 3
    Password: "xxx"
    PostLogoutRedirectUri: null
    Prompt: null
    Properties: Count = 1
    RedirectUri: null
    RefreshToken: null
    Registration: null
    Request: null
    RequestId: null
    RequestUri: null
    Resources: null
    ResponseMode: null
    ResponseType: null
    Scope: null
    State: null
    Token: null
    TokenTypeHint: null
    UiLocales: null
    Username: "xxx"

var app = tokenRequest["application"];

(which I am sending in the request form) returns null.

**Comment by kevinchalet** [comment]
I am unable to reproduce your issue. Consider posting a repro and I'll take a look.

**Comment by NetTecture** [comment]
AAAAAH. Found it. You are right. SOme part of my test framework was doing a request without that infor first to establish some baseline logged in info ;( That triggered my breakpoint.

**Comment by kevinchalet** [comment]
Watch out, this is the kind of rookie mistake that may get you fired :trollface:
