### ISSUE TITLE
Authorization Code Grant for Alexa Skill

### ISSUE THREAD

**Issue by Danielks92** [openiddict/openiddict-core#920]
I've tried to implement the authorization code grant as defined on the official amazon page for account linking: 
https://developer.amazon.com/de-DE/docs/alexa/account-linking/configure-authorization-code-grant.html

However when I receive the token request from Amazon I get the following error:

The authorization response was successfully returned as a plain-text document: {
"error": "invalid_request",
"error_description": "The mandatory 'response_type' parameter is missing."
}.

Example Request from Amazon:
POST /auth/o2/token HTTP/1.1
Host: api.amazon.com
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

grant_type=authorization_code
&code=123456EXAMPLE
&client_id=exampleId
&client_secret=ABCDEFGEXAMPLE

The problem is, I can not influence this request.  Has anyone already implemented account linking for alexa skills and can provide an example or knows how I can solve this issue?

Version: 2.0.0-rc2-final

**Comment by kevinchalet** [comment]
> Version: 2.0.0-rc2-final

This version is obsolete and no longer supported. Consider migrating to 2.0.1.

> However when I receive the token request from Amazon I get the following error:

This error is returned by the authorization endpoint. You likely mixed up the token endpoint and authorization endpoint addresses.

**Comment by kevinchalet** [comment]
Does that work now?

**Comment by Danielks92** [comment]
Yes, the error I had yesterday is gone.
However I have a new error now. If I try to get a token by providing the authorization code I get:

The token response was successfully returned: {
         "error": "invalid_client",
         "error_description": "The specified client credentials are invalid."
 }.

Does that mean the provided code is wrong?

The token request was successfully extracted from the HTTP request: {
         "grant_type": "authorization_code",
         "code": "[removed for security reasons]",
         "client_id": "AmazonSLA",
        "redirect_uri": "https://layla.amazon.com/api/skill/link/M1SCE62WF71KU0"
 }.

**Comment by Danielks92** [comment]
Problem solved, I had to include the client_secret.
Thanks for the help!

**Comment by kevinchalet** [comment]
You're welcome!
