### ISSUE TITLE
Access token in body

### ISSUE THREAD

**Issue by Danielks92** [openiddict/openiddict-core#921]
Hi, I have another Alexa related question.
The way Amazon sends the access token is a bit wired:

> The token is available in the accessToken property of the user object, which is available in the context object. The context object is included in all requests. You can access the accessToken in context.System.user.accessToken.

How can I validate the token if it's sent in the body and how can I get the corresponding user for the token?

Thanks in advance

**Comment by kevinchalet** [comment]
Hi,

It's probably a question you should ask to the Amazon folks, as this is not directly related to OpenIddict.
