### ISSUE TITLE
Use System.Net.Http.Json once available

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#922]
https://github.com/dotnet/designs/blob/master/accepted/2020/json-http-extensions/json-http-extentions.md

**Comment by kinosang** [comment]
seems add via dotnet/runtime#33459

**Comment by kevinchalet** [comment]
Yeah. There's no RTM package yet but I started using it for my local introspection branch and it's really promising 👏

**Comment by kevinchalet** [comment]
For the record, the 3.2.0 RTM version of the `System.Net.Http.Json` package was released last week.
