### ISSUE TITLE
Execution error using a custom TKey

### ISSUE THREAD

**Issue by eduardoluizm** [openiddict/openiddict-core#93]
Hi,

I tried to use a custom TKey (Guid) and it compiles, but, when I try to run, it doesn't work.

**It works:**
![image](https://cloud.githubusercontent.com/assets/3385836/14818690/d886e6fa-0b94-11e6-89bf-7e3d5bbbc066.png)

![image](https://cloud.githubusercontent.com/assets/3385836/14818707/ecd0ad80-0b94-11e6-97ac-77269b17cc2d.png)

![image](https://cloud.githubusercontent.com/assets/3385836/14818724/0204c114-0b95-11e6-841a-312d9029e11b.png)

**It doesn't work:**
![image](https://cloud.githubusercontent.com/assets/3385836/14818838/88ac0cb8-0b95-11e6-8e1c-e76fdffece16.png)

![image](https://cloud.githubusercontent.com/assets/3385836/14818846/8fa63cfa-0b95-11e6-99ef-b15e4ef9460f.png)

![image](https://cloud.githubusercontent.com/assets/3385836/14818857/99922fc6-0b95-11e6-93a3-0ec03d693087.png)

![image](https://cloud.githubusercontent.com/assets/3385836/14818821/752b9384-0b95-11e6-881c-9ad6f8ea58a7.png)

**Dotnet Info**
PS C:\WINDOWS\system32> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002485)

Product Information:
 Version:     1.0.0-rc2-002485
 Commit Sha:  d3c65aee87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by kevinchalet** [comment]
Hey,

Looks like you're not registering the `AppClient` type.
Can you try calling `AddOpenIddict<AppClient>()` instead of `AppOpenIddict()`?

**Comment by eduardoluizm** [comment]
@PinpointTownes Thanks! I've forgot something.. rsrs
