### ISSUE TITLE
An unhandled exception occurred while processing the request. InvalidOperationException: An authorization or token response cannot be returned from this endpoint. AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.SignInAsync(AuthenticationTicket ticket)

### ISSUE THREAD

**Issue by anilvebilisetty** [openiddict/openiddict-core#930]
An unhandled exception occurred while processing the request.
InvalidOperationException: An authorization or token response cannot be returned from this endpoint.
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.SignInAsync(AuthenticationTicket ticket)

I could able to get identity token but due to openiddict restriction I couldnt able to redirect to externallogincallback after authentication

options.Events = new OpenIdConnectEvents
                    {
                        OnTicketReceived =  ctx =>
                        {
                            var identity = ctx.Principal.Identity;
                            ctx.Response.Redirect("ExternalLoginCallback");
                            return Task.FromResult(0);
                        }
                    };
                    });

I have seen many references but i couldnt find exact solution for this.

**Comment by kevinchalet** [comment]
This error indicates you tried to call `SignIn` from an arbitrary location that doesn't correspond to the authorization or token endpoint. To fix that, don't call `SignIn` from `ExternalLoginCallback` but make sure your users are redirected to your authorization endpoint by `ExternalLoginCallback`.
