### ISSUE TITLE
EntityFramework incompatibility with ASP.net core 3.1

### ISSUE THREAD

**Issue by martinkoslof** [openiddict/openiddict-core#937]
I am trying to use Openiddict in a very simple fashion -> to provide openid tokens and a simple wrapper around Windows Authentication and Kerberos. I am planning on using the ClientCredentialsFlow. We will probably only have a handful of "accepted" clients and I was really hoping to just store these in a json file, local file on the server, or if I really had to, a simple database and just load this into memory such as a dictionary.

Every example I have seen, seems to have a dependency on the Entity Framework. For example:

                // Register the OpenIddict core services.
                .AddCore(options =>
                {
                    // Register the Entity Framework stores and models.
                    options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
                })

When I try to import the nuget package I get compatibility errors for OpenIddict.EntityFrameworkCore.  I am willing to use EntityFramework if I absolutely have to, and perhaps its in memory version. But can I not do with this ASP.net core 3.1? I'm not entirely sure what is supported and not given the description of the library says "Versatile OpenID Connect stack for ASP.NET 4.x and ASP.NET Core 2.x/3.x". That 3.x would lead me to believe I can import OpenIddict.EntityFrameworkCore without versioning issues.

As a general question, can I use openddict without this? For example, it appears the manager just has find by id methods and also the ability to create items.

`var manager = scope.ServiceProvider.GetRequiredService<OpenIddictApplicationManager<OpenIddictApplication>>();`

                if (await manager.FindByClientIdAsync("console") == null)
                {
                    var descriptor = new OpenIddictApplicationDescriptor
                    {
                        ClientId = "console",
                        ClientSecret = "388D45FA-B36B-4988-BA59-B187D329C207",
                        DisplayName = "My client application",
                        Permissions =
                        {
                            OpenIddictConstants.Permissions.Endpoints.Token,
                            OpenIddictConstants.Permissions.GrantTypes.ClientCredentials
                        }
                    };

                    await manager.CreateAsync(descriptor);
                }

What defines the persistence of this class? Does it need to be EntityFramework?

**Comment by kevinchalet** [comment]
> Every example I have seen, seems to have a dependency on the Entity Framework.

Because it's the most popular option, just like Identity is the de-facto reference for membership operations. But that doesn't mean OpenIddict depends on EF Core or Identity.

> When I try to import the nuget package I get compatibility errors for OpenIddict.EntityFrameworkCore.

The 2.0.1 EF Core package works fine on 3.1. Without having any error detail, it's hard to help you.

> As a general question, can I use openddict without this?

OOTB, EF 6.x, EF Core and MongoDB are supported, but you can also write your own stores.
In OpenIddict 3.0 (still a WIP), you'll also be able to use the "degraded mode", that allows using OpenIddict without any store/backing database.

More info here: https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

**Comment by martinkoslof** [comment]
Thanks Kevin, I would absolutely be interested in "degraded mode" but we have an escalated delivery date and I don't think we can wait for 3.0 to get to release candidate. Apologies, for whatever reason, it appears 2.0.1 EF Core does compile without warning, perhaps I was in some odd state before.

However, sadly its just not working for me. Right now, all I want to do is use Openiddict with some in memory storage to finish my prototype. I do not have a sql server database at my disposal. So I figured, I'll try the Entity In Memory flavor:

`      services.AddDbContext<AuthContext>(options =>
            {
                options.UseInMemoryDatabase(databaseName: "ClientCredentialAuth");
                options.UseOpenIddict();
            });`

I added the Entity In Memory 3.1.3 nuget package. When trying to use it, it fails:

System.TypeLoadException: 'Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource' from assembly 'Microsoft.EntityFrameworkCore, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

I have no idea what I'm missing here. There is no "configuration" to be had and no examples online I have found with using the InMemory flavor have some appsettings or config I'm missing. If it helps I'm really just trying to follow the client credential flow example, but not using SqlServer:

https://github.com/openiddict/openiddict-samples/tree/dev/samples/ClientCredentialsFlow

I'm literally just trying to store 2 client credential flow "sets of the data" (the client id, client secret and description, permissions). I'd stick the darn thing in a dictionary at this point I don't care. I'm trying to use the 2.0.1 version since I can't use an alpha version when we go live.

**Comment by kevinchalet** [comment]
The error message seems to indicate you’re using referencing different versions of the EF Core packages. Can you triple check that your csproj references the latest version of the core/in-memory EF packages?

If it still doesn’t work, post your project somewhere and I’ll take a look.

**Comment by egorpavlikhin** [comment]
I had the same issue, which is resolved by adding reference to Microsoft.AspNetCore.Identity.EntityFrameworkCore of the same version as EF Core package.

Side comment: Entity Framework reference is very had to get rid of. Yes, you can theoretically write your own store, but it's hundreds of lines of code, that are not explained in how they are supposed to work. The fact that InMemoryStore is the proposed solution really just highlights the problem. Even samples, that show how you can validate the request yourself, are still referencing EF when there is no need to do so - membership is already handled by external code.

**Comment by kevinchalet** [comment]
> Even samples, that show how you can validate the request yourself, are still referencing EF when there is no need to do so - membership is already handled by external code.

Heh no, only the user authentication part is always left as an exercise (for that, you can use ASP.NET Core Identity, some form of Windows Integration Authentication, manual LDAP calls or anything else you want). The OIDC request validation logic uses EF to store the application details and manage some authorization and token entries for tracking and revocation purposes.

> Yes, you can theoretically write your own store, but it's hundreds of lines of code, that are not explained in how they are supposed to work.

Would you be interested in contributing or sponsoring the documentation effort needed to make that part clearer?

> The fact that InMemoryStore is the proposed solution really just highlights the problem.

I'm all ears. Do you have any concrete suggestion? BTW, it's not the only proposed solution. In 3.0, you can also use the degraded to use OpenIddict without any stores: https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/
