### ISSUE TITLE
OpenIddict and PowerBI

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#942]
I am not sure if this is the right use for this or not, so maybe someone can just asy if this how we are supposed to use it or not.

But i have my application using openIddict (great piece of software thank you).  Users type in a username and password ot gain access, i return a token/refresh token etc.  This works great.

Now we have a client that wants to use PowerBI with our app, i have told them to go down the token route, and they have done this successfully, but have asked if they need to do this each time they want to call our application.  I would say yes, but i wondered if this is where i would setup a clientId and clientSecret on my application and send that to them to use instead?  Does this return a token as well?  Is this the way openIddict is supposed to be used, or am i getting confused and clientSecret isnt used for this scenario?

**Comment by kevinchalet** [comment]
I'm not familiar enough with Power PI to make recommendations.
That said, it sounds like a good scenario for the code flow (without a client secret, if the Power BI client is installed on machines you don't control).

**Comment by Gillardo** [comment]
its more about the user wanting to use our api and not having to login with uesrname and password each time.

What is code flow?

**Comment by kevinchalet** [comment]
> What is code flow?

https://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-choosing-the-right-flows/

> its more about the user wanting to use our api and not having to login with uesrname and password each time.

If you're happy with the ROPC flow, why not using refresh tokens so that you can retrieve new access tokens without re-asking for user credentials?
