### ISSUE TITLE
Revocation of reference token is success but still revoked token is working fine. I am not using cache.

### ISSUE THREAD

**Issue by anilvebilisetty** [openiddict/openiddict-core#945]
I could see the status of the token as revoked in "OpenIddictTokens" table but i am surprised how it is getting validated successfully.
My code: 
var res = await httpClient.RevokeTokenAsync(new TokenRevocationRequest
                {
                    ClientId = "ClientId***",
                    Address = "https://localhost:5000/connect/revoke",
                    Token = token,
                    TokenTypeHint="access_token"
                }).ConfigureAwait(false);

in Authorization  server:
startup.cs:
.AddValidation(opt => {
                    opt.UseReferenceTokens();
                });

**Comment by kevinchalet** [comment]
What version are you using?

**Comment by anilvebilisetty** [comment]
@kevinchalet  I am using 2.0.1 version. One more thing i would like you to know even after deleting all records in openiddictToken table token is getting validated.
Below is my Introspection code: 

 .AddOAuthIntrospection(options =>
                {
                    options.Authority = new Uri(Configuration.URL.AUTH);
                    options.Audiences.Add(Configuration.Credentials.ID);
                    options.ClientId = Configuration.Credentials.ID;
                    options.ClientSecret = Configuration.Credentials.SECRET;
                    options.RequireHttpsMetadata = true;
                });

**Comment by kevinchalet** [comment]
I am not able to reproduce the issue you describe. I've tried with both the validation and the introspection handlers.

Also, you don't seem to be overriding the default caching policy - that caches introspection responses for 15 minutes. Are you sure it's not a caching issue?

**Comment by anilvebilisetty** [comment]
@kevinchalet can you help me how can I override cache policy. I felt if we explicitly mention cache it will use cache or else no.

**Comment by kevinchalet** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/blob/dev/src/AspNet.Security.OAuth.Introspection/OAuthIntrospectionOptions.cs#L120-L129

**Comment by anilvebilisetty** [comment]
@kevinchalet  My bad,yes it worked on updating cache policy to null. Thank you 😊
