### ISSUE TITLE
Does it support LDAP/Active Dir authentication?

### ISSUE THREAD

**Issue by biapar** [openiddict/openiddict-core#955]
Does it support LDAP/Active Dir authentication?

**Comment by kevinchalet** [comment]
OpenIddict doesn't handle the user authentication part. You're free to use whatever you want, Windows Integrated Authentication (NTLM/Kerberos) or manual LDAP lookups included.

**Comment by biapar** [comment]
Is there an example how to include it?

**Comment by kevinchalet** [comment]
No.

**Comment by kevinchalet** [comment]
@auroris created a very nice sample showing how to use Windows Integrated Authentication with OpenIddict 3.0's degraded mode (on IIS): https://github.com/auroris/OpenIddict-WindowsAuth

**Comment by cryo75** [comment]
The sample doesn't work the second time round. For example; I enter wrong credentials, I do get 401. I then enter the correct credentials, I get 200. However, I can enter wrong credentials again and it will always return 200.

**Comment by luboid** [comment]
to those who are interested in the question you can check out https://github.com/luboid/openiddict-active-directory

**Comment by auroris** [comment]
@cryo75 Maybe clear your browser cookies.
