### ISSUE TITLE
In need of a RavenDb Store

### ISSUE THREAD

**Issue by cadilhac** [openiddict/openiddict-core#959]
Hi,

I have several web platforms without corresponding mobile apps and I think it's time to be modern and think about it. I currently use Asp.Net MVC 5 and RavenDb as the database. It uses simple authentication with email/password and login with facebook/twitter/google. Creating a Xamarin app will be totally new for me as well as migrating to asp.net core. Authentication will have to be changed from a cookie based solution to a token one. So many things to learn... I was happy to discover this openiddict solution + [IdentityModel](https://github.com/IdentityModel/IdentityModel) on the client side, but unfortunately, there is no RavenDb store and I won't be capable to create one by myself.

This thread's goal is to check with you all how many people would be interested to have such a store.

Thanks

**Comment by kevinchalet** [comment]
Hey,

Thanks for your interest. There are still many things to do for OpenIddict 3.0, so introducing new stores is unlikely to happen in the near future. However, two things could help change that:

  - An external contribution: if you or someone else is interested in submitting a PR to add complete RavenDB support, I'll try my best to help review it.

  - Sponsoring: if RavenDB support is important for you or your company, please consider sponsoring the project. This helps me spend more time on OpenIddict and implementing features requested by the community.

**Comment by cadilhac** [comment]
It can't be me in both cases, but just to add some info on this case, is there some documentation to help understand all the moving pieces involved and how to build a custom data store?

**Comment by kevinchalet** [comment]
No, but you can take a look at the existing stores to see how they are implemented.

**Comment by kevinchalet** [comment]
Closing as no one offered to sponsor or contribute to the initiative and the demand is not strong enough to implement it myself.
