### ISSUE TITLE
Two calls to the Authorization endpoint produces an exception if refres_token asked

### ISSUE THREAD

**Issue by jonathanantoine** [openiddict/openiddict-core#960]
When I call twice the authorization endpoint with the offline_access scope and password flow, the second call receive a 500 status code with an exception "Cannot insert duplicate key row in object 'portal.OpenIddictTokens'

Exception :
SqlException: Cannot insert duplicate key row in object 'portal.OpenIddictTokens' with unique index 'IX_OpenIddictTokens_ReferenceId'. The duplicate key value is (<NULL>). The statement has been terminated.

Is it a normal behavior ? Where the ReferenceId comes from ?

**Comment by kevinchalet** [comment]
> When I call twice the authorization endpoint with the offline_access scope and password flow

The password flow doesn't use the authorization endpoint.

It's hard to say what's going on without at least knowing what OpenIddict version you're using. A `CREATE` script of your tokens table (with the indexes) would also help.

**Comment by jonathanantoine** [comment]
Sorry for not providing enough information. I use the "2.0.1" version.

Here are the create script :

```sql
CREATE TABLE [mo].[OpenIddictTokens]
(
    [ApplicationId]    BIGINT                 NULL,
    [AuthorizationId]  BIGINT                 NULL,
    [ConcurrencyToken] NVARCHAR(50)           NULL,
    [CreationDate]     DATETIMEOFFSET(7)      NULL,
    [ExpirationDate]   DATETIMEOFFSET(7)      NULL,
    [Id]               BIGINT IDENTITY (1, 1) NOT NULL,
    [Payload]          NVARCHAR(MAX)          NULL,
    [Properties]       NVARCHAR(MAX)          NULL,
    [ReferenceId]      NVARCHAR(100)          NULL,
    [Status]           NVARCHAR(25)           NOT NULL,
    [Subject]          NVARCHAR(450)          NOT NULL,
    [Type]             NVARCHAR(25)           NOT NULL,
    CONSTRAINT [PK_OpenIddictTokens] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO
CREATE NONCLUSTERED INDEX [IX_OpenIddictTokens_AuthorizationId]
    ON [mo].[OpenIddictTokens] ([AuthorizationId] ASC);

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_OpenIddictTokens_ReferenceId]
    ON [mo].[OpenIddictTokens] ([ReferenceId] ASC);



GO
CREATE NONCLUSTERED INDEX [IX_OpenIddictTokens_ApplicationId_Status_Subject_Type]
    ON [mo].[OpenIddictTokens] ([ApplicationId] ASC, [Status] ASC, [Subject] ASC, [Type] ASC);


```

**Comment by jonathanantoine** [comment]
pff I am so sorry for making you waste your time, my creation script is wrong (again... :().

Sorry again.

**Comment by jonathanantoine** [comment]
For the reference, I should have this creation script for `IX_OpenIddictTokens_ReferenceId` :

```sql
CREATE UNIQUE NONCLUSTERED INDEX [IX_OpenIddictTokens_ReferenceId]
    ON [dbo].[OpenIddictTokens]([ReferenceId] ASC) WHERE ([ReferenceId] IS NOT NULL);

```

**Comment by kevinchalet** [comment]
No problem. Out of curiosity, how was the original script - that doesn't have the `IS NOT NULL` filter - generated?

**Comment by jonathanantoine** [comment]
It was generated using Jetbrains Rider.
