### ISSUE TITLE
Have you considered supporting MFA?

### ISSUE THREAD

**Issue by kamikyo** [openiddict/openiddict-core#967]
Have you considered supporting MFA?
like this:

`builder.EnableMultiFactorAuthentication(opts=>{...});`

Thank you for your efforts, Openiddict is a great tool.

**Comment by kevinchalet** [comment]
> Openiddict is a great tool.

Glad you like it!

> Have you considered supporting MFA?

2FA/MFA is mostly a user authentication thing, which is not something OpenIddict itself deals with. In general, you'll want to use ASP.NET Core Identity to implement MFA support at the authorization server level (tho' the options are quite limited OOTB: SMS or TOTP).

If you want your clients to be able to know whether the user was authenticated using MFA, you can add a standard `amr` claim to your identity tokens containing the `mfa` value (defined by https://tools.ietf.org/html/rfc8176#section-2). It allows clients to reject authentication methods that are not considered secure enough, but it has privacy concerns, so it's something to keep in mind.

**Comment by kevinchalet** [comment]
I sent https://github.com/openiddict/openiddict-core/pull/968 to add the `amr` values defined by the RFC8176 specification in `OpenIddictConstants`.

**Comment by kamikyo** [comment]
Thanks kevinchalet. Thank you for your valuable comments!
