### ISSUE TITLE
Improve the message of the exception thrown when a request is not handled

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-core#977]
E.g: https://github.com/openiddict/openiddict-core/blob/b6e19a918b9babf3255396b1caa4314ed4d1812a/src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs#L311-L316

/cc @Bartmax

**Comment by Bartmax** [comment]
I think there are 2 main points that can improve the message:

1) Don't make one better than the other. Right now the message sounds like if event handler is the correct way to do it while passthru is a "workaround". I understand that is not the case, it's a matter of choice. Maybe is me but the word "alternative" suggest that the later is less preferred than the former.

2) Explain how to enable pass thru with similar details on how register an event handler.

(explaining what you mean with pass-through is a bonus)

I was thinking in something along this lines (may need proper grammar):

The authorization request was not handled.
You can either use an OpenIddict Server Handler creating a class that implements 'IOpenIddictServerHandler<HandleAuthorizationRequestContext>' and registering using 'services.AddOpenIddict().AddServer().AddEventHandler()' or using your server infrastructure enabling the pass-through mode. In aspnetcore that would be: `services.AddOpenIddict().AddServer().UseAspNetCore().EnableAuthorizationEndpointPassthrough()`
