### ISSUE TITLE
Ambiguity in System.Linq on NET 3.0 when using openiddict and EF Core.

### ISSUE THREAD

**Issue by Bartmax** [openiddict/openiddict-core#980]
There's ambiguity in System.Linq when referencing either 
`OpenIddict.AspNetCore` or `OpenIddict.EntityFrameworkCore` in the same project as `Microsoft.EntityFrameworkCore.SqlServer`

![image](https://user-images.githubusercontent.com/3386797/84735176-3434ca80-af79-11ea-9a05-b81b14845dda.png)

Here's the full csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\Arthon.Client.csproj" />
    <ProjectReference Include="..\Shared\Arthon.Shared.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" Version="$(OpenIddictVersion)" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="$(OpenIddictVersion)" />
  </ItemGroup>
  
</Project>

```

I'm not sure if this is directly related to https://github.com/dotnet/efcore/issues/18124 but it looks like.

Not sure what would be a good solution for this. Totally doesn't look as a OI thing, but since it uses AsyncEnumerable in very few places, maybe we could get rid of that (?)

Some really ugly scenario here.

Just for reference, a workaround to make it work is to add `AsQueryable` any ef query like for example: 
```c#
await context.WeatherForecasts.AsQueryable().Take(10).ToListAsync();
```

**Comment by kevinchalet** [comment]
It's definitely a manifestation of https://github.com/dotnet/efcore/issues/18124. In 3.0, `OpenIddict.Core` references `System.Linq.Async`, whose extensions are in the same `System.Linq` namespace as the good old `IQueryable<T>` LINQ extensions coming from the BCL. If you add a `System.Linq` using, you're immediately impacted.

We have a couple of options here:
  1. Don't change anything on our side, which forces our users to use `.AsQueryable()` to avoid issues with the extensions resolution mechanism.

  2. Remove the `System.Linq.Async` reference from `OpenIddict.Core`, which is what other projects like Stripe.NET did: https://github.com/stripe/stripe-dotnet/issues/1974.

  3. Convince the RX team to move their extensions to a different namespace to avoid accidental collisions (e.g `System.Linq.Async`). It's a breaking change, so it won't be easy to sell.

While I'm personally a huge fan of IX/RX and quite reluctant to remove it from `OpenIddict.Core`, it's unfortunately the only thing we can do if we consider the pain for our users is too high.

@clairernovotny hey Claire. IIRC, you said a few times it was an EF Core issue, but was a namespace change considered?

**Comment by clairernovotny** [comment]
There’s nothing we can change. We are System.Linq, and we defined the extension methods. EF created the conflict, they need to solve it.

**Comment by kevinchalet** [comment]
> There’s nothing we can change.

You could change the namespace.

> EF created the conflict, they need to solve it.

True, but I suspect EF Core will not be the only one in this situation: after all having a type that implements both `IAsyncEnumerable<T>` and `IQueryable<T>` is not that unreasonable.

Anyway, thanks for your reply. It's quite unfortunate we'll have to remove our dependency on `System.Linq.Async`, but if neither the EF folks nor the RX team want to improve the situation (but both have good arguments, to be honest), we're kinda stuck.

**Comment by Bartmax** [comment]
Agree, let's remove the dependency on `System.Linq.Async` as others are doing and I guess many will follow.
Worst case scenario, we can make the code available as `OpenIddict.Linq.Async` for the bits we need.
