### ISSUE TITLE
Unable to get examples working

### ISSUE THREAD

**Issue by garethrampton** [openiddict/openiddict-core#983]
I have been using version 2 for some while with great success, but for some reason I’m really struggling with version 3.

The issue I’m having is with the authorization code flow. 

I can’t even get the samples working from the either the samples repo or the example in the main repo.

Specifically with the AuthorizationController in the Authorize action, the following line always fails resulting in an authorization loop. 

`var result = await HttpContext.AuthenticateAsync(IdentityConstants.ApplicationScheme); `

result.Succeeded is always false. 

This is when running the provided example MvcServer and MvcClient projects exactly as-is, freshly cloned. 

In my own code (core 3.1), if I apply the authorize attribute back (as per v2) on the action this works, but the authentication token is clearly never being set correctly as the client is simply redirected back to the login view rather than redirecting to the redirecturi. 

Any thoughts or advice would be welcome. I don’t feel this is necessarily a bug with OpenIddict, but given I can’t even get the samples working as-is, something is clearly off and I can’t fathom why even the samples are not working. 

I’m running in a Windows environment and using the latest Chrome beta to test with.

**Comment by kevinchalet** [comment]
Can you try with Firefox? It sounds like a browser-side issue to me.

**Comment by garethrampton** [comment]
Ok, interesting. More testing reveals this is indeed a browser issue:

Working:
Edge: 83.0.478.50 (Official build) (64-bit)
Edge: 83.0.478.54 (Official build) (64-bit)
Firefox: 77.0.1 (64-bit)

Not working:
Chrome: 83.0.4103.106 (Official Build) (64-bit)

Whatever has changed recently in Chrome has clearly broken things.

**Comment by kevinchalet** [comment]
Interesting. Is there anything in the browser logs? I'm tempted to think it's related to the recent changes in their `Set-Cookie` validation routine. Could you please try enabling TLS and see if it makes any difference?

**Comment by garethrampton** [comment]
Ok, can confirm that enabling TLS with the samples fixes this in Chrome. There was nothing at all logged by Chrome to indicate the issue though.

**Comment by kevinchalet** [comment]
Thanks! Would you be interested in sending a PR to fix the samples? 😃

**Comment by kevinchalet** [comment]
@garethrampton let me know if it's something you're interested in doing.

**Comment by auroris** [comment]
Does this have relevance? https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by kevinchalet** [comment]
@auroris yeah. We'll need to update all the samples to use TLS (the good thing is that it's now much easier, compared to how painful it was 5 years ago 😅)
