### ISSUE TITLE
Custom EF models causing failed Authorize calls, with System.InvalidOperationException in FindByClientIdAsync - validation handler using default Application class?

### ISSUE THREAD

**Issue by dysangelist-1** [openiddict/openiddict-core#985]
I'm putting together an OpenIddict 3.x-based auth service (.NET Core 3.1), but am running into problems with custom OpenIddict EF (Core) models. I've managed to reduce things to a repro case based on making some narrow changes to the current (`dev` branch) [Mvc.Server sample](https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server).

The problem: I make a basic GET request of `/connect/authorize` with `client_id` and `response_type` set. Leaving either parameter out, or using an invalid `response_type` value, returns a 400 error page. But with a `client_id=anything&response_type=code`, I get the following stacktrace back in a 500 response:

```
System.InvalidOperationException: Cannot create a DbSet for 'OpenIddictEntityFrameworkCoreApplication' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsTracking[TEntity](IQueryable`1 source)
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreApplicationStore`5.FindByClientIdAsync(String identifier, CancellationToken cancellationToken) in /_/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreApplicationStore.cs:line 303
   at OpenIddict.Core.OpenIddictApplicationCache`1.<>c__DisplayClass6_0.<<FindByClientIdAsync>g__ExecuteAsync|0>d.MoveNext() in /_/src/OpenIddict.Core/Caches/OpenIddictApplicationCache.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at OpenIddict.Core.OpenIddictApplicationManager`1.FindByClientIdAsync(String identifier, CancellationToken cancellationToken) in /_/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs:line 263
   at OpenIddict.Core.OpenIddictApplicationManager`1.OpenIddict.Abstractions.IOpenIddictApplicationManager.FindByClientIdAsync(String identifier, CancellationToken cancellationToken) in /_/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs:line 1376
   at OpenIddict.Server.OpenIddictServerHandlers.Authentication.ValidateClientId.HandleAsync(ValidateAuthorizationRequestContext context) in /_/src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs:line 1056
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.OpenIddictServerHandlers.Authentication.ValidateAuthorizationRequest.HandleAsync(ProcessRequestContext context) in /_/src/OpenIddict.Server/OpenIddictServerHandlers.Authentication.cs:line 185
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.HandleRequestAsync() in /_/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs:line 65
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, br
Cookie: .AspNetCore.Antiforgery.6WSk9eCXbgI=CfDJ8LfTpwh2bqhPuev5FfxYOKKFzZ6C755o99sc93JkiOMERPCQXz4sTkqyvGvN0eNA8CnfoRe1q8T7_5oS17ZzZgoK0YXUnPdv4NREYmlj3j-kOq2QO4ApoqNiGj3pfuJWpXKWN6eAB3iiqNWjWWHqLho
Host: localhost:54540
User-Agent: PostmanRuntime/7.24.1
Postman-Token: 21ea18b1-36cf-4c27-abd0-91e8c5b2019c
```

I've attached a zip file of my repro case project below for convenience, but it was created by taking the [Mvc.Server sample project](https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server) and making the following changes:

1) Replace the project references in `Mvc.Server.csproj` with package references for the OpenIddict 3.0.0-beta1 packages that recently became available on Nuget: 

```XML
<PackageReference Include="OpenIddict.AspNetCore" Version="3.0.0-beta1.20311.67" />
<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="3.0.0-beta1.20311.67" />
```

2) Add custom classes - without any actual custom fields or behaviour - which inherit from the OpenIddict EF Core models, in the same basic form as they've been outlined in various Github issues and SO responses over the last few years:

```C#
public class CustomOpenIdApplication : OpenIddictEntityFrameworkCoreApplication<string, CustomOpenIdAuthorization, CustomOpenIdToken>  {}
public class CustomOpenIdAuthorization : OpenIddictEntityFrameworkCoreAuthorization<string, CustomOpenIdApplication, CustomOpenIdToken> {}
public class CustomOpenIdScope : OpenIddictEntityFrameworkCoreScope<string> {}
public class CustomOpenIdToken : OpenIddictEntityFrameworkCoreToken<string, CustomOpenIdApplication, CustomOpenIdAuthorization> {}
```

3) Use the generic overload of `DbContextOptionsBuilder.UseOpenIddict` in `ConfigureServices`:

```C#
options.UseOpenIddict<CustomOpenIdApplication, CustomOpenIdAuthorization, CustomOpenIdScope, CustomOpenIdToken, string>();
``` 

4) Create an EF migration and run it to establish the database (using the default LocalDB connection string alone): `dotnet ef migrations add InitialCreate`, then `dotnet ef database update`.

5) In `AuthorizationController.cs`, update the `OpenIddict*Manager` types to use the custom classes rather than the `OpenIddictEntityFrameworkCore*` ones:

```C#
public class AuthorizationController : Controller
{
    private readonly OpenIddictApplicationManager<CustomOpenIdApplication> _applicationManager;
    private readonly OpenIddictAuthorizationManager<CustomOpenIdAuthorization> _authorizationManager;
    private readonly OpenIddictScopeManager<CustomOpenIdScope> _scopeManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    private readonly UserManager<ApplicationUser> _userManager;

    public AuthorizationController(
        OpenIddictApplicationManager<CustomOpenIdApplication> applicationManager,
        OpenIddictAuthorizationManager<CustomOpenIdAuthorization> authorizationManager,
        OpenIddictScopeManager<CustomOpenIdScope> scopeManager,
        SignInManager<ApplicationUser> signInManager,
        UserManager<ApplicationUser> userManager)
    {
```
(Note that the above step is not actually necessary to repro the exception, which seems to happen in early validation processing before `AuthorizationController` gets instantiated/injected)

6) Change the data seeding code in `Worker.cs` to get managers for the custom Application and Scope models, rather than the default ones:

```C#
// RegisterApplicationsAsync:
var manager = provider.GetRequiredService<OpenIddictApplicationManager<CustomOpenIdApplication>>();
...
// RegisterScopesAsync:
var manager = provider.GetRequiredService<OpenIddictScopeManager<OpenIddictEntityFrameworkCoreScope>>();
```

(interestingly, when I initially ran the application _without_ having remembered to make this change, it threw exactly the same `Cannot create a DbSet for 'OpenIddictEntityFrameworkCoreApplication'` exception at Startup as detailed above from requesting `/connect/authorize` - a different stacktrace, of course, but following the same basic execution path through `OpenIddictApplicationManager` → `OpenIddictApplicationCache` → `OpenIddictEntityFrameworkCoreApplicationStore`. This makes me wonder if there isn't maybe a subtle typing issue in the OpenIddict code which results in it using a manager for the default entity type rather than my custom one at the point of validating the `client_id` on the `/authorize` request ... and if that isn't entirely off-target, whether there might be some way to work around this with DI type registrations)

That's essentially it - with the above changes made, I run the application (through Kestrel), hit `/connect/authorize?client_id=anything&response_type=code`, and get the 500 + exception back. I've zipped my modified project (with .sln added) and put it on Dropbox, in case anyone wants to skip the steps and get this up and running quickly: [OpenIddict.Mvc.Server-CustomEntities-Repro.zip](https://www.dropbox.com/s/qriu4gqjvzk4mtr/OpenIddict.Mvc.Server-CustomEntities-Repro.zip?dl=0)

I've searched around a bit for similar problems or related bugs, and though the same or very similar errors have definitely been reported a few times over the past few years (always due to the default Application class not being found in the context, and always by way of `FindByClientIdAsync`), nothing seemed relevant to the current code or my repro. I did at one point try changing the DbContext `OnModelCreating` to specify custom table names with `ToTable()`, but, while I probably will do this in my actual project, it doesn't seem to change the outcomes at all (and no surprise there - I haven't added any custom fields to the custom models yet, and even if I had, I think it'd still play out and migrate fine in current EF Core).

The only other detail I can offer is one that I'm admittedly a bit fuzzy on - I think I **might** have been able to get further along with my `/connect/authorize` request testing when I was using OpenIddict 3.x _alpha_ packages from myget.org, prior to the rename of the entities from e.g. `OpenIddictApplication` to `OpenIddictEntityFrameworkCoreApplication`. I could well be completely wrong about that, though, and I haven't attempted to build earlier revs of openiddict-core that might match those packages to verify it, so probably best to take this with a grain of salt.

Anyways, unless I'm missing some crucial (new?) step that's required to properly set up custom models, it appears that you can't successfully use them at all (or at least, can't use a custom `OpenIddictEntityFrameworkCoreApplication` subclass) in the current OpenIddict 3.x beta1.

**Comment by kevinchalet** [comment]
Actually, it looks like you don't override the default models in the OpenIddict EF Core options. Call `ReplaceDefaultEntities` and it should work:

```csharp
services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore()
               .UseDbContext<ApplicationDbContext>()
               .ReplaceDefaultEntities<CustomOpenIdApplication, CustomOpenIdAuthorization, CustomOpenIdScope, CustomOpenIdToken, string>();
    });
```

The syntax hasn't changed in 3.0, but I removed the instructions from README.md to make it lighter. I'll update the samples to mention the entities must be also set in the OpenIddict options.

**Comment by dysangelist-1** [comment]
Many thanks Kevin, no idea how I missed that. I did see some comments about custom entities which included the `ReplaceDefaultEntities` call, but I guess at some point I started to erroneously assume that it was an old OpenIddict thing, rather than a new(er) one. After adding the missing `ReplaceDefaultEntities` call, everything seems to be working as expected.

While I do understand that two different things are being configured here (as discussed on [#614](https://github.com/openiddict/openiddict-core/issues/614)), I do think that, if it could be done without blocking any legitimate use cases, it'd still be a good long-term goal to eliminate the apparent redundancy here, so that custom keys and/or entities only need to be specified once - is there ever a case where I'd use the `UseOpenIddict<App, Auth, Scope, Token, key>` overload but would **not** intend for the `Default*Type` properties to be updated accordingly (or vice versa)?

In any case, I think the [comments you've just added](https://github.com/openiddict/openiddict-core/commit/5738ba0e6fddafd3872cafdc23ff7c8dead73bd1) to the sample `Startup.cs` and the EF helper classes are a great start here - these almost certainly would have been enough to prevent me from tripping over myself on this. Thanks again for all of your good work on OpenIddict (both coding it and patiently explaining it to others on SO/GitHub/Gitter!) 👍

**Comment by kevinchalet** [comment]
> I do think that, if it could be done without blocking any legitimate use cases, it'd still be a good long-term goal to eliminate the apparent redundancy here, so that custom keys and/or entities only need to be specified once - is there ever a case where I'd use the `UseOpenIddict<App, Auth, Scope, Token, key>` overload but would **not** intend for the `Default*Type` properties to be updated accordingly (or vice versa)?

I'd love to, but it's unfortunately not as easy as it should be:
  - EF Core uses an internal DI container for each of the configured `DbContext`. This means `DbContextOptionsBuilder` provides no access to the application DI container we'd need to amend the default entities configured in `OpenIddictCoreOptions`. Concretely, the `options.UseOpenIddict()` helper called from `AddDbContext()` can't be used alone to configure everything. The only thing we could do here is removing the overloads taking generic parameters and resolving them from `OpenIddictCoreOptions`: you'd still need to call `options.UseOpenIddict()`, unfortunately.

  - Since each `DbContext` has its own internal DI container that is configured separately, we can't just update `options.UseEntityFrameworkCore()` to register our `IModelCustomizer` in the application DI container: it's something that must be done using the EF Core `ReplaceService` helper (see https://blog.darkloop.com/post/using-entity-framework-core-imodelcustomizer-to-target-multiple-databases for more information).

If you have an idea to improve this - far from ideal - situation, I'm all ears 😃

**Comment by kevinchalet** [comment]
> Thanks again for all of your good work on OpenIddict (both coding it and patiently explaining it to others on SO/GitHub/Gitter!) 👍

Thanks for the kind words! ❤️
