### ISSUE TITLE
Could not run MVC.server  project in openiddict-core

### ISSUE THREAD

**Issue by ibrmohammed** [openiddict/openiddict-core#99]
got the latest version today. Build was successful.But when I run the MVC.Server solution on IISexpress, it gives me an error.
http://localhost:54540/.  Site can't be reached.

My clr runtime is
![error](https://cloud.githubusercontent.com/assets/5870046/14914526/90b08142-0e28-11e6-839f-95ec1e17b1e4.png)

**Comment by kevinchalet** [comment]
DNX no longer works with OpenIddict: you need to use CLI to run the samples:

Mvc.Client: `dotnet run server.urls=http://localhost:53507/`
Mvc.Server: `dotnet run server.urls=http://localhost:54540/`

**Comment by ibrmohammed** [comment]
@PinpointTownes how could you arrive to a point that I was using dnx but not .NET CLI

**Comment by kevinchalet** [comment]
The screenshot you posted lists all the DNX runtimes installed on your machine, so it was reasonable to think you were using DNX (unless the screenshot has nothing to do with the rest of your question)

That... or I have a crystal ball.

**Comment by ibrmohammed** [comment]
i did install dotnet CLI on my machine. how to check that i am using dotnet runtime.

**Comment by kevinchalet** [comment]
Not sure to understand your question. If you're using commands that begin with "dotnet", then you're using CLI.

**Comment by ibrmohammed** [comment]
got it.so i did try dotnet restore on MVC.Server. got the following errors.
![e2](https://cloud.githubusercontent.com/assets/5870046/14915987/79ee61c0-0e34-11e6-830a-5f7a601c7071.png)

**Comment by kevinchalet** [comment]
Which CLI version are you using? (run dotnet --info)

**Comment by ibrmohammed** [comment]
![e3](https://cloud.githubusercontent.com/assets/5870046/14916116/30f36d70-0e35-11e6-8437-ea539ae6792d.png)

**Comment by kevinchalet** [comment]
I can't reproduce your issue on my machine (and the latest CI build worked fine). I'll ping a friend to confirm this is not a global issue.

**Comment by kevinchalet** [comment]
It's likely an issue with your own configuration as we're unable to reproduce your issue.
I tested the MVC samples on a brand new machine where CLI was not installed yet and it worked fine.

**Comment by ibrmohammed** [comment]
which particluar configuration are you referring to.

**Comment by ibrmohammed** [comment]
I did remove all my dnx runtimes as well

**Comment by kevinchalet** [comment]
Nothing specific: the packages installed on your machine, your CLI version, or something else.

There's nothing I can do since the issue you're seeing is not caused by our samples, so I'd recommend pinging someone from the ASP.NET team to get live assistance.

**Comment by ibrmohammed** [comment]
@PinpointTownes Thanks for helping me out.It worked.
I was missing the json dependency in the project.json that you added yesterday.
close
